#!/usr/bin/env bash

set -u

TEST_DIR=$(cd "$(dirname "$0")" && pwd)
ROOT_DIR=$(cd "$TEST_DIR/../../.." && pwd)
TEST_CMD=$TEST_DIR/test
MZN_CMD=$ROOT_DIR/tools/flatzinc/mzn-gstrings
MODE=${1:-}
TOUT=${GSTRINGS_TEST_TIMEOUT:-10}
X=$(mktemp "${TMPDIR:-/tmp}/gstrings-output.XXXXXX")
Z=$(mktemp "${TMPDIR:-/tmp}/gstrings-diff.XXXXXX")
trap 'rm -f "$X" "$Z"' EXIT HUP INT TERM

run_cpp() {
  if [[ -n $MODE ]]; then
    "$TEST_CMD" "$@" "$MODE"
  else
    "$TEST_CMD" "$@"
  fi
}

run_mzn_with_timeout() {
  local model=$1
  timeout "$TOUT" "$MZN_CMD" "$model" > "$X"
  local status=$?
  if [[ $status -eq 0 ]]; then
    return 0
  fi
  if [[ $status -eq 124 ]]; then
    echo "Error! Timed out after ${TOUT}s: $model"
  else
    echo "Error! MiniZinc solver exited with status $status: $model"
  fi
  return "$status"
}

cd "$ROOT_DIR"
make -j4 compilelib &&
make -j1 tools/flatzinc/fzn-gecode || exit $?

if
  [[ $MODE != "mzn" ]]
then
  run_cpp $TEST_DIR/anbn.cpp           10000 &&
  run_cpp $TEST_DIR/chunk_split.cpp    10000 &&
  run_cpp $TEST_DIR/hamming_mod.cpp    10000 &&
  run_cpp $TEST_DIR/levenshtein.cpp    10000 &&
  run_cpp $TEST_DIR/string_replace.cpp 10000 &&
  if
    [[ $MODE == "opt" ]]
  then
    # Optimised mode, timeout depends on the target machine!
    timeout 2 $TEST_CMD $TEST_DIR/sql.cpp 11    &&
    timeout 2 $TEST_CMD $TEST_DIR/sql.cpp 12    &&
    timeout 2 $TEST_CMD $TEST_DIR/sql.cpp 100   &&
    timeout 2 $TEST_CMD $TEST_DIR/sql.cpp 200   &&
    timeout 3 $TEST_CMD $TEST_DIR/sql.cpp 250   &&
    timeout 3 $TEST_CMD $TEST_DIR/sql.cpp 300   &&
    timeout 2 $TEST_CMD $TEST_DIR/sql.cpp 400   &&
    timeout 2 $TEST_CMD $TEST_DIR/sql.cpp 500   &&
    timeout 2 $TEST_CMD $TEST_DIR/sql.cpp 1000  &&
    timeout 2 $TEST_CMD $TEST_DIR/sql.cpp 2500  &&
    timeout 3 $TEST_CMD $TEST_DIR/sql.cpp 5000  &&
    timeout 2 $TEST_CMD $TEST_DIR/sql.cpp 10000
  else
    # Debug mode.
    for i in 11 12 100 200 250 300 400 500
    do
      run_cpp $TEST_DIR/sql.cpp $i
      if
        [ $? -ne 0 ]
      then
        exit 1
      fi
    done &&
    for i in 1000 2500 5000 10000
    do
      $TEST_CMD $TEST_DIR/sql.cpp $i
      if
        [ $? -ne 0 ]
      then
        exit 1
      fi
    done
  fi
  ret=$?
  if 
    [[ $ret -ne 0 ]]
  then
    echo "Error $ret"
    exit $ret
  fi
  declare -a TESTS=( \
      'str_test1.cpp' 'str_test2.cpp' 'str_test3.cpp'\
      'char_at.cpp' 'substring.cpp' 'element.cpp' 'find.cpp' 'replace.cpp'\
      'length.cpp'\
      'char2code.cpp' 'pow.cpp' 'branch.cpp'\
      'str_ex1.cpp' 'str_ex2.cpp' 'str_ex3.cpp'\
      'str_ex4.cpp' 'str_ex5.cpp' 'str_ex6.cpp' 'str_ex7.cpp' 'str_ex8.cpp'\
      'str_ex9.cpp' 'str_ex10.cpp' 'str_ex11.cpp' 'str_ex12.cpp'\
      'palindrome.cpp' 'gray.cpp' 'min_superstr.cpp' 'shortest_match.cpp'\
      'longest_match.cpp')
  for t in "${TESTS[@]}"
  do
    echo "===== Testing $t ====="
    run_cpp $TEST_DIR/$t
    if
      [ $? -ne 0 ]
    then
      exit 1
    fi
    echo "===== Done! ====="
  done
fi &&
"$MZN_CMD" $TEST_DIR/test.mzn > $X
Y=$TEST_DIR/output_mzn
diff $X $Y > $Z
if
  [ -s $Z ]
then
  echo "Error! MZN output not expected!"
  cat $Z
  exit 1
fi &&
cat $X && 
echo "Solving ex_js.mzn"
"$MZN_CMD" $TEST_DIR/ex_js.mzn > $X
x=`grep -a SVAL_TMP3 "$X" | awk -F" = " '{print $2}'`
if
  [ "$x" == "Hello0;" ]
then
  cat $X
else
  echo "Error! MZN output not expected!"
  cat $X
  exit 1
fi &&
echo "Solving decode.mzn"
"$MZN_CMD" $TEST_DIR/decode.mzn > $X
x=`grep -a "x = array1d" "$X" | awk -F"[" '{print $2}' | sed "s/]);//g"`
if
  [ "$x" == "01100011, 01100001, 01110011, 01100110, 01101111, 01110010, 01110100, 01100101" ]
then
  cat $X
else
  echo "Error! MZN output not expected!"
  cat $X
  exit 1
fi &&
echo "Solving max_pattern.mzn"
"$MZN_CMD" $TEST_DIR/max_pattern.mzn > $X
if
  grep -aq "obj = 4" "$X" && grep -aq "==========" "$X"
then
  cat $X
else
  echo "Error! MZN output not expected!"
  cat $X
  exit 1
fi &&
echo "Solving mfp.mzn"
"$MZN_CMD" $TEST_DIR/mfp.mzn > $X
if
  grep -aq "CENTROCAMPO" "$X" && grep -aq "==========" "$X"
then
  cat $X
else
  echo "Error! MZN output not expected!"
  cat $X
  exit 1
fi &&
for m in `ls $TEST_DIR/appscan/*.mzn`
do  
  run_mzn_with_timeout "$m" || exit 1
  if
    grep -aq -- "----------" "$X"
  then
    echo "Solved $m"
  else
    echo "Error! $m not sound."
    exit 1
  fi
done &&
for m in `ls $TEST_DIR/pisa/*.mzn | sort`
do
  run_mzn_with_timeout "$m" || exit 1
  if
    grep -aq -- "----------" "$X"
  then
    m=`basename $m`
    res=`grep $m $TEST_DIR/pisa/pisa_check.txt | awk '{print $2}'`
    if
      [[ $res == "sat" ]]
    then
      echo "Solved $m!"
    else
      echo "Error! $m not sound."
      exit 1
    fi
  elif 
    grep -aq "=====UNSATISFIABLE=====" "$X"
  then
    m=`basename $m`
    res=`grep $m $TEST_DIR/pisa/pisa_check.txt | awk '{print $2}'`
    if
      [[ $res == "uns" ]]
    then
      echo "Solved $m!"
    else
      echo "Error! $m not sound."
      exit 1
    fi
  else
    echo "Error! $m not sound."
    exit 1
  fi
done &&
for m in `ls $TEST_DIR/stranger/*.mzn | sort`
do
  run_mzn_with_timeout "$m" || exit 1
  if 
    grep -q replace_all "$m"
  then  
    r=`echo $m | sed 's/.all//g'`
  elif 
    grep -q replace_last "$m"
  then  
    r=`echo $m | sed 's/.last//g'`
  else
    r=$m
  fi
  r=`basename $r`
  if
    grep -aq -- "----------" "$X"
  then
    res=`grep ^$r $TEST_DIR/stranger/stranger_check.txt | awk '{print $2}'`
    if
      [[ $res == "sat" ]]
    then
      echo "Solved $m!"
    else
      echo "Error! $m not sound."
      exit 1
    fi
  elif 
    grep -aq "=====UNSATISFIABLE=====" "$X"
  then
    res=`grep ^$r $TEST_DIR/stranger/stranger_check.txt | awk '{print $2}'`
    if
      [[ $res == "uns" ]]
    then
      echo "Solved $m!"
    else
      echo "Error! $m not sound."
      exit 1
    fi
  else
    echo "Error! $m not sound."
    exit 1
  fi
done &&
for m in `ls $TEST_DIR/norn/*/*.mzn | sort`
do
  echo "Solving $m..."
  run_mzn_with_timeout "$m" || exit 1
  if
    grep -aq -- "----------" "$X"
  then
    m=`basename $m`
    res=`grep $m $TEST_DIR/norn/norn_check.txt | awk '{print $2}'`
    if
      [[ $res == "sat" ]]
    then
      echo "Solved $m!"
    else
      echo "Error! $m not found."
      exit 1
    fi
  elif 
    grep -aq "=====UNSATISFIABLE=====" "$X"
  then
    m=`basename $m`
    res=`grep $m $TEST_DIR/norn/norn_check.txt | awk '{print $2}'`
    if
      [[ $res == "uns" ]]
    then
      echo "Solved $m!"
    else
      echo "Error! $m not sound."
      exit 1
    fi
  else
    echo "Error! $m not sound."
    exit 1
  fi
done &&
echo "===== All good! ====="

