#!/bin/bash

TEST_DIR="${0%/*}"
TEST_CMD=$TEST_DIR/test_cpp.sh
declare -a TESTS=(
  'test-eq.cpp' 'test-prop.cpp' 'str_ex1.cpp' 'str_ex2.cpp' 'str_ex3.cpp' \
  'anbn.cpp' 'chunk_split.cpp' 'hamming_mod.cpp' 'levenshtein.cpp'
)

if
  [[ $1 == "dep" ]]
then
  make depend
fi &&
make -j 4 && sudo make install &&

for t in "${TESTS[@]}"
do
  echo "===== Testing $t ====="
  $TEST_CMD $TEST_DIR/$t $1 $2
  if
    [ $? -ne 0 ]
  then
    exit 1
  fi
  echo "===== All tests pass! ====="
done
