#!/bin/bash

TEST_DIR="${0%/*}"
TEST_CMD=$TEST_DIR/test_cpp.sh
declare -a TESTS=(
  'str_test1.cpp' 'str_test2.cpp' 'str_test3.cpp' 'str_test4.cpp' \
  'str_ex1.cpp' 'str_ex2.cpp' 'str_ex3.cpp' 'str_ex4.cpp' 'str_ex7.cpp' \
  'str_ex8.cpp' 'str_ex12.cpp' \
  'anbn.cpp' 'chunk_split.cpp' 'hamming_mod.cpp' 'levenshtein.cpp' \
  'string_replace.cpp' 'gray.cpp' 'scs.cpp' 
)
X=$TEST_DIR/x
Y=$TEST_DIR/y
Z=$TEST_DIR/z

if
  [[ $1 == "dep" ]]
then
  make depend
fi &&
make -j 4 && sudo make install &&
if
  [[ $1 != "mzn" ]]
then
  for t in "${TESTS[@]}"
  do
    echo "===== Testing $t ====="
    $TEST_CMD $TEST_DIR/$t $1 $2
    if
      [ $? -ne 0 ]
    then
      exit 1
    fi
  done &&
  for i in 11 13 100 200 250 300 400 500
      do
        $TEST_CMD $TEST_DIR/sql.cpp $i $1
        if
          [ $? -ne 0 ]
        then
          exit 1
        fi
      done &&
      for i in 1000 2500 5000 10000
      do
        $TEST_CMD $TEST_DIR/sql.cpp $i
        if
          [ $? -ne 0 ]
        then
          exit 1
        fi
      done
fi &&
mzn-dashed $TEST_DIR/test.mzn > $X
diff $X $TEST_DIR/output_mzn > $Y
if
  [ -s $Y ]
then
  echo "Error! MZN output not expected. See $X and $Y logs."
  cat $Y
  exit 1
else
  cat $X
  rm $Y
fi &&
# FIXME: Timeout depends on the target machine.
TOUT=2
for m in `ls $TEST_DIR/pisa/*.mzn | sort -n`
do
  timeout $TOUT mzn-dashed $m > $X
  ret=$?
  m=`basename $m`
  if
    [[ `grep "\----------" $X` ]]
  then
#    cat $X | grep -v "\----------" > $Y.dzn
    res=`grep $m $TEST_DIR/pisa/pisa_check.txt | awk '{print $2}'`
    if
      [[ $res == "sat" ]]
    then
      echo "$m sat"
    else
      echo "Error! $m incorrect."
      rm $X
      exit 1
    fi
  elif 
    [[ `grep "=====UNSATISFIABLE=====" $X` ]]
  then
    res=`grep $m $TEST_DIR/pisa/pisa_check.txt | awk '{print $2}'`
    if
      [[ $res == "uns" ]]
    then
      echo "$m unsat"
    else
      echo "Error! $m incorrect."
      rm $X
      exit 1
    fi
  else
    if
      [[ $ret -eq 124 ]]
    then
      echo "$m timeout"
    else
      echo "$m unknown"
      rm $X
      exit 1
    fi
  fi
done &&
for m in `ls $TEST_DIR/woorpje/*.mzn | sort -n`
do
  timeout $TOUT mzn-dashed $m > $X
  ret=$?
  m=`basename $m`
  if
    [[ `grep "\----------" $X` ]]
  then
#    cat $X | grep -v "\----------" > $Y.dzn
    res=`grep $m $TEST_DIR/woorpje/woorpje_res.csv | awk '{print $2}'`
    if
      [[ $res == "SAT" ]]
    then
      echo "$m sat"
    else
      echo "Error! $m incorrect."
      rm $X
      exit 1
    fi
  elif 
    [[ `grep "=====UNSATISFIABLE=====" $X` ]]
  then
    res=`grep $m $TEST_DIR/woorpje/woorpje_res.csv | awk '{print $2}'`
    if
      [[ $res == "UNSAT" ]]
    then
      echo "$m unsat"
    else
      echo "Error! $m incorrect."
      rm $X
      exit 1
    fi
  else
    if
      [[ $ret -eq 124 ]]
    then
      echo "$m timeout"
    else
      echo "$m unknown"
      rm $X
      exit 1
    fi
  fi
done &&
echo "===== All tests pass! ====="
rm $X
