var string: D;
var string: E;
var string: A;
constraint
  (("ff") ++ (A) ++ ("b") ++ (A) ++ ("eagacdebfegegdbeaeggdaegeegebfcgbfgefe") ++ (A) ++ ("edafb") ++ (A) ++ ("dddf") ++ (E) ++ ("bbbaa") ++ (A) ++ ("daaccab") ++ (A) ++ ("dfedffeea"))
    =
    (("ffcbceaga") ++ (A) ++ ("debfegegdbeaeggdaegeegebfcg") ++ (D) ++ (A) ++ ("dddf") ++ (E) ++ ("bbbaacdaa") ++ (A) ++ ("cab") ++ (A) ++ ("dfedffeea"));
solve satisfy;
