var string: L;
var string: D;
var string: A;
constraint
  (("dbc") ++ (A) ++ ("h") ++ (A) ++ ("hhcahiigib") ++ (A) ++ ("ie") ++ (A) ++ ("dgcgacihfifd") ++ (A) ++ (L) ++ ("e") ++ (A) ++ ("dahgeeibhhfiaeehha") ++ (A) ++ ("fccgfeagegg"))
    =
    (("dbc") ++ (A) ++ (D) ++ ("iff") ++ (A) ++ ("agg") ++ (A) ++ (A) ++ (A) ++ ("bafe") ++ (A) ++ ("da") ++ (A) ++ ("geeibhhfiaee") ++ (A) ++ (A) ++ ("a") ++ (A) ++ ("fccgfeagegg"));
solve satisfy;
