var string: H;
var string: E;
var string: J;
var string: O;
var string: M;
var string: D;
constraint
  (("ebf") ++ (E) ++ ("jihfch") ++ (D) ++ ("da") ++ (J) ++ ("c") ++ (H) ++ (J) ++ ("c") ++ (D) ++ ("jgc") ++ (D) ++ ("aci") ++ (D) ++ ("hhhh") ++ (J) ++ (D) ++ ("i") ++ (D) ++ ("ajfefccghiahgdbjdd") ++ (D))
    =
    ((O) ++ ("jafijihfchjda") ++ (J) ++ ("cahaecjjg") ++ (M) ++ ("hh") ++ (J) ++ ("ji") ++ (D) ++ ("a") ++ (D) ++ ("f") ++ (J) ++ ("fccghiahgdbjdd") ++ (D));
solve satisfy;
