var string: A;
constraint
  ((A) ++ ("aaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ ("aaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ ("aaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ ("aaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ ("aaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ ("aaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ ("aaaaaaaaaaa") ++ ("")) = ((A) ++ ("aaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ ("aaaaaaaaaaa") ++ ("")) = ((A) ++ ("aaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ ("aaaaaaaaaaa") ++ ("")) = ((A) ++ ("aaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ ("aaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ ("aaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ ("aaaaaaaaaaa") ++ ("")) = ((A) ++ ("aaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ ("aaaaaaaaaaa") ++ ("")) = ((A) ++ ("aaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ ("aaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ ("aaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ ("aaaaaaaaaaa") ++ ("")) = ((A) ++ ("aaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ ("aaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ ("aaaaaaaaaaa") ++ ("")) = ((A) ++ ("aaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ ("aaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ ("aaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ ("aaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ ("aaaaaaaaaaa") ++ ("")) = ((A) ++ ("aaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ ("aaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ ("aaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ ("aaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ ("aaaaaaaaaaa") ++ ("")) = ((A) ++ ("aaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ ("aaaaaaaaaaa") ++ ("")) = ((A) ++ ("aaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ ("aaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ ("aaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
solve satisfy;
