var string: B;
var string: A;
var string: C;
var string: D;
constraint
  ((D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    =
    ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) = ((B) ++ ("aaaaaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"))
    = ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((C) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ (D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((A) ++ ("aa") ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaa")) =
    ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((C) ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaa")) =
    ((D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ ("aa") ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaa")) =
    ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ (D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"))
    = ((A) ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((C) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((C) ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaa")) =
    ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((C) ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaa")) =
    ((A) ++ (D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((C) ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaa")) =
    ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaa"))
    = ((A) ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ (D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((C) ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (D) ++ ("aaaaaaaaaaaaaaaaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (D) ++ ("aaaaaaaaaaaaaaaaaaa"))
    = ((A) ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((C) ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaa")) =
    ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((A) ++ (D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaa")) =
    ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((C) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaa")) =
    ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((D) ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"))
    =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((A) ++ ("aa") ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaa")) =
    ((A) ++ (D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaa"))
    =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((C) ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((C) ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaa")) =
    ((D) ++ (D) ++ ("aaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((C) ++ (D) ++ ("aaaaaaaaaaaaaaaaaaaaaa")) =
    ((B) ++ ("aaaaaaaaaaaaaa") ++ (""));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((D) ++ (D) ++ ("aaaaaaaaaaaaaaaaaaa")) =
    ((A) ++ (D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((C) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaa"))
    = ((D) ++ (D) ++ ("aaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((C) ++ ("aaa") ++ (D) ++ ("aaaaaaaaaaaaaaaaaaa"));
constraint
  ((C) ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaa")) =
    ((D) ++ (D) ++ ("aaaaaaaaaaaaaaaaaaa"));
constraint
  ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ (D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((A) ++ ("aa") ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaa")) =
    ((D) ++ (D) ++ ("aaaaaaaaaaaaaaaaaaa"));
constraint
  ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa")) =
    ((C) ++ ("aaa") ++ (D) ++ ("aaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (D) ++ ("aaaaaaaaaaaaaaaaaaa"));
constraint
  ((C) ++ (D) ++ ("aaaaaaaaaaaaaaaaaaaaaa")) =
    ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) = ((B) ++ ("aaaaaaaaaaaaaa") ++ (""));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((C) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaa")) =
    ((D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaa"))
    = ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((C) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaa"))
    = ((A) ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((C) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((C) ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaa")) =
    ((D) ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaa"))
    = ((D) ++ (D) ++ ("aaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ (D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((C) ++ (D) ++ ("aaaaaaaaaaaaaaaaaaaaaa")) =
    ((C) ++ ("aaa") ++ (D) ++ ("aaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (D) ++ ("aaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((D) ++ (D) ++ ("aaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa")) =
    ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((C) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaa")) =
    ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((D) ++ (D) ++ ("aaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((D) ++ (D) ++ ("aaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaa"))
    = ((A) ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (D) ++ ("aaaaaaaaaaaaaaaaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaa"))
    = ((D) ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa")) =
    ((C) ++ ("aaa") ++ (D) ++ ("aaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ (D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((C) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaa")) =
    ((D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaa"))
    = ((A) ++ (D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((C) ++ (D) ++ ("aaaaaaaaaaaaaaaaaaaaaa")) =
    ((A) ++ (A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ (C) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaa"));
solve satisfy;
