var string: B;
var string: A;
var string: C;
constraint
  (("babacbacac") ++ (B) ++ ("baabccbcbabcaabbabbac")) =
    (("babacbaca") ++ (A) ++ ("bcababbaabccbcbabcaabbabbac"));
constraint
  (("abbccacbabaccbcabbababcbcbbccbaaaaaa") ++ (A)) =
    (("abbccacbabaccbcabbababcbcbbccbaaaaaacbcbbbccb") ++ (""));
constraint
  (("caacbaccbab") ++ (C) ++ ("baabccbcbacacca")) =
    (("caacbaccbaba") ++ (B) ++ ("bcbacacca"));
constraint
  (("bcbaab") ++ (C) ++ ("abcbacabacaccaabb")) =
    (("bcbaabacccaabcbcb") ++ (B) ++ ("b"));
constraint
  (("cabcbacabbccbcbc") ++ (C) ++ ("cabacbcacabcbaaaccbccaa")) =
    (("cabcbacabbccbcbc") ++ (C) ++ ("cabacbcacabcbaaaccbccaa"));
constraint
  (("cabbcbabbaacbcabaccbababcccccac") ++ (C) ++ ("abbabaac")) =
    (("cabbcbabbaacbcabaccbababcccccac") ++ (C) ++ ("abbabaac"));
constraint
  (("ccaaccaab") ++ (C) ++ ("abccababcbabacacbcaabbabaacccc")) =
    (("ccaaccaabcbcbababccababcbabacacbcaabbabaacccc") ++ (""));
constraint
  (("acbbaaacbbaaacacbbbabaccacbcbababccbbccabccca") ++ ("")) =
    (("acbbaaacbbaaacacbbbabacca") ++ (C) ++ ("abccbbccabccca"));
constraint
  (("abbbaaccbccacaabcccbcccbaaaccacbcbabaccacacbb") ++ ("")) =
    (("abbbaaccbccacaabcccbcccbaaacca") ++ (C) ++ ("accacacbb"));
constraint
  (("acacacccccbbbcb") ++ (C) ++ ("bbaaaccccaaabcbabacccbcc")) =
    (("acacacccccbbbcbcbcbabbbaaaccccaaabcbabacccbcc") ++ (""));
constraint
  (("aacaaccacaaacbbacaacbaaaccccbaaacacaab") ++ (C) ++ ("a")) =
    (("aacaaccacaaacbbacaacbaaaccccbaaacacaabcbcbaba") ++ (""));
constraint
  (("bbcabccbbccacaccaabbbaaba") ++ (C) ++ ("aaccbcbccbccca")) =
    (("bbcabccbbccacaccaabbbaabacbcbabaaccbcbccbccca") ++ (""));
constraint
  (("acabcacabbbaccbacababcccbababcbccc") ++ (C) ++ ("cbaac")) =
    (("acabcacabbbaccbacababcccbababcbccc") ++ (C) ++ ("cbaac"));
constraint
  (("abcbcbabababbbaaabbcacaaaacabacbbacababbaaccb") ++ ("")) =
    (("ab") ++ (C) ++ ("ababbbaaabbcacaaaacabacbbacababbaaccb"));
constraint
  (("caccccbaacabaaaaacaccaacbbbbcbaa") ++ (C) ++ ("babacbb")) =
    (("caccccbaacabaaaaacaccaacbbbbcbaacbcbabbabacbb") ++ (""));
constraint
  (("aabbb") ++ (C) ++ ("cbccccccabaaababbccacbaccbbcbcacca")) =
    (("aabbb") ++ (C) ++ ("cbccccccabaaababbccacbaccbbcbcacca"));
constraint
  (("abcbccccacccbcababbbacccabbba") ++ (C) ++ ("cbbbccabab")) =
    (("abcbccccacccbcababbbacccabbba") ++ (C) ++ ("cbbbccabab"));
constraint
  (("bccbbaabccbcaabaccbcbccbcbcabbbbbcbcbabcacacb") ++ ("")) =
    (("bccbbaabccbcaabaccbcbccbcbcabbbbb") ++ (C) ++ ("cacacb"));
constraint
  (("bcabacbbcacbaccacccaaccacaaabb") ++ (C) ++ ("bcbbcabac")) =
    (("bcabacbbcacbaccacccaaccacaaabbcbcbabbcbbcabac") ++ (""));
constraint
  (("aacaabcbcbabcabbccaaaccacccacccacaacabababbaa") ++ ("")) =
    (("aacaab") ++ (C) ++ ("cabbccaaaccacccacccacaacabababbaa"));
constraint
  (("cbbcbbacbbabbbbababbacbcbabcbcbcbcbabcabbcccb") ++ ("")) =
    (("cbbcbbacbbabbbbababba") ++ (C) ++ ("cbcbcbcbabcabbcccb"));
constraint
  (("bccccabbcabbacacbabccbcbabccabaacbabcccabccca") ++ ("")) =
    (("bccccabbcabbacacbabc") ++ (C) ++ ("ccabaacbabcccabccca"));
constraint
  (("ccabbccaa") ++ (C) ++ ("bbaabaaaababbbbccccbcabaacbcac")) =
    (("ccabbccaacbcbabbbaabaaaababbbbccccbcabaacbcac") ++ (""));
constraint
  (("acaacbabaacbaccacbccaaccbcbcb") ++ (C) ++ ("abaaacacab")) =
    (("acaacbabaacbaccacbccaaccbcbcbcbcbababaaacacab") ++ (""));
constraint
  (("cbbaa") ++ (C) ++ ("cbaabbcbcccbacaccaacbacbbcabbcbaca")) =
    (("cbbaacbcbabcbaabbcbcccbacaccaacbacbbcabbcbaca") ++ (""));
constraint
  (("bbbccbccbcbaaacabaacab") ++ (C) ++ ("abbbbabcbbccaccba")) =
    (("bbbccbccbcbaaacabaacab") ++ (C) ++ ("abbbbabcbbccaccba"));
constraint
  (("bcbcabcabcabacaabbacbcbcbacaacaacaabac") ++ (C) ++ ("b")) =
    (("bcbcabcabcabacaabbacbcbcbacaacaacaabaccbcbabb") ++ (""));
constraint
  (("bbacc") ++ (C) ++ ("bbbbbabbabbcccbbaaabababacbbccabca")) =
    (("bbacc") ++ (C) ++ ("bbbbbabbabbcccbbaaabababacbbccabca"));
constraint
  (("bcbacabcccbbcccaccaab") ++ (C) ++ ("bbcacaaacaccbcbacc")) =
    (("bcbacabcccbbcccaccaab") ++ (C) ++ ("bbcacaaacaccbcbacc"));
constraint
  (("baccbabacccacca") ++ (C) ++ ("bcacbaabcbbabcbaaaaabcaa")) =
    (("baccbabacccaccacbcbabbcacbaabcbbabcbaaaaabcaa") ++ (""));
constraint
  (("ccccabbbaabccccbabbabcc") ++ (C) ++ ("bbbcaccbccacabab")) =
    (("ccccabbbaabccccbabbabcc") ++ (C) ++ ("bbbcaccbccacabab"));
constraint
  (("cccbcaabbaccacbcabcb") ++ (C) ++ ("baabbabbaabbbabccab")) =
    (("cccbcaabbaccacbcabcbcbcbabbaabbabbaabbbabccab") ++ (""));
constraint
  (("ccabcbabcabbcbccca") ++ (C) ++ ("bbccbaaabacabaaabcbcb")) =
    (("ccabcbabcabbcbcccacbcbabbbccbaaabacabaaabcbcb") ++ (""));
constraint
  (("acaaca") ++ (C) ++ ("bcbcabcbcabcabcabbbacbcbccccabbbc")) =
    (("acaaca") ++ (C) ++ ("bcbcabcbcabcabcabbbacbcbccccabbbc"));
constraint
  (("bbaabbbbacaabccacbbacbccaacbccacaabba") ++ (C) ++ ("cb")) =
    (("bbaabbbbacaabccacbbacbccaacbccacaabba") ++ (C) ++ ("cb"));
constraint
  (("ccccaacabccabaacbcbabccccbacacacbcaaabbacbbab") ++ ("")) =
    (("ccccaacabccabaa") ++ (C) ++ ("ccccbacacacbcaaabbacbbab"));
constraint
  (("bbbbbaccbcbbccbcbabacbbbabcbbacaccacbbaaaacbb") ++ ("")) =
    (("bbbbbaccbcbbc") ++ (C) ++ ("acbbbabcbbacaccacbbaaaacbb"));
constraint
  (("cbaacacabcbaabaaabc") ++ (C) ++ ("abbaaccbabcababbcacb")) =
    (("cbaacacabcbaabaaabc") ++ (C) ++ ("abbaaccbabcababbcacb"));
constraint
  (("bbaabaaaaacaabccbacaaccacbbcacaaccaabcb") ++ (C)) =
    (("bbaabaaaaacaabccbacaaccacbbcacaaccaabcbcbcbab") ++ (""));
constraint
  (("cbababcacbcbababbbcbcbccbabcabbaacccaaccaabaa") ++ ("")) =
    (("cbababca") ++ (C) ++ ("abbbcbcbccbabcabbaacccaaccaabaa"));
constraint
  (("acbc") ++ (C) ++ ("cccacbbcbcbcbbbbccbaccbaaababbabbbb")) =
    (("acbc") ++ (C) ++ ("cccacbbcbcbcbbbbccbaccbaaababbabbbb"));
constraint
  (("caacabcbaccbbaccabbbaabccbabacbccbcbabcbabbbb") ++ ("")) =
    (("caacabcbaccbbaccabbbaabccbabacbc") ++ (C) ++ ("cbabbbb"));
constraint
  (("cbabacbaabbbbcbcbac") ++ (C) ++ ("aacbcacacbabbcbcccba")) =
    (("cbabacbaabbbbcbcbac") ++ (C) ++ ("aacbcacacbabbcbcccba"));
constraint
  ((C) ++ ("abcbaabaaaaaaabbacabbabcbbcacbcaaacaaab") ++ ("")) =
    (("cbcbababcbaabaaaaaaabbacabbabcbbcacbcaaacaaab") ++ (""));
constraint
  (("abcbacacaabcbccbabaaaaa") ++ (C) ++ ("abbabcbbcabbabab")) =
    (("abcbacacaabcbccbabaaaaacbcbababbabcbbcabbabab") ++ (""));
constraint
  (("accaabababbbbbcaaabcacaacc") ++ (C) ++ ("bbaaacaaacacb")) =
    (("accaabababbbbbcaaabcacaacc") ++ (C) ++ ("bbaaacaaacacb"));
constraint
  (("cbbbbaabababcbbaaccbbaccbaaac") ++ (C) ++ ("cccbcbacab")) =
    (("cbbbbaabababcbbaaccbbaccbaaac") ++ (C) ++ ("cccbcbacab"));
constraint
  (("abaacacabcba") ++ (C) ++ ("abccbaaaaaacaabcccacccab")) =
    (("abaacacabcba") ++ (C) ++ ("abccbaaaaaacaabcccacccab"));
constraint
  (("aaabcccbbaaccbcbaacccbacbcbcbcaacbabcbcacbbca") ++ ("")) =
    (("aaabcccbbaaccbcbaacccbac") ++ (C) ++ ("babcbcacbbca"));
constraint
  (("baccacabccaaaaababa") ++ (C) ++ ("abacbaaacccabcbba")) =
    (("baccacabccaaaaabababcbcbcaacabacbaaacccabcbba") ++ (""));
constraint
  (("acabcabcbcbcaacbbbbbabcababcacaaacbccbacccaba") ++ ("")) =
    (("acabca") ++ (C) ++ ("bbbbbabcababcacaaacbccbacccaba"));
constraint
  (("accbabbabbaabcbccccccaca") ++ (C) ++ ("babbbaababaa")) =
    (("accbabbabbaabcbccccccacabcbcbcaacbabbbaababaa") ++ (""));
constraint
  (("bca") ++ (C) ++ ("aabccbcbc")) =
    (("bcaabbabbcbcbbabc") ++ (B) ++ ("bbacaaccbacbaabccbcbc"));
constraint
  (("bababbcbcbccccabcacbaabbabcaaccaacbaababaabab") ++ ("")) =
    (("bababbcbcbccccabcacbaabbabcaaccaa") ++ (B) ++ ("aabab"));
constraint
  (("cbbaacbaccbb") ++ (B) ++ ("cccababbcaaacccacaabcaabac")) =
    (("cbbaacbaccbb") ++ (B) ++ ("cccababbcaaacccacaabcaabac"));
constraint
  (("cccaacaabccbaacccaccbcaaccaccbaababcababaacaa") ++ ("")) =
    (("cccaacaabccbaacccaccbcaaccac") ++ (B) ++ ("cababaacaa"));
constraint
  (("bbcbaababaccabbaccacbaaccbcbaacacbbcbccacbbcc") ++ ("")) =
    (("bb") ++ (B) ++ ("accabbaccacbaaccbcbaacacbbcbccacbbcc"));
constraint
  (("cabbbabacbbaabcaccccccbaababccccaacaaabcbcaba") ++ ("")) =
    (("cabbbabacbbaabcaccccc") ++ (B) ++ ("ccccaacaaabcbcaba"));
constraint
  (("acacbccbbaaabbcbbbaaabccbababcbccbb") ++ (B) ++ ("cbb")) =
    (("acacbccbbaaabbcbbbaaabccbababcbccbbcbaababcbb") ++ (""));
constraint
  (("bbcabbabccacabbbaacaacbbabbacbacacca") ++ (B) ++ ("cb")) =
    (("bbcabbabccacabbbaacaacbbabbacbacacca") ++ (B) ++ ("cb"));
constraint
  (("c") ++ (B) ++ ("accaaabcbcbccacaacaaacbcabbbbbccaabbb")) =
    (("c") ++ (B) ++ ("accaaabcbcbccacaacaaacbcabbbbbccaabbb"));
constraint
  (("abcbaccc") ++ (B) ++ ("bbabcccbcbbaabbcbaccacbcccccbb")) =
    (("abcbaccccbaababbbabcccbcbbaabbcbaccacbcccccbb") ++ (""));
constraint
  (("bcbcc") ++ (B) ++ ("aaabbbccbbcbcbbcacccaccabccabccbb")) =
    (("bcbcc") ++ (B) ++ ("aaabbbccbbcbcbbcacccaccabccabccbb"));
constraint
  (("bacaaaacaacbabcca") ++ (B) ++ ("bcbacbbaaccbbababcaaa")) =
    (("bacaaaacaacbabcca") ++ (B) ++ ("bcbacbbaaccbbababcaaa"));
constraint
  (("cbbbcaacacbacacbbbcbaccccbaababbcbaaaacacbaba") ++ ("")) =
    (("cbbbcaacacbacacbbbcbaccc") ++ (B) ++ ("bcbaaaacacbaba"));
constraint
  (("aabaccaccaabcbacbaaccbbbcababbabaaaccbaababcb") ++ ("")) =
    (("aabaccaccaabcbacbaaccbbbcababbabaaac") ++ (B) ++ ("cb"));
constraint
  (("baacbcbaababaacacbcbbbabcaaaaacbcbcbaabcccbaa") ++ ("")) =
    (("baacb") ++ (B) ++ ("aacacbcbbbabcaaaaacbcbcbaabcccbaa"));
constraint
  (("bbcbccbaaaccababcacbccabcc") ++ (B) ++ ("ccbccbcbccba")) =
    (("bbcbccbaaaccababcacbccabcccbaababccbccbcbccba") ++ (""));
constraint
  (("bcbbcaaabc") ++ (A) ++ ("bbaacaaccbaccccbbcb")) =
    (("bcbbcaaabc") ++ (A) ++ ("bbaacaaccbaccccbbcb"));
constraint
  (("accaaa") ++ (C) ++ ("acbacacbbccbbca")) =
    (("ac") ++ (B) ++ ("cbacacbbccbbca"));
constraint
  ((A) ++ ("bccbccaccbbbbcaabb") ++ ("")) =
    ((A) ++ ("bccbccaccbbbbcaabb") ++ (""));
constraint
  (("b") ++ (A) ++ ("aaccbcbcbcabbbca") ++ (B) ++ ("aabcbcbbacbab")) =
    (("bcacaac") ++ (B) ++ ("cccbaaaccbcbcbcabbbca") ++ (B) ++ ("aabcbcbbac") ++ (B) ++ ("b"));
constraint
  (("bccbcccbbacbbccccabccacbbcaaabacaabbcaaabacbc") ++ ("")) =
    (("bccbcccb") ++ (B) ++ ("cbbccccabccacbbcaaabacaabbcaaabacbc"));
constraint
  (("cb") ++ (B) ++ ("aab") ++ (B) ++ ("aacccc") ++ (B) ++ ("cababcabbbbabbccc") ++ (B) ++ ("c") ++ (B) ++ ("bcbbbc"))
    =
    (("cb") ++ (B) ++ ("aabbaaacccc") ++ (B) ++ ("ca") ++ (B) ++ ("bcabbb") ++ (B) ++ ("bbccc") ++ (B) ++ ("c") ++ (B) ++ ("bcbbbc"));
constraint
  ((B) ++ ("abaaccbacbcb") ++ (B) ++ ("aabbbcaccbabaabc") ++ (B) ++ ("cccbcbbbcaa"))
    =
    (("baabaaccbacbcb") ++ (B) ++ ("aabbbcacc") ++ (B) ++ ("baabcbacccbcbbbcaa"));
constraint
  (("aabccaacabc") ++ (B) ++ ("bbcbcbbbbcbbbcac") ++ (B) ++ ("cac") ++ (B) ++ ("aacaaaacb"))
    =
    (("aabccaacabc") ++ (B) ++ ("bbcbcbbbbcbbbcac") ++ (B) ++ ("cac") ++ (B) ++ ("aacaaaacb"));
constraint
  (("bbbbcccbcacaccbb") ++ (B) ++ ("bcabca") ++ (B) ++ ("aaaccbcaac") ++ (B) ++ ("ccbbbca"))
    =
    (("bbbbcccbcacaccbb") ++ (B) ++ ("bcabca") ++ (B) ++ ("aaaccbcaac") ++ (B) ++ ("ccbbbca"));
constraint
  (("cbccaabbcbcbabcaabbbabca") ++ (B) ++ ("aabcacaacaabbbcacaa")) =
    (("cbccaabbcbcbabcaabbbabca") ++ (B) ++ ("aabcacaacaabbbcacaa"));
constraint
  (("aaabccbaabccbccbbcbccbaab") ++ (B) ++ ("bcacccbcaabacbbccc")) =
    (("aaabcc") ++ (B) ++ ("abccbccbbcbccbaabbabcacccbcaabacbbccc"));
constraint
  (("cccabcabbaabcbcccab") ++ (B) ++ ("cacbcaccaacaccacbaacaacc")) =
    (("cccabcab") ++ (B) ++ ("abcbcccab") ++ (B) ++ ("cacbcaccaacaccac") ++ (B) ++ ("acaacc"));
constraint
  (("bcbccc") ++ (B) ++ ("accacbacbbcbbbacbbcbaccb") ++ (B) ++ ("aabcacbabbb"))
    =
    (("bcbcccbaaccac") ++ (B) ++ ("cbbcbbbacbbc") ++ (B) ++ ("ccbbaaabcac") ++ (B) ++ ("bbb"));
constraint
  (("accbccc") ++ (B) ++ ("bbbbbccaaaabcbacababcbc") ++ (B) ++ ("a") ++ (B) ++ ("aabca") ++ (B) ++ ("b"))
    =
    (("accbccc") ++ (B) ++ ("bbbbbccaaaabcbacababcbcbaa") ++ (B) ++ ("aabca") ++ (B) ++ ("b"));
constraint
  (("cabbcacaaacabaacaacbbccccc") ++ (B) ++ ("cabbcbccaacbcacaa")) =
    (("cabbcacaaaca") ++ (B) ++ ("acaacbbccccc") ++ (B) ++ ("cabbcbccaacbcacaa"));
constraint
  (("bccaccbbabcacbbcacccbcbbacbcbabbb") ++ (B) ++ ("cccabaabca")) =
    (("bccaccbbabcacbbcacccbcbbacbc") ++ (B) ++ ("bbbbacccabaabca"));
constraint
  (("aaaccccbcbababccacbacbcc") ++ (B) ++ ("cbacbbaccbcaaaacbac")) =
    (("aaaccccbcba") ++ (B) ++ ("bccac") ++ (B) ++ ("cbccbacbacbbaccbcaaaac") ++ (B) ++ ("c"));
constraint
  (("ccabbaba") ++ (B) ++ ("cbbbbbcbb") ++ (B) ++ ("acababbbbbcbcbbbabbbcbaa"))
    =
    (("ccabba") ++ (B) ++ ("bacbbbbbcbbbaaca") ++ (B) ++ ("bbbbbcbcbb") ++ (B) ++ ("bbbcbaa"));
constraint
  (("caabacbbcac") ++ (B) ++ ("cccccabbcacaabcacaaacabcacabbbac")) =
    (("caabacbbcac") ++ (B) ++ ("cccccabbcacaabcacaaacabcacabbbac"));
constraint
  (("aaccaaaaabacbacacacbcbb") ++ (B) ++ ("caab") ++ (B) ++ ("bcaaaababbacbc"))
    =
    (("aaccaaaaabac") ++ (B) ++ ("cacacbcbb") ++ (B) ++ ("caab") ++ (B) ++ ("bcaaaa") ++ (B) ++ ("b") ++ (B) ++ ("cbc"));
constraint
  (("cccbaac") ++ (B) ++ ("cbbccaca") ++ (B) ++ ("cbbbcaabcaa") ++ (B) ++ ("ccaaaabbaabaa"))
    =
    (("ccc") ++ (B) ++ ("acbacbbccaca") ++ (B) ++ ("cbbbcaabcaa") ++ (B) ++ ("ccaaaabbaabaa"));
constraint
  ((B) ++ ("cacccbcb") ++ (B) ++ ("acbbcacabaccabccbcbaacaaa") ++ (B) ++ ("bccccc"))
    =
    (("bacacccbcbbaacbbcacabaccabccbc") ++ (B) ++ ("acaaa") ++ (B) ++ ("bccccc"));
constraint
  (("ccaaabc") ++ (B) ++ ("acccbcaabbaaa") ++ (B) ++ ("cbcacbbcbbbacabaaca") ++ (B))
    =
    (("ccaaabc") ++ (B) ++ ("acccbcaab") ++ (B) ++ ("aabacbcacbbcbbbacabaaca") ++ (B));
constraint
  (("aabbcabcbccbacccbacbcaacbaab") ++ (B) ++ ("bcaccabbbbaccbc")) =
    (("aabbcabcbcc") ++ (B) ++ ("cccbacbcaac") ++ (B) ++ ("ab") ++ (B) ++ ("bcaccabbb") ++ (B) ++ ("ccbc"));
constraint
  (("bcbcbcbbcbaccbaacacbbbcacaabbcbacabcbcbcbccbb") ++ ("")) =
    (("bcbcbcbbcbacc") ++ (B) ++ ("acacbbbcacaabbc") ++ (B) ++ ("cabcbcbcbccbb"));
constraint
  (("b") ++ (B) ++ ("cbccbacaaac") ++ (B) ++ ("cbc") ++ (B) ++ ("abacbacacaabbabccacb") ++ (B) ++ ("ab"))
    =
    (("bbacbcc") ++ (B) ++ ("caaacbacbc") ++ (B) ++ ("a") ++ (B) ++ ("cbacacaabbabccacb") ++ (B) ++ ("ab"));
constraint
  (("bcbcccabbbcbaccacbbc") ++ (B) ++ ("aaacaccbcbbcaccaccaaaac")) =
    (("bcbcccabbbc") ++ (B) ++ ("ccacbbcbaaaacaccbcbbcaccaccaaaac"));
constraint
  (("ccbcabcabbcbcacbbcaacaaaabbcccac") ++ (B) ++ ("caabaccbbcb")) =
    (("ccbcabcabbcbcacbbcaacaaaabbcccac") ++ (B) ++ ("caabaccbbcb"));
constraint
  (("acbccabacabcab") ++ (B) ++ ("acaac") ++ (B) ++ ("bcbcacaacbcbbbccbcaaaa"))
    =
    (("acbccabacabcab") ++ (B) ++ ("acaac") ++ (B) ++ ("bcbcacaacbcbbbccbcaaaa"));
constraint
  (("b") ++ (B) ++ ("ccabbabbbcb") ++ (B) ++ ("bbcbcbcbbb") ++ (B) ++ ("cccbca") ++ (B) ++ ("bbcacabca"))
    = (("b") ++ (B) ++ ("ccabbabbbcbbabbcbcbcbbbbacccbcababbcacabca"));
constraint
  (("abaaaacbaacbccccabcbacbccbccbcac") ++ (B) ++ ("caaaaabbcbb")) =
    (("abaaaac") ++ (B) ++ ("acbccccabc") ++ (B) ++ ("cbccbccbcacbacaaaaabbcbb"));
constraint
  (("ccbbbbbcbcccbbc") ++ (B) ++ ("acbbcaaaccabcabaaabbc") ++ (B) ++ ("bbcab"))
    = (("ccbbbbbcbcccbbcbaacbbcaaaccabcabaaabbcbabbcab") ++ (""));
constraint
  (("acccbaabcabc") ++ (B) ++ ("ccacccacccacaaabcacaabbb") ++ (B) ++ ("aac") ++ (B))
    = (("acccbaabcabc") ++ (B) ++ ("ccacccacccacaaabcacaabbbbaaacba"));
constraint
  (("bcccabcbccbbcccabcc") ++ (B) ++ ("ccbcacacbabaaaba") ++ (B) ++ ("abbbbb"))
    =
    (("bcccabcbccbbcccabcc") ++ (B) ++ ("ccbcacacba") ++ (B) ++ ("aa") ++ (B) ++ (B) ++ ("abbbbb"));
constraint
  (("acabbccccacbabcbaaabbcc") ++ (B) ++ ("bbacbaaacccbcb") ++ (B) ++ ("cbca"))
    =
    (("acabbccccac") ++ (B) ++ ("bcbaaabbcc") ++ (B) ++ ("bbac") ++ (B) ++ ("aacccbcbbacbca"));
constraint
  (("cab") ++ (B) ++ ("cbbbbbbccabbbbaaaa") ++ (B) ++ ("aacb") ++ (B) ++ ("ccabbacbccbcbb"))
    =
    (("cab") ++ (B) ++ ("cbbbbbbccabbb") ++ (B) ++ ("aaabaaacb") ++ (B) ++ ("ccab") ++ (B) ++ ("cbccbcbb"));
constraint
  ((B) ++ ("ba") ++ (B) ++ ("aa") ++ (B) ++ ("acaccbaaaabccbcbcbb") ++ (B) ++ ("cbcbbcacaaacab"))
    = (("bababaaabaacacc") ++ (B) ++ ("aaabccbcbcbbbacbcbbcacaaacab"));
constraint
  (("cbb") ++ (B) ++ ("a") ++ (B) ++ ("cabcaacaabcacbbbbccac") ++ (B) ++ ("cbaccb") ++ (B) ++ ("aacccc"))
    =
    (("cbb") ++ (B) ++ ("a") ++ (B) ++ ("cabcaacaabcacbbbbccacbacbaccbbaaacccc"));
constraint
  (("abbcaccabccaaabcacbbcaaaabcba") ++ (B) ++ ("abccccbbbbccca")) =
    (("abbcaccabccaaabcacbbcaaaabcbabaabccccbbbbccca") ++ (""));
constraint
  (("caabccccaacaaaabc") ++ (B) ++ ("cabccc") ++ (B) ++ ("bcccbcbbcccaaabbac"))
    = (("caabccccaacaaaabcbacabcccbabcccbcbbcccaaab") ++ (B) ++ ("c"));
constraint
  (("aaccabcabcaacabcbacccbbcbabcc") ++ (B) ++ (B) ++ ("aaacbacbbccb")) =
    (("aaccabcabcaacabcbacccbbc") ++ (B) ++ ("bccbabaaaac") ++ (B) ++ ("cbbccb"));
constraint
  (("bbcccccacbaa") ++ (B) ++ ("acccaca") ++ (B) ++ ("ccccbccbbcaaccaacccb") ++ (B))
    = (("bbcccccacbaabaacccaca") ++ (B) ++ ("ccccbccbbcaaccaacccbba"));
constraint
  (("bbcac") ++ (B) ++ ("caaabac") ++ (B) ++ ("c") ++ (B) ++ ("a") ++ (B) ++ ("ccabbc") ++ (B) ++ ("ba") ++ (B) ++ ("cbccaab") ++ (B) ++ ("cc"))
    =
    (("bbcac") ++ (B) ++ ("caaa") ++ (B) ++ ("cbacbaabaccabbc") ++ (B) ++ (B) ++ ("bacbccaabbacc"));
constraint
  (("cbaccbbcbabbbbaab") ++ (B) ++ (B) ++ ("aaacbccab") ++ (B) ++ ("ca") ++ (B) ++ (B) ++ ("cabaccb"))
    =
    (("cbaccbbcbabbb") ++ (B) ++ ("ab") ++ (B) ++ ("baaaacbccab") ++ (B) ++ ("ca") ++ (B) ++ ("baca") ++ (B) ++ ("ccb"));
constraint
  (("aaabcc") ++ (B) ++ ("accab") ++ (B) ++ ("ab") ++ (B) ++ ("cabbbba") ++ (B) ++ ("aabbbcaabcbccccaa"))
    =
    (("aaabcc") ++ (B) ++ ("accab") ++ (B) ++ ("abbacabbb") ++ (B) ++ ("baaabbbcaabcbccccaa"));
constraint
  (("babcbbaaaabaabcacccaac") ++ (B) ++ ("ca") ++ (B) ++ ("aaccbabb") ++ (B) ++ ("cbcaacb"))
    =
    (("babcbbaaaa") ++ (B) ++ ("abcacccaac") ++ (B) ++ ("ca") ++ (B) ++ ("aaccbabbbacbcaacb"));
constraint
  (("abbcccbbcbacccacabbabcccbcbbcaaabaabaaaacbccb") ++ ("")) =
    (("abbcccbbcbacccacab") ++ (B) ++ ("bcccbcbbcaaabaa") ++ (B) ++ ("aaacbccb"));
constraint
  (("aaacbbcbaccacbbbccaaabb") ++ (B) ++ ("cbabbccbcbbcacaabbca")) =
    (("aaacbbc") ++ (B) ++ ("ccacbbbccaaabbbacbabbccbcbbcacaabbca"));
constraint
  (("babbbbcbabbcbabbbb") ++ (B) ++ ("abccacbcaccabbcacaaacabca")) =
    (("babbbbc") ++ (B) ++ ("bbcbabbbb") ++ (B) ++ ("abccacbcaccabbcacaaacabca"));
constraint
  (("abcababc") ++ (B) ++ ("cccccbaaa") ++ (B) ++ ("bc") ++ (B) ++ ("aababbcba") ++ (B) ++ ("ccaababab"))
    =
    (("abcababcbacccccbaaa") ++ (B) ++ ("bcbaaa") ++ (B) ++ ("bbcba") ++ (B) ++ ("ccaa") ++ (B) ++ ("bab"));
constraint
  (("bcccbcccbcbbb") ++ (B) ++ ("acaccbcabbcaa") ++ (B) ++ ("acbbbcbc") ++ (B) ++ ("cccab"))
    =
    (("bcccbcccbcbbb") ++ (B) ++ ("acaccbcabbcaa") ++ (B) ++ ("acbbbcbc") ++ (B) ++ ("cccab"));
constraint
  (("bacbaacabccaaccbaaacabbbcccacbbccaaccccabccac") ++ ("")) =
    ((B) ++ ("c") ++ (B) ++ ("acabccaacc") ++ (B) ++ ("aacabbbcccacbbccaaccccabccac"));
constraint
  (("cbbbbcbcccccbbbb") ++ (B) ++ ("caacaab") ++ (B) ++ ("bcbcbbccbbcabcbc") ++ (B))
    = (("cbbbbcbcccccbbbbbacaacaabbabcbcbbccbbcabcbcba") ++ (""));
constraint
  (("b") ++ (B) ++ ("abbccbabcbcabcacbccbbaccabcaabacabaa") ++ (B) ++ ("ccac"))
    =
    (("bbaabbccbabcbcabcacbccb") ++ (B) ++ ("ccabcaa") ++ (B) ++ ("cabaa") ++ (B) ++ ("ccac"));
constraint
  (("cac") ++ (B) ++ (B) ++ ("cbcaaabcb") ++ (B) ++ ("abcaab") ++ (B) ++ ("baab") ++ (B) ++ ("b") ++ (B) ++ ("bcababccbc"))
    =
    (("cacba") ++ (B) ++ ("cbcaaabcb") ++ (B) ++ ("abcaab") ++ (B) ++ (B) ++ ("abbabbabca") ++ (B) ++ ("bccbc"));
constraint
  (("cac") ++ (B) ++ ("bcaaabbcaacbcaccabaaacabccaab") ++ (B) ++ ("caccbbb") ++ (B))
    =
    (("cac") ++ (B) ++ ("bcaaabbcaacbcacca") ++ (B) ++ ("aacabccaabbacaccbbbba"));
constraint
  (("bcccabbbabaaaacabbcbc") ++ (B) ++ ("aacc") ++ (B) ++ ("ac") ++ (B) ++ ("aab") ++ (B) ++ ("ac") ++ (B) ++ ("a") ++ (B))
    =
    (("bcccabb") ++ (B) ++ ("baaaacabbcbcbaaacc") ++ (B) ++ ("ac") ++ (B) ++ ("aabbaac") ++ (B) ++ ("aba"));
constraint
  (("aacacbbbbacababbccabccabaabcbbabcccbcacccbccb") ++ ("")) =
    (("aacacbbb") ++ (B) ++ ("ca") ++ (B) ++ ("bbccabcca") ++ (B) ++ ("abcb") ++ (B) ++ ("bcccbcacccbccb"));
constraint
  (("cbbcacbbbccabbccb") ++ (B) ++ ("a") ++ (B) ++ ("cbcaccbcabcaacbaac") ++ (B) ++ ("cac"))
    =
    (("cbbcacbbbccabbccbbaa") ++ (B) ++ ("cbcaccbcabcaac") ++ (B) ++ ("ac") ++ (B) ++ ("cac"));
constraint
  (("cbaccaaabbcacccbccbb") ++ (B) ++ ("aaabaa") ++ (B) ++ ("baaa") ++ (B) ++ (B) ++ ("acacaba"))
    =
    (("c") ++ (B) ++ ("ccaaabbcacccbccbbbaaaa") ++ (B) ++ ("a") ++ (B) ++ ("baaababaacaca") ++ (B));
constraint
  (("c") ++ (B) ++ ("ccbba") ++ (B) ++ ("aacbccaacbbbcbcbaccacabccbabccacaca"))
    = (("cbaccbbabaaacbccaacbbbcbcbaccacabcc") ++ (B) ++ ("bccacaca"));
constraint
  (("acbccacaaaaccbcccccaaaacbcaacaba") ++ (B) ++ ("bacccb") ++ (B) ++ ("bcb"))
    =
    (("acbccacaaaaccbcccccaaaacbcaacababa") ++ (B) ++ ("cccb") ++ (B) ++ ("bcb"));
constraint
  (("abccccaab") ++ (B) ++ ("acabbbbbaaccacbccacccaaccabaaacbac")) =
    (("abccccaab") ++ (B) ++ ("acabbbb") ++ (B) ++ ("accacbccacccaacca") ++ (B) ++ ("aac") ++ (B) ++ ("c"));
constraint
  (("bbacaabbaccabbaabb") ++ (B) ++ ("acacbbbabcc") ++ (B) ++ ("a") ++ (B) ++ ("babcacbba"))
    =
    (("b") ++ (B) ++ ("caab") ++ (B) ++ ("ccab") ++ (B) ++ ("abb") ++ (B) ++ ("acacbb") ++ (B) ++ ("bccbaabababcacb") ++ (B));
constraint
  (("bbccabbcacbbcc") ++ (B) ++ ("acaaacababbbcbcaacacbcbbcaacc")) =
    (("bbccabbcacbbccbaacaaaca") ++ (B) ++ ("bbbcbcaacacbcbbcaacc"));
constraint
  (("aacbbaacacacaacaacacbcbbbb") ++ (B) ++ ("bcbbcccbbcc") ++ (B) ++ ("c") ++ (B) ++ ("b"))
    = (("aacb") ++ (B) ++ ("acacacaacaacacbcbbbbbabcbbcccbbccbacbab"));
constraint
  (("aaccaacacccabcbcacbbacbac") ++ (B) ++ ("bccacacbcacaa") ++ (B) ++ ("bcc"))
    = (("aaccaacacccabcbcacbbac") ++ (B) ++ ("cbabccacacbcacaababcc"));
constraint
  (("cb") ++ (B) ++ ("bcbccccbbabccbaaacccbbba") ++ (B) ++ ("aca") ++ (B) ++ ("cbbbbbabba"))
    =
    (("cb") ++ (B) ++ ("bcbccccbbabccbaaacccbbba") ++ (B) ++ ("aca") ++ (B) ++ ("cbbbb") ++ (B) ++ ("bba"));
constraint
  (("caacabbcaccccbccbcbccacacab") ++ (B) ++ ("cb") ++ (B) ++ ("cc") ++ (B) ++ ("bccbccab"))
    = (("caacabbcaccccbccbcbccacacabbacbbaccbabccbccab") ++ (""));
constraint
  (("caabbcbaccaaaabbbbcaaaacaaabaacbcabcaaabaacab") ++ ("")) =
    (("caabbcbaccaaaabbbbcaaaacaaa") ++ (B) ++ ("acbcabcaaa") ++ (B) ++ ("acab"));
constraint
  (("cabbc") ++ (B) ++ ("ccaaabcbbbccacbc") ++ (B) ++ ("cccbbcbbaabc") ++ (B) ++ ("cccbcb"))
    =
    (("cabbc") ++ (B) ++ ("ccaaabcbbbccacbc") ++ (B) ++ ("cccbbcbbaabc") ++ (B) ++ ("cccbcb"));
constraint
  (("baacbcbcbcac") ++ (B) ++ (B) ++ ("bcbbccaaacbacaacaccbbbbccbc") ++ (B))
    =
    (("baacbcbcbcacba") ++ (B) ++ ("bcbbccaaac") ++ (B) ++ ("caacaccbbbbccbc") ++ (B));
constraint
  (("aacb") ++ (B) ++ ("ccca") ++ (B) ++ ("bbacaabbcaababcbabaccaabbbacacaaa"))
    =
    (("aacb") ++ (B) ++ ("ccca") ++ (B) ++ ("b") ++ (B) ++ ("caabbcaababc") ++ (B) ++ (B) ++ ("ccaabb") ++ (B) ++ ("cacaaa"));
constraint
  (("acbbbaaabca") ++ (B) ++ ("aaccc") ++ (B) ++ ("cbbccaaaccbaabacabcccbc") ++ (B))
    = (("acbbbaaabcabaaacccbacbbccaaaccbaabacabcccbc") ++ (B));
constraint
  (("bac") ++ (B) ++ ("bbccccaabbb") ++ (B) ++ ("acaccaab") ++ (B) ++ ("cbabacabbccbcba") ++ (B))
    =
    (("bac") ++ (B) ++ ("bbccccaabbb") ++ (B) ++ ("acaccaab") ++ (B) ++ ("c") ++ (B) ++ ("bacabbccbc") ++ (B) ++ ("ba"));
constraint
  (("bccacaa") ++ (B) ++ ("bcccaa") ++ (B) ++ ("cb") ++ (B) ++ ("acaccbbbcac") ++ (B) ++ ("babbbcbbaab"))
    =
    (("bccacaababcccaa") ++ (B) ++ ("cb") ++ (B) ++ ("acaccbbbcac") ++ (B) ++ ("babbbcbbaab"));
constraint
  (("bbca") ++ (B) ++ ("ccbabacabcabbccbbcbbabcabccabcacaabcbaa")) =
    (("bbcabaccbabacabcabbccbbcb") ++ (B) ++ ("bcabccabcacaabc") ++ (B) ++ ("a"));
constraint
  (("bca") ++ (B) ++ ("bcbcbcacabbccabbcaaccbcccbbcbaaccbacacaa")) =
    (("bca") ++ (B) ++ ("bcbcbcacabbccabbcaaccbcccbbc") ++ (B) ++ ("accbacacaa"));
constraint
  (("cbababb") ++ (B) ++ ("bacaccaccbcaccbbbacbbcbcbbbbabcacaaa")) =
    (("cba") ++ (B) ++ ("bb") ++ (B) ++ (B) ++ ("caccaccbcaccbb") ++ (B) ++ ("cbbcbcbbb") ++ (B) ++ ("bcacaaa"));
constraint
  (("aacaabaacaaaaaaacabcbccabaac") ++ (B) ++ ("cabbcaacaabcaab")) =
    (("aacaa") ++ (B) ++ ("acaaaaaaacabcbcca") ++ (B) ++ ("acbacabbcaacaabcaab"));
constraint
  (("bbabccaaaa") ++ (B) ++ ("cabccabcabbcbacaacac") ++ (B) ++ ("abc") ++ (B) ++ ("babccb"))
    =
    (("bbabccaaaa") ++ (B) ++ ("cabccabcabbc") ++ (B) ++ ("caacac") ++ (B) ++ ("abcbababccb"));
constraint
  ((B) ++ ("ca") ++ (B) ++ ("bbcbcccacbcc") ++ (B) ++ ("cccaabcaaabcbcbcaabbbcaca"))
    = ((B) ++ ("cababbcbcccacbcc") ++ (B) ++ ("cccaabcaaabcbcbcaabbbcaca"));
constraint
  (("bcbcccbbaaaabcaccccbcbcacccabbbbbcbcabaaccbcb") ++ ("")) =
    (("bcbcccb") ++ (B) ++ ("aaabcaccccbcbcacccabbbbbcbcabaaccbcb"));
constraint
  (("bcaacacbcabbbcaacaabccabbbbbcabb") ++ (B) ++ ("abbbac") ++ (B) ++ ("bbc"))
    =
    (("bcaacacbcabbbcaacaabccabbbbbcabb") ++ (B) ++ ("abb") ++ (B) ++ ("c") ++ (B) ++ ("bbc"));
constraint
  (("accabccabbccbacacb") ++ (B) ++ ("ccb") ++ (B) ++ ("bcbccaaaab") ++ (B) ++ ("cccccabc"))
    =
    (("accabccabbcc") ++ (B) ++ ("cacbbaccb") ++ (B) ++ ("bcbccaaaabbacccccabc"));
constraint
  (("bbaaaccacaaccbbabcabcb") ++ (B) ++ ("babaaab") ++ (B) ++ ("abcacca") ++ (B) ++ ("bca"))
    =
    (("bbaaaccacaaccbbabcabcb") ++ (B) ++ ("ba") ++ (B) ++ ("aab") ++ (B) ++ ("abcacca") ++ (B) ++ ("bca"));
constraint
  (("a") ++ (B) ++ ("bbaaccba") ++ (B) ++ ("ababcccb") ++ (B) ++ ("acbbbbcbcaaabcbaacbbbc"))
    =
    (("ababbaacc") ++ (B) ++ (B) ++ ("a") ++ (B) ++ ("bcccb") ++ (B) ++ ("acbbbbcbcaaabcbaacbbbc"));
constraint
  (("cbca") ++ (B) ++ ("abbc") ++ (B) ++ ("abbbbcccaabaacba") ++ (B) ++ ("ccacbbaaacacaba"))
    =
    (("cbcabaabbc") ++ (B) ++ ("abbbbcccaa") ++ (B) ++ ("ac") ++ (B) ++ ("baccacbbaaacaca") ++ (B));
constraint
  (("c") ++ (B) ++ ("cbbbcacccbbac") ++ (B) ++ ("bccaacacaabcaaab") ++ (B) ++ ("cc") ++ (B) ++ ("bbccb"))
    =
    (("c") ++ (B) ++ ("cbbbcacccbbac") ++ (B) ++ ("bccaacacaabcaaab") ++ (B) ++ ("cc") ++ (B) ++ ("bbccb"));
constraint
  (("cccb") ++ (B) ++ ("abbcbbbcabbabbcbacb") ++ (B) ++ ("b") ++ (B) ++ ("bab") ++ (B) ++ ("cccaaccabc"))
    =
    (("cccb") ++ (B) ++ ("abbcbbbcab") ++ (B) ++ ("bbcbacbbab") ++ (B) ++ ("bab") ++ (B) ++ ("cccaaccabc"));
constraint
  (("bbcabcacacabbcccabbbb") ++ (B) ++ ("babcabcbcacbcabacccbcc")) =
    (("bbcabcacacabbcccabbbb") ++ (B) ++ ("babcabcbcacbcabacccbcc"));
constraint
  (("aaaaaabcaaaccaaaa") ++ (B) ++ ("aa") ++ (B) ++ ("cc") ++ (B) ++ ("bacaa") ++ (B) ++ ("abbcabaccca"))
    =
    (("aaaaaabcaaaccaaaa") ++ (B) ++ ("aa") ++ (B) ++ ("ccbabacaabaabbcabaccca"));
constraint
  (("acc") ++ (B) ++ (B) ++ ("cc") ++ (B) ++ ("bbcbccbcbcbbbcbcaccbbacacacc") ++ (B) ++ ("aabc"))
    =
    (("accbabacc") ++ (B) ++ ("bbcbccbcbcbbbcbcaccb") ++ (B) ++ ("cacaccbaaabc"));
constraint
  (("baaaccbbccbcccbcbbc") ++ (B) ++ ("aac") ++ (B) ++ ("bca") ++ (B) ++ ("cabccaccabbbca"))
    = (("baaaccbbccbcccbcbbcbaaacbabca") ++ (B) ++ ("cabccaccabbbca"));
constraint
  (("abaaccbacca") ++ (B) ++ ("aabcca") ++ (B) ++ ("cccb") ++ (B) ++ ("bcc") ++ (B) ++ ("accbccccbcaca"))
    =
    (("abaacc") ++ (B) ++ ("ccabaaabcca") ++ (B) ++ ("cccb") ++ (B) ++ ("bccbaaccbccccbcaca"));
constraint
  (("abaaacca") ++ (B) ++ ("bcbcbacaabaccbaaaaaabca") ++ (B) ++ ("accaccaccc"))
    = (("abaaaccababcbcbacaabaccbaaaaaabcabaaccaccaccc") ++ (""));
constraint
  (("bcaabacbcaabc") ++ (B) ++ ("aacaacbbcbccaccabcbbcabbcccccc")) =
    (("bcaabacbcaabc") ++ (B) ++ ("aacaacbbcbccaccabcbbcabbcccccc"));
constraint
  (("abccccbabccabcabcaaabcbcbcccaca") ++ (B) ++ ("cbcc") ++ (B) ++ ("cccccb"))
    =
    (("abcccc") ++ (B) ++ ("bccabcabcaaabcbcbcccaca") ++ (B) ++ ("cbcc") ++ (B) ++ ("cccccb"));
constraint
  (("bcbcbbbbbbacabbaabcbccbccabca") ++ (B) ++ ("ba") ++ (B) ++ ("bbbcaa") ++ (B) ++ ("bc"))
    =
    (("bcbcbbbbb") ++ (B) ++ ("cabbaabcbccbccabca") ++ (B) ++ ("ba") ++ (B) ++ ("bbbcaababc"));
constraint
  (("bbccccaabcacbaa") ++ (B) ++ ("bbaabaaaaaacabcacaacca") ++ (B) ++ ("accb"))
    =
    (("bbccccaabcac") ++ (B) ++ ("a") ++ (B) ++ ("bbaa") ++ (B) ++ ("aaaaacabcacaacca") ++ (B) ++ ("accb"));
constraint
  (("aa") ++ (B) ++ ("b") ++ (B) ++ ("abaca") ++ (B) ++ ("cabbcbbcbcabcabcabcaaccaacbccbc"))
    =
    (("aabab") ++ (B) ++ ("abaca") ++ (B) ++ ("cabbcbbcbcabcabcabcaaccaacbccbc"));
constraint
  (("aaaaababa") ++ (B) ++ ("acbbc") ++ (B) ++ ("acacaaabcbbcbcaabbbbcaacb") ++ (B))
    = (("aaaaaba") ++ (B) ++ (B) ++ ("acbbcbaacacaaabcbbcbcaabbbbcaacbba"));
constraint
  (("bbcaaabbaaabcaaccabbab") ++ (B) ++ ("cccbcacbbcacaaaacbbba")) =
    (("bbcaaab") ++ (B) ++ ("aabcaaccab") ++ (B) ++ ("b") ++ (B) ++ ("cccbcacbbcacaaaacbbba"));
constraint
  (("cbbbacbcabcacbcbaaacaacaccbbbbacaaaccabcabccb") ++ ("")) =
    (("cbb") ++ (B) ++ ("cbcabcacbc") ++ (B) ++ ("aacaacaccbbb") ++ (B) ++ ("caaaccabcabccb"));
constraint
  ((B) ++ ("b") ++ (B) ++ ("ccaacbcac") ++ (B) ++ ("bcac") ++ (B) ++ ("cacb") ++ (B) ++ ("caabcbacbcbbbccab"))
    = (("bab") ++ (B) ++ ("ccaacbcacbabcacbacacbbacaabcbacbcbbbccab"));
constraint
  (("bcabccbca") ++ (B) ++ ("ccbbccaaccbbaaccabcbcbbcabbaabaaca")) =
    (("bcabccbcabaccbbccaaccbbaaccabcbcbbcab") ++ (B) ++ ("a") ++ (B) ++ ("aca"));
constraint
  (("bbbac") ++ (B) ++ ("cccaacaacc") ++ (B) ++ ("bcaccbccabbbbbbbabcaacbccb"))
    =
    (("bb") ++ (B) ++ ("c") ++ (B) ++ ("cccaacaacc") ++ (B) ++ ("bcaccbccabbbbbb") ++ (B) ++ ("bcaacbccb"));
constraint
  (("ccaaccbcbcbb") ++ (B) ++ ("ccacbcc") ++ (B) ++ ("b") ++ (B) ++ ("bcaabcbccccacaccaac"))
    = (("ccaaccbcbcbbbaccacbccbabbabcaabcbccccacaccaac") ++ (""));
constraint
  (("ccbbbbacbaaacacaaacaaaaacbcbbbabbbaccbbbccb") ++ (B)) =
    (("ccbbbbac") ++ (B) ++ ("aacacaaacaaaaacbcbb") ++ (B) ++ ("bbbaccbbbccbba"));
constraint
  (("ccbbcabcbcccacacaabca") ++ (B) ++ ("bcbbcbbcbcaacccacacaca")) =
    (("ccbbcabcbcccacacaabcababcbbcbbcbcaacccacacaca") ++ (""));
constraint
  ((B) ++ ("bca") ++ (B) ++ ("cccacacbbbcbbccbcacb") ++ (B) ++ ("cbbabbccaccacaaa"))
    = ((B) ++ ("bcabacccacacbbbcbbccbcacbbacb") ++ (B) ++ ("bbccaccacaaa"));
constraint
  (("cabccabccaacccccbaabcbccbac") ++ (B) ++ ("abcccabca") ++ (B) ++ ("aabca"))
    =
    (("cabccabccaaccccc") ++ (B) ++ ("abcbcc") ++ (B) ++ ("c") ++ (B) ++ ("abcccabca") ++ (B) ++ ("aabca"));
constraint
  (("bbccabaaaa") ++ (B) ++ ("cacbbac") ++ (B) ++ ("bcbccacbbcacbbcbbcabaabb"))
    =
    (("bbccabaaaa") ++ (B) ++ ("cacb") ++ (B) ++ ("c") ++ (B) ++ ("bcbccacbbcacbbcbbcabaabb"));
constraint
  (("cccacaab") ++ (B) ++ ("caacbba") ++ (B) ++ ("ccacbccacabbccbbaacabccaba"))
    =
    (("cccacaab") ++ (B) ++ ("caacbba") ++ (B) ++ ("ccacbccacabbccbbaacabccaba"));
constraint
  (("caaa") ++ (B) ++ ("caccabbbcabc") ++ (B) ++ ("bccabcabbcabcabcbcaaccbbb"))
    = (("caaa") ++ (B) ++ ("caccabbbcabcbabccabcabbcabcabcbcaaccbbb"));
constraint
  (("bbaaacabcaa") ++ (B) ++ (B) ++ ("bccaccc") ++ (B) ++ ("caabaabaaaaabbacacacb"))
    =
    (("bbaaacabcaa") ++ (B) ++ ("babccacccbacaa") ++ (B) ++ ("abaaaaab") ++ (B) ++ ("cacacb"));
constraint
  (("acbcabbbcaccabcbbcabaab") ++ (B) ++ ("aabbbbbcabbbcaccbccb")) =
    (("acbcabbbcaccabcbbcabaab") ++ (B) ++ ("aabbbbbcabbbcaccbccb"));
constraint
  (("cca") ++ (B) ++ ("cabcbbbbabbcccacbcbabccaabbcaaaacbccbcaa")) =
    (("cca") ++ (B) ++ ("cabcbbb") ++ (B) ++ ("bbcccacbc") ++ (B) ++ ("bccaabbcaaaacbccbcaa"));
constraint
  (("bacbbbccccbcacaabacbaaabbbcaa") ++ (B) ++ ("bcac") ++ (B) ++ ("bbcc") ++ (B) ++ ("bc"))
    =
    ((B) ++ ("cbbbccccbcacaa") ++ (B) ++ ("c") ++ (B) ++ ("aabbbcaa") ++ (B) ++ ("bcacbabbcc") ++ (B) ++ ("bc"));
constraint
  ((B) ++ ("aaaaa") ++ (B) ++ ("aaccbbcbacbccbabacb") ++ (B) ++ ("aaacaaba") ++ (B) ++ ("abacb"))
    =
    ((B) ++ ("aaaaa") ++ (B) ++ ("aaccbbc") ++ (B) ++ ("cbcc") ++ (B) ++ (B) ++ ("cbbaaaacaa") ++ (B) ++ (B) ++ ("a") ++ (B) ++ ("cb"));
constraint
  (("acbabbbcb") ++ (B) ++ ("bcccabab") ++ (B) ++ ("aaabacbbbbbcacbcaaabacbc"))
    =
    (("ac") ++ (B) ++ ("bbbcb") ++ (B) ++ ("bcccabab") ++ (B) ++ ("aaa") ++ (B) ++ ("cbbbbbcacbcaaa") ++ (B) ++ ("cbc"));
constraint
  (("bcaccaccaccabcba") ++ (B) ++ (B) ++ ("ccbbccaac") ++ (B) ++ ("aabbbacacccabb"))
    = (("bcaccaccaccabcba") ++ (B) ++ (B) ++ ("ccbbccaacbaaabbbacacccabb"));
constraint
  (("caaacacacaaabccccbcccabbcaaacc") ++ (B) ++ ("acccabaacbccb")) =
    (("caaacacacaaabccccbcccabbcaaacc") ++ (B) ++ ("acccabaacbccb"));
constraint
  (("a") ++ (B) ++ ("acbbcbbcacccbaaabaccaaacbbccaabbccbcbacbaa")) =
    (("abaacbbcbbcaccc") ++ (B) ++ ("aabaccaaacbbccaabbccbcbac") ++ (B) ++ ("a"));
constraint
  (("abab") ++ (B) ++ ("cab") ++ (B) ++ ("ccccaaac") ++ (B) ++ ("ac") ++ (B) ++ ("cccaa") ++ (B) ++ (B) ++ ("bcbbaabcaba"))
    =
    (("ababbacab") ++ (B) ++ ("ccccaaacbaacbacccaaba") ++ (B) ++ ("bcbbaabcaba"));
constraint
  (("cccbaaccacccaababccbacacc") ++ (B) ++ ("accbbcabbc") ++ (B) ++ ("cbcb") ++ (B))
    =
    (("cccbaaccacccaa") ++ (B) ++ ("bccbacacc") ++ (B) ++ ("accbbcabbcbacbcb") ++ (B));
constraint
  (("baacbcbc") ++ (B) ++ ("ba") ++ (B) ++ ("bcbcabcccbccaaca") ++ (B) ++ ("acccccbcabbcc"))
    =
    ((B) ++ ("acbcbcba") ++ (B) ++ (B) ++ ("bcbcabcccbccaaca") ++ (B) ++ ("acccccbcabbcc"));
constraint
  (("cacaaacbcbcaabccbbcabccbccbbaabcbcac") ++ (B) ++ ("aaabbba")) =
    (("cacaaacbcbcaabccbbcabccbccbbaabcbcacbaaaabbba") ++ (""));
solve satisfy;
