var string: B;
var string: E;
var string: G;
var string: F;
var string: A;
var string: C;
var string: D;
constraint
  (("acdcdcccbadaabaaaabc") ++ (B) ++ ("bcbaaacb")) =
    (("acdcdcccbadaabaaaa") ++ (G) ++ ("ab") ++ (A) ++ ("cbbdaddccabdccdccddbbabdccacdccbadabcadbcbaaacb"));
constraint
  (("bdcbcacdaacc") ++ (A) ++ ("dbacdaaadccddacbcdb")) =
    (("bdcbcacdaaccabaabbb") ++ (E) ++ ("b") ++ (G) ++ ("bbdbacdaaadccddacbcdb"));
constraint
  (("ddbdbddbaadacadaadb") ++ (B) ++ ("bdbbcbbddb")) =
    (("ddbdbddbaadacadaadbb") ++ (F) ++ ("cdabbccabccdcccbbbdbcbdbdcadcdbdbbcbbddb"));
constraint
  (("accbbabdcbaadddcccdcabdaccddbaadcaddbbbbbcddcacabbbbacbdcbdbabbbcbccdcadadaaac") ++ (D) ++ ("ddbadabbbabcbdad"))
    =
    (("accbbabdcbaadddcccdcabdaccddbaadcaddbbbbbcddcacabbbbacbdcbdbabbbcbccdcadadaaac") ++ (D) ++ ("ddbadabbbabcbdad"));
constraint
  (("ddbacabbdadbdccdbdcbadbdcdcabcbbdcbbcacdabcdccaddcddaaacbaddaaacacdbdacbdacdcdcddcabbddbbdaadacbcca") ++ (""))
    =
    (("ddbacabbd") ++ (D) ++ ("cdbdcb") ++ (D) ++ ("dcabcbbdcbbcacdabcdccaddcddaaacbaddaaacacdbdacbdacdcdcddcabbddbbdaadacbcca"));
constraint
  (("adbacdbccccbacdadbdcddbdacddbababbbddcbbabcbadcdbdcbbaaddbdccccccdaabacbccaabaadaacadbcbdaddcdabcbb") ++ (""))
    =
    (("adbacdbccccbacd") ++ (D) ++ ("ddbdacddbababbbddcbbabcbadcdbdcbbaaddbdccccccdaabacbccaabaadaacadbcbdaddcdabcbb"));
constraint
  (("bbdccdbdbab") ++ (D) ++ ("adbcbadadcdbbaacdccacbbdcdbaccaabdccbbdacadacdbccdbcbdcddcaaadbdbabbdababcdbddbacbb"))
    =
    (("bbdccdbdbab") ++ (D) ++ ("adbcbadadcdbbaacdccacbbdcdbaccaabdccbbdacadacdbccdbcbdcddcaaadbdbabbdababcdbddbacbb"));
constraint
  (("bcddddbaaddaaaaacdbaaaaadbbcbcdbccd") ++ (D) ++ ("adabcaccacccddcaacdddbcaddbdcaaccdabccbaacabbabcdcbda") ++ (D) ++ ("b"))
    =
    (("bcddddbaaddaaaaacdbaaaaadbbcbcdbccdadbdcadabcaccacccddcaacdddbcaddbdcaaccdabccbaacabbabcdcbdaadbdcb") ++ (""));
constraint
  (("cdcddcdbbbcacbaaddabcbdcbadadcdbdcbcccdadacddaddbdaaacddddabdcdaacaacdbcbddadacaadcacdabadad") ++ (D) ++ ("da"))
    =
    (("cdcddcdbbbcacbaaddabcbdcbadadcdbdcbcccdadacddaddbdaaacddddabdcdaacaacdbcbddadacaadcacdabadad") ++ (D) ++ ("da"));
constraint
  (("acbdaccbbcaadaacabbdcdabadcbbcadbcdcbbddbbcbbdbacdcdbaaabcdcaccacbcbcaddaccacddcccdb") ++ (D) ++ ("bbccbadadb"))
    =
    (("acbdaccbbcaadaacabbdcdabadcbbcadbcdcbbddbbcbbdbacdcdbaaabcdcaccacbcbcaddaccacddcccdb") ++ (D) ++ ("bbccbadadb"));
constraint
  (("ccbacaabadacbbdabdccdbaadacacdbbdccbdbdccbabcadbabbcdacbcccdbcadbdccdbadbcbcdaaccabaccdabcdacdcdccb") ++ (""))
    =
    (("ccbacaabadacbbdabdccdbaadacacdbbdccbdbdccbabcadbabbcdacbcccdbc") ++ (D) ++ ("cdbadbcbcdaaccabaccdabcdacdcdccb"));
constraint
  (("ccdbbcccdccbaacaaccbcdbdcbacbcbbaabababdaaabdcbccbbcbbabacdcdbbbdddacbc") ++ (D) ++ ("daaacddacbddaddacabddcd"))
    =
    (("ccdbbcccdccbaacaaccbcdbdcbacbcbbaabababdaaabdcbccbbcbbabacdcdbbbdddacbcadbdcdaaacddacbddaddacabddcd") ++ (""));
constraint
  (("dabaaacabbc") ++ (D) ++ ("ccabaaddabcdcadabbacddddabbccbdccdcacaaacadbcacdaddccbaddbbbcadddabacdcbbabccaabdca"))
    =
    (("dabaaacabbcadbdcccabaaddabcdcadabbacddddabbccbdccdcacaaacadbcacdaddccbaddbbbcadddabacdcbbabccaabdca") ++ (""));
constraint
  (("aadbdccdaaadcccadaadabcadaddbaddcbccbdbadbcbccacaabdcbbbcdcbadbbbcbbddbdadbdbadaadcdcddabadcdcaabda") ++ (""))
    =
    (("a") ++ (D) ++ ("cdaaadcccadaadabcadaddbaddcbccbdbadbcbccacaabdcbbbcdcbadbbbcbbddbdadbdbadaadcdcddabadcdcaabda"));
constraint
  (("bcbcabcbddddbadcdcbdcddddaaddcdcccdccddbabbdcddabdcdcccdaadbdcaacadcdddaacacaacbbcdbacddddbadabbbbb") ++ (""))
    =
    (("bcbcabcbddddbadcdcbdcddddaaddcdcccdccddbabbdcddabdcdcccda") ++ (D) ++ ("aacadcdddaacacaacbbcdbacddddbadabbbbb"));
constraint
  (("cbbbcdacadbcbaccdbaaacbbddbbdbdbcddbbabdababbcbadbaabbbbdbdbccbbbb") ++ (D) ++ ("ccabbaabadbdaaddbcadcbbbbaca"))
    =
    (("cbbbcdacadbcbaccdbaaacbbddbbdbdbcddbbabdababbcbadbaabbbbdbdbccbbbbadbdcccabbaabadbdaaddbcadcbbbbaca") ++ (""));
constraint
  (("ddabdcadabcbbcbbbcccdddadaccadaccbdaaaddddcdccdcbbabbbabdaaabccacadbdcbdcbddcaaabadbadbdbcdbdbdcdbd") ++ (""))
    =
    (("ddabdcadabcbbcbbbcccdddadaccadaccbdaaaddddcdccdcbbabbbabdaaabccac") ++ (D) ++ ("bdcbddcaaabadbadbdbcdbdbdcdbd"));
constraint
  (("acbccababdadcbcbabbcbadbcabdbadabbbcdbbcabddaa") ++ (D) ++ ("aaabccaadcaddcdddbdbcaabdcdddbbcbbadcaadcbabaddb"))
    =
    (("acbccababdadcbcbabbcbadbcabdbadabbbcdbbcabddaa") ++ (D) ++ ("aaabccaadcaddcdddbdbcaabdcdddbbcbbadcaadcbabaddb"));
constraint
  (("addcdbdbcdcacbccdcaacbdab") ++ (D) ++ ("ccdaabbcdbbbdcdbbccdddbddbaddabcdacddaaccbdcbabcdcadacdabbddccdcbddcc"))
    =
    (("addcdbdbcdcacbccdcaacbdabadbdcccdaabbcdbbbdcdbbccdddbddbaddabcdacddaaccbdcbabcdcadacdabbddccdcbddcc") ++ (""));
constraint
  (("aaaab") ++ (D) ++ ("adcadcaccdcbbdcbbccbccacbdadbdbadabdbbdbbadaaccbccabcabbbcdbdbaaaaaddadccdcdcdbdcabacdccc"))
    =
    (("aaaab") ++ (D) ++ ("adcadcaccdcbbdcbbccbccacbdadbdbadabdbbdbbadaaccbccabcabbbcdbdbaaaaaddadccdcdcdbdcabacdccc"));
constraint
  (("daabbdaddbddbdadda") ++ (D) ++ ("bdcbaacbcdcdcdccdabdacbdabadaacbcaaacdcaaabdabdddadcdbcabacbabcbabdcdbdbdacd"))
    =
    (("daabbdaddbddbdaddaadbdcbdcbaacbcdcdcdccdabdacbdabadaacbcaaacdcaaabdabdddadcdbcabacbabcbabdcdbdbdacd") ++ (""));
constraint
  (("c") ++ (D) ++ ("cbbbbcacdaacbbbdcdbabdbbbbcdccbbdaacaaccbcdaddaabdccbbbbabbaadaadcadacadbbccccbbbddbcdbddbbad"))
    =
    (("c") ++ (D) ++ ("cbbbbcacdaacbbbdcdbabdbbbbcdccbbdaacaaccbcdaddaabdccbbbbabbaadaadcadacadbbccccbbbddbcdbddbbad"));
constraint
  (("ccbdbadcaccaddabaccbcddaadbdcadbcbababadcbddcbbacaabcdcaadcbbddaaaddaaadbadddacbbbcadabbaaddbbaccad") ++ (""))
    =
    (("ccbdbadcaccaddabaccbcdda") ++ (D) ++ ("adbcbababadcbddcbbacaabcdcaadcbbddaaaddaaadbadddacbbbcadabbaaddbbaccad"));
constraint
  (("dcab") ++ (D) ++ ("babbacddbdbbaccabcdacccdbcacddcccbdbaabcdbcdbdcbacbbdbdcbcacbdadcbdcadbacdbddddadcbdaddacc"))
    =
    (("dcab") ++ (D) ++ ("babbacddbdbbaccabcdacccdbcacddcccbdbaabcdbcdbdcbacbbdbdcbcacbdadcbdcadbacdbddddadcbdaddacc"));
constraint
  (("dcccdaaddcddabccbbdac") ++ (D) ++ ("bbdbddacdcdadcbabdcbdbabbddccdaddbbddadaabbaadcddabaaaacdcddcabdbbdbdcdba"))
    =
    (("dcccdaaddcddabccbbdac") ++ (D) ++ ("bbdbddacdcdadcbabdcbdbabbddccdaddbbddadaabbaadcddabaaaacdcddcabdbbdbdcdba"));
constraint
  (("abcbdbddcdbacadbcaabdcacabdcdabcdcbdcdccaabcaccdabaccbddaabaadbdccdaccdabcbcbacddacadadadbadbccdcdd") ++ (""))
    =
    (("abcbdbddcdbacadbcaabdcacabdcdabcdcbdcdccaabcaccdabaccbddaaba") ++ (D) ++ ("cdaccdabcbcbacddacadadadbadbccdcdd"));
constraint
  (("bdcababdaacddabddaadbdbacbdcdddcaccaacdcadbabadbdccacdcdaadabacdcabddcccbaabbdcddcdbaccccdbbccbdbda") ++ (""))
    =
    (("bdcababdaacddabddaadbdbacbdcdddcaccaacdcadbab") ++ (D) ++ ("cacdcdaadabacdcabddcccbaabbdcddcdbaccccdbbccbdbda"));
constraint
  (("ddabadbaadacdddacaadbdacbaacadabbacddbdcbacbdbacaccbddbcbdccbbbbcddbbdbacccbddccddcbdccd") ++ (D) ++ ("dabdbd"))
    =
    (("ddabadbaadacdddacaadbdacbaacadabbacddbdcbacbdbacaccbddbcbdccbbbbcddbbdbacccbddccddcbdccd") ++ (D) ++ ("dabdbd"));
constraint
  (("adbdcccbcddbdcaaaadcaddacbcadbdccddcddadadaacbdbbccbdabcbdacbdbdacaabddbacbbccdbdabbddbccbddaddbdaa") ++ (""))
    =
    ((D) ++ ("ccbcddbdcaaaadcaddacbcadbdccddcddadadaacbdbbccbdabcbdacbdbdacaabddbacbbccdbdabbddbccbddaddbdaa") ++ (""));
constraint
  (("abdaacddabacabaabadccdadaccccdacbbbdcdcacccacccdadbdababacdabcdaccbaaabdabacdb") ++ (D) ++ ("dabcbccbcbdccdaa"))
    =
    (("abdaacddabacabaabadccdadaccccdacbbbdcdcacccacccdadbdababacdabcdaccbaaabdabacdb") ++ (D) ++ ("dabcbccbcbdccdaa"));
constraint
  (("cacdcddcdcbdbbccaaccdbccdaddcddddbdbaadacbcbbbabcbadcbaadadbccbccbcdddcbcaadcbdacadd") ++ (D) ++ ("daadddcacb"))
    =
    (("cacdcddcdcbdbbccaaccdbccdaddcddddbdbaadacbcbbbabcbadcbaadadbccbccbcdddcbcaadcbdacadd") ++ (D) ++ ("daadddcacb"));
constraint
  (("ccbabaaabcddbccbcabcdcddbbdbccbdcdbbcddaccacddbbbcdcbabdaaaccbbbdaacddcdabcbbbddabb") ++ (D) ++ ("cababaccdbc"))
    =
    (("ccbabaaabcddbccbcabcdcddbbdbccbdcdbbcddaccacddbbbcdcbabdaaaccbbbdaacddcdabcbbbddabb") ++ (D) ++ ("cababaccdbc"));
constraint
  (("ccdacaaaddccdabddcabccaccaabadaabdbcaabccadadbbcbcaabbdabcdcacbdbddbadabdbcabcaabcabca") ++ (D) ++ ("dcccddbb"))
    =
    (("ccdacaaaddccdabddcabccaccaabadaabdbcaabccadadbbcbcaabbdabcdcacbdbddbadabdbcabcaabcabcaadbdcdcccddbb") ++ (""));
constraint
  (("aababcbdcadbbbdbaaccbbcacbabdcddbaadbddbcddbdadbddddcbdcaaaccaccabbaaabbacbadbcadbdcbccbabbcdccabad") ++ (""))
    =
    (("aababcbdcadbbbdbaaccbbcacbabdcddbaadbddbcddbdadbddddcbdcaaaccaccabbaaabbacbadbc") ++ (D) ++ ("bccbabbcdccabad"));
constraint
  (("adcdabacbdccabcdadbbbccddadbbbcdadcdcabaaadacbbdccccbdcaacaccabdccbcbbbcbcdacdbcbba") ++ (D) ++ ("bcdbdbdcdca"))
    =
    (("adcdabacbdccabcdadbbbccddadbbbcdadcdcabaaadacbbdccccbdcaacaccabdccbcbbbcbcdacdbcbbaadbdcbcdbdbdcdca") ++ (""));
constraint
  (("bdcbacbadbccccaccbcbbcccddbbcabdbddaacaadbaabcb") ++ (D) ++ ("bcdcbabdaabcababacadadabbcadcdcdacbdcdadaaddbbd"))
    =
    (("bdcbacbadbccccaccbcbbcccddbbcabdbddaacaadbaabcb") ++ (D) ++ ("bcdcbabdaabcababacadadabbcadcdcdacbdcdadaaddbbd"));
constraint
  (("caabacddcabbbcadcacadbcadaabdccacaaaaadaaccabdababbbcdbdcdaaabcbccbaddccb") ++ (D) ++ ("dacaababaabbdddcdcaad"))
    =
    (("caabacddcabbbcadcacadbcadaabdccacaaaaadaaccabdababbbcdbdcdaaabcbccbaddccbadbdcdacaababaabbdddcdcaad") ++ (""));
constraint
  (("acbabcacbadccccccdaaddbbdddbacbadcbaadbdbcabbacbdbbadcddacacdbcbccbaaabdadbdccccccbcbabacacccdabadb") ++ (""))
    =
    (("acbabcacbadccccccdaaddbbdddbacbadcbaadbdbcabbacbdbbadcddacacdbcbccbaaabd") ++ (D) ++ ("cccccbcbabacacccdabadb"));
constraint
  (("caacaccbcdbddcabacbdaaadbdcadacdddcbaccadcddaddddabacbcabcddddccdadbcdcabcccbadabbbdcccdacbbbbaadad") ++ (""))
    =
    (("caacaccbcdbddcabacbdaa") ++ (D) ++ ("adacdddcbaccadcddaddddabacbcabcddddccdadbcdcabcccbadabbbdcccdacbbbbaadad"));
constraint
  (("cbccbdacccaaacdcacbcadbcdadaabbdddbdcccdacaacdaaaaccdbdbabacdadacbbcacddbbcacccaadbdcbdbbaabdbbdcbb") ++ (""))
    =
    (("cbccbdacccaaacdcacbcadbcdadaabbdddbdcccdacaacdaaaaccdbdbabacdadacbbcacddbbcaccca") ++ (D) ++ ("bdbbaabdbbdcbb"));
constraint
  (("bcadaaadcbabdaaccaabaacdaacbaabacaacbaaabccacdcbdbddcbbbcdabaababb") ++ (D) ++ ("dbbbdbdddadabdddccaacaacaccb"))
    =
    (("bcadaaadcbabdaaccaabaacdaacbaabacaacbaaabccacdcbdbddcbbbcdabaababbadbdcdbbbdbdddadabdddccaacaacaccb") ++ (""));
constraint
  (("ddcdcaccdbccabbccbcbdbadadbdccdcdcaabaccaaaadbbddcccdcbcabbabcdccababbacbbdabcbbbaddabcbaccabcbdbdd") ++ (""))
    =
    (("ddcdcaccdbccabbccbcbdbad") ++ (D) ++ ("cdcdcaabaccaaaadbbddcccdcbcabbabcdccababbacbbdabcbbbaddabcbaccabcbdbdd"));
constraint
  (("bacbdadaacaacacdacdbbcc") ++ (D) ++ ("ccddbadddcbadcbcbadaacabcdcbdbababacabacbabdabdbcabddddddbacdaaacaaacaa"))
    =
    (("bacbdadaacaacacdacdbbccadbdcccddbadddcbadcbcbadaacabcdcbdbababacabacbabdabdbcabddddddbacdaaacaaacaa") ++ (""));
constraint
  (("aadabbbcdcdcbadadbdcadabaadcbacbabcbabacbdbddccbacacabbabcbdadabaadaadaccdccbaaacddcdbccbbcbaccdacb") ++ (""))
    =
    (("aadabbbcdcdcbad") ++ (D) ++ ("adabaadcbacbabcbabacbdbddccbacacabbabcbdadabaadaadaccdccbaaacddcdbccbbcbaccdacb"));
constraint
  (("dcbbdbdadacbdbdadbddcbdcacdadcbbdabbcabcabdbbdbbaabdbbbcddbadccadbbdcabdbacddabcbadbdcddddddddccabc") ++ (""))
    =
    (("dcbbdbdadacbdbdadbddcbdcacdadcbbdabbcabcabdbbdbbaabdbbbcddbadccadbbdcabdbacddabcb") ++ (D) ++ ("ddddddddccabc"));
constraint
  (("ccaaadddbaaacdcbcdaddabadc") ++ (D) ++ ("aadabdabdbbcdaabdcadaacaddbbcbbdbdaabaaacbdbcabcbabdadbadddcccdcbadc"))
    =
    (("ccaaadddbaaacdcbcdaddabadcadbdcaadabdabdbbcdaabdcadaacaddbbcbbdbdaabaaacbdbcabcbabdadbadddcccdcbadc") ++ (""));
constraint
  ((D) ++ ("ccbbcddccdacddccbdbdcbbbccdddbadcbcdadaabbdbdccbddbac") ++ (D) ++ ("adbddcdaaccbdbbcaaaddddaadadbaaadaad"))
    =
    (("adbdcccbbcddccdacddccbdbdcbbbccdddbadcbcdadaabbdbdccbddbacadbdcadbddcdaaccbdbbcaaaddddaadadbaaadaad") ++ (""));
constraint
  (("dbabbbacadaaaaabcdbdaddccdbadadcdbccbcaabcaacdaabbcacdbadcbdcdadbdcadccdbabcabadabcadcadcbccadacbdc") ++ (""))
    =
    (("dbabbbacadaaaaabcdbdaddccdbadadcdbccbcaabcaacdaabbcacdbadcbdcd") ++ (D) ++ ("adccdbabcabadabcadcadcbccadacbdc"));
constraint
  (("ddcbdcbcbbdadbdddcbdbddcbdaacadbdcbaaacbbdccbbdccaabaabcacdacbdaaddbacaaaaddcbbacddaacdbbbaaacdaabb") ++ (""))
    =
    (("ddcbdcbcbbdadbdddcbdbddcbdaac") ++ (D) ++ ("baaacbbdccbbdccaabaabcacdacbdaaddbacaaaaddcbbacddaacdbbbaaacdaabb"));
constraint
  (("accccbcacadabbbcdcdbcabbcdcacadadbccdcdaabbcddcaaaccacbddadadab") ++ (D) ++ ("cccabacbaddadddbdaccdcdaadacdbb"))
    =
    (("accccbcacadabbbcdcdbcabbcdcacadadbccdcdaabbcddcaaaccacbddadadabadbdccccabacbaddadddbdaccdcdaadacdbb") ++ (""));
constraint
  (("aadddbabcbacdbacbcccacddcbacdbbcabcaadadcdcbacadbcccadbdccdcbadbdddcbbdaaadccccbdcadddcbbcaacbcbaad") ++ (""))
    =
    (("aadddbabcbacdbacbcccacddcbacdbbcabcaadadcdcbacadbccc") ++ (D) ++ ("cdcbadbdddcbbdaaadccccbdcadddcbbcaacbcbaad"));
constraint
  (("bbbbbcccabbdaaabbddcabdbabaacbaccdadcbb") ++ (D) ++ ("dcccabbddaabdadabaaadddaadddabadabbdcdcdadbdddcbcbbbabd"))
    =
    (("bbbbbcccabbdaaabbddcabdbabaacbaccdadcbb") ++ (D) ++ ("dcccabbddaabdadabaaadddaadddabadabbdcdcdadbdddcbcbbbabd"));
constraint
  (("dbdaccddbcbadcccdcdcaddacddacacbaabca") ++ (D) ++ ("bcdaaaadcbcdadcdabbcddccccdadabcbbbcbaaabadacadbaddbdbada"))
    =
    (("dbdaccddbcbadcccdcdcaddacddacacbaabca") ++ (D) ++ ("bcdaaaadcbcdadcdabbcddccccdadabcbbbcbaaabadacadbaddbdbada"));
constraint
  (("dbcadddadcbacbdddbccdbbacacddabaababbabbdcbdbabbacbaabcbaddcdacdbbaacbbabaadccddbabdbbadbabdadbdcdc") ++ (""))
    =
    (("dbcadddadcbacbdddbccdbbacacddabaababbabbdcbdbabbacbaabcbaddcdacdbbaacbbabaadccddbabdbbadbabd") ++ (D) ++ ("dc"));
constraint
  (("addbad") ++ (D) ++ ("acabcbbddcbddaddaadacbadddcaccabacdcddbcabadcdbabbbcaabaacabddaabcccaabbcbdccdacbbabdcdc"))
    =
    (("addbadadbdcacabcbbddcbddaddaadacbadddcaccabacdcddbcabadcdbabbbcaabaacabddaabcccaabbcbdccdacbbabdcdc") ++ (""));
constraint
  (("cdcacdaadbadaaaaabbbdcdbcabbdcacabcdcdcddcacadccaccaaacaad") ++ (D) ++ ("dabaddbadbcddccbcbaaacadacbdacabddda"))
    =
    (("cdcacdaadbadaaaaabbbdcdbcabbdcacabcdcdcddcacadccaccaaacaadadbdcdabaddbadbcddccbcbaaacadacbdacabddda") ++ (""));
constraint
  (("cccddbdaddcbcacbbbabbcaaaaadabbcbcbdaadaacaccaaaaabbccddcabbbbdaccbdaacdabbdacbcddcd") ++ (D) ++ ("bbdacbacbc"))
    =
    (("cccddbdaddcbcacbbbabbcaaaaadabbcbcbdaadaacaccaaaaabbccddcabbbbdaccbdaacdabbdacbcddcd") ++ (D) ++ ("bbdacbacbc"));
constraint
  (("abaaadbcccddddbcdcccccabcaaaabdcbaaabcaaacbaadbdbcbabbccdbdadcccccd") ++ (D) ++ ("bdcbdcaadaadccbcabdcdabbbcd"))
    =
    (("abaaadbcccddddbcdcccccabcaaaabdcbaaabcaaacbaadbdbcbabbccdbdadcccccd") ++ (D) ++ ("bdcbdcaadaadccbcabdcdabbbcd"));
constraint
  (("badabdbcdccccabcbcbacdadcbbbaaadbcaadcbcacccadcc") ++ (D) ++ ("cbadcbcaaabcdcbdaadaaccabaccbdaacacddcacaadcad"))
    =
    (("badabdbcdccccabcbcbacdadcbbbaaadbcaadcbcacccadcc") ++ (D) ++ ("cbadcbcaaabcdcbdaadaaccabaccbdaacacddcacaadcad"));
constraint
  (("ccbcacdcbbdbaddbdacbdbcabdbdcbaaadcdbbacbdcbdadcbbdbbdadbdddadcbadabaddbadbdcbadbdadcaadbadaccbddda") ++ (""))
    =
    (("ccbcacdcbbdbaddbdacbdbcabdbdcbaaadcdbbacbdcbdadcbbdbbdadbdddadcbadabaddb") ++ (D) ++ ("badbdadcaadbadaccbddda"));
constraint
  (("bbdadbcdbdbbbadbadadbabddccbcddaabccdcdcdacdcaaabacbbcacdbabaadddcdbacddacbcdbdccbcdadbdcadbacaacac") ++ (""))
    =
    (("bbdadbcdbdbbbadbadadbabddccbcddaabccdcdcdacdcaaabacbbcacdbabaadddcdbacddacbcdbdccbcd") ++ (D) ++ ("adbacaacac"));
constraint
  (("cdbccaca") ++ (D) ++ ("cdabbadcacbddcbcddbbdadddabcadbcccdababadcdacadbdbccadaadcabdbbaaddccaccbbcddccbccaabd"))
    =
    (("cdbccaca") ++ (D) ++ ("cdabbadcacbddcbcddbbdadddabcadbcccdababadcdacadbdbccadaadcabdbbaaddccaccbbcddccbccaabd"));
constraint
  (("aadcbcabbaaadabdacbcbdbacdddaadabdcbaaabbabcba") ++ (D) ++ ("dcbbdacdcabcbbcdbaccdaabddaadacaaabcbabcddcdaaba"))
    =
    (("aadcbcabbaaadabdacbcbdbacdddaadabdcbaaabbabcba") ++ (D) ++ ("dcbbdacdcabcbbcdbaccdaabddaadacaaabcbabcddcdaaba"));
constraint
  (("cdcdbdcdacadcdcbaaabababacaaddbbcacbaaaabcbbbaaadc") ++ (D) ++ ("adacccbcdbccacaaacbbabadcdbabdbcdbddabdcccbb"))
    =
    (("cdcdbdcdacadcdcbaaabababacaaddbbcacbaaaabcbbbaaadcadbdcadacccbcdbccacaaacbbabadcdbabdbcdbddabdcccbb") ++ (""));
constraint
  (("bddabbdabcbbacbaaccadccbdc") ++ (D) ++ ("adccbdad") ++ (D) ++ ("bcadbcbadbaddadbddcbaaabadcacbdbbddbacdaabddbbdbbdcbbcc"))
    =
    (("bddabbdabcbbacbaaccadccbdcadbdcadccbdad") ++ (D) ++ ("bcadbcbadbaddadbddcbaaabadcacbdbbddbacdaabddbbdbbdcbbcc"));
constraint
  (("adcdcacbcdbadbdccbdcdabadbbbddbdbbcdaaccaaadadcbccaddcaabbccbcaabaddcadccdbccddcbcddcdbbaadcdaabbda") ++ (""))
    =
    (("adcdcacbcdb") ++ (D) ++ ("cbdcdabadbbbddbdbbcdaaccaaadadcbccaddcaabbccbcaabaddcadccdbccddcbcddcdbbaadcdaabbda"));
constraint
  (("cbabdbabbbaccdbddbdaa") ++ (D) ++ ("aacdadbadcabbacbbcaacddccbccacccaccbababdcabbcdadbbcdcddbabdaddaacacabdbc"))
    =
    (("cbabdbabbbaccdbddbdaaadbdcaacdadbadcabbacbbcaacddccbccacccaccbababdcabbcdadbbcdcddbabdaddaacacabdbc") ++ (""));
constraint
  (("abaabcbcdaabdcb") ++ (D) ++ ("aababbddcdbabbddccadbdaccaabbcdbbaaaccbabcaccbdddacabddbdaadbdaccbcbbabcbcbbcdb"))
    =
    (("abaabcbcdaabdcb") ++ (D) ++ ("aababbddcdbabbddccadbdaccaabbcdbbaaaccbabcaccbdddacabddbdaadbdaccbcbbabcbcbbcdb"));
constraint
  (("dabdaaaccadabcacbbbccabdcbbbadddbbbccdbaddacdbbaaaadbacadbdadcbcadacbadcdbdcadbabbbddbcdc") ++ (D) ++ ("baacc"))
    =
    (("dabdaaaccadabcacbbbccabdcbbbadddbbbccdbaddacdbbaaaadbacadbdadcbcadacbadcdbdcadbabbbddbcdc") ++ (D) ++ ("baacc"));
constraint
  (("bbbdcdbddbaddbdcbadbdccccacccbbdcdbacbadbbddbbbcddababcbccccbccddadddaaccdccbdcaaabadcacdbcabadbcab") ++ (""))
    =
    (("bbbdcdbddbaddbdcb") ++ (D) ++ ("cccacccbbdcdbacbadbbddbbbcddababcbccccbccddadddaaccdccbdcaaabadcacdbcabadbcab"));
constraint
  (("acadbbbcaadabccddcbddacadcadaaddcaaa") ++ (D) ++ ("bdaacaadaabbccabcdcdcbbaaaabdbddcbadbbcabbdcbcbcdcadcadddb"))
    =
    (("acadbbbcaadabccddcbddacadcadaaddcaaa") ++ (D) ++ ("bdaacaadaabbccabcdcdcbbaaaabdbddcbadbbcabbdcbcbcdcadcadddb"));
constraint
  (("addaaadabdbcddbcbbcabbaabadbaaccddbacdcccaaabacbbcddadbcaabddccbadcbadbdccadaaacccabcccccdccbaadbca") ++ (""))
    =
    (("addaaadabdbcddbcbbcabbaabadbaaccddbacdcccaaabacbbcddadbcaabddccbadcb") ++ (D) ++ ("cadaaacccabcccccdccbaadbca"));
constraint
  (("ccbccccaaddcadacddadddc") ++ (D) ++ ("ddbdcadbdacdadbcdcccaadddccdbccdbcdbbbaacabccbdaccdbcdabcdddabcaaadaabb"))
    =
    (("ccbccccaaddcadacddadddcadbdcddbdcadbdacdadbcdcccaadddccdbccdbcdbbbaacabccbdaccdbcdabcdddabcaaadaabb") ++ (""));
constraint
  (("ababbcddcacddbcccdbbbdbacaadabadacacbbadabddcabaccbaacbbacbcacacdccb") ++ (D) ++ ("dcdbbabddbbcaddccddaaaacca"))
    =
    (("ababbcddcacddbcccdbbbdbacaadabadacacbbadabddcabaccbaacbbacbcacacdccbadbdcdcdbbabddbbcaddccddaaaacca") ++ (""));
constraint
  (("ccbdccdacbacbbddacbbdbcbcddddbdbaddaabdcbdbbdcbcbcadcacbdcddacacddabda") ++ (D) ++ ("ddadcdaadabbbadcdddddcdc"))
    =
    (("ccbdccdacbacbbddacbbdbcbcddddbdbaddaabdcbdbbdcbcbcadcacbdcddacacddabda") ++ (D) ++ ("ddadcdaadabbbadcdddddcdc"));
constraint
  (("dbacbddabadddbccbabaddcdcbbdcaabacdddcadababbccbaadbdccaabbddcdaacbadddaabadcaaaddbdcabcbdbdcadcdcb") ++ (""))
    =
    (("dbacbddabadddbccbabaddcdcbbdcaabacdddcadababbccba") ++ (D) ++ ("caabbddcdaacbadddaabadcaaaddbdcabcbdbdcadcdcb"));
constraint
  (("bcccdcbabbbbbdbddcbcdcdddddbcdaddaacacdbcaadbdadbbabadcdaaabcdbcbcabdbabadbbbcdbbddcdbcbadbccc") ++ (D))
    =
    (("bcccdcbabbbbbdbddcbcdcdddddbcdaddaacacdbcaadbdadbbabadcdaaabcdbcbcabdbabadbbbcdbbddcdbcbadbccc") ++ (D));
constraint
  (("cddbaa") ++ (C) ++ ("dbaacdacdcccacabcdcbbcb")) =
    (("cddbaadadbcddbcdbdbdbad") ++ (G) ++ ("ddbaacdacdcccacabcdcbbcb"));
constraint
  (("abdddd") ++ (C) ++ ("dbcdddcaaadbabdabdcabcccbcacbdabddad")) =
    ((E) ++ ("dbabdabdcabcccbcacbdabddad") ++ (""));
constraint
  (("c") ++ (D) ++ ("dbd") ++ (F) ++ ("aabbca") ++ (F) ++ (F) ++ ("cbbcadaa") ++ (F) ++ ("d") ++ (F) ++ (F) ++ ("dbdbabb") ++ (F) ++ ("ac") ++ (F) ++ ("bd") ++ (F) ++ ("dcdbabab") ++ (F) ++ ("a") ++ (F) ++ ("ccaba") ++ (F) ++ ("bdacabbab"))
    =
    (("cdc") ++ (F) ++ (F) ++ ("a") ++ (G) ++ ("bcad") ++ (F) ++ ("cbbcadaa") ++ (F) ++ (F) ++ ("dd") ++ (F) ++ ("b") ++ (F) ++ ("babb") ++ (F) ++ ("ac") ++ (F) ++ ("b") ++ (F) ++ ("ddcdbabab") ++ (F) ++ ("a") ++ (F) ++ ("ccabadb") ++ (F) ++ ("acabbab"));
constraint
  ((F) ++ ("dbadcccaaba") ++ (F) ++ ("a") ++ (F) ++ ("aba") ++ (F) ++ (F) ++ ("cccbbaba") ++ (F) ++ ("bdbdabbcbdcad") ++ (F) ++ (F) ++ ("ccabcbdbcacbbcacbcaccabbbaaccccc") ++ (F) ++ ("abb") ++ (F) ++ ("ac") ++ (F) ++ ("ba") ++ (F) ++ ("ada") ++ (F) ++ ("aacaacdd"))
    =
    (("ddba") ++ (F) ++ ("cccaabadadabaddcccbbabadbdbdabbcbdca") ++ (F) ++ ("ddccabcbdbcacbbcacbcaccabbbaacccccdabb") ++ (F) ++ ("ac") ++ (F) ++ ("bada") ++ (F) ++ ("adaacaacdd"));
constraint
  (("aa") ++ (F) ++ ("abdabbbcccacbcabbbc") ++ (F) ++ ("aacc") ++ (F) ++ ("dccdababbcca") ++ (F) ++ ("cab") ++ (F) ++ ("bdccdcabcc") ++ (F) ++ ("bacacacba") ++ (F) ++ ("ddabc") ++ (F) ++ ("dadaabac") ++ (F) ++ ("bc") ++ (F) ++ ("aaabaabaab") ++ (F) ++ (F) ++ (F) ++ ("cc"))
    =
    (("aa") ++ (F) ++ ("abdabbbcccacbcabbbc") ++ (F) ++ ("aaccd") ++ (F) ++ ("cc") ++ (F) ++ ("ababbccadcab") ++ (F) ++ ("b") ++ (F) ++ ("cc") ++ (F) ++ ("cabccdbacacacbad") ++ (F) ++ (F) ++ ("abcd") ++ (F) ++ ("a") ++ (F) ++ ("aabac") ++ (F) ++ ("bc") ++ (F) ++ ("aaabaabaab") ++ (F) ++ ("d") ++ (F) ++ ("cc"));
constraint
  (("dacaacababc") ++ (F) ++ ("dbaa") ++ (F) ++ ("baabcabaccb") ++ (F) ++ (F) ++ ("ab") ++ (F) ++ ("daddacacbccbabbb") ++ (F) ++ ("dabdaaabdc") ++ (F) ++ (F) ++ ("cabcab") ++ (F) ++ ("abccacacdccdcbdbacadbda") ++ (F) ++ ("b") ++ (F) ++ ("cdac"))
    =
    ((F) ++ ("acaacababc") ++ (F) ++ ("dbaadbaabcabaccb") ++ (F) ++ ("dabdda") ++ (F) ++ (F) ++ ("acacbccbabbb") ++ (F) ++ ("dabdaaabdcd") ++ (F) ++ ("cabcabdabccacac") ++ (F) ++ ("ccdcbdbacadb") ++ (F) ++ ("a") ++ (F) ++ ("bdcdac"));
constraint
  ((F) ++ (F) ++ (F) ++ ("bccd") ++ (F) ++ (F) ++ ("acaabab") ++ (F) ++ ("babacbcbd") ++ (F) ++ ("c") ++ (F) ++ ("cdbbd") ++ (F) ++ ("a") ++ (F) ++ ("caa") ++ (F) ++ ("acabbacb") ++ (F) ++ ("ccadcbbabbaaadcbcaca") ++ (F) ++ ("ccbbcaccbbaa") ++ (F) ++ ("aa") ++ (F) ++ ("abbacd") ++ (F) ++ ("bbad") ++ (F))
    =
    (("d") ++ (F) ++ ("dbcc") ++ (F) ++ ("d") ++ (F) ++ ("acaabab") ++ (F) ++ ("babacbcbd") ++ (F) ++ ("cdcdbb") ++ (F) ++ ("da") ++ (F) ++ ("caadacabbacbdcca") ++ (F) ++ ("cbbabbaaadcbcaca") ++ (F) ++ ("ccbbcaccbbaadaadabbac") ++ (F) ++ (F) ++ ("bbadd"));
constraint
  (("b") ++ (F) ++ ("ba") ++ (F) ++ ("cbc") ++ (F) ++ ("dadd") ++ (F) ++ ("baa") ++ (F) ++ ("adaaabdcbdbccbacbcad") ++ (F) ++ ("ccbcdaaca") ++ (F) ++ ("ccaabdacb") ++ (F) ++ ("abbcbbcabca") ++ (F) ++ ("abaabadbaaca") ++ (F) ++ ("bcbbc") ++ (F) ++ ("cbccadcab"))
    =
    (("bdbadcbcddad") ++ (F) ++ ("dbaada") ++ (F) ++ ("aaab") ++ (F) ++ ("cbdbccbacbcad") ++ (F) ++ ("ccbcdaacadccaab") ++ (F) ++ ("acbdabbcbbcabcadabaaba") ++ (F) ++ ("baacadbcbbcdcbccadcab"));
constraint
  (("bbd") ++ (F) ++ ("ccdbddcababcbdd") ++ (F) ++ ("acdc") ++ (F) ++ ("ccc") ++ (F) ++ ("d") ++ (F) ++ ("cbcbbccbabbab") ++ (F) ++ ("bbacbdaca") ++ (F) ++ ("accbcaaabcbcbbada") ++ (F) ++ (F) ++ (F) ++ ("ba") ++ (F) ++ ("cadcda") ++ (F) ++ (F) ++ ("adad") ++ (F) ++ ("abc") ++ (F) ++ ("bacc"))
    =
    (("bb") ++ (F) ++ ("dccdb") ++ (F) ++ ("dcababcb") ++ (F) ++ (F) ++ ("dac") ++ (F) ++ ("c") ++ (F) ++ ("cccd") ++ (F) ++ ("dcbcbbccbabbabdbbacbdacadaccbcaaabcbcbba") ++ (F) ++ ("a") ++ (F) ++ ("ddbadcadc") ++ (F) ++ ("ad") ++ (F) ++ ("a") ++ (F) ++ ("addabc") ++ (F) ++ ("bacc"));
constraint
  ((F) ++ ("cbadcacdacacdabdccabb") ++ (F) ++ ("ddabbcbbccaabd") ++ (F) ++ ("bc") ++ (F) ++ ("abcacacaccdcbb") ++ (F) ++ ("ccbbbbcbdbabcaaaaaacaa") ++ (F) ++ ("caccddcdaccaab") ++ (F) ++ (F) ++ ("aab") ++ (F))
    =
    ((F) ++ ("cbadcac") ++ (F) ++ ("acacdabdccabbd") ++ (F) ++ ("dabbcbbccaabddbc") ++ (F) ++ ("abcacacaccdcbb") ++ (F) ++ ("ccbbbbcb") ++ (F) ++ ("babcaaaaaacaadcacc") ++ (F) ++ (F) ++ ("c") ++ (F) ++ ("accaabddaab") ++ (F));
constraint
  (("cddbbdbaa") ++ (F) ++ ("d") ++ (F) ++ ("bcdaaaabc") ++ (F) ++ (F) ++ ("cd") ++ (F) ++ ("aabbdbbdaadbcadbcad") ++ (F) ++ ("abcdaadccbbbcca") ++ (F) ++ ("dbcb") ++ (F) ++ ("bcdbbdbcdcacd") ++ (F) ++ ("cbacdbccbbccaacbad"))
    =
    (("cddbbdbaad") ++ (F) ++ (F) ++ ("bcdaaaabcd") ++ (F) ++ ("cd") ++ (F) ++ ("aabbdbb") ++ (F) ++ ("aa") ++ (F) ++ ("bca") ++ (F) ++ ("bcaddabcdaadccbbbcca") ++ (F) ++ (F) ++ ("bcbdbc") ++ (F) ++ ("bb") ++ (F) ++ ("bc") ++ (F) ++ ("cacddcbacdbccbbccaacba") ++ (F));
constraint
  (("acdcacbbcbbadbbcdc") ++ (F) ++ (F) ++ ("acb") ++ (F) ++ ("bacdb") ++ (F) ++ ("a") ++ (F) ++ ("dcaaabccbbcddccc") ++ (F) ++ ("da") ++ (F) ++ ("dcbaadbbc") ++ (F) ++ ("ccab") ++ (F) ++ (F) ++ ("aac") ++ (F) ++ ("caacdaaa") ++ (F) ++ ("daacbcabaabd") ++ (F) ++ ("ccbca"))
    =
    (("acdcacbbcbbadbbcdcd") ++ (F) ++ ("acb") ++ (F) ++ ("bac") ++ (F) ++ ("bdaddcaaabccbbcd") ++ (F) ++ ("ccc") ++ (F) ++ ("da") ++ (F) ++ ("dcbaadbbc") ++ (F) ++ ("ccab") ++ (F) ++ (F) ++ ("aac") ++ (F) ++ ("caac") ++ (F) ++ ("aaa") ++ (F) ++ (F) ++ ("aacbcabaab") ++ (F) ++ (F) ++ ("ccbca"));
constraint
  (("ccaa") ++ (F) ++ (F) ++ ("bcbbccb") ++ (F) ++ ("bbadcab") ++ (F) ++ ("cbab") ++ (F) ++ ("accb") ++ (F) ++ ("bb") ++ (F) ++ ("c") ++ (F) ++ ("aad") ++ (F) ++ ("cccbdbacccbc") ++ (F) ++ ("dbd") ++ (F) ++ ("caabababacb") ++ (F) ++ ("c") ++ (F) ++ ("ccabaabaadcbadaa") ++ (F) ++ ("dccbadacda"))
    =
    (("ccaaddbcbbccbdbbadcabdcbabdaccbdbb") ++ (F) ++ ("c") ++ (F) ++ ("aad") ++ (F) ++ ("cccb") ++ (F) ++ ("bacccbcddb") ++ (F) ++ ("dcaabababacb") ++ (F) ++ ("c") ++ (F) ++ ("ccabaabaa") ++ (F) ++ ("cbadaa") ++ (F) ++ ("dccbadacda"));
constraint
  (("ada") ++ (F) ++ ("cbbc") ++ (F) ++ ("c") ++ (F) ++ ("cbacadbacbbadcab") ++ (F) ++ (F) ++ ("cdbdcaaaab") ++ (F) ++ ("dbbabbaabdcacdc") ++ (F) ++ ("dcbabbdacbcada") ++ (F) ++ ("d") ++ (F) ++ ("cacbab") ++ (F) ++ ("dccdccdbc") ++ (F) ++ ("dabcba") ++ (F) ++ (F) ++ ("a"))
    =
    (("a") ++ (F) ++ ("a") ++ (F) ++ ("cbbcdcdcbaca") ++ (F) ++ ("bacbbadcabddcdbdcaaaab") ++ (F) ++ ("dbbabbaab") ++ (F) ++ ("cac") ++ (F) ++ ("c") ++ (F) ++ ("dcbabb") ++ (F) ++ ("acbca") ++ (F) ++ ("ad") ++ (F) ++ (F) ++ ("cacbab") ++ (F) ++ ("dccdcc") ++ (F) ++ ("bc") ++ (F) ++ (F) ++ ("abcba") ++ (F) ++ ("da"));
constraint
  (("dc") ++ (F) ++ ("abc") ++ (F) ++ ("ac") ++ (F) ++ ("badabdaacaccbdbbcdaccbc") ++ (F) ++ ("bcbacda") ++ (F) ++ ("daaab") ++ (F) ++ (F) ++ ("c") ++ (F) ++ ("abbacbcdb") ++ (F) ++ ("acaccbccbdbbdabbcbc") ++ (F) ++ ("cdcddbca") ++ (F) ++ ("accbcb") ++ (F) ++ ("bc"))
    =
    (("dc") ++ (F) ++ ("abcdacdbadab") ++ (F) ++ ("aacaccbdbbc") ++ (F) ++ ("accbc") ++ (F) ++ ("bcbac") ++ (F) ++ ("a") ++ (F) ++ (F) ++ ("aaab") ++ (F) ++ ("dcdabbacbcdb") ++ (F) ++ ("acaccbccb") ++ (F) ++ ("bb") ++ (F) ++ ("abbcbcdc") ++ (F) ++ ("c") ++ (F) ++ ("dbcadaccbcbdbc"));
constraint
  (("acba") ++ (F) ++ ("ccdbb") ++ (F) ++ ("bbadbda") ++ (F) ++ ("cbba") ++ (F) ++ ("db") ++ (F) ++ ("ababbaaadbacb") ++ (F) ++ ("a") ++ (F) ++ ("aacbbcbbdbcbbca") ++ (F) ++ ("bdbdbba") ++ (F) ++ ("dcbacc") ++ (F) ++ ("baccbcbbc") ++ (F) ++ ("b") ++ (F) ++ ("dac") ++ (F) ++ (F) ++ ("a") ++ (F) ++ ("bacabd"))
    =
    (("acba") ++ (F) ++ ("cc") ++ (F) ++ ("bbdbba") ++ (F) ++ ("bdadcbbaddbdababbaaa") ++ (F) ++ ("bacbdadaacbbcbbdbcbbcadbdb") ++ (F) ++ ("bba") ++ (F) ++ ("dcbaccdbaccbcbbcdbd") ++ (F) ++ ("acddadbacabd"));
constraint
  ((F) ++ ("bcdcdbdcccddcbbcbd") ++ (F) ++ ("dc") ++ (F) ++ ("acdbcaacdd") ++ (F) ++ ("bbbbac") ++ (F) ++ ("cccaaa") ++ (F) ++ ("cbbd") ++ (F) ++ ("db") ++ (F) ++ ("dbccabc") ++ (F) ++ ("a") ++ (F) ++ ("cbcacbabbddccabbcbdbbaaa") ++ (F) ++ (F) ++ ("bb") ++ (F) ++ ("c") ++ (F) ++ ("c") ++ (F))
    =
    (("dbc") ++ (F) ++ ("c") ++ (F) ++ ("bdcccd") ++ (F) ++ ("cbbcbd") ++ (F) ++ (F) ++ ("cdacdbcaac") ++ (F) ++ ("d") ++ (F) ++ ("bbbbac") ++ (F) ++ ("cccaaa") ++ (F) ++ ("cbbdddb") ++ (F) ++ ("dbccabcda") ++ (F) ++ ("cbcacbabbddccabbcb") ++ (F) ++ ("bbaaaddbbdc") ++ (F) ++ ("cd"));
constraint
  ((F) ++ ("bccbbacaaacbaaaccdbcbabcdbabdcacbacccc") ++ (F) ++ ("ca") ++ (F) ++ ("baabbbdbaddad") ++ (F) ++ ("cbcdcacdccbbbcc") ++ (F) ++ (F) ++ ("aaabbbcbc") ++ (F) ++ ("a") ++ (F) ++ (F) ++ ("bdaa") ++ (F) ++ ("ababcbb"))
    =
    ((F) ++ ("bccbbacaaacbaaaccdbcbabcdbab") ++ (F) ++ ("cacbaccccdca") ++ (F) ++ ("baabbb") ++ (F) ++ ("baddaddcbc") ++ (F) ++ ("cacdccbbbcc") ++ (F) ++ (F) ++ ("aaabbbcbcdaddbdaadababcbb"));
constraint
  (("dbcbccbacb") ++ (F) ++ ("cbcbaadb") ++ (F) ++ ("adcbbcddaaccd") ++ (F) ++ ("ddbbaabcab") ++ (F) ++ ("bab") ++ (F) ++ ("daadacabaccca") ++ (F) ++ ("bccaaacababcaabacb") ++ (F) ++ ("aabaa") ++ (F) ++ ("ddabdbaaacb"))
    =
    (("dbcbccbacb") ++ (F) ++ ("cbcbaa") ++ (F) ++ ("bdadcbbcddaacc") ++ (F) ++ ("dd") ++ (F) ++ ("bbaabcabdbab") ++ (F) ++ (F) ++ ("aa") ++ (F) ++ ("acabacccadbccaaacababcaabacbdaabaa") ++ (F) ++ (F) ++ ("dabdbaaacb"));
constraint
  (("bc") ++ (F) ++ ("abaaaccaadb") ++ (F) ++ (F) ++ ("dad") ++ (F) ++ ("baabbacaaddcaab") ++ (F) ++ ("acbddabcada") ++ (F) ++ ("abc") ++ (F) ++ ("cdcbababdbcbbcbcbbbbcbdcdddddb") ++ (F) ++ ("bba") ++ (F) ++ ("bcdbbacbccba"))
    =
    (("bcdabaaaccaadb") ++ (F) ++ (F) ++ ("da") ++ (F) ++ ("dbaabbacaaddcaabdacb") ++ (F) ++ ("dabca") ++ (F) ++ ("a") ++ (F) ++ ("abc") ++ (F) ++ ("cdcbabab") ++ (F) ++ ("bcbbcbcbbbbcb") ++ (F) ++ ("cd") ++ (F) ++ ("d") ++ (F) ++ ("db") ++ (F) ++ ("bba") ++ (F) ++ ("bc") ++ (F) ++ ("bbacbccba"));
constraint
  ((F) ++ ("c") ++ (F) ++ ("cadccb") ++ (F) ++ ("d") ++ (F) ++ ("abdbaaaccccb") ++ (F) ++ (F) ++ ("cbcacbaadccdcbdccdacb") ++ (F) ++ (F) ++ ("dabccababaacdbbbaac") ++ (F) ++ ("babbcaccdddcca") ++ (F) ++ ("daabbcb") ++ (F) ++ ("dbcaabc"))
    =
    (("dc") ++ (F) ++ ("ca") ++ (F) ++ ("ccbdd") ++ (F) ++ ("ab") ++ (F) ++ ("baaaccccbddcbcacbaadccdcbdcc") ++ (F) ++ ("acb") ++ (F) ++ ("d") ++ (F) ++ ("abccababaac") ++ (F) ++ ("bbbaacdbabbcacc") ++ (F) ++ (F) ++ (F) ++ ("ccad") ++ (F) ++ ("aabbcb") ++ (F) ++ (F) ++ ("bcaabc"));
constraint
  (("badc") ++ (F) ++ ("ddccadbcbcc") ++ (F) ++ ("ccacdacccdcaabdc") ++ (F) ++ ("cdbcababaaaaabbaa") ++ (F) ++ ("aaccccbbb") ++ (F) ++ ("cabacabd") ++ (F) ++ (F) ++ ("bbdcaaabbaadbcbddcbddcd") ++ (F) ++ ("b") ++ (F) ++ ("a"))
    =
    (("ba") ++ (F) ++ ("c") ++ (F) ++ (F) ++ ("dccadbcbccdccac") ++ (F) ++ ("acccdcaab") ++ (F) ++ ("cdc") ++ (F) ++ ("bcababaaaaabbaa") ++ (F) ++ ("aaccccbbbdcabacabd") ++ (F) ++ ("dbbdcaaabbaadbcbddcb") ++ (F) ++ ("dcddbda"));
constraint
  ((F) ++ ("aa") ++ (F) ++ ("acbbbaabbd") ++ (F) ++ ("d") ++ (F) ++ ("adcdc") ++ (F) ++ ("babccacdbbbcbadbbacaacdabcccaccdddb") ++ (F) ++ ("accbbccccbaad") ++ (F) ++ ("aabadb") ++ (F) ++ (F) ++ ("cbc") ++ (F) ++ ("bbba") ++ (F) ++ (F) ++ ("bbaacccd"))
    =
    ((F) ++ ("aadacbbbaabbd") ++ (F) ++ (F) ++ (F) ++ ("adcdcdbabccac") ++ (F) ++ ("bbbcba") ++ (F) ++ ("bbacaac") ++ (F) ++ ("abcccacc") ++ (F) ++ ("ddb") ++ (F) ++ ("accbbccccbaa") ++ (F) ++ (F) ++ ("aabadb") ++ (F) ++ (F) ++ ("cbc") ++ (F) ++ ("bbbaddbbaacccd"));
constraint
  (("dcbbaba") ++ (F) ++ ("baccdbaaccbaba") ++ (F) ++ ("dcc") ++ (F) ++ ("badbaabcdaacb") ++ (F) ++ ("bbbcbbdbcacabdcbd") ++ (F) ++ ("ca") ++ (F) ++ ("ad") ++ (F) ++ ("b") ++ (F) ++ ("dccaacbcbc") ++ (F) ++ ("b") ++ (F) ++ ("acabaac") ++ (F) ++ ("dacabdbd") ++ (F) ++ ("bb"))
    =
    (("dcbbabadbaccdbaaccbaba") ++ (F) ++ ("dccdba") ++ (F) ++ ("baabc") ++ (F) ++ ("aacbdbbbcbbdbcacabdcbd") ++ (F) ++ ("ca") ++ (F) ++ ("a") ++ (F) ++ ("db") ++ (F) ++ (F) ++ ("ccaacbcbc") ++ (F) ++ ("b") ++ (F) ++ ("acabaacddacab") ++ (F) ++ ("b") ++ (F) ++ (F) ++ ("bb"));
constraint
  (("cdabdbdbcbcbaadccaab") ++ (F) ++ ("aabcacacabadadb") ++ (F) ++ ("bbab") ++ (F) ++ ("cbcab") ++ (F) ++ (F) ++ ("cccbbabdbcccbcaba") ++ (F) ++ ("bcbdadaccbcabcd") ++ (F) ++ (F) ++ ("dbcaccab") ++ (F) ++ (F) ++ ("abccc"))
    =
    (("cdab") ++ (F) ++ ("bdbcbcbaa") ++ (F) ++ ("ccaab") ++ (F) ++ ("aabcacacabadadbdbbab") ++ (F) ++ ("cbcabd") ++ (F) ++ ("cccbbabdbcccbcaba") ++ (F) ++ ("bcb") ++ (F) ++ ("adaccbcabcd") ++ (F) ++ (F) ++ ("dbcaccabddabccc"));
constraint
  (("aaad") ++ (F) ++ ("a") ++ (F) ++ (F) ++ ("baba") ++ (F) ++ ("ccaacbcdcbbcaaacdcdaaaca") ++ (F) ++ ("bbdadcb") ++ (F) ++ ("cbcbcdaccbaacbcaccaaaabacbaab") ++ (F) ++ ("d") ++ (F) ++ ("aaaca") ++ (F) ++ ("cb") ++ (F) ++ ("dbbb") ++ (F) ++ ("caacabc"))
    =
    (("aaad") ++ (F) ++ ("a") ++ (F) ++ ("dbabadccaacbcdcbbcaaac") ++ (F) ++ ("c") ++ (F) ++ ("aaacadbb") ++ (F) ++ ("adcb") ++ (F) ++ ("cbcbc") ++ (F) ++ ("accbaacbcaccaaaabacbaabd") ++ (F) ++ ("daaaca") ++ (F) ++ ("cb") ++ (F) ++ (F) ++ ("bbbdcaacabc"));
constraint
  (("dcaabaadaaaaccc") ++ (F) ++ ("bab") ++ (F) ++ ("c") ++ (F) ++ ("ccdc") ++ (F) ++ ("aadddcba") ++ (F) ++ ("acddbbbbdaa") ++ (F) ++ ("dbdbc") ++ (F) ++ ("bcccb") ++ (F) ++ ("adabbdac") ++ (F) ++ ("cdabaadcbcbbdabcbabda") ++ (F) ++ ("ccddacaa"))
    =
    (("dcaabaadaaaaccc") ++ (F) ++ ("bab") ++ (F) ++ ("cdccdc") ++ (F) ++ ("aad") ++ (F) ++ (F) ++ ("cba") ++ (F) ++ ("ac") ++ (F) ++ ("dbbbbdaaddb") ++ (F) ++ ("bc") ++ (F) ++ ("bcccb") ++ (F) ++ ("adabbdac") ++ (F) ++ ("c") ++ (F) ++ ("abaa") ++ (F) ++ ("cbcbb") ++ (F) ++ ("abcbabda") ++ (F) ++ ("cc") ++ (F) ++ ("dacaa"));
constraint
  (("ccbccbaccbbbbccba") ++ (F) ++ ("ba") ++ (F) ++ (F) ++ ("bd") ++ (F) ++ ("b") ++ (F) ++ ("cdbbaacccbbbbadcbbb") ++ (F) ++ ("ab") ++ (F) ++ ("bbaabcbcbbb") ++ (F) ++ ("bbdcaabddacccdccaaacdacabdbbda") ++ (F) ++ (F) ++ ("cacab"))
    =
    (("ccbccbaccbbbbccba") ++ (F) ++ ("bad") ++ (F) ++ ("bddb") ++ (F) ++ ("c") ++ (F) ++ ("bbaacccbbbba") ++ (F) ++ ("cbbbdab") ++ (F) ++ ("bbaabcbcbbbdbb") ++ (F) ++ ("caabddaccc") ++ (F) ++ ("ccaaac") ++ (F) ++ ("acabdbb") ++ (F) ++ ("addcacab"));
constraint
  (("cbaabacd") ++ (F) ++ ("bcb") ++ (F) ++ ("cbbabacacdbaccacca") ++ (F) ++ ("dadda") ++ (F) ++ ("aca") ++ (F) ++ ("abddcbcadcbacbd") ++ (F) ++ ("abcadacc") ++ (F) ++ ("acabbbabcacbb") ++ (F) ++ ("d") ++ (F) ++ ("bbba") ++ (F) ++ ("acbc") ++ (F) ++ ("ccaccd"))
    =
    (("cbaabac") ++ (F) ++ (F) ++ ("bcb") ++ (F) ++ ("cbbabacacdbaccaccad") ++ (F) ++ ("ad") ++ (F) ++ ("adacadabd") ++ (F) ++ ("cbcadcbacb") ++ (F) ++ (F) ++ ("abcadacc") ++ (F) ++ ("acabbbabcacbbdd") ++ (F) ++ ("bbbadacbc") ++ (F) ++ ("ccacc") ++ (F));
constraint
  ((F) ++ ("cbaaca") ++ (F) ++ ("accaaaaccacb") ++ (F) ++ ("a") ++ (F) ++ ("ddcdb") ++ (F) ++ ("bbccccc") ++ (F) ++ ("bbdcca") ++ (F) ++ ("d") ++ (F) ++ ("bdcb") ++ (F) ++ ("cbacbcdacdcb") ++ (F) ++ (F) ++ ("ccaaabaaccabd") ++ (F) ++ ("dbabaaabdbad") ++ (F) ++ ("cbcdaa") ++ (F))
    =
    ((F) ++ ("cbaacadaccaaaaccacbdad") ++ (F) ++ ("dcdbdbbcccccdbb") ++ (F) ++ ("cca") ++ (F) ++ ("d") ++ (F) ++ ("bdcb") ++ (F) ++ ("cbacbcdacdcb") ++ (F) ++ (F) ++ ("ccaaabaaccab") ++ (F) ++ ("d") ++ (F) ++ ("babaaabdbad") ++ (F) ++ ("cbcdaad"));
constraint
  (("dcbd") ++ (F) ++ ("bbcccca") ++ (F) ++ (F) ++ ("cbdcaaacacabaab") ++ (F) ++ ("abcdaa") ++ (F) ++ (F) ++ ("cccdacbad") ++ (F) ++ ("dcdbcaabcbaaacabbbbc") ++ (F) ++ ("bbdaadddbcba") ++ (F) ++ (F) ++ ("acdbcaa") ++ (F) ++ ("aaadcdc") ++ (F))
    =
    ((F) ++ ("cb") ++ (F) ++ ("dbbcccca") ++ (F) ++ (F) ++ ("cbdcaaacacabaab") ++ (F) ++ ("abc") ++ (F) ++ ("aa") ++ (F) ++ (F) ++ ("ccc") ++ (F) ++ ("acba") ++ (F) ++ ("d") ++ (F) ++ ("cdbcaabcbaaacabbbbcdbb") ++ (F) ++ ("aa") ++ (F) ++ (F) ++ ("dbcba") ++ (F) ++ (F) ++ ("ac") ++ (F) ++ ("bcaa") ++ (F) ++ ("aaa") ++ (F) ++ ("cdcd"));
constraint
  (("dcbaaaaabcccdccadabacdaccbdbaacc") ++ (F) ++ ("bacdbababbbbcabaacbcbcababadadaadba") ++ (F) ++ ("cbbdcbdbcaa") ++ (F) ++ ("dc") ++ (F) ++ ("bb") ++ (F) ++ ("aaaadbbbaaa") ++ (F))
    =
    ((F) ++ ("cbaaaaabcccdccadabacdaccb") ++ (F) ++ ("baacc") ++ (F) ++ ("bacdbababbbbcabaacbcbcababa") ++ (F) ++ ("a") ++ (F) ++ ("aa") ++ (F) ++ ("ba") ++ (F) ++ ("cbb") ++ (F) ++ ("cbdbcaa") ++ (F) ++ ("dc") ++ (F) ++ ("bbdaaaa") ++ (F) ++ ("bbbaaa") ++ (F));
constraint
  (("dccadcc") ++ (F) ++ ("aab") ++ (F) ++ ("ad") ++ (F) ++ ("cdaadcbdbdcd") ++ (F) ++ ("adcbacb") ++ (F) ++ (F) ++ (F) ++ ("bbacbcaaa") ++ (F) ++ ("aaccdbbd") ++ (F) ++ ("ccbaaacbca") ++ (F) ++ ("bab") ++ (F) ++ ("c") ++ (F) ++ ("ccdcbab") ++ (F) ++ ("cbddbbabbbcbccadd"))
    =
    ((F) ++ ("ccadccdaabdad") ++ (F) ++ ("c") ++ (F) ++ ("aadcbdb") ++ (F) ++ ("c") ++ (F) ++ (F) ++ ("a") ++ (F) ++ ("cbacbd") ++ (F) ++ ("dbbacbcaaa") ++ (F) ++ ("aaccdbb") ++ (F) ++ (F) ++ ("ccbaaacbca") ++ (F) ++ ("bab") ++ (F) ++ ("c") ++ (F) ++ ("ccdcbab") ++ (F) ++ ("cbd") ++ (F) ++ ("bbabbbcbcca") ++ (F) ++ ("d"));
constraint
  (("accbbbbdaccbc") ++ (F) ++ ("aad") ++ (F) ++ ("cdbcbaacda") ++ (F) ++ ("b") ++ (F) ++ ("abcba") ++ (F) ++ ("bb") ++ (F) ++ ("aadaccabbc") ++ (F) ++ (F) ++ ("b") ++ (F) ++ ("caabcaabbc") ++ (F) ++ ("acbddadacbabaca") ++ (F) ++ ("acbb") ++ (F) ++ ("bb") ++ (F) ++ ("bac") ++ (F) ++ ("abb") ++ (F) ++ ("ca"))
    =
    (("accbbbb") ++ (F) ++ ("accbcdaad") ++ (F) ++ ("c") ++ (F) ++ ("bcbaac") ++ (F) ++ ("a") ++ (F) ++ ("b") ++ (F) ++ ("abcba") ++ (F) ++ ("bb") ++ (F) ++ ("aa") ++ (F) ++ ("accabbcd") ++ (F) ++ ("bdcaabcaabbc") ++ (F) ++ ("acb") ++ (F) ++ ("dadacbabacadacbbdbb") ++ (F) ++ ("bacdabbdca"));
constraint
  (("acbacdababcbccbbdbdbbdcbbbcbbbaadaa") ++ (F) ++ ("dcab") ++ (F) ++ ("cdadbabdbbcdcbc") ++ (F) ++ ("c") ++ (F) ++ ("bbcdbbccccbcca") ++ (F) ++ ("ac") ++ (F) ++ (F) ++ ("bcbcaacccbccaaccda") ++ (F) ++ ("bd"))
    =
    (("acbac") ++ (F) ++ ("ababcbccbbdb") ++ (F) ++ ("bbdcbbbcbbbaa") ++ (F) ++ ("aa") ++ (F) ++ ("dcabdcda") ++ (F) ++ ("babdbbc") ++ (F) ++ ("cbc") ++ (F) ++ ("cdbbc") ++ (F) ++ ("bbccccbcca") ++ (F) ++ ("ac") ++ (F) ++ (F) ++ ("bcbcaacccbccaaccda") ++ (F) ++ ("bd"));
constraint
  (("adbababcaaccbbbbcbababbbaaca") ++ (F) ++ (F) ++ ("daccdaadcbddbdab") ++ (F) ++ ("bccbbbdc") ++ (F) ++ ("dcadbccccacbcabc") ++ (F) ++ ("ad") ++ (F) ++ ("bbba") ++ (F) ++ ("aaccaa") ++ (F) ++ ("cdb") ++ (F) ++ (F) ++ ("abaaa") ++ (F))
    =
    (("adbababcaaccbbbbcbababbbaacadd") ++ (F) ++ ("acc") ++ (F) ++ ("aadcb") ++ (F) ++ (F) ++ ("b") ++ (F) ++ ("abdbccbbbdc") ++ (F) ++ ("dca") ++ (F) ++ ("bccccacbcabc") ++ (F) ++ ("a") ++ (F) ++ (F) ++ ("bbba") ++ (F) ++ ("aaccaadcdbddabaaad"));
constraint
  (("bcccadcdcaaacbbbb") ++ (F) ++ ("dbb") ++ (F) ++ (F) ++ ("ababbbab") ++ (F) ++ ("cbacdbac") ++ (F) ++ (F) ++ ("ccbbdacccab") ++ (F) ++ ("daadbcdcdbbdbad") ++ (F) ++ ("bccbcdd") ++ (F) ++ ("ab") ++ (F) ++ (F) ++ ("bbacaacbddc") ++ (F) ++ ("cdbab"))
    =
    (("bccca") ++ (F) ++ ("c") ++ (F) ++ ("caaacbbbb") ++ (F) ++ (F) ++ ("bb") ++ (F) ++ ("dababbbabdcbacdbac") ++ (F) ++ ("dccbb") ++ (F) ++ ("acccab") ++ (F) ++ (F) ++ ("aadbcdcdbb") ++ (F) ++ ("baddbccbc") ++ (F) ++ ("d") ++ (F) ++ ("abddbbacaacb") ++ (F) ++ ("dc") ++ (F) ++ ("cdbab"));
constraint
  (("badc") ++ (F) ++ ("ccacacbabcbacb") ++ (F) ++ ("b") ++ (F) ++ ("abb") ++ (F) ++ ("cd") ++ (F) ++ (F) ++ (F) ++ ("cdadb") ++ (F) ++ ("caacac") ++ (F) ++ ("abc") ++ (F) ++ ("bacbacaccbcbcdacdabaabcaaaa") ++ (F) ++ ("adbcacbac") ++ (F) ++ (F) ++ ("ccccabbbbbcd"))
    =
    (("ba") ++ (F) ++ ("c") ++ (F) ++ ("ccacacbabcbacbdbdabb") ++ (F) ++ ("c") ++ (F) ++ ("dd") ++ (F) ++ ("cda") ++ (F) ++ ("b") ++ (F) ++ ("caacac") ++ (F) ++ ("abcdbacbacaccbcbc") ++ (F) ++ ("ac") ++ (F) ++ ("abaabcaaaadadbcacbacd") ++ (F) ++ ("ccccabbbbbc") ++ (F));
constraint
  (("cbbadc") ++ (F) ++ ("dbdbcbbacdaaabb") ++ (F) ++ ("aaa") ++ (F) ++ ("caacbccacbadababacbcadc") ++ (F) ++ ("ababcabbb") ++ (F) ++ ("bb") ++ (F) ++ (F) ++ ("badbc") ++ (F) ++ ("ab") ++ (F) ++ ("bcaabbadaa") ++ (F) ++ ("ac") ++ (F) ++ ("cacbccd") ++ (F) ++ (F) ++ ("cb"))
    =
    (("cbba") ++ (F) ++ ("c") ++ (F) ++ ("db") ++ (F) ++ ("bcbbac") ++ (F) ++ ("aaabbdaaadcaacbccacbadababacbca") ++ (F) ++ ("cdababcabbb") ++ (F) ++ ("bb") ++ (F) ++ ("dbadbc") ++ (F) ++ ("abdbcaabba") ++ (F) ++ ("aa") ++ (F) ++ ("acdcacbcc") ++ (F) ++ ("d") ++ (F) ++ ("cb"));
constraint
  (("cabaddacbbaccc") ++ (F) ++ ("cdadaccaca") ++ (F) ++ ("c") ++ (F) ++ (F) ++ (F) ++ ("dcb") ++ (F) ++ ("cc") ++ (F) ++ ("bdac") ++ (F) ++ ("ddacaaabaabcccbc") ++ (F) ++ ("c") ++ (F) ++ ("bacac") ++ (F) ++ ("bd") ++ (F) ++ ("adac") ++ (F) ++ ("dbbb") ++ (F) ++ ("dcbcac") ++ (F) ++ (F) ++ ("bcca") ++ (F) ++ ("db") ++ (F) ++ ("aaa"))
    =
    (("cabaddacbbaccc") ++ (F) ++ ("c") ++ (F) ++ ("adaccaca") ++ (F) ++ ("c") ++ (F) ++ (F) ++ (F) ++ (F) ++ ("cb") ++ (F) ++ ("ccdb") ++ (F) ++ ("ac") ++ (F) ++ (F) ++ ("dacaaabaabcccbc") ++ (F) ++ ("cdbacac") ++ (F) ++ ("bd") ++ (F) ++ ("adacddbbb") ++ (F) ++ (F) ++ ("cbcacddbccaddb") ++ (F) ++ ("aaa"));
constraint
  (("bcd") ++ (F) ++ (F) ++ ("bb") ++ (F) ++ ("ccba") ++ (F) ++ ("dd") ++ (F) ++ (F) ++ ("dddaccaaa") ++ (F) ++ ("b") ++ (F) ++ (F) ++ (F) ++ ("b") ++ (F) ++ ("dbdbcaacabda") ++ (F) ++ ("aaadcaacaadcda") ++ (F) ++ ("acaad") ++ (F) ++ (F) ++ ("abaa") ++ (F) ++ ("acaadaadc") ++ (F) ++ ("a") ++ (F) ++ ("cadacacbaadccc"))
    =
    (("bcdd") ++ (F) ++ ("bb") ++ (F) ++ ("ccbaddd") ++ (F) ++ (F) ++ (F) ++ ("ddaccaaa") ++ (F) ++ ("bdddbd") ++ (F) ++ ("bdbcaacab") ++ (F) ++ ("a") ++ (F) ++ ("aaadcaacaadcdadacaad") ++ (F) ++ ("dabaadacaa") ++ (F) ++ ("aadcda") ++ (F) ++ ("ca") ++ (F) ++ ("acacbaa") ++ (F) ++ ("ccc"));
constraint
  (("baacbaccdaaabcadcababcdcbab") ++ (F) ++ ("cdaa") ++ (F) ++ ("bcca") ++ (F) ++ ("addaaabccdaabcab") ++ (F) ++ ("abcdacbacdabccabccdcdcabcbbadba") ++ (F) ++ ("aaab") ++ (F) ++ (F) ++ ("bbbcda"))
    =
    (("baacbacc") ++ (F) ++ ("aaabca") ++ (F) ++ ("cababc") ++ (F) ++ ("cbab") ++ (F) ++ ("c") ++ (F) ++ ("aa") ++ (F) ++ ("bcca") ++ (F) ++ ("addaaabcc") ++ (F) ++ ("aabcabdabcdacbac") ++ (F) ++ ("abccabccdcdcabcbbadba") ++ (F) ++ ("aaabddbbbcda"));
constraint
  ((F) ++ ("c") ++ (F) ++ ("ccadd") ++ (F) ++ ("adbada") ++ (F) ++ ("aa") ++ (F) ++ ("bbbdcdaa") ++ (F) ++ ("bdcbb") ++ (F) ++ ("baddcbaadcadabccdabdcbaaacacba") ++ (F) ++ (F) ++ ("cbdabcabdbadcca") ++ (F) ++ ("caccacaa") ++ (F) ++ (F) ++ ("bb") ++ (F) ++ ("cbbb"))
    =
    ((F) ++ ("cdccadddadbadadaa") ++ (F) ++ ("bbbdcdaadb") ++ (F) ++ ("cbb") ++ (F) ++ ("baddcbaa") ++ (F) ++ ("ca") ++ (F) ++ ("abcc") ++ (F) ++ ("ab") ++ (F) ++ ("cbaaacacba") ++ (F) ++ ("dcbdabcab") ++ (F) ++ ("ba") ++ (F) ++ ("cca") ++ (F) ++ ("caccacaa") ++ (F) ++ ("dbbdcbbb"));
constraint
  (("acabbaaabcbcacdabcadaac") ++ (F) ++ ("ccbbccaca") ++ (F) ++ ("ccdbbc") ++ (F) ++ ("dbb") ++ (F) ++ ("dabca") ++ (F) ++ ("bcbbabddac") ++ (F) ++ ("ca") ++ (F) ++ ("adc") ++ (F) ++ ("bcabacbca") ++ (F) ++ ("b") ++ (F) ++ ("c") ++ (F) ++ (F) ++ ("dcdabbcdcaacbdd"))
    =
    (("acabbaaabcbcac") ++ (F) ++ ("abca") ++ (F) ++ ("aac") ++ (F) ++ ("ccbbccaca") ++ (F) ++ ("cc") ++ (F) ++ ("bbc") ++ (F) ++ (F) ++ ("bb") ++ (F) ++ (F) ++ ("abcadbcbbabd") ++ (F) ++ ("ac") ++ (F) ++ ("cadadc") ++ (F) ++ ("bcabacbca") ++ (F) ++ ("b") ++ (F) ++ ("c") ++ (F) ++ ("d") ++ (F) ++ ("c") ++ (F) ++ ("abbc") ++ (F) ++ ("caacbd") ++ (F));
constraint
  (("ac") ++ (F) ++ ("adccbaa") ++ (F) ++ ("abcbbbcaacbbcc") ++ (F) ++ ("acbbbbcccbb") ++ (F) ++ ("bca") ++ (F) ++ ("accbcbcd") ++ (F) ++ (F) ++ ("cc") ++ (F) ++ ("b") ++ (F) ++ ("ab") ++ (F) ++ ("cb") ++ (F) ++ ("bcdbba") ++ (F) ++ (F) ++ ("a") ++ (F) ++ ("baccdacdc") ++ (F) ++ ("daaccbccbbaa") ++ (F) ++ ("bba"))
    =
    (("acda") ++ (F) ++ ("ccbaa") ++ (F) ++ ("abcbbbcaacbbcc") ++ (F) ++ ("acbbbbcccbbdbca") ++ (F) ++ ("accbcbc") ++ (F) ++ ("ddccdbdab") ++ (F) ++ ("cbdbc") ++ (F) ++ ("bbadda") ++ (F) ++ ("bacc") ++ (F) ++ ("ac") ++ (F) ++ ("c") ++ (F) ++ ("daaccbccbbaa") ++ (F) ++ ("bba"));
constraint
  (("dcccc") ++ (F) ++ ("abb") ++ (F) ++ ("accccda") ++ (F) ++ ("bb") ++ (F) ++ ("caadcacccccc") ++ (F) ++ ("bbbcacdbdc") ++ (F) ++ ("a") ++ (F) ++ ("b") ++ (F) ++ ("aad") ++ (F) ++ ("aac") ++ (F) ++ ("cabbcbdbacbccccdc") ++ (F) ++ (F) ++ ("bbdca") ++ (F) ++ ("bba") ++ (F) ++ ("dbdbbbbadbab") ++ (F))
    =
    (("dcccc") ++ (F) ++ ("abbdacccc") ++ (F) ++ ("adbbdcaa") ++ (F) ++ ("cacccccc") ++ (F) ++ ("bbbcacdb") ++ (F) ++ ("cdadb") ++ (F) ++ ("aa") ++ (F) ++ (F) ++ ("aacdcabbcb") ++ (F) ++ ("bacbcccc") ++ (F) ++ ("cddbbdca") ++ (F) ++ ("bba") ++ (F) ++ ("db") ++ (F) ++ ("bbbba") ++ (F) ++ ("bab") ++ (F));
constraint
  (("abcdccbaababaddbbdcacccadacbbabcacaa") ++ (F) ++ ("bdabbcdabcb") ++ (F) ++ ("babcdaca") ++ (F) ++ ("addbbbcaabadd") ++ (F) ++ ("bdccadc") ++ (F) ++ ("cdcdbca") ++ (F) ++ ("adacdacbcac"))
    =
    (("abcdccbaababa") ++ (F) ++ ("dbbdcacccadacbbabcacaa") ++ (F) ++ ("b") ++ (F) ++ ("abbc") ++ (F) ++ ("abcb") ++ (F) ++ ("babc") ++ (F) ++ ("acadad") ++ (F) ++ ("bbbcaabad") ++ (F) ++ ("dbdcca") ++ (F) ++ ("cdcdcdbcadadac") ++ (F) ++ ("acbcac"));
constraint
  (("bd") ++ (F) ++ ("accbabcbdcaad") ++ (F) ++ ("bccabbbadc") ++ (F) ++ ("cdbccaaacaabacddbadbbc") ++ (F) ++ ("cbcabacb") ++ (F) ++ ("bd") ++ (F) ++ ("bcd") ++ (F) ++ ("dbcdaa") ++ (F) ++ ("b") ++ (F) ++ ("baacbcaacacbcacadb") ++ (F) ++ (F) ++ ("dcc"))
    =
    (("bddaccbabcb") ++ (F) ++ ("caad") ++ (F) ++ ("bccabbba") ++ (F) ++ ("cdcdbccaaacaabac") ++ (F) ++ (F) ++ ("ba") ++ (F) ++ ("bbcdcbcabacbdbddbc") ++ (F) ++ ("ddbcdaa") ++ (F) ++ ("b") ++ (F) ++ ("baacbcaacacbcaca") ++ (F) ++ ("b") ++ (F) ++ ("d") ++ (F) ++ ("cc"));
constraint
  ((F) ++ ("cdcaac") ++ (F) ++ ("ccddbbcacdd") ++ (F) ++ ("dc") ++ (F) ++ (F) ++ ("a") ++ (F) ++ ("aabbab") ++ (F) ++ ("bdbbaacccabbadcabdabbcc") ++ (F) ++ ("cbabcbaabdb") ++ (F) ++ (F) ++ ("bcbaaacbdb") ++ (F) ++ ("bcaaba") ++ (F) ++ ("aababdaccdb"))
    =
    ((F) ++ ("cdcaacdccddbbcac") ++ (F) ++ (F) ++ (F) ++ ("dc") ++ (F) ++ (F) ++ ("adaabbabdb") ++ (F) ++ ("bbaacccabbadcab") ++ (F) ++ ("abbccdcbabcbaabdb") ++ (F) ++ (F) ++ ("bcbaaacbdbdbcaabadaababdacc") ++ (F) ++ ("b"));
constraint
  (("c") ++ (F) ++ ("dddaaa") ++ (F) ++ ("bcdaa") ++ (F) ++ ("ccabbcbbcbdd") ++ (F) ++ ("dbbbdcdabcaadbd") ++ (F) ++ ("acbabb") ++ (F) ++ ("ccbaababdd") ++ (F) ++ ("bb") ++ (F) ++ ("bb") ++ (F) ++ ("bbacacbcccac") ++ (F) ++ ("a") ++ (F) ++ ("ababaabdbabcabdd"))
    =
    (("cdd") ++ (F) ++ ("daaa") ++ (F) ++ ("bc") ++ (F) ++ ("aadccabbcbbcb") ++ (F) ++ (F) ++ (F) ++ (F) ++ ("bbb") ++ (F) ++ ("cdabcaadb") ++ (F) ++ (F) ++ ("acbabbdccbaababdddbb") ++ (F) ++ ("bbdbbacacbcccac") ++ (F) ++ ("adababaabdbabcabd") ++ (F));
constraint
  (("cabcccccadccaabbc") ++ (F) ++ ("dbba") ++ (F) ++ ("baadaab") ++ (F) ++ ("c") ++ (F) ++ ("ccac") ++ (F) ++ (F) ++ ("bc") ++ (F) ++ ("cbccaccb") ++ (F) ++ ("b") ++ (F) ++ ("bb") ++ (F) ++ ("cbdadaac") ++ (F) ++ ("bbcdcbdacabcdbcbaabbdabb") ++ (F) ++ (F) ++ ("baaacbdd"))
    =
    (("cabcccccadccaabbc") ++ (F) ++ (F) ++ ("bba") ++ (F) ++ ("baadaabdcdccacddbc") ++ (F) ++ ("cbccaccbdbdbbdcbda") ++ (F) ++ ("aac") ++ (F) ++ ("bbc") ++ (F) ++ ("cbdacabcdbcbaabbdabb") ++ (F) ++ (F) ++ ("baaacbd") ++ (F));
constraint
  (("a") ++ (F) ++ ("accd") ++ (F) ++ ("bcccbbcbcdabdbacb") ++ (F) ++ ("bcabbc") ++ (F) ++ ("ccb") ++ (F) ++ ("c") ++ (F) ++ (F) ++ ("a") ++ (F) ++ ("aaacbc") ++ (F) ++ ("ddbda") ++ (F) ++ ("c") ++ (F) ++ (F) ++ ("cb") ++ (F) ++ ("c") ++ (F) ++ ("abada") ++ (F) ++ ("c") ++ (F) ++ ("dacccaabbcac") ++ (F) ++ ("cb") ++ (F) ++ ("cacacdc") ++ (F) ++ ("bcdca"))
    =
    (("adaccd") ++ (F) ++ ("bcccbbcbc") ++ (F) ++ ("ab") ++ (F) ++ ("bacb") ++ (F) ++ ("bcabbcdccbdcd") ++ (F) ++ ("a") ++ (F) ++ ("aaacbcd") ++ (F) ++ (F) ++ ("b") ++ (F) ++ ("adc") ++ (F) ++ (F) ++ ("cbdc") ++ (F) ++ ("aba") ++ (F) ++ ("adcd") ++ (F) ++ ("acccaabbcac") ++ (F) ++ ("cb") ++ (F) ++ ("cacacdcdbcdca"));
constraint
  ((F) ++ (F) ++ ("babcdadbbccc") ++ (F) ++ ("c") ++ (F) ++ ("bbcabdbdadab") ++ (F) ++ ("bd") ++ (F) ++ (F) ++ ("ca") ++ (F) ++ (F) ++ ("accbcbbcb") ++ (F) ++ ("ba") ++ (F) ++ ("dadc") ++ (F) ++ ("bcabbbcacbbcdcbacddccbc") ++ (F) ++ ("ba") ++ (F) ++ (F) ++ ("cbbcaaaacbac") ++ (F) ++ ("ca"))
    =
    ((F) ++ (F) ++ ("babc") ++ (F) ++ ("adbbcccdc") ++ (F) ++ ("bbcabdbda") ++ (F) ++ ("abdbd") ++ (F) ++ (F) ++ ("caddaccbcbbcbdba") ++ (F) ++ ("da") ++ (F) ++ ("c") ++ (F) ++ ("bcabbbcacbbc") ++ (F) ++ ("cbacd") ++ (F) ++ ("ccbc") ++ (F) ++ ("bad") ++ (F) ++ ("cbbcaaaacbac") ++ (F) ++ ("ca"));
constraint
  (("ac") ++ (F) ++ ("bcbabbcacddcaa") ++ (F) ++ ("dad") ++ (F) ++ ("adaccccbccdc") ++ (F) ++ ("ca") ++ (F) ++ ("cbbabbacb") ++ (F) ++ ("bc") ++ (F) ++ (F) ++ ("c") ++ (F) ++ ("cbccdaddcdbbabccbaacaab") ++ (F) ++ ("bcc") ++ (F) ++ ("c") ++ (F) ++ (F) ++ ("ab") ++ (F) ++ ("bacc") ++ (F) ++ ("abdaca"))
    =
    (("ac") ++ (F) ++ ("bcbabbcac") ++ (F) ++ ("dcaa") ++ (F) ++ (F) ++ ("a") ++ (F) ++ ("dadaccccbcc") ++ (F) ++ ("cdcadcbbabbacb") ++ (F) ++ ("bc") ++ (F) ++ ("dc") ++ (F) ++ ("cbcc") ++ (F) ++ ("a") ++ (F) ++ (F) ++ ("cdbbabccbaacaabdbccdc") ++ (F) ++ (F) ++ ("abdbacc") ++ (F) ++ ("ab") ++ (F) ++ ("aca"));
constraint
  (("dacaabcb") ++ (F) ++ ("a") ++ (F) ++ ("bd") ++ (F) ++ ("c") ++ (F) ++ ("ad") ++ (F) ++ ("cbbcb") ++ (F) ++ ("cacdab") ++ (F) ++ ("dcdbabddabdcbb") ++ (F) ++ ("c") ++ (F) ++ ("dcbcadacaacaa") ++ (F) ++ ("cabdcacdb") ++ (F) ++ ("ab") ++ (F) ++ ("bbbaadbacacccc") ++ (F) ++ ("dcab") ++ (F) ++ ("bca"))
    =
    (("dacaabcb") ++ (F) ++ ("adb") ++ (F) ++ ("dcdaddcbbcb") ++ (F) ++ ("cac") ++ (F) ++ ("abddcdbabd") ++ (F) ++ ("ab") ++ (F) ++ ("cbbdcd") ++ (F) ++ ("cbca") ++ (F) ++ ("acaacaa") ++ (F) ++ ("cab") ++ (F) ++ ("cac") ++ (F) ++ ("bdab") ++ (F) ++ ("bbbaa") ++ (F) ++ ("bacaccccd") ++ (F) ++ ("cab") ++ (F) ++ ("bca"));
constraint
  (("aadacaaccccabcccaccbddacdbaabcdb") ++ (F) ++ ("dcbbacadbcd") ++ (F) ++ ("dccc") ++ (F) ++ ("bb") ++ (F) ++ ("cbcbcbda") ++ (F) ++ ("aaaabbb") ++ (F) ++ ("bbccacdababaababcbca") ++ (F) ++ ("aad") ++ (F) ++ ("acca"))
    =
    (("aa") ++ (F) ++ ("acaaccccabcccaccbd") ++ (F) ++ ("ac") ++ (F) ++ ("baabc") ++ (F) ++ ("b") ++ (F) ++ ("dcbbaca") ++ (F) ++ ("bcd") ++ (F) ++ ("dcccdbbdcbcbcb") ++ (F) ++ ("adaaaabbbdbbccacdababaababcbca") ++ (F) ++ ("aa") ++ (F) ++ ("dacca"));
constraint
  (("acab") ++ (F) ++ ("cccbaadacc") ++ (F) ++ ("aaabaaaabcdccccbcbaaa") ++ (F) ++ ("cc") ++ (F) ++ ("cdaca") ++ (F) ++ ("c") ++ (F) ++ ("bcccadddacbcbacabbbcbbaabccbba") ++ (F) ++ ("d") ++ (F) ++ ("aaaac") ++ (F) ++ ("abdd") ++ (F) ++ ("acacba"))
    =
    (("acabdcccbaa") ++ (F) ++ ("accdaaabaaaabc") ++ (F) ++ ("ccccbcbaaa") ++ (F) ++ ("cc") ++ (F) ++ ("cdacadcdbcccad") ++ (F) ++ ("dacbcbacabbbcbbaabccbba") ++ (F) ++ ("d") ++ (F) ++ ("aaaacdab") ++ (F) ++ ("d") ++ (F) ++ ("acacba"));
constraint
  (("c") ++ (F) ++ ("bdccccbacdabcdacacccadaacdcaaabaadcbc") ++ (F) ++ (F) ++ ("aab") ++ (F) ++ ("daccdaadad") ++ (F) ++ ("cbbbba") ++ (F) ++ (F) ++ ("bcdbaccaabbccbdb") ++ (F) ++ ("b") ++ (F) ++ ("aaccbcaacdacba") ++ (F) ++ ("c"))
    =
    (("cdbdccccbac") ++ (F) ++ ("abc") ++ (F) ++ ("acacccadaacdcaaabaadcbc") ++ (F) ++ (F) ++ ("aabddacc") ++ (F) ++ ("aa") ++ (F) ++ ("a") ++ (F) ++ ("dcbbbba") ++ (F) ++ (F) ++ ("bcdbaccaabbccb") ++ (F) ++ ("b") ++ (F) ++ ("bdaaccbcaac") ++ (F) ++ ("acba") ++ (F) ++ ("c"));
constraint
  (("acbbbaba") ++ (F) ++ (F) ++ ("a") ++ (F) ++ ("a") ++ (F) ++ ("c") ++ (F) ++ ("bc") ++ (F) ++ ("dcccda") ++ (F) ++ ("cacbbbdccacc") ++ (F) ++ ("acdcaccdd") ++ (F) ++ ("bbaca") ++ (F) ++ (F) ++ ("a") ++ (F) ++ ("bbcbdcbaa") ++ (F) ++ ("dba") ++ (F) ++ ("addbccad") ++ (F) ++ ("cc") ++ (F) ++ (F) ++ ("bbbb") ++ (F) ++ ("cacaa") ++ (F) ++ ("b") ++ (F) ++ (F))
    =
    (("acbbbaba") ++ (F) ++ (F) ++ ("a") ++ (F) ++ ("adcdbcddcccdadcacbbb") ++ (F) ++ ("ccacc") ++ (F) ++ ("acdcacc") ++ (F) ++ ("d") ++ (F) ++ ("bbaca") ++ (F) ++ ("dadbbcb") ++ (F) ++ ("cbaa") ++ (F) ++ (F) ++ ("badaddbcca") ++ (F) ++ (F) ++ ("cc") ++ (F) ++ ("dbbbb") ++ (F) ++ ("cacaa") ++ (F) ++ ("bd") ++ (F));
constraint
  (("abdbddaabddcaaabccaa") ++ (F) ++ (F) ++ ("abddcda") ++ (F) ++ ("ccacbdbbadcbbb") ++ (F) ++ ("bdcaaacc") ++ (F) ++ ("aaaaba") ++ (F) ++ ("dbccadbaccbbbaccacaaadacabbbbbcbccdcbc"))
    =
    (("abdb") ++ (F) ++ ("daabd") ++ (F) ++ ("caaabccaaddab") ++ (F) ++ (F) ++ ("c") ++ (F) ++ ("a") ++ (F) ++ ("ccacbdbbadcbbbdb") ++ (F) ++ ("caaacc") ++ (F) ++ ("aaaabaddbccadbaccbbbaccacaaadacabbbbbcbccdcbc"));
constraint
  (("dddabbbdcb") ++ (F) ++ ("caaabbaaadccd") ++ (F) ++ (F) ++ ("cbadcaacca") ++ (F) ++ ("b") ++ (F) ++ (F) ++ ("db") ++ (F) ++ ("addacbcbaa") ++ (F) ++ ("adcabc") ++ (F) ++ ("abacaaababbaa") ++ (F) ++ ("aa") ++ (F) ++ ("a") ++ (F) ++ ("bbabbbbba") ++ (F) ++ ("bac") ++ (F) ++ (F) ++ ("b") ++ (F) ++ ("ba"))
    =
    (("d") ++ (F) ++ ("dabbbdcbdcaaabbaaa") ++ (F) ++ ("cc") ++ (F) ++ (F) ++ ("dcbadcaacca") ++ (F) ++ ("b") ++ (F) ++ (F) ++ ("dbda") ++ (F) ++ (F) ++ ("acbcbaadadcabc") ++ (F) ++ ("abacaaababbaadaadadbbabbbbba") ++ (F) ++ ("bac") ++ (F) ++ (F) ++ ("bdba"));
constraint
  (("aadabccacb") ++ (F) ++ ("cacbabdccccdaddbccabd") ++ (F) ++ ("dcacccbacbdcbcacbbadbaca") ++ (F) ++ ("b") ++ (F) ++ ("a") ++ (F) ++ ("aaacaadcaccbcadacbdbc") ++ (F) ++ (F) ++ ("dccabbdabbbacc"))
    =
    (("aa") ++ (F) ++ ("abccacb") ++ (F) ++ ("cacbabdccccda") ++ (F) ++ (F) ++ ("bccabd") ++ (F) ++ (F) ++ ("cacccbacbdcbcacbba") ++ (F) ++ ("baca") ++ (F) ++ ("bda") ++ (F) ++ ("aaacaa") ++ (F) ++ ("caccbcadacbdbcdd") ++ (F) ++ ("ccabbdabbbacc"));
constraint
  (("bbaccacccac") ++ (F) ++ ("da") ++ (F) ++ ("ccbca") ++ (F) ++ ("cdbd") ++ (F) ++ ("abacc") ++ (F) ++ (F) ++ ("cdc") ++ (F) ++ ("b") ++ (F) ++ ("adbc") ++ (F) ++ ("b") ++ (F) ++ ("bdacbdccbbcaa") ++ (F) ++ ("c") ++ (F) ++ ("bbbbba") ++ (F) ++ ("cdbbaacc") ++ (F) ++ (F) ++ ("acbcc") ++ (F) ++ ("c") ++ (F) ++ ("babcabdb") ++ (F) ++ ("b") ++ (F) ++ ("d"))
    =
    (("bbaccacccac") ++ (F) ++ ("da") ++ (F) ++ ("ccbca") ++ (F) ++ ("c") ++ (F) ++ ("b") ++ (F) ++ (F) ++ ("abacc") ++ (F) ++ ("dcdc") ++ (F) ++ ("bda") ++ (F) ++ ("bcdb") ++ (F) ++ ("b") ++ (F) ++ ("acb") ++ (F) ++ ("ccbbcaadc") ++ (F) ++ ("bbbbbadcdbbaacc") ++ (F) ++ ("dacbcc") ++ (F) ++ ("c") ++ (F) ++ ("babcabdbdb") ++ (F) ++ (F));
constraint
  (("cbcbccaacacaabba") ++ (F) ++ ("cacacadacdbcccbccaaabaabb") ++ (F) ++ ("a") ++ (F) ++ ("bc") ++ (F) ++ (F) ++ ("db") ++ (F) ++ ("dbbdcbaad") ++ (F) ++ (F) ++ ("ccb") ++ (F) ++ ("db") ++ (F) ++ ("adcbcabb") ++ (F) ++ ("bba") ++ (F) ++ ("acdccc") ++ (F) ++ ("cdadccbca"))
    =
    (("cbcbccaacacaabba") ++ (F) ++ ("cacaca") ++ (F) ++ ("ac") ++ (F) ++ ("bcccbccaaabaabb") ++ (F) ++ ("a") ++ (F) ++ ("bc") ++ (F) ++ (F) ++ ("db") ++ (F) ++ ("dbb") ++ (F) ++ ("cbaadd") ++ (F) ++ ("ccb") ++ (F) ++ (F) ++ ("bdadcbcabb") ++ (F) ++ ("bbadac") ++ (F) ++ ("cccdc") ++ (F) ++ ("a") ++ (F) ++ ("ccbca"));
constraint
  (("cccabb") ++ (F) ++ ("c") ++ (F) ++ ("cbcccbc") ++ (F) ++ ("bdbcbccbabbb") ++ (F) ++ ("cbbacdbabbaadbac") ++ (F) ++ ("ba") ++ (F) ++ ("aadca") ++ (F) ++ (F) ++ ("acabacccbcc") ++ (F) ++ ("c") ++ (F) ++ ("b") ++ (F) ++ ("bcaaaadbcaaacabbbbbbbccdcc"))
    =
    (("cccabbdc") ++ (F) ++ ("cbcccbc") ++ (F) ++ ("bdbcbccbabbbdcbbac") ++ (F) ++ ("babbaa") ++ (F) ++ ("bacdba") ++ (F) ++ ("aa") ++ (F) ++ ("caddacabacccbcc") ++ (F) ++ ("c") ++ (F) ++ ("bdbcaaaadbcaaacabbbbbbbcc") ++ (F) ++ ("cc"));
constraint
  (("dcdaacacdabacb") ++ (F) ++ ("aacbbbc") ++ (F) ++ ("acadbc") ++ (F) ++ ("bba") ++ (F) ++ ("b") ++ (F) ++ ("ccabdbbbcdabbaacd") ++ (F) ++ ("a") ++ (F) ++ ("bc") ++ (F) ++ (F) ++ ("ba") ++ (F) ++ ("caac") ++ (F) ++ ("cccc") ++ (F) ++ ("cadcbdbbacbaccccbabbc") ++ (F) ++ ("bac") ++ (F))
    =
    (("dc") ++ (F) ++ ("aacac") ++ (F) ++ ("abacbdaacbbbcdacadbc") ++ (F) ++ ("bbadbdccabdbbbcdabbaacdda") ++ (F) ++ ("bc") ++ (F) ++ (F) ++ ("badcaacdccccdca") ++ (F) ++ ("cbdbbacbaccccbabbcdbacd"));
constraint
  (("aababcabcb") ++ (F) ++ ("b") ++ (F) ++ ("cc") ++ (F) ++ (F) ++ ("cbbb") ++ (F) ++ ("bcabcbdabacb") ++ (F) ++ ("dbccdcabdcaccbbcacc") ++ (F) ++ ("aaacaad") ++ (F) ++ (F) ++ (F) ++ ("cbbac") ++ (F) ++ ("ccab") ++ (F) ++ ("d") ++ (F) ++ ("cddaddaa") ++ (F) ++ ("cabaabbcbaa") ++ (F))
    =
    (("aababcabcbdbdccddcbbb") ++ (F) ++ ("bcabcbdabacbddbccdcab") ++ (F) ++ ("caccbbcaccdaaacaad") ++ (F) ++ (F) ++ ("dcbbacdccabd") ++ (F) ++ (F) ++ ("cd") ++ (F) ++ ("a") ++ (F) ++ (F) ++ ("aa") ++ (F) ++ ("cabaabbcbaad"));
constraint
  (("bddcb") ++ (F) ++ ("cc") ++ (F) ++ ("baddbaabacbccb") ++ (F) ++ ("a") ++ (F) ++ ("accabbaadb") ++ (F) ++ ("dccaabbbabad") ++ (F) ++ ("ba") ++ (F) ++ ("acaac") ++ (F) ++ (F) ++ ("cbababd") ++ (F) ++ (F) ++ ("cdacbacc") ++ (F) ++ ("aaabdaa") ++ (F) ++ ("cbb") ++ (F) ++ (F) ++ ("dccbdc") ++ (F) ++ ("c"))
    =
    (("bd") ++ (F) ++ ("cb") ++ (F) ++ ("cc") ++ (F) ++ ("ba") ++ (F) ++ (F) ++ ("baabacbccbdadaccabbaadb") ++ (F) ++ (F) ++ ("ccaabbbaba") ++ (F) ++ (F) ++ ("badacaac") ++ (F) ++ ("dcbababd") ++ (F) ++ ("dcdacbacc") ++ (F) ++ ("aaab") ++ (F) ++ ("aadcbbd") ++ (F) ++ (F) ++ ("ccbdcdc"));
constraint
  (("bcdaacbbabbcadd") ++ (F) ++ ("acbbaaacbadba") ++ (F) ++ ("abdacbcabaaabdbbcba") ++ (F) ++ (F) ++ ("ddaacaccababcdca") ++ (F) ++ ("c") ++ (F) ++ ("aaacaaabdaccbcbbabb") ++ (F) ++ ("b") ++ (F) ++ ("dbbaa") ++ (F) ++ ("c"))
    =
    (("bcdaacbbabbcad") ++ (F) ++ (F) ++ ("acbbaaacba") ++ (F) ++ ("ba") ++ (F) ++ ("abdacbcabaaab") ++ (F) ++ ("bbcbad") ++ (F) ++ (F) ++ (F) ++ ("aacaccababcdca") ++ (F) ++ ("cdaaacaaabdaccbcbbabbdb") ++ (F) ++ ("dbbaa") ++ (F) ++ ("c"));
constraint
  (("babacaabaabcbad") ++ (F) ++ ("bdcca") ++ (F) ++ ("dbdabbbdbcbbaabcbc") ++ (F) ++ ("acb") ++ (F) ++ ("bbcbadba") ++ (F) ++ ("bdaabacd") ++ (F) ++ ("bacbbab") ++ (F) ++ ("baacbdcdbabaccabcd") ++ (F) ++ ("a") ++ (F) ++ ("bccddad"))
    =
    (("babacaabaabcba") ++ (F) ++ ("db") ++ (F) ++ ("cca") ++ (F) ++ ("db") ++ (F) ++ ("abbb") ++ (F) ++ ("bcbbaabcbcdacbdbbcba") ++ (F) ++ ("ba") ++ (F) ++ ("b") ++ (F) ++ ("aabac") ++ (F) ++ ("dbacbbabdbaacbdc") ++ (F) ++ ("babaccabcdda") ++ (F) ++ ("bcc") ++ (F) ++ ("dad"));
constraint
  (("ccddb") ++ (F) ++ ("cd") ++ (F) ++ ("b") ++ (F) ++ (F) ++ ("c") ++ (F) ++ ("bbcaabccadbb") ++ (F) ++ ("a") ++ (F) ++ ("abc") ++ (F) ++ ("abbaadbcdbaadbcadcc") ++ (F) ++ ("dab") ++ (F) ++ (F) ++ ("aaacccacacccacbbdcaadccadbcacabadccddaabc"))
    =
    (("ccd") ++ (F) ++ ("bdcd") ++ (F) ++ ("bddcdbbcaabcca") ++ (F) ++ ("bbda") ++ (F) ++ ("abc") ++ (F) ++ ("abbaa") ++ (F) ++ ("bc") ++ (F) ++ ("baa") ++ (F) ++ ("bcadcc") ++ (F) ++ (F) ++ ("ab") ++ (F) ++ ("daaacccacacccacbb") ++ (F) ++ ("caadcca") ++ (F) ++ ("bcacabadcc") ++ (F) ++ ("daabc"));
constraint
  ((F) ++ ("abbbca") ++ (F) ++ ("c") ++ (F) ++ (F) ++ ("bdaccaaadcacaacab") ++ (F) ++ (F) ++ ("abacbcabcac") ++ (F) ++ ("b") ++ (F) ++ ("bacccc") ++ (F) ++ ("baba") ++ (F) ++ ("aaa") ++ (F) ++ ("cccaabcba") ++ (F) ++ ("bacaabcccabcccabcaac") ++ (F) ++ (F) ++ ("caabbba"))
    =
    (("dabbbcadc") ++ (F) ++ (F) ++ ("b") ++ (F) ++ ("accaaa") ++ (F) ++ ("cacaacab") ++ (F) ++ ("dabacbcabcac") ++ (F) ++ ("b") ++ (F) ++ ("baccccdbabadaaadcccaabcba") ++ (F) ++ ("bacaabcccabcccabcaac") ++ (F) ++ (F) ++ ("caabbba"));
constraint
  (("badcbb") ++ (F) ++ ("bcaaaaacdbb") ++ (F) ++ ("ba") ++ (F) ++ ("cc") ++ (F) ++ ("b") ++ (F) ++ ("dcbabdaccaccabcd") ++ (F) ++ ("ccabcbbcbacbcaab") ++ (F) ++ ("a") ++ (F) ++ ("adabb") ++ (F) ++ (F) ++ ("baccb") ++ (F) ++ ("babbcbabcabc") ++ (F) ++ ("aab") ++ (F) ++ (F) ++ (F) ++ ("acc") ++ (F))
    =
    (("badcbbdbcaaaaacdbbdba") ++ (F) ++ ("cc") ++ (F) ++ ("b") ++ (F) ++ (F) ++ ("cbab") ++ (F) ++ ("accaccabcd") ++ (F) ++ ("ccabcbbcbacbcaabdadadabbddbaccb") ++ (F) ++ ("babbcbabcabcdaab") ++ (F) ++ ("ddaccd"));
constraint
  ((F) ++ ("d") ++ (F) ++ ("abcbcbaacdca") ++ (F) ++ ("abb") ++ (F) ++ ("ccbbbaabbbbadbccabdcacaaa") ++ (F) ++ ("cbaabdadd") ++ (F) ++ ("aaccabbac") ++ (F) ++ ("aacbcbccdddbac") ++ (F) ++ ("ababcdbb") ++ (F) ++ ("cbabcab") ++ (F) ++ ("b"))
    =
    ((F) ++ (F) ++ (F) ++ ("abcbcbaacdcadabb") ++ (F) ++ ("ccbbbaabbbba") ++ (F) ++ ("bccab") ++ (F) ++ ("cacaaadcbaabdad") ++ (F) ++ ("daaccabbacdaacbcbcc") ++ (F) ++ ("ddbac") ++ (F) ++ ("ababc") ++ (F) ++ ("bbdcbabcabdb"));
constraint
  (("d") ++ (F) ++ ("bab") ++ (F) ++ ("acaaabab") ++ (F) ++ ("bccccbbacaadacaabcabbabbadadadabac") ++ (F) ++ ("dcbdccdbcbadbabc") ++ (F) ++ ("abbbabda") ++ (F) ++ ("d") ++ (F) ++ ("dbabacdaca") ++ (F) ++ ("acccdbdadd"))
    =
    (("ddbab") ++ (F) ++ ("acaaababdbccccbbacaa") ++ (F) ++ ("acaabcabbabbadadadabac") ++ (F) ++ ("dcb") ++ (F) ++ ("ccdbcbadbabc") ++ (F) ++ ("abbbabda") ++ (F) ++ (F) ++ (F) ++ ("dbabacdacadacccdbda") ++ (F) ++ (F));
constraint
  (("abcaabbbacdbcaaaaca") ++ (F) ++ ("dbc") ++ (F) ++ ("caab") ++ (F) ++ ("aacdbbabacbcbdaabbbaca") ++ (F) ++ ("cadc") ++ (F) ++ ("aa") ++ (F) ++ ("babbbcabbccbcc") ++ (F) ++ ("bdbbacb") ++ (F) ++ (F) ++ ("ccdabcccccbabcc"))
    =
    (("abcaabbbac") ++ (F) ++ ("bcaaaacad") ++ (F) ++ ("bcdcaab") ++ (F) ++ ("aac") ++ (F) ++ ("bbabacbcbdaabbbacadca") ++ (F) ++ ("cdaa") ++ (F) ++ ("babbbcabbccbcc") ++ (F) ++ ("bdbbacb") ++ (F) ++ (F) ++ ("cc") ++ (F) ++ ("abcccccbabcc"));
constraint
  (("ac") ++ (F) ++ ("cbcd") ++ (F) ++ ("b") ++ (F) ++ ("bdacbbcbccba") ++ (F) ++ ("dbca") ++ (F) ++ ("bcbacbbbbdbabacdccda") ++ (F) ++ ("c") ++ (F) ++ ("bdaccacba") ++ (F) ++ ("aa") ++ (F) ++ (F) ++ (F) ++ ("abbbcadadb") ++ (F) ++ ("db") ++ (F) ++ ("bbcb") ++ (F) ++ ("cabbaaaadcaacd"))
    =
    (("acdcbcddb") ++ (F) ++ ("b") ++ (F) ++ ("acbbcbccbad") ++ (F) ++ ("bcadbcbacbbbb") ++ (F) ++ ("babacdccdadc") ++ (F) ++ ("b") ++ (F) ++ ("accacbadaa") ++ (F) ++ (F) ++ (F) ++ ("abbbcadadbd") ++ (F) ++ ("b") ++ (F) ++ ("bbcb") ++ (F) ++ ("cabbaaaadcaac") ++ (F));
constraint
  (("bb") ++ (F) ++ ("ca") ++ (F) ++ ("babb") ++ (F) ++ ("babb") ++ (F) ++ ("cbdbcbbdbaccdb") ++ (F) ++ ("cabaabcccddabc") ++ (F) ++ ("ada") ++ (F) ++ ("bcb") ++ (F) ++ ("c") ++ (F) ++ ("dbab") ++ (F) ++ ("cbc") ++ (F) ++ ("c") ++ (F) ++ ("bd") ++ (F) ++ (F) ++ ("cbcdaabacabdb") ++ (F) ++ ("abcbacb") ++ (F) ++ ("ac") ++ (F) ++ ("cbc"))
    =
    (("bbdca") ++ (F) ++ ("babb") ++ (F) ++ ("babbdcb") ++ (F) ++ ("bcbbdbacc") ++ (F) ++ ("b") ++ (F) ++ ("cabaabccc") ++ (F) ++ ("dabcda") ++ (F) ++ ("a") ++ (F) ++ ("bcbdcddbabdcbcdc") ++ (F) ++ ("b") ++ (F) ++ (F) ++ ("dcbcdaabacab") ++ (F) ++ ("b") ++ (F) ++ ("abcbacb") ++ (F) ++ ("acdcbc"));
constraint
  (("bdcbabcadbbababba") ++ (F) ++ ("cccabcbd") ++ (F) ++ ("cbbbcabaaaacddabaacaabc") ++ (F) ++ ("bb") ++ (F) ++ ("bcabbacdbcaabdbdbadaca") ++ (F) ++ ("caabbcaabcca") ++ (F) ++ ("aacaccca") ++ (F))
    =
    (("bdcbabcadbbababba") ++ (F) ++ ("cccabcbddcbbbcabaaaacddabaacaabc") ++ (F) ++ ("bb") ++ (F) ++ ("bcabbac") ++ (F) ++ ("bcaabdb") ++ (F) ++ ("badacadcaabbcaabccadaacacccad"));
constraint
  ((F) ++ ("cabaadcaaccbabccadadababcabbcababa") ++ (F) ++ (F) ++ (F) ++ (F) ++ ("cb") ++ (F) ++ ("aba") ++ (F) ++ ("dbcdacdaa") ++ (F) ++ ("ac") ++ (F) ++ (F) ++ ("d") ++ (F) ++ (F) ++ ("bbd") ++ (F) ++ ("accccc") ++ (F) ++ ("ddcccaacd") ++ (F) ++ ("acccabcda") ++ (F) ++ ("acbab"))
    =
    ((F) ++ ("cabaadcaaccbabccada") ++ (F) ++ ("ababcabbcababa") ++ (F) ++ ("d") ++ (F) ++ (F) ++ ("cb") ++ (F) ++ ("abad") ++ (F) ++ ("bcdac") ++ (F) ++ ("aa") ++ (F) ++ ("acd") ++ (F) ++ ("dd") ++ (F) ++ ("bb") ++ (F) ++ (F) ++ ("acccccd") ++ (F) ++ (F) ++ ("cccaac") ++ (F) ++ ("dacccabcda") ++ (F) ++ ("acbab"));
constraint
  (("cc") ++ (F) ++ ("bcbbcadbb") ++ (F) ++ ("a") ++ (F) ++ ("cbbadbd") ++ (F) ++ ("bdcbaaab") ++ (F) ++ ("c") ++ (F) ++ ("aaa") ++ (F) ++ (F) ++ (F) ++ ("ca") ++ (F) ++ ("a") ++ (F) ++ ("ccbacd") ++ (F) ++ ("cbabcab") ++ (F) ++ ("accaabaaccbccc") ++ (F) ++ ("dc") ++ (F) ++ ("bbcaacbcbdcbcba") ++ (F) ++ (F) ++ ("dccb"))
    =
    (("cc") ++ (F) ++ ("bcbbcadbbdadcbba") ++ (F) ++ ("bddb") ++ (F) ++ ("cbaaab") ++ (F) ++ ("cdaaa") ++ (F) ++ (F) ++ ("dca") ++ (F) ++ ("adccbacddcbabcabdaccaabaaccbcccddc") ++ (F) ++ ("bbcaacbcbdcbcbad") ++ (F) ++ ("dccb"));
constraint
  (("acdbbbdbadc") ++ (F) ++ ("acaadccaacbbcdccbcdbad") ++ (F) ++ ("cbcbda") ++ (F) ++ ("dbdcadaac") ++ (F) ++ ("bcaaccbbbccaa") ++ (F) ++ ("babbdabddacdcbbccd") ++ (F) ++ ("cbbbcbdb") ++ (F) ++ (F) ++ ("a") ++ (F) ++ ("cc"))
    =
    (("ac") ++ (F) ++ ("bbbdbadc") ++ (F) ++ ("acaadccaacbbc") ++ (F) ++ ("ccbc") ++ (F) ++ ("ba") ++ (F) ++ (F) ++ ("cbcbdad") ++ (F) ++ ("bdcadaacdbcaaccbbbccaadbabbdabddacdcbbcc") ++ (F) ++ ("dcbbbcbdbd") ++ (F) ++ ("adcc"));
constraint
  (("ca") ++ (F) ++ ("bcc") ++ (F) ++ ("bcabcbddcaa") ++ (F) ++ ("abb") ++ (F) ++ ("a") ++ (F) ++ ("ccaacacaba") ++ (F) ++ ("cbcabb") ++ (F) ++ ("ccacda") ++ (F) ++ ("acac") ++ (F) ++ ("abb") ++ (F) ++ ("cdabca") ++ (F) ++ ("dabbb") ++ (F) ++ ("d") ++ (F) ++ ("addcacccbbddaccacbbacabab"))
    =
    (("ca") ++ (F) ++ ("bcc") ++ (F) ++ ("bcabcb") ++ (F) ++ (F) ++ ("caa") ++ (F) ++ ("abbda") ++ (F) ++ ("ccaacacabadcbcabbdccac") ++ (F) ++ ("adacacdabbdcdabca") ++ (F) ++ (F) ++ ("abbb") ++ (F) ++ (F) ++ ("daddcacccbb") ++ (F) ++ ("daccacbbacabab"));
constraint
  (("bdcaaabcd") ++ (F) ++ ("bddcbad") ++ (F) ++ ("bccbaacddbbacccabaabadbacbcaacbcdacbdb") ++ (F) ++ ("cbabad") ++ (F) ++ ("dcc") ++ (F) ++ ("cc") ++ (F) ++ ("bbcaaab") ++ (F) ++ ("adbbcabcadacdbcbbbc") ++ (F))
    =
    (("b") ++ (F) ++ ("caaabcd") ++ (F) ++ ("b") ++ (F) ++ ("dcbaddbccbaac") ++ (F) ++ (F) ++ ("bbacccabaaba") ++ (F) ++ ("bacbcaacbcdacbdb") ++ (F) ++ ("cbabad") ++ (F) ++ (F) ++ ("ccdccdbbcaaabda") ++ (F) ++ ("bbcabcadacdbcbbbcd"));
constraint
  (("abaccaacacaaccccb") ++ (F) ++ ("aacadcdc") ++ (F) ++ (F) ++ ("ccbadb") ++ (F) ++ ("cc") ++ (F) ++ ("dad") ++ (F) ++ ("abcaadbac") ++ (F) ++ ("ccb") ++ (F) ++ ("bc") ++ (F) ++ ("bb") ++ (F) ++ ("caca") ++ (F) ++ ("c") ++ (F) ++ ("dbbbabba") ++ (F) ++ ("dacdaaac") ++ (F) ++ ("adacbc") ++ (F) ++ ("dca") ++ (F) ++ ("b"))
    =
    (("abaccaacacaaccccb") ++ (F) ++ ("aaca") ++ (F) ++ ("cdcd") ++ (F) ++ ("ccba") ++ (F) ++ ("b") ++ (F) ++ ("cc") ++ (F) ++ (F) ++ ("addabcaadbac") ++ (F) ++ ("ccb") ++ (F) ++ ("bcdbb") ++ (F) ++ ("cacadc") ++ (F) ++ (F) ++ ("bbbabba") ++ (F) ++ (F) ++ ("ac") ++ (F) ++ ("aaacda") ++ (F) ++ ("acbcddca") ++ (F) ++ ("b"));
constraint
  (("cdd") ++ (F) ++ ("dcdaaaaaabcccdabdcccaa") ++ (F) ++ ("da") ++ (F) ++ ("aacacdbdb") ++ (F) ++ ("a") ++ (F) ++ ("bbc") ++ (F) ++ ("bbd") ++ (F) ++ ("dbacccdba") ++ (F) ++ ("d") ++ (F) ++ ("c") ++ (F) ++ ("acaaadbbd") ++ (F) ++ ("dabdaddddaadca") ++ (F) ++ ("bcadadddbc"))
    =
    (("c") ++ (F) ++ ("d") ++ (F) ++ (F) ++ ("cdaaaaaabcccdabdcccaaddadaacacdbdb") ++ (F) ++ ("adbbc") ++ (F) ++ ("bbdddbaccc") ++ (F) ++ ("badd") ++ (F) ++ ("cdacaaa") ++ (F) ++ ("bbdd") ++ (F) ++ ("abda") ++ (F) ++ (F) ++ (F) ++ (F) ++ ("aa") ++ (F) ++ ("ca") ++ (F) ++ ("bcada") ++ (F) ++ ("d") ++ (F) ++ ("bc"));
constraint
  (("bcabcb") ++ (F) ++ ("bbd") ++ (F) ++ (F) ++ ("cabddbbacccccccdcdc") ++ (F) ++ ("baabbbaaa") ++ (F) ++ (F) ++ (F) ++ ("aaccbabcbccbcdcadddcbaacbbacaacbcba") ++ (F) ++ ("acbbbaddcbbdbcacacb"))
    =
    (("bcabcb") ++ (F) ++ ("bbd") ++ (F) ++ ("dcabddbbacccccccdcdcdbaabbbaaadddaaccbabcbccbcdcad") ++ (F) ++ ("dcbaacbbacaacbcba") ++ (F) ++ ("acbbba") ++ (F) ++ ("dcbbdbcacacb"));
constraint
  (("aacbbdcadccdaba") ++ (F) ++ ("dcacbabb") ++ (F) ++ ("bc") ++ (F) ++ ("bbdbacbabc") ++ (F) ++ ("bbbdcabcd") ++ (F) ++ ("dbbcdcacb") ++ (F) ++ (F) ++ ("cbbadaaccabb") ++ (F) ++ ("bcc") ++ (F) ++ ("adbdc") ++ (F) ++ ("dcdcbabcdcda") ++ (F) ++ ("cdc"))
    =
    (("aacbbdcadccdaba") ++ (F) ++ (F) ++ ("cacbabb") ++ (F) ++ ("bcdbbdbacbabc") ++ (F) ++ ("bbb") ++ (F) ++ ("cabcdddbbc") ++ (F) ++ ("cacbd") ++ (F) ++ ("cbba") ++ (F) ++ ("aaccabbdbccda") ++ (F) ++ ("bdc") ++ (F) ++ ("dcdcbabcdc") ++ (F) ++ ("adc") ++ (F) ++ ("c"));
constraint
  (("accacdaacbccbcaaccbbcadacacbaddbdbbcb") ++ (F) ++ ("c") ++ (F) ++ ("bdcaa") ++ (F) ++ ("dccaaaacbd") ++ (F) ++ (F) ++ ("bdcaacaccdddcd") ++ (F) ++ ("cbdbaccd") ++ (F) ++ ("adcccdcbbcabc") ++ (F) ++ ("bbb"))
    =
    (("accacdaacbccbcaaccbbcadacacbad") ++ (F) ++ ("b") ++ (F) ++ ("bbcbdc") ++ (F) ++ ("bdcaad") ++ (F) ++ ("ccaaaacb") ++ (F) ++ (F) ++ (F) ++ ("bdcaacacc") ++ (F) ++ (F) ++ (F) ++ ("c") ++ (F) ++ (F) ++ ("cb") ++ (F) ++ ("bacc") ++ (F) ++ ("da") ++ (F) ++ ("cccdcbbcabc") ++ (F) ++ ("bbb"));
constraint
  (("ca") ++ (F) ++ ("d") ++ (F) ++ (F) ++ ("bbcbabbacba") ++ (F) ++ (F) ++ ("bbcca") ++ (F) ++ ("acacaccab") ++ (F) ++ ("ba") ++ (F) ++ ("aadbacccadcadaabdcdabbbabdbcaacbbdabccccababcabd") ++ (F) ++ ("abaca") ++ (F) ++ ("bdaaac"))
    =
    (("ca") ++ (F) ++ (F) ++ ("ddbbcbabbacba") ++ (F) ++ (F) ++ ("bbcca") ++ (F) ++ ("acacaccab") ++ (F) ++ ("badaadbaccca") ++ (F) ++ ("ca") ++ (F) ++ ("aab") ++ (F) ++ ("c") ++ (F) ++ ("abbbab") ++ (F) ++ ("bcaacbbdabccccababcab") ++ (F) ++ ("dabacadb") ++ (F) ++ ("aaac"));
constraint
  (("dccadaccccba") ++ (F) ++ ("ccaaacaadbdabdbdcabaabc") ++ (F) ++ ("bbdcadc") ++ (F) ++ ("bbbcdbbbaccaab") ++ (F) ++ ("dcaaaabcbbcaccabb") ++ (F) ++ (F) ++ ("accc") ++ (F) ++ ("dbcaccabaaac") ++ (F) ++ ("ba"))
    =
    (("dccadaccccbadccaaacaadbdabdbdcabaabc") ++ (F) ++ ("bb") ++ (F) ++ ("cadcdbbbc") ++ (F) ++ ("bbbaccaabddcaaaabcbbcaccabbd") ++ (F) ++ ("acccd") ++ (F) ++ ("bcaccabaaacdba"));
constraint
  ((F) ++ (F) ++ ("bca") ++ (F) ++ (F) ++ ("bab") ++ (F) ++ ("ccbdabcbdddd") ++ (F) ++ ("daadc") ++ (F) ++ ("db") ++ (F) ++ ("cdbbcdd") ++ (F) ++ ("bbd") ++ (F) ++ ("abbdcbcca") ++ (F) ++ ("babbbcdccbcacacdca") ++ (F) ++ ("bccbbacbdbcb") ++ (F) ++ ("aabccacccda") ++ (F))
    =
    (("d") ++ (F) ++ ("bca") ++ (F) ++ (F) ++ ("bab") ++ (F) ++ ("ccb") ++ (F) ++ ("abcbd") ++ (F) ++ ("ddd") ++ (F) ++ ("aadc") ++ (F) ++ (F) ++ ("bdc") ++ (F) ++ ("bbc") ++ (F) ++ (F) ++ (F) ++ ("bbd") ++ (F) ++ ("abbdcbcca") ++ (F) ++ ("babbbc") ++ (F) ++ ("ccbcacac") ++ (F) ++ ("cadbccbbacb") ++ (F) ++ ("bcbdaabccaccc") ++ (F) ++ ("ad"));
constraint
  (("abaabbbdaaccaaaacaacccdbdcd") ++ (F) ++ ("aaddca") ++ (F) ++ (F) ++ ("ccbbbcabdcabdda") ++ (F) ++ ("cabb") ++ (F) ++ ("ccabbdc") ++ (F) ++ ("abbabcca") ++ (F) ++ ("cdca") ++ (F) ++ ("bdccbcca") ++ (F) ++ ("db") ++ (F) ++ ("aaada") ++ (F) ++ (F) ++ ("c"))
    =
    (("abaabbb") ++ (F) ++ ("aaccaaaacaaccc") ++ (F) ++ ("b") ++ (F) ++ ("cd") ++ (F) ++ ("aad") ++ (F) ++ ("cad") ++ (F) ++ ("ccbbbcab") ++ (F) ++ ("cab") ++ (F) ++ (F) ++ ("adcabbdccabbdc") ++ (F) ++ ("abbabcca") ++ (F) ++ ("c") ++ (F) ++ ("cadbdccbcca") ++ (F) ++ ("db") ++ (F) ++ ("aaa") ++ (F) ++ ("ad") ++ (F) ++ ("c"));
constraint
  (("caccbbabdddaccdcbd") ++ (F) ++ ("caadabdbad") ++ (F) ++ ("bdcaacac") ++ (F) ++ ("aaab") ++ (F) ++ ("abbcabcdcadbbccadabac") ++ (F) ++ (F) ++ ("bcd") ++ (F) ++ (F) ++ ("c") ++ (F) ++ ("adbddbdba") ++ (F) ++ ("bcdbbadca") ++ (F) ++ ("ccc") ++ (F) ++ ("b"))
    =
    (("caccbbabdddacc") ++ (F) ++ ("cbd") ++ (F) ++ ("caadabdbaddb") ++ (F) ++ ("caacacdaaabdabbcabcdcadbbcca") ++ (F) ++ ("abac") ++ (F) ++ (F) ++ ("bc") ++ (F) ++ ("d") ++ (F) ++ ("c") ++ (F) ++ ("a") ++ (F) ++ ("b") ++ (F) ++ ("dbdba") ++ (F) ++ ("bc") ++ (F) ++ ("bba") ++ (F) ++ ("cadcccdb"));
constraint
  (("bcb") ++ (F) ++ (F) ++ ("cccaacaccbcc") ++ (F) ++ ("dccdbbaba") ++ (F) ++ ("a") ++ (F) ++ ("aacadadabb") ++ (F) ++ ("cabdbbbabdccb") ++ (F) ++ ("dcad") ++ (F) ++ ("bcaadbd") ++ (F) ++ ("acdbaaabddaaa") ++ (F) ++ (F) ++ ("c") ++ (F) ++ ("aacaaadbcccbcc"))
    =
    (("bcb") ++ (F) ++ ("dcccaacaccbccddcc") ++ (F) ++ ("bbabada") ++ (F) ++ ("aaca") ++ (F) ++ ("a") ++ (F) ++ ("abbdcab") ++ (F) ++ ("bbbabdccb") ++ (F) ++ ("dcad") ++ (F) ++ ("bcaa") ++ (F) ++ ("bd") ++ (F) ++ ("ac") ++ (F) ++ ("baaab") ++ (F) ++ ("daaaddcdaacaaa") ++ (F) ++ ("bcccbcc"));
constraint
  (("ab") ++ (F) ++ ("abbdbbcbcaaacccdcddbacdbbbcb") ++ (F) ++ ("bbabcbbccc") ++ (F) ++ ("babcbcdbacaadaad") ++ (F) ++ (F) ++ ("ccb") ++ (F) ++ (F) ++ ("b") ++ (F) ++ (F) ++ ("cadaaddaabd") ++ (F) ++ ("bdcabd") ++ (F) ++ ("cbabcdcbcc") ++ (F))
    =
    (("ab") ++ (F) ++ ("abbdbbcbcaaacccdcddbac") ++ (F) ++ ("bbbcbdbbabcbbccc") ++ (F) ++ ("babcbc") ++ (F) ++ ("bacaa") ++ (F) ++ ("aa") ++ (F) ++ (F) ++ (F) ++ ("ccb") ++ (F) ++ (F) ++ ("bddca") ++ (F) ++ ("aaddaab") ++ (F) ++ (F) ++ ("bdcabddcbabc") ++ (F) ++ ("cbccd"));
constraint
  (("bccccabdbdcacdbc") ++ (F) ++ ("d") ++ (F) ++ ("bacaaabccccdaccbbdc") ++ (F) ++ ("dca") ++ (F) ++ ("aa") ++ (F) ++ (F) ++ ("b") ++ (F) ++ ("bbbdcbaa") ++ (F) ++ ("ca") ++ (F) ++ ("acacbcbabdbcccaaaadc") ++ (F) ++ ("bdcaaab") ++ (F) ++ ("aab") ++ (F) ++ ("ccdcd"))
    =
    (("bccccabdb") ++ (F) ++ ("cac") ++ (F) ++ ("bcdd") ++ (F) ++ ("bacaaabccccdaccbb") ++ (F) ++ ("c") ++ (F) ++ ("dcadaad") ++ (F) ++ ("bdbbbdcbaa") ++ (F) ++ ("cadacacbcbabdbcccaaaadcdb") ++ (F) ++ ("caaabdaabdcc") ++ (F) ++ ("cd"));
constraint
  (("cddbcaaddbcabcdc") ++ (F) ++ ("abdacabcccabccabcaac") ++ (F) ++ ("caadbabcddcaccaa") ++ (F) ++ ("caadbbb") ++ (F) ++ ("abbcbcacaacccaacbdba") ++ (F) ++ ("cb") ++ (F) ++ ("abbaabccaaaa"))
    =
    (("cddbcaa") ++ (F) ++ (F) ++ ("bcabc") ++ (F) ++ ("cdabdacabcccabccabcaacdcaa") ++ (F) ++ ("babc") ++ (F) ++ (F) ++ ("caccaa") ++ (F) ++ ("caa") ++ (F) ++ ("bbb") ++ (F) ++ ("abbcbcacaacccaacb") ++ (F) ++ ("badcb") ++ (F) ++ ("abbaabccaaaa"));
constraint
  (("ccbba") ++ (F) ++ ("badabbaadaccaaacaabdbbabcbbba") ++ (F) ++ ("ccadcca") ++ (F) ++ ("aaccdbdbacdddbcdbcb") ++ (F) ++ ("acadbadbaccb") ++ (F) ++ ("adab") ++ (F) ++ ("bdbbdcccacacbdaaa"))
    =
    (("ccbba") ++ (F) ++ ("badabbaa") ++ (F) ++ ("accaaacaab") ++ (F) ++ ("bbabcbbbadccadccadaaccdbdbacd") ++ (F) ++ ("dbc") ++ (F) ++ ("bcbdacadbadbaccbdadab") ++ (F) ++ ("bdbbdcccacacb") ++ (F) ++ ("aaa"));
constraint
  (("bbbdcccabbdcbdcccbddccbdcbb") ++ (F) ++ ("bbacaabcadbb") ++ (F) ++ ("adccbbaacad") ++ (F) ++ ("ccaacadcabbadbdddbabaadbabdaabcabaacbddaaccabb"))
    =
    (("bbb") ++ (F) ++ ("cccabbdcbdcccbddccb") ++ (F) ++ ("cbb") ++ (F) ++ ("bbacaabcadbb") ++ (F) ++ ("adccbbaacad") ++ (F) ++ ("ccaaca") ++ (F) ++ ("cabbadbdddbabaadbabdaabcabaacb") ++ (F) ++ ("daaccabb"));
constraint
  (("cddcc") ++ (F) ++ ("dccaaccbbdc") ++ (F) ++ ("dccadbacddcbdcacccccdaccabbbd") ++ (F) ++ ("cbca") ++ (F) ++ ("aacdcca") ++ (F) ++ ("accabbcdcbcaabcadacbca") ++ (F) ++ ("a") ++ (F) ++ ("aabaad") ++ (F) ++ ("cacb") ++ (F) ++ ("c"))
    =
    (("c") ++ (F) ++ ("dccd") ++ (F) ++ ("ccaaccbb") ++ (F) ++ ("cd") ++ (F) ++ ("cca") ++ (F) ++ ("bacd") ++ (F) ++ ("cbdcacccccdaccabbbddcbcadaac") ++ (F) ++ ("cca") ++ (F) ++ ("accabbc") ++ (F) ++ ("cbcaabcadacbca") ++ (F) ++ ("a") ++ (F) ++ ("aabaaddcacb") ++ (F) ++ ("c"));
constraint
  (("cb") ++ (F) ++ ("bbbcd") ++ (F) ++ ("cdcbcaca") ++ (F) ++ ("a") ++ (F) ++ ("dbdba") ++ (F) ++ ("bcdc") ++ (F) ++ ("acbbacadbcbcbcbcbbac") ++ (F) ++ ("bacbdc") ++ (F) ++ (F) ++ ("ca") ++ (F) ++ ("d") ++ (F) ++ (F) ++ ("cbcbcaaaa") ++ (F) ++ ("bcbbaabcdbccaabbaac") ++ (F) ++ ("bcc"))
    =
    (("cbdbbbc") ++ (F) ++ (F) ++ ("c") ++ (F) ++ ("cbcaca") ++ (F) ++ ("a") ++ (F) ++ (F) ++ ("bdba") ++ (F) ++ ("bcdc") ++ (F) ++ ("acbbaca") ++ (F) ++ ("bcbcbcbcbbac") ++ (F) ++ ("bacb") ++ (F) ++ ("c") ++ (F) ++ ("dcad") ++ (F) ++ (F) ++ (F) ++ ("cbcbcaaaa") ++ (F) ++ ("bcbbaabc") ++ (F) ++ ("bccaabbaac") ++ (F) ++ ("bcc"));
constraint
  (("bbcbdcab") ++ (F) ++ ("ddbdacccbdbccbbcbdadbba") ++ (F) ++ ("aadcdadda") ++ (F) ++ ("dcd") ++ (F) ++ (F) ++ ("bdbcd") ++ (F) ++ ("bcbbcabcaacd") ++ (F) ++ (F) ++ ("dbcaaccbdca") ++ (F) ++ ("bbccabadc") ++ (F) ++ ("cbd") ++ (F) ++ ("bbca") ++ (F))
    =
    (("bbcbdcabdd") ++ (F) ++ ("bdacccbdbccbbcb") ++ (F) ++ ("adbbadaa") ++ (F) ++ ("c") ++ (F) ++ ("a") ++ (F) ++ (F) ++ ("a") ++ (F) ++ (F) ++ ("c") ++ (F) ++ ("ddbdbcddbcbbcabcaac") ++ (F) ++ (F) ++ (F) ++ ("dbcaaccbdca") ++ (F) ++ ("bbccaba") ++ (F) ++ ("cdcb") ++ (F) ++ (F) ++ ("bbcad"));
constraint
  (("c") ++ (F) ++ ("cccc") ++ (F) ++ ("cd") ++ (F) ++ ("ccabbcbcbd") ++ (F) ++ ("bbdcdba") ++ (F) ++ ("acdaaaccadcdc") ++ (F) ++ ("bb") ++ (F) ++ ("acbab") ++ (F) ++ ("aabadcdabdac") ++ (F) ++ ("dcbbccbda") ++ (F) ++ ("ccaccd") ++ (F) ++ ("ccd") ++ (F) ++ ("abaabcdcc") ++ (F) ++ ("bbc"))
    =
    (("c") ++ (F) ++ ("ccccdcddccabbcbcb") ++ (F) ++ (F) ++ ("bb") ++ (F) ++ ("c") ++ (F) ++ ("badac") ++ (F) ++ ("aaaccadc") ++ (F) ++ ("c") ++ (F) ++ ("bbdacbabdaabadc") ++ (F) ++ ("abdacd") ++ (F) ++ ("cbbccb") ++ (F) ++ ("adccaccd") ++ (F) ++ ("ccd") ++ (F) ++ ("abaabc") ++ (F) ++ ("cc") ++ (F) ++ ("bbc"));
constraint
  (("bdccaadadccc") ++ (F) ++ ("c") ++ (F) ++ ("c") ++ (F) ++ ("dbbbcad") ++ (F) ++ ("ddcbcbaabb") ++ (F) ++ ("bbaccdbdbbdaabacbbbd") ++ (F) ++ ("acb") ++ (F) ++ ("a") ++ (F) ++ ("cbdc") ++ (F) ++ ("cbb") ++ (F) ++ ("ca") ++ (F) ++ ("adcbbaacbdaddaacdbccbccb"))
    =
    (("b") ++ (F) ++ ("ccaada") ++ (F) ++ ("cccdc") ++ (F) ++ ("c") ++ (F) ++ (F) ++ ("bbbcadd") ++ (F) ++ ("dcbcbaabbdbbaccdb") ++ (F) ++ ("bbdaabacbbb") ++ (F) ++ (F) ++ ("acbdadcbdc") ++ (F) ++ ("cbbdca") ++ (F) ++ ("a") ++ (F) ++ ("cbbaacbda") ++ (F) ++ ("daac") ++ (F) ++ ("bccbccb"));
constraint
  (("dcbcccdbc") ++ (F) ++ ("ac") ++ (F) ++ (F) ++ ("b") ++ (F) ++ ("acaccdbaaccacabdbdb") ++ (F) ++ ("badcac") ++ (F) ++ ("cdcdaabcdabab") ++ (F) ++ ("ccd") ++ (F) ++ ("acabcdbb") ++ (F) ++ ("acbbcccc") ++ (F) ++ ("b") ++ (F) ++ ("dbaa") ++ (F) ++ ("dbcbbcb") ++ (F) ++ ("caaaa"))
    =
    ((F) ++ ("cbcccdbcdac") ++ (F) ++ (F) ++ ("bdacaccdbaaccacab") ++ (F) ++ ("bdbdbadcacdcdcdaabcdabab") ++ (F) ++ ("ccddacabcdbbdacbbccccdb") ++ (F) ++ (F) ++ ("baa") ++ (F) ++ (F) ++ ("bcbbcbdcaaaa"));
constraint
  (("cdaabcbdbdcaabbbacccdbcaabbaaabd") ++ (F) ++ ("adcacbbbbcccbadcbdadc") ++ (F) ++ ("abc") ++ (F) ++ ("cbbbbbbbcbbc") ++ (F) ++ (F) ++ ("abbadbccbad") ++ (F) ++ ("b") ++ (F) ++ (F) ++ ("dccaaadd") ++ (F) ++ (F) ++ ("b"))
    =
    (("cdaabcb") ++ (F) ++ ("bdcaabbbaccc") ++ (F) ++ ("bcaabbaaabd") ++ (F) ++ ("a") ++ (F) ++ ("cacbbbbcccbadcb") ++ (F) ++ ("a") ++ (F) ++ ("cdabc") ++ (F) ++ ("cbbbbbbbcbbc") ++ (F) ++ ("dabbadbccbad") ++ (F) ++ ("bd") ++ (F) ++ ("dccaaa") ++ (F) ++ ("dd") ++ (F) ++ ("b"));
constraint
  ((F) ++ ("cbdb") ++ (F) ++ (F) ++ ("cca") ++ (F) ++ ("cbbabbcabc") ++ (F) ++ (F) ++ ("ccabcb") ++ (F) ++ ("cb") ++ (F) ++ ("dbbcab") ++ (F) ++ ("dacddbbacdbbacdaccadacbacc") ++ (F) ++ ("bdcabb") ++ (F) ++ ("accaddbbbbbbbbadbadc") ++ (F) ++ ("bcaa"))
    =
    (("dcb") ++ (F) ++ ("b") ++ (F) ++ ("dcca") ++ (F) ++ ("cbbabbcabc") ++ (F) ++ (F) ++ ("ccabcb") ++ (F) ++ ("cbddbbcab") ++ (F) ++ ("dac") ++ (F) ++ (F) ++ ("bbac") ++ (F) ++ ("bbac") ++ (F) ++ ("accadacbacc") ++ (F) ++ ("b") ++ (F) ++ ("cabbdaccaddbbbbbbbbadbadc") ++ (F) ++ ("bcaa"));
constraint
  ((F) ++ ("a") ++ (F) ++ ("cad") ++ (F) ++ ("d") ++ (F) ++ ("cccbddbcda") ++ (F) ++ ("ac") ++ (F) ++ ("ccccabaca") ++ (F) ++ ("cbab") ++ (F) ++ (F) ++ (F) ++ ("bcabccbdcbccb") ++ (F) ++ ("abcb") ++ (F) ++ ("cccbaaa") ++ (F) ++ ("ddcacbbbaadadbac") ++ (F) ++ (F) ++ ("bbaadbcadb") ++ (F) ++ ("cdb"))
    =
    (("dadcad") ++ (F) ++ (F) ++ (F) ++ ("cccbddbcda") ++ (F) ++ ("acdccccabacadcbabdddbcabccb") ++ (F) ++ ("cbccbdabcbdcccbaaa") ++ (F) ++ ("ddcacbbbaa") ++ (F) ++ ("adbac") ++ (F) ++ ("dbbaa") ++ (F) ++ ("bca") ++ (F) ++ ("bdcdb"));
constraint
  (("ab") ++ (F) ++ ("aacbbcabaaab") ++ (F) ++ ("bc") ++ (F) ++ (F) ++ ("c") ++ (F) ++ ("bbabcc") ++ (F) ++ (F) ++ ("dadbb") ++ (F) ++ ("c") ++ (F) ++ (F) ++ (F) ++ ("a") ++ (F) ++ ("ac") ++ (F) ++ ("aacd") ++ (F) ++ ("bba") ++ (F) ++ ("cca") ++ (F) ++ ("cbacccabdabccadabdaacbdaacbbadddccccaab") ++ (F) ++ (F))
    =
    (("abdaacbbcabaaabdbc") ++ (F) ++ ("dcdbbabccd") ++ (F) ++ ("dadbb") ++ (F) ++ ("c") ++ (F) ++ ("d") ++ (F) ++ ("a") ++ (F) ++ ("acdaacd") ++ (F) ++ ("bba") ++ (F) ++ ("ccadcbacccabdabcca") ++ (F) ++ ("abdaacbdaacbbadd") ++ (F) ++ ("ccccaab") ++ (F) ++ ("d"));
constraint
  ((F) ++ ("cdbc") ++ (F) ++ ("ccc") ++ (F) ++ ("b") ++ (F) ++ ("cbcdab") ++ (F) ++ ("bdac") ++ (F) ++ ("aaa") ++ (F) ++ ("c") ++ (F) ++ ("cabbbbbacabcb") ++ (F) ++ ("bcabacb") ++ (F) ++ ("dcaacacbbbbac") ++ (F) ++ ("bcc") ++ (F) ++ ("adbbadcd") ++ (F) ++ (F) ++ ("c") ++ (F) ++ ("b") ++ (F) ++ ("acd") ++ (F) ++ ("ba") ++ (F) ++ ("abacc") ++ (F) ++ ("c") ++ (F))
    =
    ((F) ++ ("cdbc") ++ (F) ++ ("cccdb") ++ (F) ++ ("cbc") ++ (F) ++ ("abdbdac") ++ (F) ++ ("aaadcdcabbbbbacabcb") ++ (F) ++ ("bcabacbd") ++ (F) ++ ("caacacbbbbac") ++ (F) ++ ("bcc") ++ (F) ++ ("adbbadc") ++ (F) ++ ("d") ++ (F) ++ ("cdbdacddbadabaccdcd"));
constraint
  (("aaabcabcc") ++ (F) ++ ("bdccc") ++ (F) ++ ("bbadaaccada") ++ (F) ++ ("acaaacb") ++ (F) ++ ("c") ++ (F) ++ (F) ++ ("b") ++ (F) ++ ("dcaca") ++ (F) ++ (F) ++ ("cacbabcbaada") ++ (F) ++ (F) ++ ("aabac") ++ (F) ++ ("abbcbdbbdcdcdccabba") ++ (F) ++ ("caacacdaab") ++ (F))
    =
    (("aaabcabcc") ++ (F) ++ ("b") ++ (F) ++ ("cccdbba") ++ (F) ++ ("aaccadadacaaacb") ++ (F) ++ ("cd") ++ (F) ++ ("bd") ++ (F) ++ ("caca") ++ (F) ++ (F) ++ ("cacbabcbaadad") ++ (F) ++ ("aabacdabbcbdbb") ++ (F) ++ ("cdc") ++ (F) ++ ("ccabbadcaacacdaab") ++ (F));
constraint
  ((F) ++ ("c") ++ (F) ++ ("abbacaacca") ++ (F) ++ ("dcdaaa") ++ (F) ++ ("c") ++ (F) ++ ("bbada") ++ (F) ++ ("baba") ++ (F) ++ ("a") ++ (F) ++ (F) ++ ("accbbcddbba") ++ (F) ++ ("abdcd") ++ (F) ++ ("abccbcaacab") ++ (F) ++ ("badaddaca") ++ (F) ++ ("adcdbcbadcdcadcca") ++ (F) ++ (F) ++ ("cb") ++ (F))
    =
    ((F) ++ ("c") ++ (F) ++ ("abbacaaccad") ++ (F) ++ ("cdaaadc") ++ (F) ++ ("bbadadbaba") ++ (F) ++ ("a") ++ (F) ++ ("daccbbc") ++ (F) ++ (F) ++ ("bba") ++ (F) ++ ("ab") ++ (F) ++ ("cd") ++ (F) ++ ("abccbcaacab") ++ (F) ++ ("bada") ++ (F) ++ (F) ++ ("aca") ++ (F) ++ ("a") ++ (F) ++ ("c") ++ (F) ++ ("bcbadc") ++ (F) ++ ("ca") ++ (F) ++ ("ccad") ++ (F) ++ ("cb") ++ (F));
constraint
  ((F) ++ ("adbcbcbca") ++ (F) ++ ("bbabbaabaaacaadbbdabcacb") ++ (F) ++ ("ac") ++ (F) ++ ("cbbcbda") ++ (F) ++ ("ccbbcb") ++ (F) ++ ("dbdddbcdbccbdbbcaacccaabbdccacbbbcacabccccbda"))
    =
    ((F) ++ ("a") ++ (F) ++ ("bcbcbca") ++ (F) ++ ("bbabbaabaaacaa") ++ (F) ++ ("bbdabcacb") ++ (F) ++ ("acdcbbcb") ++ (F) ++ ("a") ++ (F) ++ ("ccbbcbd") ++ (F) ++ ("bdddbc") ++ (F) ++ ("bccbdbbcaacccaabbdccacbbbcacabccccbda"));
constraint
  ((F) ++ (F) ++ ("b") ++ (F) ++ ("bcbbbab") ++ (F) ++ ("abbbcaada") ++ (F) ++ ("bbdadbacbaabaddc") ++ (F) ++ ("abbdbaddbbcaabcd") ++ (F) ++ ("bbbcccacddad") ++ (F) ++ ("dcccba") ++ (F) ++ ("cacbdaadcbaca") ++ (F) ++ ("bbdacabdd"))
    =
    (("ddb") ++ (F) ++ ("bcbbbab") ++ (F) ++ ("abbbcaa") ++ (F) ++ ("a") ++ (F) ++ ("bb") ++ (F) ++ ("adbacbaaba") ++ (F) ++ (F) ++ ("c") ++ (F) ++ ("abbdba") ++ (F) ++ (F) ++ ("bbcaabcddbbbcccacd") ++ (F) ++ ("ad") ++ (F) ++ (F) ++ ("cccba") ++ (F) ++ ("cacbdaadcbaca") ++ (F) ++ ("bbdacabdd"));
constraint
  (("ccbbacc") ++ (F) ++ ("ad") ++ (F) ++ ("d") ++ (F) ++ ("bbccca") ++ (F) ++ (F) ++ ("caadbbcca") ++ (F) ++ ("cabbacdaadcaccca") ++ (F) ++ ("adbbcdd") ++ (F) ++ ("dabca") ++ (F) ++ ("dcacca") ++ (F) ++ (F) ++ ("adabdbddacaaadca") ++ (F) ++ ("b") ++ (F) ++ (F) ++ ("cabcb") ++ (F) ++ ("cdc"))
    =
    (("ccbbaccda") ++ (F) ++ ("d") ++ (F) ++ (F) ++ ("bbcccaddcaa") ++ (F) ++ ("bbccadcabbac") ++ (F) ++ ("aa") ++ (F) ++ ("caccca") ++ (F) ++ ("a") ++ (F) ++ ("bbc") ++ (F) ++ (F) ++ ("d") ++ (F) ++ ("abca") ++ (F) ++ ("dcaccadda") ++ (F) ++ ("abdbddacaaa") ++ (F) ++ ("cadb") ++ (F) ++ ("dcabcb") ++ (F) ++ ("cdc"));
constraint
  (("ccccbcaa") ++ (F) ++ ("ccaab") ++ (F) ++ ("aca") ++ (F) ++ ("bab") ++ (F) ++ ("ccbbcaccabcbbca") ++ (F) ++ ("ccadbacbdcccac") ++ (F) ++ ("cc") ++ (F) ++ ("a") ++ (F) ++ ("babcbabbdacacbbadbb") ++ (F) ++ ("dacabc") ++ (F) ++ ("ab") ++ (F) ++ ("dcca") ++ (F) ++ ("c") ++ (F) ++ (F) ++ ("bc"))
    =
    (("ccccbcaa") ++ (F) ++ ("ccaabdacadbab") ++ (F) ++ ("ccbbcaccabcbbca") ++ (F) ++ ("cca") ++ (F) ++ ("bacbdcccacdcc") ++ (F) ++ ("adbabcbabb") ++ (F) ++ ("acacbbadbb") ++ (F) ++ ("dacabcdab") ++ (F) ++ (F) ++ ("ccadcd") ++ (F) ++ ("bc"));
constraint
  (("bdc") ++ (F) ++ ("cccbaaa") ++ (F) ++ ("caabaadb") ++ (F) ++ ("cba") ++ (F) ++ (F) ++ ("adaabcd") ++ (F) ++ ("acc") ++ (F) ++ ("b") ++ (F) ++ ("ccbbdbcddabcbaadca") ++ (F) ++ ("abc") ++ (F) ++ ("ccbdba") ++ (F) ++ (F) ++ (F) ++ ("ab") ++ (F) ++ ("dacaacbcdd") ++ (F) ++ ("babccbccaacbd"))
    =
    (("bdcdcccbaaa") ++ (F) ++ ("caabaa") ++ (F) ++ ("b") ++ (F) ++ ("cba") ++ (F) ++ (F) ++ ("a") ++ (F) ++ ("aabcd") ++ (F) ++ ("accdbdccbb") ++ (F) ++ ("bcddabcbaa") ++ (F) ++ ("cadabc") ++ (F) ++ ("ccbdba") ++ (F) ++ ("d") ++ (F) ++ ("ab") ++ (F) ++ ("dacaacbc") ++ (F) ++ ("ddbabccbccaacb") ++ (F));
constraint
  (("aaa") ++ (F) ++ (F) ++ ("a") ++ (F) ++ ("bd") ++ (F) ++ ("daccc") ++ (F) ++ ("adbabacabccabdbbb") ++ (F) ++ ("dadacdbcdacabbaaabacbcabc") ++ (F) ++ ("b") ++ (F) ++ ("adcbca") ++ (F) ++ ("dcd") ++ (F) ++ ("caacc") ++ (F) ++ ("bcbbc") ++ (F) ++ (F) ++ ("bcbacbc") ++ (F) ++ ("baabb"))
    =
    (("aaa") ++ (F) ++ ("da") ++ (F) ++ ("b") ++ (F) ++ (F) ++ ("dacccda") ++ (F) ++ ("babacabccabdbbbd") ++ (F) ++ ("adac") ++ (F) ++ ("bcdacabbaaabacbcabc") ++ (F) ++ ("b") ++ (F) ++ ("a") ++ (F) ++ ("cbcad") ++ (F) ++ ("cddcaacc") ++ (F) ++ ("bcbbcddbcbacbc") ++ (F) ++ ("baabb"));
constraint
  (("dbaaacacacabaca") ++ (F) ++ ("c") ++ (F) ++ ("bcbdabbc") ++ (F) ++ ("aa") ++ (F) ++ ("abcdcbbd") ++ (F) ++ ("bccccc") ++ (F) ++ ("ca") ++ (F) ++ ("aacb") ++ (F) ++ ("dcb") ++ (F) ++ ("bbabbcdabdc") ++ (F) ++ ("bb") ++ (F) ++ ("ccabbacabcd") ++ (F) ++ ("ab") ++ (F) ++ ("bbaaadbcdca"))
    =
    (("dbaaacacacabaca") ++ (F) ++ ("cdbcb") ++ (F) ++ ("abbc") ++ (F) ++ ("aa") ++ (F) ++ ("abc") ++ (F) ++ ("cbb") ++ (F) ++ (F) ++ ("bcccccdcadaacbd") ++ (F) ++ ("cbdbbabbc") ++ (F) ++ ("abdc") ++ (F) ++ ("bbdccabbacabcd") ++ (F) ++ ("ab") ++ (F) ++ ("bbaaa") ++ (F) ++ ("bc") ++ (F) ++ ("ca"));
constraint
  (("cbabaaabbdaaacbadc") ++ (F) ++ ("bcddb") ++ (F) ++ ("cda") ++ (F) ++ (F) ++ ("cc") ++ (F) ++ ("caaacdbbbccaa") ++ (F) ++ (F) ++ ("dccabbbaa") ++ (F) ++ ("babacc") ++ (F) ++ ("ccaddbbad") ++ (F) ++ ("abc") ++ (F) ++ ("cdd") ++ (F) ++ ("baa") ++ (F) ++ (F) ++ ("a") ++ (F) ++ ("adcb") ++ (F) ++ ("aacc"))
    =
    (("cbabaaabbdaaacbadcdbcd") ++ (F) ++ ("bdcda") ++ (F) ++ (F) ++ ("ccdcaaac") ++ (F) ++ ("bbbccaad") ++ (F) ++ ("dccabbbaa") ++ (F) ++ ("babaccdccaddbba") ++ (F) ++ (F) ++ ("abcdcdd") ++ (F) ++ ("baa") ++ (F) ++ (F) ++ ("ada") ++ (F) ++ ("cbdaacc"));
constraint
  (("ddbcac") ++ (F) ++ ("adbacc") ++ (F) ++ ("abbba") ++ (F) ++ ("cccad") ++ (F) ++ ("dcb") ++ (F) ++ ("bdacabbbcabccbbc") ++ (F) ++ ("bacbbccbabbccbdcabbcccdccba") ++ (F) ++ ("cbcc") ++ (F) ++ ("a") ++ (F) ++ ("cb") ++ (F) ++ ("bcbadbbaadaacb"))
    =
    ((F) ++ ("dbcac") ++ (F) ++ ("a") ++ (F) ++ ("baccdabbba") ++ (F) ++ ("cccad") ++ (F) ++ ("dcb") ++ (F) ++ ("bdacabbbcabccbbc") ++ (F) ++ ("bacbbccbabbccbdcabbccc") ++ (F) ++ ("ccba") ++ (F) ++ ("cbccdadcb") ++ (F) ++ ("bcbadbbaadaacb"));
constraint
  ((F) ++ ("aacabaadcaabbcbbacbcbadadaccaacbadcabbcbacbba") ++ (F) ++ ("a") ++ (F) ++ ("bd") ++ (F) ++ ("bacbad") ++ (F) ++ ("aacda") ++ (F) ++ ("cacd") ++ (F) ++ ("acabcaadbabab") ++ (F) ++ ("aabbdacbbb") ++ (F) ++ ("cbba"))
    =
    (("daacabaa") ++ (F) ++ ("caabbcbbacbcba") ++ (F) ++ ("adaccaacba") ++ (F) ++ ("cabbcbacbbada") ++ (F) ++ ("bddbacba") ++ (F) ++ (F) ++ ("aacda") ++ (F) ++ ("cac") ++ (F) ++ (F) ++ ("acabcaa") ++ (F) ++ ("bababdaabbdacbbb") ++ (F) ++ ("cbba"));
constraint
  (("d") ++ (F) ++ ("adadabb") ++ (F) ++ ("ccabacbdbccaaabcadbbdb") ++ (F) ++ ("dbddcbacaaacaabbdabbad") ++ (F) ++ ("ccaabc") ++ (F) ++ ("ac") ++ (F) ++ ("d") ++ (F) ++ ("cb") ++ (F) ++ ("abd") ++ (F) ++ ("cbabbaccb") ++ (F) ++ ("bbcbacbbbccbdc"))
    =
    ((F) ++ (F) ++ ("a") ++ (F) ++ ("adabb") ++ (F) ++ ("ccabacb") ++ (F) ++ ("bccaaabca") ++ (F) ++ ("bbdbd") ++ (F) ++ ("bd") ++ (F) ++ ("cbacaaacaabb") ++ (F) ++ ("abba") ++ (F) ++ ("dccaabcdac") ++ (F) ++ (F) ++ (F) ++ ("cb") ++ (F) ++ ("ab") ++ (F) ++ ("dcbabbaccb") ++ (F) ++ ("bbcbacbbbccb") ++ (F) ++ ("c"));
constraint
  (("c") ++ (F) ++ ("ccadca") ++ (F) ++ ("d") ++ (F) ++ ("acc") ++ (F) ++ (F) ++ ("bbbbcbdc") ++ (F) ++ ("cbdbc") ++ (F) ++ ("caacb") ++ (F) ++ ("aba") ++ (F) ++ (F) ++ ("bbac") ++ (F) ++ ("baaadacbbaacaaa") ++ (F) ++ ("cb") ++ (F) ++ ("dcaaaba") ++ (F) ++ ("bcca") ++ (F) ++ ("accaacaba") ++ (F) ++ ("a") ++ (F) ++ ("b") ++ (F) ++ ("dbdabb"))
    =
    (("cdccadca") ++ (F) ++ (F) ++ ("dacc") ++ (F) ++ (F) ++ ("bbbbcbdc") ++ (F) ++ ("cb") ++ (F) ++ ("bcdcaacb") ++ (F) ++ ("aba") ++ (F) ++ ("dbbac") ++ (F) ++ ("baaa") ++ (F) ++ ("acbbaacaaadcbddcaaabadbcca") ++ (F) ++ ("accaacabada") ++ (F) ++ ("b") ++ (F) ++ (F) ++ ("bdabb"));
constraint
  (("cada") ++ (F) ++ ("aabdb") ++ (F) ++ ("bba") ++ (F) ++ ("bdcdcdbbaccacaabbbacabdc") ++ (F) ++ ("cdcadca") ++ (F) ++ ("ccabc") ++ (F) ++ ("ccbadacaddbbbabbcbbcbabb") ++ (F) ++ ("bd") ++ (F) ++ (F) ++ ("cacddaaabcbb") ++ (F) ++ ("bcb"))
    =
    (("ca") ++ (F) ++ ("a") ++ (F) ++ ("aab") ++ (F) ++ ("b") ++ (F) ++ ("bbadb") ++ (F) ++ ("c") ++ (F) ++ ("c") ++ (F) ++ ("bbaccacaabbbacabdc") ++ (F) ++ ("cdca") ++ (F) ++ ("cadccabc") ++ (F) ++ ("ccba") ++ (F) ++ ("acad") ++ (F) ++ ("bbbabbcbbcbabbdb") ++ (F) ++ ("d") ++ (F) ++ ("cacddaaabcbbdbcb"));
constraint
  (("bbdddbcba") ++ (F) ++ ("bacccadac") ++ (F) ++ (F) ++ ("abdc") ++ (F) ++ ("bccbcabcddbad") ++ (F) ++ ("bcbb") ++ (F) ++ ("caccbd") ++ (F) ++ ("cdaaa") ++ (F) ++ (F) ++ ("bccdd") ++ (F) ++ ("bcabcacbbddbadcdbcaadc") ++ (F) ++ (F) ++ ("bdbdcddbcc"))
    =
    (("bb") ++ (F) ++ (F) ++ (F) ++ ("bcbadbacccadacddab") ++ (F) ++ ("cdbccbcabc") ++ (F) ++ ("dbaddbcbb") ++ (F) ++ ("caccbd") ++ (F) ++ ("c") ++ (F) ++ ("aaa") ++ (F) ++ ("dbcc") ++ (F) ++ (F) ++ ("dbcabcacbb") ++ (F) ++ ("dbadcdbcaadcd") ++ (F) ++ ("b") ++ (F) ++ ("bdcddbcc"));
constraint
  (("cbaabcadcbcacccbc") ++ (F) ++ ("badbddbccda") ++ (F) ++ ("abcbbb") ++ (F) ++ ("bcbbbc") ++ (F) ++ ("caaacbccd") ++ (F) ++ ("abbbc") ++ (F) ++ (F) ++ ("c") ++ (F) ++ ("aadd") ++ (F) ++ ("daa") ++ (F) ++ ("d") ++ (F) ++ ("cd") ++ (F) ++ ("acaccaabddcacbbcaaccac"))
    =
    (("cbaabcadcbcacccbcdbadbddbcc") ++ (F) ++ ("adabcbbbdbcbbbc") ++ (F) ++ ("caaacbccd") ++ (F) ++ ("abbbcd") ++ (F) ++ ("cdaa") ++ (F) ++ ("dddaa") ++ (F) ++ (F) ++ (F) ++ ("cd") ++ (F) ++ ("acaccaab") ++ (F) ++ ("dcacbbcaaccac"));
constraint
  (("bbb") ++ (F) ++ ("bcddacbcacbb") ++ (F) ++ (F) ++ (F) ++ ("baddc") ++ (F) ++ ("acbddc") ++ (F) ++ ("caddaabcd") ++ (F) ++ ("cc") ++ (F) ++ ("babc") ++ (F) ++ ("aabbaacabbbdabaa") ++ (F) ++ ("ccbabbbdcdba") ++ (F) ++ ("bb") ++ (F) ++ ("aabb") ++ (F) ++ ("a") ++ (F) ++ ("ccddbd") ++ (F) ++ ("bb"))
    =
    (("bbbdbcddacbcacbb") ++ (F) ++ ("d") ++ (F) ++ ("ba") ++ (F) ++ (F) ++ ("cdacb") ++ (F) ++ (F) ++ ("c") ++ (F) ++ ("ca") ++ (F) ++ (F) ++ ("aabc") ++ (F) ++ ("dcc") ++ (F) ++ ("babcdaabbaacabbb") ++ (F) ++ ("abaa") ++ (F) ++ ("ccbabbb") ++ (F) ++ ("cdbadbb") ++ (F) ++ ("aabbdadcc") ++ (F) ++ ("db") ++ (F) ++ (F) ++ ("bb"));
constraint
  (("c") ++ (F) ++ ("cabdabcabcbcbbbabccaaabcacaadacacabdbc") ++ (F) ++ ("cdcbadbddabcbabadbccdcccc") ++ (F) ++ ("abba") ++ (F) ++ ("ad") ++ (F) ++ ("dcaadcccaa") ++ (F) ++ ("aacd") ++ (F) ++ ("adaa") ++ (F) ++ ("cbd"))
    =
    (("c") ++ (F) ++ ("cab") ++ (F) ++ ("abcabcbcbbbabccaaabcacaadacacabdbc") ++ (F) ++ ("c") ++ (F) ++ ("cbadbd") ++ (F) ++ ("abcbabadbcc") ++ (F) ++ ("ccccdabbada") ++ (F) ++ (F) ++ (F) ++ ("caa") ++ (F) ++ ("cccaa") ++ (F) ++ ("aac") ++ (F) ++ (F) ++ ("a") ++ (F) ++ ("aa") ++ (F) ++ ("cb") ++ (F));
constraint
  (("bac") ++ (F) ++ ("adbacaddabcacccaac") ++ (F) ++ ("cddbaaa") ++ (F) ++ ("bacbdb") ++ (F) ++ ("bcbccbbbacd") ++ (F) ++ ("a") ++ (F) ++ ("dbcaaabbaddbacbb") ++ (F) ++ ("bbdcbbbcca") ++ (F) ++ ("c") ++ (F) ++ ("acccaca") ++ (F) ++ ("dccb") ++ (F) ++ ("cbbc"))
    =
    (("bac") ++ (F) ++ ("adbaca") ++ (F) ++ (F) ++ ("abcacccaacdc") ++ (F) ++ (F) ++ ("baaadbacbdbdbcbccbbbac") ++ (F) ++ (F) ++ ("a") ++ (F) ++ ("dbcaaabbad") ++ (F) ++ ("bacbb") ++ (F) ++ ("bb") ++ (F) ++ ("cbbbcca") ++ (F) ++ ("c") ++ (F) ++ ("acccaca") ++ (F) ++ ("dccbdcbbc"));
constraint
  ((F) ++ ("bbcbccdccbbc") ++ (F) ++ ("bbcccbadccb") ++ (F) ++ ("cc") ++ (F) ++ ("cdbbbbacdaac") ++ (F) ++ ("bbaabcacbdba") ++ (F) ++ (F) ++ ("ba") ++ (F) ++ ("bbabcadbb") ++ (F) ++ ("bcbcbcabdbadacbacacbcbdcaac") ++ (F) ++ ("ba"))
    =
    (("dbbcbcc") ++ (F) ++ ("ccbbc") ++ (F) ++ ("bbcccbadccb") ++ (F) ++ ("ccdc") ++ (F) ++ ("bbbbacdaacdbbaabcacbdba") ++ (F) ++ ("dbadbbabcadbb") ++ (F) ++ ("bcbcbcab") ++ (F) ++ ("badacbacacbcbdcaacdba"));
constraint
  (("ca") ++ (F) ++ ("acdccc") ++ (F) ++ ("ccc") ++ (F) ++ ("dcdabaadab") ++ (F) ++ ("bdadcacbdaca") ++ (F) ++ ("aba") ++ (F) ++ ("ccc") ++ (F) ++ ("bbdcdaabaccb") ++ (F) ++ (F) ++ ("ca") ++ (F) ++ ("bacabacabbcacddbdacadbcbdadacbacbdaa"))
    =
    (("ca") ++ (F) ++ ("ac") ++ (F) ++ ("ccc") ++ (F) ++ ("ccc") ++ (F) ++ ("dcdabaadab") ++ (F) ++ ("bdadcacb") ++ (F) ++ ("aca") ++ (F) ++ ("aba") ++ (F) ++ ("cccdbb") ++ (F) ++ ("cdaabaccb") ++ (F) ++ (F) ++ ("cadbacabacabbcac") ++ (F) ++ ("db") ++ (F) ++ ("aca") ++ (F) ++ ("bcb") ++ (F) ++ ("adacbacb") ++ (F) ++ ("aa"));
constraint
  (("ccacdaabadccbaacbaadcabc") ++ (F) ++ ("bdabadb") ++ (F) ++ ("b") ++ (F) ++ ("bb") ++ (F) ++ ("abbcbcbacabacddabbb") ++ (F) ++ ("abd") ++ (F) ++ ("bcdcb") ++ (F) ++ ("b") ++ (F) ++ ("bcccccaadacbccbcaadcbcc") ++ (F) ++ ("aaabc"))
    =
    (("ccac") ++ (F) ++ ("aaba") ++ (F) ++ ("ccbaacbaa") ++ (F) ++ ("cabc") ++ (F) ++ ("b") ++ (F) ++ ("abadbdbdbbdabbcbcbacabacddabbbdabddbc") ++ (F) ++ ("cbdb") ++ (F) ++ ("bcccccaadacbccbcaadcbccdaaabc"));
constraint
  (("bcdcac") ++ (F) ++ ("bcb") ++ (F) ++ ("acaadbcbbb") ++ (F) ++ ("cbc") ++ (F) ++ ("cbaddcacda") ++ (F) ++ ("dd") ++ (F) ++ ("bba") ++ (F) ++ ("ccac") ++ (F) ++ ("cdabdcdccbba") ++ (F) ++ ("cacbcbbdddbaabcaabbaa") ++ (F) ++ ("ccdb") ++ (F) ++ ("dabcdb") ++ (F) ++ ("dab"))
    =
    (("bcdcac") ++ (F) ++ ("bcb") ++ (F) ++ ("acaadbcbbb") ++ (F) ++ ("cbcdcba") ++ (F) ++ (F) ++ ("cacdad") ++ (F) ++ ("d") ++ (F) ++ ("bba") ++ (F) ++ ("ccacdcdab") ++ (F) ++ ("cdccbba") ++ (F) ++ ("cacbcbbdd") ++ (F) ++ ("baabcaabbaadcc") ++ (F) ++ ("bd") ++ (F) ++ ("abc") ++ (F) ++ ("b") ++ (F) ++ ("dab"));
constraint
  (("bcaaba") ++ (F) ++ ("b") ++ (F) ++ ("bbcbacdcc") ++ (F) ++ ("bcadadabbacbc") ++ (F) ++ ("dddbaaccdaccddbcbbacbcccdacccb") ++ (F) ++ ("ccd") ++ (F) ++ ("caab") ++ (F) ++ ("cbc") ++ (F) ++ ("a") ++ (F) ++ ("bbaabac") ++ (F) ++ ("ccbabbbabdcd"))
    =
    (("bcaaba") ++ (F) ++ ("bdbbcbac") ++ (F) ++ ("ccdbca") ++ (F) ++ ("adabbacbcd") ++ (F) ++ (F) ++ ("dbaaccdacc") ++ (F) ++ ("dbcbbacbcccdacccbdccd") ++ (F) ++ ("caab") ++ (F) ++ ("cbc") ++ (F) ++ ("adbbaabac") ++ (F) ++ ("ccbabbbab") ++ (F) ++ ("c") ++ (F));
constraint
  (("dddadbcbaacacbbbbbaccacaabdba") ++ (F) ++ ("ddbbb") ++ (F) ++ ("bdcbadabddcbbdbba") ++ (F) ++ ("cbcbacabbabbbbbbbaccdc") ++ (F) ++ ("aaaca") ++ (F) ++ ("acabccbb") ++ (F) ++ ("ba") ++ (F) ++ ("cadc"))
    =
    (("dddadbcbaacacbbbbbaccacaab") ++ (F) ++ ("ba") ++ (F) ++ ("ddbbb") ++ (F) ++ ("bdcbadabddcbbdbba") ++ (F) ++ ("cbcbacabbabbbbbbbacc") ++ (F) ++ ("c") ++ (F) ++ ("aaacadacabccbbdbadcadc"));
constraint
  (("cdbbbabbbaa") ++ (F) ++ ("cacccacdbcabcacccbccaab") ++ (F) ++ ("bbbdbaabacbaccdabccaccbacc") ++ (F) ++ ("cb") ++ (F) ++ (F) ++ ("acbcc") ++ (F) ++ (F) ++ (F) ++ ("abbdacbbcadcacbbbcccb") ++ (F) ++ (F) ++ ("c"))
    =
    (("c") ++ (F) ++ ("bbbabbbaa") ++ (F) ++ ("cacccacdbcabcacccbccaab") ++ (F) ++ ("bbb") ++ (F) ++ ("baabacbacc") ++ (F) ++ ("abccaccbaccdcbd") ++ (F) ++ ("acbccdd") ++ (F) ++ ("abbdacbbca") ++ (F) ++ ("cacbbbcccbd") ++ (F) ++ ("c"));
constraint
  (("ca") ++ (F) ++ ("acdbba") ++ (F) ++ ("bbbcbcac") ++ (F) ++ ("dabbbbbcccdadd") ++ (F) ++ (F) ++ ("aacbcabb") ++ (F) ++ ("acacc") ++ (F) ++ ("d") ++ (F) ++ (F) ++ ("ca") ++ (F) ++ ("baaba") ++ (F) ++ ("aabcbcaaabaa") ++ (F) ++ ("bcbc") ++ (F) ++ (F) ++ ("ab") ++ (F) ++ ("baadaac") ++ (F) ++ ("db") ++ (F) ++ ("acbd"))
    =
    (("cadacdbbadbbbcbcac") ++ (F) ++ ("dabbbbbcccda") ++ (F) ++ (F) ++ (F) ++ (F) ++ ("aacbcabbdacacc") ++ (F) ++ (F) ++ (F) ++ (F) ++ ("ca") ++ (F) ++ ("baaba") ++ (F) ++ ("aabcbcaaabaa") ++ (F) ++ ("bcbcd") ++ (F) ++ ("abdbaadaacd") ++ (F) ++ ("b") ++ (F) ++ ("acb") ++ (F));
constraint
  (("bbdccbddabacb") ++ (F) ++ ("dcadbda") ++ (F) ++ ("d") ++ (F) ++ ("c") ++ (F) ++ ("ccbbbbaba") ++ (F) ++ ("d") ++ (F) ++ (F) ++ ("bbabb") ++ (F) ++ ("dcbabacadabbccca") ++ (F) ++ ("abbcabbcdaadb") ++ (F) ++ ("dbbcd") ++ (F) ++ ("baa") ++ (F) ++ ("bcbabbdaadcba"))
    =
    (("bbdccb") ++ (F) ++ ("dabacb") ++ (F) ++ ("dcadb") ++ (F) ++ ("adddcdccbbbbabad") ++ (F) ++ ("ddbbabbddcbabacadabbccca") ++ (F) ++ ("abbcabbcdaa") ++ (F) ++ ("b") ++ (F) ++ ("dbbc") ++ (F) ++ ("dbaa") ++ (F) ++ ("bcbabbdaa") ++ (F) ++ ("cba"));
constraint
  (("ab") ++ (F) ++ ("b") ++ (F) ++ ("a") ++ (F) ++ ("ac") ++ (F) ++ ("abaacdc") ++ (F) ++ ("cbcbcdb") ++ (F) ++ ("ab") ++ (F) ++ (F) ++ ("cdacbbccbcbd") ++ (F) ++ ("cbd") ++ (F) ++ ("dcd") ++ (F) ++ ("aab") ++ (F) ++ (F) ++ ("ccbaabca") ++ (F) ++ ("caacabbbcca") ++ (F) ++ ("dacaad") ++ (F) ++ (F) ++ ("c") ++ (F) ++ ("dcaab") ++ (F) ++ ("daadad"))
    =
    (("abdbdadacdabaac") ++ (F) ++ ("c") ++ (F) ++ ("cbcbcdbdabd") ++ (F) ++ ("c") ++ (F) ++ ("acbbccbcb") ++ (F) ++ ("dcbdddcd") ++ (F) ++ ("aab") ++ (F) ++ (F) ++ ("ccbaabca") ++ (F) ++ ("caacabbbccaddacaa") ++ (F) ++ (F) ++ (F) ++ ("cd") ++ (F) ++ ("caabd") ++ (F) ++ ("aada") ++ (F));
constraint
  ((F) ++ ("bbda") ++ (F) ++ ("ccbbbcacbaaaacbcbbbab") ++ (F) ++ (F) ++ (F) ++ (F) ++ ("bdddbacba") ++ (F) ++ ("adccbad") ++ (F) ++ ("ab") ++ (F) ++ ("bcadbcccaaaabadcc") ++ (F) ++ ("adcdb") ++ (F) ++ ("bbac") ++ (F) ++ (F) ++ ("aaaaacbcc") ++ (F) ++ ("baaa") ++ (F) ++ ("bb"))
    =
    (("dbb") ++ (F) ++ ("adccbbbcacbaaaacbcbbbab") ++ (F) ++ ("dddb") ++ (F) ++ (F) ++ (F) ++ ("bacba") ++ (F) ++ ("adccba") ++ (F) ++ ("dabdbcadbcccaaaabadccda") ++ (F) ++ ("cdbdbbacd") ++ (F) ++ ("aaaaacbcc") ++ (F) ++ ("baaadbb"));
constraint
  (("baacbb") ++ (F) ++ ("ddadcacbdccbbd") ++ (F) ++ ("bcaadacad") ++ (F) ++ ("cbcc") ++ (F) ++ (F) ++ ("c") ++ (F) ++ ("abdb") ++ (F) ++ ("bdac") ++ (F) ++ ("babbabacbabcab") ++ (F) ++ ("dbca") ++ (F) ++ ("c") ++ (F) ++ ("a") ++ (F) ++ ("dabcdbbaacdacaa") ++ (F) ++ ("cc") ++ (F) ++ ("cacbcd"))
    =
    (("baacbb") ++ (F) ++ (F) ++ (F) ++ ("a") ++ (F) ++ ("cacbdccbbd") ++ (F) ++ ("bcaa") ++ (F) ++ ("acad") ++ (F) ++ ("cbcc") ++ (F) ++ ("dcdabdb") ++ (F) ++ ("bdacdbabbabacbabcabd") ++ (F) ++ ("bcadc") ++ (F) ++ ("addabcdbbaacdacaadcc") ++ (F) ++ ("cacbc") ++ (F));
constraint
  (("ccccbbbbbab") ++ (F) ++ ("cbc") ++ (F) ++ (F) ++ ("abbba") ++ (F) ++ (F) ++ ("abaccddcdbbcaaadc") ++ (F) ++ ("bb") ++ (F) ++ (F) ++ ("ab") ++ (F) ++ ("a") ++ (F) ++ ("cb") ++ (F) ++ ("acbb") ++ (F) ++ ("cabcbbbdccabaabbbcccbabaaccdbcac") ++ (F) ++ ("a") ++ (F) ++ ("acb") ++ (F) ++ ("a"))
    =
    (("ccccbbbbbabdcbc") ++ (F) ++ ("dabbba") ++ (F) ++ (F) ++ ("abacc") ++ (F) ++ (F) ++ ("cdbbcaaadc") ++ (F) ++ ("bbd") ++ (F) ++ ("ab") ++ (F) ++ ("a") ++ (F) ++ ("cb") ++ (F) ++ ("acbbdcabcbbbdccabaabbbcccbabaaccdbcacdadacb") ++ (F) ++ ("a"));
constraint
  (("bca") ++ (F) ++ ("abaabdddcdbcb") ++ (F) ++ ("c") ++ (F) ++ ("aaa") ++ (F) ++ ("cccbbd") ++ (F) ++ ("bbcccabaa") ++ (F) ++ ("dcb") ++ (F) ++ ("bcabbabbbadcbc") ++ (F) ++ ("adcbaaa") ++ (F) ++ ("aadaccdbbac") ++ (F) ++ ("cccccba") ++ (F) ++ ("aadbbdabc") ++ (F) ++ (F))
    =
    (("bcadabaab") ++ (F) ++ (F) ++ ("dc") ++ (F) ++ ("bcbdcdaaa") ++ (F) ++ ("cccbb") ++ (F) ++ (F) ++ ("bbcccabaaddcb") ++ (F) ++ ("bcabbabbbadcbcdadcbaaadaa") ++ (F) ++ ("accdbbacdcccccbadaadbb") ++ (F) ++ ("abc") ++ (F) ++ ("d"));
constraint
  (("ac") ++ (F) ++ ("aabdc") ++ (F) ++ ("caaddd") ++ (F) ++ ("b") ++ (F) ++ ("bbbbbd") ++ (F) ++ ("ddbacacbb") ++ (F) ++ ("bad") ++ (F) ++ ("daa") ++ (F) ++ (F) ++ (F) ++ ("bbcab") ++ (F) ++ ("d") ++ (F) ++ (F) ++ ("cccaacbcbacdadaacccb") ++ (F) ++ ("d") ++ (F) ++ ("aabcabbc") ++ (F) ++ ("aabcac") ++ (F) ++ ("ba") ++ (F) ++ (F) ++ ("c") ++ (F))
    =
    (("acdaab") ++ (F) ++ ("c") ++ (F) ++ ("caa") ++ (F) ++ (F) ++ ("d") ++ (F) ++ ("b") ++ (F) ++ ("bbbbbddd") ++ (F) ++ ("bacacbb") ++ (F) ++ ("bad") ++ (F) ++ ("daa") ++ (F) ++ (F) ++ ("dbbcabdd") ++ (F) ++ ("dcccaacbcbac") ++ (F) ++ ("a") ++ (F) ++ ("aacccbdddaabcabbc") ++ (F) ++ ("aabcacdbad") ++ (F) ++ ("cd"));
constraint
  (("bcb") ++ (F) ++ ("b") ++ (F) ++ (F) ++ ("b") ++ (F) ++ ("bbadaaabcaaa") ++ (F) ++ ("dd") ++ (F) ++ ("c") ++ (F) ++ ("c") ++ (F) ++ ("cadbabccbabdcca") ++ (F) ++ ("bd") ++ (F) ++ ("a") ++ (F) ++ ("acaaabd") ++ (F) ++ ("bcca") ++ (F) ++ ("aaaa") ++ (F) ++ ("a") ++ (F) ++ ("bdbaabc") ++ (F) ++ ("ca") ++ (F) ++ ("c") ++ (F) ++ ("dccbb") ++ (F) ++ ("ad") ++ (F) ++ ("bcaaa") ++ (F) ++ ("a"))
    =
    (("bcbdbddbdbba") ++ (F) ++ ("aaabcaaaddddc") ++ (F) ++ ("cdcadbabccbab") ++ (F) ++ ("ccadb") ++ (F) ++ (F) ++ ("a") ++ (F) ++ ("acaaabddbccadaaaa") ++ (F) ++ ("a") ++ (F) ++ ("b") ++ (F) ++ ("baabcdcadc") ++ (F) ++ (F) ++ ("ccbb") ++ (F) ++ ("addbcaaa") ++ (F) ++ ("a"));
constraint
  ((F) ++ ("badcccdbbcbcddbdcccbc") ++ (F) ++ ("ddcdaccbdd") ++ (F) ++ ("cd") ++ (F) ++ ("bbcbdcbabbccdbbaacabacacbbbbcdcbacabcabcabd") ++ (F) ++ ("bdaccbbbcbab") ++ (F) ++ ("bcbac"))
    =
    ((F) ++ ("ba") ++ (F) ++ ("ccc") ++ (F) ++ ("bbcbc") ++ (F) ++ ("db") ++ (F) ++ ("cccbcdddcdaccb") ++ (F) ++ ("ddc") ++ (F) ++ ("dbbcb") ++ (F) ++ ("cbabbcc") ++ (F) ++ ("bbaacabacacbbbbcdcbacabcabcab") ++ (F) ++ (F) ++ ("bdaccbbbcbab") ++ (F) ++ ("bcbac"));
constraint
  (("bcdc") ++ (F) ++ ("cbbcbdbcaaaaccbbcbaaa") ++ (F) ++ ("cbbdbdbaacbcacccaaaacdacbc") ++ (F) ++ ("a") ++ (F) ++ ("cc") ++ (F) ++ ("aabdc") ++ (F) ++ ("ccbbaaabdbdbcdbbcdc") ++ (F) ++ (F) ++ ("cc") ++ (F) ++ ("abbbddbccc"))
    =
    (("bcdc") ++ (F) ++ ("cbbcbdbcaaaaccbbcbaaa") ++ (F) ++ ("cbbdbdbaacbcacccaaaacdacbcda") ++ (F) ++ ("cc") ++ (F) ++ ("aabdcdccbbaaab") ++ (F) ++ ("bdbc") ++ (F) ++ ("bbc") ++ (F) ++ ("c") ++ (F) ++ (F) ++ ("cc") ++ (F) ++ ("abbb") ++ (F) ++ (F) ++ ("bccc"));
solve satisfy;
