var string: A;
constraint
  ((A) ++ (A) ++ ("aaaaa")) =
    ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ (A) ++ ("aaaaa"));
constraint
  ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ (A) ++ ("aaaaa")) =
    ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa"));
constraint
  ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa")) =
    ((A) ++ (A) ++ ("aaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa")) =
    ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ (A) ++ ("aaaaa")) =
    ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint ((A) ++ (A) ++ ("aaaaa")) = ((A) ++ (A) ++ ("aaaaa"));
constraint
  ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa"));
constraint
  ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa"));
constraint
  ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa")) =
    ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ (A) ++ ("aaaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa")) =
    ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ (A) ++ ("aaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ (A) ++ ("aaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa"));
constraint
  ((A) ++ (A) ++ ("aaaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint ((A) ++ (A) ++ ("aaaaa")) = ((A) ++ (A) ++ ("aaaaa"));
constraint
  ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ (A) ++ ("aaaaa"));
constraint
  ((A) ++ (A) ++ ("aaaaa")) =
    ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa")) =
    ((A) ++ (A) ++ ("aaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa")) =
    ((A) ++ (A) ++ ("aaaaa"));
constraint
  ((A) ++ (A) ++ ("aaaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa"));
constraint ((A) ++ (A) ++ ("aaaaa")) = ((A) ++ (A) ++ ("aaaaa"));
constraint
  ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ (A) ++ ("aaaaa"));
constraint ((A) ++ (A) ++ ("aaaaa")) = ((A) ++ (A) ++ ("aaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ (A) ++ ("aaaaa"));
constraint
  ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa")) =
    ((A) ++ (A) ++ ("aaaaa"));
constraint
  ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa")) =
    ((A) ++ (A) ++ ("aaaaa"));
constraint
  ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa")) =
    ((A) ++ (A) ++ ("aaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa")) =
    ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ (A) ++ ("aaaaa"));
constraint
  ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa"));
constraint
  ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ (A) ++ ("aaaaa"));
constraint
  ((A) ++ (A) ++ ("aaaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ (A) ++ ("aaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa")) =
    ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ (A) ++ ("aaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa"));
constraint
  ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ ("")) =
    ((A) ++ (A) ++ ("aaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ (A) ++ ("aaaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ (A) ++ ("aaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa")) =
    ((A) ++ (A) ++ ("aaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""))
    = ((A) ++ (A) ++ ("aaaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa"));
constraint
  ((A) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (A) ++ ("aaaaa"));
constraint
  ((A) ++ (A) ++ ("aaaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
solve satisfy;
