var string: B;
var string: C;
var string: A;
constraint
  (("baaabaababb") ++ (C) ++ ("abbaabaaabbaaaaaaaa")) =
    (("baaabaababbbbabbabbbbabbabaaabaabbaabaaabbaaaaaaaa") ++ (""));
constraint
  (("aaabaabaaaaaaaabbaaaaaabbabbbbabaaabbabbabbbabaaba") ++ ("")) =
    (("aaab") ++ (B) ++ ("abbbabaaba"));
constraint
  (("baaaaaabbabbbbababaaaabbaabaaabaaabbbbabaaabbabaab") ++ ("")) =
    ((A) ++ ("bbabbbbababaaaabbaabaaabaaabbbbabaaabbabaab") ++ (""));
constraint
  (("bbbbbbaaaaabbbbbbbaaabaababbbaaabaaaaaaabaabbabbba") ++ ("")) =
    (("bbbbbbaaaaabbbbbbbaaabaababbbaaa") ++ (A) ++ ("abaabbabbba"));
constraint
  (("abbabbabbbabbbabaaaaaabbbbabbbaaabaaaaabaaaabbabbb") ++ ("")) =
    (("abbabbabbbabbba") ++ (A) ++ ("bbbbabbbaaabaaaaabaaaabbabbb"));
constraint
  (("bababbbaaabaaaabbaabbbbabbbbbba") ++ (A) ++ ("aabbbbbabaaa")) =
    (("bababbbaaabaaaabbaabbbbabbbbbbabaaaaaaaabbbbbabaaa") ++ (""));
constraint
  (("aaabaaab") ++ (A) ++ ("babaabaabaaaaaabaabaaabaababaaaaaba")) =
    (("aaabaaab") ++ (A) ++ ("babaabaa") ++ (A) ++ ("baabaaabaababaaaaaba"));
constraint
  (("abbabbbaaaabaabbaaaaaaababaaaabaabbbbabaabbbbabbaa") ++ ("")) =
    (("abbabbbaaaabaab") ++ (A) ++ ("ababaaaabaabbbbabaabbbbabbaa"));
constraint
  (("aaaaabaaaaaaababbbbbabbaabbaaaaaaaaabbabbbbbabbaaa") ++ ("")) =
    (("aaaaa") ++ (A) ++ ("ababbbbbabbaabbaaaaaaaaabbabbbbbabbaaa"));
constraint
  (("abaaa") ++ (A) ++ ("baaabababaabaabaab") ++ (A) ++ ("aabbababbaaba")) =
    (("abaaabaaaaaabaaabababaabaabaab") ++ (A) ++ ("aabbababbaaba"));
constraint
  (("abaabbaaaaabaaababbbabbaabaabaabbaba") ++ (A) ++ ("aaaaabb")) =
    (("abaabbaaaaabaaababbbabbaabaabaabbaba") ++ (A) ++ ("aaaaabb"));
constraint
  (("baabbaaaaaaabbbbabbbbbabaabaaababbbabaabbbbbbababb") ++ ("")) =
    (("baab") ++ (A) ++ ("abbbbabbbbbabaabaaababbbabaabbbbbbababb"));
constraint
  (("baaaabbbabaaaaabaababbbabbababaa") ++ (A) ++ ("bababbbbabb")) =
    (("baaaabbbabaaaaabaababbbabbababaabaaaaaabababbbbabb") ++ (""));
constraint
  (("bbaabababa") ++ (A) ++ ("babbabbabaababbabaaababaabbbabbaa")) =
    (("bbaababababaaaaaababbabbabaababbabaaababaabbbabbaa") ++ (""));
constraint
  (("baaba") ++ (A) ++ ("abbbbbabaaabbbbaaabbbaabaaaaaaabbbbaba")) =
    (("baaba") ++ (A) ++ ("abbbbbabaaabbbbaaabbbaabaaaaaaabbbbaba"));
constraint
  (("abbabbaaabbbabaabbaaaaaabababbbbabbaabaaaabaabaaba") ++ ("")) =
    (("abbabbaaabbbabaab") ++ (A) ++ ("bababbbbabbaabaaaabaabaaba"));
constraint
  (("bbaababbbaabbbbaaaba") ++ (A) ++ ("bbaaabaaabbbabbbbaababa")) =
    (("bbaababbbaabbbbaaababaaaaaabbaaabaaabbbabbbbaababa") ++ (""));
constraint
  (("babbbaaababababbbbabbbabbbbabab") ++ (A) ++ ("aabaababbaba")) =
    (("babbbaaababababbbbabbbabbbbababbaaaaaaaabaababbaba") ++ (""));
constraint
  (("aaaabaaaaaaaabbabaaaaaaababaabbaabbbabbbabbaaabaaa") ++ ("")) =
    (("aaaa") ++ (A) ++ ("aabba") ++ (A) ++ ("ababaabbaabbbabbbabbaaabaaa"));
constraint
  (("baabbabbbbbaabaa") ++ (A) ++ ("aaaaaaaababbaaaabaabbabbbbb")) =
    (("baabbabbbbbaabaa") ++ (A) ++ ("aaaaaaaababbaaaabaabbabbbbb"));
constraint
  (("baabaabbbbabbaababbaaaaaaaabbabbbaaabbbaababbbabab") ++ ("")) =
    (("baabaabbbbabbaabab") ++ (A) ++ ("aabbabbbaaabbbaababbbabab"));
constraint
  (("aaaaaabbabbbbbabbbbbbbaba") ++ (A) ++ ("abaabbbbbbabbaabaa")) =
    (("aaaaaabbabbbbbabbbbbbbababaaaaaaabaabbbbbbabbaabaa") ++ (""));
constraint
  (("bbbbaabaababb") ++ (A) ++ ("baabbbbababaaaababaababaababba")) =
    (("bbbbaabaababb") ++ (A) ++ ("baabbbbababaaaababaababaababba"));
constraint
  (("ababaabbbbabababaababaaaaabaababaabbbbabaaaaaaabba") ++ ("")) =
    (("ababaabbbbabababaababaaaaabaababaabbbba") ++ (A) ++ ("abba"));
constraint
  (("baaabaaabaaabaaaaaabaabbbbbbbbababaabbabbabaaabbbb") ++ ("")) =
    (("baaabaaabaaa") ++ (A) ++ ("baabbbbbbbbababaabbabbabaaabbbb"));
constraint
  (("bbbbbaaabbababbaabbabbbbaba") ++ (A) ++ ("bbbaaabbaabbabbb")) =
    (("bbbbbaaabbababbaabbabbbbaba") ++ (A) ++ ("bbbaaabbaabbabbb"));
constraint
  (("bbaababababababababaaaababbaabaa") ++ (A) ++ ("aaaabbbaaab")) =
    (("bbaababababababababaaaababbaabaa") ++ (A) ++ ("aaaabbbaaab"));
constraint
  (("babaababa") ++ (A) ++ ("bbabbaaaababbbabaaaabaabaabaaabaaa")) =
    (("babaababa") ++ (A) ++ ("bbabbaaaababbbabaaaabaabaabaaabaaa"));
constraint
  (("abbbab") ++ (A) ++ ("bbabababbabaabaabbaabbbabbababaabaaba")) =
    (("abbbabbaaaaaabbabababbabaabaabbaabbbabbababaabaaba") ++ (""));
constraint
  (("babbbbaabbbabbaabbbaabbbabbabab") ++ (A) ++ ("bbaabbbababb")) =
    (("babbbbaabbbabbaabbbaabbbabbababbaaaaaabbaabbbababb") ++ (""));
constraint
  ((A) ++ ("aaaabbaabbbaaaabaaaaababaaaababbaaababbabab") ++ ("")) =
    ((A) ++ ("aaaabbaabbbaaaabaaaaababaaaababbaaababbabab") ++ (""));
constraint
  (("baaabbbbbbabababaaabb") ++ (A) ++ ("aabbbbabbaaabaaaababab")) =
    (("baaabbbbbbabababaaabbbaaaaaaaabbbbabbaaabaaaababab") ++ (""));
constraint
  (("babababbaaaaaabaaababaabaababbaaaababaabbbbabbaaba") ++ ("")) =
    (("bababab") ++ (A) ++ ("baaababaabaababbaaaababaabbbbabbaaba"));
constraint
  (("bbbbbbaaabbababbabaaaaaaababbbabbaabbaababaabaaaaa") ++ ("")) =
    (("bbbbbbaaabbababba") ++ (A) ++ ("ababbbabbaabbaababaabaaaaa"));
constraint
  (("bb") ++ (A) ++ ("aaaababaabaaaaabbaaaabbbaabaabaabbabbabba")) =
    (("bb") ++ (A) ++ ("aaaababaabaaaaabbaaaabbbaabaabaabbabbabba"));
constraint
  (("aabaabbbaaaaabaabbababaababbaaababbbabbbbab") ++ (A)) =
    (("aabaabbbaaaaabaabbababaababbaaababbbabbbbab") ++ (A));
constraint
  ((A) ++ ("a") ++ (A) ++ ("aabaabbabababbbbbabbbbbabbaabababab")) =
    (("baaaaaaabaaaaaaaabaabbabababbbbbabbbbbabbaabababab") ++ (""));
constraint
  (("abbaaabbbbbbaabbababaaabbbaaaababba") ++ (A) ++ ("baaabbab")) =
    (("abbaaabbbbbbaabbababaaabbbaaaababbabaaaaaabaaabbab") ++ (""));
constraint
  (("aabaababaaabbaabbbbba") ++ (A) ++ ("bbbabababaabbbaaababbb")) =
    (("aabaababaaabbaabbbbbabaaaaaabbbabababaabbbaaababbb") ++ (""));
constraint
  (("bbaabbaaabbbbabbbbbbaaaabaaaaaabbaaabbbbbbabbbbbba") ++ ("")) =
    (("bbaabbaaabbbbabbbbbbaaaa") ++ (A) ++ ("bbaaabbbbbbabbbbbba"));
constraint
  (("bbbabaabbbaababaabaaabbabbabbaaaababaaaababbaaaaaa") ++ ("")) =
    (("bbbabaabbbaababaabaaabbabbabbaaaababaaaabab") ++ (A));
constraint
  (("bbabbaabbaababaabbbbaababbabbaaaaabbaaaaaabbbababa") ++ ("")) =
    (("bbabbaabbaababaabbbbaababbabbaaaaab") ++ (A) ++ ("bbbababa"));
constraint
  (("aabbbababbbbbbbbababaababaaa") ++ (A) ++ ("abbabbbbbabbaab")) =
    (("aabbbababbbbbbbbababaababaaabaaaaaaabbabbbbbabbaab") ++ (""));
constraint
  (("abbababbbbabaabbbabbbabbbbababbabbbabababbb") ++ (A)) =
    (("abbababbbbabaabbbabbbabbbbababbabbbabababbb") ++ (A));
constraint
  (("bbbabababbababbbaaaabbbbaabbaabbaaabb") ++ (A) ++ ("abbaba")) =
    (("bbbabababbababbbaaaabbbbaabbaabbaaabb") ++ (A) ++ ("abbaba"));
constraint
  (("bbbbbabbaab") ++ (A) ++ ("bbbbbbbabaaabbbab") ++ (A) ++ ("bbaabbbb")) =
    (("bbbbbabbaab") ++ (A) ++ ("bbbbbbbabaaabbbabbaaaaaabbaabbbb"));
constraint
  (("ababaabbbbbaaababbbbbbbaaaa") ++ (A) ++ ("bababaababbaaaba")) =
    (("ababaabbbbbaaababbbbbbbaaaa") ++ (A) ++ ("bababaababbaaaba"));
constraint
  (("aaba") ++ (A) ++ ("bbababaababaabbabababaabaaabbabbbbaabba")) =
    (("aababaaaaaabbababaababaabbabababaabaaabbabbbbaabba") ++ (""));
constraint
  (("abbbabbabaabbabbabaaaabbaabbbbaabaaaaaaaabaabaaaab") ++ ("")) =
    (("abbbabbabaabbabbabaaaabbaabbbbaa") ++ (A) ++ ("aabaabaaaab"));
constraint
  (("aaaabbbbaaabbaaaaaabbaabaaabbaababbabbbbababbabbbb") ++ ("")) =
    (("aaaabbbbaaab") ++ (A) ++ ("bbaabaaabbaababbabbbbababbabbbb"));
constraint
  (("bbaaab") ++ (A) ++ ("abbabbaabaabbbbabaabbaabaa") ++ (A) ++ ("abbb")) =
    (("bbaaabbaaaaaaabbabbaabaabbbbabaabbaabaabaaaaaaabbb") ++ (""));
constraint
  (("baaaabbbbbbbaaabbbaa") ++ (A) ++ ("baaabaaaaaaabbbbaababab")) =
    (("baaaabbbbbbbaaabbbaabaaaaaabaaabaaaaaaabbbbaababab") ++ (""));
constraint
  (("bbaabbaabbaaaaabbabbbbabbbbaabbb") ++ (A) ++ ("bbbabbabbbb")) =
    (("bbaabbaabbaaaaabbabbbbabbbbaabbbbaaaaaabbbabbabbbb") ++ (""));
constraint
  (("aaababaaaab") ++ (A) ++ ("babbbaaabbbabaaaabaababababbbbba")) =
    (("aaababaaaabbaaaaaababbbaaabbbabaaaabaababababbbbba") ++ (""));
constraint
  (("abaaaabaabbaaaaaaaabbaaaaababababbbabbaaabbaaaabbb") ++ ("")) =
    (("abaaaabaab") ++ (A) ++ ("aabbaaaaababababbbabbaaabbaaaabbb"));
constraint
  (("bbbababba") ++ (A) ++ ("bbbaababbbbabaaaabbbabbbbaaaaabbaa")) =
    (("bbbababba") ++ (A) ++ ("bbbaababbbbabaaaabbbabbbbaaaaabbaa"));
constraint
  (("abbbbbaaaababbaaabbbaababbbaaaaaaababbabbabbbbbbbb") ++ ("")) =
    (("abbbbbaaaababbaaabbbaababb") ++ (A) ++ ("ababbabbabbbbbbbb"));
constraint
  (("babaaabaab") ++ (A) ++ ("abaabaabababbabaaabaaaabaabbbaaba")) =
    (("babaaabaab") ++ (A) ++ ("abaabaabababbabaaabaaaabaabbbaaba"));
constraint
  (("aabbbbabbbaabbbabbbaaaabbbabbbaaaaaabbabbaaaabaaab") ++ ("")) =
    (("aabbbbabbbaabbbabbbaaaabbbabb") ++ (A) ++ ("bbabbaaaabaaab"));
constraint
  (("abaaabba") ++ (A) ++ ("baabbaabaababbabbabbbbabaaabbbaaaab")) =
    (("abaaabba") ++ (A) ++ ("baabbaabaababbabbabbbbabaaabbbaaaab"));
constraint
  (("a") ++ (A) ++ ("abbabaaaaabaabababababaabaaabbbaabababbabb")) =
    (("abaaaaaaabbabaaaaabaabababababaabaaabbbaabababbabb") ++ (""));
constraint
  (("bbbaabaaaabbbaababbbbaabbababbaaabaaabbaaabaaaaaab") ++ ("")) =
    (("bbbaabaaaabbbaababbbbaabbababbaaabaaabbaaa") ++ (A) ++ ("b"));
constraint
  (("ababbabbbbaabbbaabbabbabaabaaaaaabbaaababbabbababa") ++ ("")) =
    (("ababbabbbbaabbbaabbabbabaa") ++ (A) ++ ("bbaaababbabbababa"));
constraint
  (("abbbbabbbbbbaaaaaaabaaaabbbaabbaaaaaabaabaaaabaaba") ++ ("")) =
    (("abbbbabbbbbbaaaaaaabaaaabbbaab") ++ (A) ++ ("baabaaaabaaba"));
constraint
  (("abbabbbaabbbaabaabaabaaaaaaaabaabaababaaababbbaaba") ++ ("")) =
    (("abbabbbaabbbaabaabaa") ++ (A) ++ ("aabaabaababaaababbbaaba"));
constraint
  (("bbbaaaabbbabaaabbbabbbaaaaaaabaabaaaabababbaaabaaa") ++ ("")) =
    (("bbbaaaabbbabaaabbbabb") ++ (A) ++ ("abaabaaaabababbaaabaaa"));
constraint
  (("abbbbaababaaabaaaaaaa") ++ (A) ++ ("bbbbbbbababbbaababbbba")) =
    (("abbbbaababaaa") ++ (A) ++ ("a") ++ (A) ++ ("bbbbbbbababbbaababbbba"));
constraint
  (("bbaabbaabaaababbbbababbaaaa") ++ (A) ++ ("abbbbbbaababbbba")) =
    (("bbaabbaabaaababbbbababbaaaabaaaaaaabbbbbbaababbbba") ++ (""));
constraint
  (("abbbaabbaabbbabaabbababbbbbaa") ++ (A) ++ ("aaabbaabaababb")) =
    (("abbbaabbaabbbabaabbababbbbbaa") ++ (A) ++ ("aaabbaabaababb"));
constraint
  (("aaaaaaabbbaaabbbabaababbbbaaabababbaaaaaababbaabaa") ++ ("")) =
    (("aaaaaaabbbaaabbbabaababbbbaaababab") ++ (A) ++ ("babbaabaa"));
constraint
  (("aabab") ++ (A) ++ ("babaabbabbbaaaababaabbabbaaaabbabbbaba")) =
    (("aababbaaaaaababaabbabbbaaaababaabbabbaaaabbabbbaba") ++ (""));
constraint
  (("baabaabbababbaaaabb") ++ (A) ++ ("bbabbaaabbbabbabbabaaaab")) =
    (("baabaabbababbaaaabbbaaaaaabbabbaaabbbabbabbabaaaab") ++ (""));
constraint
  (("baaabbbbaa") ++ (A) ++ ("babbabbabaabbbabaabbbbbbabaabbbab")) =
    (("baaabbbbaa") ++ (A) ++ ("babbabbabaabbbabaabbbbbbabaabbbab"));
constraint
  (("abbbbbaaaaaabaabaaabbbbbbbaabbbbbaaabbbaa") ++ (A) ++ ("aa")) =
    (("abbbbbaaaaaabaabaaabbbbbbbaabbbbbaaabbbaa") ++ (A) ++ ("aa"));
constraint
  (("abbbaaba") ++ (A) ++ ("aabaaabbaabbaaababbababbababbababbb")) =
    (("abbbaababaaaaaaaabaaabbaabbaaababbababbababbababbb") ++ (""));
constraint
  (("bbbbbbaaabaabaabbbaa") ++ (A) ++ ("bababbababaaaabaabbaaab")) =
    (("bbbbbbaaabaabaabbbaabaaaaaabababbababaaaabaabbaaab") ++ (""));
constraint
  (("aaaaaabaaababbaaaaabbabaaabaababbababababaaaaaaaba") ++ ("")) =
    (("aaaaaabaaababbaaaaabbabaaabaababbabababa") ++ (A) ++ ("aba"));
constraint
  (("bbabbabbabbbbbaaaabbbbbbbaaabbaaaa") ++ (A) ++ ("abaaabbaa")) =
    (("bbabbabbabbbbbaaaabbbbbbbaaabbaaaa") ++ (A) ++ ("abaaabbaa"));
constraint
  (("abbabbbabbabababbbbabaaababa") ++ (A) ++ ("bbabaabbbbabbaa")) =
    (("abbabbbabbabababbbbabaaababa") ++ (A) ++ ("bbabaabbbbabbaa"));
constraint
  (("aabbbbaaababbaaaaaaaaabbbbaabaaaabaabbaaaabaababaa") ++ ("")) =
    (("aabbbbaaabab") ++ (A) ++ ("aaabbbbaabaaaabaabbaaaabaababaa"));
constraint
  (("bbaabbaaabbababbbaabaababab") ++ (A) ++ ("aababbbaaaabbbbb")) =
    (("bbaabbaaabbababbbaabaabababbaaaaaaaababbbaaaabbbbb") ++ (""));
constraint
  (("aaababbaaa") ++ (A) ++ ("aabbaabbbaabbabaabbbaabaababaabab")) =
    (("aaababbaaabaaaaaaaabbaabbbaabbabaabbbaabaababaabab") ++ (""));
constraint
  (("abababbbaa") ++ (A) ++ ("aaaaabbbaaabbbabababa") ++ (A) ++ ("aaabb")) =
    (("abababbbaabaaaaaaaaaaabbbaaabbbababababaaaaaaaaabb") ++ (""));
constraint
  (("bbbabbabb") ++ (A) ++ ("abbbaabaaaababaaaabaabbaaabbabbbaa")) =
    (("bbbabbabb") ++ (A) ++ ("abbbaabaaaababaaaabaabbaaabbabbbaa"));
constraint
  (("baaabbbababbbabbaaabaaabaabbaaabaaaaaaaaaabbaabbaa") ++ ("")) =
    (("baaabbbababbbabbaaabaaabaabbaaa") ++ (A) ++ ("aaaabbaabbaa"));
constraint
  (("bbabbabaaabba") ++ (A) ++ ("baaabbbbbbbbaababbbbabaabbaaba")) =
    (("bbabbabaaabbabaaaaaabaaabbbbbbbbaababbbbabaabbaaba") ++ (""));
constraint
  (("bbaabbbbbbaaabaabb") ++ (A) ++ ("baaaaababbbaabbbbaabaaaab")) =
    (("bbaabbbbbbaaabaabbbaaaaaabaaaaababbbaabbbbaabaaaab") ++ (""));
constraint
  (("babbaaaaaababbbabbabbabbbabbaababbbbbbabbaaaabbaab") ++ ("")) =
    (("bab") ++ (A) ++ ("babbbabbabbabbbabbaababbbbbbabbaaaabbaab"));
solve satisfy;
