var string: H;
var string: F;
var string: A;
var string: C;
constraint
  (("ce") ++ (H) ++ ("fbbedafbdbcab") ++ (A) ++ ("aebbabfcfbcd") ++ (A) ++ ("af"))
    = (("ce") ++ (F) ++ (A) ++ ("af"));
constraint
  (("accaeeedbdafbffcbfeadaeeebceddadeccbecaff") ++ ("")) =
    (("accaeeedb") ++ (C) ++ ("ffcbfeadaeeebceddadeccbecaff"));
constraint
  (("cecbdefbefbccfadcceccabeddbe") ++ (C) ++ ("fffeeaacc")) =
    (("cecbdefbefbccfadcceccabeddbe") ++ (C) ++ ("fffeeaacc"));
constraint
  (("acafbbedfbeaafbcaeeac") ++ (C) ++ ("dfedacffadabcede")) =
    (("acafbbedfbeaafbcaeeac") ++ (C) ++ ("dfedacffadabcede"));
constraint
  (("fadbefedffefdfddfffeddf") ++ (A) ++ ("dafdfdaaeeeaaa")) =
    (("fadbefedffefdfddfffeddf") ++ (A) ++ ("dafdfdaaeeeaaa"));
constraint
  (("edbfccdcddaaefcdbecfdbdcebeccddfccde") ++ (C) ++ ("d")) =
    (("edbfccdcddaaefcdbecfdbdcebeccddfccdedafbd") ++ (""));
constraint
  (("bfbebdcabecdebdccacaac") ++ (C) ++ ("eddbaecbbbeffed")) =
    (("bfbebdcabecdebdccacaacdafbeddbaecbbbeffed") ++ (""));
constraint
  (("fbafefaeabcdaeecbcfafccbedfacebaaeeafadcf") ++ ("")) =
    (("fba") ++ (H) ++ ("eabcdaeecbcfafccbedfacebaaeeafadcf"));
constraint
  (("bb") ++ (H) ++ ("cfdbfedbdebceaecfaeabfcefeabeeceebe")) =
    (("bb") ++ (H) ++ ("cfdbfedbdebceaecfaeabfcefeabeeceebe"));
constraint
  (("fafabfcfaacfdbaeedfecbbfebbaafcfefbcf") ++ (C)) =
    (("fafabfcfaacfdbaeedfecbbfebbaafcfefbcf") ++ (C));
constraint
  (("ebcdfdcfccbccebcdaffaccfaabfadabbb") ++ (C) ++ ("eda")) =
    (("ebcdfdcfccbccebcdaffaccfaabfadabbb") ++ (C) ++ ("eda"));
constraint
  (("fcddc") ++ (H) ++ ("fececcacbbdcabeedcecaaeeadbacbbe")) =
    (("fcddc") ++ (H) ++ ("fececcacbbdcabeedcecaaeeadbacbbe"));
constraint
  (("defddafeeacfacbcbabaeebfbcfaffadbfedeebef") ++ ("")) =
    (("defddafeeacfa") ++ (A) ++ ("abaeebfbcfaffadbfedeebef"));
constraint
  (("bcbaaecfccffe") ++ (A) ++ ("abcedfbefdfcecffcdedfcaa")) =
    (("bcbaaecfccffe") ++ (A) ++ ("abcedfbefdfcecffcdedfcaa"));
constraint
  (("acfecbcfabcddbaccfbddefcabcbc") ++ (H) ++ ("ecefbbec")) =
    (("acfecbcfabcddbaccfbddefcabcbcfefaecefbbec") ++ (""));
constraint
  (("dfefacafacdbccebfbcbcfcadfcfdeebcfbbceced") ++ ("")) =
    (("d") ++ (H) ++ ("cafacdbccebfbcbcfcadfcfdeebcfbbceced"));
constraint
  (("badaeeebeafbcddaccfbd") ++ (H) ++ ("faeeacbdeccfcbaa")) =
    (("badaeeebeafbcddaccfbd") ++ (H) ++ ("faeeacbdeccfcbaa"));
constraint
  (("bdf") ++ (C) ++ ("eceaaeffbebafadcdebcbcaebcbcfaddee")) =
    (("bdfdafbeceaaeffbebafadcdebcbcaebcbcfaddee") ++ (""));
constraint
  (("bdecdadbeccdcdabedebfaaacdfcaacfda") ++ (C) ++ ("dfa")) =
    (("bdecdadbeccdcdabedebfaaacdfcaacfdadafbdfa") ++ (""));
constraint
  (("edaeedfcbabbcdedcebacecaaffbbbbbbf") ++ (H) ++ ("fdc")) =
    (("edaeedfcbabbcdedcebacecaaffbbbbbbffefafdc") ++ (""));
constraint
  (("bbbfaabfbfddafbedbfacaacbeedecdadeabdfbee") ++ ("")) =
    (("bbbfaabfbfd") ++ (C) ++ ("edbfacaacbeedecdadeabdfbee"));
constraint
  (("eabdbaabbeadbecefedeceaeacebcdadfddf") ++ (A) ++ ("b")) =
    (("eabdbaabbeadbecefedeceaeacebcdadfddf") ++ (A) ++ ("b"));
constraint
  (("eeddfbaadccaadcccbc") ++ (A) ++ ("ffcffafcdacdbeeeed")) =
    (("eeddfbaadccaadcccbc") ++ (A) ++ ("ffcffafcdacdbeeeed"));
constraint
  (("dbfacbadaceefacdabefccbbeb") ++ (C) ++ ("eefaedaccee")) =
    (("dbfacbadaceefacdabefccbbeb") ++ (C) ++ ("eefaedaccee"));
constraint
  (("dcb") ++ (H) ++ ("acabdebdddfafbeaebbbedfcdbdaaacdaf")) =
    (("dcb") ++ (H) ++ ("acabdebdddfafbeaebbbedfcdbdaaacdaf"));
constraint
  (("dcfdeaceddafdceafbdcbfdadceebfbbbb") ++ (H) ++ ("bbd")) =
    (("dcfdeaceddafdceafbdcbfdadceebfbbbbfefabbd") ++ (""));
constraint
  (("cbcbeaeaecdeabccaafdaafacecdaeebafaedfdce") ++ ("")) =
    ((A) ++ ("eaeaecdeabccaafdaafacecdaeebafaedfdce") ++ (""));
constraint
  (("fffeacaadbcfecccbbbfccbbadaeffcfddafbbfca") ++ ("")) =
    (("fffeacaadbcfecccbbbfccbbadaeffcfd") ++ (C) ++ ("bfca"));
constraint
  (("dfedbddfabb") ++ (H) ++ ("eeebcdcbfbeacabffbeeabbfde")) =
    (("dfedbddfabb") ++ (H) ++ ("eeebcdcbfbeacabffbeeabbfde"));
constraint
  (("ccdbccf") ++ (A) ++ ("bddffbabdabecdcbdeafccabfdcfac")) =
    (("ccdbccf") ++ (A) ++ ("bddffbabdabecdcbdeafccabfdcfac"));
constraint
  (("ffbefefefacdabefefffeabdaacffaeefabeadbec") ++ ("")) =
    (("ffbefe") ++ (H) ++ ("cdabefefffeabdaacffaeefabeadbec"));
constraint
  (("ffffaecdafbbdaeecfdfacdcffdfbfcbdbebefdfb") ++ ("")) =
    (("ffffaec") ++ (C) ++ ("bdaeecfdfacdcffdfbfcbdbebefdfb"));
constraint
  (("adddeffcbeb") ++ (C) ++ ("ccbcafdaadfafddbbfbbfecadb")) =
    (("adddeffcbebdafbccbcafdaadfafddbbfbbfecadb") ++ (""));
constraint
  (("dcfbbaeeabdececaadafbeffdcfafbceedbbcaaaf") ++ ("")) =
    (("dcfbbaeeabdececaa") ++ (C) ++ ("effdcfafbceedbbcaaaf"));
constraint
  (("fdfcbfebaeeacebebfeceacbcdcf") ++ (A) ++ ("ececaefef")) =
    (("fdfcbfebaeeacebebfeceacbcdcfcbcbececaefef") ++ (""));
constraint
  (("fbdbdddeffafddfcecfb") ++ (C) ++ ("dedcdeeefaeadfffb")) =
    (("fbdbdddeffafddfcecfb") ++ (C) ++ ("dedcdeeefaeadfffb"));
constraint
  (("dfefbeee") ++ (C) ++ ("bcdaecabcaafafaddbfaaddebebef")) =
    (("dfefbeeedafbbcdaecabcaafafaddbfaaddebebef") ++ (""));
constraint
  (("cacfbeceddabaddebaaededcbdafaffdaddafbdba") ++ ("")) =
    (("cacfbeceddabaddebaaededcbdafaffdad") ++ (C) ++ ("dba"));
constraint
  (("adbcb") ++ (C) ++ ("ceabcbabbbdafffeadbfcacafdbacfcb")) =
    (("adbcb") ++ (C) ++ ("ceabcbabbbdafffeadbfcacafdbacfcb"));
constraint
  (("fdceaff") ++ (A) ++ ("beebbefadcfccbbceeacaccdcffdea")) =
    (("fdceaffcbcbbeebbefadcfccbbceeacaccdcffdea") ++ (""));
constraint
  (("fcbdfbfefeacefdcffeeeefbde") ++ (C) ++ ("aeaeacfaebb")) =
    (("fcbdfbfefeacefdcffeeeefbdedafbaeaeacfaebb") ++ (""));
constraint
  (("adfffdecdbfcedddbaaffdcbdbecefbfafeed") ++ (A)) =
    (("adfffdecdbfcedddbaaffdcbdbecefbfafeed") ++ (A));
constraint
  (("deefefdfffdcecccdefffefdbbafcdeadda") ++ (A) ++ ("ac")) =
    (("deefefdfffdcecccdefffefdbbafcdeadda") ++ (A) ++ ("ac"));
constraint
  (("affadebf") ++ (A) ++ ("daefeefbcbbbfbdfbdeaeaecdfaba")) =
    (("affadebf") ++ (A) ++ ("daefeefbcbbbfbdfbdeaeaecdfaba"));
constraint
  (("aecdbbdeecafbeadbcfaabfaedbdbcbeeaeacbcbd") ++ ("")) =
    (("aecdbbdeecafbeadbcfaabfaedbdbcbeeaea") ++ (A) ++ ("d"));
constraint
  (("cccbefdacbaeaedabbeafcbfdaaeafedfaacbcbec") ++ ("")) =
    (("cccbefdacbaeaedabbeafcbfdaaeafedfaa") ++ (A) ++ ("ec"));
constraint
  (("cbcbbfdecedeffbbefefbfdddbadabcddfbbabcea") ++ ("")) =
    ((A) ++ ("bfdecedeffbbefefbfdddbadabcddfbbabcea") ++ (""));
constraint
  (("cfecaffdbdbffefaeeacabdfdcbcfbdebaaeacacf") ++ ("")) =
    (("cfecaffdbdbf") ++ (H) ++ ("eeacabdfdcbcfbdebaaeacacf"));
constraint
  (("bccddcbfe") ++ (A) ++ ("effbffeaaffedbfabbbfedffceda")) =
    (("bccddcbfe") ++ (A) ++ ("effbffeaaffedbfabbbfedffceda"));
constraint
  (("fccfabfbcccaebefb") ++ (A) ++ ("cddeedebfeafcbdcbbfc")) =
    (("fccfabfbcccaebefbcbcbcddeedebfeafcbdcbbfc") ++ (""));
constraint
  (("dfcbfeceeafadfaceffbbbacaebdaafae") ++ (A) ++ ("fabb")) =
    (("dfcbfeceeafadfaceffbbbacaebdaafae") ++ (A) ++ ("fabb"));
constraint
  ((C) ++ ("debbbeadeafcfbaaeedbacaabacdaeccafacb") ++ ("")) =
    (("dafbdebbbeadeafcfbaaeedbacaabacdaeccafacb") ++ (""));
constraint
  (("bfbcfffdcbcffedafeaaeebaeebfaecedafbfccbc") ++ ("")) =
    (("bfbcfffdcbcffedafeaaeebaeebfaece") ++ (C) ++ ("fccbc"));
constraint
  (("edcbadab") ++ (C) ++ ("caeaffdabbdefdadadcfacefaafce")) =
    (("edcbadab") ++ (C) ++ ("caeaffdabbdefdadadcfacefaafce"));
constraint
  (("bbbcdcdaeabdbff") ++ (H) ++ ("acdfdaccccedbebffdfebf")) =
    (("bbbcdcdaeabdbff") ++ (H) ++ ("acdfdaccccedbebffdfebf"));
constraint
  (("dacbdddbcdcfcfebcfefaffeaddfedefdcaddbcac") ++ ("")) =
    (("dacbdddbcdcfcfebc") ++ (H) ++ ("ffeaddfedefdcaddbcac"));
constraint
  (("edddbbfedefafcafafceacfaaeecfcfdafbccbbdb") ++ ("")) =
    (("edddbbfedefafcafafceacfaaeecfcf") ++ (C) ++ ("ccbbdb"));
solve satisfy;
