var string: A;
constraint
  (("bbaaaaababababababbbabb") ++ (A) ++ ("aaabab")) =
    (("bbaaaaababababababbbabb") ++ (A) ++ ("aaabab"));
constraint
  (("bbababbbbbbbbbabbbbababbbaaaaaaaabbaaaaabbaaaabb") ++ ("")) =
    (("bb") ++ (A) ++ ("bbbababbbaaaaaaaabbaaaaabbaaaabb"));
constraint
  (("aabaabaaaa") ++ (A) ++ ("babbbababbaabbaabbaaaaba")) =
    (("aabaabaaaa") ++ (A) ++ ("babbbababbaabbaabbaaaaba"));
constraint
  (("abbbbbaaaaaabbababbbabbbbbaaaaabbbababbbaaabaaba") ++ ("")) =
    (("abbbbbaaaaaa") ++ (A) ++ ("baaabaaba"));
constraint
  (("aabaaabaababaabbbbaabaababaabbabbaaaaabbbaaabbba") ++ ("")) =
    (("a") ++ (A) ++ ("abaababaabbabbaaaaabbbaaabbba"));
constraint
  (("babbbbaababababbab") ++ (A) ++ ("aababbbbbbbabbbaabbaababa")) =
    (("babbbbaababababbab") ++ (A) ++ ("aababbbbbbbabbbaabbaababa"));
constraint
  (("aab") ++ (A) ++ ("abbbabbbaabababbbabbabababbb") ++ (A) ++ ("abbbaba"))
    = (("aababaababbbabbbaabababbbabbabababbb") ++ (A) ++ ("abbbaba"));
constraint
  (("aaabababaabbaaabbbbaaaabbaaaababaababba") ++ (A) ++ ("bbab")) =
    (("aaabababaabbaaabbbbaaaabbaaaab") ++ (A) ++ ("abbaabaabbbab"));
constraint
  (("baabbaaabbbaaaaabbbabbbabbaababaabababbbaaaabbba") ++ ("")) =
    (("baabbaaabbbaaaaabbbabbbabbaab") ++ (A) ++ ("ababbbaaaabbba"));
constraint
  (("baabbbaaabaaababaaabbbabab") ++ (A) ++ ("ababaaabbbbbaaaaa")) =
    (("baabbbaaabaaababaaabbbabababaabababaaabbbbbaaaaa") ++ (""));
constraint
  (("bbbaababbabbaabbbbabbbaaaaababaabbabbaabbbababaa") ++ ("")) =
    (("bbbaababbabbaabbbbabbbaaaaab") ++ (A) ++ ("babbaabbbababaa"));
constraint
  (("babbaaaaaabba") ++ (A) ++ ("aabbaaaabbbbaaabbaabbaaabbbbba")) =
    (("babbaaaaaabbaabaabaabbaaaabbbbaaabbaabbaaabbbbba") ++ (""));
constraint
  (("babbaabababbbabbbaabbbbbababaaaaaa") ++ (A) ++ ("ababaaabb")) =
    (("babbaabababbbabbbaabbbbbababaaaaaa") ++ (A) ++ ("ababaaabb"));
constraint
  (("bbaabbbaaaabbbaa") ++ (A) ++ ("bbbbabbababaaababbbbbbbabab")) =
    (("bbaabbbaaaabbbaaabaabbbbbabbababaaababbbbbbbabab") ++ (""));
constraint
  (("aaabbabbababbb") ++ (A) ++ (A) ++ ("aaabaabaaabbabab") ++ (A) ++ ("aaa"))
    =
    (("aaabbabbababbb") ++ (A) ++ ("abaabaa") ++ (A) ++ ("aaabbabababaabaaa"));
constraint
  (("bbbabbabababbaabaaaababbbbaaabbbba") ++ (A) ++ ("bbaaaabbb")) =
    (("bbbabbabababbaabaaaababbbbaaabbbbaabaabbbaaaabbb") ++ (""));
constraint
  (("baabbaabbabbbbaabbbbababaaab") ++ (A) ++ ("aabbbaabbbbabaa")) =
    (("baabbaabbabbbbaabbbbababaaababaabaabbbaabbbbabaa") ++ (""));
constraint
  (("baaababbbababbaabaababbbbaaabbabaaaababbbbababaa") ++ ("")) =
    (("baaababbbababba") ++ (A) ++ ("abbbbaaabbabaaaababbbbababaa"));
constraint
  (("babbaabaaaabaababbbaabbabaa") ++ (A) ++ ("abbbbb") ++ (A) ++ ("bbbbb"))
    = (("babbaabaaaabaababbbaabbabaaabaababbbbb") ++ (A) ++ ("bbbbb"));
constraint
  (("aababaabaaabbbaabbbbababbababbbabbbbbabaaababbaa") ++ ("")) =
    (("aab") ++ (A) ++ ("aaabbbaabbbbababbababbbabbbbbabaaababbaa"));
constraint
  (("babaaabbbaaaaabababaaaababbaaabbaaabb") ++ (A) ++ ("aabbbb")) =
    (("babaaabbbaaaaabababaaaababbaaabbaaabbabaabaabbbb") ++ (""));
constraint
  (("babaaaa") ++ (A) ++ ("ababbabbbbbabbbbbaabbaabbaaaaabbbbab")) =
    (("babaaaaabaabababbabbbbbabbbbbaabbaabbaaaaabbbbab") ++ (""));
constraint
  (("aabaaabbbbab") ++ (A) ++ ("a") ++ (A) ++ ("abaaabbbbbaaabaabaabbaaba"))
    =
    (("aabaaabbbbab") ++ (A) ++ ("aabaababaaabbbbbaa") ++ (A) ++ ("aabbaaba"));
constraint
  (("bbbaaaaabbababaabbaaabaaabaaa") ++ (A) ++ ("aaaaabbbababbb")) =
    (("bbbaaaaabbab") ++ (A) ++ ("baaabaaabaaaabaabaaaaabbbababbb"));
constraint
  (("aabbaabaabbbbabbbbbbaaabbaaaabbbbaabbbbabbbbbbab") ++ ("")) =
    (("aabba") ++ (A) ++ ("bbbabbbbbbaaabbaaaabbbbaabbbbabbbbbbab"));
constraint
  (("bbaabababbba") ++ (A) ++ ("baabbabbbabbbba") ++ (A) ++ ("bbbaaaabbba"))
    =
    (("bbaabababbba") ++ (A) ++ ("baabbabbbabbbba") ++ (A) ++ ("bbbaaaabbba"));
constraint
  (("baabaababaaabbbbbabbababbaabbbbabbbabaabaaabbaaa") ++ ("")) =
    (("ba") ++ (A) ++ ("abaaabbbbbabbababbaabbbbabbbabaabaaabbaaa"));
constraint
  (("baabbababbbaabbaaaabbbaabaababbaabbaababbaabbabb") ++ ("")) =
    (("baabbababbbaabbaaaabbba") ++ (A) ++ ("abbaabbaababbaabbabb"));
constraint
  (("abbbaaabaabbabbabbbbbaab") ++ (A) ++ ("bbabbaaaabbbabbbaba")) =
    (("abbbaa") ++ (A) ++ ("babbabbbbbaababaabbbabbaaaabbbabbbaba"));
constraint
  (("aabbaaaabbbbbabaaaabbbaababaababaabbabbabbbabaab") ++ ("")) =
    (("aabbaaaabbbbbabaaaabbbaababaab") ++ (A) ++ ("babbabbbabaab"));
constraint
  (("aaabbbbbbbbbbbaabbbbbaaaaab") ++ (A) ++ ("abbbaabbaabbabba")) =
    (("aaabbbbbbbbbbbaabbbbbaaaaababaababbbaabbaabbabba") ++ (""));
constraint
  (("baaabaaabbabaaaaaabbaaababbbbbbbaaabaa") ++ (A) ++ ("abbbb")) =
    (("baaabaaabbabaaaaaabbaaababbbbbbbaaabaa") ++ (A) ++ ("abbbb"));
constraint
  (("aaaaababbaaabbbbabaaabaaababbaabaaaaa") ++ (A) ++ ("babbab")) =
    (("aaaaababbaaabbbbabaaabaaababbaabaaaaaabaabbabbab") ++ (""));
constraint
  (("bbaaabbbaaaabaaaaabaabbbbbabbabbbbbabbb") ++ (A) ++ ("baba")) =
    (("bbaaabbbaaaabaaaaabaabbbbbabbabbbbbabbb") ++ (A) ++ ("baba"));
constraint
  (("bbbbaaaaabbbbbaaaaababaabab") ++ (A) ++ ("baabaaabaaabaaaa")) =
    (("bbbbaaaaabbbbbaaaaab") ++ (A) ++ ("ab") ++ (A) ++ ("baabaaabaaabaaaa"));
constraint
  (("bbbbbbabaabaaaabbababaabaabbbbaabaabaaab") ++ (A) ++ ("aba")) =
    (("bbbbbbabaabaaaabbab") ++ (A) ++ ("aabbbba") ++ (A) ++ ("aaababaababa"));
constraint
  (("abbbbaaabbbaaaabbaabababbaabababbbbaabaabaabbaaa") ++ ("")) =
    (("abbbbaaabbbaaaabbaabababbaabababbbba") ++ (A) ++ ("aabbaaa"));
constraint
  (("bbabaaabbababbbbabbbabaababbaabaaaaabababaababbb") ++ ("")) =
    (("bbabaaabbababbbbabbb") ++ (A) ++ ("abbaabaaaaabab") ++ (A) ++ ("abbb"));
constraint
  (("bbbabaaabbbbaabbabaaaababbbbbabaabbbaaabaabababa") ++ ("")) =
    (("bbbabaaabbbbaabbabaaaababbbbbabaabbbaa") ++ (A) ++ ("ababa"));
constraint
  (("aaabbabbaaaabbaaab") ++ (A) ++ ("abaabaaabbaaababbbabbbbba")) =
    (("aaabbabbaaaabbaaababaab") ++ (A) ++ ("aaabbaaababbbabbbbba"));
constraint
  (("bababaaabbaabbababaababaaab") ++ (A) ++ ("bbbbaabbbbabbbba")) =
    (("bababaaabbaabbababaababaaab") ++ (A) ++ ("bbbbaabbbbabbbba"));
constraint
  (("bbaabbaabbabababbbbaaabbbaabb") ++ (A) ++ ("aabbb") ++ (A) ++ ("aaba"))
    = (("bbaabbaabbabababbbbaaabbbaabbabaabaabbbabaabaaba") ++ (""));
constraint
  (("bbab") ++ (A) ++ ("babaabbbbaaababbbabaaaabababbabaabababb")) =
    (("bbababaabb") ++ (A) ++ ("bbbaaababbbabaaaabababb") ++ (A) ++ ("ababb"));
constraint
  (("bbabbabbb") ++ (A) ++ ("abbabaabbbbbabababaaabaaababbaaaaa")) =
    (("bbabbabbbabaababb") ++ (A) ++ ("bbbbabababaaabaaababbaaaaa"));
constraint
  (("abbaabbbabbabaaa") ++ (A) ++ ("ababbbbaaaaabaaaaabbbabbabb")) =
    (("abbaabbbabbabaaaabaabababbbbaaaaabaaaaabbbabbabb") ++ (""));
constraint
  (("bbaababbbabbbaabbaabbbbaabaabaaa") ++ (A) ++ ("abaaaabaabb")) =
    (("bbaababbbabbbaabbaabbbbaabaabaaaabaababaaaabaabb") ++ (""));
constraint
  (("abbaabbaaabaabaaabbbaabbbbbbaaabbabaabbababababb") ++ ("")) =
    (("abbaabbaa") ++ (A) ++ ("aaabbbaabbbbbbaaabb") ++ (A) ++ ("bababababb"));
constraint
  (("baaaa") ++ (A) ++ (A) ++ ("bbaaaabababaababaaaabbaaaabbbaaaa")) =
    (("baaaa") ++ (A) ++ ("abaabbbaaaabab") ++ (A) ++ ("abaaaabbaaaabbbaaaa"));
constraint
  (("baaabbaaaaaabbabbbabababbaaaabaabbbabbabbaabbbba") ++ ("")) =
    (("baaabbaaaaaabbabbbabababbaaa") ++ (A) ++ ("bbabbabbaabbbba"));
constraint
  (("abaababbbabababaaaaabaabbbbbabbbbbbbaabbbbabaabb") ++ ("")) =
    ((A) ++ ("abbbabababaaaa") ++ (A) ++ ("bbbbabbbbbbbaabbbbabaabb"));
constraint
  (("baaabbabbbaabaaabbaabbbabbbaabaabbbabbbbbbabbbba") ++ ("")) =
    (("baaabbabbbaabaaabbaabbbabbba") ++ (A) ++ ("bbabbbbbbabbbba"));
constraint
  (("abababbbbabbbaababab") ++ (A) ++ ("aaabbaaabaaabaaabbaabba")) =
    (("abababbbbabbbaababab") ++ (A) ++ ("aaabbaaabaaabaaabbaabba"));
constraint
  (("baabaabbbbabaaaabbbbabaaababba") ++ (A) ++ ("bbbabbaabaabb")) =
    (("ba") ++ (A) ++ ("bbbabaaaabbbbabaaababbaabaabbbbabba") ++ (A) ++ ("b"));
constraint
  (("bbbabb") ++ (A) ++ ("bbbbbaaaaaaaabbbaaaaa") ++ (A) ++ ("aabaaaababb"))
    =
    (("bbbabb") ++ (A) ++ ("bbbbbaaaaaaaabbbaaaaa") ++ (A) ++ ("aabaaaababb"));
constraint
  (("babbaabaabbababbaaabaabbaaabaababbbbababbbbbbbab") ++ ("")) =
    (("babba") ++ (A) ++ ("bababbaaabaabbaa") ++ (A) ++ ("abbbbababbbbbbbab"));
constraint
  (("a") ++ (A) ++ ("abbaababbbaabaaaaaaaaaaaabbbaaabbbbbaabbba")) =
    (("aabaababbaababbbaabaaaaaaaaaaaabbbaaabbbbbaabbba") ++ (""));
constraint
  (("baabababbbbababbbbabaabaabbbaaaabbbaabaabaaaabba") ++ ("")) =
    (("baabababbbbababbbb") ++ (A) ++ ("aabbbaaaabbbaabaabaaaabba"));
constraint
  (("abababbbbabaababaababbabbaabbababababbabbaabbbab") ++ ("")) =
    (("abababbbb") ++ (A) ++ (A) ++ ("abbabbaabbababababbabbaabbbab"));
constraint
  (("abababaaaaababaababbbabbaabaaaabaabababbaabaaaab") ++ ("")) =
    (("abababaaaaababaababbbabbaabaaa") ++ (A) ++ ("ababbaabaaaab"));
constraint
  (("aabaaabbabababbaaaababbaabbaabaabbbaaaaaaabaaaaa") ++ ("")) =
    (("aabaaabbabababbaaaababbaabba") ++ (A) ++ ("bbaaaaaaabaaaaa"));
constraint
  (("babbbbaaabbabbaaabaaabbaaaaabbababbabbabaa") ++ (A) ++ ("a")) =
    (("babbbbaaabbabbaaabaaabbaaaaabbababbabbabaa") ++ (A) ++ ("a"));
constraint
  (("aabbaaaabbbabaabbaaaabbbaabbbaabbbbabb") ++ (A) ++ ("babba")) =
    (("aabbaaaabbb") ++ (A) ++ ("baaaabbbaabbbaabbbbabb") ++ (A) ++ ("babba"));
constraint
  (("babbbbbbbbbaaaababbabbbabaaaabbaab") ++ (A) ++ ("bbabbaaba")) =
    (("babbbbbbbbbaaaababbabbbabaaaabbaababaabbbabbaaba") ++ (""));
constraint
  (("babaabaabbaabbbbabababababbbbaababbabaaaabaabaab") ++ ("")) =
    (("b") ++ (A) ++ ("aabbaabbbbabababababbbbaababbabaaaabaabaab"));
constraint
  (("babbbbbbbabbabbbabaa") ++ (A) ++ ("bbaabbabbaaaabaaaababaa")) =
    (("babbbbbbbabbabbbabaaabaabbbaabbabbaaaabaaaababaa") ++ (""));
constraint
  (("bababbbbbaabbaaababbabbabaaaabaaabaababbbbababaa") ++ ("")) =
    (("bababbbbbaabbaaababbabbabaaaabaa") ++ (A) ++ ("abbbbababaa"));
constraint
  (("aa") ++ (A) ++ ("baabaabbaaababbbbbabbb") ++ (A) ++ ("babbbbabbabbba"))
    = (("aaabaabbaabaabbaaababbbbbabbbabaabbabbbbabbabbba") ++ (""));
constraint
  (("abaaaaabaaababbbbbabaabab") ++ (A) ++ ("bbbaabbababaaaabbb")) =
    (("abaaaaabaaababbbbbabaabababaabbbbaabbababaaaabbb") ++ (""));
constraint
  (("abaaabbbb") ++ (A) ++ ("bbaaabbabbaaababbbbbabbbaaab") ++ (A) ++ ("a"))
    =
    (("abaaabbbb") ++ (A) ++ ("bbaaabbabbaaababbbbbabbbaaab") ++ (A) ++ ("a"));
constraint
  (("baaaabbbaaabaaababbbabbabbbbbaabbabbbababab") ++ (A)) =
    (("baaaabbbaaabaaababbbabbabbbbbaabbabbbababababaab") ++ (""));
constraint
  (("bb") ++ (A) ++ ("baaabbabaaabbaaaababbbabababbaabbbaaabbba")) =
    (("bb") ++ (A) ++ ("baaabbabaaabbaaaababbbabababbaabbbaaabbba"));
constraint
  (("babbbbbaabbaabbabbb") ++ (A) ++ (A) ++ ("ababbaaababbbbbaaaa")) =
    (("babbbbbaabbaabbabbbabaab") ++ (A) ++ ("ababbaaababbbbbaaaa"));
constraint
  (("baaabbabb") ++ (A) ++ ("aabbbbabbaabaabbabaaaa") ++ (A) ++ ("aabbbba"))
    =
    (("baaabbabb") ++ (A) ++ ("aabbbbabba") ++ (A) ++ ("babaaaa") ++ (A) ++ ("aabbbba"));
constraint
  (("babbabbaabbabababbababbba") ++ (A) ++ ("abbabaaababbbaaabb")) =
    (("babbabbaabbabababbababbba") ++ (A) ++ ("abbabaaababbbaaabb"));
constraint
  (("abbabbabbbbaaaaaaabaabbababbaa") ++ (A) ++ ("aaaaababaaaba")) =
    (("abbabbabbbbaaaaaa") ++ (A) ++ ("bababbaa") ++ (A) ++ ("aaaaababaaaba"));
constraint
  (("bbaaabbbbbabbbbbabbbaaaabbabbabaaa") ++ (A) ++ ("babbbbbbb")) =
    (("bbaaabbbbbabbbbbabbbaaaabbabbabaaaabaabbabbbbbbb") ++ (""));
constraint
  (("babbaaababb") ++ (A) ++ ("bbaabba") ++ (A) ++ ("b") ++ (A) ++ ("aaaabbaaaababb"))
    = (("babbaaababb") ++ (A) ++ ("bbaabbaabaabbabaabaaaabbaaaababb"));
constraint
  (("aa") ++ (A) ++ ("aaabbbbbaaaaababbbabbbaabbabaaabaabaaaabb")) =
    (("aaabaabaaabbbbbaaaaababbbabbbaabbabaa") ++ (A) ++ ("aaaabb"));
constraint
  (("ababaaabbba") ++ (A) ++ ("bbbbbaabaaaabbbbabbbbaabbabbabab")) =
    (("ababaaabbba") ++ (A) ++ ("bbbbbaabaaaabbbbabbbbaabbabbabab"));
constraint
  (("baabbbbaababbaababbbaaaaaabbaa") ++ (A) ++ ("bbaabbaaaaaab")) =
    (("baabbbbaababbaababbbaaaaaabbaa") ++ (A) ++ ("bbaabbaaaaaab"));
constraint
  (("bbbbaabbbabababbaabbaababaaabaaaaaaabaababbaaaba") ++ ("")) =
    (("bbbbaabbbabababbaabbaababaaabaaaaaa") ++ (A) ++ ("abbaaaba"));
constraint
  (("bababbabbbbaa") ++ (A) ++ ("baabbbabbababbbaababbabbbabaaa")) =
    (("bababbabbbbaa") ++ (A) ++ ("baabbbabbababbbaababbabbbabaaa"));
constraint
  (("aabbbbbbabababaabbabbabaaaaababbbbbbbaaaabbababa") ++ ("")) =
    (("aabbbbbbabab") ++ (A) ++ ("babbabaaaaababbbbbbbaaaabbababa"));
constraint
  (("aaaabaaabaababaaaabaaabbaabbaaabbbaababaaaaaabba") ++ ("")) =
    (("aaaabaa") ++ (A) ++ ("abaaaabaaabbaabbaaabbbaababaaaaaabba"));
constraint
  (("aaaababab") ++ (A) ++ ("abaaabbbababbbbbbababaaaaaababbabb")) =
    (("aaaababababaababaaabbbababbbbbbababaaaaaababbabb") ++ (""));
constraint
  (("abaaabaaaabaa") ++ (A) ++ ("bbbbbbaaabbaabababbabbaabbbbaa")) =
    (("abaaabaaaabaaabaabbbbbbbaaabbaabababbabbaabbbbaa") ++ (""));
constraint
  (("baabbaaaabaaabaaabbabbabbbaaababbabbaaababb") ++ (A)) =
    (("baabbaaaabaaabaaabbabbabbbaaababbabbaaababb") ++ (A));
constraint
  (("abbb") ++ (A) ++ ("aaaababbbaaaaabbbbbbbbaaaaabbbbaababbaa")) =
    (("abbb") ++ (A) ++ ("aaaababbbaaaaabbbbbbbbaaaaabbbbaababbaa"));
constraint
  (("ab") ++ (A) ++ ("babbbaaababbbbbaabaaaabbbaaabaaaaabbaaabb")) =
    (("ababaabbabbbaaababbbbbaabaaaabbbaaabaaaaabbaaabb") ++ (""));
constraint
  (("a") ++ (A) ++ ("bbbababaabbbaaaaabbbbaa") ++ (A) ++ ("aabbbbbaabaaab"))
    =
    (("aabaabbbbab") ++ (A) ++ ("bbaaaaabbbbaa") ++ (A) ++ ("aabbbbbaabaaab"));
constraint
  (("aabaaaabb") ++ (A) ++ ("bbabbabaaabbaabbbbbbabbbbaabaaabbb")) =
    (("aabaaaabbabaabbbabbabaaabbaabbbbbbabbbbaabaaabbb") ++ (""));
constraint
  (("aabbabb") ++ (A) ++ ("baabaabaaabbbbab") ++ (A) ++ ("baaaaaabbaaabbb"))
    =
    (("aabbabbabaabba") ++ (A) ++ ("aaabbbbab") ++ (A) ++ ("baaaaaabbaaabbb"));
constraint
  (("aabab") ++ (A) ++ ("aaaabbba") ++ (A) ++ ("abaaabbbbabbbaabbbaaabbba"))
    =
    (("aabab") ++ (A) ++ ("aaaabbba") ++ (A) ++ ("abaaabbbbabbbaabbbaaabbba"));
constraint
  (("babbbaabbabaa") ++ (A) ++ ("babaaabaaaabbbaaaaabbbaabbbaab")) =
    (("babbbaabbabaa") ++ (A) ++ ("babaaabaaaabbbaaaaabbbaabbbaab"));
constraint
  (("bbaaaababaabaabbabbbbbaaabbbabbbbbbbaaabaa") ++ (A) ++ ("b")) =
    (("bbaaaab") ++ (A) ++ ("aabbabbbbbaaabbbabbbbbbbaaabaa") ++ (A) ++ ("b"));
constraint
  (("abbbbbabbbaaabababbbabaaaabbbabbbaaababbbaaabaab") ++ ("")) =
    (("abbbbbabbbaaabababbbabaaaabbbabbbaaababbbaa") ++ (A));
constraint
  (("babaaabaaabbbaababbabbaaaabbbaaaabaabbaaababbaab") ++ ("")) =
    (("babaaabaaabbbaababbabbaaaabbbaaa") ++ (A) ++ ("baaababbaab"));
constraint
  (("abbbabababbbaaabbabaaaaaabaaababaaabaabbbaabbbbb") ++ ("")) =
    (("abbbabababbbaaabbabaaaaaabaaababaa") ++ (A) ++ ("bbaabbbbb"));
constraint
  (("aabaabab") ++ (A) ++ ("abaaabbbaababaabbababbbaaaaabbabbab")) =
    (("aabaabababaababaaabbbaab") ++ (A) ++ ("bababbbaaaaabbabbab"));
constraint
  (("abaabbabbbbaabbbaabbbaaaaabbb") ++ (A) ++ ("aaababaaabbbbb")) =
    ((A) ++ ("babbbbaabbbaabbbaaaaabbb") ++ (A) ++ ("aaababaaabbbbb"));
constraint
  (("baaaabaabbbbaaabbabbbaabbababb") ++ (A) ++ ("babbbababaaba")) =
    (("baaaabaabbbbaaabbabbbaabbababb") ++ (A) ++ ("babbbababaaba"));
constraint
  (("ba") ++ (A) ++ ("bbabba") ++ (A) ++ ("bbaaaabbbb") ++ (A) ++ ("abbb") ++ (A) ++ ("ababab"))
    =
    (("ba") ++ (A) ++ ("bbabbaabaabbbaaaabbbbabaababbb") ++ (A) ++ ("ababab"));
constraint
  (("bbbaabbbaaabaaaabaabbaaaabbaaaabbababbbaa") ++ (A) ++ ("aa")) =
    (("bbbaabbbaaabaaa") ++ (A) ++ ("baaaabbaaaabbababbbaa") ++ (A) ++ ("aa"));
constraint
  (("baaabbaaaaabbbabbbababba") ++ (A) ++ ("abababbababababbbba")) =
    (("baaabbaaaaabbbabbbababbaabaababababbababababbbba") ++ (""));
constraint
  ((A) ++ ("abbabbababaaaaaababbabbaabababbabbbabbbaaab") ++ ("")) =
    (("abaababbabbababaaaaaababbabbaabababbabbbabbbaaab") ++ (""));
constraint
  (("aabbbbbbbaabababaabbaaaabaaaaaaaababbbbaaabbabba") ++ ("")) =
    (("aabbbbbbbaabab") ++ (A) ++ ("baaaabaaaaaaaababbbbaaabbabba"));
constraint
  (("aaaabbababbaabbbbab") ++ (A) ++ ("bababbaaaabaaaaabbbbabbb")) =
    (("aaaabbababbaabbbbab") ++ (A) ++ ("bababbaaaabaaaaabbbbabbb"));
constraint
  (("abbbabaaabaabbaaaabbbbababaaababbaabababbbbbaaaa") ++ ("")) =
    (("abbbabaa") ++ (A) ++ ("baaaabbbbababaaababbaabababbbbbaaaa"));
constraint
  (("babaababbabbbabbaaaa") ++ (A) ++ ("aaababaabbbbaaaabbbaaab")) =
    (("babaababbabbbabbaaaa") ++ (A) ++ ("aaababaabbbbaaaabbbaaab"));
constraint
  (("aababbbbababbbaaaaaaabbbaabbaabbbbbbab") ++ (A) ++ ("bbaaa")) =
    (("aababbbbababbbaaaaaaabbbaabbaabbbbbbab") ++ (A) ++ ("bbaaa"));
constraint
  (("bbabbbabbbbbbbabbbabaabbbaabbababbbaabbbbbbbaaba") ++ ("")) =
    (("bbabbbabbbbbbbabbb") ++ (A) ++ ("bbaabbababbbaabbbbbbbaaba"));
constraint
  (("abaaabbbabaaaabbabbabaababbbbaabbbbbbabaababbabb") ++ ("")) =
    (("abaaabbbabaaaabbabb") ++ (A) ++ ("abbbbaabbbbbb") ++ (A) ++ ("abbabb"));
constraint
  (("baaabaaaabbabbaabbaa") ++ (A) ++ ("bbabbbbaabbbaababaaaabb")) =
    (("baaabaaaabbabbaabbaaabaabbbabbbbaabbbaababaaaabb") ++ (""));
constraint
  (("bbabaaabbababbaaaabba") ++ (A) ++ ("aaababbbaaabababbbbbab")) =
    (("bbabaaabbababbaaaabbaabaabaaababbbaaabababbbbbab") ++ (""));
constraint
  (("bbaaababbaaaaabbababbbbbbbbbbabbbaabab") ++ (A) ++ ("bbbab")) =
    (("bbaaababbaaaaabbababbbbbbbbbbabbbaabababaabbbbab") ++ (""));
constraint
  (("aaababababbbaabbba") ++ (A) ++ ("baabbaaaaaaaaabbbababbbab")) =
    (("aaababababbbaabbbaabaabbaabbaaaaaaaaabbbababbbab") ++ (""));
constraint
  (("babbbabaaaababbabbbaabbabbaabbbbbabbabbbaab") ++ (A)) =
    (("babbbabaaaababbabbbaabbabbaabbbbbabbabbbaab") ++ (A));
constraint
  (("baaababaababbabaabaababbabbbabbbabaaabbaabaaaaab") ++ ("")) =
    (("baaab") ++ (A) ++ ("abb") ++ (A) ++ ("aababbabbbabbbabaaabbaabaaaaab"));
constraint
  (("aabbabbbb") ++ (A) ++ ("bbbbbbabababbaababbaabaaaaabbbbaba")) =
    (("aabbabbbb") ++ (A) ++ ("bbbbbbabababbaababbaabaaaaabbbbaba"));
constraint
  (("aabbaabbbbbbaaaabbbababaaababaabaaaabaabbbbababa") ++ ("")) =
    (("aabbaabbbbbbaaaabbbababaaab") ++ (A) ++ ("aaa") ++ (A) ++ ("bbbababa"));
constraint
  (("bbbabb") ++ (A) ++ ("baaaaaababaabaabaaaaaabaaabaaabbbbaab")) =
    (("bbbabb") ++ (A) ++ ("baaaaaab") ++ (A) ++ ("aabaaaaaabaaabaaabbbbaab"));
constraint
  (("aaaaaaababbbbbabbbbaabbbab") ++ (A) ++ ("abbaaababababbaab")) =
    (("aaaaaaababbbbbabbbbaabbbab") ++ (A) ++ ("abbaaababababbaab"));
constraint
  (("baabaababbbababbabaaaababababaaabbbabbabbbaaaaaa") ++ ("")) =
    (("ba") ++ (A) ++ ("abbbababbabaaaababababaaabbbabbabbbaaaaaa"));
constraint
  (("babaabaabbbbaaaaabbabbbaaababaaabaaabaaabaabbaab") ++ ("")) =
    (("babaabaabbbbaaaaabbabbbaaababaaabaaabaa") ++ (A) ++ ("baab"));
constraint
  (("abbbabbaaaaabbbbbabbabbbbaaabbabaababaaabbbaabaa") ++ ("")) =
    (("abbbabbaaaaabbbbbabbabbbbaaabb") ++ (A) ++ ("abaaabbbaabaa"));
constraint
  (("abbabaabaaabbbbbbbaaaababaabbaaabababaababaaaabb") ++ ("")) =
    (("abb") ++ (A) ++ ("aaabbbbbbbaaaab") ++ (A) ++ ("baaabab") ++ (A) ++ ("abaaaabb"));
constraint
  (("abaabbbbababbbbbbabbbbbbbabbbabbbaaaabbaaababbab") ++ ("")) =
    ((A) ++ ("bbbababbbbbbabbbbbbbabbbabbbaaaabbaaababbab") ++ (""));
constraint
  (("aaa") ++ (A) ++ ("ababbaaabbabaabbaababbbabbbbbaabbbbbbbaa")) =
    (("aaa") ++ (A) ++ ("ababbaaabbabaabbaababbbabbbbbaabbbbbbbaa"));
constraint
  (("bbabbbbbaabbabaaaabb") ++ (A) ++ ("bbababbbaabbabbaaaaaabb")) =
    (("bbabbbbbaabbabaaaabbabaabbbababbbaabbabbaaaaaabb") ++ (""));
constraint
  (("bbbaabaaaabaaaaab") ++ (A) ++ ("ab") ++ (A) ++ ("abb") ++ (A) ++ ("bbbaaabbabb"))
    =
    (("bbbaabaaaabaaaaab") ++ (A) ++ ("ababaababb") ++ (A) ++ ("bbbaaabbabb"));
constraint
  (("babaabbbbaaaaabbbaabbbaaaabbaababbbababbabbbaabb") ++ ("")) =
    (("b") ++ (A) ++ ("bbbaaaaabbbaabbbaaaabbaababbbababbabbbaabb"));
constraint
  (("aabaaa") ++ (A) ++ ("abbbbabbabbbbaaaaaabbbaaaaab") ++ (A) ++ ("babb"))
    = (("aabaaaabaababbbbabbabbbbaaaaaabbbaaaaababaabbabb") ++ (""));
constraint
  (("aaaaabaabaaaaaabb") ++ (A) ++ ("babbaabbbaabbabaa") ++ (A) ++ ("abaa"))
    =
    (("aaaaabaabaaaaaabb") ++ (A) ++ ("babbaabbbaabbabaa") ++ (A) ++ ("abaa"));
constraint
  (("aaabbbbaababababbbba") ++ (A) ++ ("ababbaaaaabababbababbaa")) =
    (("aaabbbbaababababbbba") ++ (A) ++ ("ababbaaaaabababbababbaa"));
constraint
  (("bbabaabbaaa") ++ (A) ++ ("abaabaabbababbbbaabbb") ++ (A) ++ ("aaaaab"))
    =
    (("bbabaabbaaaabaab") ++ (A) ++ ("aabbababbbbaabbb") ++ (A) ++ ("aaaaab"));
constraint
  (("b") ++ (A) ++ ("abbbabbbaaaaaaabaabbbb") ++ (A) ++ ("baaaabbbaababaa"))
    = (("babaababbbabbbaaaaaaabaabbbb") ++ (A) ++ ("baaaabbbaababaa"));
constraint
  (("babaaaabbaaabbaaabbabbaabaababbbabaabaabbbabbbbb") ++ ("")) =
    (("babaaaabbaaabbaaabbabba") ++ (A) ++ ("abbb") ++ (A) ++ ("aabbbabbbbb"));
solve satisfy;
