var string: I;
var string: G;
var string: A;
var string: D;
constraint
  (("deacaaaddfdaadfaefabdaaaaceeecedfbcecccda") ++ (D) ++ ("ecfdfdbfbbdeeece"))
    =
    (("de") ++ (I) ++ (A) ++ ("aaa") ++ (G) ++ ("aababeacbaeecffbbfefabbfaaacdaceecfdfdbfbbdeeece"));
constraint
  (("cfdebfdfbedafebcaafeacbeaacfecfbcdecfeeefebeddccffafbdeacabadbedeebeaeedafebeffbcacdedfdfffbbac") ++ (""))
    =
    (("cfdebfdfbedafebcaafeacbeaacfecfbcdecfeeefebeddccffafbde") ++ (I) ++ ("badbedeebeaeedafebeffbcacdedfdfffbbac"));
constraint
  (("ccfaddadbfed") ++ (I) ++ ("fbddeedccecdbbfecfffabffdbdcabeebdcfcafbaabbaadeecfecaeaafedcdadbefcdfdbceadeeda"))
    =
    (("ccfaddadbfedacafbddeedccecdbbfecfffabffdbdcabeebdcfcafbaabbaadeecfecaeaafedcdadbefcdfdbceadeeda") ++ (""));
constraint
  (("ebccffebebfaabcb") ++ (I) ++ ("eccfbecbebfceecfccfbdbffccbdbddaaceaeabfccdcbaaeabedffebdeeaefdcaeaacdcedadd"))
    =
    (("ebccffebebfaabcb") ++ (I) ++ ("eccfbecbebfceecfccfbdbffccbdbddaaceaeabfccdcbaaeabedffebdeeaefdcaeaacdcedadd"));
constraint
  (("faaabffdddafddcfdcfcdeeaaedbfcbfeaffaeefcfbffebddeecdffccefaafcdbdcaacbdccfbacadbdadebcdcbecbbf") ++ (""))
    =
    (("faaabffdddafddcfdcfcdeeaaedbfcbfeaffaeefcfbffebddeecdffccefaafcdbdcaacbdccfb") ++ (I) ++ ("dbdadebcdcbecbbf"));
constraint
  (("ecfbacefafbcffdaeccccfdbfbedecdcedbadefecddabdaefefcfbadbdbebcafaeaaecaadcfdace") ++ (I) ++ ("bfddafbdcceae"))
    =
    (("ecfbacefafbcffdaeccccfdbfbedecdcedbadefecddabdaefefcfbadbdbebcafaeaaecaadcfdace") ++ (I) ++ ("bfddafbdcceae"));
constraint
  (("cbedbbdbbdedafdccdeccbfbcddadedbbacefaaecbbaeaceefdcebecbbdffbafaecbebeeefbdecfdfbeae") ++ (I) ++ ("bededcd"))
    =
    (("cbedbbdbbdedafdccdeccbfbcddadedbbacefaaecbbaeaceefdcebecbbdffbafaecbebeeefbdecfdfbeae") ++ (I) ++ ("bededcd"));
constraint
  (("bcdeadacdfcababbecabcffebcaceecfdfcecbbbfcbdacadccdaffdabdbcdeabbbfaedaebbdbfcebdccbaeddfcfbeff") ++ (""))
    =
    (("bcdeadacdfcababbecabcffebcaceecfdfcecbbbfcbd") ++ (I) ++ ("dccdaffdabdbcdeabbbfaedaebbdbfcebdccbaeddfcfbeff"));
constraint
  (("acbbcfedce") ++ (I) ++ ("fcbeaeeebdaaafedadddecffdbdefbddfbaddbcefdefdebcdffedaffcdcbccaffdaaddecaacfaefbdb"))
    =
    (("acbbcfedceacafcbeaeeebdaaafedadddecffdbdefbddfbaddbcefdefdebcdffedaffcdcbccaffdaaddecaacfaefbdb") ++ (""));
constraint
  (("ffafafdfcabcfaacacbdfdfedefdfaccadbeffbceafedbbabdadabaedfdebfcedbeecacbaaddaadaedbbeedacacdbeb") ++ (""))
    =
    (("ffafafdfcabcfa") ++ (I) ++ ("cbdfdfedefdfaccadbeffbceafedbbabdadabaedfdebfcedbeecacbaaddaadaedbbeed") ++ (I) ++ ("cdbeb"));
constraint
  (("eedceeedffcfbcbdcafcccadeecaefacebacceacdfdfeedfffedb") ++ (I) ++ ("bfcafbaedacebccaafffcffeafffdcfdfdbfecd"))
    =
    (("eedceeedffcfbcbdcafcccadeecaefacebacceacdfdfeedfffedb") ++ (I) ++ ("bfcafbaedacebccaafffcffeafffdcfdfdbfecd"));
constraint
  (("fbccdbcffabdabbedbecbfaebcdedcdbefaafefaefabbdeccd") ++ (I) ++ ("abdccfccdecaaeabdeebfcfbdbecdfadfbfffeeece"))
    =
    (("fbccdbcffabdabbedbecbfaebcdedcdbefaafefaefabbdeccdacaabdccfccdecaaeabdeebfcfbdbecdfadfbfffeeece") ++ (""));
constraint
  (("bfefeaedadbcfebfaceddafdcbddbbfacbfdfebfedcccbbaeee") ++ (I) ++ ("daeeffadddabbcfbdeacccaacafaccdabfefcbfdc"))
    =
    (("bfefeaedadbcfebfaceddafdcbddbbfacbfdfebfedcccbbaeeeacadaeeffadddabbcfbdeacccaacafaccdabfefcbfdc") ++ (""));
constraint
  (("bdfccfeadebdafdaaaffcafcbcdeffacdcefeeaafbadfbfddabdbcdfbeffefbcafbacbfcfffcdbfecb") ++ (I) ++ ("ecefddbaef"))
    =
    (("bdfccfeadebdafdaaaffcafcbcdeffacdcefeeaafbadfbfddabdbcdfbeffefbcafbacbfcfffcdbfecb") ++ (I) ++ ("ecefddbaef"));
constraint
  (("ddecaceacbbdbcfbdaeacaebededbacbfabedaecfafadebddfdcdefcbbbbfdfdfdafddaeccdecbfdbcfcfdddcddfeed") ++ (""))
    =
    (("ddecaceacbbdbcfbdae") ++ (I) ++ ("ebededbacbfabedaecfafadebddfdcdefcbbbbfdfdfdafddaeccdecbfdbcfcfdddcddfeed"));
constraint
  (("ecfdfecabdeffbdabbdddfbfefaffeaabdbabfebcffaafadcfdddedbdcbafcdffdfccccfbfffdfa") ++ (I) ++ ("dafecaecabdaf"))
    =
    (("ecfdfecabdeffbdabbdddfbfefaffeaabdbabfebcffaafadcfdddedbdcbafcdffdfccccfbfffdfaacadafecaecabdaf") ++ (""));
constraint
  (("bfbdbaeacaafeacdadfdbcfacfebdcfbeceecaeeaaccabbafecbbefcdaffcfeefbbdadeedbcfbbccecfedbbefddacdd") ++ (""))
    =
    (("bfbdbae") ++ (I) ++ ("afeacdadfdbcfacfebdcfbeceecaeeaaccabbafecbbefcdaffcfeefbbdadeedbcfbbccecfedbbefddacdd"));
constraint
  (("cfadbcefebbbffdebdadaabeeecdcdadcfabebbbddeebeefbfcbfedacfaffbcaddc") ++ (I) ++ ("afcfeafadcfefcebdbdfccdac"))
    =
    (("cfadbcefebbbffdebdadaabeeecdcdadcfabebbbddeebeefbfcbfedacfaffbcaddcacaafcfeafadcfefcebdbdfccdac") ++ (""));
constraint
  (("fcfceffebdbbfdecdabacdcebfabadffcbccefbfbacaeefaeabafaefddfcfbedbadafbcbdcbdbffdbdadbebdfaddbcb") ++ (""))
    =
    (("fcfceffebdbbfdecdabacdcebfabadffcbccefbfb") ++ (I) ++ ("eefaeabafaefddfcfbedbadafbcbdcbdbffdbdadbebdfaddbcb"));
constraint
  (("caafcddcfbfbfbdeeaacccabfcadbabeaeeddaebdbbccdafdeeafacbaebebfaefdeebfccaadcbcaabdeafacadfcbbac") ++ (""))
    =
    (("caafcddcfbfbfbdeeaacccabfcadbabeaeeddaebdbbccdafdeeafacbaebebfaefdeebfccaadcbcaabdeaf") ++ (I) ++ ("dfcbbac"));
constraint
  (("fdeafabbcadfbebecfdcdefebebffbcddecabcefcacfaafdaddeceaadb") ++ (I) ++ ("cfebfbcebbaacbfcdeacfefaebcddfdfab"))
    =
    (("fdeafabbcadfbebecfdcdefebebffbcddecabcefcacfaafdaddeceaadb") ++ (I) ++ ("cfebfbcebbaacbfcdeacfefaebcddfdfab"));
constraint
  (("fadaebfaaceafddaaecceaddbeaefaeeaaffdbfbeabaddcbafebbfffaeadbebedeecdddedfafeffadfcbbfacaacbbbe") ++ (""))
    =
    (("fadaebfaaceafddaaecceaddbeaefaeeaaffdbfbeabaddcbafebbfffaeadbebedeecdddedfafeffadfcbbf") ++ (I) ++ ("acbbbe"));
constraint
  (("afefefccecabcccdbbfdddcaafabaedacecfccfdbfebceaeccfadedfcbaaacedddccefdadfecbeefeecfaff") ++ (I) ++ ("cbdfd"))
    =
    (("afefefccecabcccdbbfdddcaafabaedacecfccfdbfebceaeccfadedfcbaaacedddccefdadfecbeefeecfaff") ++ (I) ++ ("cbdfd"));
constraint
  (("fccaaaeffacbdecfaacbceedddefeedfbadecfcfcdefbdffdbbdebcabeebeeaccccbecfecfdbf") ++ (I) ++ ("dddbeecdccbcdec"))
    =
    (("fccaaaeffacbdecfaacbceedddefeedfbadecfcfcdefbdffdbbdebcabeebeeaccccbecfecfdbfacadddbeecdccbcdec") ++ (""));
constraint
  (("acbadddfdcfeafbdeeedfdffafdaeeeefa") ++ (I) ++ ("eebcfdecabdeaffeabfcfdbdabfdfbabedbdfbefeedfaadbbeeecadbfd"))
    =
    (("acbadddfdcfeafbdeeedfdffafdaeeeefaacaeebcfdecabdeaffeabfcfdbdabfdfbabedbdfbefeedfaadbbeeecadbfd") ++ (""));
constraint
  (("debbdfcadececbbcdcdddeecdcdcbeffabcadcddbeb") ++ (I) ++ ("ceacedbebdfefcbafeeaefedbeddadcdafcfbdfbbccccbceb"))
    =
    (("debbdfcadececbbcdcdddeecdcdcbeffabcadcddbebacaceacedbebdfefcbafeeaefedbeddadcdafcfbdfbbccccbceb") ++ (""));
solve satisfy;
