var string: B;
var string: A;
constraint
  (("bbdcabcabcaadbdacdcabcaacdcadacbdaddbabccdbacadcddccdcadbdbbcdaccbddccdabaddababdd") ++ (""))
    = (("bbdcabcabcaadbdac") ++ (B) ++ ("dbbcdaccbddccdabaddababdd"));
constraint
  (("ccbbaddcacba") ++ (A) ++ ("bddcacabccbbddabacaaba")) =
    (("ccbbaddcac") ++ (B) ++ ("dacdaddbcdabbbdcbddcacabccbbddabacaaba"));
constraint
  (("babbbdadabaaccadaabdbcc") ++ (A) ++ ("abbd")) =
    (("babbbdadabaa") ++ (B) ++ ("cdcacbccacabbd"));
constraint
  (("aabacdabdbcabbddabcdacacdabbddcbccd") ++ (B) ++ ("abadbddcdaba")) =
    (("aabacdabdbcabbddabcdacacdabbd") ++ (A) ++ ("d") ++ (B) ++ ("abadbddcdaba"));
constraint
  (("bbccbaaddbaaddacdcbddcb") ++ (A) ++ ("dcdcbaccbbbddadadaaacbaaadddaacabaccdcbdaccbcaaaccacaa"))
    =
    (("bbccbaaddbaaddacdcbddcbdcbccdcdcbaccbbbddadadaaacbaaadddaacabaccdcbdaccbcaaaccacaa") ++ (""));
constraint
  (("bddcbdcbcddcbaabcccbdaacdcbcdabbcdcaadcacad") ++ (A) ++ ("bcdcbabcdcaabcdddcacaaaaddddaddbbd"))
    =
    (("bddcbdcbcddcbaabcccbdaacdcbcdabbcdcaadcacad") ++ (A) ++ ("bcdcbabcdcaabcdddcacaaaaddddaddbbd"));
constraint
  (("bcdbccdbabddcdcaaddcdacbbcdbaddbddcbcccaaaddacaaddadaddddbadcbaaccaabbbdbbacadcabd") ++ (""))
    =
    (("bcdbccdbabddcdcaaddcdacbbcdbaddbd") ++ (A) ++ ("caaaddacaaddadaddddbadcbaaccaabbbdbbacadcabd"));
constraint
  (("cacaaccbbbbdabdbbacaacdacccadbcaadcabd") ++ (A) ++ ("dddacdaaaacbabadabababacacadccccabbcbdb"))
    =
    (("cacaaccbbbbdabdbbacaacdacccadbcaadcabd") ++ (A) ++ ("dddacdaaaacbabadabababacacadccccabbcbdb"));
constraint
  (("aadbcacdaadcababaddbcdadccacbcdddcaacbacaa") ++ (A) ++ ("bcbccdcdbccdcbbcdbacdcaababdabaddcb"))
    =
    (("aadbcacdaadcababaddbcdadccacbcdddcaacbacaadcbccbcbccdcdbccdcbbcdbacdcaababdabaddcb") ++ (""));
constraint
  (("ddcbdabdcdbccdacccdbc") ++ (A) ++ ("cbcabbddaddbdbbdabbccdbcbaacbbdbcadccaaacaabacdaababddba"))
    =
    (("ddcbdabdcdbccdacccdbc") ++ (A) ++ ("cbcabbddaddbdbbdabbccdbcbaacbbdbcadccaaacaabacdaababddba"));
constraint
  (("abdbbcdaddadabdcbcdcbdbdddcabbdddcbccdddcabdabdbababddabdaaaabcbaacbdaddbbacadccda") ++ (""))
    =
    (("abdbbcdaddadabdcbcdcbdbdddcabbdd") ++ (A) ++ ("dddcabdabdbababddabdaaaabcbaacbdaddbbacadccda"));
constraint
  (("cacacadccaaddddaddcdbbbccbdbbdbdcbccbbacbdbbdabcdabccacbbaddbaabcbbdbcdbccabadcdba") ++ (""))
    =
    (("cacacadccaaddddaddcdbbbccbdbbdb") ++ (A) ++ ("bbacbdbbdabcdabccacbbaddbaabcbbdbcdbccabadcdba"));
constraint
  (("dcbacbccbdcdbbacdcbccbddddcdcaabcdacaaccaadaaccbccdccbbbcddbabddbdccabccbaaccdbadb") ++ (""))
    =
    (("dcbacbccbdcdbbac") ++ (A) ++ ("bddddcdcaabcdacaaccaadaaccbccdccbbbcddbabddbdccabccbaaccdbadb"));
constraint
  (("bcbbbbdbcaadaaddabdbddbcaaadbdacabcddacbaaccaadddcdbdcbccddcacacacbdabbabdddbacabc") ++ (""))
    =
    (("bcbbbbdbcaadaaddabdbddbcaaadbdacabcddacbaaccaadddcdb") ++ (A) ++ ("ddcacacacbdabbabdddbacabc"));
constraint
  (("acabcccdcbacabacbdbdbdbadddacadbcaddbbacacbacdcadbcbddcbccaadabcddacddddbaddcdaccc") ++ (""))
    =
    (("acabcccdcbacabacbdbdbdbadddacadbcaddbbacacbacdcadbcbd") ++ (A) ++ ("aadabcddacddddbaddcdaccc"));
constraint
  (("ccccaabdabbdbdccbaadbadbabcdaadaccbcaadbbdcddbccccddabcaddbcd") ++ (A) ++ ("acaddcdbadbaadba"))
    =
    (("ccccaabdabbdbdccbaadbadbabcdaadaccbcaadbbdcddbccccddabcaddbcd") ++ (A) ++ ("acaddcdbadbaadba"));
constraint
  (("cadcbccdbcdbbaabdbbababcddacbbccbcacbabacbcddbdadbbddaabaddbaacadbcdbcacccdcdbbdaa") ++ (""))
    =
    (("ca") ++ (A) ++ ("dbcdbbaabdbbababcddacbbccbcacbabacbcddbdadbbddaabaddbaacadbcdbcacccdcdbbdaa"));
constraint
  (("bbcbdcaacccccdddaadddbddcbccadbccadcccdaaaacadcbbcacadbcdbadcbacdbdbbccadccacadbdc") ++ (""))
    =
    (("bbcbdcaacccccdddaadddbd") ++ (A) ++ ("adbccadcccdaaaacadcbbcacadbcdbadcbacdbdbbccadccacadbdc"));
constraint
  (("cdbdbddaaaacdbcababcccadbbaaabadbadbabcdcbccbacdaabdcacccdccdaadccddacadcbcacbbadd") ++ (""))
    =
    (("cdbdbddaaaacdbcababcccadbbaaabadbadbabc") ++ (A) ++ ("bacdaabdcacccdccdaadccddacadcbcacbbadd"));
constraint
  (("dcbddabdacdbcaaba") ++ (A) ++ ("dacadadcdccacccbabcaacbabcbcabcbdbcccdaaaabcacbaacbbbcaacbca"))
    =
    (("dcbddabdacdbcaabadcbccdacadadcdccacccbabcaacbabcbcabcbdbcccdaaaabcacbaacbbbcaacbca") ++ (""));
constraint
  (("acbbaacadcdbbbbbaacbabbccdcbaaabbcdddabacacaddccbabcadcacdbdcadcdccbab") ++ (A) ++ ("bbbcbcb"))
    =
    (("acbbaacadcdbbbbbaacbabbccdcbaaabbcdddabacacaddccbabcadcacdbdcadcdccbabdcbccbbbcbcb") ++ (""));
constraint
  (("adccbdbddacdbadcbcdaacacccadbbbdbcaabaaaabddbcccdcbdbadbdcbdc") ++ (A) ++ ("cadbbbbddcadadba"))
    =
    (("adccbdbddacdbadcbcdaacacccadbbbdbcaabaaaabddbcccdcbdbadbdcbdcdcbcccadbbbbddcadadba") ++ (""));
constraint
  (("bacbaccccccccbdcdbbdbbbabbabddcdbbb") ++ (A) ++ ("cbadcdbdbcccaabadbabbbcabcdddccccdddaadbba"))
    =
    (("bacbaccccccccbdcdbbdbbbabbabddcdbbbdcbcccbadcdbdbcccaabadbabbbcabcdddccccdddaadbba") ++ (""));
solve satisfy;
