var string: B;
var string: A;
constraint
  (("aaadbceacceaae") ++ (A) ++ ("dcbfaabfbdafbfcaffdebaebaecdbfadebbceeddacfffdce"))
    = (("aaadbceacceaaecac") ++ (B) ++ ("affdebaebaecdbfadebbceeddacfffdce"));
constraint
  (("dbeeaebbcbaaefebedeefc") ++ (B) ++ ("fabefefbafcbedcdeccfecdfda")) =
    (("dbeeaebbcbaaefebedeefc") ++ (B) ++ ("fabefefbafcbedcdeccfecdfda"));
constraint
  (("bbfacfbceedcadebabcbcfeaefcafa") ++ (A) ++ ("edacbabeffbafeeeeefbdcbcabadafacacdeb"))
    =
    (("bbfacfbceedcadebabcb") ++ (B) ++ ("edacbabeffbafeeeeefbdcbcabadafacacdeb"));
constraint
  (("bdfce") ++ (A) ++ ("cdedeaefdf") ++ (B) ++ ("dba")) =
    (("bdfceddcfaaecdedeaefdfcfcdbfaebbacacffcabdfdcddffeaacabbdfdfdcbfacecbbbbbedcbcacaadba") ++ (""));
constraint
  (("aaefdeaf") ++ (A) ++ ("bcfbdcfaceefcbeeebfddceefccabdbfeebafdbcedcabffacbfbafebfafceeefacfbdd"))
    =
    (("aaefdeaf") ++ (A) ++ ("bcfbdcfaceefcbeeebfddceefccabdbfeebafdbcedcabffacbfbafebfafceeefacfbdd"));
constraint
  (("cadefbfddfcaebdddddbcecafaefacbfaeeebdefea") ++ (B) ++ ("fbacbbdbecdffebbcdbeadccbeefccbcbdccdf"))
    =
    (("cadefbfddfcaebdddddbcecafaefacbfaeeebdefea") ++ (B) ++ ("fbacbbdbecdffebbcdbeadccbeefccbcbdccdf"));
constraint
  (("fcbfeafebebefffadbfebadbdcadbeebbfaf") ++ (B) ++ ("cdcfdbdccafbeebbbbbebceadedaafabfececaedaebb"))
    =
    (("fcbfeafebebefffadbfebadbdcadbeebbfaf") ++ (B) ++ ("cdcfdbdccafbeebbbbbebceadedaafabfececaedaebb"));
constraint
  (("beddcefadaddeecffddfaecfafeefcdebaabfbacaaadcbdcabdcdfebadcdcdfddfeecccfebeaebeaddbcc") ++ (""))
    =
    (("beddcefadaddeecffddfaecfafeef") ++ (B) ++ ("abfbacaaadcbdcabdcdfebadcdcdfddfeecccfebeaebeaddbcc"));
constraint
  (("deebbaaeffbccecafeeebdececfeacfdeadabfdfdacdeeafeabcfefecdced") ++ (B) ++ ("cbaeefddfdacdcbfaeb"))
    =
    (("deebbaaeffbccecafeeebdececfeacfdeadabfdfdacdeeafeabcfefecdced") ++ (B) ++ ("cbaeefddfdacdcbfaeb"));
constraint
  (("cebcbbacbdfdafbfcbabcdecbdefffdefecaddcdfacbaedbceaeafdefcbebdaebbecec") ++ (B) ++ ("cdfdcdadfe"))
    =
    (("cebcbbacbdfdafbfcbabcdecbdefffdefecaddcdfacbaedbceaeafdefcbebdaebbececcdebacdfdcdadfe") ++ (""));
constraint
  (("aeebcfebafadfdaddbdaccacdd") ++ (B) ++ ("afddbceedfdffbaafeccfaedaeedfdacbbecfaffcbebfbddefaffd"))
    =
    (("aeebcfebafadfdaddbdaccacddcdebaafddbceedfdffbaafeccfaedaeedfdacbbecfaffcbebfbddefaffd") ++ (""));
constraint
  (("eeafecafdcadefcaeeaaafabafcdbbcedcdabdbccefecfccbdaaeaabefaee") ++ (B) ++ ("fcdfbbeffcaffeeaabe"))
    =
    (("eeafecafdcadefcaeeaaafabafcdbbcedcdabdbccefecfccbdaaeaabefaee") ++ (B) ++ ("fcdfbbeffcaffeeaabe"));
constraint
  (("dccfbfcefdfecaffcdfceacdcdebafeefbfeadeedfdffddbbdeaecebceaecebebbdebcdcbdcceecabbded") ++ (""))
    =
    (("dccfbfcefdfecaffcdfceacd") ++ (B) ++ ("feefbfeadeedfdffddbbdeaecebceaecebebbdebcdcbdcceecabbded"));
constraint
  (("ebbbefdebdfaeadaedeadadbdfefbcdcccaefeabdbccbfabfccd") ++ (B) ++ ("adbaedbddefdaaddcbdfffcbcfba"))
    =
    (("ebbbefdebdfaeadaedeadadbdfefbcdcccaefeabdbccbfabfccd") ++ (B) ++ ("adbaedbddefdaaddcbdfffcbcfba"));
constraint
  (("ffafabaae") ++ (B) ++ ("ebfffbcdeebeedaddcddcdccafccacfbcccceabffdeaddacca"))
    =
    (("ffafabaaefdcabebadfbfbccafcafafddffebfffbcdeebeedaddcddcdccafccacfbcccceabffdeaddacca") ++ (""));
constraint
  (("ebbababcaacbfcddaddaebfaeffbdecaadbdcfeabecaaefaadfaaedbabafbbbefacbceaedffceabcfacbf") ++ (""))
    = (("ebbababcaacb") ++ (B));
constraint
  (("cbeecedbaeeafbddcffacadefcddadafabcceccbcf") ++ (A) ++ ("fedecaebfaddeedaeceddcbedfbdaffdccdfba"))
    = (("cbeecedba") ++ (B) ++ ("deedaeceddcbedfbdaffdccdfba"));
constraint
  (("cdfcddfafbdebbdbafafcfafabeaeeffaafcbbabededfccdeeedafcfffeecfdddcacedceacdbcdecbdcff") ++ (""))
    =
    (("cdfcddfafbdebbdbafafcfafabeaeeffaafcbbabeded") ++ (A) ++ ("eedafcfffeecfdddcacedceacdbcdecbdcff"));
constraint
  (("fabaedbbdbccabdbbeca") ++ (A) ++ ("dabebfeebbbbefbcfbdcaaabecfcdebeaadbdcccffecfacccedaacdbebda"))
    =
    (("fabaedbbdbccabdbbeca") ++ (A) ++ ("dabebfeebbbbefbcfbdcaaabecfcdebeaadbdcccffecfacccedaacdbebda"));
constraint
  (("caefaaefbfefdbadeacbedaaafdecddcacbfcafcbccdeeeeffccbfddfbfeebcaccaeffb") ++ (A) ++ ("eabeaffae"))
    =
    (("caefaaefbfefdbadeacbedaaafdecddcacbfcafcbccdeeeeffccbfddfbfeebcaccaeffbfccdeeabeaffae") ++ (""));
constraint
  (("eeeacfafbdbddbcadebcffcaeccabcabbf") ++ (A) ++ ("ccbdcefdbdadccbeeaacfdfbdeedcfeffcecbbaaaffeca"))
    =
    (("eeeacfafbdbddbcadebcffcaeccabcabbffccdeccbdcefdbdadccbeeaacfdfbdeedcfeffcecbbaaaffeca") ++ (""));
constraint
  (("cefbcdbacaecfbecaaecfadfefdcaeeddfbfbcbddbfdfadfbeafafdedbfe") ++ (A) ++ ("adbbacadcccefbfcfaff"))
    =
    (("cefbcdbacaecfbecaaecfadfefdcaeeddfbfbcbddbfdfadfbeafafdedbfe") ++ (A) ++ ("adbbacadcccefbfcfaff"));
constraint
  (("bdcaedadafbdbdedcecffffeadfcaebee") ++ (A) ++ ("aeecbdefcbfaacebaffbfdeadeebffddbaedadcdafaace"))
    =
    (("bdcaedadafbdbdedcecffffeadfcaebeedfffcdaeecbdefcbfaacebaffbfdeadeebffddbaedadcdafaace") ++ (""));
constraint
  (("aeababfbcfacaddefdadcafebcfdbbeffaadeaacadfefccbcefbbcdbbefdfdfcfddebdaacbafdb") ++ (A) ++ ("f"))
    =
    (("aeababfbcfacaddefdadcafebcfdbbeffaadeaacadfefccbcefbbcdbbefdfdfcfddebdaacbafdb") ++ (A) ++ ("f"));
constraint
  (("bcdefedbbecdccaaaccfadccacceaafcbfdacffabacdcdfdfacdcfdebcedeefba") ++ (A) ++ ("aacddaabedabce"))
    =
    (("bcdefedbbecdccaaaccfadccacceaafcbfdacffabacdcdfdfacdcfdebcedeefbadfffcdaacddaabedabce") ++ (""));
constraint
  (("dafbeadeaaededbccfacddfd") ++ (A) ++ ("bbfebacfdaeedbbacefbeecfbcbdcffbacbadce"))
    =
    (("dafbeadeaaededbccfacddfdddfcfecfdbaeebbccaafafbbfebacfdaeedbbacefbeecfbcbdcffbacbadce") ++ (""));
constraint
  (("bbaccebaecaaccbdba") ++ (A) ++ ("bbc")) =
    (("bbaccebaecaaccbdba") ++ (A) ++ ("bbc"));
constraint
  (("eeabfbfeeffaabaeaddfebcadeebfefcabcfbcdaedbbfcbcecfcaedeffcfdbbcbbeedcfadcebbbffbdbea") ++ (""))
    =
    (("eeabfbfeeffaabaeaddfebcadeebfefca") ++ (A) ++ ("bbcbbeedcfadcebbbffbdbea"));
constraint
  (("ebcfdcabac") ++ (B) ++ ("bcdebbcaad")) =
    ((A) ++ ("abacbbedaffdafeabbaecdfeddaccbbebbebfcaccaddaafdfdbfbedeffadbcbcdcaefbcdebbcaad") ++ (""));
constraint
  (("efeddddaafeaedbadebcecafafecccaacbcaabbdefadefedeedeacaddfaaefaebcdaddacdddeaf") ++ (A) ++ ("b"))
    =
    (("efeddddaafeaedbadebcecafafecccaacbcaabbdefadefedeedeacaddfaaefaebcdaddacdddeafebcfdcb") ++ (""));
constraint
  (("bbbcdccbbccdeafecadbaddddcfadafdfe") ++ (A) ++ ("bbbdeadcacccbebfce")) =
    (("bbbcdccbbccdeafecadbaddddcfadafdfedefedebfbbaffaafebbbdadcbbcfcbccfbbbdeadcacccbebfce") ++ (""));
constraint
  (("bcdccdcbeeaabeebfcefccdddbceebaebbcdd") ++ (A) ++ ("bbeabaaaffcdbfebeffda"))
    = (("bcdccd") ++ (B) ++ ("aaaffcdbfebeffda"));
constraint
  (("ffdcbfeefdddfbfc") ++ (A) ++ ("beaefaabbbcbdbafecceabcfdfcbefddbdbbddbabea"))
    =
    (("ffdcbfeefdddfbfcfadfbeacfadcefbaf") ++ (B) ++ ("abcfdfcbefddbdbbddbabea"));
constraint
  (("bcebdffdebbcfdfaaeefdefaaacecebdc") ++ (A) ++ ("fafdbdfecdbfbabd")) =
    (("bcebdffdebbcfdfaaeefdefaaacecebdcaededaaeaccbacadbcafaceaeecfeaeadddbfafdbdfecdbfbabd") ++ (""));
constraint
  (("fdfddfd") ++ (B) ++ ("eacbcebbcbde") ++ (B) ++ ("bcdadeccbdceddd") ++ (B) ++ ("f") ++ (B) ++ ("dddaae") ++ (B) ++ ("d") ++ (B) ++ ("abadcdefdccdebbdaadbcbceb") ++ (B) ++ ("fcacbcebdd") ++ (B))
    =
    (("fdfddfdae") ++ (B) ++ ("cbcebbcbde") ++ (B) ++ ("bcd") ++ (B) ++ ("deccbdceddd") ++ (B) ++ ("faddda") ++ (B) ++ ("eada") ++ (B) ++ ("b") ++ (B) ++ ("dcdefdccdebbdaadbcbceb") ++ (B) ++ ("fcacbcebdda"));
constraint
  (("cebe") ++ (B) ++ ("bcdcfbc") ++ (B) ++ ("dceeddbcfcecdbceebdbbdfeeebedfddfdbcfebedddcdfbfddddcebfdde") ++ (B) ++ ("fecce") ++ (B) ++ ("bd") ++ (B) ++ ("ecc"))
    =
    (("cebeabcdcfbcadceeddbcfcecdbceebdbbdfeeebedfddfdbcfebedddcdfbfddddcebfdde") ++ (B) ++ ("fecceabdaecc"));
constraint
  (("addafddcd") ++ (B) ++ ("dfdafedfdfbcdbb") ++ (B) ++ (B) ++ ("fabaebdbbc") ++ (B) ++ (B) ++ ("ddedffccbedbcbbcfbcbebcbcd") ++ (B) ++ ("caecbaefacbffeb") ++ (B) ++ ("bfb"))
    =
    (("add") ++ (B) ++ ("fddcdadfdafedfdfbcdbb") ++ (B) ++ (B) ++ ("fabaebdbbcaaddedffccbedbcbbcfbcbebcbcd") ++ (B) ++ ("c") ++ (B) ++ ("ecbaef") ++ (B) ++ ("cbffeb") ++ (B) ++ ("bfb"));
constraint
  (("ebfff") ++ (B) ++ ("debdefdecadcac") ++ (B) ++ ("aeddeedddfeccbbdc") ++ (B) ++ ("beeafbbecbebcedbdecddbdfb") ++ (B) ++ ("afdfbeebbebeecfcdcfe"))
    =
    (("ebfff") ++ (B) ++ ("debdefdec") ++ (B) ++ ("dcac") ++ (B) ++ (B) ++ ("eddeedddfeccbbdc") ++ (B) ++ ("bee") ++ (B) ++ ("fbbecbebcedbdecddbdfbaafdfbeebbebeecfcdcfe"));
constraint
  (("fedffc") ++ (B) ++ ("aefcc") ++ (B) ++ ("cdbbfadfbfbddbcdcbbacfced") ++ (B) ++ (B) ++ ("ceeedfffcf") ++ (B) ++ ("b") ++ (B) ++ (B) ++ ("cdddbb") ++ (B) ++ ("d") ++ (B) ++ ("dcfefbeebfadbeefedbfe") ++ (B))
    =
    (("fedffcaaefcc") ++ (B) ++ ("cdbbfadfbfbddbcdcbbacfceda") ++ (B) ++ ("ceeedfffcfaba") ++ (B) ++ ("cdddbbadadcfefbeebfadbeefedbfea"));
constraint
  (("ffecfdfcabcccdbcfcbecefdcbfa") ++ (B) ++ ("aa") ++ (B) ++ ("ceaabfbcbebefbabcbd") ++ (B) ++ ("c") ++ (B) ++ ("df") ++ (B) ++ ("fcfcbec") ++ (B) ++ ("dcbfaefdefde") ++ (B) ++ ("fcdffce"))
    =
    (("ffecfdfc") ++ (B) ++ ("bcccdbcfcbecefdcbf") ++ (B) ++ ("aa") ++ (B) ++ (B) ++ ("ceaabfbcbebefb") ++ (B) ++ ("bcbd") ++ (B) ++ ("c") ++ (B) ++ ("dfafcfcbec") ++ (B) ++ ("dcbfaefdefde") ++ (B) ++ ("fcdffce"));
constraint
  (("db") ++ (B) ++ ("efdbcbeddddfddda") ++ (B) ++ ("c") ++ (B) ++ ("edafddcdcca") ++ (B) ++ ("cc") ++ (B) ++ ("dbfedfcddcddcbeeebacffbfcba") ++ (B) ++ ("eeed") ++ (B) ++ ("fd") ++ (B) ++ ("cbd") ++ (B) ++ ("bafabfc") ++ (B))
    =
    (("db") ++ (B) ++ ("efdbcbeddddfddd") ++ (B) ++ (B) ++ ("c") ++ (B) ++ ("ed") ++ (B) ++ ("fddcdcc") ++ (B) ++ ("acc") ++ (B) ++ ("dbfedfcddcddcbeeebacffbfcb") ++ (B) ++ (B) ++ ("eeed") ++ (B) ++ ("fd") ++ (B) ++ ("cbdab") ++ (B) ++ ("fabfca"));
constraint
  (("dadff") ++ (B) ++ ("febccc") ++ (B) ++ ("beadedfccedbecbeaeefbfcdeeecfbe") ++ (B) ++ ("fbffffbedeffdcaaedebfe") ++ (B) ++ ("eed") ++ (B) ++ ("a") ++ (B) ++ ("ed") ++ (B) ++ ("cceff") ++ (B) ++ ("bb"))
    =
    (("d") ++ (B) ++ ("dffafebcccabeadedfccedbecbe") ++ (B) ++ ("eefbfcdeeecfbe") ++ (B) ++ ("fbffffbedeffdc") ++ (B) ++ (B) ++ ("edebfe") ++ (B) ++ ("eeda") ++ (B) ++ ("aed") ++ (B) ++ ("cceffabb"));
constraint
  (("acdbcdcebf") ++ (B) ++ ("eaaddfecdabdfbcc") ++ (B) ++ ("adaafdae") ++ (B) ++ ("cd") ++ (B) ++ ("ff") ++ (B) ++ (B) ++ ("e") ++ (B) ++ ("cedbddc") ++ (B) ++ (B) ++ ("cdfc") ++ (B) ++ ("ed") ++ (B) ++ ("badedfebbbb") ++ (B) ++ ("feffccaad") ++ (B))
    =
    (("acdbcdcebf") ++ (B) ++ ("ea") ++ (B) ++ ("ddfecdabdfbccaadaafd") ++ (B) ++ ("e") ++ (B) ++ ("cdaff") ++ (B) ++ ("aeacedbddcaacdfcaedabadedfebbbbafeffcc") ++ (B) ++ ("ad") ++ (B));
constraint
  (("fffefebadcbdbcbeceaadecd") ++ (B) ++ ("fd") ++ (B) ++ ("decfffebbbbbdbf") ++ (B) ++ ("f") ++ (B) ++ (B) ++ ("ccbfcefbbafded") ++ (B) ++ ("dfdccfdedceaccdbafdbcce"))
    =
    (("fffefeb") ++ (B) ++ ("dcbdbcbece") ++ (B) ++ (B) ++ ("decd") ++ (B) ++ ("fd") ++ (B) ++ ("decfffebbbbbdbf") ++ (B) ++ ("f") ++ (B) ++ (B) ++ ("ccbfcefbbafded") ++ (B) ++ ("dfdccfdedceaccdb") ++ (B) ++ ("fdbcce"));
constraint
  (("ffacdcbcf") ++ (B) ++ ("d") ++ (B) ++ ("ebdbe") ++ (B) ++ ("dcde") ++ (B) ++ ("dccedcf") ++ (B) ++ ("ddbcdceadfdfedcfbadaeebfedefbfbcafebefd") ++ (B) ++ ("ccadeedbcecaba"))
    =
    (("ffacdcbcfadaebdbeadcde") ++ (B) ++ ("dccedcfaddbcdce") ++ (B) ++ ("dfdfedcfb") ++ (B) ++ ("daeebfedefbfbcafebefd") ++ (B) ++ ("cc") ++ (B) ++ ("deedbcec") ++ (B) ++ ("b") ++ (B));
constraint
  (("adfbbd") ++ (B) ++ ("bd") ++ (B) ++ ("fecfca") ++ (B) ++ ("dedc") ++ (B) ++ (B) ++ (B) ++ ("ebcbefedfbdefbddefdafccbefbdebbee") ++ (B) ++ ("cdd") ++ (B) ++ ("bdba") ++ (B) ++ ("bbaecddccedf") ++ (B) ++ ("abcef"))
    =
    (("adfbbdabd") ++ (B) ++ ("fecfcaadedc") ++ (B) ++ ("a") ++ (B) ++ ("ebcbefedfbdefbddefdafccbefbdebbeeacdd") ++ (B) ++ ("bdb") ++ (B) ++ ("abb") ++ (B) ++ ("ecddccedf") ++ (B) ++ (B) ++ ("bcef"));
constraint
  (("fbddfceb") ++ (B) ++ ("deaedefbdaeaacfecfddfdabbdfbc") ++ (B) ++ ("bed") ++ (B) ++ ("eececfb") ++ (B) ++ ("cccbcccc") ++ (B) ++ ("ecfdcdc") ++ (B) ++ ("c") ++ (B) ++ ("fefbddffb") ++ (B) ++ ("ffeee"))
    =
    (("fbddfceb") ++ (B) ++ ("de") ++ (B) ++ ("edefbdaea") ++ (B) ++ ("cfecfddfdabbdfbc") ++ (B) ++ ("bedaeececfb") ++ (B) ++ ("cccbccccaecfdcdcacafefbddffbaffeee"));
constraint
  (("cbacdbbbfbcdeabbbbeaacebfad") ++ (B) ++ ("caebfccea") ++ (B) ++ ("e") ++ (B) ++ ("dddbebfa") ++ (B) ++ ("becdefdfbdcbccf") ++ (B) ++ ("ffecdfcddcdfeedefbea"))
    =
    (("cb") ++ (B) ++ ("cdbbbfbcdeabbbbe") ++ (B) ++ ("acebfad") ++ (B) ++ ("c") ++ (B) ++ ("ebfccea") ++ (B) ++ ("e") ++ (B) ++ ("dddbebf") ++ (B) ++ ("abecdefdfbdcbccf") ++ (B) ++ ("ffecdfcddcdfeedefbea"));
constraint
  (("cfbadebdebef") ++ (B) ++ ("bfbcbecbeadbfceedbfbcfdffcdccdaafb") ++ (B) ++ ("acfdcddbeee") ++ (B) ++ ("d") ++ (B) ++ ("ac") ++ (B) ++ ("bbeffccab") ++ (B) ++ ("efdddfeddd"))
    =
    (("cfbadebdebefabfbcbecbe") ++ (B) ++ ("dbfceedbfbcfdffcdccd") ++ (B) ++ ("afba") ++ (B) ++ ("cfdcddbeee") ++ (B) ++ ("daacabbeffcc") ++ (B) ++ ("b") ++ (B) ++ ("efdddfeddd"));
constraint
  (("d") ++ (B) ++ ("deedebbe") ++ (B) ++ ("fdcbbccdeef") ++ (B) ++ ("cbfbfcdfbef") ++ (B) ++ ("edbbd") ++ (B) ++ ("ffeaedbb") ++ (B) ++ ("bcbbefdeebdab") ++ (B) ++ ("aebabcbfec") ++ (B) ++ ("eedadececd"))
    =
    (("d") ++ (B) ++ ("deedebbeafdcbbccdeef") ++ (B) ++ ("cbfbfcdfbef") ++ (B) ++ ("edbbd") ++ (B) ++ ("ffeaedbb") ++ (B) ++ ("bcbbefdeebdabaaeb") ++ (B) ++ ("bcbfec") ++ (B) ++ ("eed") ++ (B) ++ ("dececd"));
constraint
  ((B) ++ ("fcbccdaebcea") ++ (B) ++ ("fbabdcbcbcfdebbecccbcccababbefbb") ++ (B) ++ ("bfedfbccfde") ++ (B) ++ ("df") ++ (B) ++ ("fddaebecd") ++ (B) ++ ("b") ++ (B) ++ (B) ++ ("eddebfdcdf"))
    =
    (("afcbccdaebceaafb") ++ (B) ++ ("bdcbcbcfdebbecccbccc") ++ (B) ++ ("b") ++ (B) ++ ("bbefbb") ++ (B) ++ ("bfedfbccfdeadf") ++ (B) ++ ("fdd") ++ (B) ++ ("ebecdabaaeddebfdcdf"));
constraint
  (("dffd") ++ (B) ++ ("fc") ++ (B) ++ ("effccdcfbedcbcbfecffd") ++ (B) ++ ("cbd") ++ (B) ++ ("cfccdde") ++ (B) ++ ("ddabebaebddfe") ++ (B) ++ ("eb") ++ (B) ++ ("ffbdbffccdbdcb") ++ (B) ++ ("ffeebaffccd"))
    =
    (("dffd") ++ (B) ++ ("fc") ++ (B) ++ ("effccdcfbedcbcbfecffdacbdacfccddeadd") ++ (B) ++ ("bebaebddfeaeb") ++ (B) ++ ("ffbdbffccdbdcbaffeebaffccd"));
constraint
  (("f") ++ (B) ++ ("ffafdffefefacfcbeccdfeaac") ++ (B) ++ ("fbccffcdccfcbccfe") ++ (B) ++ ("dfdecbceb") ++ (B) ++ ("dcaefedebd") ++ (B) ++ ("ddbeccfaacefbaccab"))
    =
    (("f") ++ (B) ++ ("ff") ++ (B) ++ ("fdffefef") ++ (B) ++ ("cfcbeccdfeaac") ++ (B) ++ ("fbccffcdccfcbccfe") ++ (B) ++ ("dfdecbcebadc") ++ (B) ++ ("efedebd") ++ (B) ++ ("ddbeccf") ++ (B) ++ ("acefbaccab"));
constraint
  (("ffbcfdbd") ++ (B) ++ (B) ++ ("ebddaeabdbbddefdfdabce") ++ (B) ++ ("dddbfcefcfaefefaed") ++ (B) ++ ("fffa") ++ (B) ++ ("fcfcdaab") ++ (B) ++ ("d") ++ (B) ++ ("cece") ++ (B) ++ ("addfae") ++ (B) ++ ("dcdef"))
    =
    (("ffbcfdbd") ++ (B) ++ ("aebddae") ++ (B) ++ ("bdbbddefdfdabceadddbfcefcfaefefaed") ++ (B) ++ ("fffa") ++ (B) ++ ("fcfcdaabad") ++ (B) ++ ("cece") ++ (B) ++ (B) ++ ("ddf") ++ (B) ++ ("eadcdef"));
constraint
  (("adecccdbdaebb") ++ (B) ++ ("ebce") ++ (B) ++ ("fdfdcdb") ++ (B) ++ ("bfcdbbbfcfffbddcdd") ++ (B) ++ ("acfddfaeaaaef") ++ (B) ++ (B) ++ ("bdeefefefdcddedfcaefaeba"))
    =
    ((B) ++ ("decccdbd") ++ (B) ++ ("ebb") ++ (B) ++ ("ebceafdfdcdb") ++ (B) ++ ("bfcdbbbfcfffbddcddaacfddfaeaaaef") ++ (B) ++ (B) ++ ("bdeefefefdcddedfcaefaeba"));
constraint
  (("ace") ++ (B) ++ ("dfde") ++ (B) ++ ("fee") ++ (B) ++ ("aedfaffecfeddedbcccbcae") ++ (B) ++ ("ffdfbecdadddacdddecfcabf") ++ (B) ++ ("fabbcbccfcefecfecfdbbef"))
    =
    ((B) ++ ("ce") ++ (B) ++ ("dfde") ++ (B) ++ ("fee") ++ (B) ++ (B) ++ ("edf") ++ (B) ++ ("ffecfeddedbcccbcaeaffdfbecdadddacdddecfcabf") ++ (B) ++ ("f") ++ (B) ++ ("bbcbccfcefecfecfdbbef"));
constraint
  (("fbcdbebdbee") ++ (B) ++ ("affcdfefb") ++ (B) ++ ("bcccffececdcedefbcbccbeebdffabfe") ++ (B) ++ (B) ++ ("cdcdfededbfdfffdfca") ++ (B) ++ ("b") ++ (B) ++ (B) ++ ("b") ++ (B) ++ ("c") ++ (B) ++ ("c") ++ (B))
    =
    (("fbcdbebdbee") ++ (B) ++ ("affcdfefb") ++ (B) ++ ("bcccffececdcedefbcbccbeebdff") ++ (B) ++ ("bfe") ++ (B) ++ ("acdcdfededbfdfffdfcaaba") ++ (B) ++ ("bac") ++ (B) ++ ("ca"));
constraint
  (("ddfbfcddeeccdefcfbdbde") ++ (B) ++ ("dab") ++ (B) ++ ("bedbe") ++ (B) ++ ("becfeffefcecfcdfdddcd") ++ (B) ++ ("ec") ++ (B) ++ ("ead") ++ (B) ++ ("fdfaccacedeaffcbdfafa") ++ (B) ++ ("f"))
    =
    (("ddfbfcddeeccdefcfbdbde") ++ (B) ++ ("d") ++ (B) ++ ("b") ++ (B) ++ ("bedbe") ++ (B) ++ ("becfeffefcecfcdfdddcdaec") ++ (B) ++ ("e") ++ (B) ++ ("d") ++ (B) ++ ("fdfacc") ++ (B) ++ ("cedeaffcbdfaf") ++ (B) ++ (B) ++ ("f"));
constraint
  ((B) ++ ("edede") ++ (B) ++ ("dca") ++ (B) ++ ("fef") ++ (B) ++ ("aecfededdbbebdefefe") ++ (B) ++ ("debcdecbfeccedbeedfcba") ++ (B) ++ ("dbeaeebc") ++ (B) ++ ("ddefccead") ++ (B) ++ (B) ++ ("cff") ++ (B) ++ ("bbc"))
    =
    ((B) ++ ("edede") ++ (B) ++ ("dca") ++ (B) ++ ("fefaaecfededdbbebdefefe") ++ (B) ++ ("debcdecbfeccedbeedfcbaadbe") ++ (B) ++ ("eebcaddefcce") ++ (B) ++ ("d") ++ (B) ++ (B) ++ ("cffabbc"));
constraint
  (("a") ++ (B) ++ ("fbcceddceddbbbdeeccdcf") ++ (B) ++ ("ddfaaaeccb") ++ (B) ++ ("aebefccebefeeddedeeddffebdccfeacdcdabeefcbfeaebc") ++ (B))
    =
    (("aafbcceddceddbbbdeeccdcf") ++ (B) ++ ("ddfaaaeccb") ++ (B) ++ ("aebefccebefeeddedeeddffebdccfe") ++ (B) ++ ("cdcdabeefcbfeaebca"));
constraint
  (("e") ++ (B) ++ ("defffdecbbbbcacdabffcbfbccbcbfccffe") ++ (B) ++ ("dcedbcdbeffbcebf") ++ (B) ++ ("bfa") ++ (B) ++ ("bffdddeb") ++ (B) ++ ("cfbffe") ++ (B) ++ ("cdfbcbffaa"))
    =
    (("e") ++ (B) ++ ("defffdecbbbbcacd") ++ (B) ++ ("bffcbfbccbcbfccffeadcedbcdbeffbcebf") ++ (B) ++ ("bfa") ++ (B) ++ ("bffdddeb") ++ (B) ++ ("cfbffe") ++ (B) ++ ("cdfbcbffaa"));
constraint
  (("ebfedcadccfdcffdcfafcfeddeadefefdafafbdffb") ++ (B) ++ ("fdcbbe") ++ (B) ++ ("dcfef") ++ (B) ++ ("dfcfe") ++ (B) ++ (B) ++ ("ffabaece") ++ (B) ++ ("bfeaeabbdfaf") ++ (B))
    =
    (("ebfedc") ++ (B) ++ ("dccfdcffdcf") ++ (B) ++ ("fcfedde") ++ (B) ++ ("defefd") ++ (B) ++ ("fafbdffbafdcbbe") ++ (B) ++ ("dcfef") ++ (B) ++ ("dfcfeaaffab") ++ (B) ++ ("eceabfe") ++ (B) ++ ("e") ++ (B) ++ ("bbdfafa"));
constraint
  (("dfeefc") ++ (B) ++ ("e") ++ (B) ++ ("fbfb") ++ (B) ++ ("edeeddfdfe") ++ (B) ++ (B) ++ ("adbddeecbdefbeecdbcfebaa") ++ (B) ++ ("daadffefecab") ++ (B) ++ ("fcfdddbbfe") ++ (B) ++ ("dfce") ++ (B) ++ (B) ++ ("ebcd"))
    =
    (("dfeefc") ++ (B) ++ ("eafbfb") ++ (B) ++ ("edeeddfdfea") ++ (B) ++ ("adbddeecbdefbeecdbcfeb") ++ (B) ++ (B) ++ ("adaadffefec") ++ (B) ++ ("bafcfdddbbfe") ++ (B) ++ ("dfceaaebcd"));
constraint
  (("ebccaeb") ++ (B) ++ ("fefddddeddfbbd") ++ (B) ++ ("edcffebbccabbeedeeceecbecfefbcfdbdedfffdbabfb") ++ (B) ++ ("eaaf") ++ (B) ++ ("bffb") ++ (B) ++ ("ebb") ++ (B) ++ ("c") ++ (B))
    =
    (("ebcc") ++ (B) ++ ("eb") ++ (B) ++ ("fefddddeddfbbd") ++ (B) ++ ("edcffebbcc") ++ (B) ++ ("bbeedeeceecbecfefbcfdbdedfffdb") ++ (B) ++ ("bfbae") ++ (B) ++ (B) ++ ("fabffb") ++ (B) ++ ("ebbac") ++ (B));
constraint
  (("bebac") ++ (B) ++ ("cfdfffccbce") ++ (B) ++ ("d") ++ (B) ++ ("acbdfbdeccafcbbebededfdbcbffbdfeabcebbbbbeecfdceeebeebaddacfceccc"))
    =
    (("beb") ++ (B) ++ ("c") ++ (B) ++ ("cfdfffccbce") ++ (B) ++ ("daacbdfbdeccafcbbebededfdbcbffbdfeabcebbbbbeecfdceeebeeb") ++ (B) ++ ("dd") ++ (B) ++ ("cfceccc"));
constraint
  (("ebdbcefaffbecdf") ++ (B) ++ ("c") ++ (B) ++ ("ebbdfabccaef") ++ (B) ++ ("b") ++ (B) ++ ("ece") ++ (B) ++ ("bacdeefeeeebff") ++ (B) ++ ("cdafc") ++ (B) ++ ("ecdbcbeed") ++ (B) ++ ("dac") ++ (B) ++ ("accfefedcebbc"))
    =
    (("ebdbcefaffbecdf") ++ (B) ++ ("caebbdf") ++ (B) ++ ("bcc") ++ (B) ++ ("ef") ++ (B) ++ ("baeceab") ++ (B) ++ ("cdeefeeeebffacdafcaecdbcbeedad") ++ (B) ++ ("caaccfefedcebbc"));
constraint
  (("afc") ++ (B) ++ ("bafcdadbffdfdfbcaeffdcbaccedbbfdffacd") ++ (B) ++ ("abe") ++ (B) ++ ("efdddcfdeacf") ++ (B) ++ ("edfbeceebafeebd") ++ (B) ++ ("bcdeeee") ++ (B) ++ ("fe"))
    =
    (("afc") ++ (B) ++ ("bafcdadbffdfdfbcaeffdcbaccedbbfdff") ++ (B) ++ ("cd") ++ (B) ++ ("abe") ++ (B) ++ ("efdddcfde") ++ (B) ++ ("cf") ++ (B) ++ ("edfbeceeb") ++ (B) ++ ("feebdabcdeeee") ++ (B) ++ ("fe"));
constraint
  (("a") ++ (B) ++ ("eeedafbbea") ++ (B) ++ ("cfcdbbecebfefedbedccbfdbdddcffffcfdadcec") ++ (B) ++ ("afccbed") ++ (B) ++ ("fdecdfc") ++ (B) ++ ("ccbfadaecdfcffe"))
    =
    ((B) ++ (B) ++ ("eeedafbbea") ++ (B) ++ ("cfcdbbecebfefedbedccbfdbdddcffffcfd") ++ (B) ++ ("dceca") ++ (B) ++ ("fccbed") ++ (B) ++ ("fdecdfcaccbfad") ++ (B) ++ ("ecdfcffe"));
constraint
  (("fefddeadcfabad") ++ (B) ++ ("cbcddabacecfcc") ++ (B) ++ ("cedcebcfdaecdededfefcccbdfbfdcec") ++ (B) ++ ("fbabcbebebbbfbdeacdffd"))
    =
    (("fefddeadcfab") ++ (B) ++ ("dacbcddabacecfcc") ++ (B) ++ ("cedcebcfdaecdededfefcccbdfbfdcecafbabcbebebbbfbdeacdffd"));
constraint
  (("decfbedede") ++ (B) ++ ("ffc") ++ (B) ++ ("dbcbdbafafcaeecfcfbcfeefdbfafcddeffcd") ++ (B) ++ ("afccaddcefeeecdfdba") ++ (B) ++ ("ccefcbdfbddb"))
    =
    (("decfbededeaffcadbcbdb") ++ (B) ++ ("f") ++ (B) ++ ("fcaeecfcfbcfeefdbfafcddeffcd") ++ (B) ++ (B) ++ ("fccaddcefeeecdfdb") ++ (B) ++ (B) ++ ("ccefcbdfbddb"));
constraint
  (("ffddccbebfedecccdcbcddcbdcfdddebedcadbfbbfeedc") ++ (B) ++ ("d") ++ (B) ++ (B) ++ ("bccdabcceef") ++ (B) ++ ("bcbbbce") ++ (B) ++ ("efadfebcededccd"))
    =
    (("ffddccbebfedecccdcbcddcbdcfdddebedc") ++ (B) ++ ("dbfbbfeedcad") ++ (B) ++ (B) ++ ("bccd") ++ (B) ++ ("bcceefabcbbbceaefadfebcededccd"));
constraint
  (("accddccc") ++ (B) ++ ("cddefbaedcddfdddabced") ++ (B) ++ (B) ++ ("dfdbaefebccefbbbfc") ++ (B) ++ ("becceeeffdd") ++ (B) ++ ("cede") ++ (B) ++ ("bfddeaeffffffca") ++ (B) ++ ("f"))
    =
    (("accddccc") ++ (B) ++ ("cddefb") ++ (B) ++ ("edcddfdddabceda") ++ (B) ++ ("dfdb") ++ (B) ++ ("efebccefbbbfc") ++ (B) ++ ("becceeeffddacedeabfddeaeffffffc") ++ (B) ++ ("af"));
constraint
  (("eedaebfebbed") ++ (B) ++ (B) ++ ("fafbdbede") ++ (B) ++ ("cabefceccddecebdfdbebfdbcacbfbfbfecddaaacfebeefcffafbfceecefb"))
    =
    (("eedaebfebbed") ++ (B) ++ (B) ++ ("f") ++ (B) ++ ("fbdbede") ++ (B) ++ ("cabefceccddecebdfdbebfdbcacbfbfbfecddaa") ++ (B) ++ ("cfebeefcff") ++ (B) ++ ("fbfceecefb"));
constraint
  (("dccdbcbbeeef") ++ (B) ++ ("aebdbcaccbfc") ++ (B) ++ ("fab") ++ (B) ++ ("feefcaddfbba") ++ (B) ++ ("f") ++ (B) ++ ("fb") ++ (B) ++ ("edcaedfdebbade") ++ (B) ++ ("dcc") ++ (B) ++ ("eabfbebbfcea") ++ (B) ++ ("cbfed"))
    =
    (("dccdbcbbeeef") ++ (B) ++ (B) ++ ("ebdbcaccbfc") ++ (B) ++ ("f") ++ (B) ++ ("bafeefc") ++ (B) ++ ("ddfbba") ++ (B) ++ ("f") ++ (B) ++ ("fb") ++ (B) ++ ("edc") ++ (B) ++ ("edfdebbadeadcc") ++ (B) ++ ("eabfbebbfce") ++ (B) ++ ("acbfed"));
constraint
  (("daceceaeabedecdfe") ++ (B) ++ (B) ++ ("eccedfefde") ++ (B) ++ ("cdedefecdeecee") ++ (B) ++ ("dcbceddeededfdcddcefedeafce") ++ (B) ++ ("cfdccddcae") ++ (B) ++ ("c"))
    =
    (("dacece") ++ (B) ++ ("eabedecdfea") ++ (B) ++ ("eccedfefde") ++ (B) ++ ("cdedefecdeeceeadcbceddeededfdcddcefedeafce") ++ (B) ++ ("cfdccddcae") ++ (B) ++ ("c"));
constraint
  (("ceeceffcadbeccd") ++ (B) ++ ("cddbf") ++ (B) ++ ("bb") ++ (B) ++ ("fcde") ++ (B) ++ ("cdd") ++ (B) ++ ("adbfedefbbbc") ++ (B) ++ ("faffff") ++ (B) ++ ("ebacffdebfcabbbbeecffafddab") ++ (B) ++ ("cac"))
    =
    (("ceeceffc") ++ (B) ++ ("dbeccd") ++ (B) ++ ("cddbfabb") ++ (B) ++ ("fcde") ++ (B) ++ ("cdd") ++ (B) ++ (B) ++ ("dbfedefbbbc") ++ (B) ++ ("f") ++ (B) ++ ("ffff") ++ (B) ++ ("eb") ++ (B) ++ ("cffdebfcabbbbeecffafddabac") ++ (B) ++ ("c"));
constraint
  (("ffaedf") ++ (B) ++ ("aeba") ++ (B) ++ (B) ++ (B) ++ ("adddfbcb") ++ (B) ++ ("fcecbcb") ++ (B) ++ ("eeabcacdebfdedfabf") ++ (B) ++ ("cfdbeeeceefe") ++ (B) ++ ("cacdedaaaede") ++ (B) ++ ("bdbbb") ++ (B) ++ (B) ++ ("be"))
    =
    (("ff") ++ (B) ++ ("edfa") ++ (B) ++ ("ebaaaa") ++ (B) ++ ("dddfbcb") ++ (B) ++ ("fcecbcb") ++ (B) ++ ("eeabc") ++ (B) ++ ("cdebfdedf") ++ (B) ++ ("bfacfdbeeeceefe") ++ (B) ++ ("c") ++ (B) ++ ("cdedaa") ++ (B) ++ ("ede") ++ (B) ++ ("bdbbba") ++ (B) ++ ("be"));
constraint
  ((B) ++ ("feefdabfc") ++ (B) ++ ("aceeebedaeaabddfddffcbacddfb") ++ (B) ++ (B) ++ ("ecffddcccbebeaafbebfeffc") ++ (B) ++ ("ed") ++ (B) ++ ("fddbbdbcedebb") ++ (B) ++ ("dc"))
    =
    (("afeefd") ++ (B) ++ ("bfc") ++ (B) ++ ("aceeebed") ++ (B) ++ ("e") ++ (B) ++ (B) ++ ("bddfddffcbacddfb") ++ (B) ++ (B) ++ ("ecffddcccbebe") ++ (B) ++ ("afbebfeffcaed") ++ (B) ++ ("fddbbdbcedebbadc"));
constraint
  (("decfcbbfedeefbfabf") ++ (B) ++ (B) ++ ("ddcccc") ++ (B) ++ ("abdcdaddccdeabcaee") ++ (B) ++ ("febbc") ++ (B) ++ ("ccbfdeeacdbfffdcbdcbfbc") ++ (B) ++ ("dcfbcbefa"))
    =
    (("decfcbbfedeefbf") ++ (B) ++ ("bfa") ++ (B) ++ ("ddcccc") ++ (B) ++ (B) ++ ("bdcd") ++ (B) ++ ("ddccdeabc") ++ (B) ++ ("ee") ++ (B) ++ ("febbcaccbfdeeacdbfffdcbdcbfbcadcfbcbefa"));
constraint
  (("dffaffedcda") ++ (B) ++ ("fbacfbdddabafc") ++ (B) ++ (B) ++ ("d") ++ (B) ++ ("c") ++ (B) ++ ("bfadf") ++ (B) ++ ("dccdfbdfcfbf") ++ (B) ++ ("cedfcdee") ++ (B) ++ (B) ++ ("ecedce") ++ (B) ++ ("ee") ++ (B) ++ ("ebbebccee") ++ (B) ++ ("ffdb"))
    =
    (("dff") ++ (B) ++ ("ffedcdaafb") ++ (B) ++ ("cfbddd") ++ (B) ++ ("bafcaadac") ++ (B) ++ ("bf") ++ (B) ++ ("dfadccdfbdfcfbf") ++ (B) ++ ("cedfcdee") ++ (B) ++ ("aecedceaeeaebbebcceeaffdb"));
constraint
  (("fbfdecefc") ++ (B) ++ ("dfabcb") ++ (B) ++ ("eabfcfeebdffacbbceceaee") ++ (B) ++ ("dfdffddba") ++ (B) ++ ("ecdacbbda") ++ (B) ++ ("cede") ++ (B) ++ ("bbeedcd") ++ (B) ++ ("a") ++ (B) ++ ("eeefbbcfe"))
    =
    (("fbfdecefc") ++ (B) ++ ("dfabcb") ++ (B) ++ ("eabfcfeebdff") ++ (B) ++ ("cbbcece") ++ (B) ++ ("ee") ++ (B) ++ ("dfdffddba") ++ (B) ++ ("ecdacbbd") ++ (B) ++ (B) ++ ("cedeabbeedcdaa") ++ (B) ++ ("eeefbbcfe"));
constraint
  (("cdfeaec") ++ (B) ++ ("eaefcbefad") ++ (B) ++ ("dadeefccbfdaecfdbebcfc") ++ (B) ++ ("fdbabfae") ++ (B) ++ ("cddbebceebbadcacfacecbbcffcdcdffec"))
    =
    (("cdfe") ++ (B) ++ ("ec") ++ (B) ++ ("eaefcbefad") ++ (B) ++ ("dadeefccbfdaecfdbebcfc") ++ (B) ++ ("fdbabfaeacddbebceebbadcacf") ++ (B) ++ ("cecbbcffcdcdffec"));
constraint
  (("ccb") ++ (B) ++ ("fbcedfbebaefbbdf") ++ (B) ++ (B) ++ ("bdcecfccef") ++ (B) ++ ("cbdfafefffbedfdecdaed") ++ (B) ++ ("ceecfbeaec") ++ (B) ++ ("cfeccbfdbcfbbcdbfbd"))
    =
    (("ccbafbcedfbeb") ++ (B) ++ ("efbbdfa") ++ (B) ++ ("bdcecfccef") ++ (B) ++ ("cbdf") ++ (B) ++ ("fefffbedfdecd") ++ (B) ++ ("edaceecfbeaecacfeccbfdbcfbbcdbfbd"));
constraint
  (("ffedfdfefd") ++ (B) ++ ("ffae") ++ (B) ++ ("ccbce") ++ (B) ++ ("aeabbffebedc") ++ (B) ++ ("aedeafbbbffbbefebbbdfdeedbeff") ++ (B) ++ ("aeeeeffdcfebfcbfdbbb"))
    =
    (("ffedfdfefd") ++ (B) ++ ("ff") ++ (B) ++ ("e") ++ (B) ++ ("ccbce") ++ (B) ++ (B) ++ ("eabbffebedc") ++ (B) ++ (B) ++ ("ede") ++ (B) ++ ("fbbbffbbefebbbdfdeedbeffa") ++ (B) ++ ("eeeeffdcfebfcbfdbbb"));
constraint
  (("d") ++ (B) ++ ("fcefcabbbddf") ++ (B) ++ ("cbacdefdb") ++ (B) ++ ("edbbebe") ++ (B) ++ ("eedbbcdb") ++ (B) ++ ("baecebbdcadfcefffe") ++ (B) ++ (B) ++ ("efdeedffadbbe") ++ (B) ++ ("bcefbfdfe"))
    =
    (("dafcefcabbbddfacb") ++ (B) ++ ("cdefdb") ++ (B) ++ ("edbbebe") ++ (B) ++ ("eedbbcdb") ++ (B) ++ ("baecebbdc") ++ (B) ++ ("dfcefffe") ++ (B) ++ ("aefdeedff") ++ (B) ++ ("dbbeabcefbfdfe"));
constraint
  (("fdbafdecfccdccfb") ++ (B) ++ ("ffbf") ++ (B) ++ ("acdececaedcdbfebceabccecfbcecb") ++ (B) ++ (B) ++ (B) ++ ("badecc") ++ (B) ++ ("fdfcfcacbafddedffcfdefb"))
    =
    (("fdb") ++ (B) ++ ("fdecfccdccfb") ++ (B) ++ ("ffbf") ++ (B) ++ (B) ++ ("cdececaedcdbfebce") ++ (B) ++ ("bccecfbcecba") ++ (B) ++ ("ab") ++ (B) ++ ("decc") ++ (B) ++ ("fdfcfc") ++ (B) ++ ("cb") ++ (B) ++ ("fddedffcfdefb"));
constraint
  (("ddecabbfc") ++ (B) ++ ("cdba") ++ (B) ++ ("aadfdacfbdbdeffbfebaeaecce") ++ (B) ++ ("faaaddcbdfebbeffecdbddbdde") ++ (B) ++ ("fcc") ++ (B) ++ ("cbddbeead") ++ (B) ++ ("cf"))
    =
    (("ddecabbfcacdb") ++ (B) ++ (B) ++ (B) ++ (B) ++ ("dfd") ++ (B) ++ ("cfbdbdeffbfeb") ++ (B) ++ ("eaecceaf") ++ (B) ++ (B) ++ ("addcbdfebbeffecdbddbddeafccacbddbeeadacf"));
constraint
  (("d") ++ (B) ++ (B) ++ ("d") ++ (B) ++ ("dfcd") ++ (B) ++ ("fdcbefdfaeb") ++ (B) ++ ("ce") ++ (B) ++ ("dfdfccfdf") ++ (B) ++ (B) ++ ("ccb") ++ (B) ++ ("ebcdedcfefbfbbeffe") ++ (B) ++ ("ec") ++ (B) ++ ("ebcbc") ++ (B) ++ ("ffdebdbbb") ++ (B) ++ ("bd") ++ (B) ++ ("dddb"))
    =
    (("d") ++ (B) ++ ("adadfcd") ++ (B) ++ ("fdcbefdfaebace") ++ (B) ++ ("dfdfccfdf") ++ (B) ++ ("accb") ++ (B) ++ ("ebcdedcfefbfbbeffeaecaebcbcaffdebdbbb") ++ (B) ++ ("bd") ++ (B) ++ ("dddb"));
constraint
  (("bffc") ++ (B) ++ (B) ++ ("bf") ++ (B) ++ ("bcbccf") ++ (B) ++ ("eceec") ++ (B) ++ ("dfeafebe") ++ (B) ++ ("ed") ++ (B) ++ ("b") ++ (B) ++ ("bdbcdaedddddfecbdfbcfeba") ++ (B) ++ ("ccbdfeacddeebcbfcfdbdece"))
    =
    (("bffcaabf") ++ (B) ++ ("bcbccfaeceec") ++ (B) ++ ("dfeafebe") ++ (B) ++ ("edababdbcdaedddddfecbdfbcfeb") ++ (B) ++ ("accbdfe") ++ (B) ++ ("cddeebcbfcfdbdece"));
constraint
  (("ec") ++ (B) ++ ("dbdeddfeeefabc") ++ (B) ++ ("eddfbdecddedcabeeeddfffefcfc") ++ (B) ++ ("abddeeaddabfebffffbecbe") ++ (B) ++ ("fefceffdddcb") ++ (B) ++ ("e"))
    =
    (("ecadbdeddfeeefabc") ++ (B) ++ ("eddfbdecddedc") ++ (B) ++ ("beeeddfffefcfc") ++ (B) ++ ("abddee") ++ (B) ++ ("ddabfebffffbecbe") ++ (B) ++ ("fefceffdddcb") ++ (B) ++ ("e"));
constraint
  (("e") ++ (B) ++ ("ecfbffcc") ++ (B) ++ ("beaccbcddfbfbdf") ++ (B) ++ ("addabfbe") ++ (B) ++ ("dcbff") ++ (B) ++ ("eebeffdfaadddd") ++ (B) ++ ("aadcdaffcfc") ++ (B) ++ (B) ++ ("be") ++ (B) ++ ("ecdcdfcbabbe"))
    =
    (("e") ++ (B) ++ ("ecfbffccabe") ++ (B) ++ ("ccbcddfbfbdf") ++ (B) ++ ("addabfbe") ++ (B) ++ ("dcbff") ++ (B) ++ ("eebeffdfa") ++ (B) ++ ("dddd") ++ (B) ++ (B) ++ ("adcdaffcfca") ++ (B) ++ ("beaecdcdfcb") ++ (B) ++ ("bbe"));
constraint
  (("dcfdfcedccaebcfacdfefcbdeb") ++ (B) ++ ("dc") ++ (B) ++ ("edccbf") ++ (B) ++ ("cb") ++ (B) ++ ("fde") ++ (B) ++ ("bcbbdfbbeaeffbed") ++ (B) ++ ("fdcadfbcfcb") ++ (B) ++ ("ecfcecbabacb"))
    =
    (("dcfdfcedcc") ++ (B) ++ ("ebcf") ++ (B) ++ ("cdfefcbdebadc") ++ (B) ++ ("edccbfacb") ++ (B) ++ ("fde") ++ (B) ++ ("bcbbdfbbeaeffbedafdcadfbcfcb") ++ (B) ++ ("ecfcecbabacb"));
constraint
  (("ddb") ++ (B) ++ ("db") ++ (B) ++ ("eadf") ++ (B) ++ ("fefdefbfccafd") ++ (B) ++ (B) ++ ("cebfcdfadbc") ++ (B) ++ ("dc") ++ (B) ++ ("abfdfecaafd") ++ (B) ++ ("dbdcceaafdbcefb") ++ (B) ++ ("ecfcb") ++ (B) ++ ("eef") ++ (B) ++ ("eddbe"))
    =
    (("ddb") ++ (B) ++ ("dbaeadf") ++ (B) ++ ("fefdefbfcc") ++ (B) ++ ("fda") ++ (B) ++ ("cebfcdf") ++ (B) ++ ("dbc") ++ (B) ++ ("dc") ++ (B) ++ ("abfdfec") ++ (B) ++ ("afdadbdcceaafdbcefb") ++ (B) ++ ("ecfcbaeef") ++ (B) ++ ("eddbe"));
constraint
  (("bcf") ++ (B) ++ ("dbcff") ++ (B) ++ ("abebcfc") ++ (B) ++ ("fddeecbeabffe") ++ (B) ++ (B) ++ ("accebdef") ++ (B) ++ ("fa") ++ (B) ++ ("fecabbaf") ++ (B) ++ ("acaaea") ++ (B) ++ ("cbbdbbbbccffedfbdffbbecd"))
    =
    (("bcfadbcff") ++ (B) ++ (B) ++ ("bebcfcafddeecbe") ++ (B) ++ ("bffea") ++ (B) ++ ("accebdefaf") ++ (B) ++ ("afecabbafa") ++ (B) ++ ("caaeaacbbdbbbbccffedfbdffbbecd"));
constraint
  (("ac") ++ (B) ++ ("ffdf") ++ (B) ++ ("ecaac") ++ (B) ++ ("ebfde") ++ (B) ++ ("da") ++ (B) ++ ("cdccde") ++ (B) ++ ("cfe") ++ (B) ++ ("cdfdafec") ++ (B) ++ ("ccbfabf") ++ (B) ++ ("decdebf") ++ (B) ++ ("aebdbc") ++ (B) ++ ("fdbceaccbdf") ++ (B) ++ ("eddba") ++ (B) ++ ("e"))
    =
    ((B) ++ ("c") ++ (B) ++ ("ffdf") ++ (B) ++ ("ec") ++ (B) ++ (B) ++ ("c") ++ (B) ++ ("ebfdead") ++ (B) ++ (B) ++ ("cdccde") ++ (B) ++ ("cfeacdfd") ++ (B) ++ ("fecaccbf") ++ (B) ++ ("bfadecdebf") ++ (B) ++ (B) ++ ("ebdbcafdbce") ++ (B) ++ ("ccbdfaeddbaae"));
constraint
  ((B) ++ ("bcd") ++ (B) ++ ("affd") ++ (B) ++ (B) ++ ("ccdbceadbefec") ++ (B) ++ ("fbfebd") ++ (B) ++ ("cd") ++ (B) ++ ("feddecdfe") ++ (B) ++ ("fceeceabebbefbbccebbbdc") ++ (B) ++ ("ebbfbfbccdf") ++ (B) ++ ("cbcb"))
    =
    ((B) ++ ("bcdaaffdaaccdbce") ++ (B) ++ ("dbefec") ++ (B) ++ ("fbfebdacdafeddecdfe") ++ (B) ++ ("fceeceabebbefbbccebbbdc") ++ (B) ++ ("ebbfbfbccdfacbcb"));
constraint
  ((B) ++ ("babec") ++ (B) ++ ("fefefdede") ++ (B) ++ ("ccfbdbee") ++ (B) ++ (B) ++ ("be") ++ (B) ++ ("ae") ++ (B) ++ ("cdcfebedbfcdccefbeeccfcdeeaaffbbbccccddf") ++ (B) ++ ("ddddffdcb") ++ (B) ++ ("c"))
    =
    ((B) ++ ("b") ++ (B) ++ ("bec") ++ (B) ++ ("fefefdedeaccfbdbeeaabeaaeacdcfebedbfcdccefbeeccfcdee") ++ (B) ++ (B) ++ ("ffbbbccccddfaddddffdcbac"));
constraint
  (("abdeedadbedcfb") ++ (B) ++ ("cfcaddbfee") ++ (B) ++ ("fecbbdbeacbcd") ++ (B) ++ ("efeccba") ++ (B) ++ ("cddbbadbfe") ++ (B) ++ ("cdffdffdccfdeceecbfdcdbbfb"))
    =
    ((B) ++ ("bdeed") ++ (B) ++ ("dbedcfbacfcaddbfee") ++ (B) ++ ("fecbbdbeacbcdaefeccb") ++ (B) ++ ("acddbbadbfe") ++ (B) ++ ("cdffdffdccfdeceecbfdcdbbfb"));
constraint
  (("eacebfedcbcbafe") ++ (B) ++ ("efbc") ++ (B) ++ (B) ++ ("a") ++ (B) ++ ("edccebb") ++ (B) ++ ("ddefdebdeefaafdaabf") ++ (B) ++ ("dfedddcecbbafacdbefceccdeaebfc") ++ (B) ++ ("ee"))
    =
    (("eacebfedcbcbafe") ++ (B) ++ ("efbcaaa") ++ (B) ++ ("edccebbaddefdebdeef") ++ (B) ++ ("afdaabf") ++ (B) ++ ("dfedddcecbb") ++ (B) ++ ("facdbefceccde") ++ (B) ++ ("ebfcaee"));
constraint
  (("cee") ++ (B) ++ ("edce") ++ (B) ++ ("eec") ++ (B) ++ ("bfebbecdb") ++ (B) ++ ("ddfcfecdaba") ++ (B) ++ ("fbefaddfeeefccdacdfffd") ++ (B) ++ ("addbcccdbc") ++ (B) ++ ("fdbeefcecdb") ++ (B) ++ ("eede"))
    =
    (("ceeaedceaeec") ++ (B) ++ ("bfebbecdbaddfcfecd") ++ (B) ++ ("b") ++ (B) ++ ("afbef") ++ (B) ++ ("ddfeeefccdacdfffda") ++ (B) ++ ("ddbcccdbcafdbeefcecdbaeede"));
constraint
  (("edbd") ++ (B) ++ (B) ++ ("ecbfc") ++ (B) ++ ("dab") ++ (B) ++ ("b") ++ (B) ++ ("fcebcefbff") ++ (B) ++ ("dcebcfdae") ++ (B) ++ ("ffafebeeacbdabcdeecadb") ++ (B) ++ ("bddccd") ++ (B) ++ ("bfebcdaad") ++ (B) ++ ("dcfeee"))
    =
    (("edbdaaecbfc") ++ (B) ++ ("d") ++ (B) ++ ("b") ++ (B) ++ ("b") ++ (B) ++ ("fcebcefbffadcebcfd") ++ (B) ++ ("e") ++ (B) ++ ("ff") ++ (B) ++ ("febeeacbd") ++ (B) ++ ("bcdeec") ++ (B) ++ ("dbabddccdabfebcda") ++ (B) ++ ("dadcfeee"));
constraint
  (("bacbbcccedadddbbcbfdfdbfbcbeebdedec") ++ (B) ++ ("ecc") ++ (B) ++ ("cbadcbbc") ++ (B) ++ ("efdd") ++ (B) ++ (B) ++ ("bcea") ++ (B) ++ (B) ++ ("deacddcffde") ++ (B) ++ ("ccdbcedbfddc"))
    =
    (("b") ++ (B) ++ ("cbbcccedadddbbcbfdfdbfbcbeebdedec") ++ (B) ++ ("eccacb") ++ (B) ++ ("dcbbcaefdd") ++ (B) ++ (B) ++ ("bce") ++ (B) ++ ("a") ++ (B) ++ ("deacddcffdeaccdbcedbfddc"));
constraint
  (("cdecadebdabbb") ++ (B) ++ ("cad") ++ (B) ++ ("cf") ++ (B) ++ ("dddebacdfefcdf") ++ (B) ++ ("bebedcdcacdeccfeecffdbeebcfe") ++ (B) ++ ("cdfeedfeccddecf") ++ (B) ++ ("e") ++ (B) ++ (B) ++ ("c"))
    =
    (("cdec") ++ (B) ++ ("debd") ++ (B) ++ ("bbb") ++ (B) ++ ("c") ++ (B) ++ ("d") ++ (B) ++ ("cfadddeb") ++ (B) ++ ("cdfefcdfabebedcdc") ++ (B) ++ ("cdeccfeecffdbeebcfeacdfeedfeccddecf") ++ (B) ++ ("e") ++ (B) ++ (B) ++ ("c"));
constraint
  (("ffdcbfdcb") ++ (B) ++ ("d") ++ (B) ++ ("b") ++ (B) ++ ("afdbbcfbedabaed") ++ (B) ++ ("eeff") ++ (B) ++ ("e") ++ (B) ++ ("bcafbfcfeecedcadcdecbcedefbbdfcdfbfefebbb") ++ (B) ++ ("efd") ++ (B) ++ ("cb"))
    =
    (("ffdcbfdcbad") ++ (B) ++ ("ba") ++ (B) ++ ("fdbbcfbedab") ++ (B) ++ ("ed") ++ (B) ++ ("eeffae") ++ (B) ++ ("bcafbfcfeecedc") ++ (B) ++ ("dcdecbcedefbbdfcdfbfefebbb") ++ (B) ++ ("efd") ++ (B) ++ ("cb"));
constraint
  (("abfbee") ++ (B) ++ ("abdad") ++ (B) ++ ("abaabbbdffcedfacccbbdcbadccdedbfeacdabdfbdfbcbfeaddb") ++ (B) ++ ("cededd") ++ (B) ++ ("f") ++ (B) ++ (B) ++ ("bdfdcbaab"))
    =
    ((B) ++ ("bfbeeaabdada") ++ (B) ++ ("b") ++ (B) ++ (B) ++ ("bbbdffcedfacccbbdcbadccdedbfeacd") ++ (B) ++ ("bdfbdfbcbfe") ++ (B) ++ ("ddb") ++ (B) ++ ("cededdaf") ++ (B) ++ (B) ++ ("bdfdcba") ++ (B) ++ ("b"));
constraint
  (("aadbfbfbdafcdcfdcf") ++ (B) ++ ("eecfddeffbecdbfbbfbcbcddfba") ++ (B) ++ ("fefddb") ++ (B) ++ ("dceadbbbcecec") ++ (B) ++ ("f") ++ (B) ++ ("aecbbceafebfbde"))
    =
    (("aadbfbfbd") ++ (B) ++ ("fcdcfdcfaeecfddeffbecdbfbbfbcbcddfb") ++ (B) ++ (B) ++ ("fefddbadceadbbbcecec") ++ (B) ++ ("faaecbbceafebfbde"));
constraint
  (("efcccdabcbbbddedbaecbfef") ++ (B) ++ ("a") ++ (B) ++ ("cfcfcfe") ++ (B) ++ ("deaebbffeeeccececfb") ++ (B) ++ ("e") ++ (B) ++ ("cddffdb") ++ (B) ++ ("ecfbbfeaedaaaedcadbc"))
    =
    (("efcccdabcbbbddedb") ++ (B) ++ ("ecbfefaa") ++ (B) ++ ("cfcfcfe") ++ (B) ++ ("de") ++ (B) ++ ("ebbffeeeccececfb") ++ (B) ++ ("eacddffdb") ++ (B) ++ ("ecfbbfeaedaaaedc") ++ (B) ++ ("dbc"));
constraint
  (("deedbebfe") ++ (B) ++ ("fffdbeff") ++ (B) ++ ("b") ++ (B) ++ ("baaddfefffc") ++ (B) ++ ("fcabdaab") ++ (B) ++ ("ebdcbbbcebbcedbdbef") ++ (B) ++ ("dbebecfbeccbdebbb") ++ (B) ++ ("ffffd"))
    =
    (("deedbebfe") ++ (B) ++ ("fffdbeff") ++ (B) ++ ("bab") ++ (B) ++ ("addfefffcafcabd") ++ (B) ++ (B) ++ ("b") ++ (B) ++ ("ebdcbbbcebbcedbdbef") ++ (B) ++ ("dbebecfbeccbdebbb") ++ (B) ++ ("ffffd"));
constraint
  (("ffeadabb") ++ (B) ++ ("bddfeefedafdfadebabceccce") ++ (B) ++ ("bacfbfdcffc") ++ (B) ++ ("bdeaeacbeacf") ++ (B) ++ (B) ++ ("eb") ++ (B) ++ ("cf") ++ (B) ++ ("cfb") ++ (B) ++ ("cededebdbeeaee"))
    =
    (("ffeadabbabddfeefed") ++ (B) ++ ("fdf") ++ (B) ++ ("debabceccceabacfbfdcffcabde") ++ (B) ++ ("e") ++ (B) ++ ("cbeacfa") ++ (B) ++ ("eb") ++ (B) ++ ("cfacfb") ++ (B) ++ ("cededebdbeeaee"));
constraint
  (("bdfffbcbcceffc") ++ (B) ++ ("bcf") ++ (B) ++ ("befdcacdfddbe") ++ (B) ++ ("becfdbcfdcebcbffebcfcddbce") ++ (B) ++ ("eddbafeddcbffeeb") ++ (B) ++ (B) ++ ("defeadd"))
    =
    (("bdfffbcbcceffc") ++ (B) ++ ("bcf") ++ (B) ++ ("befdc") ++ (B) ++ ("cdfddbeabecfdbcfdcebcbffebcfcddbceaeddb") ++ (B) ++ ("feddcbffeeba") ++ (B) ++ ("defeadd"));
constraint
  (("dbcfaedfbcdebdfdfedb") ++ (B) ++ (B) ++ ("dff") ++ (B) ++ (B) ++ ("facbdcfeebcdc") ++ (B) ++ ("edcdebfebafbeebffeafbcdaeecebdcebcb") ++ (B) ++ ("bdddedab"))
    =
    (("dbcf") ++ (B) ++ ("edfbcdebdfdfedb") ++ (B) ++ (B) ++ ("dffaafacbdcfeebcdcaedcdebfebafbeebffe") ++ (B) ++ ("fbcdaeecebdcebcb") ++ (B) ++ ("bddded") ++ (B) ++ ("b"));
constraint
  (("befbaecbcfe") ++ (B) ++ ("bfceebdeeabdbcdbcfcbcdeccbffed") ++ (B) ++ ("dbdecccefecbd") ++ (B) ++ ("eeeecfb") ++ (B) ++ ("dcdbdbdceaabcdafedca"))
    =
    (("befbaecbcfe") ++ (B) ++ ("bfceebdeeabdbcdbcfcbcdeccbffedadbdecccefecbd") ++ (B) ++ ("eeeecfb") ++ (B) ++ ("dcdbdbdce") ++ (B) ++ ("abcdafedca"));
constraint
  (("a") ++ (B) ++ ("eeeeecfeaedf") ++ (B) ++ ("feecdebded") ++ (B) ++ ("f") ++ (B) ++ ("eefdadfebedaecccbdddbcabe") ++ (B) ++ ("bbeacfdcfe") ++ (B) ++ ("bbcbedfc") ++ (B) ++ ("dad") ++ (B) ++ ("dfdcaea"))
    =
    ((B) ++ ("aeeeeecfe") ++ (B) ++ ("edf") ++ (B) ++ ("feecdebded") ++ (B) ++ ("f") ++ (B) ++ ("eefdadfebed") ++ (B) ++ ("ecccbdddbc") ++ (B) ++ ("beabbeacfdcfe") ++ (B) ++ ("bbcbedfc") ++ (B) ++ ("d") ++ (B) ++ ("d") ++ (B) ++ ("dfdcaea"));
constraint
  (("bdbcfbcbcaddec") ++ (B) ++ (B) ++ ("cdefffbcaecefbcceabbeaa") ++ (B) ++ ("fdbffd") ++ (B) ++ ("dfcedecdfdcbcd") ++ (B) ++ ("febcecdfbeeabccecbfeccf"))
    =
    (("bdbcfbcbc") ++ (B) ++ ("ddec") ++ (B) ++ (B) ++ ("cdefffbcaecefbcceabbeaaafdbffdadfcedecdfdcbcd") ++ (B) ++ ("febcecdfbeeabccecbfeccf"));
constraint
  (("ecb") ++ (B) ++ ("ffafddfcfdcbbceeedf") ++ (B) ++ ("cbbfaeefaed") ++ (B) ++ ("aeccdccfffdbbecccfefbbaeb") ++ (B) ++ ("cfdefce") ++ (B) ++ (B) ++ (B) ++ ("e") ++ (B) ++ ("baf") ++ (B) ++ ("dffdab") ++ (B))
    =
    (("ecbaff") ++ (B) ++ ("fddfcfdcbbceeedf") ++ (B) ++ ("cbbf") ++ (B) ++ ("eef") ++ (B) ++ ("ed") ++ (B) ++ (B) ++ ("eccdccfffdbbecccfefbb") ++ (B) ++ ("ebacfdefceaa") ++ (B) ++ ("e") ++ (B) ++ ("bafadffd") ++ (B) ++ ("b") ++ (B));
constraint
  (("dbdd") ++ (B) ++ ("ffcffeddbfefdbdd") ++ (B) ++ ("ffdfeeabef") ++ (B) ++ ("accdedeafd") ++ (B) ++ ("eecbcdbceba") ++ (B) ++ ("cbaadebddececefcaedb") ++ (B) ++ ("dcfbdcae"))
    =
    (("dbddaffcffeddbfefdbdd") ++ (B) ++ ("ffdfee") ++ (B) ++ ("befa") ++ (B) ++ ("ccdedeafd") ++ (B) ++ ("eecbcdbcebaacb") ++ (B) ++ ("adebddececefc") ++ (B) ++ ("edbadcfbdcae"));
constraint
  (("eb") ++ (B) ++ ("cddaddeceedeecdfabbebbefabbbafe") ++ (B) ++ ("efdeecb") ++ (B) ++ ("dccdfdfbdcbeedfebdcbcebedeabfffefcbbfefecc"))
    =
    (("eb") ++ (B) ++ ("cddaddeceedeecdfabbebbefabbbafe") ++ (B) ++ ("efdeecb") ++ (B) ++ ("dccdfdfbdcbeedfebdcbcebedeabfffefcbbfefecc"));
constraint
  (("b") ++ (B) ++ ("dfef") ++ (B) ++ ("fb") ++ (B) ++ ("bfaefccceaccedddbdd") ++ (B) ++ ("bebbfadcecde") ++ (B) ++ ("baced") ++ (B) ++ ("cfbfeeeddefdddccacbebaeaf") ++ (B) ++ ("afbf") ++ (B) ++ ("bbefd"))
    =
    (("b") ++ (B) ++ ("dfefafbabfaefccceaccedddbdd") ++ (B) ++ ("bebbf") ++ (B) ++ ("dcecde") ++ (B) ++ ("b") ++ (B) ++ ("cedacfbfeeeddefdddcc") ++ (B) ++ ("cbebae") ++ (B) ++ ("faafbf") ++ (B) ++ ("bbefd"));
constraint
  (("ffeecdacbfdae") ++ (B) ++ ("aeb") ++ (B) ++ ("bea") ++ (B) ++ ("fdbccecceccdb") ++ (B) ++ (B) ++ ("dcdcfc") ++ (B) ++ ("fabdc") ++ (B) ++ ("d") ++ (B) ++ ("cbcfcfbaf") ++ (B) ++ ("f") ++ (B) ++ ("bbaccedcbcfdddfbfdcfa"))
    =
    (("ffeecdacbfdaea") ++ (B) ++ ("ebabeaafdbccecceccdb") ++ (B) ++ ("adcdcfc") ++ (B) ++ ("f") ++ (B) ++ ("bdc") ++ (B) ++ ("d") ++ (B) ++ ("cbcfcfbaf") ++ (B) ++ ("f") ++ (B) ++ ("bb") ++ (B) ++ ("ccedcbcfdddfbfdcf") ++ (B));
constraint
  (("fffecedbddf") ++ (B) ++ ("bcc") ++ (B) ++ ("ece") ++ (B) ++ (B) ++ ("fbc") ++ (B) ++ ("bbebffaebccdaeebe") ++ (B) ++ ("eeaddcbceeebffaadffcccebfbbfbec") ++ (B) ++ ("feebddfbde"))
    =
    (("fffecedbddf") ++ (B) ++ ("bccaecea") ++ (B) ++ ("fbcabbebffaebccd") ++ (B) ++ ("eebe") ++ (B) ++ ("ee") ++ (B) ++ ("ddcbceeebff") ++ (B) ++ (B) ++ ("dffcccebfbbfbecafeebddfbde"));
solve satisfy;
