var string: H;
var string: G;
var string: E;
var string: A;
var string: C;
constraint
  (("bcc") ++ (E) ++ ("bcabbcdbddabbcdad")) =
    (("bccdbcdcbccbadaddcbd") ++ (A) ++ ("cabcbcabbcdbddabbcdad"));
constraint
  (("bda") ++ (E) ++ ("bdaccd")) = (("bd") ++ (A) ++ ("bdbbdacbdaccd"));
constraint
  (("dbdaacbccadddcdcdcbbcbacdbbbcddabdbbacdbcdbabadcbdbdcbdbbbaac") ++ (""))
    =
    (("dbdaacbccadddcdcdcbbcbacdbbbcdd") ++ (G) ++ ("bbacdbcdbabadcbdbdcbdbbbaac"));
constraint
  (("bdaabdacdccadddabccbccbcaaadbbbbcacadcbbbcdbcccccbdcbcabacaab") ++ (""))
    =
    (("bdaabdacdccadddabccbccbca") ++ (H) ++ ("bbbbcacadcbbbcdbcccccbdcbcabacaab"));
constraint
  (("aaabbdacdbcdccbbbccacbbabcbcccdabdddacbdbbcb") ++ (G) ++ ("acadddbcdbcadd"))
    =
    (("aaabbdacdbcdccbbbccacbbabcbcccd") ++ (G) ++ ("ddacbdbbcbabdacadddbcdbcadd"));
constraint
  (("ddcacbacdbcbccccbcdcbbbccdcddcbaacdcbbda") ++ (H) ++ ("abdcaccbcabbadadac"))
    =
    (("ddcacbacdbcbccccbcdcbbbccdcddcbaacdcbbda") ++ (H) ++ ("abdcaccbcabbadadac"));
constraint
  (("dcc") ++ (H) ++ ("abcdacbbabcccbccaccacdadcabccdbbbddccbbaaab") ++ (G) ++ ("dbdcdbccd"))
    =
    (("dcc") ++ (H) ++ ("abcdacbbabcccbccaccacdadcabccdbbbddccbbaaab") ++ (G) ++ ("dbdcdbccd"));
constraint
  (("baaadbaacdbccadabcabdccddaacbbccbcdcaacdada") ++ (G) ++ ("acacdccdcbdcabd"))
    =
    (("baaadbaacdbccadabc") ++ (G) ++ ("ccddaacbbccbcdcaacdadaabdacacdccdcbdc") ++ (G));
constraint
  (("bacaabddccd") ++ (H) ++ ("cbddccbcacdccabb") ++ (G) ++ ("cbbccbcacadabbcadcbbdbcbabad"))
    =
    (("baca") ++ (G) ++ ("dccd") ++ (H) ++ ("cbddccbcacdccabbabdcbbccbcacadabbcadcbbdbcbabad"));
constraint
  (("aacbdaabbcbcbaa") ++ (G) ++ ("adacddbcccddcaadbaddcbdcadbdbbdbdbcbcdbd") ++ (H))
    =
    (("aacbdaabbcbcbaa") ++ (G) ++ ("adacddbcccddc") ++ (H) ++ ("baddcbdcadbdbbdbdbcbcdbdaad"));
constraint
  (("dcdbdacccdbdddcaccccbbcdbbddcdabcdadbbbcccacddbc") ++ (G) ++ ("adbcacddad"))
    =
    (("dcdbdacccdbdddcaccccbbcdbbddcdabcdadbbbcccacddbcabdadbcacddad") ++ (""));
constraint
  (("cbaccbddacacaddddaacadddadbdcdcdbcd") ++ (H) ++ ("bbaccdaadadddbcdaaddaca"))
    =
    (("cbaccbddacacaddddaacadddadbdcdcdbcd") ++ (H) ++ ("bbaccdaadadddbcdaaddaca"));
constraint
  (("d") ++ (G) ++ ("cdcbaacacacdacd") ++ (G) ++ ("adbdccaadadbccdbd") ++ (G) ++ ("bbbcccbadadab") ++ (G) ++ ("baa"))
    =
    (("d") ++ (G) ++ ("cdcbaacacacdacdabdadbdccaadadbccdbd") ++ (G) ++ ("bbbcccbadadab") ++ (G) ++ ("baa"));
constraint
  (("aacaacddcccbbcccaaabaabcbdcdacdcdbaabccdcaabaabdacdcaacbdb") ++ (H)) =
    (("aacaacddcccbbcccaaabaabcbdcdacdcdbaabccdcaabaabdacdcaacbdb") ++ (H));
constraint
  (("cbaababbddccacbccddddaacadccddbbbccabbbbadbddbadbdbdcbcdac") ++ (H)) =
    (("cbaababbddccacbccddddaacadccddbbbccabbbbadbddbadbdbdcbcdac") ++ (H));
constraint
  (("dcbccbcdacaab") ++ (G) ++ ("bacbcadbdbbcabdcbcdddabacaacbcdabbaaccabcbbac"))
    =
    (("dcbccbcdacaababdbacbcadbdbbcabdcbcdddabacaacbcdabbaaccabcbbac") ++ (""));
constraint
  (("adaad") ++ (H) ++ ("cdbcbaccdbcddbddbadadbccccbccbbbbbddccdabbccabbdbcccb"))
    =
    (("ad") ++ (H) ++ (H) ++ ("cdbcbaccdbcddbddbadadbccccbccbbbbbddccdabbccabbdbcccb"));
constraint
  (("babbaab") ++ (G) ++ ("dbddcddabcdab") ++ (H) ++ ("dcbabbbcabccadbddbabccba") ++ (G) ++ ("accbadbc"))
    =
    (("babbaab") ++ (G) ++ ("dbddcddabcdabaaddcbabbbcabccadbddbabccbaabdaccbadbc"));
constraint
  (("dbabcdabcbdaccca") ++ (G) ++ ("acbddbbdddacabccbaaadcdaddcbacb") ++ (H) ++ ("acbbabda"))
    =
    (("dbabcdabcbdacccaabdacbddbbdddacabccbaaadcdaddcbacb") ++ (H) ++ ("acbbabda"));
constraint
  (("ccacbaadaacdaacda") ++ (H) ++ ("cdbcbccadaaccdbcbbaacaabbdbababcbbbbcabcc"))
    =
    (("ccacbaadaacdaacda") ++ (H) ++ ("cdbcbccadaaccdbcbbaacaabbdbababcbbbbcabcc"));
constraint
  (("babcdabbbccdddccaaccccdaacacbbbbacbdacdcababbcbbbccdaadabdcba") ++ (""))
    =
    (("babcdabbbccdddccaaccccdaacacbbbbacbdacdcababbcbbbccd") ++ (H) ++ ("abdcba"));
constraint
  (("acbaacbdbcdcac") ++ (H) ++ ("acbcadaabaacccbcdaccddbbcdaacbcadcbcacdcdbab"))
    =
    (("acbaacbdbcdcac") ++ (H) ++ ("acbcadaabaacccbcdaccddbbcdaacbcadcbcacdcdbab"));
constraint
  (("dccc") ++ (G) ++ ("cabacadcddcacccbbbcbdddbbacdadbdadcadbacabcbda") ++ (H) ++ ("cabad"))
    =
    (("dccc") ++ (G) ++ ("cabacadcddcacccbbbcbdddbbacdadbdadcadbacabcbdaaadcabad"));
constraint
  (("bb") ++ (G) ++ ("cbbca") ++ (G) ++ ("bdbacbabcdcbcbaaccabccabbbcbddc") ++ (G) ++ ("aadbbacbcbbccd"))
    =
    (("bb") ++ (G) ++ ("cbbca") ++ (G) ++ ("bdbacbabcdcbcbaaccabccabbbc") ++ (C) ++ ("d") ++ (H) ++ ("bbacbcbbccd"));
constraint
  (("bcabcacbacad") ++ (H) ++ ("bba") ++ (H) ++ ("cdaddcacbabccbdcddbdabbcbcbdcbdaccdbccac"))
    =
    (("bcabcacbacad") ++ (H) ++ ("bba") ++ (H) ++ ("cdaddcacbabccbdcddbdabbcbcbdcbdaccdbccac"));
constraint
  (("adaaccccddaacdbacaccbadacaddcbadbdbcbccdccbdd") ++ (H) ++ ("abcdbbbbcdcdd"))
    =
    (("adaaccccddaacdbacaccbadacaddcbadbdbcbccdccbddaadabcdbbbbcdcdd") ++ (""));
constraint
  (("acbadbcacdaadaddccbadbbdccdabaddbccbddbbbdbcbbcdbabacadcbaacd") ++ (""))
    =
    (("acbadbcacd") ++ (H) ++ ("addccbadbbdccdabaddbccbddbbbdbcbbcdbabacadcbaacd"));
constraint
  (("dccdbb") ++ (H) ++ ("bbdc") ++ (G) ++ ("daadbbcdcbacb") ++ (G) ++ ("dbdba") ++ (G) ++ ("ddababdbcabbcdbbbcbad"))
    =
    (("dccdbbaadbbdc") ++ (G) ++ ("daadbbcdcbacbabddbdbaabdddab") ++ (G) ++ ("bcabbcdbbbcbad"));
constraint
  (("caaababaddccdbdbcddacdbdbdddbaabadaadb") ++ (H) ++ ("bddacbcbbbbcbdccdabc"))
    =
    (("caaababaddccdbdbcddacdbdbdddbaabadaadb") ++ (H) ++ ("bddacbcbbbbcbdccdabc"));
constraint
  (("bdccdababbacababbdbadbacccbacbabaacabccabddbabbbbadbcdbaabada") ++ (""))
    =
    (("bdccdababbacababbdbadbacccbacbabaacabcc") ++ (G) ++ ("dbabbbbadbcdbaabada"));
constraint
  (("cadadbcdbdbcdcdbdabdddddddbcadddbbbbdadbcabdbbcdbcdcadaa") ++ (G) ++ ("cb"))
    =
    (("cadadbcdbdbcdcdbd") ++ (G) ++ ("ddddddbcadddbbbbdadbcabdbbcdbcdcadaaabdcb"));
constraint
  (("bbbacdcddb") ++ (H) ++ ("bbbbccbcbbabbcaaccdcdcbddacbddcdacbbcdcabcdbdbbc"))
    =
    (("bbbacdcddbaadbbbbccbcbbabbcaaccdcdcbddacbddcdacbbcdcabcdbdbbc") ++ (""));
constraint
  (("acdddbdba") ++ (H) ++ ("bdacdbdacddcbbdbcacdcadddcbadbbacadddbabdddcdabac"))
    =
    (("acdddbdbaaadbdacdbdacddcbbdbcacdcadddcbadbbacadddb") ++ (G) ++ ("ddcdabac"));
constraint
  (("ccbcb") ++ (H) ++ ("acdcdabacbcdbcdbcbccdaddacdbdbbabbdb") ++ (H) ++ ("dabccbbbcddbca"))
    =
    (("ccbcb") ++ (H) ++ ("acdcdabacbcdbcdbcbccdaddacdbdbbabbdb") ++ (H) ++ ("dabccbbbcddbca"));
constraint
  (("caadddccddcddaabaccbdcbddbaacbadbacbacccaccdcdbabcdbddadbdbca") ++ (""))
    =
    (("c") ++ (H) ++ ("ddccddcddaabaccbdcbddbaacbadbacbacccaccdcdbabcdbddadbdbca"));
constraint
  (("dbbabbcdddbcbaadddaccbbbabbdbadabacba") ++ (H) ++ ("cdbabcacacaadbacdbccb"))
    =
    (("dbbabbcdddbcb") ++ (H) ++ ("ddaccbbbabbdbadabacbaaadcdbabcacac") ++ (H) ++ ("bacdbccb"));
constraint
  ((G) ++ ("abbacaacbbdb") ++ (H) ++ ("daaabadbdcdbadcbaaabcaacaccdbccadadcbcdcddb"))
    =
    ((G) ++ ("abbacaacbbdbaaddaaabadbdcdbadcbaaabcaacaccdbccadadcbcdcddb") ++ (""));
constraint
  (("bccbdacbdaaddbccadccbdaabcddccdddcaacbdbdbacabadabcdbacdb") ++ (H) ++ ("a"))
    =
    (("bccbdacbdaaddbccadccbdaabcddccdddcaacbdbdbacabadabcdbacdbaada") ++ (""));
constraint
  (("ccbdb") ++ (H) ++ ("cdddabccbcdcabacbdaccddcdaabbbcdccbadcaabcacaabdddcdd"))
    =
    (("ccbdbaadcdddabccbcdcabacbdaccddcdaabbbcdccbadcaabcacaabdddcdd") ++ (""));
constraint
  (("ccccdb") ++ (H) ++ ("bccbdaaadcbaaddbbabdacaccbdacabaccabcacadaacdcaabada"))
    =
    (("ccccdbaadbccbdaaadcb") ++ (H) ++ ("dbbabdacaccbdacabaccabcacadaacdcaabada"));
constraint
  (("cbbdcccbdbad") ++ (G) ++ ("ddbdcacacadcaddcabdbbcbccbbcbdcddcccaddbdbaaab"))
    =
    (("cbbdcccbdbad") ++ (G) ++ ("ddbdcacacadcaddcabdbbcbccbbcbdcddcccaddbdbaaab"));
constraint
  (("cdbbdadadacbda") ++ (G) ++ ("cacadcbbbbdcbbbdddccaccabdcbbbcbabcbabababba"))
    =
    (("cdbbdadadacbda") ++ (G) ++ ("cacadcbbbbdcbbbdddccacc") ++ (G) ++ ("cbbbcbabcbabababba"));
constraint
  (("aaccaddbbaddddbbdccabcdddabccaabcdddcbbbdcabadaacbccdacdaadba") ++ (""))
    =
    (("aaccaddbbaddddbbdccabcdddabccaabcdddcbbbdcabadaacbccdacd") ++ (H) ++ ("ba"));
constraint
  (("dccccdbcddbbabacabbdccab") ++ (G) ++ ("babddacbcbcdbcdddccdbdbbbcdaacdaab"))
    =
    (("dccccdbcddbbabacabbdccab") ++ (G) ++ ("b") ++ (G) ++ ("dacbcbcdbcdddccdbdbbbcdaacdaab"));
constraint
  (("bbdbbdbabcbdbca") ++ (H) ++ ("baacddccdbdcadccbdacccaddaaaccaaacacbaddcbc"))
    =
    (("bbdbbdbabcbdbcaaadbaacddccdbdcadccbdacccaddaaaccaaacacbaddcbc") ++ (""));
constraint
  (("bbcccbad") ++ (H) ++ ("aaccbcdbabdccabcbbdddacabcbbcaddcbcdababbdbabccdda"))
    =
    (("bbcccbad") ++ (H) ++ ("aaccbcdb") ++ (G) ++ ("ccabcbbdddacabcbbcaddcbcdababbdbabccdda"));
constraint
  (("cbddcab") ++ (G) ++ ("adcbdadccddacbbaabcbdadaa") ++ (G) ++ ("dbaaaadbaddbddcdbccbbaa"))
    =
    (("cbddcababdadcbdadccddacbbaabcbdadaa") ++ (G) ++ ("dbaaaadbaddbddcdbccbbaa"));
constraint
  (("dcadbcbbdcadbccbaadcdbbbcdadbdcacaa") ++ (G) ++ ("adabcdabcdabccddcddcdab"))
    =
    (("dcadbcbbdcadbccb") ++ (H) ++ ("cdbbbcdadbdcacaa") ++ (G) ++ ("adabcdabcdabccddcddcdab"));
constraint
  (("caccacdbdbdcdbadcdacaadaacbdccabcbcbacbccacdbaadcbddcdbbdbbda") ++ (""))
    =
    (("caccacdbdbdcdbadcdac") ++ (H) ++ ("aacbdccabcbcbacbccacdb") ++ (H) ++ ("cbddcdbbdbbda"));
constraint
  (("bcadaca") ++ (G) ++ ("bdbbbdaabccdabbdbcdaabbbcaabbaabcdbdabbbccdbcabbabb"))
    =
    (("bcadacaabdbdbbbdaabccdabbdbcdaabbbcaabbaabcdbdabbbccdbcabbabb") ++ (""));
constraint
  (("ddaccadcacdbdbbcccabccbcccbcbbcdddbbacdcdbaacc") ++ (G) ++ ("badacacaaaba"))
    =
    (("ddaccadcacdbdbbcccabccbcccbcbbcdddbbacdcdbaacc") ++ (G) ++ ("badacacaaaba"));
constraint
  (("cbbbccbddbbdcdacaaacdaadbddcaccbacbcbbbbdbcabacbdcbaacbaad") ++ (H)) =
    (("cbbbccbddbbdcdacaaacd") ++ (H) ++ ("bddcaccbacbcbbbbdbcabacbdcbaacbaad") ++ (H));
constraint
  (("baddbdaddbdbabbccda") ++ (H) ++ ("baaacdaabcbccacbddbacaccacadbacabddcbba"))
    =
    (("baddbdaddbdbabbccda") ++ (H) ++ ("baaacdaabcbccacbddbacaccacadbacabddcbba"));
constraint
  ((H) ++ ("aacbccbbbaacddbbddcdaabacbbddbcdcbcabcddbaddadccacbccbbbaa") ++ (""))
    =
    ((H) ++ ("aacbccbbbaacddbbddcdaabacbbddbcdcbcabcddbaddadccacbccbbbaa") ++ (""));
constraint
  (("dacaadcdcdaddccbbcdbcaababddcddadbdadaaadba") ++ (G) ++ ("accbccdadcabcca"))
    =
    (("dac") ++ (H) ++ ("cdcdaddccbbcdbcaababddcddadbdadaaadbaabdaccbccdadcabcca"));
constraint
  (("adaaaddbdada") ++ (G) ++ ("bdabaacddcaadcdabdbacbccdccdbccbdbaacaddcadcbc"))
    =
    (("ada") ++ (H) ++ ("dbdada") ++ (G) ++ ("bdabaacddc") ++ (H) ++ ("cdabdbacbccdccdbccbdbaacaddcadcbc"));
constraint
  (("bdacddcdcbdadbcbcdbdaabbdabcbbbddbdcacacacaaaaddccacbbccddccc") ++ (""))
    =
    (("bdacddcdcbdadbcbcdbdaabbdabcbbbddbdcacacacaa") ++ (H) ++ ("dccacbbccddccc"));
constraint
  (("acacddbbcbccaddbc") ++ (G) ++ ("acabacccbdaabaccbcbdccaccabccbddbdcdcccaa"))
    =
    (("acacddbbcbccaddbc") ++ (G) ++ ("acabacccbdaabaccbcbdccaccabccbddbdcdcccaa"));
constraint
  (("abdbbdcacbbbccadadbcabdaccacabbadaadbccbbadcccccdbcbbcdbc") ++ (G) ++ ("a"))
    =
    ((G) ++ ("bbdcacbbbccadadbcabdaccacabbad") ++ (H) ++ ("bccbbadcccccdbcbbcdbcabda"));
constraint
  (("ccdbdddbacacdcbdddaddbccdbbaaacbaabaabc") ++ (H) ++ ("dacdcbddadcddcbacda"))
    =
    (("ccdbdddbacacdcbdddaddbccdbbaaacbaabaabcaaddacdcbddadcddcbacda") ++ (""));
constraint
  (("ddaadbadabbddddbbacdabccbadadababdbacbccdacabcdbacbccabddcddb") ++ (""))
    =
    (("ddaadbadabbddddbbacdabccbadadab") ++ (G) ++ ("bacbccdacabcdbacbccabddcddb"));
constraint
  (("dcccaacdcaaa") ++ (G) ++ ("cbcaaacbcbccbbdacdcdbddcdadba") ++ (H) ++ ("bdba") ++ (H) ++ ("dadccca"))
    =
    (("dcccaacdcaaa") ++ (G) ++ ("cbcaaacbcbccbbdacdcdbddcdadbaaadbdba") ++ (H) ++ ("dadccca"));
constraint
  (("badbbddbaabcdcaaacdacdbbbcdcadbbdbcdbdaddddabadadabdbbcbdccac") ++ (""))
    =
    (("badbbddbaabcdcaaacdacdbbbcdcadbbdbcdbdaddddabadad") ++ (G) ++ ("bbcbdccac"));
constraint
  (("acbdbcbbccdcacabcbdabbabbcdddacdacaaabcdcdbca") ++ (H) ++ ("abbbcbacdccca"))
    =
    (("acbdbcbbccdcacabcbdabbabbcdddacdacaaabcdcdbcaaadabbbcbacdccca") ++ (""));
constraint
  (("cadbbadabbdcbbcdddbccdacbcdbdd") ++ (H) ++ ("bcbabcbdda") ++ (H) ++ ("abaaddbdcacbdac"))
    =
    (("cadbbadabbdcbbcdddbccdacbcdbddaadbcbabcbddaaadab") ++ (H) ++ ("dbdcacbdac"));
constraint
  (("cdabbbdbadababaacdcbdbbddaddbacaadcbadcddcccbddabccad") ++ (H) ++ ("dddcd"))
    =
    (("cdabbbdbadababaacdcbdbbddaddbacaadcbadcddcccbddabccad") ++ (H) ++ ("dddcd"));
constraint
  (("d") ++ (H) ++ ("dccccbabccaddaccadbcdacadabbbcdddacbbdbbdcbdcacbcdcbadadc"))
    =
    (("d") ++ (H) ++ ("dccccbabccaddaccadbcdacadabbbcdddacbbdbbdcbdcacbcdcbadadc"));
constraint
  (("dcccdcdcdbbbddbddbcdcbadd") ++ (H) ++ ("abaadaadabadcddd") ++ (G) ++ ("cbdbdabcbdabcd"))
    =
    (("dcccdcdcdbbbddbddbcdcbaddaadab") ++ (H) ++ ("aadabadcddd") ++ (G) ++ ("cbdbdabcbdabcd"));
constraint
  (("cadcdabbbabddbdba") ++ (H) ++ ("baaaccddcdbcbbacbabaccbddbbbccbbddcbbbcab"))
    =
    (("cadcdabbbabddbdbaaadbaaaccddcdbcbbacbabaccbddbbbccbbddcbbbcab") ++ (""));
constraint
  (("bccbbbabbcddbbaadbdaaccccccacdbadbdbcbbc") ++ (G) ++ ("ccbbcaccbcccdacddb"))
    =
    (("bccbbbabbcddbb") ++ (H) ++ ("bdaaccccccacdbadbdbcbbc") ++ (G) ++ ("ccbbcaccbcccdacddb"));
constraint
  (("adbc") ++ (H) ++ ("bdacbcaddadaabaaacccbcbdcbcddabaabbacdccbddabcccccdacd"))
    =
    (("adbc") ++ (H) ++ ("bdacbcaddadaabaaacccbcbdcbcddabaabbacdccbddabcccccdacd"));
constraint
  (("accadbcddabccaaaaddbcdcadcccdbadbabcda") ++ (H) ++ ("abbdcddcbadcdaabbcab"))
    =
    (("accadbcddabccaaaaddbcdcadcccdbadbabcdaaadabbdcddcbadcdaabbcab") ++ (""));
constraint
  (("dbbccbaba") ++ (G) ++ ("cdbddbcadbaaacacbbdacbababccddddabacdbacbacdbcbab"))
    =
    (("dbbccbaba") ++ (G) ++ ("cdbddbcadbaaacacbbdacbababccddddabacdbacbacdbcbab"));
constraint
  (("daacc") ++ (G) ++ ("cc") ++ (G) ++ ("bdcaaddcbaaacdbdbcdccdacaacbdcdbdabacbadbcabddbd"))
    =
    (("daaccabdcc") ++ (G) ++ ("bdcaaddcbaaacdbdbcdccdacaacbdcdbdabacbadbc") ++ (G) ++ ("dbd"));
constraint
  (("cbddaadabccbbbcdadcbbabca") ++ (H) ++ ("acabcaabadacbcabcddacccdcbdcabdda"))
    =
    (("cbddaadabccbbbcdadcbbabca") ++ (H) ++ ("acabcaabadacbcabcddacccdcbdcabdda"));
constraint
  (("daccddbbcdcabaaaacbbddcdcbdbcdbbadcaddabbdccbbcbdd") ++ (G) ++ ("cddbadaa"))
    =
    (("daccddbbcdcabaaaacbbddcdcbdbcdbbadcaddabbdccbbcbddabdcddbadaa") ++ (""));
constraint
  (("abcbbdaabcdacaabaacaddbcbcbdabdbbdcbcabcbadacb") ++ (G) ++ ("abbcacaddcbb"))
    =
    (("abcbbdaabcdacaabaacaddbcbcbd") ++ (G) ++ ("bbdcbcabcbadacb") ++ (G) ++ ("abbcacaddcbb"));
constraint
  (("bacdcbdaddcdcdbabdddcbadcbbddcccdaccdccaacccddbddaadbadbaddbc") ++ (""))
    =
    (("bacdcbdaddcdcdb") ++ (G) ++ ("ddcbadcbbddcccdaccdccaacccddbdd") ++ (H) ++ ("badbaddbc"));
constraint
  (("aaccddbdcdabbcaaddddacdcbaacbbbddadabcbcccdcbdcdbbbcaddccacba") ++ (""))
    =
    (("aaccddbdcdabbc") ++ (H) ++ ("dddacdcbaacbbbddadabcbcccdcbdcdbbbcaddccacba"));
constraint
  (("dcdbacabccbabacdacbdcbccbabbdbcbddddcca") ++ (G) ++ ("cacdbdbcdccc") ++ (G) ++ ("cbcc"))
    =
    (("dcdbacabccbabacdacbdcbccbabbdbcbddddccaabdcacdbdbcdccc") ++ (G) ++ ("cbcc"));
constraint
  (("bdacdcdcbcccddadbcadbaaddbcbcdbbaadb") ++ (G) ++ ("acddbcbadbadccaaaa") ++ (H) ++ ("b"))
    =
    (("bdacdcdcbcccddadbcadbaaddbcbcdbb") ++ (H) ++ ("b") ++ (G) ++ ("acddbcbadbadccaaaaaadb"));
constraint
  (("bcbadaacabaabcbbacabbbabbbabddaacbacdbabdcaddddcdcdacbabbbbda") ++ (""))
    =
    (("bcbadaacabaabcbbacabbbabbb") ++ (G) ++ ("daacbacdbabdcaddddcdcdacbabbbbda"));
constraint
  (("cacdbcaddaddabadbcbcdcacaacdacbbdadcbadabaaccbbdbbabbaabacaad") ++ (""))
    = (("cacdbcaddaddabadbcbcdcacaacdacbbdadcbadabaaccbbdbbabbaabac") ++ (H));
constraint
  (("cbdbaadcdc") ++ (H) ++ ("cbc") ++ (G) ++ ("cdacbaccbcbdbdcdadaddcddcdccadcabaabaccada"))
    =
    (("cbdbaadcdc") ++ (H) ++ ("cbc") ++ (G) ++ ("cdacbaccbcbdbdcdadaddcddcdccadcabaabaccada"));
constraint
  (("cadbddcccadbacabacaab") ++ (H) ++ ("bbbbaccaddcbaddaddcbacdddccccdbbabaaa"))
    =
    (("cadbddcccadbacabacaab") ++ (H) ++ ("bbbbaccaddcbaddaddcbacdddccccdbbabaaa"));
constraint
  (("bcdbabcaacccdaaaacbaccbdbdbabaaabc") ++ (G) ++ ("adadaccbcbddabccdccbbbdc"))
    =
    (("bcdbabcaacccdaaaacbaccbdbdbabaaabcabdadadaccbcbddabccdccbbbdc") ++ (""));
constraint
  (("bddadadadadcccdbbacdcccdcbacdddaaadbddccbcdacaabcdccbbcbcdacc") ++ (""))
    =
    (("bddadadadadcccdbbacdcccdcbacddda") ++ (H) ++ ("bddccbcdacaabcdccbbcbcdacc"));
constraint
  (("cdaaaacbccdcaaadddaabaccbdadadbbbdabcabddacbdcbcbbbadacaccddd") ++ (""))
    =
    (("cdaaaacbccdca") ++ (H) ++ ("ddaabaccbdadadbbbdabcabddacbdcbcbbbadacaccddd"));
constraint
  (("ddbddcaddbcdcbac") ++ (H) ++ ("bcabcbcc") ++ (G) ++ ("dbaddbdccccbababccaa") ++ (H) ++ ("abdddaaa"))
    =
    (("ddbddcaddbcdcbac") ++ (H) ++ ("bcabcbccabddbaddbdccccbababccaa") ++ (H) ++ ("abdddaaa"));
constraint
  ((H) ++ ("bddabcadababadcacddcccbccccdcbaacdccddbacbbc") ++ (G) ++ ("bdabcaddddb"))
    =
    (("aadbddabcadababadcacddcccbccccdcbaacdccddbacbbc") ++ (G) ++ ("bdabcaddddb"));
constraint
  (("bacdacddddccdcdcbbccbcbbbbcca") ++ (G) ++ ("daabcab") ++ (H) ++ ("abbbbbbbdccbdccccab"))
    =
    (("bacdacddddccdcdcbbccbcbbbbccaabddaabcabaadabbbbbbbdccbdccccab") ++ (""));
constraint
  (("dabcbddccacbabacbdadddbddddddc") ++ (G) ++ ("bdbbaccdaaaadbcccbbbcccadbad"))
    =
    (("dabcbddccacbabacbdadddbddddddc") ++ (G) ++ ("bdbbaccdaa") ++ (H) ++ ("bcccbbbcccadbad"));
constraint
  (("dcdbcdcabbddbdcbbaacaa") ++ (H) ++ ("acdadcdabcbbcbdbcbdbbbbdbcadababb") ++ (H))
    = (("dcdbcdcabbddbdcbbaacaaaadacdadcdabcbbcbdbcbdbbbbdbcadababb") ++ (H));
constraint
  (("ddcadccacbcddbdd") ++ (H) ++ ("cccacdbcdbcccaadccdbbbcccccdcdcbdabdddc") ++ (H))
    =
    (("ddcadccacbcddbdd") ++ (H) ++ ("cccacdbcdbcccaadccdbbbcccccdcdcbd") ++ (G) ++ ("ddc") ++ (H));
constraint
  (("dbbdbdacbadddcacdacddbdbaacdbbbacbcaaabacd") ++ (H) ++ ("bbcdcbbdabacabdd"))
    =
    (("dbbdbdacbadddcacdacddbdbaacdbbbacbcaaabacdaadbbcdcbbdabac") ++ (G) ++ ("d"));
constraint
  (("abacddaabbabbddacdcbbbccdacbbaaaabcbdbbcdbdbbbacabbbb") ++ (G) ++ ("adbdb"))
    =
    (("abacddaabbabbddacdcbbbccdacbbaaaabcbdbbcdbdbbbacabbbb") ++ (G) ++ ("adbdb"));
constraint
  (("cabbdcdbaccdbdcbcabcb") ++ (G) ++ ("caccacddcdaaacacadbbabdbacacadabcccdd"))
    =
    (("cabbdcdbaccdbdcbcabcbabdcaccacddcdaaacacadbb") ++ (G) ++ ("bacacadabcccdd"));
constraint
  (("bdddadcaabccdddcadcabcdbbcaccbd") ++ (G) ++ ("bdcdcbdbbdaacdcbbaccbbaaaaa"))
    =
    (("bdddadcaabccdddcadcabcdbbcaccbdabdbdcdcbdbbdaacdcbbaccbbaaaaa") ++ (""));
constraint
  (("dbacb") ++ (G) ++ ("dadbcbbbdadbdbbbabcccbccdaabbcbddcbcacdbbdbccaaccadba"))
    =
    (("dbacbabddadbcbbbdadbdbbbabcccbccdaabbcbddcbcacdbbdbccaaccadba") ++ (""));
constraint
  (("bbbcddcdabbaadccaaaaacbabbddabadacdcbdaccaaadcbdbcdbccdcaacdd") ++ (""))
    =
    (("bbbcddcdabb") ++ (H) ++ ("ccaaaaacbabbddabadacdcbdaccaaadcbdbcdbccdcaacdd"));
constraint
  (("dcdbadbcbabbcbdadaacbcbbdccc") ++ (G) ++ ("baaccbcdbccbddcbcbdadbbaabaacc"))
    =
    (("dcdbadbcbabbcbdadaacbcbbdcccabdbaaccbcdbccbddcbcbdadbbaabaacc") ++ (""));
constraint
  (("abac") ++ (H) ++ ("adbdbadccaabcdddacdcbddadcaccdababbaddcdccbdadbabaacda"))
    =
    (("abac") ++ (H) ++ ("adbdbadccaabcdddacdcbddadcaccdababbaddcdccbdadbabaacda"));
constraint
  (("cacbcbbccdb") ++ (G) ++ ("aabcbddcdabbbaccdddbbbdccabcabbddcdcbbdcdabddac"))
    =
    (("cacbcbbccdbabdaabcbddcdabbbaccdddbbbdccabcabbddcdcbbdcd") ++ (G) ++ ("dac"));
constraint
  (("dbbcbcabbddaaadbcdbcbaaaacccdbaddbababbabaccaabcadcddbdadacbd") ++ (""))
    =
    (("dbbcbcabbdda") ++ (H) ++ ("bcdbcbaaaacccdbaddbababbabaccaabcadcddbdadacbd"));
constraint
  (("cccadaddbbccadbdbcccadcacbcabbcddddddcbdbadabbabddddbbcadadab") ++ (""))
    =
    (("cccadaddbbccadbdbcccadcacbcabbcddddddcbdbadabb") ++ (G) ++ ("dddbbcadadab"));
constraint
  (("cbbbababbdbbcabbdbd") ++ (G) ++ ("dbadbbbdacccbbbdbadddcabbddbaababcababa"))
    =
    (("cbbbababbdbbcabbdbdabddbadbbbdacccbbbdbadddcabbddbaababcababa") ++ (""));
constraint
  (("dcdbccbcbbcbabcadbddbbcccbcdcadcbcb") ++ (H) ++ ("ccdadbabbaccddac") ++ (H) ++ ("acaa"))
    =
    (("dcdbccbcbbcbabcadbddbbcccbcdcadcbcb") ++ (H) ++ ("ccdadbabbaccddac") ++ (H) ++ ("acaa"));
constraint
  (("ddaababbdcddadcabccacddcccccdacccbddacaacdba") ++ (G) ++ ("caddcdbcbdbbda"))
    =
    (("ddaababbdcddadcabccacddcccccdacccbddacaacdba") ++ (G) ++ ("caddcdbcbdbbda"));
constraint
  (("dbbdbadccbcadcabbbccccacdab") ++ (H) ++ ("baadacdbab") ++ (G) ++ ("aacccdbccdacdbdbac"))
    =
    (("dbbdbadccbcadcabbbccccacdab") ++ (H) ++ ("baadacdbababdaacccdbccdacdbdbac"));
constraint
  (("daacddbccbd") ++ (G) ++ ("cdcddab") ++ (H) ++ ("baabbaacaabddcacbabadddbbadbacbcccdca"))
    =
    (("daacddbccbd") ++ (G) ++ ("cdcddab") ++ (H) ++ ("baabbaacaabddcacbabadddbbadbacbcccdca"));
constraint
  (("bcadcacabcbbcbdaabaababbbaddacabddacdaccdbcbdccabaabbcccccdcc") ++ (""))
    =
    (("bcadcacabcbbcbdaabaababbbaddac") ++ (G) ++ ("dacdaccdbcbdccabaabbcccccdcc"));
constraint
  (("aaabdacbacdddcccbcdddacabccabbbdabcacccbcaaccabbdbbadbccdcdcb") ++ (""))
    =
    (("aa") ++ (G) ++ ("acbacdddcccbcdddacabccabbbdabcacccbcaaccabbdbbadbccdcdcb"));
constraint
  (("bdbdbcdbdbcdabbccdcb") ++ (H) ++ ("caccaaabbcc") ++ (H) ++ ("aca") ++ (H) ++ ("bcccdbcaadbcbcdcda"))
    =
    (("bdbdbcdbdbcdabbccdcbaadcaccaaabbccaadaca") ++ (H) ++ ("bcccdbc") ++ (H) ++ ("bcbcdcda"));
constraint
  (("dbdadb") ++ (G) ++ ("cbaccdcaabbcbdbdbdbddacbbacddbaacdcbcddaaaccaabc") ++ (H) ++ ("b"))
    =
    (("dbdadbabdcbaccdcaabbcbdbdbdbddacbbacddbaacdcbcddaaaccaabcaadb") ++ (""));
constraint
  (("ababbcabaadbbdadccbababbdaadcddbdbbbadcab") ++ (H) ++ ("aadabbcaddabadcda"))
    =
    (("ababbcabaadbbdadccbababbdaadcddbdbbbadcabaadaadabbcaddabadcda") ++ (""));
constraint
  (("bbcbbbbcaadddbacadddcdbadcbc") ++ (G) ++ ("dcddbbdadaaaddacbaaabaaadadcda"))
    =
    (("bbcbbbbc") ++ (H) ++ ("ddbacadddcdbadcbc") ++ (G) ++ ("dcddbbdadaaaddacbaaaba") ++ (H) ++ ("adcda"));
constraint
  (("aacddcbdbbdbbbaaaddcbadccaabcaaadadbbababccdadbcbdaadabadccad") ++ (""))
    =
    (("aacddcbdbbdbbbaaaddcbadccaabca") ++ (H) ++ ("adbbababccdadbcbdaadabadccad"));
constraint
  (("bbaabcadacadcdaadadccbacbaaddbdcacdcbdaadaacdbdbdbaccaaacdaba") ++ (""))
    =
    (("bbaabcadacadcd") ++ (H) ++ ("adccbacbaaddbdcacdcbdaadaacdbdbdbaccaaacdaba"));
constraint
  ((H) ++ ("cbcbadacbcbccaadbddabccaaaacacbdbddaaabdbcccbadaaabcbbdaac") ++ (""))
    =
    (("aadcbcbadacbcbccaadbddabccaaaacacbdbddaaabdbcccbadaaabcbbdaac") ++ (""));
constraint
  (("cdbdadd") ++ (H) ++ ("daacdcbcbc") ++ (G) ++ ("ddaabadacadccddacddcdbdbbbbacadcdddbab"))
    =
    (("cdbdadd") ++ (H) ++ ("daacdcbcbc") ++ (G) ++ ("ddaabadacadccddacddcdbdbbbbacadcdddbab"));
constraint
  ((G) ++ ("dcacdabdadddcdbccdcbdcabbabccbdcbdacbadcdbbdddccccdcdccbbd") ++ (""))
    =
    ((G) ++ ("dcacd") ++ (G) ++ ("adddcdbccdcbdcabbabccbdcbdacbadcdbbdddccccdcdccbbd"));
constraint
  (("dccadddba") ++ (H) ++ ("abccdbbbabacbabc") ++ (H) ++ ("bdcdacdbccbabccdddcbddacbddcdd"))
    =
    (("dccadddbaaadabccdbbbabacbabcaadbdcdacdbccbabccdddcbddacbddcdd") ++ (""));
constraint
  (("bddbadcdbbdcbbaaccddcbabbbaaaabbbbcaabca") ++ (G) ++ ("cbcdad") ++ (H) ++ ("acccb") ++ (G) ++ ("a"))
    =
    (("bddbadcdbbdcbbaaccddcbabbbaaaabbbbcaabcaabdcbcdadaadacccb") ++ (G) ++ ("a"));
constraint
  (("ccaacadaddbdabcbbdccdbcdcbdcddccbaacdcbbbabacbadbcdddcddad") ++ (G)) =
    (("ccaacadaddbdabcbbdccdbcdcbdcddccbaacdcbbbabacbadbcdddcddadabd") ++ (""));
constraint
  (("ddacbccdacaadbaabca") ++ (G) ++ ("dacccccbddbcccdbdbabbddccdcdccabccadbcb"))
    =
    (("ddacbccdacaadbaabcaabddacccccbddbcccdbdbabbddccdcdccabccadbcb") ++ (""));
constraint
  (("bdcddbb") ++ (G) ++ (H) ++ ("baa") ++ (H) ++ ("aaddbdaaaacabaccbabdbbabbcaccbccdd") ++ (G) ++ ("bbacc"))
    =
    (("bdcddbbabd") ++ (H) ++ ("baa") ++ (H) ++ ("aaddbdaaaacabaccb") ++ (G) ++ ("bbabbcaccbccddabdbbacc"));
constraint
  (("aacbddbcdccbbcbccbccaacdaacdcacdcaca") ++ (H) ++ ("a") ++ (G) ++ ("daaacdadacbbbccbaa"))
    =
    (("aacbddbcdccbbcbccbccaacdaacdcacdcaca") ++ (H) ++ ("aabddaaacdadacbbbccbaa"));
constraint
  (("dc") ++ (G) ++ ("bbadabcdbbccbbcdabddaacadbbbbd") ++ (H) ++ ("dcccdbcbdbcdcbadabcadbc"))
    =
    (("dc") ++ (G) ++ ("bbadabcdbbccbbcd") ++ (G) ++ ("daacadbbbbdaaddcccdbcbdbcdcbadabcadbc"));
constraint
  (("dbbbabadbabbbccddbcdacbdddbbbbdcdbbcdbbccacdaacabbddbbab") ++ (H) ++ ("aa"))
    =
    (("dbbbabadbabbbccddbcdacbdddbbbbdcdbbcdbbccacdaacabbddbbab") ++ (H) ++ ("aa"));
constraint
  (("caacddccdaddbcbdbdbccabaacabaacdacbdadbdcdcbacb") ++ (H) ++ ("cddadcbccaa"))
    =
    (("caacddccdaddbcbdbdbccabaacabaacdacbdadbdcdcbacbaadcddadcbccaa") ++ (""));
constraint
  (("ccdcdbaccacdaddbb") ++ (G) ++ ("bacbbbccadadbadaccdacabdabadbdabdadaaaadb"))
    =
    (("ccdcdbaccacdaddbbabdbacbbbccadadbadaccdac") ++ (G) ++ ("abadbdabdadaaaadb"));
constraint
  ((G) ++ ("ccdabbacabdadcccccdbcbbbcbcdcbcbbdbbdaca") ++ (G) ++ ("bacdcdabbdcaaad"))
    = (("abdccdabbacabdadcccccdbcbbbcbcdcbcbbdbbdacaabdbacdcdabbdca") ++ (H));
constraint
  (("dbbbadcbbcaccdbbdadacdaabcddadacaaddadcddcaab") ++ (G) ++ ("ccccaccdccccb"))
    =
    (("dbbbadcbbcaccdbbdadacdaabcddadac") ++ (H) ++ ("dadcddcaababdccccaccdccccb"));
constraint
  (("aadccdbcdadccdbdbaaabaabacadbdbddbccaccdcd") ++ (H) ++ ("cdaacddbacbcdccb"))
    =
    ((H) ++ ("ccdbcdadccdbdbaaabaabacadbdbddbccaccdcdaadcdaacddbacbcdccb") ++ (""));
constraint
  (("abcacdbbbdcdcacc") ++ (G) ++ ("dbbcbbcaaabcddccbbaabbaccdbddadccbbabca") ++ (G))
    = (("abcacdbbbdcdcaccabddbbcbbcaaabcddccbbaabbaccdbddadccbbabca") ++ (G));
constraint
  (("abcdbdddbcdaacaabacbdabbcabccbaaca") ++ (H) ++ ("bdcbadddcbdbbdaabdcaaacc"))
    =
    (("abcdbdddbcdaacaabacbdabbcabccbaacaaadbdcbadddcbdbbdaabdcaaacc") ++ (""));
constraint
  (("cbacbcbcabcddbbcadbbdbddbbacdadcbaadaabbbdd") ++ (G) ++ ("ddacbabaabadddb"))
    =
    (("cbacbcbcabcddbbcadbbdbddbbacdadcbaadaabbbdd") ++ (G) ++ ("ddacbabaabadddb"));
constraint
  (("adabcdac") ++ (H) ++ ("bbacacbdabbabbabddccddbcaabadbacdcacbadbdabaccabda"))
    =
    (("adabcdacaadbbacacbdabbabbabddccddbcaabadbacdcacbadbdabacc") ++ (G) ++ ("a"));
constraint
  (("badcccdddaba") ++ (G) ++ ("bcbaacc") ++ (G) ++ ("dbbcdadddbbbdbcc") ++ (G) ++ ("ddbbbdccbdcbbddab"))
    =
    (("badcccdddaba") ++ (G) ++ ("bcbaacc") ++ (G) ++ ("dbbcdadddbbbdbcc") ++ (G) ++ ("ddbbbdccbdcbbddab"));
constraint
  (("ddcbaacbdcbdaaaadbaddbbdaddddbddccbccacbcdadccdcbddccddbabdcd") ++ (""))
    =
    (("ddcbaacbdcbdaa") ++ (H) ++ ("baddbbdaddddbddccbccacbcdadccdcbddccddb") ++ (G) ++ ("cd"));
constraint
  (("d") ++ (G) ++ ("dbdcbccbcbcacadccddbdcabbadacbaaacaacadcbaccdcdbbdcbbbbda"))
    =
    (("dabddbdcbccbcbcacadccddbdcabbadacbaaacaacadcbaccdcdbbdcbbbbda") ++ (""));
constraint
  (("ccbadcaddcadcabcbbcbbdaaacabcbdbadbaabcacbdddbcaa") ++ (H) ++ ("dcadd") ++ (G) ++ ("b"))
    =
    (("ccbadcaddcadcabcbbcbbdaaacabcbdbadbaabcacbdddbcaaaaddcaddabdb") ++ (""));
constraint
  (("badcbdcacdcdcbcdadadaccdadbaaac") ++ (H) ++ ("dcdccbcdddcaadcbddbbabcdbda"))
    =
    (("badcbdcacdcdcbcdadadaccdadbaaacaaddcdccbcdddcaadcbddbbabcdbda") ++ (""));
constraint
  (("dbbabbac") ++ (G) ++ ("accccddcbbdadcabcccbbadcaccab") ++ (G) ++ ("baabddadccdcdbccac"))
    =
    (("dbbabbac") ++ (G) ++ ("accccddcbbdadcabcccbbadcaccababdbaabddadccdcdbccac"));
constraint
  (("bbcaaacaacaadabcdbaaacbdbbadcdcaddcaddbcabdbacddbabbcdcadbdab") ++ (""))
    =
    (("bbcaaacaacaadabcdbaaacbdbbadcdcaddcaddbc") ++ (G) ++ ("bacddbabbcdcadbdab"));
constraint
  ((H) ++ ("abddcccbacdcddaacccdbbbbbacbacababadadccdbcbbbbdadcdbbdbdd") ++ (""))
    =
    (("aad") ++ (G) ++ ("dcccbacdcddaacccdbbbbbacbacababadadccdbcbbbbdadcdbbdbdd"));
solve satisfy;
