var string: B;
var string: E;
var string: A;
var string: D;
constraint
  (("cab") ++ (D) ++ ("bccca") ++ (D) ++ ("acba") ++ (D) ++ ("cbb") ++ (D) ++ ("a") ++ (D) ++ ("aacbaaabcacca") ++ (D) ++ ("b") ++ (D) ++ ("accbccaccc") ++ (D) ++ ("aba"))
    =
    (("ca") ++ (D) ++ (D) ++ ("b") ++ (E) ++ (B) ++ ("a") ++ (A) ++ ("cbaba"));
constraint
  (("aabccabac") ++ (D) ++ ("aca") ++ (D) ++ ("ac") ++ (D) ++ (D) ++ ("ac") ++ (D) ++ ("cc") ++ (D) ++ (D) ++ ("c") ++ (D) ++ ("bacac") ++ (D) ++ ("acacbbaa") ++ (D) ++ ("cbbaaaaac"))
    =
    (("aabccabacbacabacb") ++ (D) ++ ("ac") ++ (D) ++ ("ccbbc") ++ (D) ++ (D) ++ ("acacbacac") ++ (D) ++ (D) ++ ("aa") ++ (D) ++ ("c") ++ (D) ++ ("baaaaac"));
constraint
  (("bcaacaacaac") ++ (D) ++ ("caaabab") ++ (D) ++ ("aaaacaacaaaa") ++ (D) ++ ("ccaacaa") ++ (D) ++ ("cc") ++ (D) ++ (D) ++ ("ab") ++ (D) ++ ("cca"))
    =
    (("bcaacaacaac") ++ (D) ++ ("caaababbaaaacaacaaaabccaacaa") ++ (D) ++ ("ccbba") ++ (D) ++ ("bcca"));
constraint
  (("b") ++ (D) ++ ("abcc") ++ (D) ++ ("ccbccbcbaaacaa") ++ (D) ++ ("cbcacabcc") ++ (D) ++ ("cacababcccccacaa") ++ (D) ++ ("cc"))
    =
    ((D) ++ ("babcc") ++ (D) ++ ("cc") ++ (D) ++ ("cc") ++ (D) ++ ("cbaaacaabc") ++ (D) ++ ("caca") ++ (D) ++ ("ccbcaca") ++ (D) ++ ("a") ++ (D) ++ ("cccccacaa") ++ (D) ++ ("cc"));
constraint
  (("accabc") ++ (D) ++ ("cc") ++ (D) ++ ("b") ++ (D) ++ ("caba") ++ (D) ++ (D) ++ ("a") ++ (D) ++ ("ccaab") ++ (D) ++ (D) ++ (D) ++ ("ab") ++ (D) ++ ("aaababbbc") ++ (D) ++ ("ccacaccaac"))
    =
    (("accabc") ++ (D) ++ ("ccbbbcabab") ++ (D) ++ ("abccaa") ++ (D) ++ ("bb") ++ (D) ++ ("ab") ++ (D) ++ ("aaabab") ++ (D) ++ (D) ++ ("cbccacaccaac"));
constraint
  (("c") ++ (D) ++ ("caccacabacaacbcb") ++ (D) ++ ("cca") ++ (D) ++ ("acccccaacabaaacccaccaccaaa") ++ (D) ++ ("c"))
    =
    (("cbcaccacabacaacbc") ++ (D) ++ (D) ++ ("ccabacccccaaca") ++ (D) ++ ("aaacccaccaccaaa") ++ (D) ++ ("c"));
constraint
  (("caa") ++ (D) ++ ("acaaacccac") ++ (D) ++ ("aaaaa") ++ (D) ++ ("aabccac") ++ (D) ++ ("cccccaaccc") ++ (D) ++ ("c") ++ (D) ++ (D) ++ ("c") ++ (D) ++ (D) ++ ("baaac"))
    =
    (("caa") ++ (D) ++ ("acaaacccac") ++ (D) ++ ("aaaaa") ++ (D) ++ ("aa") ++ (D) ++ ("ccacbcccccaacccbc") ++ (D) ++ ("bcb") ++ (D) ++ (D) ++ ("aaac"));
constraint
  (("cabc") ++ (D) ++ ("cccaabbaccc") ++ (D) ++ ("c") ++ (D) ++ ("baabba") ++ (D) ++ ("cacc") ++ (D) ++ ("caabaabccaccabacab") ++ (D) ++ ("b"))
    =
    (("cabc") ++ (D) ++ ("cccaa") ++ (D) ++ ("baccc") ++ (D) ++ ("c") ++ (D) ++ (D) ++ ("aa") ++ (D) ++ ("ba") ++ (D) ++ ("cacc") ++ (D) ++ ("caabaabccaccabacab") ++ (D) ++ ("b"));
constraint
  (("ccbab") ++ (D) ++ ("c") ++ (D) ++ ("a") ++ (D) ++ ("aac") ++ (D) ++ ("abcbb") ++ (D) ++ ("cb") ++ (D) ++ (D) ++ ("ca") ++ (D) ++ ("c") ++ (D) ++ ("cab") ++ (D) ++ ("acabcaac") ++ (D) ++ (D) ++ ("cca") ++ (D) ++ ("aaca"))
    =
    (("cc") ++ (D) ++ ("ab") ++ (D) ++ ("c") ++ (D) ++ ("abaac") ++ (D) ++ ("abc") ++ (D) ++ ("b") ++ (D) ++ ("cb") ++ (D) ++ ("bcabc") ++ (D) ++ ("cab") ++ (D) ++ ("acabcaac") ++ (D) ++ ("bccabaaca"));
constraint
  (("ca") ++ (D) ++ ("aabcbbcaaaa") ++ (D) ++ ("c") ++ (D) ++ ("ababababcaaac") ++ (D) ++ ("cc") ++ (D) ++ ("c") ++ (D) ++ ("bacb") ++ (D) ++ ("cc") ++ (D) ++ ("cbccaab"))
    =
    (("cabaabc") ++ (D) ++ ("bcaaaa") ++ (D) ++ ("c") ++ (D) ++ ("aba") ++ (D) ++ ("ababcaaac") ++ (D) ++ ("ccbcb") ++ (D) ++ ("acb") ++ (D) ++ ("ccbc") ++ (D) ++ ("ccaa") ++ (D));
constraint
  (("acc") ++ (D) ++ ("abccbccb") ++ (D) ++ ("c") ++ (D) ++ ("a") ++ (D) ++ ("acabaac") ++ (D) ++ ("bcabaaacacbaacc") ++ (D) ++ (D) ++ ("ca") ++ (D) ++ ("bb") ++ (D) ++ ("baa"))
    =
    (("acc") ++ (D) ++ ("a") ++ (D) ++ ("cc") ++ (D) ++ ("ccb") ++ (D) ++ ("cba") ++ (D) ++ ("acabaacbbcabaaacac") ++ (D) ++ ("aaccb") ++ (D) ++ ("cab") ++ (D) ++ (D) ++ (D) ++ ("baa"));
constraint
  (("acacb") ++ (D) ++ ("acaa") ++ (D) ++ ("a") ++ (D) ++ ("caaa") ++ (D) ++ ("aaca") ++ (D) ++ ("ccbcbac") ++ (D) ++ ("cbcacccaabacaa") ++ (D) ++ ("cccba"))
    =
    (("acacb") ++ (D) ++ ("acaa") ++ (D) ++ ("abcaaa") ++ (D) ++ ("aaca") ++ (D) ++ ("ccbcbac") ++ (D) ++ ("cbcacccaa") ++ (D) ++ ("acaabccc") ++ (D) ++ ("a"));
constraint
  (("ccac") ++ (D) ++ (D) ++ (D) ++ ("c") ++ (D) ++ ("ccacacaab") ++ (D) ++ ("abbca") ++ (D) ++ (D) ++ ("c") ++ (D) ++ ("cc") ++ (D) ++ ("ab") ++ (D) ++ (D) ++ ("acaaaccc") ++ (D) ++ ("ca") ++ (D) ++ ("bb") ++ (D) ++ ("a"))
    =
    (("ccacbb") ++ (D) ++ ("cbccacacaa") ++ (D) ++ ("bab") ++ (D) ++ ("cabbcbccbabbbacaaacccbca") ++ (D) ++ ("bbba"));
constraint
  ((D) ++ ("c") ++ (D) ++ (D) ++ ("ab") ++ (D) ++ ("bcc") ++ (D) ++ (D) ++ ("ccaacccc") ++ (D) ++ ("acaabccbabcc") ++ (D) ++ ("b") ++ (D) ++ (D) ++ ("cacccabbccaa") ++ (D) ++ ("c"))
    =
    ((D) ++ ("cbba") ++ (D) ++ ("bbccbbccaaccccbacaa") ++ (D) ++ ("cc") ++ (D) ++ ("a") ++ (D) ++ ("cc") ++ (D) ++ (D) ++ ("bbcaccca") ++ (D) ++ ("bccaa") ++ (D) ++ ("c"));
constraint
  (("a") ++ (D) ++ ("c") ++ (D) ++ (D) ++ ("baaaacbabaa") ++ (D) ++ ("aa") ++ (D) ++ (D) ++ ("cbcaccaacbcacbaa") ++ (D) ++ ("b") ++ (D) ++ (D) ++ (D) ++ ("aac") ++ (D) ++ ("bbcaa"))
    =
    (("abcbb") ++ (D) ++ ("aaaac") ++ (D) ++ ("abaabaa") ++ (D) ++ ("bc") ++ (D) ++ ("caccaacbcac") ++ (D) ++ ("aabbbbbaac") ++ (D) ++ ("b") ++ (D) ++ ("caa"));
constraint
  (("abcbc") ++ (D) ++ ("bccc") ++ (D) ++ ("cc") ++ (D) ++ ("aac") ++ (D) ++ ("aaa") ++ (D) ++ ("cacaaaac") ++ (D) ++ ("ac") ++ (D) ++ ("aba") ++ (D) ++ ("accbcacbcbcaa"))
    =
    (("a") ++ (D) ++ ("cbc") ++ (D) ++ (D) ++ ("ccc") ++ (D) ++ ("cc") ++ (D) ++ ("aacbaaabcacaaaacbacbaba") ++ (D) ++ ("accbcac") ++ (D) ++ ("c") ++ (D) ++ ("caa"));
constraint
  (("abcaccacabacb") ++ (D) ++ ("baa") ++ (D) ++ ("aaabcc") ++ (D) ++ ("c") ++ (D) ++ ("ba") ++ (D) ++ (D) ++ ("acccaaaaac") ++ (D) ++ ("aba") ++ (D) ++ ("baa") ++ (D) ++ (D))
    =
    (("abcaccaca") ++ (D) ++ ("ac") ++ (D) ++ (D) ++ (D) ++ ("aabaaabcc") ++ (D) ++ ("cbba") ++ (D) ++ ("bacccaaaaac") ++ (D) ++ ("a") ++ (D) ++ ("a") ++ (D) ++ (D) ++ ("aabb"));
constraint
  (("ccbacccccbcac") ++ (D) ++ (D) ++ ("aabcccbccb") ++ (D) ++ ("cc") ++ (D) ++ ("bb") ++ (D) ++ (D) ++ ("acc") ++ (D) ++ ("accab") ++ (D) ++ ("ac") ++ (D) ++ ("cabcb"))
    =
    (("ccbaccccc") ++ (D) ++ ("cacbbaabccc") ++ (D) ++ ("ccbbccb") ++ (D) ++ (D) ++ ("b") ++ (D) ++ ("acc") ++ (D) ++ ("acca") ++ (D) ++ ("bacbcabcb"));
constraint
  (("b") ++ (D) ++ ("ccbcacb") ++ (D) ++ ("ba") ++ (D) ++ ("aacca") ++ (D) ++ ("bacbacacabacb") ++ (D) ++ ("aa") ++ (D) ++ ("ba") ++ (D) ++ ("ac") ++ (D) ++ ("c") ++ (D) ++ ("c") ++ (D) ++ ("cbcac"))
    =
    (("bbcc") ++ (D) ++ ("cacbbba") ++ (D) ++ ("aaccab") ++ (D) ++ ("acbacaca") ++ (D) ++ ("acbbaabba") ++ (D) ++ ("acbcbc") ++ (D) ++ ("c") ++ (D) ++ ("cac"));
constraint
  (("cbca") ++ (D) ++ ("a") ++ (D) ++ ("c") ++ (D) ++ ("cccabacc") ++ (D) ++ ("accacbacccacccccba") ++ (D) ++ ("acc") ++ (D) ++ ("acacaabcaa"))
    =
    (("cbca") ++ (D) ++ ("abc") ++ (D) ++ ("ccca") ++ (D) ++ ("accbaccac") ++ (D) ++ ("acccaccccc") ++ (D) ++ ("abaccbacacaa") ++ (D) ++ ("caa"));
constraint
  (("aacc") ++ (D) ++ ("aac") ++ (D) ++ ("aacbaaab") ++ (D) ++ ("cbcaabacaaccaca") ++ (D) ++ ("a") ++ (D) ++ ("aaacbaaacaacccc"))
    =
    (("aaccbaacbaac") ++ (D) ++ ("aaa") ++ (D) ++ (D) ++ ("cbcaabacaaccacababaaac") ++ (D) ++ ("aaacaacccc"));
constraint
  (("cccccca") ++ (D) ++ (D) ++ ("cc") ++ (D) ++ ("a") ++ (D) ++ ("ccca") ++ (D) ++ ("cacacacaaacaac") ++ (D) ++ (D) ++ (D) ++ ("cbcaacacbacaacc"))
    =
    (("cccccca") ++ (D) ++ (D) ++ ("cc") ++ (D) ++ ("a") ++ (D) ++ ("ccca") ++ (D) ++ ("cacacacaaacaacbb") ++ (D) ++ ("cbcaacac") ++ (D) ++ ("acaacc"));
constraint
  (("aa") ++ (D) ++ (D) ++ ("bcb") ++ (D) ++ ("acb") ++ (D) ++ ("cabcccacbaaaacacccaaccbccbc") ++ (D) ++ ("caacaabcaab"))
    =
    (("aa") ++ (D) ++ ("bbcb") ++ (D) ++ ("acb") ++ (D) ++ ("cabcccac") ++ (D) ++ ("aaaacacccaacc") ++ (D) ++ ("ccbcbcaacaabcaa") ++ (D));
constraint
  ((D) ++ ("abccacb") ++ (D) ++ ("baab") ++ (D) ++ ("baabaccaa") ++ (D) ++ ("a") ++ (D) ++ ("bcacb") ++ (D) ++ ("aacbcaaaccccac") ++ (D) ++ ("aacc"))
    =
    (("babccacbb") ++ (D) ++ ("aa") ++ (D) ++ ("b") ++ (D) ++ ("aabaccaaba") ++ (D) ++ ("bcacb") ++ (D) ++ ("aacbcaaaccccac") ++ (D) ++ ("aacc"));
constraint
  (("abb") ++ (D) ++ ("ca") ++ (D) ++ ("ca") ++ (D) ++ ("bc") ++ (D) ++ ("abcabcca") ++ (D) ++ ("ccacaa") ++ (D) ++ ("accaacccacacaacc") ++ (D) ++ (D) ++ ("bbaa"))
    =
    (("abb") ++ (D) ++ ("cabcabbc") ++ (D) ++ ("a") ++ (D) ++ ("ca") ++ (D) ++ ("ccabccacaabaccaacccacacaaccb") ++ (D) ++ ("b") ++ (D) ++ ("aa"));
constraint
  (("cb") ++ (D) ++ ("bbaaa") ++ (D) ++ ("bca") ++ (D) ++ ("bbbcc") ++ (D) ++ (D) ++ ("bcaabbaca") ++ (D) ++ ("c") ++ (D) ++ (D) ++ ("caab") ++ (D) ++ ("c") ++ (D) ++ ("aacbc") ++ (D) ++ ("aaccc"))
    =
    (("c") ++ (D) ++ (D) ++ (D) ++ ("baaa") ++ (D) ++ ("bca") ++ (D) ++ (D) ++ (D) ++ (D) ++ ("ccbb") ++ (D) ++ ("caabbacabcbbcaa") ++ (D) ++ (D) ++ ("c") ++ (D) ++ ("aac") ++ (D) ++ ("cbaaccc"));
constraint
  (("a") ++ (D) ++ ("cba") ++ (D) ++ ("a") ++ (D) ++ ("ccacacb") ++ (D) ++ ("bc") ++ (D) ++ (D) ++ ("acabcabb") ++ (D) ++ ("abaa") ++ (D) ++ ("ccc") ++ (D) ++ (D) ++ ("cc") ++ (D) ++ ("accccaacb"))
    =
    (("a") ++ (D) ++ ("c") ++ (D) ++ ("ababccacac") ++ (D) ++ ("bbc") ++ (D) ++ (D) ++ ("acabcabb") ++ (D) ++ ("abaa") ++ (D) ++ ("cccb") ++ (D) ++ ("ccbaccccaac") ++ (D));
constraint
  (("b") ++ (D) ++ ("acb") ++ (D) ++ ("acaccaccacccbbacaaacbb") ++ (D) ++ (D) ++ (D) ++ ("cacaa") ++ (D) ++ ("accbb") ++ (D) ++ ("aca") ++ (D) ++ ("cbaa"))
    =
    (("bbacb") ++ (D) ++ ("acaccaccacccb") ++ (D) ++ ("acaaac") ++ (D) ++ ("b") ++ (D) ++ ("b") ++ (D) ++ ("cacaabacc") ++ (D) ++ ("b") ++ (D) ++ ("acabcbaa"));
constraint
  (("ccc") ++ (D) ++ ("a") ++ (D) ++ ("bcacacc") ++ (D) ++ ("bac") ++ (D) ++ ("a") ++ (D) ++ ("cccaa") ++ (D) ++ ("bbccbaa") ++ (D) ++ ("aaacccacacaaab") ++ (D) ++ (D) ++ ("a"))
    =
    (("cccba") ++ (D) ++ ("bcacaccb") ++ (D) ++ ("ac") ++ (D) ++ ("abcccaabbbcc") ++ (D) ++ ("aa") ++ (D) ++ ("aaacccacacaaab") ++ (D) ++ ("ba"));
constraint
  (("acacab") ++ (D) ++ ("a") ++ (D) ++ ("c") ++ (D) ++ ("bacabaa") ++ (D) ++ (D) ++ ("cb") ++ (D) ++ (D) ++ ("a") ++ (D) ++ ("aaacaa") ++ (D) ++ ("bcca") ++ (D) ++ ("cbcaaca") ++ (D) ++ ("cacb") ++ (D))
    =
    (("acaca") ++ (D) ++ ("babc") ++ (D) ++ (D) ++ ("acabaab") ++ (D) ++ ("cb") ++ (D) ++ ("ba") ++ (D) ++ ("aaacaab") ++ (D) ++ ("cca") ++ (D) ++ ("c") ++ (D) ++ ("caaca") ++ (D) ++ ("cacb") ++ (D));
constraint
  (("c") ++ (D) ++ ("c") ++ (D) ++ ("ac") ++ (D) ++ ("caccacabbbaabccaaa") ++ (D) ++ ("c") ++ (D) ++ ("c") ++ (D) ++ ("cbcac") ++ (D) ++ (D) ++ ("aacb") ++ (D) ++ (D) ++ ("ba") ++ (D) ++ ("ccac") ++ (D))
    =
    (("cbc") ++ (D) ++ ("acbcaccaca") ++ (D) ++ (D) ++ ("baa") ++ (D) ++ ("ccaaabc") ++ (D) ++ ("cbcbcac") ++ (D) ++ (D) ++ ("aac") ++ (D) ++ ("b") ++ (D) ++ (D) ++ ("abccac") ++ (D));
constraint
  (("ca") ++ (D) ++ ("cccaca") ++ (D) ++ ("b") ++ (D) ++ ("aab") ++ (D) ++ (D) ++ ("aacb") ++ (D) ++ ("b") ++ (D) ++ (D) ++ ("ccc") ++ (D) ++ ("cccccbbaaabca") ++ (D) ++ ("cbacbcb") ++ (D))
    =
    (("ca") ++ (D) ++ ("cccacab") ++ (D) ++ ("baabb") ++ (D) ++ ("aac") ++ (D) ++ ("b") ++ (D) ++ (D) ++ (D) ++ ("cccbccccc") ++ (D) ++ (D) ++ ("aaabcabc") ++ (D) ++ ("ac") ++ (D) ++ ("cbb"));
constraint
  (("aaa") ++ (D) ++ ("ba") ++ (D) ++ (D) ++ ("bbaccacabbbbaccbcccacccccbaccc") ++ (D) ++ ("bccaccccabca"))
    =
    (("aaabbabb") ++ (D) ++ ("baccacabb") ++ (D) ++ (D) ++ ("accbcccacccccbaccc") ++ (D) ++ (D) ++ ("ccacccca") ++ (D) ++ ("ca"));
constraint
  (("aca") ++ (D) ++ ("acb") ++ (D) ++ ("c") ++ (D) ++ ("bac") ++ (D) ++ ("ba") ++ (D) ++ (D) ++ ("c") ++ (D) ++ ("cccccaac") ++ (D) ++ ("cabcacb") ++ (D) ++ ("ccc") ++ (D) ++ ("ccaca") ++ (D) ++ ("caca"))
    =
    (("acabac") ++ (D) ++ (D) ++ ("c") ++ (D) ++ (D) ++ ("acbba") ++ (D) ++ (D) ++ ("c") ++ (D) ++ ("cccccaac") ++ (D) ++ ("cabcac") ++ (D) ++ (D) ++ ("ccc") ++ (D) ++ ("ccacabcaca"));
constraint
  ((D) ++ ("cbbcaaca") ++ (D) ++ ("caaacabaac") ++ (D) ++ ("acbbcaac") ++ (D) ++ (D) ++ ("aa") ++ (D) ++ ("bcc") ++ (D) ++ ("aa") ++ (D) ++ ("acab") ++ (D) ++ ("ccabc"))
    =
    (("bc") ++ (D) ++ ("bcaaca") ++ (D) ++ ("caaacabaac") ++ (D) ++ ("ac") ++ (D) ++ (D) ++ ("caacb") ++ (D) ++ ("aab") ++ (D) ++ ("cc") ++ (D) ++ ("aa") ++ (D) ++ ("aca") ++ (D) ++ ("bcca") ++ (D) ++ ("c"));
constraint
  (("acaaacabacacacaaccccaacacaaacbacc") ++ (D) ++ ("ac") ++ (D) ++ ("c") ++ (D) ++ ("aa") ++ (D) ++ ("a") ++ (D) ++ ("cb") ++ (D) ++ ("a") ++ (D) ++ ("bc"))
    =
    (("acaaacabacacacaaccccaacacaaacbaccbacbcbaaba") ++ (D) ++ ("cb") ++ (D) ++ ("abbc"));
constraint
  ((D) ++ ("aaacaabc") ++ (D) ++ ("ccaccca") ++ (D) ++ ("aaca") ++ (D) ++ ("ab") ++ (D) ++ (D) ++ ("cac") ++ (D) ++ ("acacacbaaabb") ++ (D) ++ ("aaacbcc"))
    =
    ((D) ++ ("aaacaa") ++ (D) ++ ("cbccacccabaacaba") ++ (D) ++ (D) ++ (D) ++ ("cac") ++ (D) ++ ("acacac") ++ (D) ++ ("aaabbbaaacbcc"));
constraint
  ((D) ++ ("aaabaaaacabaca") ++ (D) ++ ("ac") ++ (D) ++ ("cccaacacbccaaccacccccaabcaaccaaa"))
    =
    ((D) ++ ("aaabaaaaca") ++ (D) ++ ("acabacbcccaacac") ++ (D) ++ ("ccaaccacccccaa") ++ (D) ++ ("caaccaaa"));
constraint
  (("ccba") ++ (D) ++ ("cabbcabbaaaacaa") ++ (D) ++ ("abc") ++ (D) ++ (D) ++ (D) ++ ("bacccbccba") ++ (D) ++ ("cacaacaaaa") ++ (D) ++ ("ca"))
    =
    (("cc") ++ (D) ++ ("abcab") ++ (D) ++ ("ca") ++ (D) ++ ("baaaacaaba") ++ (D) ++ ("c") ++ (D) ++ ("b") ++ (D) ++ ("bacccbccba") ++ (D) ++ ("cacaacaaaabca"));
constraint
  (("aaaaaccacca") ++ (D) ++ ("cccaaaaaa") ++ (D) ++ ("aabccbacbcbacbcacaa") ++ (D) ++ (D) ++ ("b") ++ (D) ++ ("caccab"))
    =
    (("aaaaaccaccabcccaaaaaabaabccbac") ++ (D) ++ ("cbacbcacaa") ++ (D) ++ (D) ++ (D) ++ (D) ++ ("caccab"));
constraint
  (("ccaaaaacaa") ++ (D) ++ ("bcaccbac") ++ (D) ++ ("bcabacac") ++ (D) ++ ("bcaba") ++ (D) ++ ("aa") ++ (D) ++ ("cb") ++ (D) ++ ("ab") ++ (D) ++ ("c") ++ (D) ++ ("cbcca"))
    =
    (("ccaaaaacaa") ++ (D) ++ ("bcaccbac") ++ (D) ++ ("bca") ++ (D) ++ ("acacb") ++ (D) ++ ("cababaa") ++ (D) ++ ("cb") ++ (D) ++ ("a") ++ (D) ++ ("bcbcbcca"));
constraint
  ((D) ++ ("ba") ++ (D) ++ ("cbaaaaaabb") ++ (D) ++ ("cca") ++ (D) ++ ("cacccaacbaccccaabaaccacaacaacbaa"))
    =
    (("b") ++ (D) ++ ("a") ++ (D) ++ ("c") ++ (D) ++ ("aaaaaa") ++ (D) ++ (D) ++ ("bcca") ++ (D) ++ ("cacccaacbaccccaa") ++ (D) ++ ("aaccacaacaac") ++ (D) ++ ("aa"));
constraint
  (("a") ++ (D) ++ ("baac") ++ (D) ++ ("cbb") ++ (D) ++ ("cbabc") ++ (D) ++ ("c") ++ (D) ++ ("bcbbbaca") ++ (D) ++ ("bccbabca") ++ (D) ++ ("aacbaabaacccac"))
    =
    (("a") ++ (D) ++ ("baacbc") ++ (D) ++ (D) ++ (D) ++ ("cbabcbc") ++ (D) ++ (D) ++ ("cbbbacabbccbabca") ++ (D) ++ ("aacbaa") ++ (D) ++ ("aacccac"));
constraint
  (("bca") ++ (D) ++ ("aaaa") ++ (D) ++ ("aac") ++ (D) ++ ("aaaacba") ++ (D) ++ ("ccb") ++ (D) ++ (D) ++ ("c") ++ (D) ++ ("a") ++ (D) ++ ("cbcaacb") ++ (D) ++ ("b") ++ (D) ++ (D) ++ ("bbca") ++ (D) ++ ("c") ++ (D) ++ ("ac") ++ (D))
    =
    ((D) ++ ("ca") ++ (D) ++ ("aaaa") ++ (D) ++ ("aac") ++ (D) ++ ("aaaac") ++ (D) ++ ("abcc") ++ (D) ++ (D) ++ ("bcbabc") ++ (D) ++ ("caac") ++ (D) ++ ("b") ++ (D) ++ ("bbbbcabcbacb"));
constraint
  (("caca") ++ (D) ++ ("ac") ++ (D) ++ ("bcabbacabaaaaaacacc") ++ (D) ++ ("aa") ++ (D) ++ ("ca") ++ (D) ++ ("acaac") ++ (D) ++ ("accca") ++ (D) ++ ("caccc"))
    =
    (("cacabac") ++ (D) ++ (D) ++ ("cab") ++ (D) ++ ("acabaaaaaacaccbaa") ++ (D) ++ ("ca") ++ (D) ++ ("acaac") ++ (D) ++ ("accca") ++ (D) ++ ("caccc"));
constraint
  (("aabbca") ++ (D) ++ ("cbbc") ++ (D) ++ ("caacab") ++ (D) ++ ("bacba") ++ (D) ++ ("bbb") ++ (D) ++ (D) ++ ("caaaaacbbcc") ++ (D) ++ ("cccb") ++ (D) ++ ("a") ++ (D) ++ ("aa"))
    =
    (("aabbca") ++ (D) ++ ("c") ++ (D) ++ (D) ++ ("c") ++ (D) ++ ("caaca") ++ (D) ++ ("b") ++ (D) ++ ("acba") ++ (D) ++ ("b") ++ (D) ++ ("bbbcaaaaacbbccbccc") ++ (D) ++ ("ba") ++ (D) ++ ("aa"));
constraint
  (("aaaab") ++ (D) ++ ("cccbbbca") ++ (D) ++ (D) ++ ("cca") ++ (D) ++ ("acbcbcccbb") ++ (D) ++ (D) ++ (D) ++ ("b") ++ (D) ++ ("cacba") ++ (D) ++ ("bcca") ++ (D) ++ (D) ++ ("cacb"))
    =
    (("aaaabbccc") ++ (D) ++ ("bbcab") ++ (D) ++ ("ccabac") ++ (D) ++ ("cbccc") ++ (D) ++ ("bbb") ++ (D) ++ (D) ++ (D) ++ ("cac") ++ (D) ++ ("a") ++ (D) ++ ("bcca") ++ (D) ++ ("bcacb"));
constraint
  (("aaaacac") ++ (D) ++ ("cbcbcbbccccbccccccc") ++ (D) ++ ("bcaacacca") ++ (D) ++ ("ac") ++ (D) ++ ("accbbccaac"))
    =
    (("aaaacacbcbc") ++ (D) ++ ("c") ++ (D) ++ ("bcccc") ++ (D) ++ ("cccccccb") ++ (D) ++ ("caacaccabac") ++ (D) ++ ("accbbccaac"));
constraint
  ((D) ++ ("bcaaab") ++ (D) ++ ("bcaaccc") ++ (D) ++ ("acaaaacaaabccaaccaaa") ++ (D) ++ ("cccabc") ++ (D) ++ ("b") ++ (D) ++ ("caabb"))
    =
    ((D) ++ (D) ++ ("caaab") ++ (D) ++ ("bcaacccbacaaaacaaabccaaccaaabcccabcbbbcaa") ++ (D) ++ (D));
constraint
  (("cac") ++ (D) ++ (D) ++ ("caaacaacbaab") ++ (D) ++ (D) ++ (D) ++ ("cccacaaa") ++ (D) ++ ("cbca") ++ (D) ++ ("aa") ++ (D) ++ ("acaaacc") ++ (D) ++ ("cccaac"))
    =
    (("cac") ++ (D) ++ (D) ++ ("caaacaac") ++ (D) ++ ("aa") ++ (D) ++ (D) ++ (D) ++ ("bcccacaaa") ++ (D) ++ ("cbcabaabacaaaccbcccaac"));
constraint
  (("ccaba") ++ (D) ++ ("aabc") ++ (D) ++ ("accaaccaa") ++ (D) ++ ("abacccaca") ++ (D) ++ ("abacbcbcccccba") ++ (D) ++ (D) ++ ("c") ++ (D) ++ ("ca"))
    =
    (("ccaba") ++ (D) ++ ("aabcbaccaaccaa") ++ (D) ++ ("a") ++ (D) ++ ("acccaca") ++ (D) ++ ("a") ++ (D) ++ ("ac") ++ (D) ++ ("cbcccccba") ++ (D) ++ (D) ++ ("c") ++ (D) ++ ("ca"));
constraint
  (("acaacccbbcaaabccacccaacbccbc") ++ (D) ++ ("abaacbbcbbbb") ++ (D) ++ ("aa") ++ (D) ++ ("c") ++ (D) ++ ("acca"))
    =
    (("acaacccb") ++ (D) ++ ("caaa") ++ (D) ++ ("ccacccaac") ++ (D) ++ ("cc") ++ (D) ++ ("cba") ++ (D) ++ ("aacbbcbb") ++ (D) ++ ("bbaabc") ++ (D) ++ ("acca"));
constraint
  ((D) ++ (D) ++ ("acc") ++ (D) ++ ("c") ++ (D) ++ ("cccaccacabcacaccc") ++ (D) ++ ("c") ++ (D) ++ (D) ++ ("aabccc") ++ (D) ++ (D) ++ ("bacac") ++ (D) ++ ("a") ++ (D) ++ ("a") ++ (D) ++ ("acac"))
    =
    (("b") ++ (D) ++ ("acc") ++ (D) ++ ("cbcccaccacabcacaccc") ++ (D) ++ ("cb") ++ (D) ++ ("aabccc") ++ (D) ++ (D) ++ ("bacac") ++ (D) ++ ("a") ++ (D) ++ ("abacac"));
constraint
  (("abcca") ++ (D) ++ ("bcc") ++ (D) ++ ("ccabacca") ++ (D) ++ ("b") ++ (D) ++ ("c") ++ (D) ++ ("cac") ++ (D) ++ ("bc") ++ (D) ++ (D) ++ ("acccabccaabaccc") ++ (D) ++ (D) ++ ("abb"))
    =
    (("abccabbccbccabaccab") ++ (D) ++ (D) ++ ("cbcac") ++ (D) ++ ("bcbbaccca") ++ (D) ++ ("ccaa") ++ (D) ++ ("accc") ++ (D) ++ (D) ++ ("a") ++ (D) ++ (D));
constraint
  (("a") ++ (D) ++ ("ca") ++ (D) ++ ("ac") ++ (D) ++ (D) ++ (D) ++ ("aaa") ++ (D) ++ ("cbbcabcbcbccccaacabcacbacacbcccc") ++ (D) ++ ("baba"))
    =
    (("a") ++ (D) ++ ("cabac") ++ (D) ++ (D) ++ (D) ++ ("aaabcb") ++ (D) ++ ("ca") ++ (D) ++ ("cbcbccccaacabcacbacac") ++ (D) ++ ("ccccbba") ++ (D) ++ ("a"));
constraint
  (("aacacbcaab") ++ (D) ++ (D) ++ ("b") ++ (D) ++ ("accac") ++ (D) ++ ("bcaacccacacaaac") ++ (D) ++ ("cacacabb") ++ (D) ++ (D) ++ ("ca") ++ (D) ++ ("a") ++ (D))
    =
    (("aacac") ++ (D) ++ ("caabbb") ++ (D) ++ (D) ++ ("accac") ++ (D) ++ ("bcaacccacacaaac") ++ (D) ++ ("cacacabbb") ++ (D) ++ ("ca") ++ (D) ++ ("ab"));
constraint
  ((D) ++ (D) ++ ("ab") ++ (D) ++ ("caac") ++ (D) ++ ("cccaaaaab") ++ (D) ++ (D) ++ ("bcbca") ++ (D) ++ ("cbcc") ++ (D) ++ ("c") ++ (D) ++ ("a") ++ (D) ++ (D) ++ ("ccbbbb") ++ (D) ++ ("cbacaa") ++ (D))
    =
    ((D) ++ ("ba") ++ (D) ++ (D) ++ ("caac") ++ (D) ++ ("cccaaaaabb") ++ (D) ++ ("bc") ++ (D) ++ ("ca") ++ (D) ++ ("cbccbcba") ++ (D) ++ ("bccbbbbbcbacaa") ++ (D));
constraint
  (("aa") ++ (D) ++ (D) ++ (D) ++ ("cbaba") ++ (D) ++ (D) ++ ("bccaca") ++ (D) ++ (D) ++ ("accbaacacaccaa") ++ (D) ++ (D) ++ ("ccbaacbccbcacba"))
    =
    (("aa") ++ (D) ++ (D) ++ ("bc") ++ (D) ++ ("ababbbccaca") ++ (D) ++ (D) ++ ("acc") ++ (D) ++ ("aacacaccaa") ++ (D) ++ ("bccbaacbcc") ++ (D) ++ ("cac") ++ (D) ++ ("a"));
constraint
  (("ccabc") ++ (D) ++ ("bacacaacacaa") ++ (D) ++ ("a") ++ (D) ++ ("cacccbccacacaccacba") ++ (D) ++ ("ccbb") ++ (D) ++ ("cbaaa"))
    =
    (("cca") ++ (D) ++ ("cbbacacaacacaaba") ++ (D) ++ ("cacccbccacacaccac") ++ (D) ++ ("a") ++ (D) ++ ("ccbbbc") ++ (D) ++ ("aaa"));
constraint
  (("bba") ++ (D) ++ (D) ++ (D) ++ ("bbcc") ++ (D) ++ ("cabab") ++ (D) ++ ("ac") ++ (D) ++ ("cacccab") ++ (D) ++ ("a") ++ (D) ++ ("aca") ++ (D) ++ (D) ++ ("abbcaabbccaabacc"))
    =
    ((D) ++ ("babbb") ++ (D) ++ ("bccbca") ++ (D) ++ ("abbac") ++ (D) ++ ("caccca") ++ (D) ++ (D) ++ ("abacabbab") ++ (D) ++ ("caab") ++ (D) ++ ("ccaabacc"));
constraint
  (("bbaaaaaaac") ++ (D) ++ ("cbabcccaac") ++ (D) ++ ("abcbaaac") ++ (D) ++ (D) ++ ("b") ++ (D) ++ ("bc") ++ (D) ++ ("cb") ++ (D) ++ ("ab") ++ (D) ++ ("a") ++ (D) ++ ("a") ++ (D) ++ ("cbab"))
    =
    (("b") ++ (D) ++ ("aaaaaaacbc") ++ (D) ++ ("a") ++ (D) ++ ("cccaacbabcbaaacb") ++ (D) ++ (D) ++ ("b") ++ (D) ++ ("c") ++ (D) ++ ("cb") ++ (D) ++ ("abba") ++ (D) ++ ("a") ++ (D) ++ ("cba") ++ (D));
constraint
  ((D) ++ ("caab") ++ (D) ++ ("acaaa") ++ (D) ++ ("acabab") ++ (D) ++ ("cc") ++ (D) ++ (D) ++ ("cccc") ++ (D) ++ ("accccaabc") ++ (D) ++ ("baaabc") ++ (D) ++ ("abacba"))
    =
    ((D) ++ ("caa") ++ (D) ++ ("bacaaa") ++ (D) ++ ("acababbccb") ++ (D) ++ ("ccccbaccccaa") ++ (D) ++ ("cbbaaa") ++ (D) ++ ("c") ++ (D) ++ ("abac") ++ (D) ++ ("a"));
constraint
  (("a") ++ (D) ++ ("aca") ++ (D) ++ ("abbcaa") ++ (D) ++ ("ccb") ++ (D) ++ ("baaaaa") ++ (D) ++ ("aaccaabc") ++ (D) ++ ("ccccbc") ++ (D) ++ ("ccacabbaccc"))
    =
    (("abaca") ++ (D) ++ ("a") ++ (D) ++ (D) ++ ("caabcc") ++ (D) ++ ("b") ++ (D) ++ ("aaaaabaaccaa") ++ (D) ++ ("cbccccbcbccaca") ++ (D) ++ (D) ++ ("accc"));
constraint
  (("abca") ++ (D) ++ ("c") ++ (D) ++ ("aa") ++ (D) ++ ("cb") ++ (D) ++ (D) ++ ("cac") ++ (D) ++ ("acac") ++ (D) ++ ("a") ++ (D) ++ (D) ++ ("a") ++ (D) ++ ("cca") ++ (D) ++ ("aaccb") ++ (D) ++ (D) ++ ("bacbbaccbaba"))
    =
    (("abca") ++ (D) ++ ("cbaabc") ++ (D) ++ (D) ++ (D) ++ ("cac") ++ (D) ++ ("acacbabbabccabaacc") ++ (D) ++ ("b") ++ (D) ++ (D) ++ ("ac") ++ (D) ++ ("bacc") ++ (D) ++ ("aba"));
constraint
  ((D) ++ ("bbaccac") ++ (D) ++ ("b") ++ (D) ++ (D) ++ ("cbaa") ++ (D) ++ (D) ++ ("accaa") ++ (D) ++ ("b") ++ (D) ++ ("bcaa") ++ (D) ++ ("ababaccc") ++ (D) ++ ("a") ++ (D) ++ ("abac") ++ (D) ++ ("acb") ++ (D))
    =
    ((D) ++ ("b") ++ (D) ++ ("accacb") ++ (D) ++ ("b") ++ (D) ++ ("c") ++ (D) ++ ("aab") ++ (D) ++ ("accaa") ++ (D) ++ ("b") ++ (D) ++ ("bcaababa") ++ (D) ++ ("acccbababac") ++ (D) ++ ("ac") ++ (D) ++ ("b"));
constraint
  (("b") ++ (D) ++ ("baabccabacaabaabcccacacbb") ++ (D) ++ ("cc") ++ (D) ++ ("acc") ++ (D) ++ (D) ++ ("cacba") ++ (D) ++ ("caaa") ++ (D) ++ ("a") ++ (D) ++ ("ca"))
    =
    (("bb") ++ (D) ++ ("aa") ++ (D) ++ ("cca") ++ (D) ++ ("acaa") ++ (D) ++ ("aa") ++ (D) ++ ("cccacacb") ++ (D) ++ (D) ++ ("ccbaccbbcac") ++ (D) ++ ("abcaaababca"));
constraint
  (("aaa") ++ (D) ++ (D) ++ ("cccaaacccab") ++ (D) ++ ("aacaaab") ++ (D) ++ ("acabacc") ++ (D) ++ ("cac") ++ (D) ++ ("c") ++ (D) ++ ("caa") ++ (D) ++ ("aacaa") ++ (D) ++ ("ab"))
    =
    (("aaab") ++ (D) ++ ("cccaaacccab") ++ (D) ++ ("aacaaabbaca") ++ (D) ++ ("acc") ++ (D) ++ ("cac") ++ (D) ++ ("cbcaabaacaa") ++ (D) ++ ("a") ++ (D));
constraint
  (("a") ++ (D) ++ (D) ++ ("baaacaaab") ++ (D) ++ ("caaaaaaccbabcbbcccacaa") ++ (D) ++ ("aaaba") ++ (D) ++ ("aca") ++ (D) ++ ("bacac"))
    =
    (("a") ++ (D) ++ (D) ++ (D) ++ ("aaacaaabbcaaaaaacc") ++ (D) ++ ("abcb") ++ (D) ++ ("cccacaabaaa") ++ (D) ++ ("a") ++ (D) ++ ("acab") ++ (D) ++ ("acac"));
constraint
  (("aaac") ++ (D) ++ ("ccaabba") ++ (D) ++ ("bcacbbccccbca") ++ (D) ++ ("acabc") ++ (D) ++ ("caac") ++ (D) ++ ("aaab") ++ (D) ++ (D) ++ (D) ++ ("bca") ++ (D) ++ (D) ++ ("a"))
    =
    (("aaacbccaa") ++ (D) ++ (D) ++ ("a") ++ (D) ++ ("bcac") ++ (D) ++ ("bccccbca") ++ (D) ++ ("aca") ++ (D) ++ ("cbcaac") ++ (D) ++ ("aaa") ++ (D) ++ ("bbbbcabba"));
constraint
  (("caa") ++ (D) ++ (D) ++ (D) ++ ("bbaca") ++ (D) ++ ("a") ++ (D) ++ ("c") ++ (D) ++ ("acaa") ++ (D) ++ ("acccbaccbaaa") ++ (D) ++ ("bbaaaaaababcccac") ++ (D))
    =
    (("caa") ++ (D) ++ (D) ++ ("bbbacaba") ++ (D) ++ ("c") ++ (D) ++ ("acaabaccc") ++ (D) ++ ("accbaaa") ++ (D) ++ ("bbaaaaaababcccacb"));
constraint
  (("aaa") ++ (D) ++ ("accaacc") ++ (D) ++ ("bc") ++ (D) ++ ("ccbaccaccaab") ++ (D) ++ ("ccba") ++ (D) ++ ("cbcaaacaacacca") ++ (D) ++ ("ca") ++ (D))
    =
    (("aaabaccaacc") ++ (D) ++ ("bc") ++ (D) ++ ("ccbaccaccaabbcc") ++ (D) ++ ("a") ++ (D) ++ ("c") ++ (D) ++ ("caaacaacacca") ++ (D) ++ ("cab"));
constraint
  (("c") ++ (D) ++ (D) ++ (D) ++ ("bc") ++ (D) ++ ("c") ++ (D) ++ ("accaab") ++ (D) ++ ("aa") ++ (D) ++ ("cab") ++ (D) ++ ("a") ++ (D) ++ ("ccbc") ++ (D) ++ ("a") ++ (D) ++ ("aacc") ++ (D) ++ ("bccacccaabcaba"))
    =
    (("c") ++ (D) ++ ("b") ++ (D) ++ (D) ++ ("cbc") ++ (D) ++ ("accaa") ++ (D) ++ ("baa") ++ (D) ++ ("ca") ++ (D) ++ ("babccbc") ++ (D) ++ ("abaacc") ++ (D) ++ ("bccacccaa") ++ (D) ++ ("caba"));
constraint
  (("baa") ++ (D) ++ ("a") ++ (D) ++ ("a") ++ (D) ++ ("c") ++ (D) ++ (D) ++ ("b") ++ (D) ++ ("ccbcbaaaccba") ++ (D) ++ ("cacccaabacbaa") ++ (D) ++ ("a") ++ (D) ++ ("caaa") ++ (D) ++ ("cac") ++ (D))
    =
    (("baa") ++ (D) ++ ("aba") ++ (D) ++ ("cb") ++ (D) ++ ("b") ++ (D) ++ ("cc") ++ (D) ++ ("cbaaaccbabcacccaabacbaababcaaabcacb"));
solve satisfy;
