var string: B;
var string: A;
var string: C;
constraint
  (("cceeefebcdaef") ++ (B) ++ ("fdaacaddf")) =
    (("cceeefebcdaefefabbfcc") ++ (C) ++ ("beafdedcffdeacdbefbbfffaafdcfaedbeccbdddafdaacaddf"));
constraint
  (("bfdcf") ++ (B) ++ ("fdefacbefcdfb")) =
    (("bfdcf") ++ (B) ++ ("fdefacbefcdfb"));
constraint
  (("ddabeefeaafbbeeefbcedddaaddaf") ++ (B) ++ ("bdadddaaffeccebcafbacadedacbcdcebbffb"))
    =
    (("ddabeefeaafbbeeefbcedddaadda") ++ (C) ++ ("cfbbcaffabbdadddaaffeccebcafbacadedacbcdcebbffb"));
constraint
  (("defaaedffccebbfdeadbeafcafbffcfbdfbbedfffbdbbbbcfdcceebbacabbebfeedfefcbfddadddf") ++ (""))
    =
    (("defaaedffccebbfdeadbea") ++ (C) ++ ("ffcfbdfbbedfffbdbbbbcfdcceebbacabbebfeedfefcbfddadddf"));
constraint
  (("adcdacfaefdefceeeceffdaccfabbbddbffbaabddebdbecdddc") ++ (C) ++ ("dfceebbcaabdbbecdffbeced"))
    =
    (("adcdacfaefdefceeeceffdaccfabbbddbffbaabddebdbecdddcfcafbdfceebbcaabdbbecdffbeced") ++ (""));
constraint
  (("eeaafaacbaeeaeebfeffaaeeefcebdbfffabddedddfecbfdbfcefabdaabbaeaaefc") ++ (C) ++ ("fdedecdb"))
    =
    (("eeaafaacbaeeaeebfeffaaeeefcebdbfffabddedddfecbfdbfcefabdaabbaeaaefcfcafbfdedecdb") ++ (""));
constraint
  (("ccfedcefdbddfcebbfeaecedffbfecdfddecabdffefcafbadfabfafabfffdfffdddeeabbdcabbdef") ++ (""))
    =
    (("ccfedcefdbddfcebbfeaecedffbfecdfddecabdffe") ++ (C) ++ ("adfabfafabfffdfffdddeeabbdcabbdef"));
constraint
  (("affaeeffdaccd") ++ (C) ++ ("bcdbbdfadcfcabacabbfcdffbefaeefbaeefeffafbcfcfacebaabadddcdafc"))
    =
    (("affaeeffdaccdfcafbbcdbbdfadcfcabacabbfcdffbefaeefbaeefeffafbcfcfacebaabadddcdafc") ++ (""));
constraint
  (("dcfecbcacebcdbfaffddeafacdeeddfaeeefdcabffacbbeabfacacbbebdb") ++ (C) ++ ("fdcefecebebedde"))
    =
    (("dcfecbcacebcdbfaffddeafacdeeddfaeeefdcabffacbbeabfacacbbebdbfcafbfdcefecebebedde") ++ (""));
constraint
  (("bbefeaabceaabf") ++ (C) ++ ("eedfeceedeafdddaffffaceacacceababaccfcacdbaaeffaacbebdacfdfbb"))
    =
    (("bbefeaabceaabffcafbeedfeceedeafdddaffffaceacacceababaccfcacdbaaeffaacbebdacfdfbb") ++ (""));
constraint
  (("debeeceafabedcbdbabddabf") ++ (A) ++ ("deefffccfbfcbedbbbdbbedaddedebbacfbcfdefdeeb"))
    =
    (("debeeceafabedcbdbabddabffecceeafaabadeefffccfbfcbedbbbdbbedaddedebbacfbcfdefdeeb") ++ (""));
constraint
  (("eaabadddecadfedfeafaabcceacdeeaabaeefcaaeedacbfcbdededeebeedbaafeabdebccbfcabfcd") ++ (""))
    =
    (("eaabadddecadfedf") ++ (B) ++ ("bcceacdeeaabaeefcaaeedacbfcbdededeebeedbaafeabdebccbfcabfcd"));
constraint
  (("beeffebfefdebfbcacaceaffeefefaee") ++ (B) ++ ("bfbdcdeecbfefedceceadddcdeddfadbdbcfcbffcbb"))
    =
    (("beeffebfefdebfbcacaceaffeefefaee") ++ (B) ++ ("bfbdcdeecbfefedceceadddcdeddfadbdbcfcbffcbb"));
constraint
  (("dcbfabbcdafbeb") ++ (B) ++ ("fbedecabdfbefabbcfcdcfefaaddeeaceefafefddceadeefadecacbfaabdf"))
    =
    (("dcbfabbcdafbebeafaafbedecabdfbefabbcfcdcfefaaddeeaceefafefddceadeefadecacbfaabdf") ++ (""));
constraint
  (("beccbdccfadaceddaaeefeecbcdccaaad") ++ (B) ++ ("bffddfeebdeeccdffabdcbeccafaeaeefbefccdfcb"))
    =
    (("beccbdccfadaceddaaeefeecbcdccaaadeafaabffddfeebdeeccdffabdcbeccafaeaeefbefccdfcb") ++ (""));
constraint
  (("bcebabbbeffbacbeac") ++ (B) ++ ("eeffffcbdacdeddffafeceebacbadeecfbccdbeaeabaddeddbbcacfbd"))
    =
    (("bcebabbbeffbacbeaceafaaeeffffcbdacdeddffafeceebacbadeecfbccdbeaeabaddeddbbcacfbd") ++ (""));
constraint
  (("cbbbceeaffbaedfdccdfbcebcebbccbeeafaadbbfffecfbfeafbffdbccbbaeacfcbbffacafcefccd") ++ (""))
    =
    (("cbbbceeaffbaedfdccdfbcebcebbccbe") ++ (B) ++ ("dbbfffecfbfeafbffdbccbbaeacfcbbffacafcefccd"));
constraint
  (("aaebafbadfaccddbcd") ++ (A) ++ ("eabdb") ++ (B) ++ ("eaaaadedcdef")) =
    (("aaebafbadfaccddbc") ++ (C) ++ ("fbeabdb") ++ (B) ++ ("eaaaadedcdef"));
constraint
  (("bcbeedbdabaecdcbfacacdbfebdafcabddcebfeeaddbdbaebdbeecdcbefcdfccdfaaaeccfcbebbfb") ++ (""))
    =
    (("bcbeedbdabaecdcbfacacdbfebdafcabddcebfeea") ++ (C) ++ ("baebdbeecdcbefcdfccdfaaaeccfcbebbfb"));
constraint
  (("ffaaacdcaadbecaafcbdeabfbffadabfdebaebbcfdbdf") ++ (C) ++ ("cabbafeaadccceccddaffcdedcccccd"))
    =
    (("ffaaacdcaadbecaafcbdeabfbffadabfdebaebbcfdbdf") ++ (C) ++ ("cabbafeaadccceccddaffcdedcccccd"));
constraint
  (("aeeedccaebccbadfadfececadbddbeacffdebdfedccacdfbffeeedffbadedfddecdf") ++ (C) ++ ("feaadffd"))
    =
    (("aeeedccaebccbadfadfececadbddbeacffdebdfedccacdfbffeeedffbadedfddecdf") ++ (C) ++ ("feaadffd"));
constraint
  (("cadcbfcdabffffbcccdbdfbdceccbddcbddadbfbefedebabdcbadffccbfebfbfbbddcabaedefabdf") ++ (""))
    =
    (("cadcbfcdabffffbccc") ++ (A) ++ ("dceccbddcbddadbfbefedebabdcbadffccbfebfbfbbddcabaedefabdf"));
constraint
  (("bd") ++ (C) ++ ("badddcbdbccdefbdedfcefbbeefeebedbbbbefdfeeabffaafdcaaafafedecfeedffecdaeee"))
    =
    (("bdddbdbadddcbdbccdefbdedfcefbbeefeebedbbbbefdfeeabffaafdcaaafafedecfeedffecdaeee") ++ (""));
constraint
  (("bdbaadccaaadeaefbbcbafababbadfef") ++ (C) ++ ("bfbbbbfcdffccadcfdcaebedfebfadfedcbdadeacccd"))
    =
    (("bdbaadccaaadeaefbbcbafababbadfefddbdbfbbbbfcdffccadcfdcaebedfebfadfedcbdadeacccd") ++ (""));
constraint
  (("dcaebebbfbfdddefbbfbcccaceacdedaddafeabadcbccddacccccdfadfdbcddabeaeedceed") ++ (C) ++ ("ef"))
    =
    (("dcaebebbfbfdddefbbfbcccaceacdedaddafeabadcbccddacccccdfadfdbcddabeaeedceed") ++ (C) ++ ("ef"));
constraint
  (("cedbeadfefffcb") ++ (C) ++ ("cbcaafeeedbedaabddeabccccececbfedfcfebaefcbbaddabcffedaacafbea"))
    =
    (("cedbeadfefffcbddbdcbcaafeeedbedaabddeabccccececbfedfcfebaefcbbaddabcffedaacafbea") ++ (""));
constraint
  (("afdcbdebcebfccfbaacadfbebabfdccdaadfda") ++ (C) ++ ("a") ++ (C) ++ ("aecbceeedfcfbccabfcffffadcfaffcbd"))
    =
    (("afdcbdebcebfccfbaacadfbebabfdccdaadfdaddbdaddbdaecbceeedfcfbccabfcffffadcfaffcbd") ++ (""));
constraint
  (("dddbdeaedefaadafeddccdeeaedacbfbafbfccfbceefbafafabdafacacbecdbdcafeccaceabaacda") ++ (""))
    =
    (("d") ++ (C) ++ ("eaedefaadafeddccdeeaedacbfbafbfccfbceefbafafabdafacacbecdbdcafeccaceabaacda"));
constraint
  (("cbeadfddeaddacaccaedbfcaabbcdcadacfeabaeddcabbdedafaf") ++ (C) ++ ("aadaaacccdfefacdbfcacef"))
    =
    (("cbeadfddeaddacaccaedbfcaabbcdcadacfeabaeddcabbdedafaf") ++ (C) ++ ("aadaaacccdfefacdbfcacef"));
constraint
  (("dbcacebacedbcafcaddcafeeeffecacfaaceedfcfedfbbdf") ++ (C) ++ ("ddbcffbaccdeabbdeaaeaaedfdff"))
    =
    (("dbcacebacedbcafcaddcafeeeffecacfaaceedfcfedfbbdfddbdddbcffbaccdeabbdeaaeaaedfdff") ++ (""));
constraint
  (("dfeddedbbfaeecaabddeedaceaab") ++ (C) ++ ("dbcefbfdeaecdfddddccadfcfbffdccedaeedeaacdddffbc"))
    =
    (("dfeddedbbfaeecaabddeedaceaabddbddbcefbfdeaecdfddddccadfcfbffdccedaeedeaacdddffbc") ++ (""));
solve satisfy;
