var string: B;
var string: E;
var string: A;
var string: C;
var string: D;
constraint
  ((B) ++ (D) ++ ("aaaaaaaaaaaaaaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (B) ++ ("aaaa")) =
    ((B) ++ ("aaaaaaaaaaaa") ++ (D) ++ ("aaaa"));
constraint
  ((D) ++ ("aaaaaaaaaa") ++ (C) ++ ("aaaaaaaa")) =
    ((A) ++ ("aaaaaa") ++ (D) ++ ("aaaa"));
constraint ((B) ++ (B) ++ ("aaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint
  ((B) ++ (B) ++ ("aaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (B) ++ ("aaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (D) ++ ("aaaa")) =
    ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (B) ++ ("aaaa")) =
    ((B) ++ (B) ++ ("aaaa"));
constraint
  ((B) ++ (B) ++ ("aaaa")) =
    ((D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaa") ++ (D) ++ ("aaaa"));
constraint
  ((C) ++ ("aa") ++ (B) ++ ("aaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint ((B) ++ (B) ++ ("aaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (B) ++ ("aaaa")) =
    ((D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaa") ++ (D) ++ ("aaaa"));
constraint ((B) ++ (B) ++ ("aaaa")) = ((B) ++ (B) ++ ("aaaa"));
constraint ((B) ++ (B) ++ ("aaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint
  ((B) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ ("")) =
    ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint ((C) ++ (C) ++ ("aaaaaaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint
  ((B) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ ("")) =
    ((C) ++ ("aaaaaaaaaaaaaa") ++ (D) ++ ("aaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ ("")) =
    ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (B) ++ ("aaaa")) =
    ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint
  ((B) ++ (C) ++ ("aaaaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaa") ++ (D) ++ (D) ++ ("aaaa"));
constraint
  ((D) ++ ("aaaaaaaaaaaa") ++ (B) ++ ("aaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaa") ++ (D) ++ (D) ++ ("aaaa"));
constraint
  ((C) ++ ("aa") ++ (B) ++ ("aaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint ((B) ++ (B) ++ ("aaaa")) = ((D) ++ (B) ++ ("aaaaaaaaaaaaaaaa"));
constraint
  ((C) ++ ("aa") ++ (B) ++ ("aaaa")) = ((A) ++ ("aaaaaa") ++ (D) ++ ("aaaa"));
constraint ((B) ++ (C) ++ ("aaaaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint ((A) ++ (C)) = ((B) ++ (B) ++ ("aaaa"));
constraint
  ((B) ++ (C) ++ ("aaaaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((B) ++ (C) ++ ("aaaaaa")) =
    ((D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaa") ++ (D) ++ ("aaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (B) ++ ("aaaa")) =
    ((D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaa") ++ (D) ++ ("aaaa"));
constraint ((B) ++ (B) ++ ("aaaa")) = ((D) ++ (D) ++ (D) ++ ("aaaa"));
constraint
  ((B) ++ (B) ++ ("aaaa")) = ((D) ++ (D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ ("")) =
    ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (B) ++ ("aaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaa") ++ (D) ++ (D) ++ ("aaaa"));
constraint ((B) ++ (C) ++ ("aaaaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint ((B) ++ (B) ++ ("aaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint ((B) ++ (B) ++ ("aaaa")) = ((B) ++ (B) ++ ("aaaa"));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (B) ++ ("aaaa")) =
    ((D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaa") ++ (D) ++ ("aaaa"));
constraint ((B) ++ (B) ++ ("aaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint
  ((C) ++ ("aa") ++ (B) ++ ("aaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint
  ((E) ++ ("aaaaaaaaaa") ++ ("")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaa") ++ (D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaa") ++ (D) ++ ("aaaa")) =
    ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint ((C) ++ (C) ++ ("aaaaaaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint
  ((C) ++ ("aa") ++ (B) ++ ("aaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint
  ((C) ++ (C) ++ ("aaaaaaaa")) = ((B) ++ ("aaaaaaaaaaaa") ++ (D) ++ ("aaaa"));
constraint
  ((A) ++ (D) ++ ("aaaaaaaaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaa") ++ (D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((C) ++ ("aa") ++ (B) ++ ("aaaa")) =
    ((B) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  ((B) ++ (B) ++ ("aaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaa") ++ (D) ++ (D) ++ ("aaaa"));
constraint
  ((A) ++ (C)) =
    (("aaaaaaaaaaaaaaaaaaaaaaaa") ++ (D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((B) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ ("")) =
    ((B) ++ (B) ++ ("aaaa"));
constraint
  ((D) ++ ("aaaaaaaaaaaa") ++ (B) ++ ("aaaa")) =
    ((D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaa") ++ (D) ++ ("aaaa"));
constraint
  ((C) ++ ("aa") ++ (B) ++ ("aaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint
  ((B) ++ (C) ++ ("aaaaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaa") ++ (D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint ((B) ++ (C) ++ ("aaaaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (B) ++ ("aaaa")) =
    ((D) ++ (D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint ((B) ++ (C) ++ ("aaaaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint
  ((B) ++ (B) ++ ("aaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaa") ++ (D) ++ (D) ++ ("aaaa"));
constraint
  ((C) ++ (C) ++ ("aaaaaaaa")) =
    ((D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaa") ++ (D) ++ ("aaaa"));
constraint
  ((C) ++ ("aa") ++ (B) ++ ("aaaa")) = ((D) ++ (D) ++ (D) ++ ("aaaa"));
constraint
  ((D) ++ ("aaaaaaaaaaaa") ++ (B) ++ ("aaaa")) =
    ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint ((B) ++ (C) ++ ("aaaaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint
  ((B) ++ (C) ++ ("aaaaaa")) =
    ((D) ++ (D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint ((B) ++ (B) ++ ("aaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint ((B) ++ (C) ++ ("aaaaaa")) = ((D) ++ (D) ++ (D) ++ ("aaaa"));
constraint ((B) ++ (B) ++ ("aaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint ((A) ++ (C)) = ((D) ++ (D) ++ (D) ++ ("aaaa"));
constraint ((B) ++ (B) ++ ("aaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint
  ((B) ++ (C) ++ ("aaaaaa")) =
    ((B) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint ((A) ++ (C)) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint
  ((B) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ ("")) =
    ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint
  ((B) ++ (B) ++ ("aaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (D) ++ ("aaaa"));
constraint
  ((C) ++ ("aa") ++ (B) ++ ("aaaa")) =
    ((D) ++ (D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((C) ++ ("aa") ++ (B) ++ ("aaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint
  ((C) ++ ("aa") ++ (B) ++ ("aaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint
  ((B) ++ (C) ++ ("aaaaaa")) = ((A) ++ ("aaaaaa") ++ (D) ++ ("aaaa"));
constraint
  ((B) ++ (B) ++ ("aaaa")) =
    ((B) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (""));
constraint
  (("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ++ (C) ++ ("aaaaaaaa")) =
    ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint ((B) ++ (B) ++ ("aaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint ((B) ++ (C) ++ ("aaaaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint ((A) ++ (C)) = ((D) ++ (D) ++ (D) ++ ("aaaa"));
constraint
  ((B) ++ (B) ++ ("aaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaa") ++ (D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint ((B) ++ (B) ++ ("aaaa")) = ((D) ++ (B) ++ ("aaaaaaaaaaaaaaaa"));
constraint ((B) ++ (C) ++ ("aaaaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint ((B) ++ (C) ++ ("aaaaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint ((B) ++ (B) ++ ("aaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint
  ((A) ++ (C)) =
    (("aaaaaaaaaaaaaaaaaaaaaaaa") ++ (D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((C) ++ ("aa") ++ (B) ++ ("aaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaa") ++ (D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint ((A) ++ (D) ++ ("aaaaaaaaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint
  ((C) ++ ("aa") ++ (B) ++ ("aaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint ((C) ++ (C) ++ ("aaaaaaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint ((B) ++ (B) ++ ("aaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint ((C) ++ (C) ++ ("aaaaaaaa")) = ((D) ++ (D) ++ (D) ++ ("aaaa"));
constraint ((A) ++ (C)) = ((D) ++ (B) ++ ("aaaaaaaaaaaaaaaa"));
constraint
  ((C) ++ ("aa") ++ (B) ++ ("aaaa")) =
    (("aaaaaaaaaaaaaaaaaaaaaaaa") ++ (D) ++ ("aaaaaaaaaaaaaaaaaaaaaaaaaaaa"));
constraint
  ((C) ++ ("aa") ++ (B) ++ ("aaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint
  ((C) ++ ("aa") ++ (B) ++ ("aaaa")) = ((D) ++ (D) ++ (D) ++ ("aaaa"));
constraint ((B) ++ (B) ++ ("aaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
constraint
  ((E) ++ ("aaaaaaaaaa") ++ ("")) = ((C) ++ ("aa") ++ (B) ++ ("aaaa"));
constraint ((B) ++ (B) ++ ("aaaa")) = ((E) ++ ("aaaaaaaaaa") ++ (""));
solve satisfy;
