var string: B;
var string: A;
var string: C;
var string: D;
constraint
  (("badddcbcabb") ++ (C) ++ ("cacada")) =
    (("badddcbcab") ++ (D) ++ ("dcbbaddddcabbbbcbbbbcbdbbcdddccbbddbccddcbbcbbbacbdabcacada"));
constraint
  (("dbbcbadbadbacdbcddcbdabbdba") ++ (D) ++ ("dab")) =
    (("dbbcbadbadbacdbcddcbdabbdba") ++ (D) ++ ("dab"));
constraint
  (("cadaaabbbccbbddabbdadbbabcbdabaccbccbdbadccaccacdaacbcabdddabacbdcbdacddbbbcdaabcbdbbbabbdcbdacabba") ++ (""))
    =
    (("cadaa") ++ (C) ++ ("bddabbdadbbabcbdabaccbccbdbadccaccacdaacbcabdddabacbdcbdacddbbbcdaabcbdbbbabbdcbdacabba"));
constraint
  (("aacabadcdbdcbabcabacbdcdcdbacbcdbbcbccbcccccaddaddaadbdddbdaadaaddbabccbadbddcbacbccdbd") ++ (C) ++ ("dbddb"))
    =
    (("aacabadcdbdcbabcabacbdcdcdbacbcdbbcbccbcccccaddaddaadbdddbdaadaaddbabccbadbddcbacbccdbdabbbccbdbddb") ++ (""));
constraint
  (("accbdcbbdcdcdcbdbacccab") ++ (C) ++ ("acabbccbdbbcdacadccabacdacabcbbccabdabbacccabcdadaaabbdbcabcdddcadcba"))
    =
    (("accbdcbbdcdcdcbdbacccab") ++ (C) ++ ("acabbccbdbbcdacadccabacdacabcbbccabdabbacccabcdadaaabbdbcabcdddcadcba"));
constraint
  (("bddbabdddbbcddbbdacddcdcbddcdacbbbcabacab") ++ (A) ++ ("daca")) =
    (("bddbabdddbbcddbbdacddcdcbddcdac") ++ (B) ++ ("cbbcaaabcbccdcdbaccaddbdccadaca"));
constraint
  ((A) ++ ("cabdccabbdcaccaabacdaadcdccbbbdabaddcbcaaaddddbbaaad") ++ ("")) =
    (("dadaadbabbbbaaaddccbdaad") ++ (B) ++ ("ccbbbdabaddcbcaaaddddbbaaad"));
constraint
  ((C) ++ ("dacabbbcdbabbcdd") ++ ("")) =
    (("dcbabbababdabddaaacbacdbaacbabadaaaabadbaccdabdbbdaadaadcabddbbbcadccdbaaacbabdbabddacabbbcdbabbcdd") ++ (""));
constraint
  (("ccbaadacdddabccdadabbccbaaacbcddddabbcddbbdcbbaabdbaabca") ++ (D) ++ ("abcaddabadadbccdcdcbccdbdcccaacbccda"))
    =
    (("ccbaadacdddabccdadabbccbaaacbcddddabbcddbbdcbbaabdbaabca") ++ (D) ++ ("abcaddabadadbccdcdcbccdbdcccaacbccda"));
constraint
  (("ccbccccdcaddccccbcabdaadaacccdccdadccdbdbbadbaaccddcddbbccdbcdbdaaabcddcabaddcabcdddcbccacaccccdbac") ++ (""))
    =
    (("ccbccccdcaddccccbca") ++ (D) ++ ("cccdccdadccdbdbbadbaaccddcddbbccdbcdbdaaabcddcabaddcabcdddcbccacaccccdbac"));
constraint
  (("badbcddcbadaccadda") ++ (C) ++ ("cbaccbcdcccbcdaadabbddcaaacbbbbcabccdcaabddaadbdcdbacddbbaddccc"))
    = (("badbcddcba") ++ (B) ++ ("bbbcabccdcaabddaadbdcdbacddbbaddccc"));
constraint
  (("aabacd") ++ (D) ++ ("addabaa") ++ (B) ++ ("caaacbbacabbaacddaaacaabaccddcacbacacbcaabcdcbdabcd"))
    =
    (("aabacdaddaacbbadbdcabddacbcaabaddaba") ++ (C) ++ ("cacbcaabcdcbdabcd"));
constraint
  (("aac") ++ (C) ++ ("bcdbaaaadcdbadabaabcdbbbacbbda")) =
    (("aacbdacaccddadbdabbbabaaaaacbbcbcdabcab") ++ (B) ++ ("dbadabaabcdbbbacbbda"));
constraint
  (("ccaadbbacdbdbbcbc") ++ (B) ++ ("acdddb") ++ (D) ++ ("cdbacbdadddbdd")) =
    (("ccaadbbacdbdbbcbc") ++ (B) ++ ("acdddb") ++ (D) ++ ("cdbacbdadddbdd"));
constraint
  (("cbaaccabaaccabdcddddacbddbaddaccacaacaccbabbcacbbcddbacacadad") ++ (D) ++ ("aacdbddddcabbaabddcacabbaacbbcbdba"))
    =
    (("cbaaccabaaccabdcddddacbddbaddaccacaacaccbabbcacbbcddbacacadadcdcdaacdbddddcabbaabddcacabbaacbbcbdba") ++ (""));
constraint
  (("ddbdabdbbcaabcdabacaddcbdccbddcbbaadcbddcccdcddacdcdbbbddbbcabacacabdbbacddddcddadabcbcbbcdbcdcbbad") ++ (""))
    =
    (("ddbdabdbbcaabcdabacaddcbdccbddcbbaadcbddcccdcdda") ++ (D) ++ ("bbbddbbcabacacabdbbacddddcddadabcbcbbcdbcdcbbad"));
constraint
  (("acdbddbadcdbaddcbcdddaddbdbddbaaaacbcaaddcba") ++ (D) ++ ("cdcbacbbcadbabdccdadcddccdaadbdbcbdcababaacac") ++ (D) ++ ("bd"))
    =
    (("acdbddbadcdbaddcbcdddaddbdbddbaaaacbcaaddcbacdcdcdcbacbbcadbabdccdadcddccdaadbdbcbdcababaacac") ++ (D) ++ ("bd"));
constraint
  (("bcabbcbcbacccbacc") ++ (D) ++ ("dbabacaddbdbacbdacabbccdcbbcbcccddbddcbdacdbcabbaddddcbacddcadddccbbbcbddabaac"))
    =
    (("bcabbcbcbacccbacc") ++ (D) ++ ("dbabacaddbdbacbdacabbccdcbbcbcccddbddcbdacdbcabbaddddcbacddcadddccbbbcbddabaac"));
constraint
  (("dbbbbdbccccdcabacdacbdcbcdbddabaaabbbcbcbbacaabcbacdbbccaaccdcdaaabbcddddcbbbcaccdbcadcaadaaabbddbb") ++ (""))
    =
    (("dbbbbdbccccdcabacdacbdcbcdbddabaaabbbcbcbbacaabcbacdbbccaac") ++ (D) ++ ("aaabbcddddcbbbcaccdbcadcaadaaabbddbb"));
constraint
  (("cccaaccddbdaddddabaddaacddaccaadabdbdadddbccdcbdddacccbcddaadaaccaadccbddbbbddcdcdcdbadcbcbaacdcdda") ++ (""))
    =
    (("cccaaccddbdaddddabaddaacddaccaadabdbdadddbccdcbdddacccbcddaadaaccaadccbddbbbdd") ++ (D) ++ ("cdbadcbcbaacdcdda"));
constraint
  (("dababbbdacabdcbadddabcddabaccdbbdbadccdaaabbabbddbbdbbadcadbab") ++ (D) ++ ("ddddadbabcbccbdabaaabcdbcadbcddca"))
    =
    (("dababbbdacabdcbadddabcddabaccdbbdbadccdaaabbabbddbbdbbadcadbabcdcdddddadbabcbccbdabaaabcdbcadbcddca") ++ (""));
constraint
  (("cccbccda") ++ (D) ++ ("caccccbcdbdbbcaccdbddbdbcbdadacdddcdccccabdddddcbccaddcbacbacacacddcdabadadbbaacababcad"))
    =
    (("cccbccdacdcdcaccccbcdbdbbcaccdbddbdbcbdadacdddcdccccabdddddcbccaddcbacbacacacddcdabadadbbaacababcad") ++ (""));
constraint
  (("cbdcccbbbdcdacddbdbdaabaacccdbbbddaabcdcdcbadbadaadccbaaabaddcddaddccbcaadbacddcbbddaddbddddbbbaadc") ++ (""))
    =
    (("cbdcccbbbdcdacddbdbdaabaacccdbbbddaab") ++ (D) ++ ("cbadbadaadccbaaabaddcddaddccbcaadbacddcbbddaddbddddbbbaadc"));
constraint
  (("dcdbccbdbbabbabbcbaadabaddababcbadbadbdccaaacbcccccbcbdaabab") ++ (D) ++ ("aaadadacdbacaddaabcbddbabaccdaabdab"))
    =
    (("dcdbccbdbbabbabbcbaadabaddababcbadbadbdccaaacbcccccbcbdaababcdcdaaadadacdbacaddaabcbddbabaccdaabdab") ++ (""));
constraint
  (("cbaddbaadcbccbbdacdddcbbcdbbabbccccaabcccabdbcabdbbcdcddbdbbbdaabbcccacabdaddadadbbacdaabbddcbaadcc") ++ (""))
    =
    (("cbaddbaadcbccbbdacdddcbbcdbbabbccccaabcccabdbcabdbb") ++ (D) ++ ("dbdbbbdaabbcccacabdaddadadbbacdaabbddcbaadcc"));
constraint
  (("ccbcdbabacbcacabbcadcbdacccccacabbdcaddcbc") ++ (D) ++ ("bcdbcbdddaabbacbcabdabccdaadaddaabdadbacbadcacddcadcc"))
    =
    (("ccbcdbabacbcacabbcadcbdacccccacabbdcaddcbc") ++ (D) ++ ("bcdbcbdddaabbacbcabdabccdaadaddaabdadbacbadcacddcadcc"));
constraint
  (("bacabb") ++ (D) ++ ("cdaabbdaaccbbabaadaddababcdbacdcabadaadadddbbaaddccccbdaacaccadcaccbccbdbabcbcdaabdaacabc"))
    =
    (("bacabb") ++ (D) ++ ("cdaabbdaaccbbabaadaddababcdbacdcabadaadadddbbaaddccccbdaacaccadcaccbccbdbabcbcdaabdaacabc"));
constraint
  (("ddbcbdccddcadcaddcaddbaabcabcdcdcddbcacbadcccddacaccbccdadbdaaaacabacbaabacadbaadbcbcbcccbdacaabdcd") ++ (""))
    =
    (("ddbcbdccddcadcaddcaddbaabcab") ++ (D) ++ ("cddbcacbadcccddacaccbccdadbdaaaacabacbaabacadbaadbcbcbcccbdacaabdcd"));
constraint
  (("ddddcdacddbabddaaaaabcdadbbbbdbbaaccdbdabbdaccdbacdbdcdca") ++ (D) ++ ("aabcbacddddbdccdbadbaabacdcadabbcbdcda"))
    =
    (("ddddcdacddbabddaaaaabcdadbbbbdbbaaccdbdabbdaccdbacdbdcdcacdcdaabcbacddddbdccdbadbaabacdcadabbcbdcda") ++ (""));
constraint
  (("ddcddddbcbdcdddbbbaaaacbcdbbabaaabdbabcadaabdbaccbaaccbbcabddaaabadcdabdcadcaacddaaddccacbab") ++ (D) ++ ("adb"))
    =
    (("ddcddddbcbdcdddbbbaaaacbcdbbabaaabdbabcadaabdbaccbaaccbbcabddaaabadcdabdcadcaacddaaddccacbabcdcdadb") ++ (""));
constraint
  (("dbcdadbbdccccacbcdadbaabbbdbcdbcbdccdacbdaaadcbabcdddbdcaccbcbddadbbdbcbcbadbabcbbbcacba") ++ (D) ++ ("bcbbaba"))
    =
    (("dbcdadbbdccccacbcdadbaabbbdbcdbcbdccdacbdaaadcbabcdddbdcaccbcbddadbbdbcbcbadbabcbbbcacba") ++ (D) ++ ("bcbbaba"));
constraint
  (("babdcabdcdcadbadaacdbdbbcacddaddbbabaadabdabcddaccdcdcdcccbaaaccbbbbadccdaaccacbcbccacaccabdacbbdda") ++ (""))
    =
    (("babdcabdcdcadbadaacdbdbbcacddaddbbabaadabdabcddac") ++ (D) ++ ("cdcccbaaaccbbbbadccdaaccacbcbccacaccabdacbbdda"));
constraint
  (("adcacad") ++ (D) ++ ("cbaabcdcacbddcabddabacddcdabadbadbdaddccbbdadcaccdbababbbcadccbcbbabdcaacccaddccabadcabb"))
    =
    (("adcacadcdcdcbaabcdcacbddcabddabacddcdabadbadbdaddccbbdadcaccdbababbbcadccbcbbabdcaacccaddccabadcabb") ++ (""));
constraint
  (("bbcbcdacdaaddccbcdcbabddcbacccdcbbcaabcaaaadcbbcadacccabbaddbdbbbdadaabccacbcaacdcbbabbd") ++ (D) ++ ("addbaca"))
    =
    (("bbcbcdacdaaddccbcdcbabddcbacccdcbbcaabcaaaadcbbcadacccabbaddbdbbbdadaabccacbcaacdcbbabbd") ++ (D) ++ ("addbaca"));
constraint
  ((D) ++ ("badddbdbccdabaaacaaddcbdadacdcabcaacccacaabcbcaaccacacdbadacbaaaadabbaaaadbcdcbdbaccbcbdaaccdca") ++ (""))
    =
    ((D) ++ ("badddbdbccdabaaacaaddcbdadacdcabcaacccacaabcbcaaccacacdbadacbaaaadabbaaaadbcdcbdbaccbcbdaaccdca") ++ (""));
solve satisfy;
