var string: B;
var string: A;
constraint
  (("a") ++ (B) ++ ("ccbaaabbcabbacccbabaa")) =
    (("aabbaabaababccacbcbcabaabccbbccbbcc") ++ (A) ++ ("baaabbcabbacccbabaa"));
constraint
  (("acacbbccccabbcabcaaabaabaabaabbcccbcbaaacacccabbbbbbabcabcbcbababbaabbcbaacaabcaabb") ++ (""))
    = (("acacbbccccabbcabcaaabaabaabaabbcccb") ++ (A) ++ ("bb"));
constraint
  (("b") ++ (B) ++ ("ccbabacaaccccbbababaaabbaaaccabbaababacbababcacbbbbcb"))
    =
    (("b") ++ (B) ++ ("ccbabacaaccccbbababaaabbaaaccabbaababacbababcacbbbbcb"));
constraint
  (("baaccbccbccacbacbb") ++ (B) ++ ("aababaabcbcbaaacbcbcbacbbcaacaccbbbcababcacabbbab"))
    =
    (("baaccbccbccacbacbbcaccbacaacbba") ++ (A) ++ ("abcbcbaaacbcbcbacbbcaacaccbbbcababcacabbbab"));
constraint
  (("cabcabaacccbccabccaababaababcbccaaacbcbbaabbccbcbcbacabcbbccaccabaacccabbabcabbccbb") ++ (""))
    =
    (("cabcabaacccbcca") ++ (A) ++ ("ababcbccaaacbcbbaabbccbcbcbacabcbbccaccabaacccabbabcabbccbb"));
constraint
  (("bbbabacaaacbabbbbaaabcacbcabcacaa") ++ (B) ++ ("acacacc")) =
    (("bbbabacaaacbabbbbaaabcacbcabcacaa") ++ (B) ++ ("acacacc"));
constraint
  (("bbcbabbbcccaaccccb") ++ (B) ++ ("cbaaacacabcaaabaacbaccbababcaabb")) =
    (("bbcbabbbcccaaccccb") ++ (B) ++ ("cbaaacacabcaaabaacbaccbababcaabb"));
constraint
  (("a") ++ (B) ++ ("bbacbaabaaccacccbbcbbabccbbbabcaccaccaccccabbccacccaabcbababbb"))
    =
    (("aaccacabccccabcbcb") ++ (A) ++ ("bccbbbabcaccaccaccccabbccacccaabcbababbb"));
constraint
  (("cccbbbccbbaccbb") ++ (B) ++ ("abccaacbc") ++ (A) ++ ("bbaacaa")) =
    (("cccbbbccbbaccbbabbccaacabbbaccbabbcbbabaaabcbcaaabaabcbbbbccabacabccaacbcabbbbaacaa") ++ (""));
constraint
  (("cccbccbbcaabccacabbcccccbabbbccababbbccabbbcacabbabcbabcaaccacacbaabbabbbaaccbaacac") ++ (""))
    =
    (("cccbccbbcaabccac") ++ (A) ++ ("cccccb") ++ (A) ++ ("bccab") ++ (A) ++ ("bccabbbcac") ++ (A) ++ ("abcbabcaaccacacbaabb") ++ (A) ++ ("baaccbaacac"));
constraint
  (("aaabbacaaba") ++ (A) ++ ("abbaacccbbccacacaaccbbaaaacccbbbaccbbaccccacabcbaaccacbccbacabbccaaab"))
    =
    (("aa") ++ (A) ++ ("acaabaabb") ++ (A) ++ ("aacccbbccacacaaccbbaaaacccbbbaccbbaccccacabcbaaccacbccbac") ++ (A) ++ ("ccaaab"));
constraint
  (("cababaaaaaaaaba") ++ (A) ++ ("acababccbbcbaccbbccacbbaabccacabaabcccaaabcccccacbbbcbbbcbccacccb"))
    =
    (("cababaaaaaaaaba") ++ (A) ++ ("acababccbbcbaccbbccacbbaabccacabaabcccaaabcccccacbbbcbbbcbccacccb"));
constraint
  (("cacacacbabccbbcbcaab") ++ (A) ++ ("bcaaccccbccacabcaaccabbbaaabbcacb") ++ (A) ++ ("acbcacbcaabbbbccaabaaaca"))
    =
    (("cacacacbabccbbcbcaab") ++ (A) ++ ("bcaaccccbccacabcaacc") ++ (A) ++ ("baa") ++ (A) ++ ("cacb") ++ (A) ++ ("acbcacbca") ++ (A) ++ ("bbccaabaaaca"));
constraint
  (("bcacacbaabaabbacacaccbbbcaacabbccaabccabccbccbaaaaacbaccacacbabaaabcbcbbbbabbababba") ++ (""))
    =
    (("bcacacbaaba") ++ (A) ++ ("acacaccbbbcaacabbccaabccabccbccbaaaaacbaccacacbabaaabcbcbbbbabbab") ++ (A) ++ ("a"));
constraint
  (("acbbbbabbcccaccbabaccaccabcacbbcaacbccbcbbcbacabacbbcbaacbcbaaabaababcaacacbcbabaab") ++ (""))
    =
    (("acbbbb") ++ (A) ++ ("cccaccbabaccaccabcacbbcaacbccbcbbcbacabacbbcbaacbcbaaabaababcaacacbcbabaab"));
constraint
  (("acaa") ++ (A) ++ ("babbccaaaabaababaaacaaaaacbcaccccbacbbbaaababcac") ++ (A) ++ ("c") ++ (A) ++ ("acbbbb") ++ (A) ++ ("abaaacababcb"))
    =
    (("acaa") ++ (A) ++ ("babbccaaaabaababaaacaaaaacbcaccccbacbbbaaababcacabbc") ++ (A) ++ ("acbbbbabbabaaacababcb"));
constraint
  (("abac") ++ (A) ++ ("aaabcabaccbccacaaabcbcabcacacacbbbabcbbcbbaaaaaabacbaccbacbbbacbcbbbcccacbac"))
    =
    (("abac") ++ (A) ++ ("aaabcabaccbccacaaabcbcabcacacacbbbabcbbcbbaaaaaabacbaccbacbbbacbcbbbcccacbac"));
constraint
  (("baaaccaababaabcaccacbbbaaccccccccccacbacbcccccbaccbcbaabccbacabaaccccabaaaaaabbabac") ++ (""))
    =
    (("baaaccaababaabcaccacbbbaaccccccccccacbacbcccccbaccbcbaabccbacabaaccccabaaaaa") ++ (A) ++ ("abac"));
constraint
  (("ccccccabacaccaccbacbbc") ++ (A) ++ ("bbcbccbbcbbcbba") ++ (A) ++ ("bcaccbcccaaaccaabbbbbababcbabbcbabccbbcc"))
    =
    (("ccccccabacaccaccbacbbc") ++ (A) ++ ("bbcbccbbcbbcbbaabbbcaccbcccaaaccaabbbbbababcb") ++ (A) ++ ("cbabccbbcc"));
constraint
  (("cccbcccacbcababbbccbacccbbaccbbbcaacaaabbbbaaaacababcbaabcaacbcb") ++ (A) ++ ("ccaaaacbaccaccaa"))
    =
    (("cccbcccacbcab") ++ (A) ++ ("bccbacccbbaccbbbcaacaaabbbbaaaacababcbaabcaacbcbabbccaaaacbaccaccaa"));
constraint
  (("abbbabcabaabbcaacbbbaacbcacbabaacbbbac") ++ (A) ++ ("cbaabbabaacabccaba") ++ (A) ++ ("caccbcb") ++ (A) ++ ("accbabcbaab"))
    =
    (("abbbabcabaabbcaacbbbaacbcacbabaacbbbacabbcba") ++ (A) ++ ("abaacabccaba") ++ (A) ++ ("caccbcb") ++ (A) ++ ("accbabcbaab"));
constraint
  (("caaccacaabcbabababccba") ++ (A) ++ ("cca") ++ (A) ++ ("bcabaaabcbbcccbbbbabbabcacabacbcabab") ++ (A) ++ ("bcbb") ++ (A) ++ ("bcbaca"))
    =
    (("caaccacaabcbabababccba") ++ (A) ++ ("ccaabbbcabaaabcbbcccbbbb") ++ (A) ++ ("abcacabacbcabababbbcbbabbbcbaca"));
constraint
  (("accbcbcaaabcacccbaaabccbcbbccbcbcbbcbbcabaaacccabbbbabcacababcabcaabbaababacbbbcbca") ++ (""))
    =
    (("accbcbcaaabcacccbaaabccbcbbccbcbcbbcbbcabaaacccabbbbabcacababcabca") ++ (A) ++ ("aababacbbbcbca"));
constraint
  (("bcaabcabcccbbcacccaaacbbccbaaaacacacaabbbccbcbcabcabcbaabccabcbbabacccb") ++ (A) ++ ("aaccacacb"))
    =
    (("bcaabcabcccbbcacccaaacbbccbaaaacacaca") ++ (A) ++ ("bccbcbcabcabcbaabccabcbbabacccb") ++ (A) ++ ("aaccacacb"));
constraint
  (("babaccacabcaaacbbaaacbbaaaccccabcbccacccbacabcbacccbcaaaa") ++ (A) ++ ("bbbaccccacbcbbcacbaaaba"))
    =
    (("babaccacabcaaacbbaaacbbaaaccccabcbccacccbacabcbacccbcaaaa") ++ (A) ++ ("bbbaccccacbcbbcacbaaaba"));
constraint
  (("c") ++ (A) ++ ("abaaaaaaccbcccccbcccababcccbacaabaabcabbbaac") ++ (A) ++ ("bcacbcbabcccaabcbbacbcabaacbcacb"))
    =
    (("cabbabaaaaaaccbcccccbcccababcccbacaabaabcabbbaacabbbcacbcbabcccaabcbbacbcabaacbcacb") ++ (""));
constraint
  (("accabccca") ++ (A) ++ ("baaaababaaaabcbcacbbcacaababcbabcbab") ++ (A) ++ ("cbbccabacaaccbababcbcbcbaaacbcbc"))
    =
    (("accabcccaabbbaaaababaaaabcbcacbbcacaababcbabcbab") ++ (A) ++ ("cbbccabacaaccbababcbcbcbaaacbcbc"));
constraint
  (("abbaaaabccacbabcabacbbabccababcabacabcabcbbcccaabbaccaacb") ++ (A) ++ ("caabcbaabaabaccaabaaabc"))
    =
    ((A) ++ ("aaaabccacbabcabacbbabccababcabacabcabcbbcccaabbaccaacb") ++ (A) ++ ("caabcbaabaabaccaabaaabc"));
constraint
  (("bacc") ++ (A) ++ ("acaaabacbccaccaaaacabbbccbbabccbbccccccabccbccaaabcbabaaccabcbccaccaacbaaaab"))
    =
    (("baccabbacaaabacbccaccaaaac") ++ (A) ++ ("bccbbabccbbccccccabccbccaaabcbabaaccabcbccaccaacbaaaab"));
constraint
  (("bcabaacb") ++ (A) ++ ("bccaa") ++ (A) ++ ("cacabaaccbbaacccaacccccacaabccbaccaacaaacaccbcccbacacaccbabbcbcb"))
    =
    (("bcabaacbabbbccaa") ++ (A) ++ ("cacabaaccbbaacccaacccccacaabccbaccaacaaacaccbcccbacacaccbabbcbcb"));
constraint
  (("aacbcabaca") ++ (A) ++ ("cbcccbbaccabcbcacaaaccccccaaabccabaacccbcabcbcbbacacccbbaaacababccbcab"))
    =
    (("aacbcabacaabbcbcccbbaccabcbcacaaaccccccaaabccabaacccbcabcbcbbacacccbbaaacababccbcab") ++ (""));
constraint
  (("cbbabbbcbcc") ++ (A) ++ ("cabbcbacabccacbabcabcbaacbcababbccccbcbaacacbbccbbbaaccbabaaacaccaacc"))
    =
    (("cbb") ++ (A) ++ ("bcbcc") ++ (A) ++ ("cabbcbacabccacbabcabcbaacbcab") ++ (A) ++ ("ccccbcbaacacbbccbbbaaccbabaaacaccaacc"));
solve satisfy;
