var string: H;
var string: G;
var string: E;
var string: C;
var string: D;
constraint
  (("abaadaadacbc") ++ (G) ++ ("dbeacb") ++ (C) ++ ("aabedeaacaebeaaddcebebceada"))
    = (("abaadaadacbcecedaccca") ++ (D) ++ ("bebceada"));
constraint
  (("ceecbedebbdbdbcccdaddeebcaabbdeaabccdecabdabbeeedcbbaadbaadcbccdedceaedd") ++ (""))
    =
    (("ceecbedebbdbdbcccdaddeebcaabbdeaabccdeca") ++ (E) ++ ("beeedcbbaadbaadcbccdedceaedd"));
constraint
  (("beedddeebbecaabcdcdaeaededaddcacbb") ++ (E) ++ ("bbbbcbabcdaccdbabdaacdadedeacaadae"))
    =
    (("beedddeebbecaabcdcdaeaededaddcacbb") ++ (E) ++ ("bbbbcbabcdaccdbabdaacdadedeacaadae"));
constraint
  (("ddaeebdcbdcbccdedeacddaeebccddaad") ++ (H) ++ ("dbaeecacaecabeeebbccbacbcabdaaebbbb"))
    =
    (("ddaeebdcbdcbccdedeacddaeebccddaad") ++ (H) ++ ("dbaeecacaecabeeebbccbacbcabdaaebbbb"));
constraint
  (("bedabdabdadbbcccaabbdaddeecabcbedeadacbcecbdccdebccaaddaeaaedbebebbceeae") ++ (""))
    =
    (("beda") ++ (E) ++ ("dadbbcccaabbdaddeecabcbedeadacbcecbdccdebccaaddaeaaedbebebbceeae"));
constraint
  (("cbeebcadecddeacdbbdaceeceedabeddadbbedeabacbadbccecb") ++ (H) ++ ("ddddecadadbbeadc"))
    =
    (("cbeebcadecddeacdbbdaceeceedabeddadbbedeabacbadbccecbacbdddddecadadbbeadc") ++ (""));
constraint
  (("bbbddadabeacaedaecacdcbeadbeebaadccaeecaad") ++ (E) ++ ("aecdceddedaaeeaedadeabedce"))
    =
    (("bbbddadabeacaedaecacdcbeadbeebaadccaeecaadbdabaecdceddedaaeeaedadeabedce") ++ (""));
constraint
  (("baabbbcbeaaacaceacecbebbaecacedacecbdccdbebbaabbaebcaccecbecacbdecceedec") ++ (""))
    =
    (("baabbbcbeaaacaceacecbebbaecacedacecbdccdbebbaabbaebcaccecbec") ++ (H) ++ ("ecceedec"));
constraint
  (("ebceceeceecadeabcbceedecaeccbabceecdbacdcaccacbdbaddb") ++ (E) ++ ("acebdecdacebcad"))
    =
    (("ebceceeceecadeabcbceedecaeccbabceecdbacdcacc") ++ (H) ++ ("baddbbdabacebdecdacebcad"));
constraint
  (("bedeccadbcabaebebccdbbcccacccededaecadbdcecbcddacceaced") ++ (E) ++ ("eebebeaebbdde"))
    =
    (("bedeccadbcabaebebccdbbcccacccededaecadbdcecbcddacceaced") ++ (E) ++ ("eebebeaebbdde"));
constraint
  (("adbeeddbcdddcdaabbdabbacdcadbbcebbeeacebcdcbdbbebcededbeaadedcbeddeeaccd") ++ (""))
    =
    (("adbeeddbcdddcdaab") ++ (E) ++ ("bacdcadbbcebbeeacebcdcbdbbebcededbeaadedcbeddeeaccd"));
constraint
  (("beaeebddccccddacbbbbeeedcbdd") ++ (E) ++ ("addacddecbccecceedaaacccebcbabbebdcdbeed"))
    =
    (("beaeebddccccddacbbbbeeedcbdd") ++ (E) ++ ("addacddecbccecceedaaacccebcbabbebdcdbeed"));
constraint
  (("edcacddabadcbacdbddebdbbebeaacadecdddebacddcbbebdbaadaadadd") ++ (H) ++ ("eabaaddad"))
    =
    (("edcacddabadcbacdbddebdbbebeaacadecdddebacddcbbebdbaadaadadd") ++ (H) ++ ("eabaaddad"));
constraint
  (("aebccceadebaccdcbbdbecbdaeccccaebeedabbacaaacccacddadceaeddaedbeebacbdbb") ++ (""))
    =
    (("aebccceadebaccdcbbdbecbdaeccccaebeedabbacaaacccacddadceaeddaedbeeb") ++ (H) ++ ("bb"));
constraint
  (("aecceddeddebccabdeddcdaebedecacbdbeabbbaaceaccadceecbacdabdeaaadbdcbcdbc") ++ (""))
    =
    (("aecceddeddebccabdeddcdaebedec") ++ (H) ++ ("beabbbaaceaccadceecbacdabdeaaadbdcbcdbc"));
constraint
  (("eacacddabbbcdedbebdecacbdbadcaaaebeceddbeebddecedcadbcdbcccaebddaaaadbbd") ++ (""))
    =
    (("eacacddabbbcdedbebdec") ++ (H) ++ ("badcaaaebeceddbeebddecedcadbcdbcccaebddaaaadbbd"));
constraint
  (("edbadceaaeedecdecdcdabbcbdecbddbbacedcd") ++ (E) ++ ("cadbeeadaedeedcbbcdddddacbdea"))
    =
    (("edbadceaaeedecdecdcdabbcbdecbddbbacedcd") ++ (E) ++ ("cadbeeadaedeedcbbcdddddacbdea"));
constraint
  (("caceaedbedddedcaddddbcdaaacaaddccaeacdeaababc") ++ (E) ++ ("aabccbeedaeaceaeeacbcce"))
    =
    (("caceaedbedddedcaddddbcdaaacaaddccaeacdeaababcbdabaabccbeedaeaceaeeacbcce") ++ (""));
constraint
  (("cceacdddbb") ++ (H) ++ ("abccdbdcedeeaccaaddcacbebcdebabdaaddeddecedeaacacaeaebcbee"))
    =
    (("cceacdddbb") ++ (H) ++ ("abccdbdcedeeaccaaddcacbebcdebabdaaddeddecedeaacacaeaebcbee"));
constraint
  (("bcabdde") ++ (H) ++ ("dceddbbeedcecbbbebccabbaceaccbaccaecdccacdaecdaeeeaaaaddedbec"))
    =
    (("bcabdde") ++ (H) ++ ("dceddbbeedcecbbbebccabbaceaccbaccaecdccacdaecdaeeeaaaaddedbec"));
constraint
  (("becdcb") ++ (E) ++ ("dcdedcaadaccaaacdbbdbeeeabdddedbcadebedadbecebdbabcdbdaeebdceb"))
    =
    (("becdcbbdabdcdedcaadaccaaacdbbdbeeeabdddedbcadebedadbecebdbabcdbdaeebdceb") ++ (""));
constraint
  (("aeaaaaeecdbabdcb") ++ (H) ++ ("acceadcdeecbcaaabbcddbabbcceabacddbbaaaccecdbeacdded"))
    =
    (("aeaaaaeecdbabdcb") ++ (H) ++ ("acceadcdeecbcaaabbcddbabbcceabacddbbaaaccecdbeacdded"));
constraint
  (("abcecebdcaeaabbaedadedcccabbaaaeecbdceaebeaceecbdabcaadadabbe") ++ (H) ++ ("babccec"))
    =
    (("abcecebdcaeaabbaedadedcccabbaaaeecbdceaebeaceecbdabcaadadabbe") ++ (H) ++ ("babccec"));
constraint
  (("bdaebabebadeeec") ++ (H) ++ ("cdbbbaeebceeabaabedeacaceeedbeaabdedaaeececbbecdcddbb"))
    =
    (("bdaebabebadeeecacbdcdbbbaeebceeabaabedeacaceeedbeaabdedaaeececbbecdcddbb") ++ (""));
constraint
  (("abeeacbcaeeecccbcbbdbabbeecaeaabde") ++ (H) ++ ("cacaecbccabeaedeceacbbcabdcdcdaded"))
    =
    (("abeeacbcaeeecccbcbbdbabbeecaeaabdeacbdcacaecbccabeaedeceacbbcabdcdcdaded") ++ (""));
constraint
  (("bbdebcbbdecddcabbbaaccaebbecdbaaebdcaabbabecadbdaececabbad") ++ (H) ++ ("bddbceaddd"))
    =
    (("bbdebcbbdecddcabbbaaccaebbecdbaaebdcaabbabecadbdaececabbad") ++ (H) ++ ("bddbceaddd"));
constraint
  (("bbbdebdeaedbadcecaaccdeecceaecceddbcddcbcdb") ++ (E) ++ ("dbeecedbdccdaecdbbabbdced"))
    =
    (("bbbdebdeaedbadcecaaccdeecceaecceddbcddcbcdbbdabdbeecedbdccdaecdbbabbdced") ++ (""));
constraint
  (("cbdeacebbeeeeadabcdbccabcbaaaebebbdadbebaeedbadbedccecaacddebbbcb") ++ (H) ++ ("acb"))
    =
    (("cbdeacebbeeeeadabcdbccabcbaaaebebbdadbebaeedbadbedccecaacddebbbcb") ++ (H) ++ ("acb"));
constraint
  (("ddddeddaecceeaaddcbcedcbadeddbcbaccbabccddececddbcd") ++ (H) ++ ("ebccbdbbbcdaeaeed"))
    =
    (("ddddeddaecceeaaddcbcedcbadeddbcbaccbabccddececddbcd") ++ (H) ++ ("ebccbdbbbcdaeaeed"));
constraint
  (("edadbabcdaacbdcdedcecbde") ++ (E) ++ ("beaeadceaebbbadcbecaeaadbbacbbabdecdbdceedca"))
    =
    (("edadbabcdaacbdcdedcecbde") ++ (E) ++ ("beaeadceaebbbadcbecaeaadbbacbbabdecdbdceedca"));
constraint
  (("dccbadebaabdcdebeaaabaedcabbeddabcceebadcaacbdcadbebcccbceddddaeabeeceea") ++ (""))
    =
    (("dccbadebaabdcdebeaaabaedcabbeddabcceebadca") ++ (H) ++ ("cadbebcccbceddddaeabeeceea"));
constraint
  (("eaeeaeceedaddaebceddbcdabddcd") ++ (E) ++ ("beddceebbabedbdedbcaeacdbaadbdcbacbbace"))
    =
    (("eaeeaeceedaddaebceddbcdabddcdbdabbeddceebbabedbdedbcaeacdbaadbdcbacbbace") ++ (""));
constraint
  (("daecbdeaadadbacaccdbdebbeeddeeccebededeaeebacdeeccaacebdaaec") ++ (H) ++ ("bbadaccc"))
    =
    (("daecbdeaadadbacaccdbdebbeeddeeccebededeaeebacdeeccaacebdaaecacbdbbadaccc") ++ (""));
constraint
  (("dcdbcebcbbcbadcaaaadcccaecabcdbbeecbecbdebcedeabccaaedbbcebdd") ++ (H) ++ ("edcddde"))
    =
    (("dcdbcebcbbcbadcaaaadcccaecabcdbbeecbecbdebcedeabccaaedbbcebdd") ++ (H) ++ ("edcddde"));
constraint
  (("eaeaeabdcdbececceccdbcedecddeac") ++ (H) ++ ("bccccdbaaebeceabdaddecedbeaeacedbcacb"))
    =
    (("eaeaeabdcdbececceccdbcedecddeacacbdbccccdbaaebeceabdaddecedbeaeacedbcacb") ++ (""));
constraint
  (("bdbbeddabbcbcedbcbaeecbdbeacccbacdcacaabeeacbdbbecedeaaececeacccaddabdce") ++ (""))
    =
    (("bdbbeddabbcbcedbcbaeecbdbeacccbacdcacaabee") ++ (H) ++ ("bbecedeaaececeacccaddabdce"));
constraint
  (("cebcbaebddacaaddabcbbbaceccdaaddcaaecabcccbcbdbaeceaabdabcbbecbcdabecbbc") ++ (""))
    =
    (("cebcbaebddacaaddabcbbbaceccdaaddcaaecabcccbcbdbaeceaa") ++ (E) ++ ("cbbecbcdabecbbc"));
constraint
  (("edaadcaebaeeecabcbbadeaecddbeeaececcddcbdccedbdbeeec") ++ (H) ++ ("ddbcbdaeebabcddb"))
    =
    (("edaadcaebaeeecabcbbadeaecddbeeaececcddcbdccedbdbeeec") ++ (H) ++ ("ddbcbdaeebabcddb"));
constraint
  (("daceabcd") ++ (H) ++ ("ceabccaedbaebdbbeeacddaaedddeeccbcebaeddecaeb") ++ (H) ++ ("dacaacedcbe"))
    =
    (("daceabcd") ++ (H) ++ ("ceabccaedbaebdbbeeacddaaedddeeccbcebaeddecaebacbddacaacedcbe"));
constraint
  (("adaebbcddeeeaccbaaeeeadaeecaeeedecabbbccedebecaaacebedcccdaebe") ++ (E) ++ ("ababda"))
    =
    (("adaebbcddeeeaccbaaeeeadaeecaeeedecabbbccedebecaaacebedcccdaebe") ++ (E) ++ ("ababda"));
constraint
  (("bdbadcbcaacbcbbadebeaaedbeceedecceaceeebeacaaededaadcbeeebdeaaca") ++ (H) ++ ("acac"))
    =
    (("bdbadcbcaacbcbbadebeaaedbeceedecceaceeebeacaaededaadcbeeebdeaaca") ++ (H) ++ ("acac"));
constraint
  (("dedcedeebbaabdcceccbdebbcccdceadbaaaadabeadabbdceabdcabecd") ++ (E) ++ ("dbbbbeccbd"))
    =
    (("dedcedeebbaabdcceccbdebbcccdceadbaaaadabeadabbdceabdcabecd") ++ (E) ++ ("dbbbbeccbd"));
constraint
  (("dcdaccebaedabadedbabceacaccdebeeccdaeeccdeecedddbabaaaddabcccd") ++ (H) ++ ("bdacea"))
    =
    (("dcdaccebaedabadedbabceacaccdebeeccdaeeccdeecedddbabaaaddabcccd") ++ (H) ++ ("bdacea"));
constraint
  (("bceceabecaedabebdbaaacebabbeceacebebbccebeaeec") ++ (E) ++ ("bbccecdebdbccdabddbccd"))
    =
    (("bceceabecaedabebdbaaacebabbeceacebebbccebeaeecbdabbbccecdebdbccdabddbccd") ++ (""));
constraint
  (("bacedcdebabbbeabcaabceaadbbbebdcbacaecdbcbeabbcadbeaa") ++ (H) ++ ("beacbecebdcdcbc"))
    =
    (("bacedcdebabbbeabcaabceaadbbbebdcbacaecdbcbeabbcadbeaa") ++ (H) ++ ("beacbecebdcdcbc"));
constraint
  (("babbebeaeebcdddaabdddccdcaebecea") ++ (H) ++ ("cbaadbebebaabbbaebeebcaceacbaccacdad"))
    =
    (("babbebeaeebcdddaabdddccdcaebecea") ++ (H) ++ ("cbaadbebebaabbbaebeebcaceacbaccacdad"));
constraint
  (("adcadbdaadeaaaeddaccbacdadaccacdacbedeedaebcebaeeebaaaddceccdbbbdd") ++ (E) ++ ("ec"))
    =
    (("adcadbdaadeaaaeddaccbacdadaccacdacbedeedaebcebaeeebaaaddceccdbbbddbdabec") ++ (""));
constraint
  (("dccabcaeaebeeeababecdadabadbecdcecaedcacbcaacdecddddacbddeaaadbdacddbbdb") ++ (""))
    =
    (("dccabcaeaebeeeababecdadabadbecdcecaedcacbcaacdecdddd") ++ (H) ++ ("deaaadbdacddbbdb"));
constraint
  (("cdbaaaeeeea") ++ (H) ++ ("cbedbceabbaeadccbceabbeeaadbeddbcddcaaaccecceecbadbbadaba"))
    =
    (("cdbaaaeeeeaacbdcbedbceabbaeadccbceabbeeaadbeddbcddcaaaccecceecbadbbadaba") ++ (""));
constraint
  (("bacbddbcaebdacbeeecbccccdabcebbebacbbeeacceadeeeeabaceabacceaecaadccbded") ++ (""))
    =
    (("b") ++ (H) ++ ("dbcaebdacbeeecbccccdabcebbebacbbeeacceadeeeeabaceabacceaecaadccbded"));
constraint
  (("bbdadadbbeeebbaeecaaccdddbdaeecdcb") ++ (E) ++ ("aecdaebdeebedacbedeeecdbeeecdcccbc"))
    =
    (("bbdadadbbeeebbaeecaaccdddbdaeecdcbbdabaecdaebdeebedacbedeeecdbeeecdcccbc") ++ (""));
constraint
  (("dbecce") ++ (H) ++ ("ebacacdddedeebebcadedacdbaccecbeebdddaccceaccbccdabbbbdcedabee"))
    =
    (("dbecce") ++ (H) ++ ("ebacacdddedeebebcadedacdbaccecbeebdddaccceaccbccdabbbbdcedabee"));
constraint
  (("adacccccacecbadeceebaaddaebbbbecebdedeacdbcbab") ++ (H) ++ ("eaeedbdcdccdeebeaecbcb"))
    =
    (("adacccccacecbadeceebaaddaebbbbecebdedeacdbcbabacbdeaeedbdcdccdeebeaecbcb") ++ (""));
constraint
  (("deabdadccabddbeeceeedeeaadd") ++ (E) ++ ("cabedacdaacaecb") ++ (H) ++ ("dbbedadeaacbeadbcccaab"))
    =
    (("deabdadccabddbeeceeedeeaadd") ++ (E) ++ ("cabedacdaacaecb") ++ (H) ++ ("dbbedadeaacbeadbcccaab"));
constraint
  (("aebddccedccddbcbdbbdeabbedaacbeceabded") ++ (H) ++ ("bddcaeebabccbceacdaabbbddbdbdc"))
    =
    (("aebddccedccddbcbdbbdeabbedaacbeceabded") ++ (H) ++ ("bddcaeebabccbceacdaabbbddbdbdc"));
constraint
  (("e") ++ (H) ++ ("dacedacddacdddeaebaceebadabbdcdcbabdcddadaacdddadadeaacbecdabbdbdbb"))
    =
    (("eacbddacedacddacdddeaebaceebadabbdcdcbabdcddadaacdddadadeaacbecdabbdbdbb") ++ (""));
constraint
  (("adecbbeeb") ++ (H) ++ ("eeebadbbaeddebedeadabcacddeceadbebaabbeacebedcaedbbedadbeac"))
    =
    (("adecbbeebacbdeeebadbbaeddebedeadabcacddeceadbebaabbeacebedcaedbbedadbeac") ++ (""));
constraint
  (("a") ++ (H) ++ ("cdaaccaacecddbebaaddcbcecdcbacbacbcccbecbdeaedadeadcdbbdbeadaaddcdd"))
    =
    (("a") ++ (H) ++ ("cdaaccaacecddbebaaddcbcecdcbacbacbcccbecbdeaedadeadcdbbdbeadaaddcdd"));
constraint
  (("ebdebebdecabdabebc") ++ (E) ++ ("dcdbaaadacabaebedbaebccdee") ++ (H) ++ ("bdadccccaabcbecdeced"))
    =
    (("ebdebebdeca") ++ (E) ++ ("ebc") ++ (E) ++ ("dcdbaaadacabaebedbaebccdeeacbdbdadccccaabcbecdeced"));
constraint
  (("eedddcacedcdedaecddadbcaedbabaeaaaeeedbbbdeebbdabbaacceeccaceaebeeceeabe") ++ (""))
    =
    (("eedddcacedcdedaecddadbcaedbabaeaaaeeedbbbdeeb") ++ (E) ++ ("baacceeccaceaebeeceeabe"));
constraint
  (("d") ++ (H) ++ ("ceedbbadacbaaceebceadadadbebeebcbbbbadaadbbebbebccabdcbcaedbcdcbddb"))
    =
    (("dacbdceedbbadacbaaceebceadadadbebeebcbbbbadaadbbebbebccabdcbcaedbcdcbddb") ++ (""));
constraint
  (("ceecabcedebeaeebeeacadccbdcabdabebcdaaeabdceadeccbcdbccedacbdedaccebdebd") ++ (""))
    =
    (("ceecabcedebeaeebeeacadccbdcabdabebcdaaeabdceadeccbcdbcced") ++ (H) ++ ("edaccebdebd"));
constraint
  (("edbdcbaebcacaedeecdddbeadbcac") ++ (H) ++ ("bbddbaedadadeeddcacbaebbeaebddabaeaaadc"))
    =
    (("edbdcbaebcacaedeecdddbeadbcac") ++ (H) ++ ("bbddbaedadadeeddcacbaebbeaebddabaeaaadc"));
constraint
  (("aebebcdabcdaccccbedebebaecbbbabebbaadccdbabdadabbeeabacabab") ++ (H) ++ ("ebabececb"))
    =
    (("aebebcdabcdaccccbedebebaecbbbabebbaadccdbabdadabbeeabacabab") ++ (H) ++ ("ebabececb"));
constraint
  (("cadebcaacaecdcacdbbabbcebadbeeebadadeaaeccaecbccbaeddbeecdcdcaa") ++ (H) ++ ("dcdee"))
    =
    (("cadebcaacaecdcacdbbabbcebadbeeebadadeaaeccaecbccbaeddbeecdcdcaa") ++ (H) ++ ("dcdee"));
solve satisfy;
