var string: B;
var string: E;
var string: A;
var string: C;
constraint
  (("bbcdcbbcecacdbeabdcbabbd") ++ (B) ++ ("badeedaccabaddcadcddbe")) =
    (("bbcdcbbc") ++ (A) ++ ("dcbabbdcdabedb") ++ (C) ++ ("deedaccabaddcadcddbe"));
constraint
  (("ccea") ++ (B) ++ ("cdcadabbbdecceecbeceaece") ++ (E) ++ ("beacecabeaaeaebedaac") ++ (B) ++ ("dcdcdcac"))
    =
    (("cceabecdcadabbbdecc") ++ (C) ++ ("c") ++ (B) ++ ("acecabeaaeaebedaac") ++ (B) ++ ("dcdcdcac"));
constraint
  (("eccaeaadedaadeaadecbddaaecabaeaebbdaced") ++ (B) ++ ("cdbccabbaedcacbadaadebcabdcacddbca"))
    =
    (("eccaeaadedaadeaadecbddaaecabaeaebbdacedbecdbccabbaedcacbadaadebcabdcacddbca") ++ (""));
constraint
  (("dacecdcdebddcdddebadeebadbaaeadccbcaaaecbcadeeaebbbbbeccea") ++ (B) ++ ("cacdebebda") ++ (B) ++ ("bdc"))
    =
    (("dacecdcdebddcdddebadeebadbaaeadccbcaaaecbcadeeaebbbb") ++ (B) ++ ("ccea") ++ (B) ++ ("cacde") ++ (B) ++ ("bda") ++ (B) ++ ("bdc"));
constraint
  (("bccebdacdbccadecccbdecbbdddbadabbacceadbcacaebacbdcdeecadacdccaadececbce") ++ (B) ++ ("b"))
    =
    (("bccebdacdbccadecccbdecbbdddbadabbacceadbcacaebacbdcdeecadacdccaadececbcebeb") ++ (""));
constraint
  (("eaaeddccccaecdbcdbddbeaccbabaddcdebdbbbbccaebeeedbdabeebdeccbcdbdaeebcbbeee") ++ (""))
    =
    (("eaaeddccccaecdbcdbdd") ++ (B) ++ ("accbabaddcdebdbbbbccae") ++ (B) ++ ("eedbdabeebdeccbcdbdaeebcbbeee"));
constraint
  (("aecaccbadbcebbcaeaeacadebadadebdecdaadeecdcbbcdbecdcdedaaddabaceeeadb") ++ (B) ++ ("abbc"))
    =
    (("aecaccbadbcebbcaeaeacadebadadebdecdaadeecdcbbcd") ++ (B) ++ ("cdcdedaaddabaceeeadb") ++ (B) ++ ("abbc"));
constraint
  (("beecbadaaddaceeebadccdcdebebacadabaeeecccccbbcdcdcdebaebdcddecacdbccdeaabce") ++ (""))
    =
    (("beecbadaaddaceeebadccdcde") ++ (B) ++ ("bacadabaeeecccccbbcdcdcdebaebdcddecacdbccdeaabce"));
constraint
  (("ccddadddbdadcccddbaaadeaedddaabcadaebbacedeadbccedaccbccdaacaca") ++ (B) ++ ("aabadbbcbc"))
    =
    (("ccddadddbdadcccddbaaadeaedddaabcadaebbacedeadbccedaccbccdaacaca") ++ (B) ++ ("aabadbbcbc"));
constraint
  (("ceebdabbacbaacbacacdeabcbdccacaabbeeccbdedbceecdbabdbdeaaded") ++ (B) ++ ("cbabdebccbaca"))
    =
    (("ceebdabbacbaacbacacdeabcbdccacaabbeeccbdedbceecdbabdbdeaaded") ++ (B) ++ ("cbabdebccbaca"));
constraint
  (("aacaabaacbcaddddecdeaddccbbaeede") ++ (B) ++ ("edebdadaaddceadbadaebdcdbadbacdbadcca") ++ (B) ++ (B))
    =
    (("aacaabaacbcaddddecdeaddccbbaeedebeedebdadaaddceadbadaebdcdbadbacdbadccabebe") ++ (""));
constraint
  (("edacddcebbdcccedebeabdededeccdbdedcababacadabcbba") ++ (B) ++ ("baacb") ++ (B) ++ ("aabbdada") ++ (B) ++ ("cbeabec"))
    =
    (("edacddcebbdcccede") ++ (B) ++ ("abdededeccdbdedcababacadabcbbabebaacb") ++ (B) ++ ("aabbdada") ++ (B) ++ ("c") ++ (B) ++ ("abec"));
constraint
  (("cdedbcdecedbbbbebcaaaccaabaacaddedeadbaeaddacadeacdaadebcbadbabcadbbedacaae") ++ (""))
    =
    (("cdedbcdecedbbbbebcaaaccaabaacaddedeadbaeaddacadeacdaadebcbadbabcadb") ++ (B) ++ ("dacaae"));
constraint
  (("edabbadebbbaabccccbaaa") ++ (B) ++ ("daeea") ++ (B) ++ ("aadbd") ++ (B) ++ ("cebbdaeaabdaecbadaebcaeeeecbcddddaedb"))
    =
    (("edabbadebbbaabccccbaaa") ++ (B) ++ ("daeeabeaadbdbecebbdaeaabdaecbadaebcaeeeecbcddddaedb"));
constraint
  (("ecbddba") ++ (B) ++ (B) ++ ("cdacedbadebecacaedbaddeeeeebdaedbbcecadebbbaaddcedecbdaceeadecac"))
    =
    (("ecbddba") ++ (B) ++ (B) ++ ("cdacedbade") ++ (B) ++ ("cacaedbaddeeeeebdaedbbcecadebbbaaddcedecbdaceeadecac"));
constraint
  (("bdcacacbacdbcccdceacceaaebcbbbccdaadeceaebdebdacdacccaeacaadada") ++ (B) ++ ("caacabaead"))
    =
    (("bdcacacbacdbcccdceacceaaebcbbbccdaadeceaebdebdacdacccaeacaadadabecaacabaead") ++ (""));
constraint
  (("eddeeabedceabddbcdcbcad") ++ (B) ++ ("aedceddabaccbba") ++ (B) ++ ("ececbcaccacddeaabdacaea") ++ (B) ++ ("aabcebac"))
    =
    (("eddeea") ++ (B) ++ ("dceabddbcdcbcad") ++ (B) ++ ("aedceddabaccbba") ++ (B) ++ ("ececbcaccacddeaabdacaeabeaabcebac"));
constraint
  (("aeebabaaaecaedbbccaacdabbacccaaccaadebddccaaebbeddddcccdadeab") ++ (B) ++ ("cea") ++ (B) ++ ("bdacdcc"))
    =
    (("aeebabaaaecaedbbccaacdabbacccaaccaadebddccaaebbeddddcccdadeab") ++ (B) ++ ("ceabebdacdcc"));
constraint
  (("abaeeaabbceaedadbdedddecbdbbaddbcbacdeecedceabdddcb") ++ (B) ++ ("ddaaededdebddaabceddea"))
    =
    (("abaeeaabbceaedadbdedddecbdbbaddbcbacdeecedceabdddcb") ++ (B) ++ ("ddaaededdebddaabceddea"));
constraint
  (("edbadcbdceabcdaabdbeccebdbbdbdccbcaeaecbebbdedddccdecaaeeca") ++ (B) ++ ("eabcdeccdacaba"))
    =
    (("edbadcbdceabcdaabdbeccebdbbdbdccbcaeaecbebbdedddccdecaaeeca") ++ (B) ++ ("eabcdeccdacaba"));
constraint
  (("bbccabdcedccbccdeeea") ++ (B) ++ ("ecebde") ++ (B) ++ ("aedeabbadceeeebceceddcdabcccedcdeadddbaedcdbc"))
    =
    (("bbccabdcedccbccdeeeabeecebde") ++ (B) ++ ("aedeabbadceeeebceceddcdabcccedcdeadddbaedcdbc"));
constraint
  (("cadbddebaebbcbaeadcaeabbbacaacbcdaedaaecabdcebdacabdeacaaeaddbeceeeaedddaed") ++ (""))
    =
    (("cadbddebaebbcbaeadcaeabbbacaacbcdaedaaecabdcebdacabdeacaaeadd") ++ (B) ++ ("ceeeaedddaed"));
solve satisfy;
