var string: B;
var string: A;
var string: C;
var string: D;
constraint
  (("fdfedebdfbeffbda") ++ (C) ++ ("fddc")) =
    (("fdfedebdfbeffbdacabfdf") ++ (B) ++ ("dc"));
constraint
  (("ea") ++ (A)) =
    (("eacdbdbbdfbefddcfadf") ++ (B) ++ ("f") ++ (D) ++ ("cabacfffabddccbfdecbdaaadddbecbddabbaeeedaec"));
constraint
  (("eedccdeabfbafafffbbabcbfccbba") ++ (A) ++ ("feacbbfbefcebefcfcaacaeecbcbccacbdedeaccabfd"))
    =
    (("eedccdeabfbafafffbbabcbfccbbafdfbdedd") ++ (B) ++ ("fcfcaacaeecbcbccacbdedeaccabfd"));
constraint
  (("cafccdaccdbccfaacbcabfdfaabdace") ++ (C) ++ ("fecddcacbebaecbe")) =
    (("cafccdaccdbccfaacbcab") ++ (B) ++ ("dabcfebaafcdfeeddbefecddcacbebaecbe"));
constraint
  (("badbdeddbdaddafafadeceaebf") ++ (A) ++ ("cdbdacabacbefdddecebbfcdcfc"))
    =
    (("badbdeddbdaddafafa") ++ (B) ++ ("cbbdfafedfcdbdacabacbefdddecebbfcdcfc"));
constraint
  (("ffe") ++ (A) ++ ("f") ++ (C) ++ ("ceecfaabaadebacefaddfbcbadbadacfdabccbbddeadf"))
    = (("ffeffdfcbcefceeffdadf") ++ (B) ++ ("ddeadf"));
constraint
  (("eaaafbbcbafddfdbbd") ++ (A) ++ ("faabddbbbdbbeedbadbdfee")) =
    (("eaaafbbcbafddfdbbdaebeeece") ++ (D) ++ ("eddadcffecffeaaeebafaabddbbbdbbeedbadbdfee"));
constraint
  (("eedebeffcdeccd") ++ (B) ++ ("fdabceffadfaeaaefeaaddadebfddfebbddafcbebeeedfdebddaaacabbbcfedbfcaddecf"))
    =
    (("eede") ++ (C) ++ ("fcdeccdaecbfdabceffadfaeaaefea") ++ (A) ++ ("dafcbebeeedfdebddaaacabbbcfedbfcaddecf"));
constraint
  (("bfcfbcaeeaadafdeddcfdddfdcebbfecfdacbbdaabdd") ++ (C) ++ ("aeedaabebddecefaefcbcedabedeeecceaadbcbccbc"))
    =
    (("bfcfbcaeeaadafdeddcfdddfdcebbfecfdacbbdaabdd") ++ (C) ++ ("aeedaabebddecefaefcbcedabedeeecceaadbcbccbc"));
constraint
  (("dbaedaeedacdbefebdecbcfbfcebaddbadeffccfefbfbcadeeceaaefceeceaeefbdaadefcdaececddbeebcaafa") ++ (""))
    =
    (("dbaedaeedacd") ++ (C) ++ ("ebdecbcfbfcebaddbadeffccfefbfbcadeeceaaefceeceaeefbdaadefcdaececddbeebcaafa"));
constraint
  (("eaebccfcadedbcefaceacceacfadebf") ++ (C) ++ ("fedfacbfdceddeaccedfceeaadbcaddbdbccfefcbaabcbdcebcebdbe"))
    =
    (("eaebccfcadedbcefaceacceacfadebfbeffedfacbfdceddeaccedfceeaadbcaddbdbccfefcbaabcbdcebcebdbe") ++ (""));
constraint
  (("ebdfbaeefeedbbddeafceeaebaaeaaebfdbdabbeaadccccacccbbecb") ++ (C) ++ ("bbbccccecfdbcbfeebfeecbcdcfdbae"))
    =
    (("ebdfbaeefeedbbddeafceeaebaaeaaebfdbdabbeaadccccacccbbecb") ++ (C) ++ ("bbbccccecfdbcbfeebfeecbcdcfdbae"));
constraint
  (("dbcebaecdaedcdcdbbcebbfeccbcfceedfddfaffebeeaafcebfcdcbdaeafcefabefbffbcddcbadbfaadfbaafdf") ++ (""))
    =
    (("dbcebaecdaedcdcdbbcebbfeccbcfceedfddfaffebeeaafcebfcdcbdaeafcefa") ++ (C) ++ ("bffbcddcbadbfaadfbaafdf"));
constraint
  (("ceecdfbeecbeadacbcedeeaedfadcafebbdbdefbfebefdfdccbdafcdcfbcdccaecfafabbabceacbdaaebaafefe") ++ (""))
    =
    (("ceecdfbeecbeadacbcedeeaedfadcafebbdbdefbfe") ++ (C) ++ ("dfdccbdafcdcfbcdccaecfafabbabceacbdaaebaafefe"));
constraint
  (("cfdeeaeedffbddbafdbdfbaefacceaccfabdecaacaeaaaefbfacbffdedbcceeecacffabdfcfafafdccfd") ++ (C) ++ ("fbd"))
    =
    (("cfdeeaeedffbddbafdbdfbaefacceaccfabdecaacaeaaaefbfacbffdedbcceeecacffabdfcfafafdccfd") ++ (C) ++ ("fbd"));
constraint
  (("fbccfaddcabdedfac") ++ (C) ++ ("beccddcfcfabfeecdebedbdaeafefbbcfcbdfefcdafdcffedafbebabbadbeebcfdeaec"))
    =
    (("fbccfaddcabdedfacbefbeccddcfcfabfeecdebedbdaeafefbbcfcbdfefcdafdcffedafbebabbadbeebcfdeaec") ++ (""));
constraint
  (("ddeebdabacacbaddeacebaecebfcadcacdcbdebaacbefcfdaefddaabcbbacbbbedaadfccadfdedebcbfbdbcfaa") ++ (""))
    =
    (("ddeebdabacacbaddeacebaecebfcadcacdcbdebaac") ++ (C) ++ ("cfdaefddaabcbbacbbbedaadfccadfdedebcbfbdbcfaa"));
constraint
  (("cafdccafeacbcffeb") ++ (C) ++ ("adedaabbdeaaedddbbdadeecdfaceadedbcecbabdfdacbbddacdefbfedafbcefadecfc"))
    =
    (("cafdccafeacbcffeb") ++ (C) ++ ("adedaabbdeaaedddbbdadeecdfaceadedbcecbabdfdacbbddacdefbfedafbcefadecfc"));
constraint
  (("fdacacbbdbdacfcdbfcdbc") ++ (C) ++ ("eacfddbfcafcfacdddecbceacdcebfcafcdcacbeccfbfcafddccbfeeedebeeefe"))
    =
    (("fdacacbbdbdacfcdbfcdbc") ++ (C) ++ ("eacfddbfcafcfacdddecbceacdcebfcafcdcacbeccfbfcafddccbfeeedebeeefe"));
constraint
  (("fccafafcefeeedebfeadadddecefcdde") ++ (C) ++ ("cdfdbfebdcfcfdfadbebdbebfbcadfbabafceefdcafbabcccfbaafb"))
    =
    (("fccafafcefeeedebfeadadddecefcddebefcdfdbfebdcfcfdfadbebdbebfbcadfbabafceefdcafbabcccfbaafb") ++ (""));
constraint
  (("fdcecbdbabeeeaebcfffcabafabddbcfbaf") ++ (C) ++ ("afbabcfaddfaedeaceafdffbeddaffaddabaefbeccfafbcdddaf"))
    =
    (("fdcecbdbabeeeaebcfffcabafabddbcfbafbefafbabcfaddfaedeaceafdffbeddaffaddabaefbeccfafbcdddaf") ++ (""));
constraint
  (("dabdfacdfedddeefdafbcf") ++ (C) ++ ("cbccdfbdcbcbecdbbfbaafaadddeedaebcefabffcbbbcabfbacbcebeaceacabfa"))
    =
    (("dabdfacdfedddeefdafbcfbefcbccdfbdcbcbecdbbfbaafaadddeedaebcefabffcbbbcabfbacbcebeaceacabfa") ++ (""));
constraint
  (("cbffcbbbbabfddeaaaccbbdacdaaecdfbccaaccbeddcaffdffbdbabddcdeaee") ++ (C) ++ ("edcecdacedebcdefbbedbbad"))
    =
    (("cbffcbbbbabfddeaaaccbbdacdaaecdfbccaaccbeddcaffdffbdbabddcdeaeebefedcecdacedebcdefbbedbbad") ++ (""));
constraint
  (("ccbbbfafbafcdadcea") ++ (C) ++ ("aaeddfffffbcfedacbdcefdaceebdecaabd") ++ (C) ++ ("beddccfbbabcebbeeacfedcfdccfbbe"))
    =
    (("ccbbbfafbafcdadceabefaaeddfffffbcfedacbdcefdaceebdecaabdbefbeddccfbbabcebbeeacfedcfdccfbbe") ++ (""));
solve satisfy;
