var string: I;
var string: B;
var string: G;
var string: F;
var string: A;
var string: C;
constraint
  (("bbaaa") ++ (I) ++ ("aaaababaabababab")) =
    (("bbaaaaaaaaaabbbaa") ++ (C) ++ ("baababaabaabbbbabbaaabbababbaaaababaabababab"));
constraint
  (("abbbabbabbababaabbbaabaabbbbbabbabbabababbbbaabbababaaaaaaabbbaabaaaabbabbbaabbbabbbabaabbbabbbba") ++ (""))
    =
    (("abbbabbabbababaabbbaabaabbbbbabbabbabababbbbaabbababa") ++ (B) ++ ("baaaabbabbbaabbbabbbabaabbbabbbba"));
constraint
  (("aabaababbbbabbbbbabbbaababbbaaaaaabbbaaababaaababababbabaaaababbbababaabbbbbabaaaaabbbababbbbabab") ++ (""))
    =
    (("aabaababbbbabbbbbabbbaababbb") ++ (B) ++ ("ababaaababababbabaaaababbbababaabbbbbabaaaaabbbababbbbabab"));
constraint
  (("bbabbabbbaaabbbbbaaaabbababaabaaaaaabbaababbaba") ++ (G) ++ ("abbabaababbbbbabbbaaaaaabbaaababbaabaa"))
    =
    (("bbabbabbbaaabbbbbaaaabbababaabaaaaaabbaababbababbbabababaababbabaababbbbbabbbaaaaaabbaaababbaabaa") ++ (""));
constraint
  (("aaaababaababaabbbabaaaaaaabbaabbaaaaaaabaabbaabbaabaaabbabbaaaaaaabbbaabbaabbbbbbaabbbabaaabaaabb") ++ (""))
    =
    (("aaaababaababaabbbabaaaaaaabbaabbaaaaaaabaabbaabbaabaaabbabba") ++ (B) ++ ("bbaabbbbbbaabbbabaaabaaabb"));
constraint
  (("abbaaabbbbababaaaabaaabaabababbbbababaaabaaabbaabbbbbaababaab") ++ (B) ++ ("bbbbaabbabbbabaaabbbbbaba"))
    =
    (("abbaaabbbbababaaaabaaabaabababbbbababaaabaaabbaabbbbbaababaab") ++ (B) ++ ("bbbbaabbabbbabaaabbbbbaba"));
constraint
  (("baabaaaabbabbbbbbbaabbbbaaabbabbbbaabbabbaababaaaaabbbab") ++ (G) ++ ("aabbaaaaaabbabbabbabaaabbabab"))
    =
    (("baabaaaabbabbbbbbbaabbbbaaabbabbbbaabbabbaababaaaaabbbabbbbabababaabaabbaaaaaabbabbabbabaaabbabab") ++ (""));
constraint
  (("bababaabaaabbbaabbbbbaabbaabbbbbabaaaabbbbbabababaababababbabbabaaabbbaaababababbbbbbbaabbaaabbba") ++ (""))
    =
    (("bababaabaaabbbaabbbbbaabbaabbbbbabaaaabb") ++ (G) ++ ("abababbabbabaaabbbaaababababbbbbbbaabbaaabbba"));
constraint
  (("abbbbbbbbababaaaabbabaabaabaaabbbabbbbaababaaaaabbbbabbababbab") ++ (B) ++ ("babababaaaababaabaaabaab"))
    =
    (("abbbbbbbbababaaaabbabaabaabaaabbbabbbbaababaaaaabbbbabbababbabaaaaaabbbaababababaaaababaabaaabaab") ++ (""));
constraint
  (("abbbabbbababbab") ++ (B) ++ ("aaabbabbbabbbababbbbbbbbaaaabbbbaaababbababbbbaabbabbbbaabbabbbababaaaa"))
    =
    (("abbbabbbababbab") ++ (B) ++ ("aaabbabbbabbbababbbbbbbbaaaabbbbaaababbababbbbaabbabbbbaabbabbbababaaaa"));
constraint
  (("baababbbbaaaaaaabaaabaabbbbbbaaaaabbaaabbabaaabbaabbabbab") ++ (B) ++ ("abbababbabababbabaaaaabbbaabb"))
    =
    (("baababbbbaaaaaaabaaabaabbbbbbaaaaabbaaabbabaaabbaabbabbabaaaaaabbbaaabbababbabababbabaaaaabbbaabb") ++ (""));
constraint
  (("baababbabbbabaaabaaabababaabaaba") ++ (B) ++ ("ababbabbaabbbaaababbaaaaabbaaabaabbbbbabababbbbbaaaaba"))
    =
    (("baababbabbbabaaabaaabababaabaaba") ++ (B) ++ ("ababbabbaabbbaaababbaaaaabbaaabaabbbbbabababbbbbaaaaba"));
constraint
  (("bbaababaabaabbaaaaabbbbbabaaabaaaabaabbabaaaabaaabbabaabbbbaaababbaaaabaabbabbbaababbaaaaaaabbbaa") ++ (""))
    =
    (("bbaababaabaabbaaaaabbbbbabaaabaaaabaabbabaaaabaaabbabaabbbbaaababbaaaabaabbabbbaababba") ++ (B));
constraint
  (("aaabbaabbabaabababbabbbbaaababaaaabaabaabbbbabbbaabbbbaaaaabaaaaaaabbbaabaababababbbbbaaaabbbabbb") ++ (""))
    =
    (("aaabbaabbabaabababbabbbbaaababaaaabaabaabbbbabbbaabbbbaaaaaba") ++ (B) ++ ("baababababbbbbaaaabbbabbb"));
constraint
  (("bbaababaabba") ++ (G) ++ ("bbaabababbaabababbbaabaaabbbbbaababaaaababbaaaababbbaaabbaabbbbaaabbabaab"))
    =
    (("bbaababaabbabbbabababaabbbaabababbaabababbbaabaaabbbbbaababaaaababbaaaababbbaaabbaabbbbaaabbabaab") ++ (""));
constraint
  (("aabaa") ++ (B) ++ ("baabbbaabaaabbabaaaabbbabaabababababaaaabbaababbaabaaabababaaabaaaabaabaabbababbb"))
    =
    (("aabaaaaaaaabbbaabaabbbaabaaabbabaaaabbbabaabababababaaaabbaababbaabaaabababaaabaaaabaabaabbababbb") ++ (""));
constraint
  (("aaaaaaabaabababbbbababaaabababaabaabbbbabbabaaaaaabbbaaaaabbabbaababaabbabbaaababbbabaaaababbbaba") ++ (""))
    =
    (("aaaaaaabaabababbbbababaaabababaabaabbbbabbab") ++ (B) ++ ("aaabbabbaababaabbabbaaababbbabaaaababbbaba"));
constraint
  (("abbbaababbbbaabaaabaaaaaababbababbbabbaaaaaababbaaaaaaabbbaababaabbbaaabababbbbaaabbbaaabaaaabbbb") ++ (""))
    =
    (("abbbaababbbbaabaaabaaaaaababbababbbabbaaaaaababba") ++ (B) ++ ("babaabbbaaabababbbbaaabbbaaabaaaabbbb"));
constraint
  (("bababaabababbbbbbbaaaabb") ++ (B) ++ ("aaaabbaaaabbabaabbabbbbbbaabaaabbabbbbaaabaaabaabbbabbbbbabbab"))
    =
    (("bababaabababbbbbbbaaaabb") ++ (B) ++ ("aaaabbaaaabbabaabbabbbbbbaabaaabbabbbbaaabaaabaabbbabbbbbabbab"));
constraint
  (("aaaaabaaa") ++ (B) ++ ("abbabaababaabababaabaaabaaaabaabbbaababbbbbbbabbbabbbbabaaabaabaaaaabaaaaabab"))
    =
    (("aaaaabaaaaaaaaabbbaaabbabaababaabababaabaaabaaaabaabbbaababbbbbbbabbbabbbbabaaabaabaaaaabaaaaabab") ++ (""));
constraint
  (("bbbbaabaabbbbbbabbabbbaabbbbbaabbbabbbabaaaaaaababaaabaaaaabaaabbaaaa") ++ (B) ++ ("aaabbabaaaababbab"))
    =
    (("bbbbaabaabbbbbbabbabbbaabbbbbaabbbabbbabaaaaaaababaaabaaaaabaaabbaaaa") ++ (B) ++ ("aaabbabaaaababbab"));
constraint
  (("abbabbaaaaabaabbbbbaabaaaababbbaaaabaaaabbb") ++ (B) ++ ("abbaaabbaaaaaabbabbbabbabbbbabaabbababbabaa"))
    =
    (("abbabbaaaaabaabbbbbaabaaaababbbaaaabaaaabbbaaaaaabbbaaabbaaabbaaaaaabbabbbabbabbbbabaabbababbabaa") ++ (""));
constraint
  (("babbbbaabaaaaaabbbaaaabaaaaaabaaaaabbaaaaabababbaaabaaabababbbbabaabbbbaaababbaaaaaabaaabbabbaaba") ++ (""))
    =
    (("babbbbaab") ++ (B) ++ ("aabaaaaaabaaaaabbaaaaabababbaaabaaabababbbbabaabbbbaaababbaaaaaabaaabbabbaaba"));
constraint
  (("bbabbbbbabbabaaabbaaabababbabaabbaababaaabbbaaaaaaaabbbaaabbbaabbabbaababaaaaaaaaabbbabbababbabbb") ++ (""))
    =
    (("bbabbbbbabbabaaabbaaabababbabaabbaababaaabbbaa") ++ (B) ++ ("abbbaabbabbaababaaaaaaaaabbbabbababbabbb"));
constraint
  (("abbabbbaaabaabbaabbaaaaabb") ++ (B) ++ ("baaabbbbbbbbabbaaabaaaabbabbababbaaaaaabaabaaababaaabbbbbbaa"))
    =
    (("abbabbbaaabaabbaabbaaaaabbaaaaaabbbaabaaabbbbbbbbabbaaabaaaabbabbababbaaaaaabaabaaababaaabbbbbbaa") ++ (""));
constraint
  (("aaaaa") ++ (G) ++ ("abaaaaabbababbabbabbbbaabbbaabbbbaababaaaababaaabbbbaaababbabbaababaabbbababbabb"))
    =
    (("aaaaabbbabababaababaaaaabbababbabbabbbbaabbbaabbbbaababaaaababaaabbbbaaababbabbaababaabbbababbabb") ++ (""));
constraint
  (("aababaabbbbabbabaaabbbaabbabaaabaabaaaaaabbbaaababbabaaabababaabbabaababaababbbbbabaaaaabbabbbbbb") ++ (""))
    =
    (("aababaabbbbabbabaaabbbaabbabaaabaab") ++ (B) ++ ("ababbabaaabababaabbabaababaababbbbbabaaaaabbabbbbbb"));
constraint
  (("abbbbaaaaaabbaaabbbbaaabbaabaaabaaabaabbaaababbbbbababaa") ++ (G) ++ ("abbaabbbbbaababaaabbbbbaabaaa"))
    =
    (("abbbbaaaaaabbaaabbbbaaabbaabaaabaaabaabbaaababbbbbababaabbbabababaababbaabbbbbaababaaabbbbbaabaaa") ++ (""));
constraint
  (("baaaabaaaabaaabbbbaabbbbabaabaaababbbbbaabbbabbbbababaaaaaabbbaababbabaabaaaaababbaabbaabaaaabaaa") ++ (""))
    =
    (("baaaabaaaabaaabbbbaabbbbabaabaaababbbbbaabbbabbbbabab") ++ (B) ++ ("babbabaabaaaaababbaabbaabaaaabaaa"));
constraint
  (("ababbbbabaabbbbabbbbaaaabbabaaabababaaabbbbaaabaaabbbbbaabbabaabbbbababbbbabababaababbabbbababbaa") ++ (""))
    =
    (("ababbbbabaabbbbabbbbaaaabbabaaabababaaabbbbaaabaaabbbbbaabbabaabbbbabab") ++ (G) ++ ("abbabbbababbaa"));
constraint
  (("babaababbbbbaaabaabbabaabaabababbbbbabaabbbbbbbbbabbba") ++ (B) ++ ("bbaabaaabbbbabbbaaabbbbbbbbababb"))
    =
    (("babaababbbbbaaabaabbabaabaabababbbbbabaabbbbbbbbbabbba") ++ (B) ++ ("bbaabaaabbbbabbbaaabbbbbbbbababb"));
constraint
  (("aabaaababbbbaabbbaaaaaaaabaaaaabaaabaababababbbbbabbbbbabaaa") ++ (B) ++ ("aabbbbbbbbaabaaababbaaaaba"))
    =
    (("aabaaababbbbaabbbaaaaaaaabaaaaabaaabaababababbbbbabbbbbabaaa") ++ (B) ++ ("aabbbbbbbbaabaaababbaaaaba"));
constraint
  (("abaaaabbbaaabbaabbaaabbabbbaaababbbbbabbaabaaabbabaabaaaaabaaabababbbbabbabbbabbba") ++ (G) ++ ("bab"))
    =
    (("abaaaabbbaaabbaabbaaabbabbbaaababbbbbabbaabaaabbabaabaaaaabaaabababbbbabbabbbabbbabbbabababaabbab") ++ (""));
constraint
  (("baaabaaaaabaaabaaabbaaabaabbbbbbbbabaabaabaabaaaaaaabaaaaaababbbaabababaabbbabba") ++ (G) ++ ("babab"))
    =
    (("baaabaaaaabaaabaaabbaaabaabbbbbbbbabaabaabaabaaaaaaabaaaaaababbbaabababaabbbabbabbbabababaabbabab") ++ (""));
constraint
  (("abbbbbbaaababaabbabaaaababbbabaaaabaaababab") ++ (G) ++ ("aaababaabbaaaabbbbbababaaaaabaaabaabaaabaa"))
    =
    (("abbbbbbaaababaabbabaaaababbbabaaaabaaabababbbbabababaabaaababaabbaaaabbbbbababaaaaabaaabaabaaabaa") ++ (""));
constraint
  (("aaaaababbbbbabbbbabbaaaabaaabababbb") ++ (G) ++ ("abbaabaaaaabaaababaabbbaaaabbbbbbbbbbaabbaaaabbaba"))
    =
    (("aaaaababbbbbabbbbabbaaaabaaabababbb") ++ (G) ++ ("abbaabaaaaabaaababaabbbaaaabbbbbbbbbbaabbaaaabbaba"));
constraint
  (("aaaaaabbbaabababaaabababaabbabbbbaaaabaabbaababbbbbababbbbaabbbabbbaaabababaabbabbaabaababbabaaab") ++ (""))
    =
    ((B) ++ ("bababaaabababaabbabbbbaaaabaabbaababbbbbababbbbaabbbabbbaaabababaabbabbaabaababbabaaab") ++ (""));
constraint
  (("abaabbabbbaabaaaaaaabbbaabaabaabbabbabaabbbbabaababbbbaaababbbbababbabababbbabaaabbabbaaaabbabbba") ++ (""))
    =
    (("abaabbabbbaaba") ++ (B) ++ ("baabaabbabbabaabbbbabaababbbbaaababbbbababbabababbbabaaabbabbaaaabbabbba"));
constraint
  (("aaababbbaabbaabbbbaabababbbaaabbababbbabaaabbbbabbababbaabbabbaababaaaaaaabbbaabbbabababbabbabbba") ++ (""))
    =
    (("aaababbbaabbaabbbbaabababbbaaabbababbbabaaabbbbabbababbaabbabbaababa") ++ (B) ++ ("bbbabababbabbabbba"));
constraint
  (("bbaababbbbaaaabbaabaabbbabbabaababbbbbaaaaaabaaabaaaaaabbbaaababbaaaaabbabbbabbbaabbababbababbbaa") ++ (""))
    =
    (("bbaababbbbaaaabbaabaabbbabbabaababbbbbaaaaaabaaab") ++ (B) ++ ("ababbaaaaabbabbbabbbaabbababbababbbaa"));
constraint
  ((F) ++ ("bbabbbaaa") ++ (A) ++ ("bbbababbabaabaaabbababaabbaabbabbabbabbabaaba"))
    =
    (("abbbaaabbabbbbababaabbabbabbbaaabaa") ++ (B) ++ ("babaabaaabbababaabbaabbabbabbabbabaaba"));
constraint
  (("abbabbaaabbbaabababbaabbbabbbaaabbabaabaabbbbabaaabbbbbaabbb") ++ (C) ++ ("abaaaabbabbbabbabbaababaaaba"))
    =
    (("abbabbaaabbbaabababbaabbbabbbaaabbabaabaabbbbabaaabbbbbaabbb") ++ (C) ++ ("abaaaabbabbbabbabbaababaaaba"));
constraint
  (("abbbaabbbbbbbaaabbabbbbaabbabbbaabababa") ++ (C) ++ ("bbabbbabbabbbabbaaababbbbaabbaababababaababbbbaba"))
    =
    (("abbbaabbbbbbbaaabbabbbbaabbabbbaababababbabbbbabbbabbbabbabbbabbaaababbbbaabbaababababaababbbbaba") ++ (""));
constraint
  (("aaa") ++ (C) ++ ("bbbbabbbbaaaaabaaaaaaaabbbabbaaaababbbbbabbabbababbaabaaabababaaabbabababbbbaabbaaaaa"))
    =
    (("aaa") ++ (C) ++ ("bbbbabbbbaaaaabaaaaaaaabbbabbaaaababbbbbabbabbababbaabaaabababaaabbabababbbbaabbaaaaa"));
constraint
  (("aaaaababbababbaa") ++ (C) ++ ("bbaaaaaaaabbaaaabaaabaabbababaaaabaabbbaabaababbabaabaaababbbbaaabbbaaaa"))
    =
    (("aaaaababbababbaa") ++ (C) ++ ("bbaaaaaaaabbaaaabaaabaabbababaaaabaabbbaabaababbabaabaaababbbbaaabbbaaaa"));
constraint
  (("abbabaaaababababbabbabbaaaababaabaabaabaaaaabbabaababb") ++ (C) ++ ("bbbbabbbbaaaabbbaaabbbbbabbbabaaaa"))
    =
    (("abbabaaaababababbabbabbaaaababaabaabaabaaaaabbabaababbbbabbbbabbbbbabbbbaaaabbbaaabbbbbabbbabaaaa") ++ (""));
constraint
  (("bbbbaaabbbabbaaaabbaabbbbababbbbaaabaabaababbaaaaaabbbaaabbbbbabaaaaaabbbaabbaaaaab") ++ (C) ++ ("abbab"))
    =
    (("bbbbaaabbbabbaaaabbaabbbbababbbbaaabaabaababbaaaaaabbbaaabbbbbabaaaaaabbbaabbaaaaab") ++ (C) ++ ("abbab"));
constraint
  (("abbbababbaaababababaaabbbbaabbbbbbbbbabbaaaabababbbbbbbbbbbabbbbababbaaabaaabaaaaaabbaabbabbaabba") ++ (""))
    =
    (("abbbababbaaababababaaabbbbaabbbbbbbbbabbaaaabababbbbbbbbb") ++ (C) ++ ("abbaaabaaabaaaaaabbaabbabbaabba"));
constraint
  (("bbaababbbaaaabaabbbbaaaaabbaabbbbbbabbbaabaabababaabbbabbbabbbbabbaaabbbabbababaabaabbbaaaaababbb") ++ (""))
    =
    (("bbaababbbaaaabaabbbbaaaaabbaabbbbbbabbbaabaabababaabbbab") ++ (C) ++ ("baaabbbabbababaabaabbbaaaaababbb"));
constraint
  (("abbaababaaabbaababbaaabbaabaaabbabbbabbaabaaaabbbababbbbbbbabbbaabbabab") ++ (C) ++ ("baabbababbbaaaaaa"))
    =
    (("abbaababaaabbaababbaaabbaabaaabbabbbabbaabaaaabbbababbbbbbbabbbaabbabab") ++ (C) ++ ("baabbababbbaaaaaa"));
constraint
  (("bbabbbababbababaaabbbaabaaabaabbababbbbabbaababbaabbbbbababbbaabbaaaabababaaaabab") ++ (C) ++ ("abbbbba"))
    =
    (("bbabbbababbababaaabbbaabaaabaabbababbbbabbaababbaabbbbbababbbaabbaaaabababaaaababbbabbbbababbbbba") ++ (""));
constraint
  (("ababbabbbaaabbbabbaaabbabaabaabab") ++ (C) ++ ("ababbbaabbabbbabbaabaabbbbbbbabbaabbbabaabaaabbbaaaaaab"))
    =
    (("ababbabbbaaabbbabbaaabbabaabaababbbabbbbabababbbaabbabbbabbaabaabbbbbbbabbaabbbabaabaaabbbaaaaaab") ++ (""));
constraint
  (("bbabbaaaaabbabaaababbaabbaaaaabbbbbabaabbbbaababaabbba") ++ (C) ++ ("abbabbaabbabaaaaaaabaabababaaaabab"))
    =
    (("bbabbaaaaabbabaaababbaabbaaaaabbbbbabaabbbbaababaabbba") ++ (C) ++ ("abbabbaabbabaaaaaaabaabababaaaabab"));
constraint
  (("abbaababbabbbaaabbabbbbaabaabbaaaabaababababbbbabbbaaababbbaabbbabbbbaaababbaaaab") ++ (C) ++ ("bbbbbaa"))
    =
    (("abbaababbabbbaaabbabbbbaabaabbaaaabaababababbbbabbbaaababbbaabbbabbbbaaababbaaaabbbabbbbabbbbbbaa") ++ (""));
constraint
  (("ababbaaabbbbaababbabbababbbaabababbbbabbbbb") ++ (C) ++ ("abbaaaabbaabbaaabbababbbbaabbaabbbaabbbaabbba"))
    =
    (("ababbaaabbbbaababbabbababbbaabababbbbabbbbbbbabbbbababbaaaabbaabbaaabbababbbbaabbaabbbaabbbaabbba") ++ (""));
constraint
  (("aabbbbbbbabbaaabababaaabbbaaaabbabbaaabbbabbbabaabaabaabbbbbaaabba") ++ (C) ++ ("baaaababbaabaaaaaababb"))
    =
    (("aabbbbbbbabbaaabababaaabbbaaaabbabbaaabbbabbbabaabaabaabbbbbaaabba") ++ (C) ++ ("baaaababbaabaaaaaababb"));
constraint
  (("bbabaabbbbbaabbabbababaaabbbbbaaababababbbbbabbaabbaaaaabbab") ++ (C) ++ ("bbababbbbbabaabbbbbabbaaabab"))
    =
    (("bbabaabbbbbaabbabbababaaabbbbbaaababababbbbbabbaabbaaaaabbabbbabbbbabbbababbbbbabaabbbbbabbaaabab") ++ (""));
constraint
  (("baababaabbbaabbbbbaabbbaabbabababbbabbbbabbbaabaabbabbaaababbaabaaaaabababbbaaaabbaabaaaabbbaabba") ++ (""))
    =
    (("baababaabbbaabbbbbaabbbaabbababab") ++ (C) ++ ("bbaabaabbabbaaababbaabaaaaabababbbaaaabbaabaaaabbbaabba"));
constraint
  (("bbaaaaaaabbbab") ++ (C) ++ ("ababbbbababbabbbabbaabbbbbbbaaabbabbaaabbabaababbaabababbabbababbaaaaabaab"))
    =
    (("bbaaaaaaabbbabbbabbbbabababbbbababbabbbabbaabbbbbbbaaabbabbaaabbabaababbaabababbabbababbaaaaabaab") ++ (""));
constraint
  (("bbbbababaabbbbaaaabbbabaababbaaaabaabbbbbabbbabbbbb") ++ (C) ++ ("babbababbbabbbbbabbbabbbabbaabbbbabba"))
    =
    (("bbbbababaabbbbaaaabbbabaababbaaaabaabbbbbabbbabbbbb") ++ (C) ++ ("babbababbbabbbbbabbbabbbabbaabbbbabba"));
constraint
  (("bbbbaababbaaabaababbbabbaaaaabbaaaaaabaaabababbaabbbaaaabbaabbbbbbaaaabbabbbbabbaababbaabbaaabaab") ++ (""))
    =
    (("bbbbaababbaaabaababbbabbaaaaabbaaaaaabaaabababbaabbbaaaabbaabbbbbbaaaa") ++ (C) ++ ("baababbaabbaaabaab"));
constraint
  (("bbbbaaaabbbbbbabbaabaabbbbbbabbaaabbbabababaababaabbbabbbbabaaababbbbaabbbbaaaaaabbbbaababaaababb") ++ (""))
    =
    (("bbbbaaaabbbbbbabbaabaabbbbbbabbaaabbbabababaababaab") ++ (C) ++ ("aaababbbbaabbbbaaaaaabbbbaababaaababb"));
constraint
  (("abaaabababaaabbabaabbbbabbbaaaaabaababababaaaabbaabbabaaaaabbbaaaaaaaabaababaabbabaa") ++ (C) ++ ("aaab"))
    =
    (("abaaabababaaabbabaabbbbabbbaaaaabaababababaaaabbaabbabaaaaabbbaaaaaaaabaababaabbabaa") ++ (C) ++ ("aaab"));
constraint
  (("bbaabbbabbaaabbbbabbbbabaabaaaaabbbbaaaabbbbaaaabbaaaaaa") ++ (C) ++ ("bbabaaababbbbbababaababbbbabbaab"))
    =
    (("bbaabbbabbaaabb") ++ (C) ++ ("aabaaaaabbbbaaaabbbbaaaabbaaaaaa") ++ (C) ++ ("bbabaaababbbbbababaababbbbabbaab"));
constraint
  (("abababbaaabbbbbababbbbababbbbabbaabbabaaabaaaaaaabaabaaaaabaabbba") ++ (C) ++ ("bbbbbbababbbabababaabbb"))
    =
    (("abababbaaabbbbbababbbbababbbbabbaabbabaaabaaaaaaabaabaaaaabaabbbabbabbbbabbbbbbbababbbabababaabbb") ++ (""));
constraint
  (("aaaaaabaaba") ++ (C) ++ ("bababababbaabbbbbaababaaaaaaabaaaabbbbaabababbaabaaabbaaaababaaaaabaababaaaba"))
    =
    (("aaaaaabaaba") ++ (C) ++ ("bababababbaabbbbbaababaaaaaaabaaaabbbbaabababbaabaaabbaaaababaaaaabaababaaaba"));
constraint
  (("abababbbbbbababaababbbbababbababaabaaababababaabababaaaababaaabaabbabbbbabaaabbbabbbbbaaaaabaabaa") ++ (""))
    =
    (("abababbbbbbababaababbbbababbababaabaaababababaabababaaaababaaabaa") ++ (C) ++ ("aaabbbabbbbbaaaaabaabaa"));
constraint
  (("aabbabbabbbbabaaaaabbbababbaaabaabaaaabbbabaaaabbabbbababbbbababbaabaaaababbbbbbbbbabbbaaaabbaabb") ++ (""))
    =
    (("aabba") ++ (C) ++ ("aaaaabbbababbaaabaabaaaabbbabaaaabbabbbababbbbababbaabaaaababbbbbbbbbabbbaaaabbaabb"));
constraint
  (("abbbbbaaabbbabababbabbbbabaaabbbaabbbababbbbabbbaaabbabaaababbabababbaababababbaaaaaabaababbbaaab") ++ (""))
    =
    (("abbbbbaaabbbababa") ++ (C) ++ ("aaabbbaabbbababbbbabbbaaabbabaaababbabababbaababababbaaaaaabaababbbaaab"));
constraint
  (("bbbbbbbabbaabbaababbaabaaabbababbbabaaaabbbbbabbbbabbabaababbbbaabaabbbaabbbaabaabbbabbbaabbbabab") ++ (""))
    =
    (("bbbbbbbabbaabbaababbaabaaabbababbbabaaaabbb") ++ (C) ++ ("babaababbbbaabaabbbaabbbaabaabbbabbbaabbbabab"));
constraint
  (("bbbbbaaabaaaaabaabbaabbbaaaaaaabbaaabbabababbabaabbbbabab") ++ (C) ++ ("abaababbbbaabaabaabbaaabbbbaaab"))
    =
    (("bbbbbaaabaaaaabaabbaabbbaaaaaaabbaaabbabababbabaabbbbababbbabbbbababaababbbbaabaabaabbaaabbbbaaab") ++ (""));
constraint
  (("aababababaabbbaaabbaaaabaaaabbbaaaabbbbabbbbbbbaabaabbbababaabaabaaabbabaaaaaabbbabbab") ++ (C) ++ ("aa"))
    =
    (("aababababaabbbaaabbaaaabaaaabbbaaaabbbbabbbbbbbaabaabbbababaabaabaaabbabaaaaaabbbabbabbbabbbbabaa") ++ (""));
constraint
  (("baabbaaabbbabaaaa") ++ (C) ++ ("bbbabbbbaabaaabaabbaaabbaaababababbabbbbbaaaabbaabaaababaabbbabbababaab"))
    =
    (("baabbaaabbbabaaaa") ++ (C) ++ ("bbbabbbbaabaaabaabbaaabbaaababababbabbbbbaaaabbaabaaababaabbbabbababaab"));
constraint
  (("baaabbabbaaabbaabbbabbaaaaabaabaaa") ++ (C) ++ ("baaaaaabbababbbabbaabaaabbaababbaabbabbbaabaabaabaaaba"))
    =
    (("baaabbabbaaabbaabbbabbaaaaabaabaaa") ++ (C) ++ ("baaaaaabbababbbabbaabaaabbaababbaabbabbbaabaabaabaaaba"));
constraint
  (("ababbbabbabbbbaabaaabbbaabbbaaabaaaaaaabbaaaaaaabbbbabbbbbaa") ++ (C) ++ ("babbababbbababbbaaaaaabbbbbb"))
    =
    (("ababbbabbabbbbaabaaabbbaabbbaaabaaaaaaabbaaaaaaabbbbabbbbbaabbabbbbabbabbababbbababbbaaaaaabbbbbb") ++ (""));
constraint
  (("aabbababbbbbbabbbbbabaabbbbbaabbaaabbbbbabbbbabbaaaaaabbbbbbbbbbaabbababbaabaabbbaaaababbabbbbbba") ++ (""))
    =
    (("aabbababbbbbbabbbbbabaabbbbbaabbaaabbb") ++ (C) ++ ("baaaaaabbbbbbbbbbaabbababbaabaabbbaaaababbabbbbbba"));
constraint
  (("babababbbaaabbbbabbbbabaaaabbbaaababbaababaaaabaabbbabababbbababbbbaaaaaababbbbabbbabbababaaabbbb") ++ (""))
    =
    (("babababbbaaabb") ++ (C) ++ ("aaaabbbaaababbaababaaaabaabbbabababbbababbbbaaaaaababbbbabbbabbababaaabbbb"));
constraint
  (("abbbbabbbbbbabaaabbbabbabababbbaabbbababaabbbaaababababbbbbaabababbbbbaababbbabaabb") ++ (C) ++ ("bbbbb"))
    =
    (("abbbbabbbbbbabaaabbbabbabababbbaabbbababaabbbaaababababbbbbaabababbbbbaababbbabaabb") ++ (C) ++ ("bbbbb"));
constraint
  (("aaabbbaabbbababbaaaabbbbbaaaabbbbbabbbbabbaaaabbabbaaaaaabbababaaabbaabbaabaabaaabaaaababbbababbb") ++ (""))
    =
    (("aaabbbaabbbababbaaaabbbbbaaaabbb") ++ (C) ++ ("baaaabbabbaaaaaabbababaaabbaabbaabaabaaabaaaababbbababbb"));
constraint
  (("abbbbbaabbaaabaaaabbababbabababababbbbabbbbabaabaababaabbaabaaabbabbbbaabbaabababbbbaabbabbaaaaab") ++ (""))
    =
    (("abbbbbaabbaaabaaaabbababbabababababb") ++ (C) ++ ("aabaababaabbaabaaabbabbbbaabbaabababbbbaabbabbaaaaab"));
constraint
  (("baaabaabaabbbaaabbabababaabbaababaabaabbaabababaababbbababbbbaabbaaaaaaaaababbbabbbbabaabbbaabaab") ++ (""))
    =
    (("baaabaabaabbbaaabbabababaabbaababaabaabbaabababaababbbababbbbaabbaaaaaaaaabab") ++ (C) ++ ("aabbbaabaab"));
constraint
  (("abbabab") ++ (C) ++ ("aaaaabababbbbabbaabbbbbaababbabbababaab") ++ (C) ++ ("aabaaabbaaaabaaabbbabbaaaabaabbba"))
    =
    (("abbababbbabbbbabaaaaabababbbbabbaabbbbbaababbabbababaabbbabbbbabaabaaabbaaaabaaabbbabbaaaabaabbba") ++ (""));
constraint
  (("baaabbaaaabaa") ++ (C) ++ ("baaaabbaabbabaaabbbbbaaabaabaabbabbbaabaaabbaababbbabbaaabbababbaababaaaaba"))
    =
    (("baaabbaaaabaabbabbbbabbaaaabbaabbabaaabbbbbaaabaabaabbabbbaabaaabbaababbbabbaaabbababbaababaaaaba") ++ (""));
constraint
  (("babbbaaaababaabbbaaababaabbbabbabbbaabbbbbbaaabaabaaaababbbaaba") ++ (C) ++ ("aabaaabbabbabbbababbbaaaa"))
    =
    (("babbbaaaababaabbbaaababaabbbabbabbbaabbbbbbaaabaabaaaababbbaaba") ++ (C) ++ ("aabaaabbabbabbbababbbaaaa"));
constraint
  (("bababababba") ++ (C) ++ ("aabbaabbbaabbbaaabbbbaabaaabaabaabaabaaaabbabaaaabaabbaaaabaaaabaaaaaabaaabab"))
    =
    (("bababababbabbabbbbabaabbaabbbaabbbaaabbbbaabaaabaabaabaabaaaabbabaaaabaabbaaaabaaaabaaaaaabaaabab") ++ (""));
constraint
  (("bbaabaaaabbbaabaabaabbbbaaabbababbbabababaaaabbbbbaaaabbaabababbababaabaaaa") ++ (C) ++ ("aaaaabbaaabaa"))
    =
    (("bbaabaaaabbbaabaabaabbbbaaabbababbbabababaaaabbbbbaaaabbaabababbababaabaaaabbabbbbabaaaaabbaaabaa") ++ (""));
constraint
  (("bbabaaaabababaaaaaaaaababbabaaababbbbbbbbaababbaaabbbbbabbbabaaabbababbabbbbababbbbaabaabbbbaaaaa") ++ (""))
    =
    (("bbabaaaabababaaaaaaaaababbabaaababbbbbbbbaababbaaabbbbbabbbabaaabbaba") ++ (C) ++ ("abbbbaabaabbbbaaaaa"));
constraint
  (("babbbbaaaaaabbaababbbaabbabbbaabbaaabbabaababbbbbbbbbbaabbabbabbbbaaabbaaababaabaabababbabbbbabbb") ++ (""))
    =
    (("babbbbaaaaaabbaababbbaabbabbbaabbaaabbabaababbbbbbbbbbaabbabbabbbbaaabbaaababaabaababa") ++ (C) ++ ("bb"));
constraint
  (("abbbabababbaabbababaabababbbbb") ++ (C) ++ ("ababbaaababaabb") ++ (C) ++ ("bbaaabaababbaaabababababbbbabaaabb"))
    =
    (("abbbabababbaabbababaabababbbbbbbabbbbabababbaaababaabb") ++ (C) ++ ("bbaaabaababbaaabababababbbbabaaabb"));
constraint
  (("babbabbabababababbababaaaaaaabaabbabbabbbb") ++ (C) ++ ("aaaababaaabaaababbbbabbbabaabababaaaabababaaab"))
    =
    (("babbabbabababababbababaaaaaaabaabbabbabbbbbbabbbbabaaaababaaabaaababbbbabbbabaabababaaaabababaaab") ++ (""));
constraint
  (("baaabaaabbaabaababaabbaabbabbbaaaababbaabbaaaa") ++ (C) ++ ("babbbbabbbababbbbbabbbbbabbbaabbbabaabbbab"))
    =
    (("baaabaaabbaabaababaabbaabbabbbaaaababbaabbaaaabbabbbbabbabbbbabbbababbbbbabbbbbabbbaabbbabaabbbab") ++ (""));
constraint
  (("babbbbaaaabaabbaaabaaaababbbabaaabaaabbbaaabbababaabababaaaaaabbaaaaabbbaabba") ++ (C) ++ ("abbbbbbaaba"))
    =
    (("babbbbaaaabaabbaaabaaaababbbabaaabaaabbbaaabbababaabababaaaaaabbaaaaabbbaabbabbabbbbababbbbbbaaba") ++ (""));
constraint
  (("bbaaabbaaaaabbbbaabbbabbaaaaaaaaababbaabbaaabaabaaaabababaabbbabaaabb") ++ (C) ++ ("baabbbbbbabababbbbb"))
    =
    (("bbaaabbaaaaabbbbaabbbabbaaaaaaaaababbaabbaaabaabaaaabababaabbbabaaabbbbabbbbabbaabbbbbbabababbbbb") ++ (""));
constraint
  (("babbbbbabbababaaaaaaaabbababababbaabbbaa") ++ (C) ++ ("babbbbbbabbbbaaabbabbbbabaaabbbaabbbbababaaaabab"))
    =
    (("babbbbbabbababaaaaaaaabbababababbaabbbaa") ++ (C) ++ ("babbbbbbabbbbaaabbabbbbabaaabbbaabbbbababaaaabab"));
constraint
  (("bbababaaaaaabbbbababaaaaabbabaabababbababababbbaaabaaaabbaba") ++ (C) ++ ("abbbbbaaababbbbbabbbbbabbaba"))
    =
    (("bbababaaaaaabbbbababaaaaabbabaabababbababababbbaaabaaaabbaba") ++ (C) ++ ("abbbbbaaababbbbbabbbbbabbaba"));
constraint
  (("bbbbaaaabbbbabaaababa") ++ (C) ++ ("abbbbabbbabaaabaaababaaaabaababbbabbbaaaabaaaabababbbabaabaaabbaaaa"))
    =
    (("bbbbaaaabbbbabaaabababbabbbbababbbbabbbabaaabaaababaaaabaababbbabbbaaaabaaaabababbbabaabaaabbaaaa") ++ (""));
constraint
  (("aabbbaaabbbbabbbbababaabbbbaababbbabbaaaabbbabbbaaaaaaaabbabbabaabaabbaabaababbbabbaabbaabbababba") ++ (""))
    =
    (("aabbbaaabb") ++ (C) ++ ("abaabbbbaababbbabbaaaabbbabbbaaaaaaaabbabbabaabaabbaabaababbbabbaabbaabbababba"));
constraint
  (("abbbbbbaabaabaaaaabaaabaabaababbbbababbabbabaabbaaaaa") ++ (C) ++ ("ababbbabbbb") ++ (C) ++ ("aabbbabbbaabbab"))
    =
    (("abbbbbbaabaabaaaaabaaabaabaababbbbababbabbabaabbaaaaa") ++ (C) ++ ("ababbbabbbb") ++ (C) ++ ("aabbbabbbaabbab"));
constraint
  (("bbabaabaaabbabbbbabaaababaaabaabb") ++ (C) ++ ("aaaaaabbaabaabaababbbbaaabbbbbaaaababbaaabababaababbaaa"))
    =
    (("bbabaabaaa") ++ (C) ++ ("aaababaaabaabb") ++ (C) ++ ("aaaaaabbaabaabaababbbbaaabbbbbaaaababbaaabababaababbaaa"));
constraint
  (("babbbbabbabbbaaabbabbabbbbbbbabbaaaabbbbbabbbbabbbbbbbabbbabaaabaaabaaaaababababbabbbbbaabaababba") ++ (""))
    =
    (("babbbbabbabbbaaabbabbabbbbbbbabbaaaabbb") ++ (C) ++ ("bbbbbbabbbabaaabaaabaaaaababababbabbbbbaabaababba"));
constraint
  (("bbabbbaabbbabbbabbbababaaabbbabaaaaaababbbabaabbabbbabbbaabbbbbaabbbabbabbbbababaabbbaabbababbbba") ++ (""))
    =
    (("bbabbbaabbbabbbabbbababaaabbbabaaaaaababbbabaabbabbbabbbaabbbbbaabbba") ++ (C) ++ ("abaabbbaabbababbbba"));
constraint
  (("aaabaaaaaaabbbaabaabbaabbbbaba") ++ (C) ++ ("bbaaabbabbbbaaaabbbaabbaaaabbaabaababaaaababbbbaaaaabaaaab"))
    =
    (("aaabaaaaaaabbbaabaabbaabbbbaba") ++ (C) ++ ("bbaaabbabbbbaaaabbbaabbaaaabbaabaababaaaababbbbaaaaabaaaab"));
constraint
  (("bbbbbbbbbbaaababbababbaabaaaaababbabbbaababababaabaabbaaaabaaaabbb") ++ (C) ++ ("bbaabbbbbabaababababba"))
    =
    (("bbbbbbbbbbaaababbababbaabaaaaababbabbbaababababaabaabbaaaabaaaabbb") ++ (C) ++ ("bbaabbbbbabaababababba"));
solve satisfy;
