var string: A;
constraint
  (("dcddccd") ++ (A) ++ ("ddbbdadadaab")) =
    (("dcddccdabdacbaccabadbacddccbcbcacdbddbabbbcdaddbbdadadaab") ++ (""));
constraint
  (("ddab") ++ (A) ++ ("acbcaabccbbdbbccddbbddbdbcccdbaddcdcbdcdbadacbcda"))
    =
    (("ddab") ++ (A) ++ ("acbcaabccbbdbbccddbbddbdbcccdbaddcdcbdcdbadacbcda"));
constraint
  (("acdcddcdcbdbdddacaaabacbbccbbddbddaddcdcdbcddaccdcddcbdbb") ++ ("")) =
    (("acdcddcdcbdbddda") ++ (A) ++ ("bacbbccbbddbddaddcdcdbcddaccdcddcbdbb"));
constraint
  (("ddccdbcdbaddbccbadabb") ++ (A) ++ ("dbbbdaaacdabbdabdaabdababdcaadaa"))
    = (("ddccdbcdbaddbccbadabbcaaadbbbdaaacdabbdabdaabdababdcaadaa") ++ (""));
constraint
  (("ccbcbddccdbbdbbbbdcacdbbbccbbadbdc") ++ (A) ++ ("acdbabcbbaaaddddbaa"))
    = (("ccbcbddccdbbdbbbbdcacdbbbccbbadbdccaaaacdbabcbbaaaddddbaa") ++ (""));
constraint
  (("acacadbdacbdc") ++ (A) ++ ("cdbbaaaaadbdcacaccdbcbaacbccaadbddcacbda"))
    = (("acacadbdacbdccaaacdbbaaaaadbdcacaccdbcbaacbccaadbddcacbda") ++ (""));
constraint
  (("dabbbdabdddabaddbadadabcbadadabdbbddabbd") ++ (A) ++ ("ddabdbaaabada"))
    =
    (("dabbbdabdddabaddbadadabcbadadabdbbddabbd") ++ (A) ++ ("ddabdbaaabada"));
constraint
  (("bbbbbbbdbabababdbbaaabcaaabdaabcbdbcaaacddabbbaadcdcdaabc") ++ ("")) =
    (("bbbbbbbdbabababdbbaaab") ++ (A) ++ ("bdaabcbdbcaaacddabbbaadcdcdaabc"));
constraint
  (("dbaaabacbbbbcbbbdbdcbaadaadbbdcaaddcaaacaababddbadaabdcac") ++ ("")) =
    (("dbaaabacbbbbcbbbdbdcbaadaadbbdcaadd") ++ (A) ++ ("caababddbadaabdcac"));
constraint
  (("aadc") ++ (A) ++ ("abcccbccabdbcaddaccaddccacdbaddddcdcacbcdbbaaadaa"))
    =
    (("aadc") ++ (A) ++ ("abcccbccabdbcaddaccaddccacdbaddddcdcacbcdbbaaadaa"));
constraint
  (("caddadcccadbbbcadbdaaacbabcdaadcdbbbacaaabdadacdbbabccddd") ++ ("")) =
    (("caddadcccadbbbcadbdaaacbabcdaadcdbbba") ++ (A) ++ ("bdadacdbbabccddd"));
constraint
  (("bacaaadaadbbbdbcbadabcdadddcdcdbbcaadabcdacdaabaabbadbcdb") ++ ("")) =
    (("ba") ++ (A) ++ ("daadbbbdbcbadabcdadddcdcdbbcaadabcdacdaabaabbadbcdb"));
constraint
  (("ccab") ++ (A) ++ ("accaadcadcbdbdcaabbacacaaddacacbbdcababcaaddccdda"))
    =
    (("ccab") ++ (A) ++ ("accaadcadcbdbdcaabbacacaaddacacbbdcababcaaddccdda"));
constraint
  (("abdbbbbaddabbadadddabba") ++ (A) ++ ("bcbaddbadaaacadadbaaaccdbdadda"))
    =
    (("abdbbbbaddabbadadddabba") ++ (A) ++ ("bcbaddbadaaacadadbaaaccdbdadda"));
constraint
  (("ccbadcadccdbbabaccdadbcacdba") ++ (A) ++ ("cdaaddcaadaabbbcddacdcdbc"))
    =
    (("ccbadcadccdbbabaccdadbcacdba") ++ (A) ++ ("cdaaddcaadaabbbcddacdcdbc"));
constraint
  (("a") ++ (A) ++ ("abdbbaaabdbcaabbcddbddbbbabcddacdbcbaddaaaacbaabdbbb"))
    = (("acaaaabdbbaaabdbcaabbcddbddbbbabcddacdbcbaddaaaacbaabdbbb") ++ (""));
constraint
  (("addccbaacdccadbbcacdbadccdbdacaacbdbadcacbadbdcaaabdacaca") ++ ("")) =
    (("addccbaacdccadbbcacdbadccdbdacaacbdbadcacbadbd") ++ (A) ++ ("bdacaca"));
constraint
  (("cdddccbddabdbbdacadcbccbbcaaabaadcbbcbaaaaabbdccacaabbacc") ++ ("")) =
    (("cdddccbddabdbbdacadcbccbb") ++ (A) ++ ("baadcbbcbaaaaabbdccacaabbacc"));
constraint
  (("cadcaabdbbcadadcbdddbbdccbdbababbbadabbbdcacababb") ++ (A) ++ ("cabc"))
    =
    (("cadcaabdbbcadadcbdddbbdccbdbababbbadabbbdcacababb") ++ (A) ++ ("cabc"));
constraint
  (("dccdadbabdddabbcaddbabdabdcbddbcdabbbacdcaadddbbcaaadabab") ++ ("")) =
    (("dccdadbabdddabbcaddbabdabdcbddbcdabbbacdcaadddbb") ++ (A) ++ ("dabab"));
constraint
  (("bcbcddbadcbadbdbbacadc") ++ (A) ++ ("daaaadcaacbacbbddaacadaadabadad"))
    = (("bcbcddbadcbadbdbbacadccaaadaaaadcaacbacbbddaacadaadabadad") ++ (""));
constraint
  (("acdddbdaacdcdaaacb") ++ (A) ++ ("bcacaadbbdbdadaaaaacbcccdcddddbbacb"))
    = (("acdddbdaacdcdaaacbcaaabcacaadbbdbdadaaaaacbcccdcddddbbacb") ++ (""));
constraint
  (("bcadacdddcbdaada") ++ (A) ++ ("dcddbcddcddaadabcbccdaabcbccccabcabdd"))
    =
    (("bcadacdddcbdaada") ++ (A) ++ ("dcddbcddcddaadabcbccdaabcbccccabcabdd"));
constraint
  (("aacdcbcbdadcaaaddbdccdcdccdcbcadcacddbbddbbdbdbbdccdcdacc") ++ ("")) =
    (("aacdcbcbdad") ++ (A) ++ ("ddbdccdcdccdcbcadcacddbbddbbdbdbbdccdcdacc"));
constraint
  (("abcacccdcbacbcdcbacacdabbababbccbddacadaaadabcaaacdcbccad") ++ ("")) =
    (("abcacccdcbacbcdcbacacdabbababbccbddacadaaadab") ++ (A) ++ ("cdcbccad"));
constraint
  (("dacbbccabbcbadacdadadddaccbbbaccccbdabaaccaaadddacbdddddd") ++ ("")) =
    (("dacbbccabbcbadacdadadddaccbbbaccccbdabaac") ++ (A) ++ ("dddacbdddddd"));
constraint
  (("cddcdacbbcdbbcbdbbbdcdbcdbabdcaaacbbbacccacadcaaccdddcbbd") ++ ("")) =
    (("cddcdacbbcdbbcbdbbbdcdbcdbabd") ++ (A) ++ ("cbbbacccacadcaaccdddcbbd"));
constraint
  (("cdacabcadcccadbdccbcbcaaccdcaddbdcdaccaab") ++ (A) ++ ("bdddacdcbbca"))
    = (("cdacabcadcccadbdccbcbcaaccdcaddbdcdaccaabcaaabdddacdcbbca") ++ (""));
constraint
  (("bcacddadcadacddbdddabbaadbcd") ++ (A) ++ ("acdbcdccbdbdcaccabcacbdad"))
    = (("bcacddadcadacddbdddabbaadbcdcaaaacdbcdccbdbdcaccabcacbdad") ++ (""));
constraint
  (("adaabcbdaabddabcbbdbccdabddccdbcbcccadcbd") ++ (A) ++ ("bacdbdcbcacc"))
    = (("adaabcbdaabddabcbbdbccdabddccdbcbcccadcbdcaaabacdbdcbcacc") ++ (""));
constraint
  (("caccbdbadaaccadbdbbbcb") ++ (A) ++ ("bcbcaddbabaadccccbdddbabaddacaa"))
    = (("caccbdbadaaccadbdbbbcbcaaabcbcaddbabaadccccbdddbabaddacaa") ++ (""));
constraint
  (("bd") ++ (A) ++ ("bcddcdaacadcdacdacddacacdbdacbddcccacddbdccddbabaca"))
    = (("bdcaaabcddcdaacadcdacdacddacacdbdacbddcccacddbdccddbabaca") ++ (""));
constraint
  (("caabdababdaadabba") ++ (A) ++ ("abcaadabcddbbcadbaaacddbdabdcddbcbaa"))
    = (("caabdababdaadabbacaaaabcaadabcddbbcadbaaacddbdabdcddbcbaa") ++ (""));
constraint
  (("bdaaaddbcacabcbabccaaaccbacbcbdadcdadaccccdccdbdadbdbbadb") ++ ("")) =
    (("bdaaaddbcacabcbabc") ++ (A) ++ ("ccbacbcbdadcdadaccccdccdbdadbdbbadb"));
constraint
  (("adbcbadd") ++ (A) ++ ("dbdaddbbdadabcbaccbbcdaccabaacbcdcabaccadaacc"))
    = (("adbcbaddcaaadbdaddbbdadabcbaccbbcdaccabaacbcdcabaccadaacc") ++ (""));
constraint
  (("bacbdbccbcccadbdcccaaaadcdbbdaddddabddacccbcbcddcdccdccdd") ++ ("")) =
    (("bacbdbccbcccadbdcc") ++ (A) ++ ("adcdbbdaddddabddacccbcbcddcdccdccdd"));
constraint
  (("dbcdabccaccbcbbdc") ++ (A) ++ ("ddaabdbadddacbbbddadaadcabacddbcacbc"))
    = (("dbcdabccaccbcbbdccaaaddaabdbadddacbbbddadaadcabacddbcacbc") ++ (""));
constraint
  (("dcccabcbdbadaab") ++ (A) ++ ("bbabcaadbbddddcbaacddddcbbadddcdccccbb"))
    =
    (("dcccabcbdbadaab") ++ (A) ++ ("bbabcaadbbddddcbaacddddcbbadddcdccccbb"));
constraint
  (("bdacbacccaaaccdabdcbbcdcaadabcdcdbdaadaadaababacbcbcaccdd") ++ ("")) =
    (("bdacbacc") ++ (A) ++ ("ccdabdcbbcdcaadabcdcdbdaadaadaababacbcbcaccdd"));
constraint
  (("dbcdcbcc") ++ (A) ++ ("cabaadccbbcdbbcdcdabcaddbbaaacbcbddaddaddacaa"))
    = (("dbcdcbcccaaacabaadccbbcdbbcdcdabcaddbbaaacbcbddaddaddacaa") ++ (""));
constraint
  (("ccacacaaaadcaacaabadcbacbcaccacdaacabcabbcdbccacccabddcbb") ++ ("")) =
    (("ccaca") ++ (A) ++ ("adcaacaabadcbacbcaccacdaacabcabbcdbccacccabddcbb"));
constraint
  (("ccbdbccadabaadcbcbabc") ++ (A) ++ ("bbdacbacdccdcacaabccabcbaadacccc"))
    =
    (("ccbdbccadabaadcbcbabc") ++ (A) ++ ("bbdacbacdccdcacaabccabcbaadacccc"));
constraint
  (("dbbacaddaaaddddcdaddbacccaccdcbbbdbabcabaccacadcac") ++ (A) ++ ("ccb"))
    = (("dbbacaddaaaddddcdaddbacccaccdcbbbdbabcabaccacadcaccaaaccb") ++ (""));
constraint
  (("accbccbccdcaccdbddbabbcaaadcaaddcdaabbbdbacabbcbbbcdadaad") ++ ("")) =
    (("accbccbccdcaccdbddbabb") ++ (A) ++ ("dcaaddcdaabbbdbacabbcbbbcdadaad"));
constraint
  (("bcdbddbbadbd") ++ (A) ++ ("dddcacadaddcdaddcacbaaddaacdccbcddbdaacdd"))
    =
    (("bcdbddbbadbd") ++ (A) ++ ("dddcacadaddcdaddcacbaaddaacdccbcddbdaacdd"));
constraint
  (("baadbabbacccaabcadcdcbadbbdcccaaabbaccdabdccbdbccadaccdba") ++ ("")) =
    (("baadbabbacccaabcadcdcbadbbdcc") ++ (A) ++ ("bbaccdabdccbdbccadaccdba"));
constraint
  (("cbacaabbbdccaacbbcaacddadbabacdaccdbccaaabacdabacaacaadaa") ++ ("")) =
    (("cbacaabbbdccaacbbcaacddadbabacdaccdbc") ++ (A) ++ ("bacdabacaacaadaa"));
constraint
  (("dbddadacacb") ++ (A) ++ ("bdcdcdbddcddacbbdddcabadbabdcdadadbbdaaabb"))
    =
    (("dbddadacacb") ++ (A) ++ ("bdcdcdbddcddacbbdddcabadbabdcdadadbbdaaabb"));
constraint
  (("cbccacababbbccdcdadbbcbadcadcabaabaccccaddac") ++ (A) ++ ("ccbcabcdc"))
    =
    (("cbccacababbbccdcdadbbcbadcadcabaabaccccaddac") ++ (A) ++ ("ccbcabcdc"));
constraint
  (("cdbbddcadbabdbabaccdcaccbcddcaaaadcbacdaaaa") ++ (A) ++ ("bdbadcdbab"))
    = (("cdbbddcadbabdbabaccdcaccbcddcaaaadcbacdaaaacaaabdbadcdbab") ++ (""));
constraint
  (("babaccbdddddadacaaaaaddbdcadabaaccdcbaccaaccccbdcaadadcab") ++ ("")) =
    (("babaccbdddddada") ++ (A) ++ ("aaddbdcadabaaccdcbaccaaccccbdcaadadcab"));
constraint
  (("aaccccadbddbcdddbabbacddbcbacadabcaadccbddcaacd") ++ (A) ++ ("dbbdab"))
    =
    (("aaccccadbddbcdddbabbacddbcbacadabcaadccbddcaacd") ++ (A) ++ ("dbbdab"));
constraint
  (("cdddcdaaacaadbda") ++ (A) ++ ("acbbcbdadbccdcadbdacccdaaddacbbccdccb"))
    =
    (("cdddcdaaacaadbda") ++ (A) ++ ("acbbcbdadbccdcadbdacccdaaddacbbccdccb"));
constraint
  (("aacadbddccddaaadbbabdacdcbaddacbdbacabccbdcaccc") ++ (A) ++ ("cadddc"))
    = (("aacadbddccddaaadbbabdacdcbaddacbdbacabccbdcaccccaaacadddc") ++ (""));
constraint
  (("ddcdddbbdcaddbadcbacacbacbdcadbaadacaaaadbbaada") ++ (A) ++ ("acbabc"))
    =
    (("ddcdddbbdcaddbadcbacacbacbdcadbaada") ++ (A) ++ ("adbbaada") ++ (A) ++ ("acbabc"));
constraint
  (("acdaa") ++ (A) ++ ("dbbdbcadcabdacabbcaccdbacccdccacbdbbaadccddbccbd"))
    =
    (("acdaa") ++ (A) ++ ("dbbdbcadcabdacabbcaccdbacccdccacbdbbaadccddbccbd"));
constraint
  (("aadbbaab") ++ (A) ++ ("caccaaabcaddabbcbdcdadccdcddccabccbacaacbbaaa"))
    =
    (("aadbbaab") ++ (A) ++ ("cac") ++ (A) ++ ("bcaddabbcbdcdadccdcddccabccbacaacbbaaa"));
constraint
  (("dddbacdcacdbdccbbdcccdabdbdcaabbabadcdaaccccdab") ++ (A) ++ ("acaabc"))
    = (("dddbacdcacdbdccbbdcccdabdbdcaabbabadcdaaccccdabcaaaacaabc") ++ (""));
constraint
  (("cadcccadbacbdcabbdcaadcbcaaaacbacccbbddbadabddccbdbaaabaa") ++ ("")) =
    (("cadcccadbacbdcabbdcaadcb") ++ (A) ++ ("acbacccbbddbadabddccbdbaaabaa"));
constraint
  (("dbbccbbdbdcbabbdacddacabbacaddbda") ++ (A) ++ ("acacccdcdbbcadbdcadd"))
    =
    (("dbbccbbdbdcbabbdacddacabbacaddbda") ++ (A) ++ ("acacccdcdbbcadbdcadd"));
constraint
  (("aaccccacddbdacdbc") ++ (A) ++ ("bbabaddadcccbbadabbaddcacbddcddcdbba"))
    =
    (("aaccccacddbdacdbc") ++ (A) ++ ("bbabaddadcccbbadabbaddcacbddcddcdbba"));
constraint
  (("cabbbddacbabbcabdaddaa") ++ (A) ++ ("acabbdaccbdbaccaaabcbbbcbaadbac"))
    =
    (("cabbbddacbabbcabdaddaa") ++ (A) ++ ("acabbdaccbdbaccaaabcbbbcbaadbac"));
constraint
  (("daaadcaaaabcbdaaccbcccbcacdbbdacaddcaadadacbbacddcbdbdcda") ++ ("")) =
    (("daaad") ++ (A) ++ ("abcbdaaccbcccbcacdbbdacaddcaadadacbbacddcbdbdcda"));
constraint
  (("aab") ++ (A) ++ ("bbabacccadcdbcdbccacaadaadbccdaccacadccbadaacdacba"))
    = (("aabcaaabbabacccadcdbcdbccacaadaadbccdaccacadccbadaacdacba") ++ (""));
constraint
  (("d") ++ (A) ++ ("dbdaaabababdbdabadacbbbbdacaacbcbbacbccdaaddbbdcbdab"))
    =
    (("d") ++ (A) ++ ("dbdaaabababdbdabadacbbbbdacaacbcbbacbccdaaddbbdcbdab"));
constraint
  (("babaadbdcccddcacaadcbacdacadbdcdbaaaadbbbdbbdbabcc") ++ (A) ++ ("bca"))
    =
    (("babaadbdcccddcacaadcbacdacadbdcdbaaaadbbbdbbdbabcc") ++ (A) ++ ("bca"));
constraint
  (("dddccdbcdbcdaaddaadbadddbcbcddcacbcdbacbdddaccdddb") ++ (A) ++ ("cbd"))
    = (("dddccdbcdbcdaaddaadbadddbcbcddcacbcdbacbdddaccdddbcaaacbd") ++ (""));
constraint
  (("dcdadacdbccbadbacacddcaaabaabcddbdcaaaddcdcbdbadcaccbbbad") ++ ("")) =
    (("dcdadacdbccbadbacacdd") ++ (A) ++ ("baabcddbdcaaaddcdcbdbadcaccbbbad"));
constraint
  (("ccdaabadbdaabcdcaabcdacbbacadaabdaadddddbcbbddbbcad") ++ (A) ++ ("ca"))
    = (("ccdaabadbdaabcdcaabcdacbbacadaabdaadddddbcbbddbbcadcaaaca") ++ (""));
constraint
  (("adcdbdadbbadbbcdaccbadbddcbddbbdbbacdbccaaadaacabbdcdbcad") ++ ("")) =
    (("adcdbdadbbadbbcdaccbadbddcbddbbdbbacdbc") ++ (A) ++ ("daacabbdcdbcad"));
constraint
  (("bccbacaaabbdbdaabdddddaacdbbdbdaaacadadbdbcaaccbdbbdcccad") ++ ("")) =
    (("bccba") ++ (A) ++ ("bbdbdaabdddddaacdbbdbdaaacadadbdbcaaccbdbbdcccad"));
constraint
  (("cbaddabadbdbcaaccabccccdbbdccdcccdcaabad") ++ (A) ++ ("bddabbbddacbb"))
    =
    (("cbaddabadbdbcaaccabccccdbbdccdcccdcaabad") ++ (A) ++ ("bddabbbddacbb"));
constraint
  (("caadbcacadbdadaabbbbbaaaccc") ++ (A) ++ ("ccddcbbdabddbccdcbccbcbaca"))
    =
    (("caadbcacadbdadaabbbbbaaaccc") ++ (A) ++ ("ccddcbbdabddbccdcbccbcbaca"));
constraint
  (("dcacadacabbdcdcbadcdc") ++ (A) ++ ("dbbadcbcaadbdababadbacdcccdaddba"))
    =
    (("dcacadacabbdcdcbadcdc") ++ (A) ++ ("dbbadcbcaadbdababadbacdcccdaddba"));
constraint
  (("bcbbcddddcdbcaaacbbcabadacddaacccbcdbacdddccaadcddcdaaccd") ++ ("")) =
    (("bcbbcddddcdb") ++ (A) ++ ("cbbcabadacddaacccbcdbacdddccaadcddcdaaccd"));
constraint
  (("dacbdbcbaab") ++ (A) ++ ("cccacbdbcacaacbbaccddadcdcdcbaabcdaccabdad"))
    =
    (("dacbdbcbaab") ++ (A) ++ ("cccacbdbcacaacbbaccddadcdcdcbaabcdaccabdad"));
constraint
  (("acbdbcbacacddaccadcaadacaaacbdaabcccdbcccdadbcaacacdaaccd") ++ ("")) =
    (("acbdbcbacacddaccadcaada") ++ (A) ++ ("cbdaabcccdbcccdadbcaacacdaaccd"));
constraint
  (("bcacdbaddaccdac") ++ (A) ++ ("abbcbdcabbadabbddbbddacddbcdbdcbbbdaad"))
    = (("bcacdbaddaccdaccaaaabbcbdcabbadabbddbbddacddbcdbdcbbbdaad") ++ (""));
constraint
  (("aaddbbdaddbcbadcabbbbaabdbccddbcbcabadaacacdc") ++ (A) ++ ("aacdabbc"))
    =
    (("aaddbbdaddbcbadcabbbbaabdbccddbcbcabadaacacdc") ++ (A) ++ ("aacdabbc"));
constraint
  (("bbccdbacbcaaaccdccaabaadbbcbdbdabbdbbbddbaadddabadbcdcddb") ++ ("")) =
    (("bbccdbacb") ++ (A) ++ ("ccdccaabaadbbcbdbdabbdbbbddbaadddabadbcdcddb"));
constraint
  (("ccabcccbdaaabdaacbaacdccdddcdc") ++ (A) ++ ("abadcbdaddacbdadcbbcaba"))
    = (("ccabcccbdaaabdaacbaacdccdddcdccaaaabadcbdaddacbdadcbbcaba") ++ (""));
constraint
  (("bdcadbaadcccabcacddcbaabdccccbcacdcaaaccddbcbadbccdabadac") ++ ("")) =
    (("bdcadbaadcccabcacddcbaabdccccbcacd") ++ (A) ++ ("ccddbcbadbccdabadac"));
constraint
  (("dadadcabcabdadddcdddcadbacdbaa") ++ (A) ++ ("babbccbcbcdabdcccdbdcab"))
    =
    (("dadadcabcabdadddcdddcadbacdbaa") ++ (A) ++ ("babbccbcbcdabdcccdbdcab"));
constraint
  (("ad") ++ (A) ++ ("ccdbbabdcbbdbbcddaaabacbcadbacbcdbcddcdacbbadcacdaa"))
    =
    (("ad") ++ (A) ++ ("ccdbbabdcbbdbbcddaaabacbcadbacbcdbcddcdacbbadcacdaa"));
constraint
  (("cdadddccccdabbdadc") ++ (A) ++ ("cbabbaabccbccacbcaadddacbbcddddbccc"))
    =
    (("cdadddccccdabbdadc") ++ (A) ++ ("cbabbaabccbccacbcaadddacbbcddddbccc"));
constraint
  (("ccba") ++ (A) ++ ("cacdcccbccbacbbacbabddcbbaddddbcdcaccdbabadcbbaab"))
    = (("ccbacaaacacdcccbccbacbbacbabddcbbaddddbcdcaccdbabadcbbaab") ++ (""));
constraint
  (("dcdcbdddaabcbdadbdaabbdaabcddcaca") ++ (A) ++ ("cbcbadaaacbbddccadcb"))
    =
    (("dcdcbdddaabcbdadbdaabbdaabcddcaca") ++ (A) ++ ("cbcbadaaacbbddccadcb"));
solve satisfy;
