var string: B;
var string: A;
constraint
  (("bbbabbcbdbbabbac") ++ (B) ++ ("d")) =
    (("bbbabbcbdbbabbac") ++ (B) ++ ("d"));
constraint
  (("daaaaccbadbdbddab") ++ (A)) =
    (("daaaaccbadbdbd") ++ (B) ++ ("ccbcccccdaddbbcbccbc"));
constraint
  (("accbdcacaab") ++ (B) ++ ("a") ++ (A) ++ ("dcb")) =
    (("accbdcacaab") ++ (B) ++ ("aacbabcadccbbcccccbbdadaababcbdcb"));
constraint
  (("ddaadcbcaabadb") ++ (B) ++ ("dbbacddadccadadababccacabc")) =
    (("ddaadcbcaabadbbddca") ++ (A) ++ ("acddbbacddadccadadababccacabc"));
constraint
  (("aaaaccddbcbdcbdcbadddcdadcbbdcccaccdaaadabccba") ++ (A) ++ ("ca")) =
    (("aaaaccddbcbdcbdcbadddcdadcbbdcccaccdaaadabccba") ++ (A) ++ ("ca"));
constraint
  (("aaaacbbddccbaacabccabcbaadaaadbcdabbbdaaddcbb") ++ (A) ++ ("aba")) =
    (("aaaacbbddccbaacabccabcbaadaaadbcdabbbdaaddcbbcbbababa") ++ (""));
constraint
  (("acaaacabcacaababcccbcabdbbddabc") ++ (A) ++ ("ddaccddcabdbdaaac")) =
    (("acaaacabcacaababcccbcabdbbddabccbbabddaccddcabdbdaaac") ++ (""));
constraint
  (("bdcbbdbaaccdadadddcaabbccdddcabbddbddcbcacbbabacdabaa") ++ ("")) =
    (("bdcbbdbaaccdadadddcaabbccdddcabbddbddcbca") ++ (A) ++ ("acdabaa"));
constraint
  (("cccdabbbdaabbbcaadadcaabadadbbababadcabdbdacbbcbbabab") ++ ("")) =
    (("cccdabbbdaabbbcaadadcaabadadbbababadcabdbdacbb") ++ (A) ++ ("ab"));
constraint
  (("acccbadcbbaabbdabdcbccdcbbabcbcabddaadccdcbbddacbcccc") ++ ("")) =
    (("acccbadcbbaabbdabdcbccd") ++ (A) ++ ("cbcabddaadccdcbbddacbcccc"));
constraint
  (("dccddcdccbdcadddbcdabddddabcababddaabcbdddcdcbbabccbd") ++ ("")) =
    (("dccddcdccbdcadddbcdabddddabcababddaabcbdddcd") ++ (A) ++ ("ccbd"));
constraint
  (("c") ++ (A) ++ ("bdbbaddcbacdddcdaaccccbadbdadccbcbccacdabadcaac")) =
    (("c") ++ (A) ++ ("bdbbaddcbacdddcdaaccccbadbdadccbcbccacdabadcaac"));
constraint
  (("caabbccbbdcdaababdcadba") ++ (A) ++ ("badbdcddcbdbbbadcaccdaacb")) =
    (("caabbccbbdcdaababdcadbacbbabbadbdcddcbdbbbadcaccdaacb") ++ (""));
constraint
  (("adadbaaaadccadcbadaddacaacaaaaabcc") ++ (A) ++ ("bccabaddcdbaad")) =
    (("adadbaaaadccadcbadaddacaacaaaaabcc") ++ (A) ++ ("bccabaddcdbaad"));
constraint
  (("dadbdbdbcbacdabcdcbbcc") ++ (A) ++ ("dcdaabbabbaadaacccddbbcbbb")) =
    (("dadbdbdbcbacdabcdcbbcccbbabdcdaabbabbaadaacccddbbcbbb") ++ (""));
constraint
  (("caccadcacaaadcabaaaabddbbdcbcbadbbdbccbbababbadbdbcdc") ++ ("")) =
    (("caccadcacaaadcabaaaabddbbdcbcbadbbdbc") ++ (A) ++ ("abbadbdbcdc"));
constraint
  (("dccadcbdbaddbdcadbcdaccddadcbabacccd") ++ (A) ++ ("cccadbbbbbbb")) =
    (("dccadcbdbaddbdcadbcdaccddadcbabacccd") ++ (A) ++ ("cccadbbbbbbb"));
constraint
  (("ccbccabddcbbdbdbcadccdbbcaadabbcbcbbbacacd") ++ (A) ++ ("abadbd")) =
    (("ccbccabddcbbdbdbcadccdbbcaadabbcbcbbbacacdcbbababadbd") ++ (""));
constraint
  (("bcdccbcdaadbdbdbaacbacdcbbccbadbcdabbaddcbad") ++ (A) ++ ("aaac")) =
    (("bcdccbcdaadbdbdbaacbacdcbbccbadbcdabbaddcbadcbbabaaac") ++ (""));
constraint
  (("babdadaccacbbadbdbddabdcbdbbccbacdcadacabcd") ++ (A) ++ ("bacca")) =
    (("babdadaccacbbadbdbddabdcbdbbccbacdcadacabcdcbbabbacca") ++ (""));
constraint
  (("ddbaaadabdaaadbabddcdacadcaaabadbaaadaadacbbabcabbddd") ++ ("")) =
    (("ddbaaadabdaaadbabddcdacadcaaabadbaaadaada") ++ (A) ++ ("cabbddd"));
constraint
  (("acaabad") ++ (A) ++ ("dcddcbbaacbdcbdccbacdcbcbabbabacdabbdbccb")) =
    (("acaabadcbbabdcddcbbaacbdcbdccbacdcbcbabbabacdabbdbccb") ++ (""));
constraint
  (("cccbcadacabbacbbaaccdcaacdbccdaccccaddbcbbabccdddcbcc") ++ ("")) =
    (("cccbcadacabbacbbaaccdcaacdbccdaccccaddb") ++ (A) ++ ("ccdddcbcc"));
constraint
  (("badbacbbabcddddbaadddbdbabaaabcdbacaacdccbbbcdcaadadc") ++ ("")) =
    (("badba") ++ (A) ++ ("cddddbaadddbdbabaaabcdbacaacdccbbbcdcaadadc"));
constraint
  (("cbaacbbabaacacdddbccbbcacabddadccbbbadacdaacbcbbcdaba") ++ ("")) =
    (("cbaa") ++ (A) ++ ("aacacdddbccbbcacabddadccbbbadacdaacbcbbcdaba"));
constraint
  (("bbbdccbaaabcaaabcbaacacdbdbbcdbacdaddcdbbbccda") ++ (A) ++ ("bc")) =
    (("bbbdccbaaabcaaabcbaacacdbdbbcdbacdaddcdbbbccdacbbabbc") ++ (""));
constraint
  (("cdbbaadccaaaddcaaaaadcccabdadcbbabbbcacdcdbaccaacbdbd") ++ ("")) =
    (("cdbbaadccaaaddcaaaaadcccabdad") ++ (A) ++ ("bbcacdcdbaccaacbdbd"));
constraint
  (("bcaadcbadaadbdaabb") ++ (A) ++ ("dcddcbdcaadddcacccbdbbaadbbdac")) =
    (("bcaadcbadaadbdaabbcbbabdcddcbdcaadddcacccbdbbaadbbdac") ++ (""));
constraint
  (("addbadacaa") ++ (A) ++ ("cbbdaaadbacccabbabccbbcabbbcababcdabaa")) =
    (("addbadacaacbbabcbbdaaadbacccabbabccbbcabbbcababcdabaa") ++ (""));
constraint
  (("abcbcadcaddacbdaaabca") ++ (A) ++ ("bbcbccdcdabccbcbaadbbccdbdb")) =
    (("abcbcadcaddacbdaaabcacbbabbbcbccdcdabccbcbaadbbccdbdb") ++ (""));
constraint
  (("acaddcccbdaabacbcbcadd") ++ (A) ++ ("dbbbddadbccababcdccccdcccc")) =
    (("acaddcccbdaabacbcbcadd") ++ (A) ++ ("dbbbddadbccababcdccccdcccc"));
constraint
  (("ccbaadbdadddbccaccbbdddccbcccbdabcabadb") ++ (A) ++ ("cacadddcb")) =
    (("ccbaadbdadddbccaccbbdddccbcccbdabcabadb") ++ (A) ++ ("cacadddcb"));
constraint
  (("abbbcdaadcbddcbcaccaaababccbbbabbbdbcb") ++ (A) ++ ("cabbabbabc")) =
    (("abbbcdaadcbddcbcaccaaababccbbbabbbdbcb") ++ (A) ++ ("cabbabbabc"));
constraint
  (("c") ++ (A) ++ ("cacbddbbdcacaddcdadbcbbdbbcaadbadbdacbcaadacadc")) =
    (("ccbbabcacbddbbdcacaddcdadbcbbdbbcaadbadbdacbcaadacadc") ++ (""));
constraint
  (("ccbdccadb") ++ (A) ++ ("aababdddbcddbcadbdaadcbdaaaaacaaadcdaad")) =
    (("ccbdccadb") ++ (A) ++ ("aababdddbcddbcadbdaadcbdaaaaacaaadcdaad"));
constraint
  (("accdddaaaccbbcababccbbaabbccdacbbabbdcccdcdcbdacdbbda") ++ ("")) =
    (("accdddaaaccbbcababccbbaabbccda") ++ (A) ++ ("bdcccdcdcbdacdbbda"));
constraint
  (("acabda") ++ (A) ++ ("cccccdcdbcaadbacbdcacbdcbadcadacbadbbacdaa")) =
    (("acabdacbbabcccccdcdbcaadbacbdcacbdcbadcadacbadbbacdaa") ++ (""));
constraint
  (("acbcccbaad") ++ (A) ++ ("abcbdbddaddbbbdccaabaaaaacdcbddbacdbcb")) =
    (("acbcccbaadcbbababcbdbddaddbbbdccaabaaaaacdcbddbacdbcb") ++ (""));
constraint
  (("accaadabdaccbabaaadcacaadaccbdddd") ++ (A) ++ ("cbabbdbcbcadcca")) =
    (("accaadabdaccbabaaadcacaadaccbddddcbbabcbabbdbcbcadcca") ++ (""));
constraint
  (("cacccbbaadcddccddabcdddbbdabcbabdabacccbbbcccccabbdac") ++ ("")) =
    (("cacccbbaadcddccd") ++ (A) ++ ("dbb") ++ (B) ++ ("ccabbdac"));
constraint
  (("dddabcacbaccaadbcadcaabaaadbadbaaddaa") ++ (A) ++ ("aaccbbcdba")) =
    (("dddabcacbaccaadbcadcaabaaadbadbaaddaadabcddaaccbbcdba") ++ (""));
constraint
  (("caddddbada") ++ (A) ++ ("ddcaadbcabcccacbbbabcbaaabcddabdbdbab")) =
    (("caddddbadadabcddddcaadbcabcccacbbbabcbaaabcddabdbdbab") ++ (""));
constraint
  (("cbdcdcabccdabcdbbdacaacddbbddbb") ++ (A) ++ ("cadabdaacabbaacd")) =
    (("cbdcdcabccdabcdbbdacaacddbbddbbdabcddcadabdaacabbaacd") ++ (""));
constraint
  (("cdddbbddddabddcbababdaacddc") ++ (A) ++ ("caaadbccaaccaaaadbaa")) =
    (("cdddbbddddabddcbababdaacddc") ++ (A) ++ ("caaadbccaaccaaaadbaa"));
constraint
  (("ddaaabdbaabdcccdcabaaadcddbacbcabccacdcdabcddbbdbdcad") ++ ("")) =
    (("ddaaabdbaabdcccdcabaaadcddbacbcabccacdc") ++ (A) ++ ("bbdbdcad"));
constraint
  (("dbdabcababaaabbcdcddcccbbcdbdabbaaaaaccbcc") ++ (A) ++ ("baacc")) =
    (("dbdabcababaaabbcdcddcccbbcdbdabbaaaaaccbcc") ++ (A) ++ ("baacc"));
constraint
  (("dccaabcdaccdcddbbadddabdcadcdabcddbcdbdbabadddddcbdbc") ++ ("")) =
    (("dccaabcdaccdcddbbadddabdcadc") ++ (A) ++ ("bcdbdbabadddddcbdbc"));
constraint (("adccbb") ++ (A)) = (("adccbb") ++ (A));
constraint
  (("acbdbbaabbcbbdbccbbcdc") ++ (B) ++ ("bcddacdbcbbbbbacdcbcacdca")) =
    (("acbdbba") ++ (A) ++ ("abcddacdbcbbbbbacdcbcacdca"));
constraint
  (("ddadddcdbdcaadcabadbcbbbcaabdabdadaacbabbbddacc") ++ (B)) =
    (("ddadddcdbdcaadcabadbcbbbcaabdabdadaacbabbbddacc") ++ (B));
constraint
  (("cbaddbbaadadbcbaababbcabcaddcdddbcdccbbaacccbbcdddddc") ++ ("")) =
    (("cbaddbbaada") ++ (B) ++ ("babbcabcaddcdddbcdccbbaacccbbcdddddc"));
constraint
  (("aaacaadbbcbaaddbcbaaccdbcadadaabbccbadbbcbdbaadaacdab") ++ ("")) =
    (("aaacaadbbcbaad") ++ (B) ++ ("ccdbcadadaabbccbadbbcbdbaadaacdab"));
constraint
  (("acadcbbdbcddbdbdcbbcbbaadbbcacdc") ++ (B) ++ ("bbcdbdbabbaccaa")) =
    (("acadcbbdbcddbdbdcbbcbbaadbbcacdc") ++ (B) ++ ("bbcdbdbabbaccaa"));
constraint
  (("cdbdbdaaccdacccbadcaddddabbaabcbdcdccaddbcbaabdadbdaa") ++ ("")) =
    (("cdbdbdaaccdacccbadcaddddabbaabcbdcdccad") ++ (B) ++ ("bdadbdaa"));
constraint
  (("cdbdddcacaacccbbbadcdcbacdbdadabbbddbcbaaadcbcdabbbba") ++ ("")) =
    (("cdbdddcacaacccbbbadcdcbacdbdadabbbd") ++ (B) ++ ("adcbcdabbbba"));
constraint
  (("dbccddbdbadbab") ++ (A) ++ ("dcba")) =
    (("dbccddbdbadbabbbbcbaacdcddddcdcbdbaaaacccbadbccbcdcba") ++ (""));
constraint
  (("cb") ++ (B) ++ ("dcaacdaaca") ++ (B) ++ ("aaab") ++ (B) ++ ("ddbbcac") ++ (B) ++ ("bbca") ++ (B) ++ ("cccaddacdadccdabca") ++ (B) ++ ("ba"))
    =
    (("c") ++ (B) ++ (B) ++ ("dcaacd") ++ (A) ++ (B) ++ ("bddbbcac") ++ (B) ++ (B) ++ ("bcabcccaddacdadccda") ++ (B) ++ ("cab") ++ (B) ++ ("a"));
constraint
  (("dac") ++ (B) ++ ("c") ++ (B) ++ ("cdbdacaddabbdddccd") ++ (B) ++ ("accdada") ++ (B) ++ ("cadca") ++ (B) ++ ("cacddbcdb") ++ (B) ++ ("cdda"))
    =
    (("dac") ++ (B) ++ ("cbcd") ++ (B) ++ ("dacadda") ++ (B) ++ (B) ++ ("dddccdbaccdadabcadcabcacdd") ++ (B) ++ ("cdb") ++ (B) ++ ("cdda"));
constraint
  (("cadcaad") ++ (B) ++ ("adddaba") ++ (B) ++ ("aacca") ++ (B) ++ ("d") ++ (B) ++ ("ddacaa") ++ (B) ++ (B) ++ ("cba") ++ (B) ++ ("ccdddcacac") ++ (B) ++ ("cdcdaa"))
    =
    (("cadcaad") ++ (B) ++ ("adddababaaccabd") ++ (B) ++ ("ddacaa") ++ (B) ++ ("bcbabccdddcacacbcdcdaa"));
constraint
  (("cda") ++ (B) ++ ("ddadcaad") ++ (B) ++ ("cccd") ++ (B) ++ ("ca") ++ (B) ++ ("cdaddbaddcccbbcdbdc") ++ (B) ++ ("caaacdcdbc") ++ (B) ++ ("d"))
    =
    (("cdabddadcaad") ++ (B) ++ ("cccdbcabcdaddbaddccc") ++ (B) ++ ("bcdbdc") ++ (B) ++ ("caaacdcd") ++ (B) ++ ("c") ++ (B) ++ ("d"));
constraint
  (("dcccd") ++ (B) ++ ("bdd") ++ (B) ++ (B) ++ ("baccadddbcdacccdcaddaddda") ++ (B) ++ ("dbaab") ++ (B) ++ ("cdad") ++ (B) ++ ("acac") ++ (B))
    =
    (("dcccd") ++ (B) ++ ("bdd") ++ (B) ++ (B) ++ ("baccaddd") ++ (B) ++ ("cdacccdcaddadddabd") ++ (B) ++ ("aabbcdadbacacb"));
constraint
  (("dbca") ++ (B) ++ ("ddbdaa") ++ (B) ++ ("dccaabdddcdaad") ++ (B) ++ ("daddbc") ++ (B) ++ ("cacc") ++ (B) ++ ("dbccbaccdac") ++ (B) ++ ("a") ++ (B))
    =
    (("dbcabdd") ++ (B) ++ ("daabdccaa") ++ (B) ++ ("dddcdaad") ++ (B) ++ ("daddbc") ++ (B) ++ ("caccbd") ++ (B) ++ ("ccbaccdacba") ++ (B));
constraint
  ((B) ++ ("db") ++ (B) ++ ("c") ++ (B) ++ ("caaddd") ++ (B) ++ ("ddadcddcbcacaccbaaacdddac") ++ (B) ++ ("dadaabaadadaab"))
    =
    (("bd") ++ (B) ++ (B) ++ ("c") ++ (B) ++ ("caadddbddadcddcbcacacc") ++ (B) ++ ("aaacdddacbdadaa") ++ (B) ++ ("aadadaab"));
constraint
  ((B) ++ ("cabdd") ++ (B) ++ ("cb") ++ (B) ++ ("c") ++ (B) ++ ("cdcaaaacadbbdccddcbbddcdcdaadbdcaabdbcaab"))
    =
    (("bcabddbc") ++ (B) ++ (B) ++ ("c") ++ (B) ++ ("cdcaaaacad") ++ (B) ++ ("bdccddcbbddcdcdaad") ++ (B) ++ ("dcaa") ++ (B) ++ ("dbcaab"));
constraint
  (("aaacdadaaaabdadcaabdabddba") ++ (B) ++ ("d") ++ (B) ++ ("d") ++ (B) ++ ("a") ++ (B) ++ ("dddccd") ++ (B) ++ ("ddddaaddcbd") ++ (B) ++ ("b"))
    =
    (("aaacdadaaaa") ++ (B) ++ ("dadcaabda") ++ (B) ++ ("dd") ++ (B) ++ ("abdbdba") ++ (B) ++ ("dddccd") ++ (B) ++ ("ddddaaddcbdbb"));
constraint
  (("a") ++ (B) ++ ("dadabcbcbcadabdcd") ++ (B) ++ ("ccc") ++ (B) ++ (B) ++ ("bcbcabbdaadadccbbdcc") ++ (B) ++ ("dadcaad"))
    =
    (("abdadabc") ++ (B) ++ ("c") ++ (B) ++ ("cada") ++ (B) ++ ("dcdbcccbbbcbca") ++ (B) ++ (B) ++ ("daadadccb") ++ (B) ++ ("dcc") ++ (B) ++ ("dadcaad"));
constraint
  (("abd") ++ (B) ++ ("cdcccd") ++ (B) ++ ("dc") ++ (B) ++ ("dbcdaacdaa") ++ (B) ++ ("adadddcd") ++ (B) ++ ("ccbadcacdcadbccacbc"))
    =
    (("abd") ++ (B) ++ ("cdcccd") ++ (B) ++ ("dc") ++ (B) ++ ("d") ++ (B) ++ ("cdaacdaa") ++ (B) ++ ("adadddcdbccbadcacdcad") ++ (B) ++ ("ccacbc"));
constraint
  (("daadcdadcdd") ++ (B) ++ ("dc") ++ (B) ++ ("caadbd") ++ (B) ++ ("dddbcdbdddbccdddccacccc") ++ (B) ++ (B) ++ ("ddcccd"))
    =
    (("daadcdadcdd") ++ (B) ++ ("dcbcaadbdbddd") ++ (B) ++ ("cdbdddbccdddccaccccbbddcccd"));
constraint
  ((B) ++ ("cddccacdbbdccaad") ++ (B) ++ ("ccdabd") ++ (B) ++ ("ca") ++ (B) ++ ("cada") ++ (B) ++ ("aacdabaaad") ++ (B) ++ ("bdcbcdada"))
    =
    (("bcddccacd") ++ (B) ++ ("bdccaadbccdabdbca") ++ (B) ++ ("cada") ++ (B) ++ ("aacdabaaadb") ++ (B) ++ ("dc") ++ (B) ++ ("cdada"));
constraint
  (("addbacbdacdcbcd") ++ (B) ++ ("a") ++ (B) ++ ("acd") ++ (B) ++ ("bbd") ++ (B) ++ ("cacacacc") ++ (B) ++ ("cb") ++ (B) ++ ("a") ++ (B) ++ ("cccaab") ++ (B) ++ ("ccdccb"))
    =
    (("add") ++ (B) ++ ("ac") ++ (B) ++ ("dacdc") ++ (B) ++ ("cdbabacdbbbd") ++ (B) ++ ("cacacaccbc") ++ (B) ++ ("babcccaabbccdccb"));
constraint
  (("ccddadac") ++ (B) ++ ("dacd") ++ (B) ++ ("c") ++ (B) ++ ("dcdaacddaadbdaadb") ++ (B) ++ ("aadaddbac") ++ (B) ++ (B) ++ ("d") ++ (B) ++ ("ccbdc") ++ (B))
    =
    (("ccddadacbdacdbcbdcdaacddaad") ++ (B) ++ ("daadb") ++ (B) ++ ("aadadd") ++ (B) ++ ("acb") ++ (B) ++ ("d") ++ (B) ++ ("cc") ++ (B) ++ ("dcb"));
constraint
  (("bcddcadaad") ++ (B) ++ ("cd") ++ (B) ++ (B) ++ ("ddbcdbcc") ++ (B) ++ ("add") ++ (B) ++ (B) ++ ("ccadcc") ++ (B) ++ ("a") ++ (B) ++ (B) ++ ("acaaaacaddddaa"))
    =
    (("bcddcadaad") ++ (B) ++ ("cdb") ++ (B) ++ ("dd") ++ (B) ++ ("cdbcc") ++ (B) ++ ("addb") ++ (B) ++ ("ccadccba") ++ (B) ++ ("bacaaaacaddddaa"));
constraint
  (("ac") ++ (B) ++ ("dd") ++ (B) ++ ("adcadd") ++ (B) ++ ("cadaaaacdccd") ++ (B) ++ ("daaada") ++ (B) ++ ("cbcccda") ++ (B) ++ ("dacbdbadd") ++ (B) ++ ("cd"))
    =
    (("acbddbadcaddbcadaaaacdccdbdaaada") ++ (B) ++ ("c") ++ (B) ++ ("cccdabdac") ++ (B) ++ ("d") ++ (B) ++ ("addbcd"));
constraint
  (("d") ++ (B) ++ ("dbbbcbada") ++ (B) ++ ("cdddddadabbdacabddaaddbddabdacbdccdaaddcd"))
    =
    (("dbdb") ++ (B) ++ ("bcbada") ++ (B) ++ ("cdddddada") ++ (B) ++ (B) ++ ("dacabddaadd") ++ (B) ++ ("ddabdac") ++ (B) ++ ("dccdaaddcd"));
constraint
  (("acdba") ++ (B) ++ (B) ++ ("bbbdccaccc") ++ (B) ++ ("ddababcdcaad") ++ (B) ++ ("a") ++ (B) ++ (B) ++ ("cadcdadd") ++ (B) ++ ("bccaaabbcb"))
    =
    (("acdba") ++ (B) ++ (B) ++ ("b") ++ (B) ++ (B) ++ ("dccaccc") ++ (B) ++ ("dda") ++ (B) ++ ("a") ++ (B) ++ ("cdcaad") ++ (B) ++ ("ab") ++ (B) ++ ("cadcdaddb") ++ (B) ++ ("ccaaabbcb"));
constraint
  (("caaddaa") ++ (B) ++ ("ddccabbcabbaacddbadabaacbdacbba") ++ (B) ++ ("cb") ++ (B) ++ ("bcac") ++ (B) ++ ("ccadc"))
    =
    (("caaddaa") ++ (B) ++ ("ddccab") ++ (B) ++ ("cabbaacddbada") ++ (B) ++ ("aacbdac") ++ (B) ++ (B) ++ ("a") ++ (B) ++ ("c") ++ (B) ++ ("bbcac") ++ (B) ++ ("ccadc"));
constraint
  (("cccdcabdccacaaaccadb") ++ (B) ++ ("aacda") ++ (B) ++ ("bcdcddabbdcdadddaba") ++ (B) ++ ("c") ++ (B) ++ ("abca"))
    =
    (("cccdcabdccacaaaccadb") ++ (B) ++ ("aacda") ++ (B) ++ (B) ++ ("cdcdda") ++ (B) ++ ("bdcdaddda") ++ (B) ++ ("a") ++ (B) ++ ("c") ++ (B) ++ ("a") ++ (B) ++ ("ca"));
constraint
  (("ddcacddddadbaaad") ++ (B) ++ ("dccbcda") ++ (B) ++ ("db") ++ (B) ++ (B) ++ ("d") ++ (B) ++ ("bcdddcdcb") ++ (B) ++ ("cddb") ++ (B) ++ ("cbcbdca"))
    =
    (("ddcacddddadbaaad") ++ (B) ++ ("dccbcdabd") ++ (B) ++ (B) ++ ("bdb") ++ (B) ++ ("cdddcdc") ++ (B) ++ (B) ++ ("cdd") ++ (B) ++ (B) ++ ("c") ++ (B) ++ ("c") ++ (B) ++ ("dca"));
constraint
  ((B) ++ ("baddbacd") ++ (B) ++ (B) ++ ("ccaccda") ++ (B) ++ ("adcd") ++ (B) ++ ("cdc") ++ (B) ++ ("bc") ++ (B) ++ ("dbcdcbaccad") ++ (B) ++ ("accacccca") ++ (B))
    =
    (("b") ++ (B) ++ ("add") ++ (B) ++ ("acdbbccaccdabadcdbcdcb") ++ (B) ++ ("cbd") ++ (B) ++ ("cdc") ++ (B) ++ ("accadbaccacccca") ++ (B));
constraint
  ((B) ++ ("dc") ++ (B) ++ ("ddbbdacccca") ++ (B) ++ ("ac") ++ (B) ++ ("dacacdddcdccb") ++ (B) ++ ("aaacca") ++ (B) ++ ("a") ++ (B) ++ ("cacdddd") ++ (B) ++ ("cca"))
    =
    (("bdc") ++ (B) ++ ("ddb") ++ (B) ++ ("daccccabacbdacacdddcdccbbaaacca") ++ (B) ++ ("abcacdddd") ++ (B) ++ ("cca"));
constraint
  (("cadcccdb") ++ (B) ++ ("dddccadbccccaadccaccccbccd") ++ (B) ++ ("baa") ++ (B) ++ ("ddcaccabccbac"))
    =
    (("cadcccd") ++ (B) ++ ("bdddccadbccccaadccacccc") ++ (B) ++ ("ccd") ++ (B) ++ ("baa") ++ (B) ++ ("ddcacca") ++ (B) ++ ("ccbac"));
constraint
  (("ddbccaa") ++ (B) ++ ("ad") ++ (B) ++ ("cadaccbacdadaacd") ++ (B) ++ ("b") ++ (B) ++ ("aa") ++ (B) ++ ("aacdad") ++ (B) ++ (B) ++ ("c") ++ (B) ++ ("d") ++ (B) ++ ("daddccad"))
    =
    (("dd") ++ (B) ++ ("ccaabad") ++ (B) ++ ("cadacc") ++ (B) ++ ("acdadaacdbbbaabaacdad") ++ (B) ++ (B) ++ ("c") ++ (B) ++ ("d") ++ (B) ++ ("daddccad"));
constraint
  (("cdcbada") ++ (B) ++ ("aa") ++ (B) ++ ("daac") ++ (B) ++ ("adcaa") ++ (B) ++ ("cac") ++ (B) ++ ("cacac") ++ (B) ++ ("aabcbdadcb") ++ (B) ++ (B) ++ ("cdadcadd") ++ (B))
    =
    (("cdcbada") ++ (B) ++ ("aabdaacbadcaa") ++ (B) ++ ("cac") ++ (B) ++ ("cacac") ++ (B) ++ ("aabcbdadcbb") ++ (B) ++ ("cdadcaddb"));
constraint
  (("dddccba") ++ (B) ++ ("bcaccc") ++ (B) ++ ("cddcca") ++ (B) ++ ("ccadcdacdcdc") ++ (B) ++ ("cdcd") ++ (B) ++ ("dcdaaacaddbdc"))
    =
    (("dddccba") ++ (B) ++ (B) ++ ("caccc") ++ (B) ++ ("cddcca") ++ (B) ++ ("ccadcdacdcdc") ++ (B) ++ ("cdcdbdcdaaacadd") ++ (B) ++ ("dc"));
constraint
  (("dbaadada") ++ (B) ++ ("dddccc") ++ (B) ++ ("dbccdaccdcaccdcacb") ++ (B) ++ ("cdadd") ++ (B) ++ ("cdcaa") ++ (B) ++ ("ad") ++ (B) ++ ("dcb"))
    =
    (("d") ++ (B) ++ ("aadadabdddcccbdbccdaccdcaccdcac") ++ (B) ++ (B) ++ ("cdadd") ++ (B) ++ ("cdcaa") ++ (B) ++ ("ad") ++ (B) ++ ("dc") ++ (B));
constraint
  (("aaadddabd") ++ (B) ++ ("cbcccddb") ++ (B) ++ ("cbaaa") ++ (B) ++ ("c") ++ (B) ++ ("acabcdc") ++ (B) ++ ("da") ++ (B) ++ ("daca") ++ (B) ++ ("cdddcc") ++ (B) ++ ("aba"))
    =
    (("aaadddabd") ++ (B) ++ ("cbcccddb") ++ (B) ++ ("cbaaa") ++ (B) ++ ("cbaca") ++ (B) ++ ("cdcbda") ++ (B) ++ ("daca") ++ (B) ++ ("cdddcc") ++ (B) ++ ("a") ++ (B) ++ ("a"));
constraint
  (("daacddbaddaabda") ++ (B) ++ ("a") ++ (B) ++ ("abdbdd") ++ (B) ++ ("ccccdcbacdabcad") ++ (B) ++ ("dcbacbc") ++ (B) ++ ("ddad"))
    =
    (("daacdd") ++ (B) ++ ("addaa") ++ (B) ++ ("daba") ++ (B) ++ ("a") ++ (B) ++ ("dbddbccccdc") ++ (B) ++ ("acdabcadbdcbacbc") ++ (B) ++ ("ddad"));
constraint
  (("d") ++ (B) ++ ("dababacc") ++ (B) ++ ("cbcdbddaac") ++ (B) ++ (B) ++ ("bdadbcad") ++ (B) ++ ("aaadbbcacaaaa") ++ (B) ++ ("dad") ++ (B) ++ ("d") ++ (B) ++ ("d"))
    =
    (("dbda") ++ (B) ++ ("a") ++ (B) ++ ("acc") ++ (B) ++ ("cbcd") ++ (B) ++ ("ddaacbb") ++ (B) ++ ("dad") ++ (B) ++ ("cadbaaad") ++ (B) ++ (B) ++ ("cacaaaa") ++ (B) ++ ("dadbdbd"));
constraint
  (("bab") ++ (B) ++ ("bbdbdba") ++ (B) ++ ("cb") ++ (B) ++ ("bddadccddad") ++ (B) ++ ("ccbdaaddaaa") ++ (B) ++ ("adddccdcddaccc"))
    =
    ((B) ++ ("a") ++ (B) ++ ("b") ++ (B) ++ (B) ++ ("d") ++ (B) ++ ("dba") ++ (B) ++ ("cb") ++ (B) ++ (B) ++ ("ddadccddadbccbdaaddaaa") ++ (B) ++ ("adddccdcddaccc"));
constraint
  ((B) ++ (B) ++ ("cddacdabaacddabadcdaddad") ++ (B) ++ ("c") ++ (B) ++ ("bdb") ++ (B) ++ ("aadadbdabab") ++ (B) ++ ("cabdd") ++ (B) ++ ("cd"))
    =
    ((B) ++ ("bcddacda") ++ (B) ++ ("aacdda") ++ (B) ++ ("adcdaddadbcbbdb") ++ (B) ++ ("aadad") ++ (B) ++ ("da") ++ (B) ++ ("abbca") ++ (B) ++ ("dd") ++ (B) ++ ("cd"));
constraint
  (("cdaddad") ++ (B) ++ ("dacacbaaadbc") ++ (B) ++ ("dabcaddad") ++ (B) ++ ("acdaa") ++ (B) ++ ("bccacdccddccccda"))
    =
    (("cdaddad") ++ (B) ++ ("dacac") ++ (B) ++ ("aaadbc") ++ (B) ++ ("da") ++ (B) ++ ("caddadbacdaabbccacdccddccccda"));
constraint
  (("ddaddaa") ++ (B) ++ (B) ++ ("acac") ++ (B) ++ ("addac") ++ (B) ++ ("a") ++ (B) ++ ("cddaadacdcbbaddcadcdc") ++ (B) ++ ("da") ++ (B) ++ ("dcddcd"))
    =
    (("ddaddaa") ++ (B) ++ ("bacac") ++ (B) ++ ("addac") ++ (B) ++ ("abcddaadacdc") ++ (B) ++ (B) ++ ("addcadcdc") ++ (B) ++ ("da") ++ (B) ++ ("dcddcd"));
constraint
  ((B) ++ ("ccaad") ++ (B) ++ ("a") ++ (B) ++ ("adccacad") ++ (B) ++ ("dbcbc") ++ (B) ++ ("caddacaadcbddccdadcccda") ++ (B) ++ ("cbd") ++ (B) ++ ("c"))
    =
    ((B) ++ ("ccaadbabadccacadbd") ++ (B) ++ ("c") ++ (B) ++ ("c") ++ (B) ++ ("caddacaadcbddccdadcccdabc") ++ (B) ++ ("d") ++ (B) ++ ("c"));
constraint
  (("d") ++ (B) ++ ("addcdd") ++ (B) ++ ("aca") ++ (B) ++ ("dcb") ++ (B) ++ ("acadbabadccdccdcddadaccaadddccdac") ++ (B) ++ ("cc"))
    =
    (("d") ++ (B) ++ ("addcddbacabdc") ++ (B) ++ (B) ++ ("acad") ++ (B) ++ ("abadccdccdcddadaccaadddccdacbcc"));
constraint
  (("cccdbadcdccbacaba") ++ (B) ++ ("acbbc") ++ (B) ++ ("a") ++ (B) ++ (B) ++ (B) ++ ("ca") ++ (B) ++ ("cdd") ++ (B) ++ (B) ++ ("cabaccccbdba") ++ (B) ++ (B) ++ ("c") ++ (B) ++ ("a"))
    =
    (("cccd") ++ (B) ++ ("adcdcc") ++ (B) ++ ("acababac") ++ (B) ++ ("bc") ++ (B) ++ ("a") ++ (B) ++ (B) ++ ("bca") ++ (B) ++ ("cddb") ++ (B) ++ ("cabacccc") ++ (B) ++ ("dbabbc") ++ (B) ++ ("a"));
constraint
  (("cdcdbdbabacacdddbbcadacaaaddaddabbddaaa") ++ (B) ++ ("bdccdabb") ++ (B) ++ ("dadc"))
    =
    (("cdcdbdba") ++ (B) ++ ("acacdddb") ++ (B) ++ ("cadacaaaddaddab") ++ (B) ++ ("ddaaab") ++ (B) ++ ("dccdab") ++ (B) ++ ("bdadc"));
constraint
  (("caba") ++ (B) ++ ("ddaaddcbadd") ++ (B) ++ ("d") ++ (B) ++ ("aadaddbbb") ++ (B) ++ ("dadaa") ++ (B) ++ ("acdadcacabddcaabbb"))
    =
    (("cababddaaddcbaddbdbaadadd") ++ (B) ++ (B) ++ (B) ++ ("bdadaa") ++ (B) ++ ("acdadcacabddcaab") ++ (B) ++ ("b"));
constraint
  (("ddac") ++ (B) ++ ("daa") ++ (B) ++ ("ccbbc") ++ (B) ++ ("d") ++ (B) ++ ("cca") ++ (B) ++ ("dbb") ++ (B) ++ ("bca") ++ (B) ++ ("dc") ++ (B) ++ ("cadcdcccc") ++ (B) ++ ("cdddbddcba") ++ (B))
    =
    (("ddacbdaabcc") ++ (B) ++ (B) ++ ("cbd") ++ (B) ++ ("cca") ++ (B) ++ ("d") ++ (B) ++ (B) ++ ("b") ++ (B) ++ ("cabdc") ++ (B) ++ ("cadcdcccc") ++ (B) ++ ("cdddbddc") ++ (B) ++ ("a") ++ (B));
constraint
  ((B) ++ ("baad") ++ (B) ++ ("cdab") ++ (B) ++ ("aaca") ++ (B) ++ ("dbbdbdbacadcdddbdcc") ++ (B) ++ ("c") ++ (B) ++ ("cabc") ++ (B) ++ ("abbdbadcda"))
    =
    ((B) ++ (B) ++ ("aadbcda") ++ (B) ++ ("baaca") ++ (B) ++ ("dbbd") ++ (B) ++ ("d") ++ (B) ++ ("acadcddd") ++ (B) ++ ("dcc") ++ (B) ++ ("c") ++ (B) ++ ("cabcbabbdbadcda"));
constraint
  (("acacbaaab") ++ (B) ++ ("adbb") ++ (B) ++ ("dddcddcccccdcaacab") ++ (B) ++ ("ccc") ++ (B) ++ ("aaadcbdadaadadb"))
    =
    (("acacbaaa") ++ (B) ++ ("badbbbdddcddcccccdcaaca") ++ (B) ++ ("bcccbaaadcbdadaadad") ++ (B));
constraint
  ((B) ++ (B) ++ ("d") ++ (B) ++ ("badccd") ++ (B) ++ ("cdb") ++ (B) ++ ("dddacddabbc") ++ (B) ++ ("aaddcccddcbccadaaddcbddccb"))
    =
    (("bbdb") ++ (B) ++ ("adccdbcdbbdddacddab") ++ (B) ++ ("cbaaddcccddcbccadaaddcbddccb"));
constraint
  (("aaccadca") ++ (B) ++ ("dadbdaddc") ++ (B) ++ ("acbcabdddbbdbc") ++ (B) ++ (B) ++ ("cdacacddcdacdc") ++ (B) ++ ("aba"))
    =
    (("aaccadcabdadbdaddc") ++ (B) ++ ("acbcabddd") ++ (B) ++ (B) ++ ("dbcb") ++ (B) ++ ("cdacacddcdacdcbaba"));
constraint
  (("aaccdccaa") ++ (B) ++ ("ccdcdd") ++ (B) ++ ("dccaccdbccc") ++ (B) ++ ("ccddddcabccacbdbacacbccb"))
    =
    (("aaccdccaabccdcddbdccaccd") ++ (B) ++ ("ccc") ++ (B) ++ ("ccddddcabccac") ++ (B) ++ ("d") ++ (B) ++ ("acacbcc") ++ (B));
constraint
  (("dbcaddadbccad") ++ (B) ++ ("abc") ++ (B) ++ ("cdcaad") ++ (B) ++ (B) ++ (B) ++ ("ca") ++ (B) ++ ("ba") ++ (B) ++ ("cdbcadb") ++ (B) ++ ("bac") ++ (B) ++ (B) ++ (B) ++ ("addcdd"))
    =
    (("dbcaddad") ++ (B) ++ ("ccad") ++ (B) ++ ("abc") ++ (B) ++ ("cdcaadb") ++ (B) ++ (B) ++ ("ca") ++ (B) ++ ("babcdbcadbbbac") ++ (B) ++ (B) ++ (B) ++ ("addcdd"));
constraint
  (("dddbadacad") ++ (B) ++ ("dcaccaadbcadc") ++ (B) ++ (B) ++ ("bac") ++ (B) ++ (B) ++ ("dacdcdccaaadbddaccbbcc"))
    =
    (("dddbadacadbdcaccaadbcadc") ++ (B) ++ ("bbac") ++ (B) ++ (B) ++ ("dacdcdccaaadbddaccbbcc"));
constraint
  (("cbbb") ++ (B) ++ ("acaccad") ++ (B) ++ ("aadddbcbccdddccca") ++ (B) ++ ("bdcc") ++ (B) ++ ("add") ++ (B) ++ ("caaddaca") ++ (B) ++ ("acab"))
    =
    (("cb") ++ (B) ++ ("bbacaccadbaadddbcbccdddcccabbdccbaddbcaaddacabaca") ++ (B));
constraint
  (("dcbcbc") ++ (B) ++ ("cdd") ++ (B) ++ ("ddaadddddbaddacdd") ++ (B) ++ ("dbdaaddcaaddccdcd") ++ (B) ++ ("bc") ++ (B) ++ ("ddc"))
    =
    (("dc") ++ (B) ++ ("c") ++ (B) ++ ("c") ++ (B) ++ ("cddbddaadddddbaddacddbdbdaaddcaaddccdcd") ++ (B) ++ (B) ++ ("c") ++ (B) ++ ("ddc"));
constraint
  (("a") ++ (B) ++ ("ac") ++ (B) ++ ("adadadccaabbddcadada") ++ (B) ++ ("bc") ++ (B) ++ ("acdcdadddcaada") ++ (B) ++ ("ccbccbcad"))
    =
    (("a") ++ (B) ++ ("acbadadadccaa") ++ (B) ++ ("bddcadada") ++ (B) ++ ("bc") ++ (B) ++ ("acdcdadddcaada") ++ (B) ++ ("ccbccbcad"));
constraint
  (("dbb") ++ (B) ++ (B) ++ ("bddc") ++ (B) ++ ("bd") ++ (B) ++ ("dccaabb") ++ (B) ++ ("caacaaacbccbdaadc") ++ (B) ++ ("dcadcabddabbca"))
    =
    (("dbbb") ++ (B) ++ ("bddc") ++ (B) ++ (B) ++ ("d") ++ (B) ++ ("dccaab") ++ (B) ++ (B) ++ ("caacaaacbccbdaadc") ++ (B) ++ ("dcadca") ++ (B) ++ ("dda") ++ (B) ++ ("bca"));
constraint
  (("caaa") ++ (B) ++ (B) ++ ("bd") ++ (B) ++ ("cbadddddc") ++ (B) ++ ("cdbbddbddacdbc") ++ (B) ++ ("a") ++ (B) ++ ("dbccdadcdbdaa") ++ (B) ++ ("ad") ++ (B))
    =
    (("caaabb") ++ (B) ++ ("d") ++ (B) ++ ("c") ++ (B) ++ ("adddddcbcd") ++ (B) ++ ("bddbddacd") ++ (B) ++ ("cba") ++ (B) ++ ("d") ++ (B) ++ ("ccdadcdbdaabad") ++ (B));
constraint
  (("aaacccccdccbd") ++ (B) ++ ("c") ++ (B) ++ ("ccacdcbdd") ++ (B) ++ ("cabacdaadcabccc") ++ (B) ++ ("c") ++ (B) ++ ("ccb") ++ (B) ++ ("adcca"))
    =
    (("aaacccccdccbdbcbccacdc") ++ (B) ++ ("dd") ++ (B) ++ ("ca") ++ (B) ++ ("acdaadcabccc") ++ (B) ++ ("c") ++ (B) ++ ("cc") ++ (B) ++ (B) ++ ("adcca"));
constraint
  (("ccddabbd") ++ (B) ++ ("a") ++ (B) ++ ("ddaadcabdcacadadbad") ++ (B) ++ ("adcaabcaa") ++ (B) ++ ("c") ++ (B) ++ ("cdabccbd") ++ (B) ++ ("b"))
    =
    (("ccddabbdba") ++ (B) ++ ("ddaadca") ++ (B) ++ ("dcacadadbadbadcaabcaa") ++ (B) ++ ("c") ++ (B) ++ ("cda") ++ (B) ++ ("ccbd") ++ (B) ++ ("b"));
constraint
  (("bdaaacdaaaababbaacdcacddcb") ++ (B) ++ ("ca") ++ (B) ++ ("da") ++ (B) ++ ("dd") ++ (B) ++ ("bddaaaa") ++ (B) ++ ("dbadadddc"))
    =
    ((B) ++ ("daaacdaaaa") ++ (B) ++ ("abbaacdcacddcbbcabdabdd") ++ (B) ++ (B) ++ ("ddaaaa") ++ (B) ++ ("dbadadddc"));
constraint
  (("ddcddb") ++ (B) ++ ("accdaccaddddda") ++ (B) ++ ("cacccddbcadbc") ++ (B) ++ (B) ++ (B) ++ ("cad") ++ (B) ++ ("cbacccd") ++ (B) ++ ("cba"))
    =
    (("ddcdd") ++ (B) ++ ("baccdaccadddddabcacccddbcadbcbbbcadbcbacccdbc") ++ (B) ++ ("a"));
constraint
  (("ccaadcd") ++ (B) ++ (B) ++ ("aacacaddabbcb") ++ (B) ++ ("bbcca") ++ (B) ++ ("cdcdccbadaddb") ++ (B) ++ ("caabccdddd"))
    =
    (("ccaadcdbbaacacaddabbc") ++ (B) ++ (B) ++ (B) ++ (B) ++ ("cca") ++ (B) ++ ("cdcdccbadaddbbcaa") ++ (B) ++ ("ccdddd"));
constraint
  (("db") ++ (B) ++ (B) ++ ("dacbcd") ++ (B) ++ (B) ++ ("bcada") ++ (B) ++ ("dcacdbbaddbabd") ++ (B) ++ ("bcdcadccadbcdaaa") ++ (B) ++ ("acc"))
    =
    (("d") ++ (B) ++ (B) ++ (B) ++ ("dac") ++ (B) ++ ("cd") ++ (B) ++ ("bbcada") ++ (B) ++ ("dcacdbbaddba") ++ (B) ++ ("d") ++ (B) ++ (B) ++ ("cdcadccad") ++ (B) ++ ("cdaaabacc"));
constraint
  (("bbdcdb") ++ (B) ++ ("dccabbdba") ++ (B) ++ (B) ++ ("bbdadda") ++ (B) ++ ("bbccabdcddc") ++ (B) ++ ("adccca") ++ (B) ++ ("c") ++ (B) ++ ("dcacdd"))
    =
    ((B) ++ (B) ++ ("dcdbbdcca") ++ (B) ++ (B) ++ ("dbabbb") ++ (B) ++ ("dadda") ++ (B) ++ ("bbccabdcddcbadcccabcbdcacdd"));
constraint
  (("cdcaaacaddcddacda") ++ (B) ++ ("cacabdadcaaadbdbccdbaadca") ++ (B) ++ ("da") ++ (B) ++ ("cacda") ++ (B))
    =
    (("cdcaaacaddcddacda") ++ (B) ++ ("caca") ++ (B) ++ ("dadcaaad") ++ (B) ++ ("d") ++ (B) ++ ("ccdbaadca") ++ (B) ++ ("dabcacda") ++ (B));
constraint
  (("ccddbcc") ++ (B) ++ (B) ++ ("cccaadaa") ++ (B) ++ ("bccaacdcccaaacaadbddccaacacac") ++ (B) ++ ("cbada"))
    =
    (("ccddbccbbcccaadaa") ++ (B) ++ (B) ++ ("ccaacdcccaaacaad") ++ (B) ++ ("ddccaacacac") ++ (B) ++ ("c") ++ (B) ++ ("ada"));
constraint
  (("cc") ++ (B) ++ ("aaadad") ++ (B) ++ ("ddbbccd") ++ (B) ++ ("abcdbdbdacbacdbdccdcdbbaacccbdbcdba"))
    =
    (("cc") ++ (B) ++ ("aaadad") ++ (B) ++ ("dd") ++ (B) ++ ("bccdbabcdbdbdac") ++ (B) ++ ("acdbdccdcdb") ++ (B) ++ ("aacccbd") ++ (B) ++ ("cdba"));
constraint
  (("abddaa") ++ (B) ++ ("dbdd") ++ (B) ++ (B) ++ ("cccaa") ++ (B) ++ ("cbd") ++ (B) ++ ("cababcdcaa") ++ (B) ++ ("abac") ++ (B) ++ ("cd") ++ (B) ++ ("ddddcc") ++ (B) ++ ("dddc"))
    =
    (("abddaabd") ++ (B) ++ ("ddb") ++ (B) ++ ("cccaa") ++ (B) ++ ("cbdbca") ++ (B) ++ ("a") ++ (B) ++ ("cdcaaba") ++ (B) ++ ("ac") ++ (B) ++ ("cd") ++ (B) ++ ("ddddccbdddc"));
constraint
  ((B) ++ (B) ++ ("aaacbd") ++ (B) ++ ("adbc") ++ (B) ++ ("caaddbacdadaaabcaabcadcc") ++ (B) ++ ("bdcdcccda") ++ (B) ++ ("dac") ++ (B))
    =
    (("bbaaac") ++ (B) ++ ("d") ++ (B) ++ ("ad") ++ (B) ++ ("cbcaaddbacdadaaa") ++ (B) ++ ("caa") ++ (B) ++ ("cadccbbdcdcccda") ++ (B) ++ ("dacb"));
constraint
  (("a") ++ (B) ++ ("dddcbacddcdaaadad") ++ (B) ++ ("ac") ++ (B) ++ ("d") ++ (B) ++ ("dbdcadcddaa") ++ (B) ++ ("ccbcdcc") ++ (B) ++ ("acacccc") ++ (B))
    =
    (("abdddcbacddcdaaadad") ++ (B) ++ ("ac") ++ (B) ++ ("d") ++ (B) ++ ("d") ++ (B) ++ ("dcadcddaa") ++ (B) ++ ("ccbcdccbacacccc") ++ (B));
constraint
  (("ca") ++ (B) ++ ("ddabbacbbbdddb") ++ (B) ++ ("c") ++ (B) ++ (B) ++ ("cdcaabaabcaadaacdbd") ++ (B) ++ ("accbcdbabbca"))
    =
    (("cabdda") ++ (B) ++ (B) ++ ("acbbbdddb") ++ (B) ++ ("c") ++ (B) ++ ("bcdcaabaa") ++ (B) ++ ("caadaacdbd") ++ (B) ++ ("accbcd") ++ (B) ++ ("a") ++ (B) ++ (B) ++ ("ca"));
constraint
  (("bdbcad") ++ (B) ++ ("aaddcc") ++ (B) ++ ("cccdddaddbac") ++ (B) ++ ("cacdbad") ++ (B) ++ ("caadca") ++ (B) ++ ("aabbabddcd") ++ (B))
    =
    ((B) ++ ("d") ++ (B) ++ ("cad") ++ (B) ++ ("aaddccbcccdddaddbacbcacd") ++ (B) ++ ("adbcaadcabaab") ++ (B) ++ ("a") ++ (B) ++ ("ddcd") ++ (B));
constraint
  ((B) ++ ("acaddac") ++ (B) ++ ("daadcc") ++ (B) ++ ("dabcdbcbcdaadbcdcadbddaa") ++ (B) ++ ("dadddac") ++ (B) ++ ("addd"))
    =
    (("bacaddac") ++ (B) ++ ("daadccbdabcd") ++ (B) ++ ("cbcdaad") ++ (B) ++ ("cdcad") ++ (B) ++ ("ddaabdadddac") ++ (B) ++ ("addd"));
constraint
  (("cdcadcdbabcca") ++ (B) ++ ("bdcaabdac") ++ (B) ++ ("aadd") ++ (B) ++ ("dad") ++ (B) ++ ("caabbdc") ++ (B) ++ ("cdcbaacccdaa"))
    =
    (("cdcadcd") ++ (B) ++ ("a") ++ (B) ++ ("ccab") ++ (B) ++ ("dcaa") ++ (B) ++ ("dacbaaddbdadbcaa") ++ (B) ++ ("bdc") ++ (B) ++ ("cdc") ++ (B) ++ ("aacccdaa"));
constraint
  (("cabaaaaddcbdbcabcc") ++ (B) ++ ("cbddadddcadb") ++ (B) ++ ("aabcca") ++ (B) ++ ("cca") ++ (B) ++ ("b") ++ (B) ++ ("d") ++ (B) ++ (B) ++ (B) ++ ("bcad"))
    =
    (("cabaaaaddcbdbca") ++ (B) ++ ("cc") ++ (B) ++ ("cbddadddcadb") ++ (B) ++ ("aabccabccab") ++ (B) ++ (B) ++ ("dbb") ++ (B) ++ ("bcad"));
constraint
  (("a") ++ (B) ++ ("daaadcbddcaabcddacaada") ++ (B) ++ ("daacbd") ++ (B) ++ ("c") ++ (B) ++ ("d") ++ (B) ++ ("dbcbdddcbcaa") ++ (B) ++ ("dbba"))
    =
    (("abdaaadcbddcaa") ++ (B) ++ ("cddacaadabdaacbd") ++ (B) ++ ("cbdbdbc") ++ (B) ++ ("dddc") ++ (B) ++ ("caa") ++ (B) ++ ("db") ++ (B) ++ ("a"));
constraint
  (("ac") ++ (B) ++ ("ddcdddcd") ++ (B) ++ (B) ++ ("cddcaabdcbddc") ++ (B) ++ ("ddddddacddcdcdcaabdbbaa") ++ (B) ++ ("ca"))
    =
    (("acbddcdddcd") ++ (B) ++ (B) ++ ("cddcaa") ++ (B) ++ ("dcbddc") ++ (B) ++ ("ddddddacddcdcdcaabd") ++ (B) ++ (B) ++ ("aabca"));
constraint
  ((B) ++ (B) ++ ("aacccbd") ++ (B) ++ ("d") ++ (B) ++ ("d") ++ (B) ++ ("cdaddcdaacb") ++ (B) ++ ("baddbadadb") ++ (B) ++ ("a") ++ (B) ++ ("adaaad") ++ (B) ++ ("bbadaad"))
    =
    (("bbaacccbd") ++ (B) ++ ("dbdbcdaddcdaacb") ++ (B) ++ ("baddbadadb") ++ (B) ++ ("abadaaad") ++ (B) ++ (B) ++ (B) ++ ("adaad"));
constraint
  (("acc") ++ (B) ++ ("d") ++ (B) ++ ("cadb") ++ (B) ++ (B) ++ ("dadd") ++ (B) ++ ("aa") ++ (B) ++ (B) ++ ("acdbd") ++ (B) ++ ("cbbcdaaadadca") ++ (B) ++ ("ddabaadd") ++ (B) ++ ("bac"))
    =
    (("acc") ++ (B) ++ ("dbcad") ++ (B) ++ ("b") ++ (B) ++ ("daddbaabbacd") ++ (B) ++ ("dbcbbcdaaadadca") ++ (B) ++ ("ddabaadd") ++ (B) ++ (B) ++ ("ac"));
constraint
  ((B) ++ (B) ++ ("dcda") ++ (B) ++ (B) ++ ("b") ++ (B) ++ ("dadaabdaacc") ++ (B) ++ ("abd") ++ (B) ++ ("dcabbbcdcdccbbaa") ++ (B) ++ ("ca") ++ (B) ++ ("da") ++ (B) ++ ("cd") ++ (B) ++ ("c"))
    =
    (("bbdcdab") ++ (B) ++ ("b") ++ (B) ++ ("dadaabdaaccbabd") ++ (B) ++ ("dca") ++ (B) ++ (B) ++ ("bcdcdcc") ++ (B) ++ (B) ++ ("aa") ++ (B) ++ ("cabdabcd") ++ (B) ++ ("c"));
constraint
  (("adccccddba") ++ (B) ++ ("d") ++ (B) ++ ("aacbd") ++ (B) ++ ("bdacbbbaddcdcdcdd") ++ (B) ++ ("aa") ++ (B) ++ ("add") ++ (B) ++ ("dbdccccdc"))
    =
    (("adccccddbabd") ++ (B) ++ ("aac") ++ (B) ++ ("d") ++ (B) ++ (B) ++ ("dacb") ++ (B) ++ (B) ++ ("addcdcdcdd") ++ (B) ++ ("aabaddbd") ++ (B) ++ ("dccccdc"));
constraint
  (("ddaddcddcdda") ++ (B) ++ ("dbcccbacdb") ++ (B) ++ ("bcdc") ++ (B) ++ ("addddcdda") ++ (B) ++ ("bcba") ++ (B) ++ ("dbacdcdcb"))
    =
    (("ddaddcddcddabd") ++ (B) ++ ("cccbacdb") ++ (B) ++ (B) ++ ("cdcbaddddcdda") ++ (B) ++ ("bcbabdbacdcdc") ++ (B));
constraint
  (("adabbd") ++ (B) ++ ("cc") ++ (B) ++ ("aadbccc") ++ (B) ++ ("caccdccbccaaac") ++ (B) ++ ("ab") ++ (B) ++ ("aaaddbdd") ++ (B) ++ ("aad") ++ (B) ++ ("bcac"))
    =
    (("adab") ++ (B) ++ ("d") ++ (B) ++ ("cc") ++ (B) ++ ("aad") ++ (B) ++ ("cccbcaccdccbccaaacba") ++ (B) ++ ("baaadd") ++ (B) ++ ("dd") ++ (B) ++ ("aad") ++ (B) ++ (B) ++ ("cac"));
constraint
  (("aacd") ++ (B) ++ ("dabab") ++ (B) ++ ("b") ++ (B) ++ (B) ++ ("cdaaaabcaca") ++ (B) ++ ("bcdbbd") ++ (B) ++ (B) ++ ("d") ++ (B) ++ ("cbac") ++ (B) ++ ("acbdaa") ++ (B) ++ ("a") ++ (B) ++ ("ccb"))
    =
    (("aacd") ++ (B) ++ ("da") ++ (B) ++ ("a") ++ (B) ++ (B) ++ (B) ++ (B) ++ (B) ++ ("cdaaaabcaca") ++ (B) ++ ("bcdbbdb") ++ (B) ++ ("d") ++ (B) ++ ("c") ++ (B) ++ ("acbac") ++ (B) ++ ("daababcc") ++ (B));
constraint
  (("ddccbadd") ++ (B) ++ ("aad") ++ (B) ++ ("cda") ++ (B) ++ ("a") ++ (B) ++ ("dc") ++ (B) ++ ("aaa") ++ (B) ++ (B) ++ ("adaddcacc") ++ (B) ++ (B) ++ ("cbda") ++ (B) ++ ("ccbdaacdac"))
    =
    (("ddcc") ++ (B) ++ ("add") ++ (B) ++ ("aadbcdababdcbaaa") ++ (B) ++ (B) ++ ("adaddcaccbbc") ++ (B) ++ ("da") ++ (B) ++ ("ccbdaacdac"));
constraint
  (("cad") ++ (B) ++ ("bdda") ++ (B) ++ ("abda") ++ (B) ++ ("dca") ++ (B) ++ ("c") ++ (B) ++ ("cacdbdd") ++ (B) ++ ("cccda") ++ (B) ++ ("c") ++ (B) ++ ("ddda") ++ (B) ++ (B) ++ ("baad") ++ (B) ++ ("ac") ++ (B) ++ ("abc"))
    =
    (("cadb") ++ (B) ++ ("dda") ++ (B) ++ ("abda") ++ (B) ++ ("dca") ++ (B) ++ ("c") ++ (B) ++ ("cacd") ++ (B) ++ ("dd") ++ (B) ++ ("cccdabcbddda") ++ (B) ++ ("bbaadbacbabc"));
constraint
  (("dbaacbdad") ++ (B) ++ ("bbabddddddbdcbdbd") ++ (B) ++ (B) ++ ("bdacadccaabcbddabbacacaa"))
    =
    (("dbaac") ++ (B) ++ ("dad") ++ (B) ++ (B) ++ ("ba") ++ (B) ++ ("ddddddbdcbd") ++ (B) ++ ("db") ++ (B) ++ (B) ++ ("dacadccaa") ++ (B) ++ ("c") ++ (B) ++ ("ddab") ++ (B) ++ ("acacaa"));
constraint
  ((B) ++ ("db") ++ (B) ++ ("d") ++ (B) ++ ("a") ++ (B) ++ ("cb") ++ (B) ++ ("cadd") ++ (B) ++ ("accdadccdacddadccddaccaadbdcadcca") ++ (B) ++ ("adb"))
    =
    ((B) ++ ("d") ++ (B) ++ ("bdbabc") ++ (B) ++ (B) ++ ("caddbaccdadccdacddadccddaccaadbdcadccabad") ++ (B));
constraint
  (("cdaccccaccac") ++ (B) ++ ("aac") ++ (B) ++ ("adabcaddcdddcbcdccbbadacdba") ++ (B) ++ ("c") ++ (B) ++ ("dad") ++ (B) ++ ("d") ++ (B))
    =
    (("cdaccccaccac") ++ (B) ++ ("aac") ++ (B) ++ ("ada") ++ (B) ++ ("caddcdddc") ++ (B) ++ ("cdcc") ++ (B) ++ ("badacd") ++ (B) ++ ("a") ++ (B) ++ ("c") ++ (B) ++ ("dad") ++ (B) ++ ("db"));
constraint
  (("accabca") ++ (B) ++ ("dacddcdaaadcdccccaacaad") ++ (B) ++ ("aad") ++ (B) ++ (B) ++ ("d") ++ (B) ++ ("aaadaddacdacac"))
    =
    (("accabca") ++ (B) ++ ("dacddcdaaadcdccccaacaad") ++ (B) ++ ("aad") ++ (B) ++ (B) ++ ("d") ++ (B) ++ ("aaadaddacdacac"));
constraint
  (("acc") ++ (B) ++ ("addbddcd") ++ (B) ++ ("dbada") ++ (B) ++ (B) ++ ("ddcac") ++ (B) ++ ("ccddcdddcaccb") ++ (B) ++ ("caaa") ++ (B) ++ ("bdcbdaa") ++ (B))
    =
    (("acc") ++ (B) ++ ("add") ++ (B) ++ ("ddcd") ++ (B) ++ ("d") ++ (B) ++ ("adabbddcacbccddcdddcaccbbcaaabbdcbdaab"));
constraint
  (("abac") ++ (B) ++ ("adacddda") ++ (B) ++ ("ddb") ++ (B) ++ ("aacda") ++ (B) ++ ("a") ++ (B) ++ ("a") ++ (B) ++ ("caa") ++ (B) ++ (B) ++ ("ababcddaddaacaddd") ++ (B) ++ ("c") ++ (B))
    =
    (("abacbadacddda") ++ (B) ++ ("dd") ++ (B) ++ (B) ++ ("aacdaba") ++ (B) ++ ("a") ++ (B) ++ ("caa") ++ (B) ++ (B) ++ ("a") ++ (B) ++ ("abcddaddaacadddbcb"));
constraint
  (("cd") ++ (B) ++ ("dbbdac") ++ (B) ++ ("cbddabcaddcdcdcacbbdcbabaabbbccd") ++ (B) ++ ("ab") ++ (B) ++ ("accad") ++ (B) ++ ("a"))
    =
    (("cdbdb") ++ (B) ++ ("dacbc") ++ (B) ++ ("ddabcaddcdcdcacb") ++ (B) ++ ("dc") ++ (B) ++ ("abaa") ++ (B) ++ (B) ++ ("bccd") ++ (B) ++ ("a") ++ (B) ++ ("baccadba"));
constraint
  (("cca") ++ (B) ++ ("d") ++ (B) ++ ("ccdcb") ++ (B) ++ ("ddadd") ++ (B) ++ ("cdddd") ++ (B) ++ ("bdbcdbbcdcdda") ++ (B) ++ ("a") ++ (B) ++ ("ddcc") ++ (B) ++ ("dcdaad") ++ (B) ++ ("a"))
    =
    (("ccabdbccdcb") ++ (B) ++ ("ddadd") ++ (B) ++ ("cddddbbd") ++ (B) ++ ("cdbbcdcdda") ++ (B) ++ ("abddcc") ++ (B) ++ ("dcdaadba"));
constraint
  ((B) ++ (B) ++ ("a") ++ (B) ++ ("adbacaadb") ++ (B) ++ ("dcadcdbddcad") ++ (B) ++ ("acbaac") ++ (B) ++ ("c") ++ (B) ++ ("dbdddacdcca") ++ (B) ++ ("acb") ++ (B) ++ ("b"))
    =
    (("b") ++ (B) ++ ("a") ++ (B) ++ ("adbacaadb") ++ (B) ++ ("dcadcdbddcad") ++ (B) ++ ("ac") ++ (B) ++ ("aacbc") ++ (B) ++ ("d") ++ (B) ++ ("dddacdcca") ++ (B) ++ ("ac") ++ (B) ++ (B) ++ ("b"));
constraint
  (("c") ++ (B) ++ ("acaddcacaacabddbdaacdcacdbbbaacada") ++ (B) ++ ("d") ++ (B) ++ ("cdccddb") ++ (B) ++ ("dbcbdd"))
    =
    (("cbacaddcacaaca") ++ (B) ++ ("ddbdaacdcacd") ++ (B) ++ ("b") ++ (B) ++ ("aacada") ++ (B) ++ ("d") ++ (B) ++ ("cdccdd") ++ (B) ++ (B) ++ ("d") ++ (B) ++ ("cbdd"));
constraint
  ((B) ++ ("a") ++ (B) ++ ("cdaccdacabcddc") ++ (B) ++ ("dddcdcaaddac") ++ (B) ++ ("accdaadbcddbddadadcbdd"))
    =
    (("babcdaccdacabcddc") ++ (B) ++ ("dddcdcaaddacbaccdaadbcddbddadadc") ++ (B) ++ ("dd"));
constraint
  (("cddadcacbaadcbddddaa") ++ (B) ++ ("dabbccad") ++ (B) ++ ("adaab") ++ (B) ++ ("acbca") ++ (B) ++ ("aacaadddbad"))
    =
    (("cddadcacbaadc") ++ (B) ++ ("ddddaabdab") ++ (B) ++ ("ccadbadaabbac") ++ (B) ++ ("ca") ++ (B) ++ ("aacaadddbad"));
constraint
  (("ccccdcaca") ++ (B) ++ ("cdd") ++ (B) ++ ("ddcabdadaadaa") ++ (B) ++ ("a") ++ (B) ++ ("cdacdbacdcda") ++ (B) ++ (B) ++ (B) ++ ("dbc") ++ (B) ++ ("adbc"))
    =
    (("ccccdcacabcdd") ++ (B) ++ ("ddca") ++ (B) ++ ("dadaadaa") ++ (B) ++ ("a") ++ (B) ++ ("cdacd") ++ (B) ++ ("acdcdab") ++ (B) ++ ("bdbc") ++ (B) ++ ("adbc"));
constraint
  (("cc") ++ (B) ++ ("ccaadcaca") ++ (B) ++ ("cbcdcacbdb") ++ (B) ++ ("cdaccadaca") ++ (B) ++ (B) ++ ("adcdcadd") ++ (B) ++ ("a") ++ (B) ++ ("dbabdd"))
    =
    (("ccbccaadcaca") ++ (B) ++ ("c") ++ (B) ++ ("cdcac") ++ (B) ++ ("d") ++ (B) ++ (B) ++ ("cdaccadacab") ++ (B) ++ ("adcdcadd") ++ (B) ++ ("abd") ++ (B) ++ ("a") ++ (B) ++ ("dd"));
constraint
  (("cda") ++ (B) ++ ("b") ++ (B) ++ ("c") ++ (B) ++ ("cccaddc") ++ (B) ++ ("bacdcacadddbaada") ++ (B) ++ ("acc") ++ (B) ++ ("ccccdccadadaddca"))
    =
    (("cda") ++ (B) ++ (B) ++ (B) ++ ("c") ++ (B) ++ ("cccaddc") ++ (B) ++ (B) ++ ("acdcacadddbaadabaccbccccdccadadaddca"));
constraint
  (("adc") ++ (B) ++ ("aabaaccdaddacadadba") ++ (B) ++ ("baaaacdbc") ++ (B) ++ ("adbaccacd") ++ (B) ++ ("bad") ++ (B) ++ ("cdbdb"))
    =
    (("adc") ++ (B) ++ ("aabaaccdaddacadadba") ++ (B) ++ (B) ++ ("aaaacd") ++ (B) ++ ("cbad") ++ (B) ++ ("accacdb") ++ (B) ++ ("ad") ++ (B) ++ ("cdbd") ++ (B));
constraint
  (("dbbabbdcb") ++ (B) ++ ("adcabbaddba") ++ (B) ++ ("cacbad") ++ (B) ++ ("acbdda") ++ (B) ++ ("c") ++ (B) ++ ("cdada") ++ (B) ++ ("dbd") ++ (B) ++ ("daa") ++ (B) ++ ("d"))
    =
    (("db") ++ (B) ++ ("abbdc") ++ (B) ++ (B) ++ ("adca") ++ (B) ++ ("badd") ++ (B) ++ ("a") ++ (B) ++ ("cac") ++ (B) ++ ("adbac") ++ (B) ++ ("dda") ++ (B) ++ ("cbcdada") ++ (B) ++ ("dbdbdaa") ++ (B) ++ ("d"));
constraint
  (("c") ++ (B) ++ ("adaab") ++ (B) ++ ("dda") ++ (B) ++ ("adddcdcadc") ++ (B) ++ ("ccaac") ++ (B) ++ ("dadad") ++ (B) ++ ("ccca") ++ (B) ++ ("ddacaadac") ++ (B) ++ ("bbc"))
    =
    (("c") ++ (B) ++ ("adaa") ++ (B) ++ (B) ++ ("dda") ++ (B) ++ ("adddcdcadcbccaac") ++ (B) ++ ("dadadbccca") ++ (B) ++ ("ddacaadacbbbc"));
constraint
  (("adc") ++ (B) ++ ("bdca") ++ (B) ++ ("add") ++ (B) ++ ("acccac") ++ (B) ++ (B) ++ (B) ++ (B) ++ ("dd") ++ (B) ++ ("ccd") ++ (B) ++ ("bcbddab") ++ (B) ++ ("cdadaaaddadcad") ++ (B))
    =
    (("adcbbdcabaddbacccacbbb") ++ (B) ++ ("dd") ++ (B) ++ ("ccdbbc") ++ (B) ++ ("ddabbcdadaaaddadcad") ++ (B));
constraint
  (("bcbc") ++ (B) ++ ("bddbdaadadaddbcaadaabdcaacbb") ++ (B) ++ ("dcccdc") ++ (B) ++ ("daacba") ++ (B) ++ ("bdaca"))
    =
    (("bc") ++ (B) ++ ("cb") ++ (B) ++ ("dd") ++ (B) ++ ("daadadadd") ++ (B) ++ ("caadaa") ++ (B) ++ ("dcaac") ++ (B) ++ (B) ++ ("bdcccdc") ++ (B) ++ ("daac") ++ (B) ++ ("abbdaca"));
constraint
  (("ddadcdccadcdcbadd") ++ (B) ++ ("cdcdacb") ++ (B) ++ ("dcaaacaaacabadad") ++ (B) ++ ("adcccac") ++ (B) ++ ("c") ++ (B))
    =
    (("ddadcdccadcdc") ++ (B) ++ ("addbcdcdacb") ++ (B) ++ ("dcaaacaaaca") ++ (B) ++ ("adad") ++ (B) ++ ("adcccacbc") ++ (B));
constraint
  (("dd") ++ (B) ++ ("dd") ++ (B) ++ (B) ++ ("bdaa") ++ (B) ++ ("addddbcdbdccbadaaadccbddaacccac") ++ (B) ++ ("bcbadddca"))
    =
    (("dd") ++ (B) ++ ("ddb") ++ (B) ++ (B) ++ ("daabadddd") ++ (B) ++ ("cdbdccbadaaadcc") ++ (B) ++ ("ddaacccac") ++ (B) ++ ("bc") ++ (B) ++ ("adddca"));
constraint
  (("badc") ++ (B) ++ ("abcda") ++ (B) ++ (B) ++ ("abcdaccaab") ++ (B) ++ ("dcbacbbccc") ++ (B) ++ ("dcdc") ++ (B) ++ ("dacdcdbaa") ++ (B) ++ ("cacd"))
    =
    ((B) ++ ("adc") ++ (B) ++ ("a") ++ (B) ++ ("cdab") ++ (B) ++ ("abcdaccaa") ++ (B) ++ (B) ++ ("dcbac") ++ (B) ++ (B) ++ ("ccc") ++ (B) ++ ("dcdc") ++ (B) ++ ("dacdcd") ++ (B) ++ ("aa") ++ (B) ++ ("cacd"));
constraint
  (("daadcbbdbdbad") ++ (B) ++ ("aa") ++ (B) ++ ("bbadbaaacdddac") ++ (B) ++ ("cbcdadd") ++ (B) ++ ("dcabaa") ++ (B) ++ ("cbdcdd"))
    =
    (("daadcb") ++ (B) ++ ("d") ++ (B) ++ ("d") ++ (B) ++ ("ad") ++ (B) ++ ("aa") ++ (B) ++ ("b") ++ (B) ++ ("ad") ++ (B) ++ ("aaacdddac") ++ (B) ++ ("c") ++ (B) ++ ("cdaddbdca") ++ (B) ++ ("aabcbdcdd"));
constraint
  (("d") ++ (B) ++ ("cadcd") ++ (B) ++ ("ddaabcbd") ++ (B) ++ ("bddacddddad") ++ (B) ++ ("adbdccccdaccddbc") ++ (B) ++ ("adac") ++ (B) ++ ("db"))
    =
    (("d") ++ (B) ++ ("cadcd") ++ (B) ++ ("ddaa") ++ (B) ++ ("c") ++ (B) ++ ("dbbddacddddad") ++ (B) ++ ("ad") ++ (B) ++ ("dccccdaccddbcbadac") ++ (B) ++ ("d") ++ (B));
constraint
  (("caa") ++ (B) ++ ("dddaa") ++ (B) ++ ("cadcbdadaccabaacdc") ++ (B) ++ ("a") ++ (B) ++ (B) ++ ("adb") ++ (B) ++ ("dbcdcaccbaa") ++ (B) ++ ("dcad") ++ (B))
    =
    (("caabdddaabcadc") ++ (B) ++ ("dadaccabaacdcba") ++ (B) ++ ("bad") ++ (B) ++ (B) ++ ("dbcdcaccbaabdcadb"));
constraint
  ((B) ++ (B) ++ ("cacda") ++ (B) ++ ("bccdaa") ++ (B) ++ ("cbdabdaa") ++ (B) ++ ("baccdada") ++ (B) ++ ("bdccadd") ++ (B) ++ ("bcad") ++ (B) ++ ("bcdcdd") ++ (B))
    =
    ((B) ++ ("bcacda") ++ (B) ++ (B) ++ ("ccdaabcbda") ++ (B) ++ ("daa") ++ (B) ++ (B) ++ ("accdadabbdccaddb") ++ (B) ++ ("cad") ++ (B) ++ (B) ++ ("cdcddb"));
constraint
  (("cdbddaacbaabadbcb") ++ (B) ++ ("ddd") ++ (B) ++ ("bcbdcdcccaccdcacd") ++ (B) ++ ("a") ++ (B) ++ ("ccdaadaccdb"))
    =
    (("cd") ++ (B) ++ ("ddaac") ++ (B) ++ ("aa") ++ (B) ++ ("adbcb") ++ (B) ++ ("ddd") ++ (B) ++ ("bc") ++ (B) ++ ("dcdcccaccdcacd") ++ (B) ++ ("a") ++ (B) ++ ("ccdaadaccdb"));
constraint
  (("ba") ++ (B) ++ ("bdacdabddd") ++ (B) ++ (B) ++ ("ccadd") ++ (B) ++ ("acdc") ++ (B) ++ ("dadda") ++ (B) ++ ("dcaaccbcdaada") ++ (B) ++ ("cddddaa"))
    =
    (("ba") ++ (B) ++ ("bdacda") ++ (B) ++ ("ddd") ++ (B) ++ (B) ++ ("ccaddbacdcbdadda") ++ (B) ++ ("dcaaccbcdaada") ++ (B) ++ ("cddddaa"));
constraint
  (("bbdaadddcaca") ++ (B) ++ ("dc") ++ (B) ++ ("dcad") ++ (B) ++ ("a") ++ (B) ++ (B) ++ ("daadddaaccbdabdda") ++ (B) ++ ("adbab") ++ (B) ++ ("bddca"))
    =
    ((B) ++ ("bdaadddcaca") ++ (B) ++ ("dc") ++ (B) ++ ("dcad") ++ (B) ++ ("a") ++ (B) ++ (B) ++ ("daadddaacc") ++ (B) ++ ("da") ++ (B) ++ ("ddabad") ++ (B) ++ ("a") ++ (B) ++ ("b") ++ (B) ++ ("ddca"));
constraint
  (("cdbc") ++ (B) ++ ("add") ++ (B) ++ ("ddadccccaab") ++ (B) ++ ("bbdadddcccaa") ++ (B) ++ (B) ++ ("daddcddcaccccaaacc"))
    =
    (("cdbc") ++ (B) ++ ("addbddadccccaab") ++ (B) ++ ("bbdadddcccaab") ++ (B) ++ ("daddcddcaccccaaacc"));
constraint
  (("d") ++ (B) ++ ("adcaaaddca") ++ (B) ++ (B) ++ ("abc") ++ (B) ++ ("cb") ++ (B) ++ ("cccdaaabacaabcddcacdc") ++ (B) ++ ("dccdaad") ++ (B) ++ ("bd"))
    =
    (("d") ++ (B) ++ ("adcaaaddcabbabcbcbbcccdaaabacaa") ++ (B) ++ ("cddcacdc") ++ (B) ++ ("dccdaadbbd"));
constraint
  (("acddd") ++ (B) ++ ("cacadcddcaccdac") ++ (B) ++ (B) ++ ("adcc") ++ (B) ++ ("cbcddcddcbdaab") ++ (B) ++ ("cdabadadd") ++ (B))
    =
    (("acddd") ++ (B) ++ ("cacadcddcaccdacb") ++ (B) ++ ("adccbc") ++ (B) ++ ("cddcddcbdaab") ++ (B) ++ ("cdabadaddb"));
constraint
  ((B) ++ ("c") ++ (B) ++ ("ccddddcdaadcccaadab") ++ (B) ++ (B) ++ ("dadaa") ++ (B) ++ (B) ++ ("abccccba") ++ (B) ++ ("db") ++ (B) ++ ("adaaaab") ++ (B) ++ ("dd"))
    =
    (("bc") ++ (B) ++ ("ccddddcdaadcccaada") ++ (B) ++ ("b") ++ (B) ++ ("dadaab") ++ (B) ++ ("a") ++ (B) ++ ("cccc") ++ (B) ++ ("a") ++ (B) ++ ("d") ++ (B) ++ ("badaaaab") ++ (B) ++ ("dd"));
constraint
  (("dc") ++ (B) ++ ("d") ++ (B) ++ ("aadccdba") ++ (B) ++ ("adadbccabdacc") ++ (B) ++ ("dbda") ++ (B) ++ ("ca") ++ (B) ++ ("acdadcaaccabbbcd") ++ (B))
    =
    (("dcbd") ++ (B) ++ ("aadccd") ++ (B) ++ ("abadad") ++ (B) ++ ("cca") ++ (B) ++ ("dacc") ++ (B) ++ ("dbda") ++ (B) ++ ("cabacdadcaaccabbbcd") ++ (B));
constraint
  ((B) ++ ("dcca") ++ (B) ++ ("ba") ++ (B) ++ ("dddcccaaaacdcac") ++ (B) ++ ("a") ++ (B) ++ ("dadddc") ++ (B) ++ ("bcdddacadcabcbcdcca"))
    =
    (("bdccab") ++ (B) ++ ("a") ++ (B) ++ ("dddcccaaaacdcac") ++ (B) ++ ("abdadddcbbcdddacadcabc") ++ (B) ++ ("cdcca"));
constraint
  (("aa") ++ (B) ++ ("cacadcaadcca") ++ (B) ++ ("addadcbd") ++ (B) ++ ("dad") ++ (B) ++ ("accacdaadd") ++ (B) ++ ("d") ++ (B) ++ ("accdcaaadac"))
    =
    (("aabcacadcaadcca") ++ (B) ++ ("addadc") ++ (B) ++ ("d") ++ (B) ++ ("dad") ++ (B) ++ ("accacdaadd") ++ (B) ++ ("d") ++ (B) ++ ("accdcaaadac"));
constraint
  (("dbaaccda") ++ (B) ++ ("aadad") ++ (B) ++ ("aa") ++ (B) ++ ("a") ++ (B) ++ ("cacc") ++ (B) ++ ("cccdbaaadcd") ++ (B) ++ ("bc") ++ (B) ++ ("bcaaadcaa") ++ (B) ++ ("ccd"))
    =
    (("d") ++ (B) ++ ("aaccda") ++ (B) ++ ("aadad") ++ (B) ++ ("aa") ++ (B) ++ ("a") ++ (B) ++ ("caccbcccd") ++ (B) ++ ("aaadcdb") ++ (B) ++ ("c") ++ (B) ++ ("bcaaadcaa") ++ (B) ++ ("ccd"));
solve satisfy;
