var string: B;
var string: A;
constraint
  (("abcadabdccdacddd") ++ (B) ++ ("cdeeebeabbbcedccabbcdcddaa")) =
    (("abcadabdccdacddd") ++ (B) ++ ("cdeeebeabbbcedccabbcdcddaa"));
constraint
  (("cadcdabebaaedadabaaabcdccdbbadb") ++ (A)) =
    (("cadcdabebaaedadabaaabcdccdbbad") ++ (B) ++ ("bebbcccdaebdbbbbbaccad"));
constraint
  (("aabaadcbbaebeebeabdbdbaabcdbceeb") ++ (A) ++ ("cdabbebdcddeaeabdbcecbcacdeea"))
    = (("aabaadcbbaeb") ++ (B) ++ ("ebdcddeaeabdbcecbcacdeea"));
constraint
  (("eeecbdacaee") ++ (A) ++ ("bebedddcabcdbcabdecdeeaedceaedbbcacaabeedcededecbb"))
    =
    (("eeecbdacaeeadebbebedddcabcdbcabdecdeeaedceaedbbcacaabeedcededecbb") ++ (""));
constraint
  (("decbebaaecdcbeabecb") ++ (A) ++ ("aeddecaccebeaeaadceabdedbcbbcebaddcabceaee"))
    =
    (("decbebaaecdcbeabecbadebaeddecaccebeaeaadceabdedbcbbcebaddcabceaee") ++ (""));
constraint
  (("cbeeaaebbbccbaeeadadbcecdaacaaedbebccdbedeecdcddeacdaacebade") ++ (A) ++ ("c"))
    =
    (("cbeeaaebbbccbaeeadadbcecdaacaaedbebccdbedeecdcddeacdaacebadeadebc") ++ (""));
constraint
  (("daadabbaccadbcaacbcadcbeecddbeccbcbaacbeaeadebacadddbacdebeebdacc") ++ (""))
    =
    (("daadabbaccadbcaacbcadcbeecddbeccbcbaacbeae") ++ (A) ++ ("acadddbacdebeebdacc"));
constraint
  (("dadecdcbacebebdbcbdddddeecbeecdd") ++ (A) ++ ("cccecbdbbdaadcebeacccddbcaaad"))
    =
    (("dadecdcbacebebdbcbdddddeecbeecdd") ++ (A) ++ ("cccecbdbbdaadcebeacccddbcaaad"));
constraint
  (("abbaebbddbddcbbcdbebcdaebdbdbaccdbabdaddededebdceeae") ++ (A) ++ ("ccbdadbbc"))
    =
    (("abbaebbddbddcbbcdbebcdaebdbdbaccdbabdaddededebdceeae") ++ (A) ++ ("ccbdadbbc"));
constraint
  ((A) ++ ("eadbdbbaaceaceddaeaeabccbcccbbdeaaecdcebdbaceaabadcadbbecdabc") ++ (""))
    =
    ((A) ++ ("eadbdbbaaceaceddaeaeabccbcccbbdeaaecdcebdbaceaabadcadbbecdabc") ++ (""));
constraint
  (("aabdaedcbbcaebdbaccccccbaccecdabccbbcdc") ++ (A) ++ ("edcaceddceeaeacbebbbab"))
    =
    (("aabdaedcbbcaebdbaccccccbaccecdabccbbcdc") ++ (A) ++ ("edcaceddceeaeacbebbbab"));
constraint
  (("dedacadbaceecebeabbceabcecedebcbdddbbbed") ++ (A) ++ ("dadadbedcebadaaaceeaa"))
    =
    (("dedacadbaceecebeabbceabcecedebcbdddbbbed") ++ (A) ++ ("dadadbedcebadaaaceeaa"));
constraint
  (("eabcbeeaeb") ++ (A) ++ ("cbaaecdcceaadacdaeaacacaeadeeeebaccecccbbdcbcdddeac"))
    =
    (("eabcbeeaeb") ++ (A) ++ ("cbaaecdcceaadacdaeaacacaeadeeeebaccecccbbdcbcdddeac"));
constraint
  (("acdedcbacdbcecdbeacebbabcda") ++ (A) ++ ("deacdabedebeadbbdacebeecdcbdccbaab"))
    =
    (("acdedcbacdbcecdbeacebbabcda") ++ (A) ++ ("deacdabedebeadbbdacebeecdcbdccbaab"));
constraint
  (("dbabcbeadcae") ++ (A) ++ ("ddeaecbbcbebbdbcaddbbdadcaadbbdebcabbbbaaeceacbbe"))
    =
    (("dbabcbeadcae") ++ (A) ++ ("ddeaecbbcbebbdbcaddbbdadcaadbbdebcabbbbaaeceacbbe"));
constraint
  (("caddceebceedbedbeccbeeabacedddccdedacccbeeadadebdeececbcdcecbbeae") ++ (""))
    =
    (("caddceebceedbedbeccbeeabacedddccdedacccbeead") ++ (A) ++ ("deececbcdcecbbeae"));
constraint
  (("dcacbcaeeacebbecbaeebbdeabddbb") ++ (A) ++ ("cdddbcdebdcdeecabadccabacdaebdb"))
    =
    (("dcacbcaeeacebbecbaeebbdeabddbbadebcdddbcdebdcdeecabadccabacdaebdb") ++ (""));
constraint
  (("aabaadeaabeecdabadedaaaaabeeaabdeecaebeaedee") ++ (A) ++ ("deeebeeeeeddbebcc"))
    =
    (("aabaadeaabeecdabadedaaaaabeeaabdeecaebeaedeeadebdeeebeeeeeddbebcc") ++ (""));
constraint
  (("abdbbbabbbcbbecedecedbeabebaddceeacdeedebea") ++ (A) ++ ("aeaedddbaeebeeabab"))
    =
    (("abdbbbabbbcbbecedecedbeabebaddceeacdeedebeaadebaeaedddbaeebeeabab") ++ (""));
constraint
  (("eecaccebebeabcecdaedaeadaaecabaccaeacddabec") ++ (A) ++ ("badaeedbcbeeebedbe"))
    =
    (("eecaccebebeabcecdaedaeadaaecabaccaeacddabecadebbadaeedbcbeeebedbe") ++ (""));
constraint
  (("bdbcedbebde") ++ (A) ++ ("caabdeebcd") ++ (A) ++ ("badcaeedeecbecdbedbceddacaabbcdecedd"))
    =
    (("bdbcedbebde") ++ (A) ++ ("caabdeebcd") ++ (A) ++ ("badcaeedeecbecdbedbceddacaabbcdecedd"));
constraint
  (("eeaeeeeebbedebbacbceceddbcaaeedbacebbdcecaacdd") ++ (A) ++ ("debccbeceddcaab"))
    =
    (("eeaeeeeebbedebbacbceceddbcaaeedbacebbdcecaacddadebdebccbeceddcaab") ++ (""));
solve satisfy;
