var string: A;
constraint
  (("aababcbbbaacbbccbbaaaab") ++ (A) ++ ("acbcaacbcbaababbcaaacbcaacca")) =
    (("aababcbbbaacbbccbbaaaab") ++ (A) ++ ("acbcaacbcbaababbcaaacbcaacca"));
constraint
  (("caccbcabb") ++ (A) ++ ("bacbcbbbccabcaaacacbbaacbbcabaabbcaacabcabccbbccbab"))
    =
    (("caccbcabbccbcbabacbcbbbccabcaaacacbbaacbbcabaabbcaacabcabccbbccbab") ++ (""));
constraint
  (("cccaccbcbabccbbcacbbbbbabbcacacbacbbcbbbcaccccbcccccacbaaccaabbcbc") ++ (""))
    =
    (("ccca") ++ (A) ++ ("bccbbcacbbbbbabbcacacbacbbcbbbcaccccbcccccacbaaccaabbcbc"));
constraint
  (("abbbcaccaacccaabccbbbbcaaacabcaccbbbabcacbbbabaa") ++ (A) ++ ("bcbabaccbabb"))
    =
    (("abbbcaccaacccaabccbbbbcaaacabcaccbbbabcacbbbabaaccbcbabcbabaccbabb") ++ (""));
constraint
  (("acaccbaaaabcaccbacbaccacacacaabbacabbaaabbaaabcaacbcccbaccbcbacabc") ++ (""))
    =
    (("acaccbaaaabcaccbacbaccacacacaabbacabbaaabbaaabcaacbcccba") ++ (A) ++ ("cabc"));
constraint
  (("ccabbcccacbcbbaabaccaaacbbbccccbbbcaccaa") ++ (A) ++ ("bcccacbbcbacbcbaaaca"))
    =
    (("ccabbcccacbcbbaabaccaaacbbbccccbbbcaccaa") ++ (A) ++ ("bcccacbbcbacbcbaaaca"));
constraint
  (("bcabc") ++ (A) ++ ("aacabbaccabaacbaaccbaabaabcacbaabcacbccbaccbabaaacaabbb"))
    =
    (("bcabc") ++ (A) ++ ("aacabbaccabaacbaaccbaabaabcacbaabcacbccbaccbabaaacaabbb"));
constraint
  (("bababcccacbacbaaaabaca") ++ (A) ++ ("bcbaaacaccacbcbbaccabcbabcacbbcbbabcab"))
    =
    (("bababcccacbacbaaaabacaccbcbabcbaaacaccacbcbbaccabcbabcacbbcbbabcab") ++ (""));
constraint
  (("bcaabccaacbbccccabcccccbabcbcabbbaabbcbbabcacbaabccbaccbbbcbccbcba") ++ (""))
    =
    (("bcaabccaacbbccccabcccccbabcbcabbbaabbcbbabcacbaabccbaccbbbcb") ++ (A));
constraint
  (("abaccbccbcbaabaaaaabacbcabcbcabccaaccaabcaaabbcacbcbaccacacbcbaabb") ++ (""))
    =
    (("abaccb") ++ (A) ++ ("abaaaaabacbcabcbcabccaaccaabcaaabbcacbcbaccacacbcbaabb"));
constraint
  (("aaccaacbaacaaabcbcbacbbbbbbacababcbbcaaccbcbabbaacaabbbabacbaacabb") ++ (""))
    =
    (("aaccaacbaacaaabcbcbacbbbbbbacababcbbcaa") ++ (A) ++ ("bbaacaabbbabacbaacabb"));
constraint
  (("abacacbcacbbbbcbcaacbacbcbaacb") ++ (A) ++ ("caacbcbababcaccbbbcbbaabccaccb"))
    =
    (("abacacbcacbbbbcbcaacbacbcbaacb") ++ (A) ++ ("caacbcbababcaccbbbcbbaabccaccb"));
constraint
  (("abcbbacc") ++ (A) ++ ("cbcbacbccbbacbacbabcabaababcbbccbbababccbbbbcacaaaaa"))
    =
    (("abcbbacc") ++ (A) ++ ("cbcbacbccbbacbacbabcabaababcbbccbbababccbbbbcacaaaaa"));
constraint
  (("bcccacbbbcccbc") ++ (A) ++ ("aabbbabbacccabcbbbaacbcbbacaacccbcabbccababcab"))
    =
    (("bcccacbbbcccbcccbcbaaabbbabbacccabcbbbaacbcbbacaacccbcabbccababcab") ++ (""));
constraint
  (("cacaaccbcbabaabaaccbcccaabbcabaabbcaabbcaabacbbbccbcabcbaaccbaaccb") ++ (""))
    =
    (("cacaa") ++ (A) ++ ("baabaaccbcccaabbcabaabbcaabbcaabacbbbccbcabcbaaccbaaccb"));
constraint
  (("bccbcbaaababbcbcabaababcbbacbcccabbabbcbcbbbaaacababbaaaacccbacaaa") ++ (""))
    =
    (("b") ++ (A) ++ ("aababbcbcabaababcbbacbcccabbabbcbcbbbaaacababbaaaacccbacaaa"));
constraint
  (("caacbccaacabbcbccbaacccbcbacbbcbacccccaacaabcacbcbabbacbbbbacbcbbb") ++ (""))
    =
    (("caacbccaacabbcbccbaac") ++ (A) ++ ("cbbcbacccccaacaabcacbcbabbacbbbbacbcbbb"));
constraint
  (("aacacacbbccacbbbabaabacaabcccccaa") ++ (A) ++ ("bbacbbbcacababbaccbbbccbbbc"))
    =
    (("aacacacbbccacbbbabaabacaabcccccaa") ++ (A) ++ ("bbacbbbcacababbaccbbbccbbbc"));
constraint
  (("bccbbabbcccabbaaababbccbccabaaacbbacbbabbbaacaaabbbcaa") ++ (A) ++ ("bcbcab"))
    =
    (("bccbbabbcccabbaaababbccbccabaaacbbacbbabbbaacaaabbbcaa") ++ (A) ++ ("bcbcab"));
constraint
  (("baaaaacbabbbbcabbaccbccbba") ++ (A) ++ ("aabaabbbabcacbccbabbbaabbbacbbacbb"))
    =
    (("baaaaacbabbbbcabbaccbccbba") ++ (A) ++ ("aabaabbbabcacbccbabbbaabbbacbbacbb"));
constraint
  (("abcaaaccbabbbabcaabb") ++ (A) ++ ("bcabbccaabcaccabaabacaccbbcbccbbacaabaac"))
    =
    (("abcaaaccbabbbabcaabbccbcbabcabbccaabcaccabaabacaccbbcbccbbacaabaac") ++ (""));
constraint
  (("aa") ++ (A) ++ ("babbcbbbababcabcabbacbbcbcbbbbccaabaabaacbabbccbaccaaccbcc"))
    =
    (("aaccbcbababbcbbbababcabcabbacbbcbcbbbbccaabaabaacbabbccbaccaaccbcc") ++ (""));
constraint
  (("cbcacbccccacabbacacbbcbabaccacaabbaccacbbbaaabaaccccbbbcbbc") ++ (A) ++ ("a"))
    =
    (("cbcacbccccacabbacacbbcbabaccacaabbaccacbbbaaabaaccccbbbcbbcccbcbaa") ++ (""));
constraint
  (("bbabbabbaaccbcbbbcbbccccaaaacbaaaacccbbaa") ++ (A) ++ ("acbccacccabbacbcbbc"))
    =
    (("bbabbabbaaccbcbbbcbbccccaaaacbaaaacccbbaaccbcbaacbccacccabbacbcbbc") ++ (""));
constraint
  (("cca") ++ (A) ++ ("bacbacccbbbabbbcbcacbabbacaaabcccccbcabbababbcbccbabbcbca"))
    =
    (("cca") ++ (A) ++ ("bacbacccbbbabbbcbcacbabbacaaabcccccbcabbababbcbccbabbcbca"));
constraint
  (("cabaccbc") ++ (A) ++ ("abcacaccccbcccaabbbbbabbacbcaccbbacccccacbaccaaabacb"))
    =
    (("cabaccbc") ++ (A) ++ ("abcacaccccbcccaabbbbbabbacbcaccbbacccccacbaccaaabacb"));
constraint
  (("bcaabaacabbbbaaaabaabaccaabcbcabaaabcbbcaaabcabcbcac") ++ (A) ++ ("bccacacc"))
    =
    (("bcaabaacabbbbaaaabaabaccaabcbcabaaabcbbcaaabcabcbcac") ++ (A) ++ ("bccacacc"));
constraint
  (("ccabccccaacbccb") ++ (A) ++ ("ababbbaacbbbbbbcaabcbbaabaacabaaaaabbbccccccb"))
    =
    (("ccabccccaacbccb") ++ (A) ++ ("ababbbaacbbbbbbcaabcbbaabaacabaaaaabbbccccccb"));
constraint
  (("ababacaabcaabbabcbacba") ++ (A) ++ ("bcbbaacaaacbacacbacaaabbcaacacbcbacbaa"))
    =
    (("ababacaabcaabbabcbacba") ++ (A) ++ ("bcbbaacaaacbacacbacaaabbcaacacbcbacbaa"));
constraint
  (("cacabcabcacbcaacbcbbaacabcaaacbcccccbabaaacbcba") ++ (A) ++ ("bbcbbcbcbccac"))
    =
    (("cacabcabcacbcaacbcbbaacabcaaacbcccccbabaaacbcba") ++ (A) ++ ("bbcbbcbcbccac"));
constraint
  (("bcaabcabacccbabcacaaccbcbacbabcccabc") ++ (A) ++ ("cbbcabbcacccabaacabcabcc"))
    =
    (("bcaabcabacccbabcacaa") ++ (A) ++ ("cbabcccabcccbcbacbbcabbcacccabaacabcabcc"));
constraint
  (("babbacbccbacbcbcababcbbbca") ++ (A) ++ ("ccaaaccbaacaacacbbaaabbbcbacbabbca"))
    =
    (("babbacbccbacbcbcababcbbbcaccbcbaccaaaccbaacaacacbbaaabbbcbacbabbca") ++ (""));
constraint
  (("aaabcbbbabacccababcacbaccbacbbca") ++ (A) ++ ("baacbbccacaaaaaababcbabbaaba"))
    =
    (("aaabcbbbabacccababcacbaccbacbbcaccbcbabaacbbccacaaaaaababcbabbaaba") ++ (""));
constraint
  (("ccbccaa") ++ (A) ++ ("babaccccabaacaacbbaabbababbcaaaaccccacbaabaabacbcacac"))
    =
    (("ccbccaa") ++ (A) ++ ("babaccccabaacaacbbaabbababbcaaaaccccacbaabaabacbcacac"));
constraint
  (("aacaabbabccccc") ++ (A) ++ ("baccaabacbbacacbbbbabbaacaabcaaabbaabbacbcacbb"))
    =
    (("aacaabbabccccc") ++ (A) ++ ("baccaabacbbacacbbbbabbaacaabcaaabbaabbacbcacbb"));
constraint
  (("aaaaa") ++ (A) ++ ("bbcbbbcbcbcbabaababbaaccbbcacbbbbcabaaccbabbcacbbbcbbca"))
    =
    (("aaaaaccbcbabbcbbbcbcbcbabaababbaaccbbcacbbbbcabaaccbabbcacbbbcbbca") ++ (""));
constraint
  (("bbbbacacbabbcacacabacbcaaabcaabcaaacbacacaaaaccbaabbacacccaa") ++ (A)) =
    (("bbbbacacbabbcacacabacbcaaabcaabcaaacbacacaaaaccbaabbacacccaaccbcba") ++ (""));
constraint
  (("aabbbcabccbaaacbcbbbcacbabcba") ++ (A) ++ ("cbcbaababbbcababcabccccbabccbcc"))
    =
    (("aabbbcabccbaaacbcbbbcacbabcbaccbcbacbcbaababbbcababcabccccbabccbcc") ++ (""));
constraint
  (("caaabbacac") ++ (A) ++ ("abbbaacbcbabaccbccbabacbcbabacbcaacacaacbaaccabcbb"))
    =
    (("caaabbacac") ++ (A) ++ ("abbbaacbcbabaccbccbabacbcbabacbcaacacaacbaaccabcbb"));
constraint
  (("babaccabcccccabaaaacabbcacbccbcbaccabbabbbaccacccbbabacccbcccaacbb") ++ (""))
    =
    (("babaccabcccccabaaaacabbcacb") ++ (A) ++ ("ccabbabbbaccacccbbabacccbcccaacbb"));
constraint
  (("caabccbaaaacbaaabaabcbacbcccccbacac") ++ (A) ++ ("accaaabbcbcaccaccbbaaccac"))
    =
    (("caabccbaaaacbaaabaabcbacbcccccbacacccbcbaaccaaabbcbcaccaccbbaaccac") ++ (""));
constraint
  (("cbaaacabbaaccbbacbaccacccbcbaccacaaaaacabbbcacccbbcabcacacacccbcbb") ++ (""))
    =
    (("cbaaacabbaaccbbacbaccac") ++ (A) ++ ("ccacaaaaacabbbcacccbbcabcacacacccbcbb"));
constraint
  (("baaacccbb") ++ (A) ++ ("acaaacbbcaabbabbbbaaacbcbccccbbccaacaacabaaccbbccbc"))
    =
    (("baaacccbbccbcbaacaaacbbcaabbabbbbaaacbcbccccbbccaacaacabaaccbbccbc") ++ (""));
constraint
  (("ababaaaccacbcaabcaabbabaaaacacbcabacabcabccaccabcbbbcb") ++ (A) ++ ("bcaabc"))
    =
    (("ababaaaccacbcaabcaabbabaaaacacbcabacabcabccaccabcbbbcbccbcbabcaabc") ++ (""));
constraint
  (("bbabcabcacacccaaaaabbbbcabccbccbcbacbcccbaabcbccaaacbaababccccacbc") ++ (""))
    =
    (("bbabcabcacacccaaaaabbbbcabccb") ++ (A) ++ ("cbcccbaabcbccaaacbaababccccacbc"));
constraint
  (("cbabbabbbccacbabcbbbccccccccccaabaaabcc") ++ (A) ++ ("caacbbcaacccaacbbacca"))
    =
    (("cbabbabbbccacbabcbbbccccccccccaabaaabccccbcbacaacbbcaacccaacbbacca") ++ (""));
constraint
  (("abaababaacbacabbccccaabbccccbccbccccacbbcccbcbacaccbcaaaaccacbbcbb") ++ (""))
    =
    (("abaababaacbacabbccccaabbccccbccbccccacbbc") ++ (A) ++ ("caccbcaaaaccacbbcbb"));
constraint
  (("cbbababaccacccabcbbabbaacbcaaaabbabaccbabcbbbacbcbcbcbcccbcbababab") ++ (""))
    =
    (("cbbababaccacccabcbbabbaacbcaaaabbabaccbabcbbbacbcbcbcbc") ++ (A) ++ ("babab"));
constraint
  (("bbaacbcbacbcbcacaaacccbcbabaacaabaababbbbccccabcccccacacbccaccbbcc") ++ (""))
    =
    (("bbaacbcbacbcbcacaaac") ++ (A) ++ ("baacaabaababbbbccccabcccccacacbccaccbbcc"));
constraint
  (("cabbbcacacccbcbababaacbacbbcaacabcbccacbcbcaaccacbaaabaabbbbbacaba") ++ (""))
    =
    (("cabbbcacac") ++ (A) ++ ("babaacbacbbcaacabcbccacbcbcaaccacbaaabaabbbbbacaba"));
constraint
  (("ccabcbcaaccacccbcbacbbbbaacccbbbcccbcaacccbaaaccbabbcabaaabababccb") ++ (""))
    =
    (("ccabcbcaaccac") ++ (A) ++ ("cbbbbaacccbbbcccbcaacccbaaaccbabbcabaaabababccb"));
constraint
  (("acbcbbacccbbbbcbcbbbcbbbbcaacbbbaaabcabacaacaabb") ++ (A) ++ ("ccbaaaabacac"))
    =
    (("acbcbbacccbbbbcbcbbbcbbbbcaacbbbaaabcabacaacaabbccbcbaccbaaaabacac") ++ (""));
constraint
  (("abacbcababcccccaacabcabb") ++ (A) ++ ("bcacacbbbbabcaacbbabcbcbcbbcababbbbb"))
    =
    (("abacbcababcccccaacabcabb") ++ (A) ++ ("bcacacbbbbabcaacbbabcbcbcbbcababbbbb"));
constraint
  (("bcaaabccbcbabaabcbabbcaaabaccabccbaccaccabbacacccabaabbccbbaabbbbc") ++ (""))
    =
    (("bcaaab") ++ (A) ++ ("baabcbabbcaaabaccabccbaccaccabbacacccabaabbccbbaabbbbc"));
constraint
  (("bbbabbaaabbab") ++ (A) ++ ("bbbaccabaaccbcacacaccbcaaccbacbccacacbcbccbbabc"))
    =
    (("bbbabbaaabbab") ++ (A) ++ ("bbbaccabaaccbcacacaccbcaaccbacbccacacbcbccbbabc"));
constraint
  (("babcaabbabcbcabbcbbaaacabbaacabcacaababcbbbaaacaababcacaab") ++ (A) ++ ("cb"))
    =
    (("babcaabbabcbcabbcbbaaacabbaacabcacaababcbbbaaacaababcacaab") ++ (A) ++ ("cb"));
constraint
  (("bbacabaaccbccbbabbccbcbabbaccbabacccabbbcbbabcbbacbcbcacbaabbabcbc") ++ (""))
    =
    (("bbacabaaccbccbbabb") ++ (A) ++ ("bbaccbabacccabbbcbbabcbbacbcbcacbaabbabcbc"));
constraint
  (("acaaaccccccbbcbcccabbcccccabbbabbcabcbacbbcabaa") ++ (A) ++ ("bbbacbaabbaca"))
    =
    (("acaaaccccccbbcbcccabbcccccabbbabbcabcbacbbcabaa") ++ (A) ++ ("bbbacbaabbaca"));
constraint
  (("ccacbbaacbaccaaabacbcbbbcbb") ++ (A) ++ ("cabcbbbcaacccbcccabaacaccbaabccbb"))
    =
    (("ccacbbaacbaccaaabacbcbbbcbbccbcbacabcbbbcaacccbcccabaacaccbaabccbb") ++ (""));
constraint
  (("abbaabaaccbbabbacaccbcbcbabccabcbcbccaacaccbccacbcbcaccb") ++ (A) ++ ("caca"))
    =
    (("abbaabaaccbbabbacaccbcbcbabccabcbcbccaacaccbccacbcbcaccb") ++ (A) ++ ("caca"));
constraint
  (("bacacbccba") ++ (A) ++ ("babbcccabccbcaacacabccacaccbaabbcbbccccaaacbbcaabb"))
    =
    (("bacacbccbaccbcbababbcccabccbcaacacabccacaccbaabbcbbccccaaacbbcaabb") ++ (""));
constraint
  (("acacabcabcaabcbaabcccaaabccbabacbaaccbcc") ++ (A) ++ ("abbcacaccbcbcbcbacab"))
    =
    (("acacabcabcaabcbaabcccaaabccbabacbaaccbcc") ++ (A) ++ ("abbcacaccbcbcbcbacab"));
constraint
  (("bbbccbbbbacaaccbaabcabbb") ++ (A) ++ ("abbbacabbbaaccacaacbbbabbabbcccbcaba"))
    =
    (("bbbccbbbbacaaccbaabcabbb") ++ (A) ++ ("abbbacabbbaaccacaacbbbabbabbcccbcaba"));
constraint
  (("aaacacbbcccaaab") ++ (A) ++ ("cbacbaacacaabbcabacacbcabac")) =
    (("aaacacbbcccaaab") ++ (A) ++ ("cbacbaacacaabbcabacacbcabac"));
constraint
  (("cacb") ++ (A) ++ ("abbccbaaacacabaabaacabbbaacbbaacacbcbcaacbccbcaccccac"))
    =
    (("cacbcacbabcbbabbccbaaacacabaabaacabbbaacbbaacacbcbcaacbccbcaccccac") ++ (""));
constraint
  (("babaaccaaccbbbbaaaacacaaabcacc") ++ (A) ++ ("aacbcbbccbccacbaacaabbbaabc"))
    =
    (("babaaccaaccbbbbaaaacacaaabcacc") ++ (A) ++ ("aacbcbbccbccacbaacaabbbaabc"));
constraint
  (("babbacccabcbbbaacbacbbbaabcaccacbaabbacabacacbbcababcaaabbabbccbcb") ++ (""))
    =
    (("babbacccabcbbbaacbacbbb") ++ (A) ++ ("cabacacbbcababcaaabbabbccbcb"));
constraint
  (("bccaaabbbcbcbbbcbbbbaaabcbaaabaaabcccbcabaccabaaabbbcbabbccbcabccb") ++ (""))
    = (("bccaaabbbcbcbbbcbbbbaaabcbaaabaa") ++ (A) ++ ("cb"));
constraint
  (("abacbccbccbcaaacacbcacccbaaaacccbaccbaccabccaaaaacbbcaaaabbcbacbcc") ++ (""))
    = (("abac") ++ (A) ++ ("cc"));
constraint
  (("bcbcbbabcbbcbabbcacaaabcabccabbacabcaaabbaccaaaacabcbbbbabcbbaacbc") ++ (""))
    = (("bcbcbbabcb") ++ (A) ++ ("baccaaaacabcbbbbabcbbaacbc"));
constraint
  (("bbbbaaabbbbbcb") ++ (A) ++ ("cbbcbabbccbcc")) =
    (("bbbbaaabbbbbcb") ++ (A) ++ ("cbbcbabbccbcc"));
constraint
  (("cbccbcbbaabcccbcacbcabacaaaabbabb") ++ (A) ++ ("cccbaaaca")) =
    (("cbccbcbbaabcccbcacbcabacaaaabbabb") ++ (A) ++ ("cccbaaaca"));
constraint
  (("cccacccabcaaaacaccbcc") ++ (A) ++ ("abcbaacacbacbabbbbaabcabbcbaaa")) =
    (("cccacccabcaaaacaccbcc") ++ (A) ++ ("abcbaacacbacbabbbbaabcabbcbaaa"));
constraint
  (("bccabcaabaaabbc") ++ (A) ++ ("ababcaacabcbacbabcbbcbbcbacaacc")) =
    (("bccabcaabaaabbcbacbbaacaacbacaccbbaababcaacabcbacbabcbbcbbcbacaacc") ++ (""));
constraint
  (("babbbcbcbbacaaaabcbbacabcaccbbbabbbabacccccaaabccccccccaababbaccbb") ++ (""))
    =
    (("bab") ++ (A) ++ ("cbbacabcaccbbbabbbabacccccaaabccccccccaababbaccbb"));
constraint
  (("cacc") ++ (A) ++ ("bccacccccabccabcacaab")) =
    (("caccabcbbccabbcbabacbbcbbaaaacbbbaaaaaccbbaaabccacccccabccabcacaab") ++ (""));
constraint
  (("bbbbcbbababcbcaba") ++ (A) ++ ("abaacbccbaaaaababbbbc")) =
    (("bbbbcbbababcbcabacabcccbcaacacacaababcbcbcbababaacbccbaaaaababbbbc") ++ (""));
constraint
  (("accbcbccaacbacb") ++ (A) ++ ("abaaaaccaccbab")) =
    (("accbcbccaacbacb") ++ (A) ++ ("abaaaaccaccbab"));
constraint
  (("aabcaacbcbaaaabbbcbcbabbbcbbabcaccacbcbabbbaaabcbbcabcbbcbbccacabb") ++ (""))
    = (("aabcaacbcbaaaabbbcbc") ++ (A) ++ ("bcbbcabcbbcbbccacabb"));
constraint
  (("acbbbbaabaccccca") ++ (A) ++ ("bc")) =
    (("acbbbbaabacccccaabccaaabaaaccabacbbbcbcbaaccaaacabacaccbaaacabaabc") ++ (""));
constraint
  ((A) ++ ("bbbc") ++ (A) ++ ("a") ++ (A) ++ (A) ++ ("b") ++ (A) ++ ("acaabcab") ++ (A) ++ ("cccbcbbccbbccbc") ++ (A) ++ ("bbbc") ++ (A) ++ ("bbccabcbbbbcaca") ++ (A) ++ ("accccbcbb"))
    =
    ((A) ++ ("bbbc") ++ (A) ++ ("aa") ++ (A) ++ ("ba") ++ (A) ++ ("c") ++ (A) ++ ("abc") ++ (A) ++ ("b") ++ (A) ++ ("cccbcbbccbbccbc") ++ (A) ++ ("bbbcabbccabcbbbbcaca") ++ (A) ++ ("accccbcbb"));
constraint
  (("cbacbbbcccb") ++ (A) ++ ("cc") ++ (A) ++ (A) ++ ("bcb") ++ (A) ++ ("bbb") ++ (A) ++ (A) ++ ("ccabccba") ++ (A) ++ ("cbaacc") ++ (A) ++ (A) ++ ("bcbbb") ++ (A) ++ ("ccbbcaa") ++ (A) ++ (A) ++ ("cab") ++ (A) ++ ("ccbba"))
    =
    (("cb") ++ (A) ++ ("cbbbcccb") ++ (A) ++ ("cc") ++ (A) ++ (A) ++ ("bcbabbb") ++ (A) ++ ("acc") ++ (A) ++ ("bccbaacb") ++ (A) ++ (A) ++ ("ccaabcbbbaccbbcaaa") ++ (A) ++ ("c") ++ (A) ++ ("baccbba"));
constraint
  (("cc") ++ (A) ++ ("cab") ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("acc") ++ (A) ++ ("cbaaccaccbbabcbcacbc") ++ (A) ++ ("aabccbbbcbcb") ++ (A) ++ ("aacbabbbabcccccabc"))
    =
    (("ccac") ++ (A) ++ ("bab") ++ (A) ++ (A) ++ ("acc") ++ (A) ++ ("cba") ++ (A) ++ ("ccaccbb") ++ (A) ++ ("bcbcacbc") ++ (A) ++ (A) ++ (A) ++ ("bccbbbcbcbaaacb") ++ (A) ++ ("bbb") ++ (A) ++ ("bcccccabc"));
constraint
  (("ac") ++ (A) ++ ("cbacbccbcbb") ++ (A) ++ ("cc") ++ (A) ++ ("a") ++ (A) ++ ("bbc") ++ (A) ++ ("bbbcaabcbc") ++ (A) ++ (A) ++ ("b") ++ (A) ++ ("bbbbcbc") ++ (A) ++ ("ac") ++ (A) ++ ("baccbbbcbbb") ++ (A) ++ ("ccbcb"))
    =
    ((A) ++ ("c") ++ (A) ++ ("cbacbccbcbb") ++ (A) ++ ("cca") ++ (A) ++ (A) ++ ("bbc") ++ (A) ++ ("bbbc") ++ (A) ++ ("abcbc") ++ (A) ++ ("ab") ++ (A) ++ ("bbbbcbc") ++ (A) ++ (A) ++ ("c") ++ (A) ++ ("b") ++ (A) ++ ("ccbbbcbbbaccbcb"));
constraint
  (("a") ++ (A) ++ ("bab") ++ (A) ++ ("bbcab") ++ (A) ++ ("cbbc") ++ (A) ++ (A) ++ ("b") ++ (A) ++ ("cbccbabcaccabc") ++ (A) ++ ("cbacccccccbcbccbbb") ++ (A) ++ ("ba") ++ (A) ++ ("c") ++ (A) ++ ("acaaacb"))
    =
    ((A) ++ (A) ++ ("b") ++ (A) ++ ("b") ++ (A) ++ ("bbc") ++ (A) ++ ("bacbbca") ++ (A) ++ ("b") ++ (A) ++ ("cbccb") ++ (A) ++ ("bc") ++ (A) ++ ("ccabc") ++ (A) ++ ("cb") ++ (A) ++ ("cccccccbcbccbbbabaacaaca") ++ (A) ++ ("acb"));
constraint
  (("abbcac") ++ (A) ++ (A) ++ (A) ++ ("accbabcca") ++ (A) ++ ("cccb") ++ (A) ++ ("b") ++ (A) ++ ("cbbbcbcc") ++ (A) ++ (A) ++ (A) ++ ("c") ++ (A) ++ ("ab") ++ (A) ++ (A) ++ ("caa") ++ (A) ++ ("baccbbccbbc") ++ (A) ++ ("a") ++ (A) ++ (A) ++ ("c") ++ (A) ++ ("b") ++ (A))
    =
    ((A) ++ ("bbc") ++ (A) ++ ("c") ++ (A) ++ (A) ++ (A) ++ ("accbabcca") ++ (A) ++ ("cccbab") ++ (A) ++ ("cbbbcbcc") ++ (A) ++ (A) ++ (A) ++ ("c") ++ (A) ++ ("abaaca") ++ (A) ++ ("ab") ++ (A) ++ ("ccbbccbbc") ++ (A) ++ ("aa") ++ (A) ++ ("c") ++ (A) ++ ("ba"));
constraint
  (("b") ++ (A) ++ ("a") ++ (A) ++ ("c") ++ (A) ++ (A) ++ ("bcbbacbbcbcbcca") ++ (A) ++ ("bbb") ++ (A) ++ ("b") ++ (A) ++ ("abcbc") ++ (A) ++ (A) ++ ("c") ++ (A) ++ ("cbbbabaabcbba") ++ (A) ++ ("cbbbbbbb") ++ (A) ++ ("abbb") ++ (A))
    =
    (("ba") ++ (A) ++ (A) ++ ("ca") ++ (A) ++ ("bcbbacbbcbcbcc") ++ (A) ++ ("abbbabaabcbcaacacbbbabaabcbb") ++ (A) ++ ("acbbbbbbb") ++ (A) ++ (A) ++ ("bbba"));
constraint
  (("c") ++ (A) ++ ("bbbbbb") ++ (A) ++ ("bccc") ++ (A) ++ (A) ++ ("cccc") ++ (A) ++ ("ccc") ++ (A) ++ ("cbcbc") ++ (A) ++ ("bcc") ++ (A) ++ ("bcc") ++ (A) ++ (A) ++ ("abbccbbaaabbbbc") ++ (A) ++ ("aabbabcccbb"))
    =
    (("cabbbbbbabccca") ++ (A) ++ ("ccccaccc") ++ (A) ++ ("cbcbcabcc") ++ (A) ++ ("bcca") ++ (A) ++ ("abbccbbaaabbbbca") ++ (A) ++ ("abb") ++ (A) ++ ("bcccbb"));
constraint
  (("b") ++ (A) ++ (A) ++ (A) ++ ("cbbcb") ++ (A) ++ (A) ++ ("bbcabccbccbcaccc") ++ (A) ++ ("b") ++ (A) ++ ("ccbbbcbcbccabaabcccc") ++ (A) ++ ("bcacabac") ++ (A) ++ ("aaab") ++ (A) ++ ("c"))
    =
    (("b") ++ (A) ++ ("aacbbcba") ++ (A) ++ ("bbcabccbccbcacccab") ++ (A) ++ ("ccbbbcbcbcc") ++ (A) ++ ("ba") ++ (A) ++ ("bccccabc") ++ (A) ++ ("c") ++ (A) ++ ("b") ++ (A) ++ ("c") ++ (A) ++ (A) ++ (A) ++ (A) ++ ("bac"));
constraint
  (("cbacccac") ++ (A) ++ ("cbaccbc") ++ (A) ++ ("bcabca") ++ (A) ++ (A) ++ ("c") ++ (A) ++ (A) ++ ("aab") ++ (A) ++ (A) ++ ("bbbbccbbbbbbbabac") ++ (A) ++ ("acb") ++ (A) ++ ("abcbbc") ++ (A) ++ ("a") ++ (A) ++ ("bb"))
    =
    (("cb") ++ (A) ++ ("cccac") ++ (A) ++ ("cb") ++ (A) ++ ("ccbcabcabca") ++ (A) ++ (A) ++ ("c") ++ (A) ++ (A) ++ ("a") ++ (A) ++ ("ba") ++ (A) ++ ("bbbbccbbbbbbb") ++ (A) ++ ("baca") ++ (A) ++ ("cba") ++ (A) ++ ("bcbbc") ++ (A) ++ (A) ++ (A) ++ ("bb"));
constraint
  (("b") ++ (A) ++ (A) ++ ("c") ++ (A) ++ ("bccab") ++ (A) ++ ("cbccbc") ++ (A) ++ ("cbbc") ++ (A) ++ ("ba") ++ (A) ++ (A) ++ ("bbbccca") ++ (A) ++ ("bbbbcbbbb") ++ (A) ++ ("abc") ++ (A) ++ ("abcc") ++ (A) ++ ("bbbbcc") ++ (A) ++ ("cbcbb"))
    =
    (("b") ++ (A) ++ (A) ++ ("cabcc") ++ (A) ++ ("b") ++ (A) ++ ("cbccbcacbbcab") ++ (A) ++ (A) ++ ("abbbcccaabbbbcbbbba") ++ (A) ++ ("bca") ++ (A) ++ ("bccabbbbccacbcbb"));
constraint
  (("bbc") ++ (A) ++ ("abaccbcbccbccc") ++ (A) ++ ("a") ++ (A) ++ ("cc") ++ (A) ++ ("cbcccbbbcc") ++ (A) ++ ("abccacbb") ++ (A) ++ ("c") ++ (A) ++ ("abbabbcb") ++ (A) ++ ("ccbbbb") ++ (A) ++ (A) ++ ("abc"))
    =
    (("bbc") ++ (A) ++ ("abaccbcbccbccca") ++ (A) ++ (A) ++ ("ccacbcccbbbcc") ++ (A) ++ (A) ++ ("bccacbb") ++ (A) ++ ("caabb") ++ (A) ++ ("bbcb") ++ (A) ++ ("ccbbbba") ++ (A) ++ ("abc"));
constraint
  (("bcaccacc") ++ (A) ++ ("c") ++ (A) ++ ("bb") ++ (A) ++ ("abb") ++ (A) ++ ("cb") ++ (A) ++ (A) ++ ("aacbabcabbaccbbcbc") ++ (A) ++ ("bcb") ++ (A) ++ ("ab") ++ (A) ++ (A) ++ ("ccbbabbc") ++ (A) ++ (A) ++ ("bbbb") ++ (A) ++ ("aa"))
    =
    (("bcaccaccacabba") ++ (A) ++ ("bb") ++ (A) ++ ("cb") ++ (A) ++ (A) ++ (A) ++ ("acb") ++ (A) ++ ("bcabb") ++ (A) ++ ("ccbbcbc") ++ (A) ++ ("bcb") ++ (A) ++ ("ab") ++ (A) ++ (A) ++ ("ccbb") ++ (A) ++ ("bbc") ++ (A) ++ (A) ++ ("bbbb") ++ (A) ++ (A) ++ (A));
constraint
  ((A) ++ ("ccbccc") ++ (A) ++ ("ccccbb") ++ (A) ++ ("b") ++ (A) ++ ("ccbbcb") ++ (A) ++ (A) ++ ("c") ++ (A) ++ ("cba") ++ (A) ++ ("ccacccba") ++ (A) ++ ("b") ++ (A) ++ (A) ++ (A) ++ ("cbcbbacbbabba") ++ (A) ++ ("cbbcc") ++ (A) ++ ("bb"))
    =
    (("accbcccaccccbbabaccbbcb") ++ (A) ++ ("acacba") ++ (A) ++ ("cc") ++ (A) ++ ("cccb") ++ (A) ++ ("ab") ++ (A) ++ (A) ++ ("acbcbbacbb") ++ (A) ++ ("bb") ++ (A) ++ ("acbbccabb"));
constraint
  (("b") ++ (A) ++ ("ccbcbbbcbbaabab") ++ (A) ++ ("aaaacbbcaa") ++ (A) ++ (A) ++ ("acbbb") ++ (A) ++ ("bcc") ++ (A) ++ (A) ++ ("cbc") ++ (A) ++ ("cbab") ++ (A) ++ ("cb") ++ (A) ++ ("caabab") ++ (A) ++ ("cbabbb"))
    =
    (("baccbcbbbcbb") ++ (A) ++ (A) ++ ("b") ++ (A) ++ ("ba") ++ (A) ++ ("aa") ++ (A) ++ ("cbbc") ++ (A) ++ ("aa") ++ (A) ++ (A) ++ ("cbbb") ++ (A) ++ ("bcc") ++ (A) ++ ("acbc") ++ (A) ++ ("cbab") ++ (A) ++ ("cb") ++ (A) ++ ("ca") ++ (A) ++ ("babacb") ++ (A) ++ ("bbb"));
constraint
  (("c") ++ (A) ++ ("bc") ++ (A) ++ ("bcaab") ++ (A) ++ ("cbcacbccbabbabbbbcbc") ++ (A) ++ ("abbbac") ++ (A) ++ ("bcaa") ++ (A) ++ ("bbccc") ++ (A) ++ ("acbccbbbbccbbaac"))
    =
    (("cabcabc") ++ (A) ++ (A) ++ ("b") ++ (A) ++ ("cbcacbccbabbabbbbcbca") ++ (A) ++ ("bbbacabc") ++ (A) ++ (A) ++ (A) ++ ("bbccc") ++ (A) ++ ("acbccbbbbccbb") ++ (A) ++ (A) ++ ("c"));
constraint
  (("acbccab") ++ (A) ++ ("a") ++ (A) ++ ("ccaabcb") ++ (A) ++ (A) ++ ("ccab") ++ (A) ++ ("cbcc") ++ (A) ++ ("babbab") ++ (A) ++ ("bcbcbbbcb") ++ (A) ++ ("babcc") ++ (A) ++ ("aaccabbbcb") ++ (A) ++ ("ccb"))
    =
    ((A) ++ ("cbcc") ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("acc") ++ (A) ++ ("abcb") ++ (A) ++ ("acc") ++ (A) ++ ("b") ++ (A) ++ ("cbcc") ++ (A) ++ ("babb") ++ (A) ++ ("b") ++ (A) ++ ("bcbcbbbcb") ++ (A) ++ ("b") ++ (A) ++ ("bccaaaccabbbcbaccb"));
constraint
  (("c") ++ (A) ++ ("cccbb") ++ (A) ++ ("ca") ++ (A) ++ ("abbaacbab") ++ (A) ++ (A) ++ ("acabccc") ++ (A) ++ ("b") ++ (A) ++ ("b") ++ (A) ++ ("bcaaa") ++ (A) ++ ("cbcbb") ++ (A) ++ ("cbbbbc") ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("bccbccb") ++ (A) ++ ("b") ++ (A))
    =
    (("c") ++ (A) ++ ("cccbb") ++ (A) ++ ("c") ++ (A) ++ (A) ++ ("abba") ++ (A) ++ ("cb") ++ (A) ++ ("b") ++ (A) ++ ("aac") ++ (A) ++ ("bcccab") ++ (A) ++ ("babc") ++ (A) ++ ("a") ++ (A) ++ ("acbcbb") ++ (A) ++ ("cbbbbc") ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("bccbccbaba"));
constraint
  (("bcc") ++ (A) ++ ("cbcabc") ++ (A) ++ ("bcbbc") ++ (A) ++ ("ababb") ++ (A) ++ ("cbcba") ++ (A) ++ ("a") ++ (A) ++ (A) ++ ("b") ++ (A) ++ ("ab") ++ (A) ++ (A) ++ ("cbcbbbbcabcb") ++ (A) ++ ("bcacbcacbbbcccb"))
    =
    (("bcc") ++ (A) ++ ("cbcabc") ++ (A) ++ ("bcbbcaab") ++ (A) ++ ("bb") ++ (A) ++ ("cbcb") ++ (A) ++ ("a") ++ (A) ++ (A) ++ ("abaab") ++ (A) ++ (A) ++ ("cbcbbbbcabcb") ++ (A) ++ ("bc") ++ (A) ++ ("cbc") ++ (A) ++ ("cbbbcccb"));
constraint
  (("accbcaa") ++ (A) ++ ("bcba") ++ (A) ++ ("cabbbbcbac") ++ (A) ++ ("cbcc") ++ (A) ++ ("bcacabccacbaaabaaccbbbb") ++ (A) ++ ("cbcbb") ++ (A) ++ ("bcaacbc"))
    =
    (("accbca") ++ (A) ++ ("abcb") ++ (A) ++ (A) ++ ("cabbbbcb") ++ (A) ++ ("cacbcc") ++ (A) ++ ("bcacabcc") ++ (A) ++ ("cb") ++ (A) ++ (A) ++ (A) ++ ("baaccbbbbacbcbbabc") ++ (A) ++ (A) ++ ("cbc"));
constraint
  (("ccbcccbcccbaabb") ++ (A) ++ ("cba") ++ (A) ++ ("accacb") ++ (A) ++ ("bcbbbbabccabbccbbca") ++ (A) ++ ("a") ++ (A) ++ ("ccb") ++ (A) ++ ("ccc") ++ (A) ++ ("cb") ++ (A) ++ ("bbbccb"))
    =
    (("ccbcccbcccbaabbacbaa") ++ (A) ++ ("ccacb") ++ (A) ++ ("bcbbbb") ++ (A) ++ ("bcc") ++ (A) ++ ("bbccbbcaa") ++ (A) ++ ("accb") ++ (A) ++ ("ccc") ++ (A) ++ ("cbabbbccb"));
constraint
  (("cab") ++ (A) ++ ("abcb") ++ (A) ++ ("bbab") ++ (A) ++ ("cbab") ++ (A) ++ ("cbcbccbbcccbb") ++ (A) ++ ("bacccb") ++ (A) ++ ("ba") ++ (A) ++ ("cbcbbcccbc") ++ (A) ++ ("bbc") ++ (A) ++ ("cccabbac"))
    =
    (("c") ++ (A) ++ ("b") ++ (A) ++ ("abcb") ++ (A) ++ ("bb") ++ (A) ++ ("bacb") ++ (A) ++ ("bacbcbccbbcccbb") ++ (A) ++ ("b") ++ (A) ++ ("cccb") ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("cbcbbcccbc") ++ (A) ++ ("bbc") ++ (A) ++ ("cccabbac"));
constraint
  ((A) ++ ("c") ++ (A) ++ ("b") ++ (A) ++ ("cbbbaabccbbbaab") ++ (A) ++ ("ccb") ++ (A) ++ ("ccbbbbbbbbbbbbb") ++ (A) ++ ("b") ++ (A) ++ ("c") ++ (A) ++ ("cabc") ++ (A) ++ ("abba") ++ (A) ++ ("cc") ++ (A) ++ ("ccaccccc"))
    =
    (("ac") ++ (A) ++ ("bacbbbaabccbbbaab") ++ (A) ++ ("ccb") ++ (A) ++ ("ccbbbbbbbbbbbbb") ++ (A) ++ ("bacac") ++ (A) ++ ("bca") ++ (A) ++ ("bba") ++ (A) ++ ("ccaccaccccc"));
constraint
  (("bcaaccbbcb") ++ (A) ++ ("cabaabbc") ++ (A) ++ ("babcbaaa") ++ (A) ++ (A) ++ ("baaaccabbbc") ++ (A) ++ ("a") ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("bbcbbbcaaacaac") ++ (A) ++ ("c") ++ (A) ++ ("ab"))
    =
    (("bc") ++ (A) ++ ("accbbcb") ++ (A) ++ ("c") ++ (A) ++ ("ba") ++ (A) ++ ("bbc") ++ (A) ++ ("babcba") ++ (A) ++ ("a") ++ (A) ++ ("ab") ++ (A) ++ (A) ++ ("acc") ++ (A) ++ ("bbbcaa") ++ (A) ++ ("ba") ++ (A) ++ ("bbcbbbc") ++ (A) ++ (A) ++ ("acaacacaab"));
constraint
  (("ba") ++ (A) ++ ("ab") ++ (A) ++ ("cccc") ++ (A) ++ ("bcc") ++ (A) ++ ("bcbab") ++ (A) ++ ("aacccbaac") ++ (A) ++ ("cbcaa") ++ (A) ++ ("bca") ++ (A) ++ ("cbcbbccbcbcbaaccabccc") ++ (A) ++ ("acc"))
    =
    (("ba") ++ (A) ++ ("ab") ++ (A) ++ ("cccc") ++ (A) ++ ("bccabcbabaaacccb") ++ (A) ++ ("acacbcaaabcaacbcbbccbcbcbaacc") ++ (A) ++ ("bccca") ++ (A) ++ ("cc"));
constraint
  (("bccb") ++ (A) ++ ("aabbccacabbb") ++ (A) ++ ("bc") ++ (A) ++ ("aaabac") ++ (A) ++ ("c") ++ (A) ++ ("cabc") ++ (A) ++ ("cbabbbcabaccccccabbabcaaccacb") ++ (A) ++ (A))
    =
    (("bccba") ++ (A) ++ ("abbcc") ++ (A) ++ ("c") ++ (A) ++ ("bbbabc") ++ (A) ++ ("a") ++ (A) ++ (A) ++ ("b") ++ (A) ++ ("c") ++ (A) ++ ("c") ++ (A) ++ ("c") ++ (A) ++ ("bcacb") ++ (A) ++ ("bbbcabacccccc") ++ (A) ++ ("bb") ++ (A) ++ ("bca") ++ (A) ++ ("ccacba") ++ (A));
constraint
  (("bacbb") ++ (A) ++ ("ba") ++ (A) ++ ("b") ++ (A) ++ ("baab") ++ (A) ++ ("c") ++ (A) ++ ("ba") ++ (A) ++ (A) ++ ("ccb") ++ (A) ++ (A) ++ ("acbbbbbbccbb") ++ (A) ++ ("cbacbabbcbb") ++ (A) ++ ("cb") ++ (A) ++ ("cc") ++ (A) ++ ("b") ++ (A) ++ ("abbabc"))
    =
    (("bacbb") ++ (A) ++ ("ba") ++ (A) ++ ("b") ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("b") ++ (A) ++ ("c") ++ (A) ++ ("b") ++ (A) ++ ("a") ++ (A) ++ ("ccbaaacbbbbbbccbb") ++ (A) ++ ("cbacb") ++ (A) ++ ("bbcbbacbaccab") ++ (A) ++ (A) ++ ("bbabc"));
constraint
  (("acc") ++ (A) ++ ("bac") ++ (A) ++ ("bccc") ++ (A) ++ ("acccbb") ++ (A) ++ (A) ++ ("cb") ++ (A) ++ ("bcb") ++ (A) ++ ("ab") ++ (A) ++ (A) ++ (A) ++ ("c") ++ (A) ++ ("accbc") ++ (A) ++ ("cbabbbbc") ++ (A) ++ ("acbcbbcc") ++ (A) ++ ("cbab") ++ (A) ++ ("ac"))
    =
    (("accabacabccc") ++ (A) ++ ("acccbb") ++ (A) ++ (A) ++ ("cbabcba") ++ (A) ++ ("ba") ++ (A) ++ (A) ++ ("ca") ++ (A) ++ ("ccbcacb") ++ (A) ++ ("bbbbc") ++ (A) ++ (A) ++ ("cbcbbccacb") ++ (A) ++ ("baac"));
constraint
  ((A) ++ ("bb") ++ (A) ++ (A) ++ ("bcabbcbcc") ++ (A) ++ (A) ++ (A) ++ (A) ++ ("cccacaac") ++ (A) ++ ("cbccbbccccbaab") ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("baccab") ++ (A) ++ ("c") ++ (A) ++ (A) ++ ("b") ++ (A) ++ ("ab") ++ (A) ++ ("bbcbcb"))
    =
    ((A) ++ ("bbaabcabbcbcca") ++ (A) ++ ("aacccaca") ++ (A) ++ ("c") ++ (A) ++ ("cbccbbccccb") ++ (A) ++ ("ababa") ++ (A) ++ ("baccabac") ++ (A) ++ ("aba") ++ (A) ++ ("b") ++ (A) ++ ("bbcbcb"));
constraint
  (("cab") ++ (A) ++ ("cc") ++ (A) ++ ("bbacb") ++ (A) ++ (A) ++ (A) ++ ("b") ++ (A) ++ ("bb") ++ (A) ++ ("bbbcbbbbb") ++ (A) ++ ("abb") ++ (A) ++ ("bbbb") ++ (A) ++ ("cacaab") ++ (A) ++ ("accccccac") ++ (A) ++ ("ccccabccab"))
    =
    (("cabacc") ++ (A) ++ ("bbacb") ++ (A) ++ ("a") ++ (A) ++ ("b") ++ (A) ++ ("bbabbbcbbbbb") ++ (A) ++ ("abb") ++ (A) ++ ("bbbb") ++ (A) ++ ("caca") ++ (A) ++ ("b") ++ (A) ++ ("acccccc") ++ (A) ++ ("c") ++ (A) ++ ("ccccabccab"));
constraint
  (("b") ++ (A) ++ ("b") ++ (A) ++ ("bccccbbccccccb") ++ (A) ++ ("b") ++ (A) ++ ("cccccbcbbccaa") ++ (A) ++ (A) ++ ("abbcbbcab") ++ (A) ++ ("bbc") ++ (A) ++ (A) ++ ("aabbabbccc") ++ (A) ++ ("bccc"))
    =
    (("bababccccbbccccccbabacccccbcbbcca") ++ (A) ++ (A) ++ (A) ++ (A) ++ ("bbcbbcab") ++ (A) ++ ("bbcaa") ++ (A) ++ ("abbabbccc") ++ (A) ++ ("bccc"));
constraint
  (("bbccbabbccbbcbabcccccacbbaabccbcab") ++ (A) ++ ("acbcbac") ++ (A) ++ ("cabcc") ++ (A) ++ (A) ++ ("cbbabbcbbbaabaab"))
    =
    (("bbccbabbccbbcbabcccccacbbaabccbcab") ++ (A) ++ ("acbcb") ++ (A) ++ ("c") ++ (A) ++ ("c") ++ (A) ++ ("bcc") ++ (A) ++ (A) ++ ("cbbabbcbbb") ++ (A) ++ (A) ++ ("b") ++ (A) ++ ("ab"));
constraint
  (("c") ++ (A) ++ ("bccc") ++ (A) ++ (A) ++ ("cccbcb") ++ (A) ++ ("ac") ++ (A) ++ ("bcccc") ++ (A) ++ ("bccb") ++ (A) ++ (A) ++ ("acbcbcbba") ++ (A) ++ ("caccccccabcbccbbbcbbcccc") ++ (A) ++ ("b"))
    =
    (("c") ++ (A) ++ ("bcccaacccbcb") ++ (A) ++ ("acabccccabccb") ++ (A) ++ ("aacbcbcbba") ++ (A) ++ ("c") ++ (A) ++ ("cccccc") ++ (A) ++ ("bcbccbbbcbbcccc") ++ (A) ++ ("b"));
constraint
  (("acc") ++ (A) ++ ("bcbaa") ++ (A) ++ ("a") ++ (A) ++ ("ca") ++ (A) ++ (A) ++ ("cb") ++ (A) ++ ("bbcccbbcccbba") ++ (A) ++ (A) ++ ("bc") ++ (A) ++ ("acccbbbaab") ++ (A) ++ ("abaaccb") ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("cbbcccc"))
    =
    (("acc") ++ (A) ++ ("bcba") ++ (A) ++ ("aa") ++ (A) ++ ("c") ++ (A) ++ ("a") ++ (A) ++ ("cb") ++ (A) ++ ("bbcccbbcccbbaaabc") ++ (A) ++ (A) ++ ("cccbbba") ++ (A) ++ ("baab") ++ (A) ++ ("accbab") ++ (A) ++ (A) ++ ("cbbcccc"));
constraint
  (("ca") ++ (A) ++ ("abbccbabcbbc") ++ (A) ++ ("bcaab") ++ (A) ++ (A) ++ ("ccb") ++ (A) ++ ("bcb") ++ (A) ++ ("bcbbcbc") ++ (A) ++ ("bca") ++ (A) ++ ("cbbbbbbabbac") ++ (A) ++ ("ccaccabbbc"))
    =
    (("c") ++ (A) ++ ("a") ++ (A) ++ ("bbccb") ++ (A) ++ ("bcbbcabc") ++ (A) ++ (A) ++ ("b") ++ (A) ++ ("accbabcb") ++ (A) ++ ("bcbbcbc") ++ (A) ++ ("bca") ++ (A) ++ ("cbbbbbb") ++ (A) ++ ("bb") ++ (A) ++ ("caccaccabbbc"));
constraint
  (("ccbbcb") ++ (A) ++ ("bb") ++ (A) ++ ("bba") ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("bc") ++ (A) ++ (A) ++ ("ab") ++ (A) ++ ("c") ++ (A) ++ ("cbccbcb") ++ (A) ++ (A) ++ ("bc") ++ (A) ++ ("b") ++ (A) ++ ("cbacc") ++ (A) ++ (A) ++ (A) ++ ("cbbb") ++ (A) ++ ("c") ++ (A) ++ ("cc") ++ (A) ++ ("bcccabbc"))
    =
    (("ccbbcbabb") ++ (A) ++ ("bb") ++ (A) ++ ("ab") ++ (A) ++ ("abc") ++ (A) ++ ("aabacacbccbcb") ++ (A) ++ (A) ++ ("bcabacbacca") ++ (A) ++ (A) ++ ("cbbbac") ++ (A) ++ ("cc") ++ (A) ++ ("bcccabbc"));
constraint
  ((A) ++ ("cc") ++ (A) ++ (A) ++ ("a") ++ (A) ++ ("bcbbbccbabbc") ++ (A) ++ ("bcbaacbacc") ++ (A) ++ ("bcbccbccc") ++ (A) ++ ("bacaaacaaacac") ++ (A) ++ ("b") ++ (A) ++ ("bbbaca") ++ (A) ++ ("bc"))
    =
    ((A) ++ ("cc") ++ (A) ++ ("a") ++ (A) ++ (A) ++ ("bcbbbccbabbc") ++ (A) ++ ("bcb") ++ (A) ++ ("acb") ++ (A) ++ ("cc") ++ (A) ++ ("bcbccbcccab") ++ (A) ++ ("caaaca") ++ (A) ++ (A) ++ ("cacab") ++ (A) ++ ("bbbacaabc"));
constraint
  (("cacacccccbbc") ++ (A) ++ ("cc") ++ (A) ++ ("caba") ++ (A) ++ ("abccbacbab") ++ (A) ++ ("cbb") ++ (A) ++ ("c") ++ (A) ++ ("cbcbbccc") ++ (A) ++ ("aabbcb") ++ (A) ++ ("c") ++ (A) ++ ("bb") ++ (A) ++ ("bccc") ++ (A) ++ ("ca"))
    =
    (("c") ++ (A) ++ ("c") ++ (A) ++ ("cccccbbc") ++ (A) ++ ("cc") ++ (A) ++ ("c") ++ (A) ++ ("b") ++ (A) ++ ("a") ++ (A) ++ ("bccbacb") ++ (A) ++ ("b") ++ (A) ++ ("cbb") ++ (A) ++ ("c") ++ (A) ++ ("cbcbbccca") ++ (A) ++ ("abbcb") ++ (A) ++ ("cabb") ++ (A) ++ ("bccc") ++ (A) ++ ("ca"));
constraint
  (("b") ++ (A) ++ ("cca") ++ (A) ++ (A) ++ (A) ++ ("bbbccabcbababb") ++ (A) ++ ("cbbaa") ++ (A) ++ (A) ++ ("ba") ++ (A) ++ ("cb") ++ (A) ++ ("ccb") ++ (A) ++ (A) ++ (A) ++ ("cbccaabbcb") ++ (A) ++ ("babccbccbcb") ++ (A) ++ ("b"))
    =
    (("b") ++ (A) ++ ("cca") ++ (A) ++ ("a") ++ (A) ++ ("bbbccabcb") ++ (A) ++ ("b") ++ (A) ++ ("bb") ++ (A) ++ ("cbbaa") ++ (A) ++ (A) ++ ("b") ++ (A) ++ ("acbaccba") ++ (A) ++ ("acbcca") ++ (A) ++ ("bbcb") ++ (A) ++ ("babccbccbcb") ++ (A) ++ ("b"));
constraint
  (("a") ++ (A) ++ ("abbbc") ++ (A) ++ ("bca") ++ (A) ++ ("bbc") ++ (A) ++ (A) ++ ("caac") ++ (A) ++ ("bc") ++ (A) ++ (A) ++ ("acbccccabcc") ++ (A) ++ ("abacb") ++ (A) ++ ("c") ++ (A) ++ ("bbaa") ++ (A) ++ ("bac") ++ (A) ++ ("bccabccc") ++ (A) ++ ("ca"))
    =
    ((A) ++ (A) ++ (A) ++ ("bbbc") ++ (A) ++ ("bc") ++ (A) ++ ("abbc") ++ (A) ++ (A) ++ ("caacabc") ++ (A) ++ (A) ++ (A) ++ ("cbccccabcc") ++ (A) ++ (A) ++ ("b") ++ (A) ++ ("cbac") ++ (A) ++ ("bbaa") ++ (A) ++ ("bac") ++ (A) ++ ("bccabcccaca"));
constraint
  ((A) ++ ("bbbbbbaa") ++ (A) ++ ("cbb") ++ (A) ++ ("bacccccbcccbabcbbcca") ++ (A) ++ ("accabcbb") ++ (A) ++ ("accca") ++ (A) ++ ("cacb") ++ (A) ++ ("cbcbbbcccba"))
    =
    ((A) ++ ("bbbbbba") ++ (A) ++ (A) ++ ("cbb") ++ (A) ++ ("bacccccbcccbabcbbccaaacc") ++ (A) ++ ("bcbb") ++ (A) ++ ("accc") ++ (A) ++ ("acacbacbcbbbcccba"));
constraint
  (("bcab") ++ (A) ++ ("c") ++ (A) ++ ("cbaacbcabcab") ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("bcbbbccbc") ++ (A) ++ ("bcccaca") ++ (A) ++ ("ac") ++ (A) ++ ("cccaabbcbbbbc") ++ (A) ++ ("cabbbbbc"))
    =
    (("bcabacacbaacbcabc") ++ (A) ++ ("b") ++ (A) ++ ("ba") ++ (A) ++ ("bcbbbccbc") ++ (A) ++ ("bccc") ++ (A) ++ ("c") ++ (A) ++ (A) ++ (A) ++ ("caccc") ++ (A) ++ ("abbcbbbbcac") ++ (A) ++ ("bbbbbc"));
constraint
  ((A) ++ ("ccb") ++ (A) ++ ("bcbcbbaababcbbcbb") ++ (A) ++ ("bbaa") ++ (A) ++ ("ccccabbccbacb") ++ (A) ++ ("cccb") ++ (A) ++ ("aacbcaaccb") ++ (A) ++ ("ccbbbbcc"))
    =
    (("accb") ++ (A) ++ ("bcbcbb") ++ (A) ++ (A) ++ ("babcbbcbbabb") ++ (A) ++ (A) ++ (A) ++ ("cccc") ++ (A) ++ ("bbccbacb") ++ (A) ++ ("cccbaa") ++ (A) ++ ("cbcaaccb") ++ (A) ++ ("ccbbbbcc"));
constraint
  (("babbacbabcac") ++ (A) ++ ("cbbbb") ++ (A) ++ ("babbacbacbb") ++ (A) ++ (A) ++ ("abbcbcbbab") ++ (A) ++ ("bbcbbabccbbbbbbbaaccc") ++ (A) ++ ("c"))
    =
    (("babbacb") ++ (A) ++ ("bc") ++ (A) ++ ("c") ++ (A) ++ ("cbbbbababbacbacbba") ++ (A) ++ ("abbcbcbb") ++ (A) ++ ("b") ++ (A) ++ ("bbcbbabccbbbbbbba") ++ (A) ++ ("cccac"));
constraint
  (("bb") ++ (A) ++ ("bbbaccbabccacbbcbcccabbb") ++ (A) ++ ("abbb") ++ (A) ++ ("cc") ++ (A) ++ ("b") ++ (A) ++ ("a") ++ (A) ++ (A) ++ ("bbbcbcccaccbccacc") ++ (A) ++ ("acaa") ++ (A) ++ ("cc"))
    =
    (("bbabbbaccb") ++ (A) ++ ("bccacbbcbcccabbba") ++ (A) ++ ("bbb") ++ (A) ++ ("cc") ++ (A) ++ ("ba") ++ (A) ++ (A) ++ ("abbbcbccc") ++ (A) ++ ("ccbcc") ++ (A) ++ ("cc") ++ (A) ++ (A) ++ ("c") ++ (A) ++ (A) ++ ("acc"));
constraint
  ((A) ++ ("b") ++ (A) ++ ("bbcc") ++ (A) ++ ("bcabbccbabcabacabaa") ++ (A) ++ ("ccccba") ++ (A) ++ (A) ++ ("bcbccbb") ++ (A) ++ (A) ++ ("bcbcbbbabc") ++ (A) ++ ("bba") ++ (A) ++ ("acbbbb"))
    =
    ((A) ++ ("b") ++ (A) ++ ("bbccabcabbccbabcab") ++ (A) ++ ("caba") ++ (A) ++ (A) ++ ("ccccb") ++ (A) ++ ("a") ++ (A) ++ ("bcbccbbaabcbcbbbabc") ++ (A) ++ ("bb") ++ (A) ++ (A) ++ (A) ++ ("cbbbb"));
constraint
  (("abbbcbbc") ++ (A) ++ ("bcac") ++ (A) ++ ("acbcbbccbcbcabccacb") ++ (A) ++ ("cba") ++ (A) ++ ("cb") ++ (A) ++ ("bcaccabcab") ++ (A) ++ ("ccacbacbcb") ++ (A) ++ ("a") ++ (A) ++ ("b"))
    =
    (("abbbcbbcabc") ++ (A) ++ ("ca") ++ (A) ++ ("cbcbbccbcbcabcc") ++ (A) ++ ("cb") ++ (A) ++ ("cbaacbabcacc") ++ (A) ++ ("bcabacc") ++ (A) ++ ("cbacbcba") ++ (A) ++ ("ab"));
constraint
  (("babccbabbabb") ++ (A) ++ ("ab") ++ (A) ++ (A) ++ ("baccabcbcccbac") ++ (A) ++ ("ac") ++ (A) ++ ("cabbb") ++ (A) ++ ("abcbcc") ++ (A) ++ ("bccccacbbc") ++ (A) ++ ("bbab") ++ (A) ++ ("b") ++ (A))
    =
    (("babccbabbabbaab") ++ (A) ++ (A) ++ ("bacc") ++ (A) ++ ("bcbcccb") ++ (A) ++ ("caacac") ++ (A) ++ ("bbbaabcbcc") ++ (A) ++ ("bcccc") ++ (A) ++ ("cbbcabb") ++ (A) ++ ("bab") ++ (A));
constraint
  (("ccabbccbaabcbba") ++ (A) ++ ("a") ++ (A) ++ ("bcc") ++ (A) ++ ("baa") ++ (A) ++ ("cbbbc") ++ (A) ++ (A) ++ ("bbaccbcacb") ++ (A) ++ ("cbbbcbbbb") ++ (A) ++ (A) ++ ("acb") ++ (A) ++ ("bcaabb") ++ (A))
    =
    (("ccabbccb") ++ (A) ++ (A) ++ ("bcbbaaa") ++ (A) ++ ("bccabaa") ++ (A) ++ ("cbbbc") ++ (A) ++ (A) ++ ("bbaccbcacb") ++ (A) ++ ("cbbbcbbbb") ++ (A) ++ (A) ++ (A) ++ ("cbabca") ++ (A) ++ ("bba"));
constraint
  (("abbcabbcc") ++ (A) ++ ("ccc") ++ (A) ++ ("c") ++ (A) ++ ("b") ++ (A) ++ ("ccbbccccbcbbca") ++ (A) ++ (A) ++ ("b") ++ (A) ++ ("bbbbabb") ++ (A) ++ ("cbab") ++ (A) ++ ("acccbbb") ++ (A) ++ ("ab") ++ (A) ++ ("ccb") ++ (A) ++ ("bc"))
    =
    ((A) ++ ("bbcabbccacccacabaccbbccccbcbbc") ++ (A) ++ ("aab") ++ (A) ++ ("bbbb") ++ (A) ++ ("bb") ++ (A) ++ ("cb") ++ (A) ++ ("baacccbbba") ++ (A) ++ ("baccb") ++ (A) ++ ("bc"));
constraint
  (("bab") ++ (A) ++ (A) ++ ("cb") ++ (A) ++ ("a") ++ (A) ++ ("ccccb") ++ (A) ++ ("bc") ++ (A) ++ ("ca") ++ (A) ++ ("bcba") ++ (A) ++ ("bbbabbb") ++ (A) ++ ("a") ++ (A) ++ ("c") ++ (A) ++ (A) ++ ("c") ++ (A) ++ ("a") ++ (A) ++ ("ccbb") ++ (A) ++ ("ccbbcb") ++ (A) ++ ("cabacaabbc"))
    =
    (("baba") ++ (A) ++ ("cba") ++ (A) ++ ("accccbabcacaabcba") ++ (A) ++ ("bbbabbbaaacaacaaaccbbaccbbcbacab") ++ (A) ++ ("c") ++ (A) ++ ("abbc"));
constraint
  (("bbcccbbbbbbcabcbb") ++ (A) ++ ("aac") ++ (A) ++ (A) ++ ("c") ++ (A) ++ ("bba") ++ (A) ++ ("b") ++ (A) ++ ("bab") ++ (A) ++ ("acccccb") ++ (A) ++ ("c") ++ (A) ++ (A) ++ (A) ++ ("ab") ++ (A) ++ ("bcabb") ++ (A) ++ ("bbabcabac") ++ (A))
    =
    (("bbcccbbbbbbcabcbb") ++ (A) ++ ("a") ++ (A) ++ ("ca") ++ (A) ++ ("cabbaab") ++ (A) ++ ("baba") ++ (A) ++ ("cccccb") ++ (A) ++ ("caaaababcabbabb") ++ (A) ++ ("bcabac") ++ (A));
constraint
  (("bbc") ++ (A) ++ ("bccaba") ++ (A) ++ ("cbacbccaaabccbbbcaab") ++ (A) ++ ("acbccabcccccbacbc") ++ (A) ++ ("bbcbbccacccbbbbb"))
    =
    (("bbcabccab") ++ (A) ++ ("acbacbcc") ++ (A) ++ (A) ++ ("abccbbbc") ++ (A) ++ ("aba") ++ (A) ++ ("cbccabcccccb") ++ (A) ++ ("cbcabbcbbcc") ++ (A) ++ ("cccbbbbb"));
constraint
  (("cb") ++ (A) ++ ("b") ++ (A) ++ ("bbb") ++ (A) ++ (A) ++ ("a") ++ (A) ++ ("abcbbccabb") ++ (A) ++ ("ccacbcc") ++ (A) ++ ("c") ++ (A) ++ ("b") ++ (A) ++ ("aabbbac") ++ (A) ++ ("c") ++ (A) ++ ("abc") ++ (A) ++ ("ccb") ++ (A) ++ ("ccc") ++ (A) ++ ("acbac") ++ (A) ++ (A) ++ (A) ++ (A))
    =
    (("cbab") ++ (A) ++ ("bbb") ++ (A) ++ ("aa") ++ (A) ++ ("abcbbccabb") ++ (A) ++ ("ccacbccac") ++ (A) ++ ("b") ++ (A) ++ (A) ++ (A) ++ ("bbbac") ++ (A) ++ ("caabc") ++ (A) ++ ("ccbaccc") ++ (A) ++ ("acb") ++ (A) ++ ("c") ++ (A) ++ ("a") ++ (A) ++ (A));
constraint
  (("ccbacb") ++ (A) ++ ("cb") ++ (A) ++ (A) ++ ("cba") ++ (A) ++ (A) ++ ("cbcccb") ++ (A) ++ ("bbccaccabcbb") ++ (A) ++ ("cbbbbbb") ++ (A) ++ ("bccbc") ++ (A) ++ (A) ++ (A) ++ ("ccb") ++ (A) ++ ("cccbbabacb"))
    =
    (("ccb") ++ (A) ++ ("cbacba") ++ (A) ++ ("cb") ++ (A) ++ ("aacbcccbabbccacc") ++ (A) ++ ("bcbb") ++ (A) ++ ("cbbbbbbabccbc") ++ (A) ++ (A) ++ (A) ++ ("ccbacccbb") ++ (A) ++ ("b") ++ (A) ++ ("cb"));
constraint
  (("c") ++ (A) ++ ("abbc") ++ (A) ++ (A) ++ ("accb") ++ (A) ++ ("b") ++ (A) ++ ("bbbb") ++ (A) ++ ("cbbabbbba") ++ (A) ++ ("bcacbacbbcabbcacbbbcbc") ++ (A) ++ ("bbabbbbbabbbb"))
    =
    (("c") ++ (A) ++ ("abbca") ++ (A) ++ ("accbab") ++ (A) ++ ("bbbbacbb") ++ (A) ++ ("bbbb") ++ (A) ++ (A) ++ ("bcacbacbbcabbc") ++ (A) ++ ("cbbbcbcabbabbbbb") ++ (A) ++ ("bbbb"));
constraint
  (("cbbbbaccab") ++ (A) ++ ("cbbbccbbbccabccbabcbaabcccccaabcbabbbbc") ++ (A) ++ ("b") ++ (A) ++ ("c") ++ (A) ++ ("caaaaccbb") ++ (A) ++ ("b"))
    =
    (("cbbbb") ++ (A) ++ ("ccab") ++ (A) ++ ("cbbbccbbbccabccb") ++ (A) ++ ("bcb") ++ (A) ++ ("abcccccaabcbabbbbcabac") ++ (A) ++ ("c") ++ (A) ++ (A) ++ ("aaccbb") ++ (A) ++ ("b"));
constraint
  (("c") ++ (A) ++ (A) ++ (A) ++ ("ccbc") ++ (A) ++ ("b") ++ (A) ++ ("bcc") ++ (A) ++ (A) ++ ("ac") ++ (A) ++ ("cac") ++ (A) ++ ("a") ++ (A) ++ ("abccabcbb") ++ (A) ++ ("b") ++ (A) ++ ("cccaabbcc") ++ (A) ++ ("cccabaabbbbbbb") ++ (A) ++ ("bbba"))
    =
    (("c") ++ (A) ++ ("a") ++ (A) ++ ("ccbc") ++ (A) ++ ("b") ++ (A) ++ ("bcca") ++ (A) ++ (A) ++ ("c") ++ (A) ++ ("cacaaa") ++ (A) ++ ("bcc") ++ (A) ++ ("bcbbabaccca") ++ (A) ++ ("bbccaccc") ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("bbbbbbbabbb") ++ (A));
constraint
  (("bbcccccbbbababbab") ++ (A) ++ ("ac") ++ (A) ++ ("cca") ++ (A) ++ ("b") ++ (A) ++ ("bacbca") ++ (A) ++ ("bcccbabacbccbb") ++ (A) ++ ("acccc") ++ (A) ++ ("cccb") ++ (A) ++ ("cbbbcb"))
    =
    (("bbcccccbbbab") ++ (A) ++ ("bb") ++ (A) ++ ("b") ++ (A) ++ ("acacc") ++ (A) ++ (A) ++ ("b") ++ (A) ++ ("b") ++ (A) ++ ("cbca") ++ (A) ++ ("bcccbabacbccbb") ++ (A) ++ ("acccc") ++ (A) ++ ("cccbacbbbcb"));
constraint
  (("cc") ++ (A) ++ ("bbc") ++ (A) ++ ("cbcbbabbbab") ++ (A) ++ ("bbacbcbbabbbcbca") ++ (A) ++ ("cbb") ++ (A) ++ ("c") ++ (A) ++ ("c") ++ (A) ++ ("aabcc") ++ (A) ++ ("aa") ++ (A) ++ (A) ++ ("ccbcc") ++ (A) ++ ("bcc") ++ (A) ++ ("c") ++ (A))
    =
    (("ccabbc") ++ (A) ++ ("cbcbbabbb") ++ (A) ++ ("b") ++ (A) ++ ("bbacbcbbabbbcbca") ++ (A) ++ ("cbbac") ++ (A) ++ ("c") ++ (A) ++ ("aabccaaaa") ++ (A) ++ ("ccbcc") ++ (A) ++ ("bcc") ++ (A) ++ ("ca"));
constraint
  ((A) ++ ("bbc") ++ (A) ++ ("cccca") ++ (A) ++ ("bbcbabccbcac") ++ (A) ++ ("ca") ++ (A) ++ ("ba") ++ (A) ++ ("aabcbcccbbb") ++ (A) ++ ("bbbc") ++ (A) ++ ("cbbcc") ++ (A) ++ ("cab") ++ (A) ++ ("abcbbca") ++ (A) ++ ("b"))
    =
    ((A) ++ ("bbc") ++ (A) ++ ("ccccaabbcb") ++ (A) ++ ("bccbc") ++ (A) ++ ("caca") ++ (A) ++ ("b") ++ (A) ++ ("a") ++ (A) ++ ("abcbcccbbb") ++ (A) ++ ("bbbcacbbccacabaabcbbcaab"));
constraint
  (("c") ++ (A) ++ ("aaabbcca") ++ (A) ++ ("b") ++ (A) ++ ("aabcaacbb") ++ (A) ++ ("cb") ++ (A) ++ ("cccc") ++ (A) ++ ("bbcbcbcbbbcbbcab") ++ (A) ++ (A) ++ ("c") ++ (A) ++ (A) ++ (A) ++ (A) ++ ("bbbcccbbab") ++ (A) ++ ("b"))
    =
    (("c") ++ (A) ++ (A) ++ (A) ++ (A) ++ ("bbcca") ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("abcaacbb") ++ (A) ++ ("cb") ++ (A) ++ ("cccc") ++ (A) ++ ("bbcbcbcbbbcbbc") ++ (A) ++ ("ba") ++ (A) ++ ("caa") ++ (A) ++ ("abbbcccbb") ++ (A) ++ ("b") ++ (A) ++ ("b"));
constraint
  (("cccaca") ++ (A) ++ ("caaccabacbcbbcbacabb") ++ (A) ++ ("aa") ++ (A) ++ ("c") ++ (A) ++ ("cc") ++ (A) ++ ("acbbb") ++ (A) ++ ("ababcbcc") ++ (A) ++ ("bb") ++ (A) ++ ("abbcbaacb") ++ (A) ++ ("cb"))
    =
    (("ccc") ++ (A) ++ ("ca") ++ (A) ++ ("ca") ++ (A) ++ ("ccab") ++ (A) ++ ("cbcbbcb") ++ (A) ++ ("c") ++ (A) ++ ("bba") ++ (A) ++ ("a") ++ (A) ++ ("c") ++ (A) ++ ("cca") ++ (A) ++ ("cbbb") ++ (A) ++ (A) ++ ("babcbccabb") ++ (A) ++ ("abbcb") ++ (A) ++ ("acbacb"));
constraint
  (("cbacaaaacbbbccbbc") ++ (A) ++ (A) ++ (A) ++ ("cacbccbab") ++ (A) ++ ("b") ++ (A) ++ ("ccbaabccbbab") ++ (A) ++ ("cb") ++ (A) ++ ("cac") ++ (A) ++ (A) ++ ("cbbcbbbabbacc"))
    =
    (("cb") ++ (A) ++ ("c") ++ (A) ++ ("a") ++ (A) ++ ("acbbbccbbc") ++ (A) ++ ("a") ++ (A) ++ ("cacbccbababaccb") ++ (A) ++ (A) ++ ("bccbbabacb") ++ (A) ++ ("c") ++ (A) ++ ("caacbbcbbbabbacc"));
constraint
  (("b") ++ (A) ++ ("abbccbc") ++ (A) ++ ("cbaca") ++ (A) ++ ("c") ++ (A) ++ ("b") ++ (A) ++ (A) ++ (A) ++ ("ccbbbcccbccccb") ++ (A) ++ ("cabbacb") ++ (A) ++ ("aa") ++ (A) ++ ("bbbbcbc") ++ (A) ++ ("ca") ++ (A) ++ ("baacca") ++ (A))
    =
    (("baabbccbcacbacaac") ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("accbbbcccbccccb") ++ (A) ++ ("c") ++ (A) ++ ("bb") ++ (A) ++ ("cba") ++ (A) ++ (A) ++ ("abbbbcbc") ++ (A) ++ ("c") ++ (A) ++ (A) ++ ("baacc") ++ (A) ++ (A));
constraint
  (("bccbb") ++ (A) ++ ("bb") ++ (A) ++ (A) ++ ("aab") ++ (A) ++ ("c") ++ (A) ++ ("cacb") ++ (A) ++ ("baaac") ++ (A) ++ ("b") ++ (A) ++ ("cacbcc") ++ (A) ++ ("b") ++ (A) ++ ("c") ++ (A) ++ ("cccccaccb") ++ (A) ++ ("bcabc") ++ (A) ++ ("cc") ++ (A) ++ ("b") ++ (A) ++ ("c") ++ (A) ++ ("bbc"))
    =
    (("bccbb") ++ (A) ++ ("bb") ++ (A) ++ (A) ++ ("aab") ++ (A) ++ ("cacacbab") ++ (A) ++ ("a") ++ (A) ++ ("c") ++ (A) ++ ("bacacbccabacaccccc") ++ (A) ++ ("ccb") ++ (A) ++ ("bc") ++ (A) ++ ("bcaccabac") ++ (A) ++ ("bbc"));
constraint
  (("ab") ++ (A) ++ ("bccb") ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("ccbccbbbc") ++ (A) ++ ("acc") ++ (A) ++ ("a") ++ (A) ++ ("caacccbbcaccc") ++ (A) ++ ("bbcaabcbc") ++ (A) ++ ("cbb") ++ (A) ++ ("cbaac") ++ (A) ++ ("cbabb"))
    =
    ((A) ++ ("b") ++ (A) ++ ("bccb") ++ (A) ++ ("baaccbccbbbc") ++ (A) ++ ("acc") ++ (A) ++ (A) ++ (A) ++ ("c") ++ (A) ++ ("acccbbc") ++ (A) ++ ("ccc") ++ (A) ++ ("bbc") ++ (A) ++ (A) ++ ("bcbc") ++ (A) ++ ("cbbacba") ++ (A) ++ ("c") ++ (A) ++ ("cbabb"));
constraint
  (("cbbb") ++ (A) ++ ("c") ++ (A) ++ ("cbbabc") ++ (A) ++ (A) ++ ("acab") ++ (A) ++ ("abaa") ++ (A) ++ ("ccccbcb") ++ (A) ++ ("cbbcaca") ++ (A) ++ ("cccbbccaaa") ++ (A) ++ ("acac") ++ (A) ++ ("caaa") ++ (A) ++ ("bca") ++ (A))
    =
    (("cbbb") ++ (A) ++ ("cacbb") ++ (A) ++ ("bc") ++ (A) ++ (A) ++ (A) ++ ("cab") ++ (A) ++ (A) ++ ("b") ++ (A) ++ ("a") ++ (A) ++ ("ccccbcb") ++ (A) ++ ("cbbc") ++ (A) ++ ("c") ++ (A) ++ ("acccbbccaa") ++ (A) ++ (A) ++ (A) ++ ("c") ++ (A) ++ ("caca") ++ (A) ++ ("a") ++ (A) ++ ("bc") ++ (A) ++ (A));
constraint
  (("ccccbca") ++ (A) ++ ("a") ++ (A) ++ (A) ++ ("bbcaacabbcab") ++ (A) ++ ("ccb") ++ (A) ++ ("bb") ++ (A) ++ ("acbbaccc") ++ (A) ++ (A) ++ ("bccbbbcccccbbcbac") ++ (A) ++ ("c") ++ (A) ++ ("bacab"))
    =
    (("ccccbca") ++ (A) ++ (A) ++ (A) ++ ("abbcaacabbc") ++ (A) ++ ("baccbabba") ++ (A) ++ ("cbbaccc") ++ (A) ++ ("abccbbbcccccbbcb") ++ (A) ++ ("c") ++ (A) ++ ("c") ++ (A) ++ ("b") ++ (A) ++ ("cab"));
constraint
  (("b") ++ (A) ++ ("c") ++ (A) ++ ("cabbcbccbabcbb") ++ (A) ++ ("cbbbbcc") ++ (A) ++ ("cb") ++ (A) ++ ("a") ++ (A) ++ ("bcbcaabccbbcccbabb") ++ (A) ++ ("cccca") ++ (A) ++ ("aabcccb") ++ (A) ++ ("a"))
    =
    (("bacacabbcbccb") ++ (A) ++ ("bcbb") ++ (A) ++ ("cbbbbcc") ++ (A) ++ ("cbaa") ++ (A) ++ ("bcbcaabccbbcccbabb") ++ (A) ++ ("cccc") ++ (A) ++ (A) ++ (A) ++ (A) ++ ("bcccb") ++ (A) ++ (A));
constraint
  (("bcbbacaccaacabbbbaabcabca") ++ (A) ++ ("cbc") ++ (A) ++ ("ccbccbbcca") ++ (A) ++ ("bcc") ++ (A) ++ ("c") ++ (A) ++ ("bacbbabcb") ++ (A) ++ ("a") ++ (A) ++ ("ccacacc"))
    =
    (("bcbb") ++ (A) ++ ("c") ++ (A) ++ ("cc") ++ (A) ++ (A) ++ ("cabbbb") ++ (A) ++ ("abc") ++ (A) ++ ("bcaacbc") ++ (A) ++ ("ccbccbbcc") ++ (A) ++ (A) ++ ("bccac") ++ (A) ++ ("bacbbabcb") ++ (A) ++ ("a") ++ (A) ++ ("ccacacc"));
constraint
  (("bacccac") ++ (A) ++ ("cb") ++ (A) ++ ("bb") ++ (A) ++ (A) ++ ("b") ++ (A) ++ ("bbbccbcab") ++ (A) ++ ("cccbbbabccbbaacb") ++ (A) ++ (A) ++ ("bbaa") ++ (A) ++ (A) ++ (A) ++ ("ccbaabcbcc") ++ (A) ++ ("cbb"))
    =
    (("b") ++ (A) ++ ("cccacacb") ++ (A) ++ ("bb") ++ (A) ++ ("ababbbccbc") ++ (A) ++ ("bacccbbbabccbb") ++ (A) ++ ("acb") ++ (A) ++ ("abb") ++ (A) ++ ("a") ++ (A) ++ (A) ++ (A) ++ ("ccbaabcbccacbb"));
constraint
  (("c") ++ (A) ++ ("baac") ++ (A) ++ ("bb") ++ (A) ++ ("bc") ++ (A) ++ (A) ++ (A) ++ (A) ++ ("cacbbbc") ++ (A) ++ ("ccc") ++ (A) ++ ("cbba") ++ (A) ++ ("a") ++ (A) ++ ("aa") ++ (A) ++ ("bbcaccccbcc") ++ (A) ++ (A) ++ ("bbabcb") ++ (A) ++ (A) ++ ("cb") ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("c"))
    =
    (("cab") ++ (A) ++ ("ac") ++ (A) ++ ("bb") ++ (A) ++ ("bcaa") ++ (A) ++ ("ac") ++ (A) ++ ("cbbbcaccc") ++ (A) ++ ("cbb") ++ (A) ++ (A) ++ ("aaaaabbc") ++ (A) ++ ("ccccbcc") ++ (A) ++ ("abbabcb") ++ (A) ++ ("acbab") ++ (A) ++ (A) ++ ("c"));
constraint
  ((A) ++ (A) ++ ("cc") ++ (A) ++ ("b") ++ (A) ++ ("cbccaabbacaa") ++ (A) ++ ("b") ++ (A) ++ ("ba") ++ (A) ++ ("b") ++ (A) ++ ("cccba") ++ (A) ++ ("cabcacaacc") ++ (A) ++ ("bacaacc") ++ (A) ++ ("bcaabac") ++ (A) ++ ("aabbcc"))
    =
    ((A) ++ ("accab") ++ (A) ++ ("cbcca") ++ (A) ++ ("bbac") ++ (A) ++ (A) ++ ("ab") ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("bacccbaac") ++ (A) ++ ("bcac") ++ (A) ++ (A) ++ ("ccab") ++ (A) ++ ("caaccabc") ++ (A) ++ (A) ++ ("b") ++ (A) ++ ("c") ++ (A) ++ ("a") ++ (A) ++ ("bbcc"));
constraint
  (("bc") ++ (A) ++ ("cbc") ++ (A) ++ ("bbaccb") ++ (A) ++ ("cccbcaacbcbabbacccbbcbccbaabcbccccacbaacbcab") ++ (A) ++ ("cabbaab"))
    =
    (("bcacbc") ++ (A) ++ ("bb") ++ (A) ++ ("ccb") ++ (A) ++ ("cccbca") ++ (A) ++ ("cbcbabb") ++ (A) ++ ("cccbbcbccbaabcbccccacba") ++ (A) ++ ("cbcabacabb") ++ (A) ++ ("ab"));
constraint
  ((A) ++ ("cccbca") ++ (A) ++ ("c") ++ (A) ++ ("bac") ++ (A) ++ ("abacccbbcb") ++ (A) ++ (A) ++ ("a") ++ (A) ++ ("ccc") ++ (A) ++ ("ccbbc") ++ (A) ++ ("bbccb") ++ (A) ++ ("bbcacbccbcbaca") ++ (A) ++ ("ccbbc") ++ (A) ++ ("c"))
    =
    (("acccbcaacabacaab") ++ (A) ++ ("cccbbcb") ++ (A) ++ ("aa") ++ (A) ++ ("ccc") ++ (A) ++ ("ccbbcabbccbabbcacbccbcb") ++ (A) ++ ("caaccbbcac"));
constraint
  (("cc") ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("bcc") ++ (A) ++ ("babcc") ++ (A) ++ ("cbbcbbabbcbcbbc") ++ (A) ++ ("bbabbacac") ++ (A) ++ (A) ++ ("ccac") ++ (A) ++ ("cbbbaacbbbbbcbab") ++ (A) ++ (A))
    =
    (("cc") ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("bccab") ++ (A) ++ ("bcc") ++ (A) ++ ("cbbcbb") ++ (A) ++ ("bbcbcbbcabb") ++ (A) ++ ("bb") ++ (A) ++ ("cac") ++ (A) ++ (A) ++ ("ccacacbbbaacbbbbbcbab") ++ (A) ++ ("a"));
constraint
  (("abbbcc") ++ (A) ++ (A) ++ ("b") ++ (A) ++ ("ab") ++ (A) ++ ("aabb") ++ (A) ++ ("aabcacacbb") ++ (A) ++ ("ccccccbccc") ++ (A) ++ ("c") ++ (A) ++ (A) ++ ("bcbc") ++ (A) ++ ("ccaaccbbaabcc") ++ (A) ++ (A) ++ ("c") ++ (A) ++ ("a"))
    =
    (("abbbcc") ++ (A) ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("b") ++ (A) ++ (A) ++ (A) ++ ("bb") ++ (A) ++ ("aabc") ++ (A) ++ ("c") ++ (A) ++ ("cbbaccccccbccc") ++ (A) ++ ("ca") ++ (A) ++ ("bcbcacc") ++ (A) ++ (A) ++ ("ccbb") ++ (A) ++ (A) ++ ("bcc") ++ (A) ++ (A) ++ ("ca") ++ (A));
constraint
  ((A) ++ ("cacbcbbccccc") ++ (A) ++ ("abcacbbacb") ++ (A) ++ ("cbbbcaacbcbcbc") ++ (A) ++ ("bacccacbbbcbabbbabccccbacb"))
    =
    ((A) ++ ("cacbcbbccccca") ++ (A) ++ ("bc") ++ (A) ++ ("cbbacbacbbbc") ++ (A) ++ ("acbcbcbc") ++ (A) ++ ("b") ++ (A) ++ ("ccc") ++ (A) ++ ("cbbbcb") ++ (A) ++ ("bbb") ++ (A) ++ ("bccccbacb"));
constraint
  (("bab") ++ (A) ++ ("bbcba") ++ (A) ++ (A) ++ ("bbabbbab") ++ (A) ++ ("bbcbcbbcbccbcc") ++ (A) ++ ("bcccabbbb") ++ (A) ++ ("caa") ++ (A) ++ ("b") ++ (A) ++ ("bbbaacbbaa") ++ (A) ++ (A) ++ (A) ++ ("bb"))
    =
    (("b") ++ (A) ++ ("babbcbaa") ++ (A) ++ ("bb") ++ (A) ++ ("bbbab") ++ (A) ++ ("bbcbcbbcbccbccabcccabbbbac") ++ (A) ++ (A) ++ (A) ++ ("b") ++ (A) ++ ("bbb") ++ (A) ++ ("acbba") ++ (A) ++ ("aa") ++ (A) ++ ("bb"));
constraint
  (("abccb") ++ (A) ++ ("cc") ++ (A) ++ ("a") ++ (A) ++ (A) ++ ("cbc") ++ (A) ++ ("babccbc") ++ (A) ++ ("ccbabbc") ++ (A) ++ ("acc") ++ (A) ++ ("bcaabbcabb") ++ (A) ++ (A) ++ ("cbccbb") ++ (A) ++ ("b") ++ (A) ++ ("baacbbcbc"))
    =
    (("abccbacc") ++ (A) ++ (A) ++ (A) ++ ("acbc") ++ (A) ++ ("babccbcaccb") ++ (A) ++ ("bbcaaccabcaabbcabb") ++ (A) ++ (A) ++ ("cbccbb") ++ (A) ++ ("b") ++ (A) ++ ("baacbbcbc"));
constraint
  (("c") ++ (A) ++ ("c") ++ (A) ++ ("ca") ++ (A) ++ ("ba") ++ (A) ++ ("b") ++ (A) ++ ("babbbb") ++ (A) ++ ("b") ++ (A) ++ ("ccbbcaacc") ++ (A) ++ ("cbabbabcb") ++ (A) ++ ("ba") ++ (A) ++ ("bbbbcccbcccaa") ++ (A) ++ (A) ++ ("ccbbc") ++ (A) ++ ("a"))
    =
    (("c") ++ (A) ++ ("c") ++ (A) ++ ("ca") ++ (A) ++ ("baabababbbbab") ++ (A) ++ ("ccbbc") ++ (A) ++ ("acc") ++ (A) ++ ("cbabbabcb") ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("bbbbcccbccc") ++ (A) ++ ("a") ++ (A) ++ ("accbbc") ++ (A) ++ (A));
constraint
  (("cbacaccbb") ++ (A) ++ (A) ++ ("bacacccbbbb") ++ (A) ++ ("bccbbca") ++ (A) ++ (A) ++ ("babbc") ++ (A) ++ ("bbb") ++ (A) ++ ("c") ++ (A) ++ ("c") ++ (A) ++ ("abac") ++ (A) ++ ("bccca") ++ (A) ++ ("abaacbcac"))
    =
    (("cbacaccbb") ++ (A) ++ (A) ++ ("b") ++ (A) ++ ("c") ++ (A) ++ ("cccbbbb") ++ (A) ++ ("bccbbcaa") ++ (A) ++ ("b") ++ (A) ++ ("bbc") ++ (A) ++ ("bbb") ++ (A) ++ ("cac") ++ (A) ++ ("ab") ++ (A) ++ ("cabccc") ++ (A) ++ (A) ++ (A) ++ ("baacbcac"));
constraint
  (("bcbaac") ++ (A) ++ ("c") ++ (A) ++ ("cccccaabccbabaabcbbacc") ++ (A) ++ ("cabbcbccccb") ++ (A) ++ ("bba") ++ (A) ++ ("cb") ++ (A) ++ ("caccbccbbbcc") ++ (A) ++ ("bc"))
    =
    (("bcba") ++ (A) ++ ("c") ++ (A) ++ ("c") ++ (A) ++ ("cccccaabccb") ++ (A) ++ ("b") ++ (A) ++ ("abcbb") ++ (A) ++ ("ccacabbcbccccb") ++ (A) ++ ("bbaacbacaccbccbbbcc") ++ (A) ++ ("bc"));
constraint
  ((A) ++ ("bba") ++ (A) ++ ("acbbabb") ++ (A) ++ (A) ++ ("b") ++ (A) ++ ("baa") ++ (A) ++ ("b") ++ (A) ++ ("ccba") ++ (A) ++ ("acbcca") ++ (A) ++ ("bccc") ++ (A) ++ ("bcacbaabc") ++ (A) ++ ("bbbbcacbc") ++ (A) ++ ("ccacaac"))
    =
    (("abbaa") ++ (A) ++ ("cbbabb") ++ (A) ++ ("ab") ++ (A) ++ ("b") ++ (A) ++ (A) ++ (A) ++ ("baccb") ++ (A) ++ ("a") ++ (A) ++ ("cbcca") ++ (A) ++ ("bcccabcacb") ++ (A) ++ (A) ++ ("bcabbbbcacbc") ++ (A) ++ ("cc") ++ (A) ++ ("c") ++ (A) ++ ("ac"));
constraint
  (("bbbccccb") ++ (A) ++ ("babcb") ++ (A) ++ (A) ++ ("cb") ++ (A) ++ (A) ++ ("ccaccbcbc") ++ (A) ++ ("accbbc") ++ (A) ++ ("baaabcbbc") ++ (A) ++ ("a") ++ (A) ++ ("ab") ++ (A) ++ (A) ++ (A) ++ (A) ++ ("acbbaabaac") ++ (A))
    =
    (("bbbccccb") ++ (A) ++ ("b") ++ (A) ++ ("bcba") ++ (A) ++ ("cba") ++ (A) ++ ("ccaccbcbca") ++ (A) ++ ("ccbbcab") ++ (A) ++ ("aabcbbca") ++ (A) ++ ("a") ++ (A) ++ ("baaa") ++ (A) ++ (A) ++ ("cbba") ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("c") ++ (A));
constraint
  ((A) ++ (A) ++ ("bcb") ++ (A) ++ ("ccacbabbbcaaaa") ++ (A) ++ ("ababbc") ++ (A) ++ ("bbbaaa") ++ (A) ++ (A) ++ ("ccbbb") ++ (A) ++ ("bbb") ++ (A) ++ ("bbbcccbcc") ++ (A) ++ ("b") ++ (A) ++ ("bccababa"))
    =
    ((A) ++ (A) ++ ("bcbacc") ++ (A) ++ ("cb") ++ (A) ++ ("bbbcaa") ++ (A) ++ ("aaab") ++ (A) ++ ("bbcabbba") ++ (A) ++ ("aaaccbbbabbbabbbcccbcc") ++ (A) ++ ("b") ++ (A) ++ ("bccabab") ++ (A));
constraint
  (("cbb") ++ (A) ++ ("cc") ++ (A) ++ ("bccba") ++ (A) ++ ("a") ++ (A) ++ ("bcc") ++ (A) ++ ("ab") ++ (A) ++ (A) ++ ("acbcccacccb") ++ (A) ++ ("aacabcbccba") ++ (A) ++ (A) ++ ("cbcbababbaa") ++ (A) ++ ("b") ++ (A) ++ ("bacc"))
    =
    (("cbbacc") ++ (A) ++ ("bccbaaa") ++ (A) ++ ("bcc") ++ (A) ++ ("aba") ++ (A) ++ ("acbccc") ++ (A) ++ ("cccba") ++ (A) ++ ("acabcbccba") ++ (A) ++ (A) ++ ("cbcb") ++ (A) ++ ("babb") ++ (A) ++ ("a") ++ (A) ++ ("babacc"));
constraint
  (("c") ++ (A) ++ ("c") ++ (A) ++ ("ccaabacabb") ++ (A) ++ ("cbcbb") ++ (A) ++ (A) ++ ("b") ++ (A) ++ ("bbbcbc") ++ (A) ++ (A) ++ (A) ++ ("abaabcabccb") ++ (A) ++ ("bbca") ++ (A) ++ ("a") ++ (A) ++ ("c") ++ (A) ++ ("cbab") ++ (A) ++ ("bcb") ++ (A) ++ ("aaa"))
    =
    (("c") ++ (A) ++ ("c") ++ (A) ++ ("cca") ++ (A) ++ ("bacabb") ++ (A) ++ ("cbcbb") ++ (A) ++ ("ababbbcbcaa") ++ (A) ++ ("aba") ++ (A) ++ ("bc") ++ (A) ++ ("bccbabbc") ++ (A) ++ (A) ++ ("a") ++ (A) ++ ("c") ++ (A) ++ ("cb") ++ (A) ++ ("b") ++ (A) ++ ("bcbaa") ++ (A) ++ (A));
constraint
  (("a") ++ (A) ++ ("ccabca") ++ (A) ++ (A) ++ ("bbbbbcab") ++ (A) ++ ("a") ++ (A) ++ ("bbbbbcbaabb") ++ (A) ++ ("bcbab") ++ (A) ++ ("accb") ++ (A) ++ ("aaccbc") ++ (A) ++ ("ccbcccbbbb") ++ (A) ++ ("b") ++ (A) ++ ("bc"))
    =
    (("a") ++ (A) ++ ("ccabca") ++ (A) ++ ("abbbbbc") ++ (A) ++ ("ba") ++ (A) ++ (A) ++ ("bbbbbcb") ++ (A) ++ ("abbabcbabaaccba") ++ (A) ++ ("accbcaccbcccbbbbab") ++ (A) ++ ("bc"));
constraint
  (("babccabc") ++ (A) ++ ("babaabc") ++ (A) ++ ("ba") ++ (A) ++ ("abcbc") ++ (A) ++ ("ba") ++ (A) ++ ("a") ++ (A) ++ ("bcbcbc") ++ (A) ++ ("bcbc") ++ (A) ++ ("bac") ++ (A) ++ ("ca") ++ (A) ++ ("cca") ++ (A) ++ ("bcbcbbcbbbba"))
    =
    (("b") ++ (A) ++ ("bccabc") ++ (A) ++ ("b") ++ (A) ++ ("b") ++ (A) ++ ("abc") ++ (A) ++ ("baa") ++ (A) ++ ("bcbcab") ++ (A) ++ (A) ++ ("aabcbcbcabcbcabac") ++ (A) ++ ("c") ++ (A) ++ (A) ++ ("cca") ++ (A) ++ ("bcbcbbcbbbb") ++ (A));
constraint
  (("ccbacbbbca") ++ (A) ++ ("bb") ++ (A) ++ ("ccbaac") ++ (A) ++ ("bbbc") ++ (A) ++ ("b") ++ (A) ++ ("bbcbb") ++ (A) ++ ("bbccaacacbc") ++ (A) ++ ("cacccaa") ++ (A) ++ ("ccbcbcccab") ++ (A) ++ ("b"))
    =
    (("ccbacbbbca") ++ (A) ++ ("bb") ++ (A) ++ ("ccb") ++ (A) ++ ("ac") ++ (A) ++ ("bbbcab") ++ (A) ++ ("bbcbb") ++ (A) ++ ("bbcc") ++ (A) ++ ("ac") ++ (A) ++ ("cbcacacccaaaccbcbcccab") ++ (A) ++ ("b"));
constraint
  ((A) ++ (A) ++ ("a") ++ (A) ++ ("ba") ++ (A) ++ ("babbcbbbcbac") ++ (A) ++ ("b") ++ (A) ++ ("ab") ++ (A) ++ ("bacc") ++ (A) ++ ("b") ++ (A) ++ ("ccbcb") ++ (A) ++ ("bcca") ++ (A) ++ (A) ++ ("cc") ++ (A) ++ (A) ++ ("acabaabacc") ++ (A) ++ (A) ++ (A) ++ ("acaca"))
    =
    ((A) ++ ("a") ++ (A) ++ ("aba") ++ (A) ++ ("b") ++ (A) ++ ("bbcbbbcbacabaab") ++ (A) ++ ("bacc") ++ (A) ++ ("baccbcbabcc") ++ (A) ++ (A) ++ (A) ++ ("cc") ++ (A) ++ (A) ++ (A) ++ ("c") ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("bacca") ++ (A) ++ ("a") ++ (A) ++ ("c") ++ (A) ++ ("ca"));
constraint
  ((A) ++ ("cacbbaccbcbc") ++ (A) ++ (A) ++ ("cbbccaba") ++ (A) ++ ("abacccbccbbbcccc") ++ (A) ++ ("bbbcbbbbac") ++ (A) ++ ("ccb") ++ (A) ++ (A) ++ (A) ++ ("bac") ++ (A) ++ ("cbaa"))
    =
    (("acacbb") ++ (A) ++ ("ccbcbca") ++ (A) ++ ("cbbcc") ++ (A) ++ ("b") ++ (A) ++ ("aabacccbccbbbccccabbbcbbbbacaccbaa") ++ (A) ++ ("bacacb") ++ (A) ++ ("a"));
constraint
  ((A) ++ ("bbbcbcbcbc") ++ (A) ++ (A) ++ ("acb") ++ (A) ++ ("ab") ++ (A) ++ ("ccac") ++ (A) ++ ("bbbcacc") ++ (A) ++ ("bbaccbbccbcabbc") ++ (A) ++ ("cbbcbcbbbba") ++ (A) ++ (A) ++ ("bbca"))
    =
    ((A) ++ ("bbbcbcbcbca") ++ (A) ++ (A) ++ ("cbaab") ++ (A) ++ ("ccac") ++ (A) ++ ("bbbc") ++ (A) ++ ("ccabbaccbbccbc") ++ (A) ++ ("bbcacbbcbcbbbba") ++ (A) ++ ("abbca"));
constraint
  ((A) ++ (A) ++ ("ccbaa") ++ (A) ++ ("acbbc") ++ (A) ++ ("b") ++ (A) ++ ("bc") ++ (A) ++ ("cb") ++ (A) ++ ("bbac") ++ (A) ++ ("acbc") ++ (A) ++ ("cb") ++ (A) ++ ("bccba") ++ (A) ++ ("cbccb") ++ (A) ++ ("c") ++ (A) ++ ("aab") ++ (A) ++ (A) ++ ("cbcaa") ++ (A) ++ ("ccac") ++ (A) ++ ("c"))
    =
    ((A) ++ (A) ++ ("ccba") ++ (A) ++ (A) ++ ("acbbcab") ++ (A) ++ ("bcacbabbac") ++ (A) ++ (A) ++ ("cbc") ++ (A) ++ ("cb") ++ (A) ++ ("bccbaacbccb") ++ (A) ++ ("c") ++ (A) ++ ("a") ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("cbcaa") ++ (A) ++ ("cc") ++ (A) ++ ("c") ++ (A) ++ ("c"));
constraint
  (("bc") ++ (A) ++ (A) ++ ("bccbcbbbba") ++ (A) ++ ("bbbababcacaac") ++ (A) ++ (A) ++ ("cacccbcccc") ++ (A) ++ ("cbcbbcccc") ++ (A) ++ ("ccaccbbbabbbbca"))
    =
    (("bca") ++ (A) ++ ("bccbcbbbb") ++ (A) ++ ("abbb") ++ (A) ++ ("babc") ++ (A) ++ ("ca") ++ (A) ++ ("caac") ++ (A) ++ ("cccbccccacbcbbcccc") ++ (A) ++ ("ccaccbbb") ++ (A) ++ ("bbbbc") ++ (A));
constraint
  (("bccbbccc") ++ (A) ++ ("bcc") ++ (A) ++ ("cc") ++ (A) ++ (A) ++ (A) ++ ("ccc") ++ (A) ++ ("cbbcccbccababc") ++ (A) ++ ("cc") ++ (A) ++ ("accccb") ++ (A) ++ (A) ++ ("bcbccccc") ++ (A) ++ ("bbbcbcc") ++ (A) ++ ("c"))
    =
    (("bccbbccc") ++ (A) ++ ("bcc") ++ (A) ++ ("cc") ++ (A) ++ (A) ++ (A) ++ ("ccc") ++ (A) ++ ("cbbcccbccab") ++ (A) ++ ("bcacc") ++ (A) ++ (A) ++ ("ccccba") ++ (A) ++ ("bcbcccccabbbcbcc") ++ (A) ++ ("c"));
constraint
  (("bc") ++ (A) ++ ("bbc") ++ (A) ++ ("accca") ++ (A) ++ ("bcbbcbc") ++ (A) ++ ("cab") ++ (A) ++ (A) ++ (A) ++ ("bab") ++ (A) ++ ("babcbcccbcbacabbb") ++ (A) ++ ("bb") ++ (A) ++ ("ca") ++ (A) ++ ("acbbbac") ++ (A) ++ (A) ++ (A) ++ ("a"))
    =
    (("bcabbc") ++ (A) ++ ("acccaabcbbcbcacaba") ++ (A) ++ ("ab") ++ (A) ++ ("bababcbcccbcbacabbb") ++ (A) ++ ("bb") ++ (A) ++ ("ca") ++ (A) ++ (A) ++ ("cbbbac") ++ (A) ++ (A) ++ (A) ++ (A));
constraint
  ((A) ++ ("abcbccbacacb") ++ (A) ++ ("bccbbbbccbcbcccbbcba") ++ (A) ++ ("ccbc") ++ (A) ++ ("abcaabaacb") ++ (A) ++ (A) ++ (A) ++ ("ccbb") ++ (A) ++ ("aacbccbb"))
    =
    ((A) ++ (A) ++ ("bcbccbac") ++ (A) ++ ("cb") ++ (A) ++ ("bccbbbbccbcbcccbbcba") ++ (A) ++ ("ccbcaabc") ++ (A) ++ (A) ++ ("baacbaaaccbb") ++ (A) ++ ("a") ++ (A) ++ ("cbccbb"));
constraint
  (("ccacbbcccbacb") ++ (A) ++ ("accccbaa") ++ (A) ++ (A) ++ ("cbccbbbacabab") ++ (A) ++ ("ab") ++ (A) ++ ("cacb") ++ (A) ++ ("cabbbb") ++ (A) ++ ("bba") ++ (A) ++ ("acc") ++ (A) ++ ("aabc") ++ (A))
    =
    (("ccacbbcccbacba") ++ (A) ++ ("ccccb") ++ (A) ++ (A) ++ (A) ++ ("acbccbbbac") ++ (A) ++ ("baba") ++ (A) ++ ("b") ++ (A) ++ ("c") ++ (A) ++ ("cb") ++ (A) ++ ("cabbbb") ++ (A) ++ ("bbaaacca") ++ (A) ++ (A) ++ ("bca"));
constraint
  ((A) ++ ("b") ++ (A) ++ ("bc") ++ (A) ++ ("ac") ++ (A) ++ (A) ++ ("ccaabcbacb") ++ (A) ++ ("abb") ++ (A) ++ ("bcccab") ++ (A) ++ (A) ++ (A) ++ (A) ++ (A) ++ (A) ++ ("aaacbcccbbcbaca") ++ (A) ++ ("ccccbc") ++ (A) ++ ("bbc") ++ (A) ++ ("b") ++ (A))
    =
    (("ababcaaca") ++ (A) ++ ("cca") ++ (A) ++ ("bcb") ++ (A) ++ ("cb") ++ (A) ++ ("abbabcccabaaa") ++ (A) ++ ("a") ++ (A) ++ ("aa") ++ (A) ++ ("cbcccbbcbac") ++ (A) ++ (A) ++ ("ccccbcabbc") ++ (A) ++ ("ba"));
constraint
  ((A) ++ (A) ++ (A) ++ ("cabccbcbccc") ++ (A) ++ ("babcc") ++ (A) ++ ("abbcc") ++ (A) ++ ("bcbca") ++ (A) ++ ("bcb") ++ (A) ++ ("aaaccabbbbcab") ++ (A) ++ ("baaacbcabba") ++ (A) ++ ("cab"))
    =
    (("a") ++ (A) ++ (A) ++ ("cabccbcbcccababcca") ++ (A) ++ ("bbcc") ++ (A) ++ ("bcbc") ++ (A) ++ (A) ++ ("bcb") ++ (A) ++ (A) ++ ("aacc") ++ (A) ++ ("bbbbc") ++ (A) ++ ("bab") ++ (A) ++ ("a") ++ (A) ++ ("cbc") ++ (A) ++ ("bb") ++ (A) ++ (A) ++ ("cab"));
constraint
  (("ba") ++ (A) ++ ("cabcb") ++ (A) ++ ("cbbccbccbacccabb") ++ (A) ++ ("cc") ++ (A) ++ ("ccbbaac") ++ (A) ++ ("cbaaccbbb") ++ (A) ++ ("ccbcccabacb") ++ (A) ++ ("cacccba"))
    =
    (("baacabcb") ++ (A) ++ ("cbbccbccbaccc") ++ (A) ++ ("bbaccaccbba") ++ (A) ++ ("cacb") ++ (A) ++ ("accbbb") ++ (A) ++ ("ccbcccab") ++ (A) ++ ("cbac") ++ (A) ++ ("cccba"));
constraint
  ((A) ++ ("bbcaabbb") ++ (A) ++ ("acb") ++ (A) ++ ("b") ++ (A) ++ ("ba") ++ (A) ++ ("aaccbbc") ++ (A) ++ ("aabba") ++ (A) ++ ("bcc") ++ (A) ++ (A) ++ ("ccabcacacc") ++ (A) ++ (A) ++ ("bac") ++ (A) ++ ("cbbccccccbab"))
    =
    ((A) ++ ("bbcaabbbaacbab") ++ (A) ++ ("b") ++ (A) ++ ("a") ++ (A) ++ (A) ++ ("ccbbcaaabb") ++ (A) ++ (A) ++ ("bcc") ++ (A) ++ (A) ++ ("cc") ++ (A) ++ ("bc") ++ (A) ++ ("cacc") ++ (A) ++ ("abacacbbccccccb") ++ (A) ++ ("b"));
constraint
  (("abbabb") ++ (A) ++ ("b") ++ (A) ++ ("a") ++ (A) ++ ("bbba") ++ (A) ++ ("cbabcbaccbcc") ++ (A) ++ ("ccacbccbbaaca") ++ (A) ++ ("c") ++ (A) ++ ("baabccc") ++ (A) ++ ("c") ++ (A) ++ ("c") ++ (A) ++ ("cbbccacc") ++ (A))
    =
    ((A) ++ ("bbabbab") ++ (A) ++ ("aabbb") ++ (A) ++ ("acb") ++ (A) ++ ("bcb") ++ (A) ++ ("ccbcc") ++ (A) ++ ("cc") ++ (A) ++ ("cbccbb") ++ (A) ++ (A) ++ ("caac") ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("bcccacacacbbcc") ++ (A) ++ ("cca"));
constraint
  (("ccabaccbbb") ++ (A) ++ ("cbcccbcb") ++ (A) ++ (A) ++ ("abb") ++ (A) ++ ("bbbbcbbcb") ++ (A) ++ ("bcc") ++ (A) ++ (A) ++ (A) ++ (A) ++ ("bcbbbabbca") ++ (A) ++ ("cab") ++ (A) ++ ("cbbcccbbb"))
    =
    (("ccab") ++ (A) ++ ("ccbbb") ++ (A) ++ ("cbcccbcb") ++ (A) ++ (A) ++ (A) ++ ("bb") ++ (A) ++ ("bbbbcbbcb") ++ (A) ++ ("bcc") ++ (A) ++ (A) ++ ("aabcbbb") ++ (A) ++ ("bbc") ++ (A) ++ ("ac") ++ (A) ++ ("b") ++ (A) ++ ("cbbcccbbb"));
constraint
  (("b") ++ (A) ++ ("ca") ++ (A) ++ ("ab") ++ (A) ++ ("ababcb") ++ (A) ++ (A) ++ ("cbcacaacbcbbacbacaccb") ++ (A) ++ ("aa") ++ (A) ++ ("bb") ++ (A) ++ ("abcc") ++ (A) ++ ("abacc") ++ (A) ++ ("c") ++ (A) ++ ("bcc") ++ (A) ++ ("c") ++ (A) ++ ("bbc"))
    =
    (("b") ++ (A) ++ ("ca") ++ (A) ++ (A) ++ ("baababcba") ++ (A) ++ ("cbcac") ++ (A) ++ ("acbcbbacb") ++ (A) ++ ("c") ++ (A) ++ ("ccbaaaabba") ++ (A) ++ ("bcc") ++ (A) ++ ("ab") ++ (A) ++ ("cc") ++ (A) ++ ("cabcc") ++ (A) ++ ("cabbc"));
constraint
  (("cbb") ++ (A) ++ ("cbb") ++ (A) ++ ("cb") ++ (A) ++ (A) ++ ("bbcccc") ++ (A) ++ ("cbbbcaabaccbaacbcccbbbbbbcaa") ++ (A) ++ (A) ++ (A) ++ ("acbcca") ++ (A) ++ ("cac") ++ (A) ++ ("bcb") ++ (A) ++ (A))
    =
    (("cbbacbb") ++ (A) ++ ("cb") ++ (A) ++ ("abbcccc") ++ (A) ++ ("cbbbcaab") ++ (A) ++ ("ccbaacbcccbbbbbbca") ++ (A) ++ (A) ++ ("aaacbcc") ++ (A) ++ (A) ++ ("cac") ++ (A) ++ ("bcb") ++ (A) ++ (A));
constraint
  (("bcabccbcbbaccabcbca") ++ (A) ++ ("bacccaacbacaccc") ++ (A) ++ ("caa") ++ (A) ++ ("bcccaa") ++ (A) ++ ("bcb") ++ (A) ++ ("abbcb") ++ (A) ++ ("bc") ++ (A) ++ (A) ++ (A) ++ ("cccc"))
    =
    (("bc") ++ (A) ++ ("bccbcbb") ++ (A) ++ ("ccabcbcaab") ++ (A) ++ ("ccc") ++ (A) ++ ("acb") ++ (A) ++ ("caccc") ++ (A) ++ ("ca") ++ (A) ++ ("abcccaa") ++ (A) ++ ("bcb") ++ (A) ++ (A) ++ ("bbcb") ++ (A) ++ ("bca") ++ (A) ++ (A) ++ ("cccc"));
constraint
  (("c") ++ (A) ++ ("cccababbbcb") ++ (A) ++ ("cac") ++ (A) ++ ("cccbcbabbc") ++ (A) ++ (A) ++ ("cabbbbaccabbbbcacbbbbcaabc") ++ (A) ++ (A) ++ ("ca") ++ (A) ++ ("baacc"))
    =
    (("cacccab") ++ (A) ++ ("bbbcb") ++ (A) ++ ("c") ++ (A) ++ ("cacccbcbabbc") ++ (A) ++ ("acabbbbacc") ++ (A) ++ ("bbbbc") ++ (A) ++ ("cbbbbca") ++ (A) ++ ("bcaaca") ++ (A) ++ ("baacc"));
constraint
  (("c") ++ (A) ++ ("caacabbc") ++ (A) ++ ("babcbcb") ++ (A) ++ ("baaabccab") ++ (A) ++ ("bbbccaccbc") ++ (A) ++ ("abca") ++ (A) ++ ("cbabcb") ++ (A) ++ ("bbc") ++ (A) ++ ("b") ++ (A) ++ ("bbbbbacc"))
    =
    (("cac") ++ (A) ++ (A) ++ ("cabbc") ++ (A) ++ ("b") ++ (A) ++ ("bcbcbabaa") ++ (A) ++ ("bccababbbcc") ++ (A) ++ ("ccbcaabca") ++ (A) ++ ("cb") ++ (A) ++ ("bcbabbc") ++ (A) ++ ("b") ++ (A) ++ ("bbbbbacc"));
constraint
  (("b") ++ (A) ++ ("ccccb") ++ (A) ++ ("b") ++ (A) ++ ("ccccb") ++ (A) ++ ("a") ++ (A) ++ ("bbabbbbcccccc") ++ (A) ++ ("bbbcabccbbcc") ++ (A) ++ ("a") ++ (A) ++ ("cbaccbbc") ++ (A) ++ ("baaacbbcbb"))
    =
    (("b") ++ (A) ++ ("ccccbab") ++ (A) ++ ("ccccba") ++ (A) ++ ("abbabbbbccccccabbbcabccbbcc") ++ (A) ++ ("a") ++ (A) ++ ("cb") ++ (A) ++ ("ccbbc") ++ (A) ++ ("b") ++ (A) ++ ("aacbbcbb"));
constraint
  (("cabcab") ++ (A) ++ ("acb") ++ (A) ++ (A) ++ ("bccc") ++ (A) ++ ("bbbcaba") ++ (A) ++ ("bcca") ++ (A) ++ ("cc") ++ (A) ++ (A) ++ (A) ++ ("baaa") ++ (A) ++ ("bb") ++ (A) ++ ("a") ++ (A) ++ ("c") ++ (A) ++ ("bcbcb") ++ (A) ++ ("bababcabbbcbb"))
    =
    (("cabcabaacb") ++ (A) ++ (A) ++ ("bccc") ++ (A) ++ ("bbbc") ++ (A) ++ ("b") ++ (A) ++ ("abcc") ++ (A) ++ (A) ++ ("cc") ++ (A) ++ (A) ++ ("ab") ++ (A) ++ (A) ++ ("aabba") ++ (A) ++ ("acabcbcb") ++ (A) ++ ("bab") ++ (A) ++ ("bcabbbcbb"));
constraint
  (("bb") ++ (A) ++ ("bbac") ++ (A) ++ ("c") ++ (A) ++ ("ccbb") ++ (A) ++ ("cabbbccbabcac") ++ (A) ++ (A) ++ ("bb") ++ (A) ++ ("ccc") ++ (A) ++ ("ac") ++ (A) ++ ("bbbbb") ++ (A) ++ ("baa") ++ (A) ++ (A) ++ ("bca") ++ (A) ++ ("aaa") ++ (A) ++ ("cacc") ++ (A) ++ ("cc"))
    =
    (("bbabbac") ++ (A) ++ ("c") ++ (A) ++ ("ccbbacabbbccb") ++ (A) ++ ("bcac") ++ (A) ++ (A) ++ ("bb") ++ (A) ++ ("ccc") ++ (A) ++ (A) ++ ("c") ++ (A) ++ ("bbbbbabaaa") ++ (A) ++ ("bc") ++ (A) ++ (A) ++ (A) ++ ("a") ++ (A) ++ (A) ++ ("cacc") ++ (A) ++ ("cc"));
constraint
  (("acbcbbcacb") ++ (A) ++ ("abc") ++ (A) ++ ("bccc") ++ (A) ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("c") ++ (A) ++ ("bcccaaccabbccabb") ++ (A) ++ ("c") ++ (A) ++ ("bba") ++ (A) ++ (A) ++ ("bbbacbacbabc") ++ (A) ++ (A) ++ ("cc"))
    =
    ((A) ++ ("cbcbbcacb") ++ (A) ++ (A) ++ ("bc") ++ (A) ++ ("bcccaab") ++ (A) ++ ("acabccc") ++ (A) ++ (A) ++ ("ccabbcc") ++ (A) ++ ("bb") ++ (A) ++ ("cabb") ++ (A) ++ ("aabbb") ++ (A) ++ ("cb") ++ (A) ++ ("cb") ++ (A) ++ ("bca") ++ (A) ++ ("cc"));
constraint
  (("bbcaaccac") ++ (A) ++ ("b") ++ (A) ++ ("cac") ++ (A) ++ ("babaabcaccc") ++ (A) ++ ("cb") ++ (A) ++ (A) ++ (A) ++ ("ab") ++ (A) ++ ("a") ++ (A) ++ (A) ++ ("cbab") ++ (A) ++ ("cc") ++ (A) ++ ("bb") ++ (A) ++ (A) ++ ("bbbcb") ++ (A) ++ ("baccb") ++ (A) ++ ("aba"))
    =
    (("bbc") ++ (A) ++ ("accac") ++ (A) ++ ("bacacabab") ++ (A) ++ ("abc") ++ (A) ++ ("ccc") ++ (A) ++ ("cb") ++ (A) ++ ("a") ++ (A) ++ (A) ++ ("baaaacb") ++ (A) ++ ("baccabb") ++ (A) ++ ("abbbcbabaccb") ++ (A) ++ (A) ++ ("ba"));
constraint
  (("babb") ++ (A) ++ ("cbbbcababb") ++ (A) ++ ("b") ++ (A) ++ ("acb") ++ (A) ++ ("cacba") ++ (A) ++ ("abccc") ++ (A) ++ (A) ++ ("cbbcbb") ++ (A) ++ ("ccbcaca") ++ (A) ++ ("a") ++ (A) ++ (A) ++ ("ac") ++ (A) ++ ("cabcccbcbb"))
    =
    (("babbacbbbc") ++ (A) ++ ("b") ++ (A) ++ ("bb") ++ (A) ++ ("b") ++ (A) ++ ("acbacacb") ++ (A) ++ (A) ++ ("abccca") ++ (A) ++ ("cbbcbb") ++ (A) ++ ("ccbcaca") ++ (A) ++ ("a") ++ (A) ++ ("aac") ++ (A) ++ ("c") ++ (A) ++ ("bcccbcbb"));
constraint
  (("bbccb") ++ (A) ++ ("b") ++ (A) ++ ("bbb") ++ (A) ++ (A) ++ (A) ++ ("cca") ++ (A) ++ (A) ++ ("bccccbabcbcba") ++ (A) ++ ("cbaaa") ++ (A) ++ ("ac") ++ (A) ++ ("abb") ++ (A) ++ ("bacaccbb") ++ (A) ++ ("cbbbcccbbac"))
    =
    (("bbccbab") ++ (A) ++ ("bbb") ++ (A) ++ ("aacc") ++ (A) ++ (A) ++ ("abccccbabcbcba") ++ (A) ++ ("cb") ++ (A) ++ (A) ++ (A) ++ (A) ++ ("ac") ++ (A) ++ ("abb") ++ (A) ++ ("b") ++ (A) ++ ("caccbbacbbbcccbb") ++ (A) ++ ("c"));
constraint
  (("cbcbcbcba") ++ (A) ++ ("abaa") ++ (A) ++ ("bcacbcaacbbbb") ++ (A) ++ ("ba") ++ (A) ++ (A) ++ ("bab") ++ (A) ++ ("ac") ++ (A) ++ ("cbaccbcacbbcc") ++ (A) ++ ("acbbabababcb"))
    =
    (("cbcbcbcb") ++ (A) ++ (A) ++ (A) ++ ("ba") ++ (A) ++ ("abc") ++ (A) ++ ("cbca") ++ (A) ++ ("cbbbbab") ++ (A) ++ ("a") ++ (A) ++ ("bab") ++ (A) ++ ("acacb") ++ (A) ++ ("ccbc") ++ (A) ++ ("cbbcca") ++ (A) ++ ("cbb") ++ (A) ++ ("b") ++ (A) ++ ("b") ++ (A) ++ ("bcb"));
constraint
  (("aaab") ++ (A) ++ ("acaccabbb") ++ (A) ++ ("bc") ++ (A) ++ ("abbbacbcaaacaaacc") ++ (A) ++ ("cc") ++ (A) ++ ("bcbabbabccabccbbbabbababbab"))
    =
    (("a") ++ (A) ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("c") ++ (A) ++ ("cc") ++ (A) ++ ("bbbabcaabbbacbcaaac") ++ (A) ++ ("aaccaccabcb") ++ (A) ++ ("bb") ++ (A) ++ ("bccabccbbbabbababb") ++ (A) ++ ("b"));
constraint
  ((A) ++ ("baabaccabc") ++ (A) ++ ("bbccaabc") ++ (A) ++ ("cbbcccbccc") ++ (A) ++ ("bacbabbbccabaa") ++ (A) ++ ("ccbc") ++ (A) ++ ("babcccbc") ++ (A) ++ ("baacc"))
    =
    (("ab") ++ (A) ++ ("abaccabcabbcca") ++ (A) ++ ("bc") ++ (A) ++ ("cbbcccbccc") ++ (A) ++ ("b") ++ (A) ++ ("cb") ++ (A) ++ ("bbbccabaa") ++ (A) ++ ("ccbcababcccbc") ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("cc"));
constraint
  (("c") ++ (A) ++ ("cc") ++ (A) ++ (A) ++ ("cccb") ++ (A) ++ (A) ++ ("ccc") ++ (A) ++ ("abcbb") ++ (A) ++ ("bb") ++ (A) ++ ("b") ++ (A) ++ ("bccbab") ++ (A) ++ ("bbbcb") ++ (A) ++ ("bccabcbbcca") ++ (A) ++ ("babc") ++ (A) ++ (A) ++ ("a") ++ (A) ++ ("babcbb"))
    =
    (("caccaacccba") ++ (A) ++ ("ccc") ++ (A) ++ (A) ++ ("bcbb") ++ (A) ++ ("bbababccb") ++ (A) ++ ("b") ++ (A) ++ ("bbbcbabccabcbbcca") ++ (A) ++ ("babcaaaab") ++ (A) ++ ("bcbb"));
constraint
  (("bbccabc") ++ (A) ++ ("bcacaabb") ++ (A) ++ ("bcbbc") ++ (A) ++ ("a") ++ (A) ++ ("c") ++ (A) ++ ("bbcccbbb") ++ (A) ++ (A) ++ (A) ++ ("b") ++ (A) ++ ("bbcbbaccccbb") ++ (A) ++ ("acbababbcb") ++ (A) ++ ("cb"))
    =
    (("bbcc") ++ (A) ++ ("bcabcac") ++ (A) ++ (A) ++ ("bbabcbbc") ++ (A) ++ (A) ++ ("acabbcccbbbaa") ++ (A) ++ ("babbcbb") ++ (A) ++ ("ccccbbaacbab") ++ (A) ++ ("bbcbacb"));
constraint
  ((A) ++ ("ccc") ++ (A) ++ ("caaac") ++ (A) ++ ("cbabccbb") ++ (A) ++ (A) ++ (A) ++ ("aabaccaaacbcaa") ++ (A) ++ ("bcbbccaccacb") ++ (A) ++ ("ccbbcab") ++ (A) ++ ("bcacabbb"))
    =
    ((A) ++ ("ccc") ++ (A) ++ ("ca") ++ (A) ++ (A) ++ ("c") ++ (A) ++ ("cb") ++ (A) ++ ("bccbb") ++ (A) ++ ("a") ++ (A) ++ (A) ++ (A) ++ ("baccaa") ++ (A) ++ ("cbcaa") ++ (A) ++ ("bcbbccacc") ++ (A) ++ ("cb") ++ (A) ++ ("ccbbc") ++ (A) ++ ("babcacabbb"));
constraint
  (("cbabca") ++ (A) ++ (A) ++ ("baaccbb") ++ (A) ++ ("cbcbbccccbbcccbcccccccababc") ++ (A) ++ ("accbcb") ++ (A) ++ ("bc") ++ (A) ++ ("cacbabbbbb") ++ (A) ++ ("b"))
    =
    (("cbabc") ++ (A) ++ (A) ++ ("aba") ++ (A) ++ ("ccbb") ++ (A) ++ ("cbcbbccccbbcccbccccccc") ++ (A) ++ ("b") ++ (A) ++ ("bc") ++ (A) ++ ("accbcbabc") ++ (A) ++ ("cacb") ++ (A) ++ ("bbbbbab"));
constraint
  (("aca") ++ (A) ++ ("ca") ++ (A) ++ ("bcbb") ++ (A) ++ ("cbc") ++ (A) ++ ("ba") ++ (A) ++ ("accbbacc") ++ (A) ++ ("b") ++ (A) ++ ("cabcabcccaccbbb") ++ (A) ++ ("bcbbaabcb") ++ (A) ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("cbaa") ++ (A) ++ ("c"))
    =
    ((A) ++ ("c") ++ (A) ++ (A) ++ ("ca") ++ (A) ++ ("bcbb") ++ (A) ++ ("cbc") ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("accbbaccabac") ++ (A) ++ ("bc") ++ (A) ++ ("bcccaccbbbabcbba") ++ (A) ++ ("bcb") ++ (A) ++ (A) ++ ("ba") ++ (A) ++ ("cb") ++ (A) ++ (A) ++ (A) ++ ("c"));
constraint
  (("cacca") ++ (A) ++ ("c") ++ (A) ++ (A) ++ ("bbc") ++ (A) ++ ("cab") ++ (A) ++ ("bc") ++ (A) ++ ("b") ++ (A) ++ ("cbbc") ++ (A) ++ ("bccaccb") ++ (A) ++ ("b") ++ (A) ++ ("cc") ++ (A) ++ (A) ++ ("ababbb") ++ (A) ++ ("b") ++ (A) ++ ("cbbcccaac") ++ (A) ++ ("bbbcbb"))
    =
    (("cacca") ++ (A) ++ ("c") ++ (A) ++ (A) ++ ("bbcac") ++ (A) ++ ("b") ++ (A) ++ ("bc") ++ (A) ++ ("bacbbc") ++ (A) ++ ("bccaccb") ++ (A) ++ ("b") ++ (A) ++ ("cc") ++ (A) ++ ("aababbbabacbbccca") ++ (A) ++ ("cabbbcbb"));
constraint
  (("bcbbaabacbacbab") ++ (A) ++ ("bc") ++ (A) ++ (A) ++ ("bbcccbacabbbb") ++ (A) ++ ("ccbbabbacb") ++ (A) ++ ("bc") ++ (A) ++ (A) ++ ("cbbbba") ++ (A) ++ ("a") ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("bbac") ++ (A))
    =
    (("bcbb") ++ (A) ++ (A) ++ ("b") ++ (A) ++ ("cb") ++ (A) ++ ("cbababcaabbcccb") ++ (A) ++ ("cabbbbaccbb") ++ (A) ++ ("bb") ++ (A) ++ ("cbabc") ++ (A) ++ ("acbbbba") ++ (A) ++ ("a") ++ (A) ++ ("b") ++ (A) ++ (A) ++ ("bbaca"));
constraint
  (("acbabb") ++ (A) ++ ("b") ++ (A) ++ ("cb") ++ (A) ++ (A) ++ ("ba") ++ (A) ++ (A) ++ ("ccbcc") ++ (A) ++ ("b") ++ (A) ++ ("accbb") ++ (A) ++ (A) ++ (A) ++ ("aaabcbbacbbbbccb") ++ (A) ++ ("bccbbbb") ++ (A) ++ (A) ++ (A) ++ ("c") ++ (A) ++ (A) ++ ("bbc"))
    =
    (("acbabb") ++ (A) ++ ("b") ++ (A) ++ ("cbaaba") ++ (A) ++ (A) ++ ("ccbcc") ++ (A) ++ ("baaccbb") ++ (A) ++ (A) ++ ("aaaabcbb") ++ (A) ++ ("cbbbbccb") ++ (A) ++ ("bccbbbb") ++ (A) ++ (A) ++ ("aca") ++ (A) ++ ("bbc"));
constraint
  (("abbbaa") ++ (A) ++ ("bb") ++ (A) ++ ("bcc") ++ (A) ++ (A) ++ ("cbc") ++ (A) ++ ("bcbbc") ++ (A) ++ ("c") ++ (A) ++ (A) ++ ("cc") ++ (A) ++ ("bcabb") ++ (A) ++ (A) ++ ("cabcbcbb") ++ (A) ++ ("babcbbcc") ++ (A) ++ ("aba") ++ (A) ++ (A) ++ ("bcaac"))
    =
    ((A) ++ ("bbbaaabbabccaacbc") ++ (A) ++ ("bcbbc") ++ (A) ++ ("c") ++ (A) ++ (A) ++ ("ccabcabbaac") ++ (A) ++ ("bcbcbbab") ++ (A) ++ ("bcbbcca") ++ (A) ++ ("baaabc") ++ (A) ++ (A) ++ ("c"));
constraint
  (("ab") ++ (A) ++ ("a") ++ (A) ++ ("cb") ++ (A) ++ ("cbbbbcbaaa") ++ (A) ++ ("ba") ++ (A) ++ ("caaab") ++ (A) ++ ("aabbccabaaacacbcbbbccbaaaa") ++ (A) ++ ("ba") ++ (A) ++ ("cabbcabc"))
    =
    ((A) ++ ("b") ++ (A) ++ ("a") ++ (A) ++ ("cbacbbbbcb") ++ (A) ++ (A) ++ (A) ++ ("abaacaa") ++ (A) ++ ("b") ++ (A) ++ (A) ++ (A) ++ ("bbcc") ++ (A) ++ ("ba") ++ (A) ++ (A) ++ ("c") ++ (A) ++ ("cbcbbbccb") ++ (A) ++ ("aa") ++ (A) ++ ("ab") ++ (A) ++ (A) ++ ("cabbcabc"));
constraint
  ((A) ++ ("aaac") ++ (A) ++ ("a") ++ (A) ++ ("bbcbc") ++ (A) ++ ("a") ++ (A) ++ ("cacbaccc") ++ (A) ++ ("caccb") ++ (A) ++ ("b") ++ (A) ++ ("bb") ++ (A) ++ ("bccccbbbbbcbc") ++ (A) ++ ("bacccc") ++ (A) ++ ("a") ++ (A) ++ (A) ++ ("bca") ++ (A) ++ ("ca"))
    =
    ((A) ++ ("a") ++ (A) ++ (A) ++ ("c") ++ (A) ++ ("a") ++ (A) ++ ("bbcbc") ++ (A) ++ ("aacacbacccac") ++ (A) ++ ("ccbab") ++ (A) ++ ("bb") ++ (A) ++ ("bccccbbbbbcbc") ++ (A) ++ ("b") ++ (A) ++ ("cccc") ++ (A) ++ (A) ++ ("a") ++ (A) ++ ("bca") ++ (A) ++ ("ca"));
constraint
  (("bbcabbcccb") ++ (A) ++ ("bbcabcacbccb") ++ (A) ++ ("bcbacbbcbacbcc") ++ (A) ++ ("bbbb") ++ (A) ++ ("bbbaacbc") ++ (A) ++ ("b") ++ (A) ++ ("b") ++ (A) ++ ("cc") ++ (A) ++ ("ab") ++ (A) ++ (A) ++ ("bc"))
    =
    (("bbcabbcccbabbc") ++ (A) ++ ("bcacbccb") ++ (A) ++ ("bcbacbbcbacbcc") ++ (A) ++ ("bbbb") ++ (A) ++ ("bbba") ++ (A) ++ ("cbc") ++ (A) ++ ("bab") ++ (A) ++ ("ccaaba") ++ (A) ++ ("bc"));
constraint
  (("b") ++ (A) ++ ("bbbcb") ++ (A) ++ ("bbbcaccc") ++ (A) ++ ("ccb") ++ (A) ++ (A) ++ ("bccba") ++ (A) ++ ("a") ++ (A) ++ ("abcacacbbcaaabcaabbbb") ++ (A) ++ ("cccbcbbbbb") ++ (A) ++ ("bcc"))
    =
    (("b") ++ (A) ++ ("bbbcbabbbcaccc") ++ (A) ++ ("ccbaabccba") ++ (A) ++ ("aaabcac") ++ (A) ++ ("cbbc") ++ (A) ++ (A) ++ ("abca") ++ (A) ++ ("bbbbacccbcbbbbb") ++ (A) ++ ("bcc"));
solve satisfy;
