var string: H;
var string: E;
var string: D;
constraint
  (("ccc") ++ (D) ++ ("ac") ++ (H) ++ ("a") ++ (E) ++ ("bbcaa") ++ (D) ++ ("abcc") ++ (D) ++ ("cabaaaacbbcaacc") ++ (H) ++ ("a"))
    =
    (("cccbac") ++ (D) ++ ("c") ++ (D) ++ ("acba") ++ (D) ++ ("bcaaba") ++ (D) ++ ("ccbca") ++ (D) ++ ("aaaacbbcaaccbc") ++ (D) ++ ("a"));
constraint
  (("cabbc") ++ (D) ++ ("abb") ++ (D) ++ (D) ++ ("aaabaa") ++ (D) ++ ("aab") ++ (D) ++ ("b") ++ (D) ++ (E) ++ ("cac") ++ (D) ++ ("ccc") ++ (D) ++ (D) ++ ("a") ++ (D) ++ ("baa") ++ (D) ++ ("c"))
    =
    (("cab") ++ (D) ++ ("c") ++ (D) ++ ("a") ++ (D) ++ (D) ++ ("b") ++ (D) ++ ("aaa") ++ (D) ++ ("aa") ++ (D) ++ ("aabbbbc") ++ (D) ++ ("acac") ++ (D) ++ ("ccc") ++ (D) ++ ("babbaabc"));
constraint
  ((D) ++ (D) ++ ("cbc") ++ (H) ++ ("ca") ++ (E) ++ (D) ++ (E) ++ (D) ++ ("ca") ++ (D) ++ ("cbccb") ++ (D) ++ (D) ++ ("abb") ++ (D) ++ (D) ++ (H) ++ ("aaaaaa") ++ (D))
    =
    (("bbc") ++ (D) ++ ("c") ++ (D) ++ ("c") ++ (D) ++ ("cac") ++ (D) ++ ("a") ++ (D) ++ ("c") ++ (D) ++ ("a") ++ (D) ++ ("cabc") ++ (D) ++ ("cc") ++ (D) ++ (D) ++ ("babb") ++ (D) ++ ("b") ++ (D) ++ ("c") ++ (D) ++ ("aaaaaab"));
constraint
  (("cc") ++ (E) ++ ("acbbaa") ++ (H) ++ (D) ++ ("ba") ++ (D) ++ ("a") ++ (H) ++ ("cabaacaacaaab") ++ (D) ++ ("ccaaac") ++ (D))
    =
    (("cc") ++ (E) ++ ("acb") ++ (D) ++ ("aa") ++ (D) ++ ("c") ++ (D) ++ ("b") ++ (D) ++ ("ababcbca") ++ (D) ++ ("aacaacaaab") ++ (D) ++ ("ccaaac") ++ (D));
constraint
  (("aaacccaccaaaccb") ++ (D) ++ (D) ++ ("a") ++ (D) ++ ("cbaabccacccb") ++ (D) ++ ("cccabacacc") ++ (D))
    =
    (("aaacccaccaaaccb") ++ (D) ++ (D) ++ ("a") ++ (D) ++ ("c") ++ (D) ++ ("aa") ++ (D) ++ ("ccaccc") ++ (D) ++ (D) ++ ("cccabacaccb"));
constraint
  (("b") ++ (D) ++ ("cabbacaccccaaaaa") ++ (D) ++ ("abbacccacac") ++ (E) ++ ("bcb") ++ (D) ++ ("ccc") ++ (D) ++ ("c") ++ (D))
    =
    ((D) ++ ("bca") ++ (D) ++ (D) ++ ("acaccccaaaaabab") ++ (D) ++ ("acccacacc") ++ (D) ++ ("abcbbcccbcb"));
constraint
  (("aababcacbaccaaa") ++ (D) ++ ("a") ++ (D) ++ ("aa") ++ (H) ++ (D) ++ ("a") ++ (E) ++ ("ab") ++ (D) ++ ("bab") ++ (D) ++ ("acbaccca"))
    =
    (("aaba") ++ (D) ++ ("cac") ++ (D) ++ ("accaaababaabc") ++ (D) ++ (D) ++ ("ac") ++ (D) ++ ("aabbbab") ++ (D) ++ ("acbaccca"));
constraint
  (("bcccac") ++ (D) ++ (D) ++ ("caca") ++ (D) ++ ("caaaaabc") ++ (D) ++ ("ca") ++ (D) ++ (D) ++ ("cabbacacccc") ++ (D) ++ ("acbbc"))
    =
    ((D) ++ ("cccacb") ++ (D) ++ ("cacabcaaaaabcbca") ++ (D) ++ ("bca") ++ (D) ++ ("bacacccc") ++ (D) ++ ("acbbc"));
constraint
  (("bcaacaa") ++ (D) ++ (D) ++ ("ccaaacaacabaaba") ++ (D) ++ ("a") ++ (D) ++ ("bacabacbaababcc") ++ (D))
    =
    (("bcaacaa") ++ (D) ++ (D) ++ ("ccaaacaaca") ++ (D) ++ ("aa") ++ (D) ++ ("a") ++ (D) ++ ("abbaca") ++ (D) ++ ("a") ++ (E) ++ ("ababccb"));
constraint
  ((D) ++ ("acc") ++ (D) ++ ("ca") ++ (D) ++ (D) ++ ("aaaccccaa") ++ (D) ++ ("aa") ++ (D) ++ ("aabccc") ++ (D) ++ (D) ++ ("ccaccacccca") ++ (D) ++ ("a"))
    =
    (("bacc") ++ (D) ++ ("cab") ++ (D) ++ ("aaaccccaa") ++ (D) ++ ("aabaa") ++ (D) ++ ("cccb") ++ (D) ++ ("ccaccaccccaba"));
constraint
  (("cccabccaac") ++ (D) ++ ("aacccacaabcaaacab") ++ (D) ++ ("cab") ++ (D) ++ ("ab") ++ (D) ++ ("cabba") ++ (D) ++ ("a"))
    =
    (("ccca") ++ (D) ++ ("ccaac") ++ (D) ++ ("aacccacaabcaaacabbca") ++ (D) ++ ("babbca") ++ (D) ++ ("ba") ++ (D) ++ ("a"));
constraint
  (("cb") ++ (E) ++ ("aa") ++ (D) ++ (D) ++ (D) ++ (D) ++ ("a") ++ (D) ++ ("cabb") ++ (H) ++ ("baaca") ++ (D) ++ ("cac") ++ (D) ++ (D) ++ (D) ++ ("bb") ++ (D) ++ (H) ++ ("aaccb"))
    =
    (("cbc") ++ (D) ++ ("aaa") ++ (D) ++ ("bb") ++ (D) ++ ("a") ++ (D) ++ ("cab") ++ (D) ++ (D) ++ ("cbbaaca") ++ (D) ++ ("cacb") ++ (D) ++ (D) ++ (D) ++ (D) ++ ("b") ++ (D) ++ ("c") ++ (D) ++ ("aaccb"));
constraint
  (("b") ++ (D) ++ ("baaaccabb") ++ (H) ++ ("bb") ++ (H) ++ (D) ++ ("aac") ++ (H) ++ ("cccc") ++ (H) ++ ("cca") ++ (H) ++ (E) ++ ("c"))
    =
    (("bbbaaaccabb") ++ (D) ++ ("cb") ++ (D) ++ (D) ++ (D) ++ ("cbbaacbc") ++ (D) ++ ("cccc") ++ (D) ++ ("c") ++ (D) ++ ("cca") ++ (H) ++ ("cbac"));
constraint
  (("cccaca") ++ (D) ++ ("acbc") ++ (D) ++ ("a") ++ (D) ++ ("a") ++ (D) ++ ("ccbcacccca") ++ (D) ++ ("ab") ++ (D) ++ ("caccbbcbba") ++ (D) ++ (D) ++ ("c"))
    =
    (("cccaca") ++ (D) ++ ("ac") ++ (D) ++ ("cba") ++ (D) ++ ("abcc") ++ (D) ++ ("caccccababbcaccbbcb") ++ (D) ++ ("a") ++ (D) ++ ("bc"));
constraint
  (("a") ++ (D) ++ ("abba") ++ (D) ++ ("acccca") ++ (D) ++ ("a") ++ (D) ++ ("aaaaba") ++ (D) ++ ("ca") ++ (D) ++ ("ca") ++ (D) ++ ("baacac") ++ (D) ++ ("caaab") ++ (D) ++ ("a"))
    =
    (("aba") ++ (D) ++ (D) ++ ("abaccccaba") ++ (D) ++ ("aaaababca") ++ (D) ++ ("cab") ++ (D) ++ ("aacac") ++ (D) ++ ("caaa") ++ (D) ++ ("ba"));
constraint
  (("a") ++ (D) ++ (D) ++ ("bccaccacaca") ++ (H) ++ ("aabacac") ++ (D) ++ (D) ++ ("ca") ++ (D) ++ ("aca") ++ (D) ++ ("acccbc") ++ (D) ++ ("bb") ++ (D))
    =
    (("ab") ++ (D) ++ ("bccaccacacabc") ++ (D) ++ ("aabacacbbcabacabaccc") ++ (D) ++ ("cb") ++ (D) ++ ("bb"));
constraint
  (("aca") ++ (D) ++ ("baccabcababaaa") ++ (D) ++ ("a") ++ (D) ++ ("abba") ++ (D) ++ (D) ++ ("bcaabcca") ++ (H) ++ ("bb") ++ (D) ++ (D) ++ (D))
    =
    (("acabbacca") ++ (D) ++ ("caba") ++ (D) ++ ("aaababa") ++ (D) ++ ("babbbcaa") ++ (D) ++ ("ccabc") ++ (D) ++ (D) ++ (D) ++ (D) ++ ("b") ++ (D));
constraint
  (("cccbcaacbcbbbcc") ++ (D) ++ ("cccaa") ++ (D) ++ ("c") ++ (D) ++ ("caaaaccbbbaaacaaaaa"))
    =
    (("ccc") ++ (D) ++ ("caacbc") ++ (D) ++ ("bbccbcccaabc") ++ (D) ++ ("caaaacc") ++ (D) ++ ("bbaaacaaaaa"));
constraint
  (("aacc") ++ (D) ++ (H) ++ ("c") ++ (D) ++ ("bcabb") ++ (D) ++ ("acbcca") ++ (D) ++ (D) ++ ("cbcaccaa") ++ (D) ++ ("cb") ++ (D) ++ (D) ++ ("abcccc"))
    =
    (("aaccb") ++ (H) ++ ("c") ++ (D) ++ ("bca") ++ (D) ++ (D) ++ (D) ++ ("acbcca") ++ (D) ++ (H) ++ ("caccaabc") ++ (D) ++ ("b") ++ (D) ++ ("abcccc"));
constraint
  (("caacc") ++ (H) ++ ("abccab") ++ (D) ++ (D) ++ ("aacca") ++ (D) ++ (D) ++ ("bcacbaacacab") ++ (D) ++ ("acb") ++ (D) ++ ("ccc"))
    =
    (("caaccbc") ++ (D) ++ ("a") ++ (D) ++ ("ccab") ++ (D) ++ (D) ++ ("aacca") ++ (D) ++ (D) ++ ("bcacbaacaca") ++ (D) ++ ("bac") ++ (D) ++ ("bccc"));
constraint
  (("abccbccacaacbcb") ++ (D) ++ ("ca") ++ (D) ++ ("aca") ++ (D) ++ ("abcabca") ++ (H) ++ ("cabcacb") ++ (D) ++ ("cc"))
    =
    (("a") ++ (D) ++ ("cc") ++ (D) ++ ("ccacaac") ++ (D) ++ ("c") ++ (D) ++ ("bcabacababcabca") ++ (H) ++ ("cabcacbbcc"));
constraint
  (("aacacac") ++ (H) ++ ("aaabaac") ++ (D) ++ ("baccaacbc") ++ (D) ++ ("b") ++ (D) ++ (D) ++ ("cacaca") ++ (E) ++ ("cca"))
    =
    (("aacacac") ++ (H) ++ ("aaabaacbbaccaac") ++ (D) ++ ("c") ++ (D) ++ ("b") ++ (D) ++ (D) ++ ("cacacac") ++ (D) ++ ("acca"));
constraint
  (("aaaccbcabcbbaa") ++ (D) ++ ("ac") ++ (D) ++ ("aa") ++ (D) ++ ("ccc") ++ (D) ++ (D) ++ ("ababbaacccac") ++ (D) ++ ("aaca"))
    =
    (("aaacc") ++ (D) ++ ("ca") ++ (D) ++ ("c") ++ (D) ++ ("baabac") ++ (D) ++ ("aabccc") ++ (D) ++ (D) ++ ("a") ++ (D) ++ ("a") ++ (D) ++ ("baacccac") ++ (D) ++ ("aaca"));
constraint
  (("caa") ++ (D) ++ ("acabc") ++ (D) ++ ("cacab") ++ (D) ++ ("cabb") ++ (D) ++ ("b") ++ (D) ++ ("a") ++ (D) ++ ("a") ++ (D) ++ (D) ++ ("ab") ++ (D) ++ ("aabbcac") ++ (D) ++ (D) ++ (H))
    =
    (("caa") ++ (D) ++ ("acabcbcacab") ++ (D) ++ ("cabb") ++ (D) ++ ("b") ++ (D) ++ ("ababba") ++ (D) ++ ("baa") ++ (D) ++ (D) ++ ("cacb") ++ (D) ++ (H));
constraint
  (("ca") ++ (D) ++ ("acaccacc") ++ (D) ++ ("aabca") ++ (D) ++ ("bcccabcab") ++ (D) ++ (D) ++ (D) ++ ("bcca") ++ (D) ++ ("ccbcab") ++ (D) ++ ("c"))
    =
    (("ca") ++ (D) ++ ("acaccacc") ++ (D) ++ ("aabca") ++ (D) ++ ("bcccabcabb") ++ (D) ++ ("b") ++ (D) ++ ("ccabcc") ++ (D) ++ ("cabbc"));
constraint
  ((D) ++ ("ca") ++ (D) ++ ("b") ++ (D) ++ ("ab") ++ (D) ++ ("ccaa") ++ (D) ++ ("accaccb") ++ (D) ++ ("aa") ++ (E) ++ ("a") ++ (D) ++ ("bacccbcc") ++ (D) ++ ("ccbaa"))
    =
    (("bca") ++ (D) ++ (D) ++ (D) ++ ("a") ++ (D) ++ (D) ++ ("ccaa") ++ (D) ++ ("accacc") ++ (D) ++ ("baacbaa") ++ (D) ++ ("baccc") ++ (D) ++ ("cc") ++ (D) ++ ("ccbaa"));
constraint
  (("bbca") ++ (D) ++ ("aaccccacb") ++ (D) ++ (D) ++ (H) ++ ("acaba") ++ (D) ++ ("a") ++ (D) ++ ("ac") ++ (D) ++ ("c") ++ (D) ++ ("acc") ++ (D) ++ ("aabaccc"))
    =
    (("bbcabaaccccac") ++ (D) ++ (D) ++ (D) ++ ("bc") ++ (D) ++ ("aca") ++ (D) ++ ("a") ++ (D) ++ ("abac") ++ (D) ++ (E) ++ ("cc") ++ (D) ++ ("aabaccc"));
constraint
  (("acaccaccaac") ++ (D) ++ ("bcaa") ++ (D) ++ ("bbcabcabcaaaabcacaccc") ++ (D) ++ ("cccc"))
    =
    (("acaccaccaacb") ++ (D) ++ ("caabbbcabcabcaaaa") ++ (D) ++ ("cacacccbcccc"));
constraint
  (("cc") ++ (H) ++ ("aba") ++ (D) ++ ("aa") ++ (H) ++ ("ac") ++ (D) ++ (D) ++ ("ccacccc") ++ (D) ++ ("abc") ++ (D) ++ ("bc") ++ (D) ++ ("c") ++ (D) ++ ("bbcccbca"))
    =
    (("ccbc") ++ (D) ++ ("a") ++ (D) ++ ("a") ++ (D) ++ ("aa") ++ (D) ++ ("c") ++ (D) ++ ("ac") ++ (D) ++ (D) ++ ("ccaccc") ++ (E) ++ (D) ++ ("cb") ++ (D) ++ ("cbc") ++ (D) ++ (D) ++ (D) ++ ("cccbca"));
constraint
  (("ccc") ++ (H) ++ ("aaaaaa") ++ (D) ++ ("ac") ++ (D) ++ ("ccbc") ++ (D) ++ ("cac") ++ (D) ++ ("abba") ++ (D) ++ (D) ++ (D) ++ ("aaacbbccaab"))
    =
    (("cccbc") ++ (D) ++ ("aaaaaa") ++ (D) ++ ("ac") ++ (D) ++ ("cc") ++ (D) ++ ("cbcacba") ++ (D) ++ ("ba") ++ (D) ++ (D) ++ ("baaac") ++ (D) ++ ("bccaab"));
constraint
  ((D) ++ (D) ++ ("aaca") ++ (D) ++ ("cccaaca") ++ (D) ++ (H) ++ ("baa") ++ (H) ++ ("aabbaaa") ++ (D) ++ ("cac") ++ (D) ++ ("abbbacc"))
    =
    (("bbaaca") ++ (D) ++ ("cccaaca") ++ (D) ++ (D) ++ ("cb") ++ (D) ++ ("aa") ++ (D) ++ ("c") ++ (D) ++ ("aabbaaa") ++ (D) ++ ("ca") ++ (E) ++ (D) ++ (D) ++ (D) ++ ("acc"));
constraint
  (("abbcabb") ++ (H) ++ ("cccacb") ++ (D) ++ ("cbaaa") ++ (D) ++ ("aacccacb") ++ (D) ++ (D) ++ (D) ++ ("c") ++ (D) ++ ("cbcacca"))
    =
    (("a") ++ (D) ++ ("bca") ++ (D) ++ ("b") ++ (H) ++ ("cccac") ++ (D) ++ ("bc") ++ (D) ++ ("aaabaacccacbbb") ++ (D) ++ ("cbc") ++ (D) ++ ("cacca"));
constraint
  ((D) ++ ("cacb") ++ (D) ++ (H) ++ ("acacccca") ++ (D) ++ (D) ++ ("ca") ++ (H) ++ ("aa") ++ (D) ++ ("b") ++ (D) ++ ("ccaa") ++ (D) ++ ("c") ++ (D) ++ ("bcacacb"))
    =
    ((D) ++ ("cacbbbc") ++ (D) ++ ("acacccca") ++ (D) ++ (D) ++ ("cab") ++ (E) ++ ("abbbccaa") ++ (H) ++ ("bcacacb"));
constraint
  (("acacb") ++ (D) ++ ("aa") ++ (D) ++ ("aa") ++ (H) ++ ("cac") ++ (D) ++ ("acccccccccca") ++ (D) ++ ("bcccaaaabaac"))
    =
    (("acacbbaabaa") ++ (D) ++ ("cbca") ++ (E) ++ ("ccccccccccabbcccaaaabaac"));
constraint
  (("a") ++ (D) ++ ("acccaccaacaacabbaaaac") ++ (D) ++ (D) ++ ("acca") ++ (D) ++ ("c") ++ (D) ++ ("caac") ++ (D) ++ (D) ++ (D) ++ (D) ++ ("cac"))
    =
    (("abacccaccaacaaca") ++ (D) ++ ("baaaac") ++ (D) ++ (D) ++ ("acca") ++ (D) ++ ("c") ++ (D) ++ ("caacb") ++ (D) ++ ("bbcac"));
constraint
  (("aacaacacabbabacaa") ++ (H) ++ (D) ++ ("bccccccacc") ++ (D) ++ ("abac") ++ (H) ++ ("c") ++ (D) ++ ("aa"))
    =
    (("aacaacacabbabacaabcb") ++ (D) ++ ("bccccccac") ++ (E) ++ ("bacbc") ++ (D) ++ ("cbaa"));
constraint
  (("aca") ++ (D) ++ ("caa") ++ (D) ++ (D) ++ (D) ++ ("a") ++ (D) ++ (D) ++ ("a") ++ (D) ++ ("bcbcacccabcac") ++ (D) ++ ("cccb") ++ (D) ++ (D) ++ (H) ++ ("c") ++ (D) ++ ("cc") ++ (D))
    =
    (("aca") ++ (D) ++ ("caa") ++ (D) ++ ("b") ++ (D) ++ ("a") ++ (D) ++ ("ba") ++ (D) ++ (D) ++ ("c") ++ (D) ++ ("caccca") ++ (D) ++ ("cacbccc") ++ (D) ++ (D) ++ ("b") ++ (D) ++ ("cbc") ++ (D) ++ ("cc") ++ (D));
constraint
  (("caa") ++ (E) ++ ("ca") ++ (D) ++ (D) ++ ("bab") ++ (D) ++ ("a") ++ (D) ++ ("ccb") ++ (D) ++ ("caccacbcccbb") ++ (E) ++ (D) ++ ("acacbca"))
    =
    (("caac") ++ (D) ++ ("aca") ++ (D) ++ (D) ++ (D) ++ ("a") ++ (D) ++ ("babccbbcaccac") ++ (D) ++ ("ccc") ++ (D) ++ (D) ++ ("c") ++ (D) ++ ("abacac") ++ (D) ++ ("ca"));
constraint
  (("aabbcccc") ++ (E) ++ ("c") ++ (D) ++ ("bbca") ++ (D) ++ (D) ++ ("a") ++ (D) ++ ("a") ++ (D) ++ ("abcaabcabcaaccacc") ++ (D) ++ (D) ++ ("a"))
    =
    (("aab") ++ (D) ++ ("ccccc") ++ (D) ++ ("ac") ++ (D) ++ ("bbcabbaba") ++ (D) ++ ("abcaa") ++ (D) ++ ("cabcaaccacc") ++ (D) ++ (D) ++ ("a"));
constraint
  (("acacaa") ++ (D) ++ (D) ++ ("aabaacccaa") ++ (D) ++ ("c") ++ (E) ++ ("caccbbcacca") ++ (D) ++ ("bcabbaa") ++ (D))
    =
    (("acacaab") ++ (D) ++ ("aabaacccaabc") ++ (E) ++ ("cacc") ++ (D) ++ ("bcacca") ++ (D) ++ (D) ++ ("ca") ++ (D) ++ (D) ++ ("aa") ++ (D));
constraint
  (("bbbcabcaaaaabb") ++ (D) ++ ("caccaccaaacacccb") ++ (D) ++ ("cac") ++ (D) ++ (D) ++ ("aa") ++ (D) ++ ("aac"))
    =
    ((D) ++ (D) ++ ("bca") ++ (D) ++ ("caaaaab") ++ (D) ++ (D) ++ ("caccaccaaacaccc") ++ (D) ++ ("bcacb") ++ (D) ++ ("aa") ++ (D) ++ ("aac"));
constraint
  ((D) ++ (D) ++ ("c") ++ (E) ++ ("aa") ++ (D) ++ ("aabac") ++ (D) ++ ("cca") ++ (D) ++ (D) ++ ("bacb") ++ (D) ++ ("a") ++ (D) ++ (D) ++ (D) ++ ("acccbcccccc") ++ (D) ++ ("cc"))
    =
    ((D) ++ ("bcc") ++ (D) ++ ("aaa") ++ (D) ++ ("aa") ++ (D) ++ ("ac") ++ (D) ++ ("cca") ++ (D) ++ (D) ++ ("bacbbabb") ++ (D) ++ ("accc") ++ (D) ++ ("cccccc") ++ (D) ++ ("cc"));
constraint
  (("c") ++ (D) ++ ("bbaaaa") ++ (D) ++ ("aaaccbccaaccacb") ++ (D) ++ ("acaabba") ++ (D) ++ ("cca") ++ (D) ++ ("abaaa") ++ (D))
    =
    (("cbbbaaaa") ++ (D) ++ ("aaacc") ++ (D) ++ ("ccaaccac") ++ (D) ++ ("bacaa") ++ (D) ++ (D) ++ ("abcca") ++ (D) ++ ("abaaa") ++ (D));
constraint
  ((H) ++ ("c") ++ (D) ++ ("aca") ++ (D) ++ (D) ++ (D) ++ ("bacb") ++ (D) ++ ("accabaa") ++ (D) ++ ("b") ++ (E) ++ ("baaacab") ++ (D) ++ (H) ++ ("bcca"))
    =
    ((D) ++ ("c") ++ (D) ++ ("c") ++ (D) ++ ("aca") ++ (D) ++ (D) ++ (D) ++ (D) ++ ("acb") ++ (D) ++ ("acca") ++ (D) ++ ("aabb") ++ (E) ++ (D) ++ ("aaacab") ++ (D) ++ (D) ++ ("cbbcca"));
constraint
  (("ca") ++ (D) ++ ("cccc") ++ (D) ++ ("accbcc") ++ (D) ++ ("cabb") ++ (D) ++ ("bbc") ++ (D) ++ ("aaaaaca") ++ (D) ++ ("abbaa") ++ (D) ++ ("aa") ++ (D) ++ ("ac"))
    =
    (("cabcccc") ++ (D) ++ ("acc") ++ (D) ++ ("cc") ++ (D) ++ ("ca") ++ (D) ++ ("bbb") ++ (H) ++ ("aaaaacaba") ++ (D) ++ (D) ++ ("aabaabac"));
constraint
  (("ab") ++ (H) ++ ("aacccacaaa") ++ (D) ++ ("bca") ++ (D) ++ ("b") ++ (D) ++ ("ca") ++ (H) ++ ("cabbcc") ++ (D) ++ ("bbccacbac"))
    =
    (("a") ++ (D) ++ ("bc") ++ (D) ++ ("aacccacaaab") ++ (D) ++ ("ca") ++ (D) ++ (D) ++ (D) ++ ("ca") ++ (D) ++ ("cbcabbccbb") ++ (D) ++ ("ccac") ++ (D) ++ ("ac"));
constraint
  (("cbccc") ++ (D) ++ (H) ++ ("aa") ++ (D) ++ ("a") ++ (D) ++ ("aacccccaa") ++ (D) ++ ("cb") ++ (D) ++ ("abacaa") ++ (D) ++ (D) ++ ("ccb") ++ (D) ++ ("aaac"))
    =
    (("c") ++ (D) ++ ("ccc") ++ (D) ++ ("b") ++ (E) ++ ("aba") ++ (D) ++ ("aacccccaa") ++ (D) ++ ("cbba") ++ (D) ++ ("acaa") ++ (D) ++ (D) ++ ("ccbbaaac"));
constraint
  ((D) ++ ("acc") ++ (D) ++ (D) ++ ("caac") ++ (D) ++ ("ccbbccac") ++ (D) ++ ("acaa") ++ (D) ++ ("aaaacacccaaa") ++ (D) ++ ("cabcb"))
    =
    (("baccbbcaac") ++ (D) ++ ("ccb") ++ (D) ++ ("ccacbacaabaaaacacccaaa") ++ (D) ++ ("cabcb"));
constraint
  (("cc") ++ (D) ++ ("acabab") ++ (D) ++ ("ccacabcc") ++ (D) ++ ("aa") ++ (E) ++ ("bcbac") ++ (D) ++ ("aa") ++ (D) ++ ("aac") ++ (D) ++ ("b") ++ (D) ++ ("c") ++ (D) ++ ("ca"))
    =
    (("cc") ++ (D) ++ ("aca") ++ (D) ++ ("a") ++ (D) ++ ("bccacabc") ++ (E) ++ ("a") ++ (E) ++ (D) ++ ("c") ++ (D) ++ ("a") ++ (E) ++ ("abaacb") ++ (D) ++ (D) ++ ("c") ++ (D) ++ ("ca"));
constraint
  (("acc") ++ (H) ++ ("c") ++ (D) ++ ("ccc") ++ (D) ++ ("bc") ++ (D) ++ (D) ++ ("b") ++ (D) ++ ("bab") ++ (D) ++ ("ca") ++ (D) ++ ("c") ++ (D) ++ ("ca") ++ (D) ++ (D) ++ ("ac") ++ (D) ++ ("cccbcabcc"))
    =
    (("acc") ++ (D) ++ ("cbc") ++ (D) ++ ("ccc") ++ (D) ++ (D) ++ ("cbbb") ++ (D) ++ ("bab") ++ (D) ++ ("ca") ++ (H) ++ ("ca") ++ (D) ++ ("bacbccc") ++ (D) ++ ("ca") ++ (D) ++ ("cc"));
constraint
  (("a") ++ (D) ++ ("aca") ++ (H) ++ ("aacaaab") ++ (D) ++ (D) ++ ("bacaaa") ++ (D) ++ ("caaacc") ++ (D) ++ ("cab") ++ (D) ++ ("abccc") ++ (D) ++ ("a") ++ (D))
    =
    (("abacabc") ++ (D) ++ ("aacaaa") ++ (D) ++ (D) ++ (D) ++ (D) ++ ("acaaa") ++ (D) ++ ("caaacc") ++ (D) ++ ("cab") ++ (D) ++ ("abccc") ++ (D) ++ ("ab"));
constraint
  (("cab") ++ (H) ++ ("bcacacbccaaccabccaacc") ++ (D) ++ ("cacac") ++ (D) ++ ("cab") ++ (H) ++ ("cbc"))
    =
    (("ca") ++ (D) ++ (H) ++ (D) ++ ("cacacbccaaccabccaaccbcacac") ++ (D) ++ ("cab") ++ (H) ++ ("c") ++ (D) ++ ("c"));
constraint
  (("acbacaacc") ++ (D) ++ ("bbaba") ++ (D) ++ ("ba") ++ (D) ++ ("abcca") ++ (D) ++ (D) ++ ("bc") ++ (D) ++ ("caabbba") ++ (D) ++ (D) ++ ("aaa") ++ (D) ++ ("c"))
    =
    (("ac") ++ (D) ++ ("acaaccbbbaba") ++ (D) ++ (D) ++ ("aba") ++ (D) ++ ("ccab") ++ (D) ++ ("bc") ++ (D) ++ ("caa") ++ (D) ++ ("b") ++ (D) ++ ("a") ++ (D) ++ ("baaa") ++ (D) ++ ("c"));
constraint
  (("c") ++ (D) ++ ("ba") ++ (E) ++ (E) ++ ("a") ++ (D) ++ ("bcccbcbc") ++ (D) ++ ("aac") ++ (D) ++ ("b") ++ (D) ++ ("b") ++ (D) ++ ("babcab") ++ (D) ++ (D) ++ (D) ++ (D) ++ ("a") ++ (D) ++ ("a") ++ (D))
    =
    (("cbba") ++ (E) ++ ("c") ++ (D) ++ ("aa") ++ (D) ++ (D) ++ ("ccc") ++ (D) ++ ("cbc") ++ (D) ++ ("aac") ++ (D) ++ (D) ++ ("b") ++ (D) ++ ("bbabcabb") ++ (D) ++ (D) ++ (D) ++ ("a") ++ (D) ++ ("ab"));
constraint
  (("aa") ++ (D) ++ ("a") ++ (D) ++ (D) ++ ("acacbca") ++ (D) ++ ("accaccbb") ++ (H) ++ ("acbbccbacccaabbccb"))
    =
    (("aaba") ++ (D) ++ ("bacacbcabaccaccbbb") ++ (E) ++ ("cb") ++ (D) ++ ("cc") ++ (D) ++ ("acccaab") ++ (D) ++ ("ccb"));
constraint
  ((E) ++ (D) ++ ("cacab") ++ (D) ++ ("cacacc") ++ (E) ++ (D) ++ (D) ++ (D) ++ ("bbcabbaa") ++ (D) ++ ("ccc") ++ (H) ++ ("aacc") ++ (D) ++ ("c"))
    =
    (("c") ++ (D) ++ ("a") ++ (D) ++ ("caca") ++ (D) ++ ("bcacaccc") ++ (D) ++ ("abbb") ++ (D) ++ (D) ++ ("ca") ++ (D) ++ ("baa") ++ (D) ++ ("cccbc") ++ (D) ++ ("aacc") ++ (D) ++ ("c"));
constraint
  (("ba") ++ (E) ++ ("bc") ++ (D) ++ ("aacacbcccccacaaca") ++ (D) ++ ("ccaa") ++ (E) ++ ("aca") ++ (E) ++ ("a") ++ (D) ++ (D) ++ ("a"))
    =
    ((D) ++ ("ac") ++ (D) ++ ("a") ++ (D) ++ ("c") ++ (D) ++ ("aacac") ++ (D) ++ ("cccccacaacabccaac") ++ (D) ++ ("aacacbaabba"));
constraint
  ((D) ++ (H) ++ ("aaaaaacac") ++ (D) ++ ("aabcacacac") ++ (D) ++ ("acacaccbbaababc") ++ (D) ++ ("aa"))
    =
    ((D) ++ (D) ++ ("c") ++ (D) ++ ("aaaaaacac") ++ (D) ++ ("aa") ++ (D) ++ ("cacacac") ++ (D) ++ ("acacaccbbaabab") ++ (E) ++ ("a"));
constraint
  (("bcacca") ++ (D) ++ ("aaac") ++ (D) ++ ("aacaaa") ++ (D) ++ ("cccaaabaca") ++ (D) ++ ("ac") ++ (D) ++ ("baa") ++ (D) ++ ("abbaca"))
    =
    (("bcacca") ++ (D) ++ ("aaac") ++ (D) ++ ("aacaaabcccaaa") ++ (D) ++ ("aca") ++ (D) ++ ("acb") ++ (D) ++ ("aaba") ++ (D) ++ (D) ++ ("aca"));
constraint
  (("cababccaaa") ++ (D) ++ ("aca") ++ (D) ++ ("bbbcaabaccb") ++ (D) ++ ("ac") ++ (D) ++ ("caab") ++ (D) ++ ("aa") ++ (D) ++ ("bcca") ++ (D))
    =
    (("caba") ++ (D) ++ ("ccaaabaca") ++ (D) ++ (D) ++ ("b") ++ (D) ++ ("caabacc") ++ (D) ++ ("bacbcaab") ++ (D) ++ ("aa") ++ (D) ++ (D) ++ ("cca") ++ (D));
constraint
  (("acca") ++ (D) ++ ("c") ++ (D) ++ ("cabaaaaaa") ++ (D) ++ ("baaa") ++ (H) ++ ("cccaa") ++ (D) ++ ("cacabaa") ++ (D) ++ ("cabca"))
    =
    (("accabc") ++ (D) ++ ("ca") ++ (D) ++ ("aaaaaab") ++ (D) ++ ("aaa") ++ (H) ++ ("cccaabcacabaabcabca"));
constraint
  (("ab") ++ (D) ++ ("aa") ++ (D) ++ ("b") ++ (D) ++ ("ca") ++ (D) ++ ("c") ++ (D) ++ ("ccccaccacc") ++ (H) ++ (D) ++ ("cca") ++ (D) ++ ("bcaa") ++ (D) ++ ("abaaa") ++ (D) ++ ("a"))
    =
    (("a") ++ (D) ++ ("baab") ++ (D) ++ ("bcabcbccccaccacc") ++ (H) ++ ("bcca") ++ (D) ++ (D) ++ ("caaba") ++ (D) ++ ("aaaba"));
constraint
  (("aacacabcbba") ++ (D) ++ ("b") ++ (D) ++ ("ca") ++ (D) ++ ("a") ++ (D) ++ ("b") ++ (D) ++ ("cccbccccc") ++ (H) ++ ("caaaaacaa") ++ (D))
    =
    (("aacaca") ++ (D) ++ ("c") ++ (D) ++ (D) ++ ("a") ++ (D) ++ (D) ++ (D) ++ ("cabab") ++ (D) ++ (D) ++ ("cccbccccc") ++ (D) ++ ("c") ++ (D) ++ ("caaaaacaab"));
constraint
  ((D) ++ ("cccca") ++ (D) ++ ("aac") ++ (D) ++ ("cccaab") ++ (D) ++ ("bbcaaccb") ++ (D) ++ ("acabcccc") ++ (D) ++ ("cccaa") ++ (D) ++ ("a"))
    =
    (("bcccca") ++ (D) ++ ("aacbcccaab") ++ (D) ++ (D) ++ (D) ++ ("caaccbbacabcccc") ++ (D) ++ ("cccaaba"));
constraint
  (("aaccca") ++ (D) ++ ("c") ++ (E) ++ ("bab") ++ (D) ++ ("a") ++ (H) ++ (D) ++ ("abcaa") ++ (D) ++ (D) ++ (D) ++ ("c") ++ (D) ++ ("b") ++ (D) ++ ("cba") ++ (D) ++ ("babc") ++ (D) ++ ("ac"))
    =
    (("aaccca") ++ (D) ++ ("cc") ++ (D) ++ ("a") ++ (D) ++ ("a") ++ (D) ++ ("ba") ++ (H) ++ (D) ++ ("abcaa") ++ (D) ++ ("bbc") ++ (D) ++ (D) ++ (D) ++ (E) ++ (D) ++ (D) ++ ("a") ++ (D) ++ (E) ++ ("c"));
constraint
  (("c") ++ (D) ++ ("cbc") ++ (D) ++ ("bbacc") ++ (D) ++ ("c") ++ (D) ++ ("a") ++ (D) ++ ("bacaac") ++ (D) ++ ("a") ++ (D) ++ ("aaacaaaaabacacc") ++ (D) ++ ("bc"))
    =
    (("c") ++ (D) ++ ("cbc") ++ (D) ++ ("bbacc") ++ (D) ++ (E) ++ (D) ++ ("bacaac") ++ (D) ++ ("a") ++ (D) ++ ("aaacaaaaa") ++ (D) ++ ("acaccbbc"));
constraint
  ((D) ++ ("a") ++ (D) ++ ("acac") ++ (D) ++ ("cbba") ++ (D) ++ ("b") ++ (H) ++ ("acaacabaa") ++ (D) ++ ("a") ++ (D) ++ ("aaa") ++ (D) ++ ("ba") ++ (D) ++ ("bcc") ++ (D) ++ ("aab"))
    =
    (("ba") ++ (D) ++ ("acac") ++ (D) ++ ("cb") ++ (D) ++ ("a") ++ (D) ++ ("b") ++ (D) ++ (E) ++ ("caacabaababaaa") ++ (D) ++ ("babbcc") ++ (D) ++ ("aab"));
constraint
  (("aaaabcc") ++ (D) ++ ("caaac") ++ (D) ++ ("cca") ++ (D) ++ ("ac") ++ (D) ++ (D) ++ ("bccb") ++ (D) ++ ("b") ++ (D) ++ ("caaca") ++ (D) ++ ("abbccbaa"))
    =
    (("aaaabcc") ++ (D) ++ ("caaacbcca") ++ (D) ++ ("acb") ++ (D) ++ ("bcc") ++ (D) ++ (D) ++ (D) ++ ("bcaacaba") ++ (D) ++ ("bccbaa"));
constraint
  ((D) ++ ("acac") ++ (D) ++ ("ca") ++ (D) ++ (D) ++ ("abbccbb") ++ (D) ++ ("c") ++ (D) ++ ("abaacabaaccaabaccabccaa"))
    =
    ((D) ++ ("acacbca") ++ (D) ++ ("bab") ++ (D) ++ ("ccb") ++ (D) ++ (D) ++ ("cba") ++ (D) ++ ("aacabaaccaa") ++ (D) ++ ("acca") ++ (D) ++ ("ccaa"));
constraint
  (("a") ++ (D) ++ ("cccbbcacaabc") ++ (D) ++ ("aac") ++ (E) ++ ("ca") ++ (D) ++ ("acb") ++ (D) ++ (D) ++ (D) ++ ("a") ++ (D) ++ ("aacc") ++ (H) ++ ("acaa"))
    =
    (("a") ++ (D) ++ ("cccb") ++ (D) ++ ("cacaa") ++ (D) ++ ("c") ++ (D) ++ ("aac") ++ (E) ++ ("cabacb") ++ (D) ++ ("bbabaaccb") ++ (E) ++ ("caa"));
constraint
  (("caaccb") ++ (D) ++ ("caac") ++ (E) ++ ("acaacac") ++ (H) ++ ("aca") ++ (D) ++ ("ca") ++ (D) ++ ("ccbbccccaa") ++ (D) ++ ("b"))
    =
    (("caacc") ++ (D) ++ ("bcaac") ++ (E) ++ ("acaacacbcbaca") ++ (D) ++ ("ca") ++ (D) ++ ("ccb") ++ (D) ++ ("ccccaa") ++ (D) ++ ("b"));
constraint
  ((D) ++ ("aaccacc") ++ (D) ++ ("bcb") ++ (D) ++ ("ccccacccb") ++ (D) ++ (D) ++ (D) ++ ("c") ++ (D) ++ ("a") ++ (D) ++ ("abca") ++ (D) ++ ("cacaacbc") ++ (D))
    =
    (("baaccaccb") ++ (D) ++ ("cb") ++ (D) ++ ("ccccacccb") ++ (D) ++ ("b") ++ (D) ++ ("c") ++ (D) ++ ("a") ++ (D) ++ ("a") ++ (D) ++ ("cabcacaac") ++ (D) ++ ("cb"));
constraint
  (("abababbbbbac") ++ (D) ++ ("b") ++ (H) ++ ("bacbbca") ++ (D) ++ ("a") ++ (E) ++ (D) ++ ("cc") ++ (D) ++ ("a") ++ (D) ++ ("baca") ++ (D) ++ ("aac"))
    =
    (("ababab") ++ (D) ++ (D) ++ (D) ++ ("bacbb") ++ (D) ++ ("c") ++ (D) ++ ("bac") ++ (D) ++ ("bca") ++ (D) ++ ("a") ++ (E) ++ (D) ++ ("cc") ++ (D) ++ ("ab") ++ (D) ++ ("aca") ++ (D) ++ ("aac"));
constraint
  (("bcaaccc") ++ (D) ++ (H) ++ ("caacaccacbacaccccbcacccabc") ++ (D) ++ ("ccccc"))
    =
    ((D) ++ ("caacccbbcbcaacaccac") ++ (D) ++ ("acacccc") ++ (D) ++ ("caccca") ++ (D) ++ ("cbccccc"));
constraint
  (("ccc") ++ (D) ++ ("ccac") ++ (H) ++ ("ca") ++ (D) ++ ("b") ++ (D) ++ ("acaccccca") ++ (D) ++ ("bb") ++ (D) ++ (D) ++ (D) ++ ("caaccc") ++ (H) ++ (D) ++ ("a") ++ (D))
    =
    (("ccc") ++ (D) ++ ("ccacbcbca") ++ (D) ++ (D) ++ ("bacaccccca") ++ (D) ++ ("b") ++ (D) ++ (D) ++ (D) ++ (D) ++ ("caacccbcb") ++ (D) ++ ("ab"));
constraint
  ((D) ++ ("a") ++ (H) ++ ("cc") ++ (D) ++ ("a") ++ (D) ++ (H) ++ ("abbcbabaccccccccbb") ++ (D) ++ ("c") ++ (D) ++ ("caaccacac"))
    =
    (("babc") ++ (D) ++ ("ccbab") ++ (D) ++ ("c") ++ (D) ++ ("abb") ++ (E) ++ ("bacccccccc") ++ (D) ++ (D) ++ ("bcbcaaccacac"));
constraint
  (("caa") ++ (D) ++ ("ccccc") ++ (D) ++ ("bccacacaca") ++ (H) ++ ("c") ++ (D) ++ ("caaacacbccabcc") ++ (D) ++ ("ccc"))
    =
    (("caa") ++ (D) ++ ("cccccb") ++ (D) ++ ("ccacacaca") ++ (D) ++ ("c") ++ (D) ++ ("cbcaaacac") ++ (D) ++ ("ccabccbccc"));
constraint
  (("ccb") ++ (D) ++ ("abcbc") ++ (D) ++ ("caccaa") ++ (E) ++ ("aca") ++ (D) ++ (D) ++ ("acc") ++ (D) ++ ("bb") ++ (D) ++ ("babbab") ++ (D) ++ ("cca") ++ (D) ++ ("a"))
    =
    (("cc") ++ (D) ++ ("babc") ++ (D) ++ ("cbcaccaac") ++ (D) ++ ("aaca") ++ (D) ++ (D) ++ ("acc") ++ (D) ++ (D) ++ ("bb") ++ (D) ++ ("abbab") ++ (D) ++ ("ccaba"));
constraint
  (("a") ++ (D) ++ ("bac") ++ (D) ++ ("cbcacbb") ++ (D) ++ ("a") ++ (D) ++ (D) ++ ("b") ++ (D) ++ (D) ++ ("accca") ++ (D) ++ ("aacbcaaacc") ++ (D) ++ ("cac") ++ (D) ++ ("ca"))
    =
    (("abbacbc") ++ (D) ++ ("cacbbba") ++ (D) ++ (D) ++ ("b") ++ (D) ++ ("baccca") ++ (D) ++ ("aacbcaaaccbcac") ++ (D) ++ ("ca"));
constraint
  (("bcccbb") ++ (H) ++ ("ca") ++ (D) ++ ("abbcabbcaaaaca") ++ (D) ++ ("c") ++ (D) ++ ("cc") ++ (D) ++ ("cacabbc") ++ (D) ++ ("bbc"))
    =
    ((D) ++ ("cccbbbcbca") ++ (D) ++ ("abbca") ++ (D) ++ ("bcaaaaca") ++ (D) ++ ("c") ++ (D) ++ ("cc") ++ (D) ++ ("cacab") ++ (D) ++ ("cbb") ++ (D) ++ ("c"));
constraint
  (("c") ++ (D) ++ ("bbccba") ++ (D) ++ ("baca") ++ (D) ++ ("a") ++ (D) ++ ("ba") ++ (D) ++ ("caccccacccaa") ++ (D) ++ ("ca") ++ (D) ++ ("ccacac") ++ (D) ++ ("b"))
    =
    (("cb") ++ (D) ++ ("bc") ++ (E) ++ ("bbaca") ++ (D) ++ ("a") ++ (D) ++ (D) ++ ("a") ++ (D) ++ ("caccccacccaabcabccacacbb"));
constraint
  (("ccb") ++ (D) ++ ("bbcaacbbca") ++ (D) ++ ("ccccbba") ++ (D) ++ ("cc") ++ (D) ++ ("c") ++ (E) ++ ("bacacbc") ++ (D) ++ ("a") ++ (D) ++ ("caa"))
    =
    (("cc") ++ (D) ++ (D) ++ (D) ++ ("bcaacbbca") ++ (D) ++ ("cccc") ++ (D) ++ ("ba") ++ (D) ++ ("cc") ++ (D) ++ ("cc") ++ (D) ++ ("abacac") ++ (D) ++ ("cba") ++ (D) ++ ("caa"));
constraint
  (("ccab") ++ (D) ++ ("aaccacc") ++ (D) ++ ("ababacbcbbaab") ++ (D) ++ ("a") ++ (D) ++ ("abacc") ++ (H) ++ ("bbaac") ++ (D))
    =
    (("ccab") ++ (D) ++ ("aaccaccbaba") ++ (D) ++ ("ac") ++ (D) ++ ("c") ++ (D) ++ ("baa") ++ (D) ++ ("ba") ++ (D) ++ ("a") ++ (D) ++ ("acc") ++ (D) ++ ("cb") ++ (D) ++ ("baacb"));
constraint
  (("a") ++ (H) ++ ("a") ++ (D) ++ (D) ++ ("cccaaa") ++ (D) ++ (D) ++ (D) ++ ("bcccaabcbacccca") ++ (H) ++ ("cb") ++ (D) ++ ("abccaa"))
    =
    (("a") ++ (D) ++ ("cba") ++ (D) ++ (D) ++ ("cccaaab") ++ (D) ++ ("b") ++ (D) ++ ("cccaa") ++ (D) ++ ("cbacccca") ++ (H) ++ ("c") ++ (D) ++ (D) ++ ("a") ++ (D) ++ ("ccaa"));
constraint
  (("b") ++ (D) ++ ("ca") ++ (D) ++ ("aacacaccb") ++ (E) ++ ("aabacb") ++ (D) ++ ("cac") ++ (D) ++ (D) ++ ("acaaca") ++ (D) ++ ("b") ++ (D) ++ ("acccc"))
    =
    ((D) ++ ("bcabaacacaccbcbaaabac") ++ (D) ++ ("bcacbbacaacabb") ++ (D) ++ ("acccc"));
constraint
  (("ccaa") ++ (D) ++ (D) ++ ("ccbbc") ++ (D) ++ ("aca") ++ (D) ++ ("c") ++ (D) ++ (D) ++ ("aa") ++ (D) ++ ("caccacb") ++ (D) ++ (D) ++ ("cac") ++ (H) ++ (D) ++ (D) ++ ("aca") ++ (D))
    =
    (("ccaabbccbbcbaca") ++ (D) ++ ("c") ++ (D) ++ ("baa") ++ (D) ++ ("caccac") ++ (D) ++ (D) ++ (D) ++ ("cacbc") ++ (D) ++ (D) ++ (D) ++ ("aca") ++ (D));
constraint
  ((D) ++ ("aaab") ++ (D) ++ (D) ++ ("cabaccccaa") ++ (D) ++ (D) ++ ("caaccc") ++ (D) ++ (D) ++ ("ba") ++ (E) ++ ("baabbbacaac"))
    =
    ((D) ++ ("aaa") ++ (D) ++ (D) ++ ("bcabaccccaa") ++ (D) ++ (D) ++ ("caacccb") ++ (D) ++ (D) ++ ("ac") ++ (D) ++ ("a") ++ (D) ++ ("aa") ++ (D) ++ ("b") ++ (D) ++ ("acaac"));
constraint
  (("abaabaa") ++ (D) ++ ("a") ++ (D) ++ ("acb") ++ (D) ++ ("a") ++ (D) ++ (D) ++ (D) ++ ("ccacccaaacba") ++ (D) ++ ("bbaacc") ++ (D) ++ ("cc") ++ (D) ++ ("cc"))
    =
    (("abaa") ++ (D) ++ ("aa") ++ (D) ++ ("abac") ++ (D) ++ ("ba") ++ (D) ++ ("b") ++ (D) ++ ("ccacccaaac") ++ (D) ++ ("a") ++ (D) ++ (D) ++ ("baaccbcc") ++ (D) ++ ("cc"));
constraint
  (("c") ++ (D) ++ ("ccaccccc") ++ (D) ++ ("accaababacb") ++ (D) ++ ("caaa") ++ (D) ++ ("aab") ++ (D) ++ ("a") ++ (D) ++ ("cb") ++ (D) ++ ("baaabc"))
    =
    (("cbccaccccc") ++ (D) ++ ("accaababacbbcaaabaa") ++ (D) ++ (D) ++ ("abc") ++ (D) ++ ("b") ++ (D) ++ ("aaa") ++ (D) ++ ("c"));
constraint
  (("abcc") ++ (D) ++ ("ac") ++ (D) ++ (H) ++ (H) ++ ("bacb") ++ (D) ++ ("a") ++ (D) ++ ("cccaccca") ++ (D) ++ ("abccc") ++ (D) ++ ("b") ++ (D) ++ ("cc") ++ (D) ++ ("ac"))
    =
    (("a") ++ (D) ++ ("cc") ++ (D) ++ ("ac") ++ (D) ++ ("bcb") ++ (D) ++ ("c") ++ (D) ++ (D) ++ ("ac") ++ (D) ++ (D) ++ ("a") ++ (D) ++ ("cccacccababccc") ++ (D) ++ ("b") ++ (D) ++ ("cc") ++ (D) ++ ("ac"));
constraint
  (("abc") ++ (D) ++ ("aa") ++ (D) ++ ("acca") ++ (E) ++ ("ba") ++ (D) ++ ("c") ++ (D) ++ ("caaabac") ++ (D) ++ (D) ++ ("cccbbbca") ++ (D) ++ ("ac") ++ (D) ++ ("bcc"))
    =
    (("abc") ++ (D) ++ ("aabaccac") ++ (D) ++ ("ababcbcaaabac") ++ (D) ++ (D) ++ ("ccc") ++ (D) ++ ("bbca") ++ (D) ++ ("ac") ++ (D) ++ (D) ++ ("cc"));
constraint
  (("accab") ++ (D) ++ ("abbcaccabcbc") ++ (D) ++ ("a") ++ (D) ++ ("aaacaac") ++ (D) ++ ("caccacaba") ++ (D) ++ ("b") ++ (D) ++ ("a") ++ (D))
    =
    (("acca") ++ (D) ++ ("ba") ++ (D) ++ ("bcacca") ++ (D) ++ ("c") ++ (D) ++ ("c") ++ (D) ++ ("a") ++ (D) ++ ("aaacaac") ++ (D) ++ ("caccaca") ++ (D) ++ ("a") ++ (D) ++ ("b") ++ (D) ++ ("ab"));
constraint
  (("cbbacabcac") ++ (D) ++ ("cacac") ++ (D) ++ (D) ++ ("a") ++ (H) ++ (D) ++ (D) ++ ("caaacbabbc") ++ (D) ++ ("ccbacacc"))
    =
    (("c") ++ (D) ++ ("bacabcacbcacac") ++ (D) ++ ("ba") ++ (H) ++ ("b") ++ (D) ++ ("caaacbab") ++ (D) ++ ("cbcc") ++ (D) ++ ("acacc"));
constraint
  (("c") ++ (D) ++ (D) ++ ("ccccaabccbccba") ++ (D) ++ ("bacc") ++ (E) ++ ("acabbcacccaaca") ++ (D) ++ (D) ++ ("ac"))
    =
    (("c") ++ (D) ++ (D) ++ ("ccccaabccbccbabbacccbaacab") ++ (D) ++ ("cacccaaca") ++ (D) ++ (D) ++ ("ac"));
constraint
  (("cc") ++ (D) ++ (D) ++ (D) ++ (H) ++ (D) ++ ("cbacccc") ++ (D) ++ ("abbaa") ++ (D) ++ ("bbacabaa") ++ (D) ++ ("b") ++ (D) ++ (D) ++ (D) ++ ("ccaaa") ++ (D) ++ (D))
    =
    (("cc") ++ (D) ++ (D) ++ (D) ++ ("bc") ++ (D) ++ (D) ++ ("c") ++ (D) ++ ("accccba") ++ (D) ++ (D) ++ ("aab") ++ (D) ++ ("bacabaa") ++ (D) ++ ("bbbbccaaa") ++ (D) ++ (D));
constraint
  (("aaccbb") ++ (D) ++ ("a") ++ (D) ++ ("acaaca") ++ (D) ++ ("ccaa") ++ (D) ++ ("cbc") ++ (D) ++ ("a") ++ (D) ++ ("ccbb") ++ (D) ++ (D) ++ (D) ++ (D) ++ ("bab") ++ (D) ++ (D) ++ ("bca"))
    =
    (("aacc") ++ (D) ++ (D) ++ (D) ++ ("abacaaca") ++ (D) ++ ("ccaa") ++ (D) ++ ("c") ++ (D) ++ ("cba") ++ (D) ++ ("ccb") ++ (D) ++ (D) ++ (D) ++ (D) ++ ("bba") ++ (D) ++ (D) ++ ("b") ++ (D) ++ ("ca"));
constraint
  (("ccabcb") ++ (D) ++ ("accaccbca") ++ (H) ++ ("a") ++ (D) ++ ("acabaacaaac") ++ (D) ++ ("cc") ++ (H) ++ ("c") ++ (D) ++ ("b") ++ (D) ++ ("a"))
    =
    (("cca") ++ (H) ++ (D) ++ ("accacc") ++ (D) ++ ("ca") ++ (D) ++ ("c") ++ (D) ++ ("abacabaacaaacbcc") ++ (D) ++ ("c") ++ (D) ++ ("c") ++ (D) ++ ("bba"));
constraint
  (("cb") ++ (D) ++ (D) ++ ("ca") ++ (D) ++ ("cccc") ++ (D) ++ (H) ++ ("a") ++ (D) ++ ("c") ++ (D) ++ ("aba") ++ (D) ++ ("ccc") ++ (D) ++ ("acca") ++ (D) ++ (D) ++ ("bacbcc") ++ (D) ++ ("aca"))
    =
    (("cbbbcabcccc") ++ (D) ++ (D) ++ ("c") ++ (D) ++ ("a") ++ (H) ++ ("a") ++ (D) ++ ("abcc") ++ (E) ++ ("cca") ++ (D) ++ ("b") ++ (D) ++ ("acbccbaca"));
constraint
  (("cacccaaaccb") ++ (D) ++ ("ca") ++ (D) ++ ("c") ++ (E) ++ ("b") ++ (D) ++ ("acc") ++ (D) ++ ("b") ++ (H) ++ ("a") ++ (D) ++ ("ac") ++ (D) ++ ("aaca") ++ (D) ++ ("ca") ++ (D) ++ ("c"))
    =
    (("cacccaaaccbbca") ++ (D) ++ ("cc") ++ (D) ++ ("a") ++ (D) ++ (D) ++ ("acc") ++ (D) ++ ("b") ++ (H) ++ ("a") ++ (D) ++ ("a") ++ (E) ++ ("acabca") ++ (D) ++ ("c"));
constraint
  (("ca") ++ (D) ++ ("accccca") ++ (D) ++ ("acaacaaabababbacaaa") ++ (D) ++ ("bcabbabaccca"))
    = (("cabacccccabacaacaaababa") ++ (D) ++ (D) ++ ("acaaabbcabbabaccca"));
constraint
  ((D) ++ (D) ++ ("cccaaacacacabccaacaccbcabba") ++ (D) ++ ("caca") ++ (D) ++ ("accaaccb"))
    =
    ((D) ++ (D) ++ ("cccaaacacaca") ++ (D) ++ ("ccaacacc") ++ (D) ++ ("cabba") ++ (D) ++ ("cacabaccaaccb"));
constraint
  (("c") ++ (D) ++ ("abb") ++ (D) ++ ("ccaaaabaacba") ++ (D) ++ ("bcabbcaccabaabcca") ++ (D) ++ ("c") ++ (D) ++ ("abcb"))
    =
    (("c") ++ (D) ++ ("a") ++ (D) ++ (D) ++ (D) ++ ("ccaaaabaacba") ++ (D) ++ ("bcabbcacca") ++ (D) ++ ("aa") ++ (D) ++ ("cca") ++ (D) ++ (E) ++ ("bcb"));
constraint
  ((H) ++ ("cccabbc") ++ (D) ++ ("a") ++ (D) ++ ("c") ++ (D) ++ ("acc") ++ (D) ++ (D) ++ (D) ++ (D) ++ ("caccabcababcabaaacc") ++ (D) ++ ("b"))
    =
    ((D) ++ ("cbcccab") ++ (D) ++ ("c") ++ (D) ++ ("abc") ++ (D) ++ ("accbb") ++ (D) ++ (D) ++ ("cacca") ++ (D) ++ ("cababca") ++ (D) ++ ("aaacc") ++ (D) ++ ("b"));
constraint
  (("aabbcacbcca") ++ (D) ++ ("bb") ++ (D) ++ ("aaacaccb") ++ (D) ++ ("b") ++ (D) ++ ("ccaaca") ++ (H) ++ ("aabcaaac"))
    =
    (("aa") ++ (D) ++ ("bcac") ++ (D) ++ ("ccabbbbaaacacc") ++ (D) ++ (D) ++ (D) ++ (D) ++ ("ccaaca") ++ (D) ++ (E) ++ ("a") ++ (D) ++ ("caaac"));
constraint
  ((H) ++ (D) ++ (D) ++ ("ba") ++ (D) ++ (D) ++ ("aabccac") ++ (D) ++ ("c") ++ (D) ++ ("a") ++ (D) ++ ("ac") ++ (D) ++ ("acaa") ++ (D) ++ (D) ++ ("ca") ++ (D) ++ ("b") ++ (D) ++ ("aca") ++ (D) ++ ("caba"))
    =
    ((H) ++ ("b") ++ (D) ++ (D) ++ ("ab") ++ (D) ++ ("aa") ++ (D) ++ ("ccac") ++ (D) ++ (E) ++ ("bac") ++ (D) ++ ("acaa") ++ (D) ++ (D) ++ ("cab") ++ (D) ++ (D) ++ ("aca") ++ (D) ++ ("caba"));
constraint
  (("bc") ++ (D) ++ ("cbccc") ++ (H) ++ ("acbbab") ++ (D) ++ ("cacaaacb") ++ (H) ++ ("accabc") ++ (D) ++ ("accccbc"))
    =
    ((H) ++ ("cbccc") ++ (H) ++ ("acbba") ++ (D) ++ (D) ++ ("cacaaac") ++ (D) ++ (D) ++ ("c") ++ (D) ++ ("accabc") ++ (D) ++ ("accccbc"));
constraint
  (("baaaacaacbacaac") ++ (H) ++ ("ccaa") ++ (D) ++ ("cbcaacaca") ++ (D) ++ ("c") ++ (D) ++ ("accca") ++ (H))
    =
    ((D) ++ ("aaaacaac") ++ (D) ++ ("acaac") ++ (D) ++ ("cbccaa") ++ (D) ++ ("c") ++ (D) ++ ("caacacabc") ++ (D) ++ ("accca") ++ (H));
constraint
  (("abaccac") ++ (D) ++ ("c") ++ (D) ++ ("ac") ++ (H) ++ ("b") ++ (D) ++ ("acccbcabbbba") ++ (D) ++ (D) ++ ("aabcacaabcc") ++ (D))
    =
    (("a") ++ (D) ++ ("accac") ++ (H) ++ ("ac") ++ (D) ++ ("c") ++ (D) ++ (D) ++ (D) ++ ("accc") ++ (D) ++ ("ca") ++ (D) ++ (D) ++ (D) ++ (D) ++ ("a") ++ (D) ++ ("baabcacaabcc") ++ (D));
constraint
  (("cccbaba") ++ (D) ++ ("cac") ++ (D) ++ ("acbcc") ++ (D) ++ ("a") ++ (D) ++ (D) ++ (D) ++ (D) ++ ("abbccaabccaaaababa") ++ (D) ++ (D))
    =
    (("cccbaba") ++ (D) ++ ("cacbacbc") ++ (E) ++ ("bbbba") ++ (D) ++ (D) ++ ("ccaa") ++ (D) ++ ("ccaaaa") ++ (D) ++ ("ababb"));
constraint
  (("caccaabbcaaa") ++ (D) ++ (D) ++ ("cabcc") ++ (D) ++ ("accbccaacabc") ++ (D) ++ (D) ++ ("b") ++ (D) ++ ("cbbca") ++ (D) ++ ("c"))
    =
    (("caccaa") ++ (D) ++ ("bcaaabbcabcc") ++ (D) ++ ("accbccaacabc") ++ (D) ++ ("bbbc") ++ (D) ++ ("bca") ++ (D) ++ ("c"));
constraint
  (("bc") ++ (D) ++ ("ccac") ++ (D) ++ (D) ++ (D) ++ ("aab") ++ (D) ++ (D) ++ ("acacbbacacac") ++ (E) ++ ("aacaabaaa") ++ (D) ++ ("ca") ++ (D))
    =
    ((D) ++ ("c") ++ (D) ++ ("ccacbbbaa") ++ (D) ++ ("b") ++ (D) ++ ("acacb") ++ (D) ++ ("acacac") ++ (E) ++ ("aacaa") ++ (D) ++ ("aaa") ++ (D) ++ ("ca") ++ (D));
constraint
  (("accabcaa") ++ (D) ++ ("aba") ++ (D) ++ ("aaca") ++ (D) ++ ("b") ++ (D) ++ ("cabccca") ++ (D) ++ (D) ++ (D) ++ ("cbb") ++ (D) ++ ("ab") ++ (D) ++ ("acbaa") ++ (D))
    =
    (("acca") ++ (D) ++ ("caababa") ++ (D) ++ ("aaca") ++ (D) ++ (D) ++ (D) ++ ("ca") ++ (D) ++ ("cccabb") ++ (D) ++ ("cb") ++ (D) ++ ("bab") ++ (D) ++ ("acbaab"));
constraint
  (("acacca") ++ (H) ++ ("cbaa") ++ (D) ++ ("aaaac") ++ (D) ++ ("a") ++ (D) ++ ("cabaaacbcccbccab") ++ (D) ++ ("ccac"))
    =
    (("acaccabcbcbaabaaaac") ++ (D) ++ ("a") ++ (D) ++ ("ca") ++ (D) ++ ("aaac") ++ (D) ++ ("cccbccabbccac"));
constraint
  (("caacb") ++ (H) ++ ("cbbccaccbcaca") ++ (D) ++ ("ab") ++ (D) ++ ("a") ++ (D) ++ ("cbacccbaaaa") ++ (D) ++ ("caa") ++ (D))
    =
    (("caacb") ++ (D) ++ ("cbc") ++ (D) ++ ("bccacc") ++ (D) ++ ("caca") ++ (D) ++ ("ab") ++ (D) ++ ("a") ++ (D) ++ ("cbaccc") ++ (D) ++ ("aaaa") ++ (D) ++ ("caab"));
constraint
  (("cabac") ++ (D) ++ ("bacaacabccaac") ++ (D) ++ ("baaccaa") ++ (D) ++ ("cccacaaa") ++ (D) ++ (D) ++ ("cbaac"))
    =
    (("cabacbbacaaca") ++ (D) ++ ("ccaacb") ++ (D) ++ ("aaccaa") ++ (D) ++ ("cccacaaa") ++ (D) ++ (D) ++ ("cbaac"));
constraint
  (("cacccabc") ++ (D) ++ ("acacc") ++ (D) ++ (E) ++ (D) ++ ("acabccbaaaacb") ++ (D) ++ (E) ++ (D) ++ (D) ++ ("baa") ++ (D) ++ ("a"))
    =
    (("caccca") ++ (D) ++ ("cbacaccbc") ++ (D) ++ ("a") ++ (D) ++ ("acabcc") ++ (D) ++ ("aaaac") ++ (D) ++ ("b") ++ (E) ++ ("b") ++ (D) ++ ("baa") ++ (D) ++ ("a"));
constraint
  (("cc") ++ (D) ++ ("ca") ++ (H) ++ (D) ++ (E) ++ (D) ++ ("bbaa") ++ (D) ++ ("aaaab") ++ (D) ++ (D) ++ ("abbbccccacbaccacaa"))
    =
    (("cc") ++ (D) ++ ("ca") ++ (D) ++ ("cb") ++ (D) ++ ("c") ++ (D) ++ ("a") ++ (D) ++ (D) ++ ("baa") ++ (D) ++ ("aaaa") ++ (D) ++ (D) ++ ("ba") ++ (D) ++ (D) ++ (D) ++ ("ccccacbaccacaa"));
solve satisfy;
