var string: B;
var string: A;
constraint
  (("ababbababbbabababaababbbbbbbaabbbbbbbbbbbabaa") ++ ("")) =
    (("aba") ++ (B) ++ ("babaababbbbbbbaabbbbbbbbbbbabaa"));
constraint
  (("baaaaabbbaabbbabbbabbabbaaabbbaaaaba") ++ (A) ++ ("b")) =
    (("baaaaabbbaabbbabbbabbabbaaabbbaaaaba") ++ (A) ++ ("b"));
constraint
  (("baabbabbbbaaabbbbabaaa") ++ (A) ++ ("baabbaaabaabaaa")) =
    (("baabbabbbbaaabbbbabaaaababbbbbbaabbaaabaabaaa") ++ (""));
constraint
  (("baabbaaababbbbbabbaababaaaabaababbaabaaaaabba") ++ ("")) =
    (("baabbaa") ++ (A) ++ ("abbaababaaaabaababbaabaaaaabba"));
constraint
  (("bbbabaaaabaaaababbaaaaabbbaaaaabaababbbbbabba") ++ ("")) =
    (("bbbabaaaabaaaababbaaaaabbbaaaaaba") ++ (A) ++ ("abba"));
constraint
  (("aaabbbbaaabbaaabaabab") ++ (A) ++ ("aabbababbaabbabb")) =
    (("aaabbbbaaabbaaabaababababbbbbaabbababbaabbabb") ++ (""));
constraint
  (("babbaabbabaabaaaaaabbbbbbabaa") ++ (A) ++ ("babababa")) =
    (("babbaabbabaabaaaaaabbbbbbabaa") ++ (A) ++ ("babababa"));
constraint
  (("bbbbaaaaaaabbaabaababbaabaaabaab") ++ (A) ++ ("abaab")) =
    (("bbbbaaaaaaabbaabaababbaabaaabaab") ++ (A) ++ ("abaab"));
constraint
  (("aababbbbbaaaaabaabbaabbaba") ++ (A) ++ ("bbbbaababaa")) =
    (("aababbbbbaaaaabaabbaabbabaababbbbbbbbbaababaa") ++ (""));
constraint
  (("babbabaabaabababbaabbbbaaaabaabbbbbababbbbbbb") ++ ("")) =
    (("babbabaabaabababbaabbbbaaaabaabbbbb") ++ (A) ++ ("bb"));
constraint
  (("babababaaaa") ++ (A) ++ ("aaabbbbabbbabbabbbbbbaabba")) =
    (("babababaaaaababbbbbaaabbbbabbbabbabbbbbbaabba") ++ (""));
constraint
  (("abbaabbbaaaabbbbbabbbbaabababbbbbabbabbaaabab") ++ ("")) =
    (("abbaabbbaaaabbbbbabbbbaab") ++ (A) ++ ("abbabbaaabab"));
constraint
  (("bbbaaabbbbaaaabbbbbabaab") ++ (A) ++ ("aabaaaababbaa")) =
    (("bbbaaabbbbaaaabbbbbabaab") ++ (A) ++ ("aabaaaababbaa"));
constraint
  (("abbbaaaaaaabbabbbaaabaabababbababbbbbbababbbb") ++ ("")) =
    (("abbbaaaaaaabbabbbaaabaabababb") ++ (A) ++ ("bababbbb"));
constraint
  (("baaaabaabaaabaaababbbbbbabbbbaaaaabaabbbbaaab") ++ ("")) =
    (("baaaabaabaaabaa") ++ (A) ++ ("babbbbaaaaabaabbbbaaab"));
constraint
  ((A) ++ ("abaabbabaababaaaaabbabaabaaaabbabbbba") ++ ("")) =
    ((A) ++ ("abaabbabaababaaaaabbabaabaaaabbabbbba") ++ (""));
constraint
  (("aababbaaaaabbbababbaaaababbbbbabaaaaabababbaa") ++ ("")) =
    (("aababbaaaaabbbababbaaa") ++ (A) ++ ("abaaaaabababbaa"));
constraint
  (("abaaaabbbbbbabababbbbbbbbbababbbaaaababbbaaba") ++ ("")) =
    (("abaaaabbbbbbab") ++ (A) ++ ("bbbbababbbaaaababbbaaba"));
constraint
  (("bbaaabbbbaabbabaababaabbaabbbbbbbabab") ++ (A)) =
    (("bbaaabbbbaabbabaababaabbaabbbbbbbababababbbbb") ++ (""));
constraint
  (("bbbbaaababbaabbbaaabbbbbababbbbbb") ++ (A) ++ ("aabb")) =
    (("bbbbaaababbaabbbaaabbbbbababbbbbbababbbbbaabb") ++ (""));
constraint
  (("baaabbbaaaa") ++ (A) ++ ("aaaaabbbbabababaabababaaab")) =
    (("baaabbbaaaa") ++ (A) ++ ("aaaaabbbbabababaabababaaab"));
constraint
  (("abbbbaaaababbbaabaaababbbbbbababbaaaaabbaaabb") ++ ("")) =
    (("abbbbaaaababbbaabaa") ++ (A) ++ ("bababbaaaaabbaaabb"));
constraint
  (("bababbabaab") ++ (A) ++ ("bbabbaabbaabbababbaababbaa")) =
    (("bababbabaabababbbbbbbabbaabbaabbababbaababbaa") ++ (""));
constraint
  (("aaababbababbbababaabbbabbabbbabbbabbbbababbbb") ++ ("")) =
    (("aaaba") ++ (B) ++ ("baabbbabbabbbabbbabbbbababbbb"));
constraint
  (("ababaaaabababbbaabbbaa") ++ (A) ++ ("babababbabbabbb")) =
    (("ababaaaabababbbaabbbaa") ++ (A) ++ ("babababbabbabbb"));
constraint
  (("ababa") ++ (A) ++ ("bababbaabbabaaaaaaabbbbbaaababab")) =
    (("ababa") ++ (A) ++ ("bababbaabbabaaaaaaabbbbbaaababab"));
constraint
  (("bbaa") ++ (A) ++ ("aaaaabababaaaaabbaabbabbbaabaaaab")) =
    (("bbaaababbbbbaaaaabababaaaaabbaabbabbbaabaaaab") ++ (""));
constraint
  (("baaabaabaabbabaabbabbbabaaaabbbaaa") ++ (A) ++ ("aba")) =
    (("baaabaabaabbabaabbabbbabaaaabbbaaaababbbbbaba") ++ (""));
constraint
  (("bbbabbaababaaaaabaababaabbbb") ++ (A) ++ ("abbaaaaaa")) =
    (("bbbabbaababaaaaabaababaabbbbababbbbbabbaaaaaa") ++ (""));
constraint
  (("baababababbbaabaababbbbababbbababaababaabbaaa") ++ ("")) =
    (("baababababbbaabaababb") ++ (B) ++ ("baababaabbaaa"));
constraint
  (("bbaaabbbaba") ++ (A) ++ ("abababaaababbabaabbaaabbab")) =
    (("bbaaabbbaba") ++ (A) ++ ("abababaaababbabaabbaaabbab"));
constraint
  (("aaabaaaaabbabbbabbabaaaaabbaaabb") ++ (A) ++ ("aaaaa")) =
    (("aaabaaaaabbabbbabbabaaaaabbaaabb") ++ (A) ++ ("aaaaa"));
constraint
  (("bbababaabaabbbaaabbabaaababbbbbaabaaabaaababa") ++ ("")) =
    (("bbababaabaabbbaaabbabaa") ++ (A) ++ ("aabaaabaaababa"));
constraint
  (("aaabbbabaaabbabaabbabbbaababbbbbbbb") ++ (A) ++ ("bb")) =
    (("aaabbbabaaabbabaabbabbbaababbbbbbbb") ++ (A) ++ ("bb"));
constraint
  (("bbabaabbabbbaabbbabbabbaaaababababaaababbbbbb") ++ ("")) =
    (("bbabaabbabbbaabbbabbabbaaaababababaa") ++ (A) ++ ("b"));
constraint
  (("bbabbabbbaabababaaaabaaaaabaaabbabbaaababbbbb") ++ ("")) =
    (("bbabbabbbaabababaaaabaaaaabaaabbabbaa") ++ (A));
constraint
  (("ababbbbbbaababbabaaaaabbbbaaaaaabbbabaaabaaaa") ++ ("")) =
    ((A) ++ ("baababbabaaaaabbbbaaaaaabbbabaaabaaaa") ++ (""));
constraint
  (("bbaabaaabaaaaaabababbbabbbbbaabaaabaababbbbba") ++ ("")) =
    (("bbaabaaabaaaaaabababbbabbbbbaabaaaba") ++ (A) ++ ("a"));
constraint
  (("babbbabaabbbba") ++ (A) ++ ("baaabbaaaaababababbaaab")) =
    (("babbbabaabbbba") ++ (A) ++ ("baaabbaaaaababababbaaab"));
constraint
  (("ba") ++ (A) ++ ("bababbabbbbabaaaabbabbabababbbbbbbb")) =
    (("baababbbbbbababbabbbbabaaaabbabbabababbbbbbbb") ++ (""));
constraint
  (("abbbbaabaababbbbbbaabbbbaabbbabbbbaabaabbbbbb") ++ ("")) =
    (("abbbbaaba") ++ (A) ++ ("baabbbbaabbbabbbbaabaabbbbbb"));
constraint
  (("ababbbaababaababbbbbbabbaabbaaaabaabbaaaabbba") ++ ("")) =
    (("ababbbaababa") ++ (A) ++ ("babbaabbaaaabaabbaaaabbba"));
constraint
  (("babbaabab") ++ (B) ++ ("bbaabababaabbbababaabbbbb")) =
    (("babbaababbbababbbababbaabababaabbbababaabbbbb") ++ (""));
constraint
  (("baabababbbbbbababbabaababbbaaabbbbaaababbbaab") ++ ("")) =
    (("baab") ++ (A) ++ ("bababbabaababbbaaabbbbaaababbbaab"));
constraint
  (("babbaabaababaabaababbbaaaabaaaaaab") ++ (A) ++ ("aaa")) =
    (("babbaabaababaabaababbbaaaabaaaaaab") ++ (A) ++ ("aaa"));
constraint
  (("baaaaababbbbbbabbbaababbbaaabbababaaabababaaa") ++ ("")) =
    (("baaaa") ++ (A) ++ ("babbbaababbbaaabbababaaabababaaa"));
constraint
  (("bbabababbababaaabbabbbbaabaaabbababbbbbbbaaba") ++ ("")) =
    (("bbabababbababaaabbabbbbaabaaabb") ++ (A) ++ ("bbaaba"));
constraint
  (("baaaaabbbbbaabaaaaaabbaabbaabbbbaaabb") ++ (A)) =
    (("baaaaabbbbbaabaaaaaabbaabbaabbbbaaabb") ++ (A));
constraint
  (("bababbababbbbbbabaabbbbbbbabba") ++ (A) ++ ("abbbbab")) =
    (("bababbababbbbbbabaabbbbbbbabbaababbbbbabbbbab") ++ (""));
constraint
  (("bababaaabbabbaabaaabbbbb") ++ (B) ++ ("abbaaabaaa")) =
    (("bababaaabbabbaabaaabbbbb") ++ (B) ++ ("abbaaabaaa"));
constraint
  (("abbabababbbabbababbbaabbbbaaaaababbbbbaababba") ++ ("")) =
    (("abbabababbbabbababbbaabbbbaaaa") ++ (A) ++ ("aababba"));
solve satisfy;
