var string: A;
var string: C;
var string: D;
constraint
  (("adcdabdcaddcdabacaacbcb") ++ (C) ++ ("abacddddacdbcadbdccdcabdadbdcbcbabbddbbdcbcc"))
    = (("adcdabdcaddc") ++ (A) ++ ("dcabdadbdcbcbabbddbbdcbcc"));
constraint
  (("cdddadacccaa") ++ (C) ++ ("bdcdddaacbbcbabccadabddadbccddbcbabdcddccacddbbabddbbcb"))
    =
    (("cdddadacccaadabccbdcdddaacbbcbabccadabddadbccddbcbabdcddccacddbbabddbbcb") ++ (""));
constraint
  (("daddabccaabccddacdccddaddacbbaadcabdbacbaabdcabbcbdbdcdaaabaccbdbdbcbaaa") ++ (""))
    =
    (("dad") ++ (C) ++ ("aabccddacdccddaddacbbaadcabdbacbaabdcabbcbdbdcdaaabaccbdbdbcbaaa"));
constraint
  (("ad") ++ (C) ++ ("dcabcdbddbbdbbcaddcdbaccaddcaaccbddcbcdbbaaacaabbaddbdbbdabddbccc"))
    =
    (("addabccdcabcdbddbbdbbcaddcdbaccaddcaaccbddcbcdbbaaacaabbaddbdbbdabddbccc") ++ (""));
constraint
  (("adabbbcbabbacbabbcdbddbddacddabddabccdcdddabadbabadccdbddabddbaaaabbccdc") ++ (""))
    =
    (("adabbbcbabbacbabbcdbddbddacddabd") ++ (C) ++ ("dcdddabadbabadccdbddabddbaaaabbccdc"));
constraint
  (("bcdcacbcabcaccaabdccbaaccbdcd") ++ (C) ++ ("aacacccbbccabdbdbbdacabaddcaabdbcdccca"))
    =
    (("bcdcacbcabcaccaabdccbaaccbdcd") ++ (C) ++ ("aacacccbbccabdbdbbdacabaddcaabdbcdccca"));
constraint
  (("bbbccabbbadaddacbabbccdcaadadbbabdbccacbccacdbdacdabd") ++ (C) ++ ("bdbaadcbdbdbdd"))
    =
    (("bbbccabbbadaddacbabbccdcaadadbbabdbccacbccacdbdacdabddabccbdbaadcbdbdbdd") ++ (""));
constraint
  (("cbccaccadcdbcbb") ++ (C) ++ ("abcdbbcacdcacabccadbbcbdddbbdcbbbcdababbbbbbdadddadc"))
    =
    (("cbccaccadcdbcbbdabccabcdbbcacdcacabccadbbcbdddbbdcbbbcdababbbbbbdadddadc") ++ (""));
constraint
  (("aaacbcdaabdaacbcddcdadabbcadcaaabdcdcdabdad") ++ (C) ++ ("bdadbcbdbdcadcadcdcdddda"))
    =
    (("aaacbcdaabdaacbcddcdadabbcadcaaabdcdcdabdad") ++ (C) ++ ("bdadbcbdbdcadcadcdcdddda"));
constraint
  (("cdbddbaaaaacaadbdbbbabd") ++ (C) ++ ("dbddadbcbabdbbbccdababbccddbaadccadadadcccdc"))
    =
    (("cdbddbaaaaacaadbdbbbabddabccdbddadbcbabdbbbccdababbccddbaadccadadadcccdc") ++ (""));
constraint
  (("cbbbbcabadbdcabaddabcccdacbbcbdaaddbcadbabdacdccadccdcbaddbddbccbdabddcc") ++ (""))
    =
    (("cbbbbcabadbdcabad") ++ (C) ++ ("cdacbbcbdaaddbcadbabdacdccadccdcbaddbddbccbdabddcc"));
constraint
  (("bbbdadbbccac") ++ (C) ++ ("cacdcbbdaaccdddbcdcaccdacdccaadcdcbdcacacdabddcabbcddcd"))
    =
    (("bbbdadbbccacdabcccacdcbbdaaccdddbcdcaccdacdccaadcdcbdcacacdabddcabbcddcd") ++ (""));
constraint
  (("bdccdccbaababbdbaacdbcdccccdcbadccadcd") ++ (C) ++ ("aadbbdccaaaacdcdcbcbcbacaacab"))
    =
    (("bdccdccbaababbdbaacdbcdccccdcbadccadcddabccaadbbdccaaaacdcdcbcbcbacaacab") ++ (""));
constraint
  (("aacabdcbbdcbdbaacccdaadaaacadbbacabbcdacbabaadabccacccaccddcadddabdccddb") ++ (""))
    =
    (("aacabdcbbdcbdbaacccdaadaaacadbbacabbcdacbabaa") ++ (C) ++ ("acccaccddcadddabdccddb"));
constraint
  (("ccbcbadaddaaddcabdbbadacdbdbbbcdbbabbc") ++ (C) ++ ("dcbcddbbdcadadbbcbabccbccacda"))
    =
    (("ccbcbadaddaaddcabdbbadacdbdbbbcdbbabbc") ++ (C) ++ ("dcbcddbbdcadadbbcbabccbccacda"));
constraint
  (("caabadcbbcbaaacdcaccddddcbcba") ++ (C) ++ ("caadadabcdbdddcddbccacbdcaccbdbaaddadd"))
    =
    (("caabadcbbcbaaacdcaccddddcbcbadabcccaadadabcdbdddcddbccacbdcaccbdbaaddadd") ++ (""));
constraint
  (("cbdbcbbbaaddbdddbabcbadbcdbdddbdaddabdacdaaaadbdadabbacbdab") ++ (C) ++ ("dbbbcbcd"))
    =
    (("cbdbcbbbaaddbdddbabcbadbcdbdddbdaddabdacdaaaadbdadabbacbdab") ++ (C) ++ ("dbbbcbcd"));
constraint
  (("bdbcbdcbcacbdabccbdbccdcdddbaaaccabacccbdddcddadcabbaadadaaacdbddcbdaacb") ++ (""))
    =
    (("bdbcbdcbcacb") ++ (C) ++ ("bdbccdcdddbaaaccabacccbdddcddadcabbaadadaaacdbddcbdaacb"));
constraint
  (("ddcdcccddcadbdcdbcbacbcdcdadcbcabbadabc") ++ (C) ++ ("bbbaaadbbaabdcaccbbbddbdccbc"))
    =
    (("ddcdcccddcadbdcdbcbacbcdcdadcbcabbadabc") ++ (C) ++ ("bbbaaadbbaabdcaccbbbddbdccbc"));
constraint
  (("bbddbdddbbbdabdbabadaadbacaddbdcadddccbcbcdbabdcadbabcadcbbab") ++ (C) ++ ("bbcdbb"))
    =
    (("bbddbdddbbbdabdbabadaadbacaddbdcadddccbcbcdbabdcadbabcadcbbab") ++ (C) ++ ("bbcdbb"));
constraint
  (("dcbabbcccdbbccbdbacaacddbbdcabadbaabbcabbbdabddbcccbccbdbadcaabdabccccdc") ++ (""))
    =
    (("dcbabbcccdbbccbdbacaacddbbdcabadbaabbcabbbdabddbcccbccbdbadcaab") ++ (C) ++ ("ccdc"));
constraint
  (("cdaccac") ++ (C) ++ ("cdaadaabbbdbbacabdbbdbdacdbdabbccbdddbcdcdcabcaabcadbcdbbaac"))
    =
    (("cdaccacdabcccdaadaabbbdbbacabdbbdbdacdbdabbccbdddbcdcdcabcaabcadbcdbbaac") ++ (""));
constraint
  (("bdccdcadbc") ++ (C) ++ ("aaaacbaccaadabcccdcdbacadcbcaabadbbdbcbbdddddadbcdddabcba"))
    =
    (("bdccdcadbc") ++ (C) ++ ("aaaacbaccaadabcccdcdbacadcbcaabadbbdbcbbdddddadbcdddabcba"));
constraint
  (("bccdbbbabaacabbdcabadbdbbbdabccadabbbcbbcaadacbabbabccddacbbdadcdaababdc") ++ (""))
    =
    (("bccdbbbabaacabbdcabadbdbbb") ++ (C) ++ ("adabbbcbbcaadacbabbabccddacbbdadcdaababdc"));
constraint
  (("dbabdacdadcccabccbcabcacbddcddadbcadcbbbadcdcccbdcbdb") ++ (C) ++ ("dbacaaaddbbcdd"))
    =
    (("dbabdacdadcccabccbcabcacbddcddadbcadcbbbadcdcccbdcbdbdabccdbacaaaddbbcdd") ++ (""));
constraint
  (("bdbdddbdcccddabab") ++ (C) ++ ("acbacdbaacaaacbbacacdbbdaabadcbbaccccbabdcdccbdcbd"))
    =
    (("bdbdddbdcccddabab") ++ (C) ++ ("acbacdbaacaaacbbacacdbbdaabadcbbaccccbabdcdccbdcbd"));
constraint
  (("bccbcccccadbdcdabcbcadac") ++ (C) ++ ("aacbdaadcabadbaddcacbdddcbbadaadcdcbdbcdbdd"))
    =
    (("bccbcccccadbdcdabcbcadacdabccaacbdaadcabadbaddcacbdddcbbadaadcdcbdbcdbdd") ++ (""));
constraint
  (("aadbbcdbdbcacdcd") ++ (C) ++ ("acbaacaaccdaabadcbcbbcbaaabbcbcabdbcbcdccddbdaacbda"))
    =
    (("aadbbcdbdbcacdcddabccacbaacaaccdaabadcbcbbcbaaabbcbcabdbcbcdccddbdaacbda") ++ (""));
constraint
  (("dbdbddcabbacacacbbbaadcd") ++ (C) ++ ("adcbaddcddccddaabdaddddbdabacdccaabcbdbdcaa"))
    =
    (("dbdbddcabbacacacbbbaadcd") ++ (C) ++ ("adcbaddcddccddaabdaddddbdabacdccaabcbdbdcaa"));
constraint
  (("dcaadcddabaabadddbdbbbbdcbd") ++ (C) ++ ("baddababbbadbcddbbccddacacdccbaaabdaabca"))
    =
    (("dcaadcddabaabadddbdbbbbdcbd") ++ (C) ++ ("baddababbbadbcddbbccddacacdccbaaabdaabca"));
constraint
  (("d") ++ (C) ++ ("cbbbbbbaddddbbdaddabbacdcbcadcabacbbaabbaacbbabcabbabcbbadacbbdcac"))
    =
    (("ddabcccbbbbbbaddddbbdaddabbacdcbcadcabacbbaabbaacbbabcabbabcbbadacbbdcac") ++ (""));
constraint
  (("daddcddacbabaddabccbdcaccddcdbcaaadbdcbdcbcaabcddada") ++ (C) ++ ("cdabbacbbaccdba"))
    =
    (("daddcddacbabaddabccbdcaccddcdbcaaadbdcbdcbcaabcddada") ++ (C) ++ ("cdabbacbbaccdba"));
constraint
  (("aacbdabccbaabccabdcddcdcccaabdabacddcaaaddddbdacaabddacddbdcccbacbaaaabb") ++ (""))
    =
    (("aacb") ++ (C) ++ ("baabccabdcddcdcccaabdabacddcaaaddddbdacaabddacddbdcccbacbaaaabb"));
constraint
  (("daadccdbcbacdbaccccddabcbcacacbcbbaccccdbadadcdabaacacbaccc") ++ (C) ++ ("bababacd"))
    =
    (("daadccdbcbacdbaccccddabcbcacacbcbbaccccdbadadcdabaacacbaccc") ++ (C) ++ ("bababacd"));
constraint
  (("ccaabcaddcadaabacbaaaccdcccaadaacbbcb") ++ (C) ++ ("bdbdcadcbcabaadaaddbbbacbbcccb"))
    =
    (("ccaabcaddcadaabacbaaaccdcccaadaacbbcb") ++ (C) ++ ("bdbdcadcbcabaadaaddbbbacbbcccb"));
constraint
  (("cbccdadabdcadaacaabccbccdaadcbcbadadddbcdabcccbbbadaaacbccdaadacdcdbbbcc") ++ (""))
    =
    (("cbccdadabdcadaacaabccbccdaadcbcbadadddbc") ++ (C) ++ ("cbbbadaaacbccdaadacdcdbbbcc"));
constraint
  (("bbdbdbdaddbcadcdbabbccdbadada") ++ (C) ++ ("dcaaabaaccddabdadcdddbcbadccdadddbadcc"))
    =
    (("bbdbdbdaddbcadcdbabbccdbadada") ++ (C) ++ ("dcaaabaaccddabdadcdddbcbadccdadddbadcc"));
constraint
  (("bccdcadbdbcbdcdacaddddbbbbcbcadbaddbcaadbbbbadababa") ++ (C) ++ ("dddcddabbadbdbcc"))
    =
    (("bccdcadbdbcbdcdacaddddbbbbcbcadbaddbcaadbbbbadababa") ++ (C) ++ ("dddcddabbadbdbcc"));
constraint
  (("adbdbdddbcbdacdaadccdabaddadcdccaccdbbabacaaacccaadbbcacdabdadabccbccadd") ++ (""))
    =
    (("adbdbdddbcbdacdaadccdabaddadcdccaccdbbabacaaacccaadbbcacdabda") ++ (C) ++ ("bccadd"));
constraint
  (("bcbcdaaddaaaaaabbadcacbbcbddaccbccbdabcdbbbbcabbdcbacddcdcbadacdabccaabb") ++ (""))
    =
    (("bcbcdaaddaaaaaabbadcacbbcbddaccbccbdabcdbbbbcabbdcbacddcdcbadac") ++ (C) ++ ("aabb"));
constraint
  (("cbadbcdbddaaaabcadbcbcddadbbbadcacbbbbbab") ++ (C) ++ ("bdadadababddadbadcdadaccad"))
    =
    (("cbadbcdbddaaaabcadbcbcddadbbbadcacbbbbbab") ++ (C) ++ ("bdadadababddadbadcdadaccad"));
constraint
  (("bcaacddabbacbcaaadadcdddbcddcabadabbbcaabdbdaabdbacadcdacccdabccbdadcaad") ++ (""))
    =
    (("bcaacddabbacbcaaadadcdddbcddcabadabbbcaabdbdaabdbacadcdaccc") ++ (C) ++ ("bdadcaad"));
constraint
  (("acbbbcaabbdaadacdbdbbdbaccbccdddbdbcbcc") ++ (C) ++ ("dcdbddabaaacaabbbaabacbbdbaa"))
    =
    (("acbbbcaabbdaadacdbdbbdbaccbccdddbdbcbccdabccdcdbddabaaacaabbbaabacbbdbaa") ++ (""));
constraint
  (("abcacbaaccccddbbaccaacacddabccaaaacdbccbaadccbcbddadbadaddcbccdabdcacccb") ++ (""))
    =
    (("abcacbaaccccddbbaccaacacd") ++ (C) ++ ("aaaacdbccbaadccbcbddadbadaddcbccdabdcacccb"));
constraint
  (("dcabbaabdaadabccbbaddcbbadacccbdacdbbddaccadddcccaaabadabdaabcdcdaacbcbd") ++ (""))
    =
    (("dcabbaabdaa") ++ (C) ++ ("bbaddcbbadacccbdacdbbddaccadddcccaaabadabdaabcdcdaacbcbd"));
constraint
  (("caaccbcccdacbdcccbddcdbbacbbcadddacadacddccdabcdbcadadcdcbbaaaad") ++ (C) ++ ("bba"))
    =
    (("caaccbcccdacbdcccbddcdbbacbbcadddacadacddccdabcdbcadadcdcbbaaaad") ++ (C) ++ ("bba"));
constraint
  (("bdddcddcabccbbccdbdcaaabddcddddcabdacdabcbcaacddabcdbdddcadacbdabcccbcda") ++ (""))
    =
    (("bdddcddcabccbbccdbdcaaabddcddddcabdacdabcbcaacddabcdbdddcadacb") ++ (C) ++ ("cbcda"));
constraint
  (("bcaadddbdcaadbcbacdcdadaaddabdacbdad") ++ (C) ++ ("caccabadacadcbacbbcdcddaadbbacc"))
    =
    (("bcaadddbdcaadbcbacdcdadaaddabdacbdaddabcccaccabadacadcbacbbcdcddaadbbacc") ++ (""));
constraint
  (("bccdbaadaccbbaddcdcabdcadcddcbcbdcbcdddacdcadaacdddbcbacdbbdcccacbabdada") ++ (""))
    =
    (("bccdbaadaccbbaddcdcabdcadcddcbcbdc") ++ (D) ++ ("cbacdbbdcccacbabdada"));
constraint
  (("badddc") ++ (C) ++ ("bbacbbabbbdcabdcccdbcd")) =
    (("badddcbccbdbddadcbcabbccaaccdddbcdcdcbabdddbdacadcbbacbbabbbdcabdcccdbcd") ++ (""));
constraint
  (("dabacdbadbbbd") ++ (A) ++ ("bcb") ++ (D) ++ ("acbcdbddc")) =
    (("dab") ++ (A) ++ ("dbadbbbd") ++ (A) ++ ("bcbccdbddbadc") ++ (A) ++ ("bbddadccccddddbdbbabbabcccdddbcbbacbcdbddc"));
constraint
  (("acaadacdbaacbdacccbababcdabcdabccabcbbaddaddbdacacbabbbcbcd") ++ (A) ++ ("c") ++ (A) ++ ("bbdac") ++ (A) ++ ("a"))
    =
    (("acaad") ++ (A) ++ ("dbaacbdacccbababcdabcdabccabcbbaddaddbdac") ++ (A) ++ ("babbbcbcdaccacbbdac") ++ (A) ++ ("a"));
constraint
  (("dcadcbdabccbccbdabdcbbbbacba") ++ (A) ++ ("cabcaddabaaadbabbbdadcccbbaadcadbaadbbadba"))
    =
    (("dcadcbdabccbccbdabdcbbbbacba") ++ (A) ++ ("cabcaddabaaadbabbbdadcccbbaadcadbaadbbadba"));
constraint
  (("cabdddbdccbabbdcbadcadaabbcdaddaadcdbcbcdcdcadccbdbddcaaabbbcad") ++ (A) ++ ("bcbadcc"))
    =
    (("cabdddbdccbabbdcbadcadaabbcdaddaadcdbcbcdcdcadccbdbddcaaabbbcadacbcbadcc") ++ (""));
constraint
  (("dbabaaacccccdcda") ++ (A) ++ ("bdccbbddaaabbad") ++ (A) ++ ("dddaddbcabcabbcddbccabbbdadabdbadcbcd"))
    =
    (("dbabaa") ++ (A) ++ ("ccccdcda") ++ (A) ++ ("bdccbbddaaabbad") ++ (A) ++ ("dddaddbcabcabbcddbccabbbdadabdbadcbcd"));
constraint
  (("dbba") ++ (A) ++ ("bdddcadddacadbccddbbdccacbcaadaadbaadbddcd") ++ (A) ++ ("cabcaaadbcbad") ++ (A) ++ ("aaccdba"))
    =
    (("dbba") ++ (A) ++ ("bdddcadddacadbccddbbdccacbcaadaadbaadbddcdaccabcaaadbcbad") ++ (A) ++ ("aaccdba"));
constraint
  (("abbdacbbcbcbdbdbbabdccdbcdcaaaadcccacabadcdbdcaddcdbbccbcaabdcabbaaddadb") ++ (""))
    =
    (("abbd") ++ (A) ++ ("bbcbcbdbdbbabdccdbcdcaaaadccc") ++ (A) ++ ("abadcdbdcaddcdbbccbcaabdcabbaaddadb"));
constraint
  (("dbacdaaadadbc") ++ (A) ++ ("ccdcbcabdcbbcdabccaadddabaabdadabadcdcbc") ++ (A) ++ ("addccdc") ++ (A) ++ ("accdad"))
    =
    (("dbacdaaadadbcacccdcbcabdcbbcdabccaadddabaabdadabadcdcbcacaddccdcacaccdad") ++ (""));
constraint
  (("ccdcbcddcadacabddadcdcdbdabcabacbdbaa") ++ (A) ++ ("cdddbddddcaaaabdcabbcadbbbdbcdcca"))
    =
    (("ccdcbcddcadacabddadcdcdbdabcabacbdbaaaccdddbddddcaaaabdcabbcadbbbdbcdcca") ++ (""));
constraint
  (("cbbbaddabcdbcdaadbabcbbcbcccaccdabdcdbabbdbdbb") ++ (A) ++ ("addabddbabadccda") ++ (A) ++ ("cdacda"))
    =
    (("cbbbaddabcdbcdaadbabcbbcbccc") ++ (A) ++ ("cdabdcdbabbdbdbb") ++ (A) ++ ("addabddbabadccdaaccd") ++ (A) ++ ("da"));
constraint
  (("cadbdcadcbbabcbccccaabcddabaadcdcbbabcbadcdcbcdcccb") ++ (A) ++ ("bcbbacdbdc") ++ (A) ++ ("bcdbbdc"))
    =
    (("cadbdcadcbbabcbccccaabcddabaadcdcbbabcbadcdcbcdcccb") ++ (A) ++ ("bcbb") ++ (A) ++ ("dbdcacbcdbbdc"));
constraint
  (("dc") ++ (A) ++ ("adaabdacabcdbcaabbbdbbcdbbc") ++ (A) ++ ("caccbbccaabbadcaaabaadaaadaadbcacdbcbca"))
    =
    (("dcacadaabdacabcdbcaabbbdbbcdbbcaccaccbbccaabbadcaaabaadaaadaadbc") ++ (A) ++ ("dbcbca"));
constraint
  (("ccbcbdca") ++ (A) ++ ("dcaccbdabdbdbababccbcacabbbbbbbcabcabbbcdabccddbbdbdbcc") ++ (A) ++ ("abb") ++ (A))
    =
    (("ccbcbdcaacdc") ++ (A) ++ ("cbdabdbdbababccbcacabbbbbbbcabcabbbcdabccddbbdbdbcc") ++ (A) ++ ("abbac"));
constraint
  ((A) ++ ("adcaabaaddccacdccdbadcdaadbddcdcdbdbadcabcd") ++ (A) ++ ("aaaadccaabbcc") ++ (A) ++ ("caccdbddcc"))
    =
    (("acadcaabaaddccacdccdbadcdaadbddcdcdbdbadcabcdacaaaadccaabbccaccaccdbddcc") ++ (""));
constraint
  (("dabccadadbcabbdcdccb") ++ (A) ++ ("cdbbddcda") ++ (A) ++ ("cdd") ++ (A) ++ ("dcdcbccabaddbdaadcdbdbbddcbdbaabdd"))
    =
    (("dabccadadbcabbdcdccbaccdbbddcda") ++ (A) ++ ("cdd") ++ (A) ++ ("dcdcbccabaddbdaadcdbdbbddcbdbaabdd"));
constraint
  (("aadbddcaadcbddbccddabbddbbcbbbb") ++ (A) ++ ("baaadbadaaddbdcdaddadaacdccccacddacddac"))
    =
    (("aadbddcaadcbddbccddabbddbbcbbbbacbaaadbadaaddbdcdaddadaacdccccacdd") ++ (A) ++ ("dd") ++ (A));
constraint
  (("cdcdabac") ++ (A) ++ ("bbcbdabadaadcdbaabbda") ++ (A) ++ ("addcbcbdbbcabdcdbbdcab") ++ (A) ++ ("dbb") ++ (A) ++ ("c") ++ (A) ++ ("dcbaddc"))
    =
    (("cdcdabacacbbcbdabadaadcdbaabbdaacaddcbcbdbbcabdcdbbdcab") ++ (A) ++ ("dbbaccacdcbaddc"));
constraint
  (("cddcb") ++ (A) ++ ("cd") ++ (A) ++ ("dbadcbabbbcdc") ++ (A) ++ ("adaddbaaddcbbdcbdaadababcdadbcbbcdccadbdddbb") ++ (A))
    =
    (("cddcb") ++ (A) ++ ("cd") ++ (A) ++ ("dbadcbabbbcdc") ++ (A) ++ ("adaddbaaddcbbdcbdaadababcdadbcbbcdccadbdddbbac"));
constraint
  (("daddbdcdbbbbcdbadddbcbdddcbbcbcbacb") ++ (A) ++ ("caadcdcbadbacdbacddbacbbbbcaacdcaad"))
    =
    (("daddbdcdbbbbcdbadddbcbdddcbbcbcb") ++ (A) ++ ("b") ++ (A) ++ ("caadcdcbadb") ++ (A) ++ ("db") ++ (A) ++ ("ddb") ++ (A) ++ ("bbbbca") ++ (A) ++ ("dcaad"));
constraint
  (("aabbdcb") ++ (A) ++ ("cddcbcddcbbcb") ++ (A) ++ ("bcabcacdcadaabbbd") ++ (A) ++ ("abacbcabdbbccdadbabaadcddbcba"))
    =
    (("aabbdcbaccddcbcddcbbcbacbcabcacdcadaabbbdacabacbcabdbbccdadbabaadcddbcba") ++ (""));
constraint
  (("ddbaabccaaababddaabddabcdccbcccc") ++ (A) ++ (A) ++ ("babcdcccddabdbdddbaddabcbdbbdacdaacd"))
    =
    (("ddbaabccaaababddaabddabcdccbccccac") ++ (A) ++ ("babcdcccddabdbdddbaddabcbdbbd") ++ (A) ++ ("daacd"));
constraint
  (("dadbbbc") ++ (A) ++ ("dbbabcadcdcabbdccadabbd") ++ (A) ++ ("dabcacdcbadbadccacabbbbdbdcddaddcbaabb"))
    =
    (("dadbbbc") ++ (A) ++ ("dbbabcadcdcabbdccadabbdacdabc") ++ (A) ++ ("dcbadbadccacabbbbdbdcddaddcbaabb"));
constraint
  (("bd") ++ (A) ++ ("bbdcdabcb") ++ (A) ++ ("adbdcacbdddbbbdbaababcbaddbacdabddbcdadbadbdabad") ++ (A) ++ ("acbcdad"))
    =
    (("bdacbbdcdabcb") ++ (A) ++ ("adbdc") ++ (A) ++ ("bdddbbbdbaababcbaddbacdabddbcdadbadbdabad") ++ (A) ++ (A) ++ ("bcdad"));
constraint
  (("cabcddcaadabbccadbdbdbccbaaaacdbabda") ++ (A) ++ ("dbccabaccddbabbacabbcddcdcbddbbdbd"))
    =
    (("cabcddcaadabbccadbdbdbccbaaaacdbabdaacdbccab") ++ (A) ++ ("cddbabbacabbcddcdcbddbbdbd"));
constraint
  (("bcadccbadbdbbbcccbcccbdbddaddcadbbcabcddbdaaa") ++ (A) ++ ("bccd") ++ (A) ++ ("badcb") ++ (A) ++ ("cacaaddbbbbb"))
    =
    (("bcadccbadbdbbbcccbcccbdbddaddcadbbcabcddbdaaa") ++ (A) ++ ("bccd") ++ (A) ++ ("badcbaccacaaddbbbbb"));
constraint
  (("dcbcdbbbdabcabbbb") ++ (A) ++ ("cbcdbacdcdddcbab") ++ (A) ++ ("ddcccdadbccdbbbbcdbda") ++ (A) ++ ("babdcc") ++ (A) ++ ("bcdb"))
    =
    (("dcbcdbbbdabcabbbb") ++ (A) ++ ("cbcdb") ++ (A) ++ ("dcdddcbab") ++ (A) ++ ("ddcccdadbccdbbbbcdbda") ++ (A) ++ ("babdccacbcdb"));
constraint
  (("bbacbcbdddcdadabaadadcdbadbcbca") ++ (A) ++ ("bdbbddabcbcdabbcbcbcbccddccadbccddcbdbb"))
    =
    (("bb") ++ (A) ++ ("bcbdddcdadabaadadcdbadbcbca") ++ (A) ++ ("bdbbddabcbcdabbcbcbcbccddccadbccddcbdbb"));
constraint
  (("b") ++ (A) ++ ("ababbbddabccdcccbdcbdabaadcbacdbccbcbbddaaddccdbd") ++ (A) ++ ("cdbbbaaabdbbdbdcaa"))
    =
    (("bacababbbddabccdcccbdcbdabaadcbacdbccbcbbddaaddccdbdaccdbbbaaabdbbdbdcaa") ++ (""));
constraint
  (("acbbacaadababcdc") ++ (A) ++ ("babcbcdcadabcaacccbdbccbdabdcbc") ++ (A) ++ ("dcadadadbddbcbddbcb") ++ (A))
    =
    (("acbb") ++ (A) ++ ("aadababcdc") ++ (A) ++ ("babcbcdcadabcaacccbdbccbdabdcbc") ++ (A) ++ ("dcadadadbddbcbddbcb") ++ (A));
constraint
  (("dbdbdacadabaa") ++ (A) ++ ("ddacaaaaaddcccadcdaabdbbbaba") ++ (A) ++ ("cbdcdddadacbcabcdb") ++ (A) ++ ("daaaaca"))
    =
    (("dbdbdacadabaaacddacaaaaaddcccadcdaabdbbbabaaccbdcdddadacbcabcdbacdaaaaca") ++ (""));
constraint
  ((A) ++ (A) ++ ("ccbadccbddabdbbacbdbdabadcbcadbdcdbcbaccdabdbdbacabbdbdbabaaabcdccdb"))
    =
    ((A) ++ ("acccbadccbddabdbb") ++ (A) ++ ("bdbdabadcbcadbdcdbcbaccdabdbdbacabbdbdbabaaabcdccdb"));
constraint
  (("cacbaa") ++ (A) ++ ("dababbadbabbdbadabba") ++ (A) ++ ("ccbbbbbadbbbdccbadabaaabbabbcccaacabdcabbb"))
    =
    (("cacbaa") ++ (A) ++ ("dababbadbabbdbadabbaacccbbbbbadbbbdccbadabaaabbabbcccaacabdcabbb"));
constraint
  (("ac") ++ (A) ++ ("cbcacddaddcdaabcdcaccbbaaaacaabdaabdbcabcbdabcbadccaaaaadadbaabba") ++ (A) ++ ("b"))
    =
    ((A) ++ ("accbc") ++ (A) ++ ("ddaddcdaabcdc") ++ (A) ++ ("cbbaaaacaabdaabdbcabcbdabcbadccaaaaadadbaabbaacb"));
constraint
  (("cbabcbbbabdddbcdbdddcbd") ++ (A) ++ ("c") ++ (A) ++ ("adcccdcccccccbbabcddaacadccddbcdbabdadccdbac"))
    =
    (("cbabcbbbabdddbcdbdddcbdacc") ++ (A) ++ ("adcccdcccccccbbabcdda") ++ (A) ++ ("adccddbcdbabdadccdbac"));
constraint
  ((A) ++ ("babbadabbdcabdada") ++ (A) ++ ("acadbcbcdbdc") ++ (A) ++ ("ddabadddccadcaabddddcbcdaabaccaababcd"))
    =
    (("acbabbadabbdcabdadaacacadbcbcdbdc") ++ (A) ++ ("ddabadddccadcaabddddcbcdaab") ++ (A) ++ ("caababcd"));
constraint
  (("dabccb") ++ (A) ++ ("babaaabbbdbbacbbcbddaaabc") ++ (A) ++ ("bcdbbbdbdabcdbcdababccacdbdcddccbb") ++ (A) ++ ("b"))
    =
    (("dabccb") ++ (A) ++ ("babaaabbbdbbacbbcbddaaabcacbcdbbbdbdabcdbcdababcc") ++ (A) ++ ("dbdcddccbb") ++ (A) ++ ("b"));
constraint
  (("adcadaabcdbba") ++ (A) ++ ("dadababcbdbaadaaabddabaabbadddbcdcbacddcbcbbbabcdabbd") ++ (A) ++ ("ab"))
    =
    (("adcadaabcdbbaacdadababcbdbaadaaabddabaabbadddbcdcbacddcbcbbbabcdabbd") ++ (A) ++ ("ab"));
constraint
  (("bacabcbaddcadaacdcc") ++ (A) ++ ("bb") ++ (A) ++ ("bbddcbabcbcabcadcddcaaadcbcad") ++ (A) ++ ("bcabcdabba") ++ (A) ++ ("ccbd"))
    =
    (("bacabcbaddcadaacdcc") ++ (A) ++ ("bb") ++ (A) ++ ("bbddcbabcbcabcadcddcaaadcbcadacbcabcdabbaacccbd"));
constraint
  (("baccccabdbbbabcbdaaccdadcaaadaacbbbd") ++ (A) ++ ("bdabccbcccddcadadadaadbbdddadddcbb"))
    =
    (("baccccabdbbbabcbda") ++ (A) ++ ("cdadcaaadaacbbbdacbdabccbcccddcadadadaadbbdddadddcbb"));
constraint
  (("bbabbbc") ++ (A) ++ ("badaadbdbdbdbbadbbcbacdabccdbabdddbcd") ++ (A) ++ ("acdbdddcbadbbdaa") ++ (A) ++ ("cdacdd"))
    =
    (("bbabbbcacbadaadbdbdbdbbadbbcb") ++ (A) ++ ("dabccdbabdddbcd") ++ (A) ++ (A) ++ ("dbdddcbadbbdaaaccd") ++ (A) ++ ("dd"));
constraint
  (("dcbbaaaaabbbdbdcdccdbcbcbbbdbccbbabdabbacdd") ++ (A) ++ ("acbdcbbbdaddaddddcccaddcbcd"))
    =
    (("dcbbaaaaabbbdbdcdccdbcbcbbbdbccbbabdabbacddacacbdcbbbdaddaddddcccaddcbcd") ++ (""));
constraint
  (("caadadaaddcdb") ++ (A) ++ ("dbabbbabadaddadbdbcaabcdbdcdbbdbcdbdababacbaabcdabcabadcd"))
    =
    (("caadadaaddcdb") ++ (A) ++ ("dbabbbabadaddadbdbcaabcdbdcdbbdbcdbdababacbaabcdabcabadcd"));
constraint
  (("bdcbbcbdadabcbdccdadcccacbcdadcaacdbccdcaccdadadcddcbbbabccbd") ++ (A) ++ ("bd") ++ (A) ++ ("dcbac"))
    =
    (("bdcbbcbdadabcbdccdadcccacbcdadca") ++ (A) ++ ("dbccdcaccdadadcddcbbbabccbdacbdacdcbac"));
constraint
  (("dddbcd") ++ (A) ++ ("aabdcdccacdbdccbabaadabddaab") ++ (A) ++ ("adaabcabddbdcbdadcbdabcbbcaa") ++ (A) ++ ("bddc"))
    =
    (("dddbcd") ++ (A) ++ ("aabdcdccacdbdccbabaadabddaab") ++ (A) ++ ("adaabcabddbdcbdadcbdabcbbcaaacbddc"));
constraint
  (("dadaaaccbdcdccbdddbcdbccbcbbbd") ++ (A) ++ ("daaabbabbaaddbbbcdbacdcbaabcbdbaadbbdbad"))
    =
    (("dadaa") ++ (A) ++ ("cbdcdccbdddbcdbccbcbbbdacdaaabbabbaaddbbbcdbacdcbaabcbdbaadbbdbad"));
constraint
  (("ddcaa") ++ (A) ++ ("daabdbccccddaccbcdc") ++ (A) ++ ("cbcbdcdadccbdabcdcdbbbdadaabbdccbdadccadcaac"))
    =
    (("ddcaaacdaabdbccccdd") ++ (A) ++ ("cbcdc") ++ (A) ++ ("cbcbdcdadccbdabcdcdbbbdadaabbdccbdadccadca") ++ (A));
constraint
  (("bdcdbbcb") ++ (A) ++ ("abadcaaaadaad") ++ (A) ++ ("a") ++ (A) ++ ("adadbdbbbbadcabacccbcaaaddabbbaabdadaaacabbd"))
    =
    (("bdcdbbcbacabadcaaaadaad") ++ (A) ++ ("aacadadbdbbbbadcab") ++ (A) ++ ("ccbcaaaddabbbaabdadaaacabbd"));
constraint
  (("caaabacaaaacdcbbdbccabbadbddabacbcaadbcadcbdadddaacaaadcbcababa") ++ (A) ++ ("badbaca"))
    =
    (("caaabacaaa") ++ (A) ++ ("dcbbdbccabbadbddabacbcaadbcadcbdadddaacaaadcbcababaacbadb") ++ (A) ++ ("a"));
constraint
  (("dcdabdabbaacdbddbccbdbdcdaddabbbcbdddbccddadb") ++ (A) ++ ("dddddbbbddcdabcbbbbbccddb"))
    =
    (("dcdabdabbaacdbddbccbdbdcdaddabbbcbdddbccddadbacdddddbbbddcdabcbbbbbccddb") ++ (""));
constraint
  (("acacacbdacbabccccdaaadbddcbbbbbbbadbababdcddbdbbadcd") ++ (A) ++ ("ccadcdddccdbbccadc"))
    =
    ((A) ++ (A) ++ ("acbdacbabccccdaaadbddcbbbbbbbadbababdcddbdbbadcd") ++ (A) ++ ("ccadcdddccdbbccadc"));
constraint
  (("caaddaaddccabcbdbdbcadadddbcbcbdbccadbbbcacacaadabaabaaadcdccac") ++ (A) ++ ("dbdbabb"))
    =
    (("caaddaaddccabcbdbdbcadadddbcbcbdbccadbbbc") ++ (A) ++ ("acaadabaabaaadcdcc") ++ (A) ++ ("acdbdbabb"));
constraint
  (("ddbdbdcdcabccdaaddad") ++ (A) ++ ("abcacadbd") ++ (A) ++ ("badbcddcacabdabcbccdbcdcaccbbd") ++ (A) ++ ("abbcaca"))
    =
    (("ddbdbdcdcabccdaaddadacabc") ++ (A) ++ ("adbdacbadbcddc") ++ (A) ++ ("abdabcbccdbcdcaccbbdacabbc") ++ (A) ++ ("a"));
constraint
  (("daadaaaa") ++ (A) ++ ("ddcdbdd") ++ (A) ++ ("b") ++ (A) ++ ("dcccbbddbcdddcdbcbbaaddcaddbcdabcabdddddcbccddcabd"))
    =
    (("daadaaaa") ++ (A) ++ ("ddcdbdd") ++ (A) ++ ("b") ++ (A) ++ ("dcccbbddbcdddcdbcbbaaddcaddbcdabcabdddddcbccddcabd"));
constraint
  (("bbcaabddabb") ++ (A) ++ ("aaddc") ++ (A) ++ ("babcdaabdaddbbdbdaddabbabcadaddcbcdabdcbabddabdaadad"))
    =
    (("bbcaabddabbacaaddcacbabcdaabdaddbbdbdaddabbabcadaddcbcdabdcbabddabdaadad") ++ (""));
constraint
  (("dbbbaddcddcbaaadddabcbdbbccbccbddbbcadadacdc") ++ (A) ++ ("caccbaabbdbdccacacbcdddacc"))
    =
    (("dbbbaddcddcbaaadddabcbdbbccbccbddbbcadad") ++ (A) ++ ("dcacc") ++ (A) ++ ("cbaabbdbdcc") ++ (A) ++ (A) ++ ("bcddd") ++ (A) ++ ("c"));
solve satisfy;
