var string: B;
var string: E;
var string: G;
var string: F;
var string: A;
var string: C;
var string: D;
constraint
  (("ebebdcacbddacdb") ++ (D) ++ ("bcdecdeacbacdcbcadbbcbaeadaaddcbebdadccba"))
    =
    (("ebebdcacbddac") ++ (G) ++ ("dbdaebbdeb") ++ (E) ++ ("cbcadbbcbaeadaaddcbebdadccba"));
constraint
  (("dbbdaceccdccdcacdbbeaaccacadbbbadbebedcbabeaeed") ++ (G) ++ ("cdabbaceececeeacedb"))
    =
    (("dbbdaceccdccdcacdbbeaaccacadbbbadbebedcbabeaeed") ++ (G) ++ ("cdabbaceececeeacedb"));
constraint
  (("cdbcddee") ++ (E) ++ ("a")) =
    (("cdbcddeeabbddbaeebbcedecdcb") ++ (C) ++ ("abbddecbacedcbdbadbadbbaeebabaa"));
constraint
  (("deeaddaacbccedba") ++ (A) ++ ("aeebcaadadbee") ++ (B) ++ ("aaedbcdeaacdedbecabcaaaeddaedb"))
    = (("deead") ++ (F) ++ ("adbeecbbceedaaedbcdeaacdedbecabcaaaeddaedb"));
constraint
  (("bcdcaeeaceebabeabadbbbaceebeeaecdbeaeeadbcbababaaadceddacccceebedaeeadecba") ++ (""))
    =
    (("bcdcaeeaceebabeabadbbb") ++ (A) ++ ("ecdbeaeeadbcbababaaadceddacccceebedaeeadecba"));
constraint
  (("eccddaeedbb") ++ (B) ++ ("adaecebaab")) =
    (("eccddaeedbbbdebcbcaecdcbabadb") ++ (F) ++ ("cbccdcedadaecebaab"));
constraint
  (("eca") ++ (A) ++ ("cdebadcccce") ++ (B) ++ ("ebbaeaeeebabadeddcdbeddbdedebccbbaadeadbacdacaaddeacdd"))
    =
    (("eca") ++ (A) ++ ("cdebadcccc") ++ (A) ++ ("edcebbaeaeeebab") ++ (D) ++ ("ddbdedebccbbaadeadbacdacaaddeacdd"));
constraint
  (("cceadbbcddeedbacdcdcddebdbdbcddeabaaddbcbacebbccebececccdbcabddabcadcbcdec") ++ (""))
    =
    (("cceadbbcddeedbacdcdcddebdbdbcddeabaaddbcbacebbccebec") ++ (A) ++ ("ccdbcabddabcadcbcd") ++ (A));
constraint
  (("eecbeaababccdbdddbaccccaaebbdbabcdeaceeebbabbcdabade") ++ (A) ++ ("ceacecbeaabbbbbbcaac"))
    =
    (("e") ++ (A) ++ ("beaababccdbdddbaccccaaebbdbabcdeaceeebbabbcdabade") ++ (A) ++ ("ceacecbeaabbbbbbcaac"));
constraint
  (("bccbbebdabcdacdcccaccec") ++ (A) ++ ("cbedeaeaebacbeebbcdbcdaaddbcdacbd") ++ (B) ++ ("bed") ++ (A) ++ ("eddabdb"))
    =
    (("bccbbebdabcdacdcccacc") ++ (A) ++ ("eccbedeaeaebacbeebbcdbcdaaddbcdacbd") ++ (B) ++ ("bedeceddabdb"));
constraint
  (("dcbaadbbcdaddcebbcbbbdcceeaaaabcaeacddbbbbbaecabdbbaddbcecbabbbeeaeebdcbea") ++ (""))
    =
    (("dcbaadbbcdaddcebbcbbbdcceeaaaabcaeacddbbbbbaecabdbbaddbc") ++ (A) ++ ("babbbeeaeebdcbea"));
constraint
  (("eaecaccecdbcbcceaddaeacbacabdccecdebaedebdeedaabacaedacea") ++ (A) ++ ("dbcebcaedbeedcc"))
    =
    (("ea") ++ (A) ++ ("acc") ++ (A) ++ ("dbcbcceaddaeacbacabdcc") ++ (A) ++ ("debaedebdeedaabacaedaceaecdbcebcaedbeedcc"));
constraint
  ((A) ++ ("bcaccacdabeebeadabaa") ++ (A) ++ ("ccceddcaeebdbdecdabacddbecebadabcda") ++ (A) ++ ("bceaedaaceede"))
    =
    ((A) ++ ("bcaccacdabeebeadabaaecccceddcaeebdbd") ++ (A) ++ ("dabacddbecebadabcda") ++ (A) ++ ("bceaedaaceede"));
constraint
  (("ccbbeebeababecedababecceeaddedccddaacddeebebbd") ++ (A) ++ ("eceeabedebeaeeadaebdcbbeae"))
    =
    (("ccbbeebeababecedababecceeaddedccddaacddeebebbd") ++ (A) ++ ("eceeabedebeaeeadaebdcbbeae"));
constraint
  (("ccaabddb") ++ (A) ++ ("baeedbcebddaeeabdbbceeaaaeaebeeaebdddbadebdaeaaadcb") ++ (A) ++ ("edd") ++ (A) ++ ("cca") ++ (A) ++ ("e"))
    =
    (("ccaabddbecbaeedbcebddaeeabdbbceeaaaeaebeeaebdddbadebdaeaaadcbeceddeccca") ++ (A) ++ ("e"));
constraint
  (("dcebcaeeceacabcadbbadcaacebdaeebbedcecddeaecbdadabddbaedbbcadebaebdddbcccc") ++ (""))
    =
    (("dcebcae") ++ (A) ++ ("eacabcadbbadcaacebdaeebbedcecddea") ++ (A) ++ ("bdadabddbaedbbcadebaebdddbcccc"));
constraint
  (("cceeabeaceccababeeddbcdecceaaceabcdeaabddeecdeacebacaecabdbddadcbaeceaedca") ++ (""))
    =
    (("cceeabeac") ++ (A) ++ ("cababeeddbcdecceaaceabcdeaabddeecdeacebaca") ++ (A) ++ ("abdbddadcba") ++ (A) ++ ("eaedca"));
constraint
  (("aaacadddeaacc") ++ (A) ++ ("aaebeaaca") ++ (A) ++ ("dcdcbeed") ++ (A) ++ ("aee") ++ (A) ++ ("addddcbadcada") ++ (A) ++ ("aabadaeedbedbbecce"))
    =
    (("aaacadddeaaccecaaebeaacaecdcdcbeed") ++ (A) ++ ("aee") ++ (A) ++ ("addddcbadcadaecaabadaeedbedbb") ++ (A) ++ ("ce"));
constraint
  (("ceebebaccdbaadabeceaaceaaaebada") ++ (B) ++ ("bbdadddeeddcaeaebedaeae") ++ (A) ++ ("dbcbedecbecccc"))
    =
    (("ceebebaccdbaadab") ++ (A) ++ ("eaaceaaaebadacedcbbdadddeeddcaeaebedaeae") ++ (A) ++ ("dbcbed") ++ (A) ++ ("b") ++ (A) ++ ("ccc"));
constraint
  (("aabeedaacceeac") ++ (A) ++ ("dcdedeebdcdeaabeedbba") ++ (A) ++ ("bceddbbeeda") ++ (A) ++ ("bbbbdddddeabedeeaabbbb"))
    =
    (("aabeedaacceeac") ++ (A) ++ ("dcdedeebdcdeaabeedbba") ++ (A) ++ ("bceddbbeedaecbbbbdddddeabedeeaabbbb"));
constraint
  (("acebcbeaddbacbeabddebaeccbeddbebaeddabddbeeaaacdbbbbaeaccaedebabccddbaebee") ++ (""))
    =
    (("acebcbeaddbacbeabddeba") ++ (A) ++ ("cbeddbebaeddabddbeeaaacdbbbbaeaccaedebabccddbaebee"));
constraint
  (("bcdadbaebcbcd") ++ (A) ++ ("ebca") ++ (A) ++ ("badedb") ++ (A) ++ ("ce") ++ (A) ++ ("ceeecaeeaeebcaabaddbccbdaaeebebbedacbbcce"))
    =
    (("bcdadbaebcbcd") ++ (A) ++ ("ebca") ++ (A) ++ ("badedb") ++ (A) ++ ("ceeccee") ++ (A) ++ ("aeeaeebcaabaddbccbdaaeebebbedacbbcce"));
constraint
  (("dddbddee") ++ (A) ++ ("eee") ++ (A) ++ ("cddabaebdeb") ++ (A) ++ ("cdadccbabedabddcaebede") ++ (A) ++ ("abbaabbedccccaeacbbbeb"))
    =
    (("dddbddeeeceeeeccddabaebdeb") ++ (A) ++ ("cdadccbabedabddcaebedeecabbaabbedccccaeacbbbeb"));
constraint
  (("ecedcbaedacb") ++ (A) ++ ("daebedbdbcbcddbaeeebbcbabe") ++ (A) ++ ("adac") ++ (A) ++ ("aaddeababaaecceedddabcbebb"))
    =
    (("ecedcbaedacbecdaebedbdbcbcddbaeeebbcbabeecadacecaaddeababaa") ++ (A) ++ ("ceedddabcbebb"));
constraint
  (("badcddbcea") ++ (A) ++ ("acb") ++ (A) ++ ("abbcbaeeeeabceaacccbdcbdcccacadebadaeaaabcb") ++ (A) ++ ("aacdaccebeba"))
    =
    (("badcddbcea") ++ (A) ++ ("acb") ++ (A) ++ ("abbcbaeeeeabceaacccbdcbdcccacadebadaeaaabcb") ++ (A) ++ ("aacdaccebeba"));
constraint
  (("ddacbbaacdbacddebdbdccebceadebbecbdbbcabbbdaeacdbceaeddcbde") ++ (A) ++ ("bddbededaeada"))
    =
    (("ddacbbaacdbacddebdbdccebceadebbecbdbbcabbbdaeacdbceaeddcbdeecbddbededaeada") ++ (""));
solve satisfy;
