var string: H;
var string: B;
var string: F;
var string: A;
var string: C;
constraint
  (("abdabbadd") ++ (C) ++ ("abdc") ++ (B) ++ ("cadaadccadcab")) =
    (("abdabbaddbdadddcbbdd") ++ (F) ++ ("cdbdbdcbaadcaccbacabababddbbacadaadccadcab"));
constraint
  (("bbdcadddcbbcb") ++ (H) ++ ("ccbbdbacbbbdcbddbccadadccbadbcdadbdaabbcbcdcbdcbcdcdcdaddabcca"))
    =
    (("bbdcadddcbbcb") ++ (H) ++ ("ccbbdbacbbbdcbddbccadadccbadbcdadbdaabbcbcdcbdcbcdcdcdaddabcca"));
constraint
  (("daacbcabdabcbcbccccdcdabcac") ++ (H) ++ ("adbbdccbdcbaadcaddcaccaddaddadbcdbadbccaabccdabb"))
    =
    (("daacbcabdabcbcbccccdcdabcac") ++ (H) ++ ("adbbdccbdcbaadcaddcaccaddaddadbcdbadbccaabccdabb"));
constraint
  (("bdbadcadbabbdaabdccdbcdcccaababbcbbdbdadaccbbcccaadbdbddcabaacccadabdbdcbddcbabcc") ++ (""))
    =
    (("bdbadcadbabbdaabdccdbcdcccaababbcbbdbdadaccbbcccaadbdbddcabaacc") ++ (H) ++ ("bdcbddcbabcc"));
constraint
  (("ddadabcdddaaddababbcdcdbcaddbcbcdbdbdabddaddaacbaabbaaacdacbbacdccadabdccdabbbdbc") ++ (""))
    =
    (("ddadabcdddaaddababbcdcdbcaddbcbcdbdbdabddaddaacbaabbaaacdacbbacdc") ++ (H) ++ ("ccdabbbdbc"));
constraint
  (("bbcddccddddbbdbadaccabadbcccddacbbbddcbaacadabdbbccccaaccbdaddbaaabcdccaaaddbccad") ++ (""))
    =
    (("bbcddccddddbbdbadaccabadbcccddacbbbddcbaa") ++ (H) ++ ("bbccccaaccbdaddbaaabcdccaaaddbccad"));
constraint
  (("cddbacaacbcccadbd") ++ (H) ++ ("adcabddbcacaaaadbcdbddbaaabaaacadacbdcacbdacbdcaacdcbdcccb"))
    =
    (("cddbacaacbcccadbdcadabdadcabddbcacaaaadbcdbddbaaabaaacadacbdcacbdacbdcaacdcbdcccb") ++ (""));
constraint
  (("caabdbabdbdabddddbcdcbbdbdccdddaacdadbacaadabbbadbbdabcadb") ++ (H) ++ ("ddbbcccdaaabccccc"))
    =
    (("caabdbabdbdabddddbcdcbbdbdccdddaacdadbacaadabbbadbbdabcadb") ++ (H) ++ ("ddbbcccdaaabccccc"));
constraint
  (("daacadabdacddbcdbccbddcbababccaddddbbbacdbbbbbcbbdcbabadacdabcaccadbcaccdbbdbcbcd") ++ (""))
    =
    (("daa") ++ (H) ++ ("acddbcdbccbddcbababccaddddbbbacdbbbbbcbbdcbabadacdabcaccadbcaccdbbdbcbcd"));
constraint
  (("adcacddbbaddddadaaacdcadcddbbaaddbabbaacdddadddaccbaddba") ++ (H) ++ ("acdabbaacdacabcadba"))
    =
    (("adcacddbbaddddadaaacdcadcddbbaaddbabbaacdddadddaccbaddbacadabdacdabbaacdacabcadba") ++ (""));
constraint
  (("cdbbcacbdacbcdbadcbccabbbddd") ++ (H) ++ ("cdcbbabccdbaadbccdbdbbbbcaadadbcaacbcadbddaaccd"))
    =
    (("cdbbcacbdacbcdbadcbccabbbddd") ++ (H) ++ ("cdcbbabccdbaadbccdbdbbbbcaadadbcaacbcadbddaaccd"));
constraint
  (("bcdaaaadabaadadbbbccdccddddbcddbdbbdabbdbbdcbadbbdbadcabcabacdbad") ++ (H) ++ ("ccdbabacca"))
    =
    (("bcdaaaadabaadadbbbccdccddddbcddbdbbdabbdbbdcbadbbdbadcabcabacdbadcadabdccdbabacca") ++ (""));
constraint
  (("adaddabcbddbdcbddcadcadabdcddcbbcaaddabbdadaaaccdbcbaabbdaaaadcdcbcabcdbacadaacdd") ++ (""))
    =
    (("adaddabcbddbdcbddcad") ++ (H) ++ ("cddcbbcaaddabbdadaaaccdbcbaabbdaaaadcdcbcabcdbacadaacdd"));
constraint
  (("bccdcabccabbbcaadbda") ++ (H) ++ ("abcbadcbdcbabbdadccadddbdddabbdcbbadbbcbcadcdbbcdbcdadc"))
    =
    (("bccdcabccabbbcaadbda") ++ (H) ++ ("abcbadcbdcbabbdadccadddbdddabbdcbbadbbcbcadcdbbcdbcdadc"));
constraint
  (("aa") ++ (B) ++ ("dcaacbaddabcc") ++ (H) ++ ("dbdaacadbabacad") ++ (H) ++ ("c"))
    =
    (("aa") ++ (H) ++ ("acccbbabcbbaaaaccacbddbcdd") ++ (H) ++ ("dcd") ++ (H) ++ ("aaaadacdadb") ++ (H) ++ ("aacbaddabccdcdbdaacadbabacad") ++ (H) ++ ("c"));
constraint
  (("bbd") ++ (H) ++ ("ccaaddaccabdcbbcc") ++ (H) ++ ("dcacaadaaababcccbcabdddcdb") ++ (H) ++ ("da") ++ (H) ++ ("bdddabaadbcabbcdaaacbbdba"))
    =
    (("bbddcccaaddaccab") ++ (H) ++ ("bbccdcdcacaadaaababcccbcabdd") ++ (H) ++ ("db") ++ (H) ++ ("da") ++ (H) ++ ("bdddabaadbcabbcdaaacbbdba"));
constraint
  (("dcbacddaabbbbcdabdcddccacabcaddaccacbdbcdad") ++ (H) ++ ("bdccd") ++ (A) ++ ("ccbaadcc") ++ (H) ++ ("bd") ++ (H) ++ ("dcacadaccbbbc"))
    =
    ((H) ++ ("bacddaabbbbcdab") ++ (H) ++ ("d") ++ (H) ++ ("cacabcaddaccacbdbcdaddcb") ++ (H) ++ ("cd") ++ (A) ++ ("ccbaa") ++ (H) ++ ("c") ++ (H) ++ ("bddcdcacadaccbbbc"));
constraint
  (("bcbababccababccadbddaa") ++ (A) ++ (H) ++ ("bacdddabddd") ++ (H) ++ ("ccbaddaddddabdbdcdddcdabaaadd") ++ (H) ++ ("ccdacbb") ++ (H))
    =
    (("bcbababccababccadbddaa") ++ (A) ++ ("dcbacdddabddd") ++ (H) ++ ("ccbaddaddddabdbdcdddcdabaaadddcccdacbb") ++ (H));
constraint
  (("adccccabbaa") ++ (H) ++ ("aaddab") ++ (H) ++ ("ccccdaacacaabdaaaab") ++ (H) ++ ("cacbccdd") ++ (H) ++ ("cddcdaaccbaacdcabbccdbaaccddc"))
    =
    (("adccccabbaa") ++ (H) ++ ("aaddabdcccccdaacacaabdaaaabdccacbccdddccddcdaaccbaacdcabbccdbaaccddc"));
constraint
  (("cdbbbadadaccaadadcccbcdbb") ++ (H) ++ ("bdcd") ++ (H) ++ ("ddadadbdcb") ++ (H) ++ ("cbcbaaacaabbcabdbcbaaabcaaaabab") ++ (H) ++ ("bda"))
    =
    (("cdbbbadadaccaada") ++ (H) ++ ("ccbcdbb") ++ (H) ++ ("bdcddcddadadb") ++ (H) ++ ("bdccbcbaaacaabbcabdbcbaaabcaaaababdcbda"));
constraint
  (("bdcddbbbacccddbabbcbdbaccbdcbbbc") ++ (H) ++ ("baddddbccadacadbabcbdddddccc") ++ (H) ++ ("daaddadbccdaaaccb"))
    =
    (("b") ++ (H) ++ ("ddbbbacccddbabbcbdbaccb") ++ (H) ++ ("bbbcdcbaddddbccadacadbabcbdddd") ++ (H) ++ ("cc") ++ (H) ++ ("daaddadbccdaaaccb"));
constraint
  (("abc") ++ (H) ++ ("adbccabdbbbaccdcbacbbcccaaabaabbabcaacccaadcdddcc") ++ (H) ++ ("dcddacaaaccabcdcccc") ++ (H) ++ ("bcbc"))
    =
    (("abcdcadbccabdbbbacc") ++ (H) ++ ("bacbbcccaaabaabbabcaacccaadcdd") ++ (H) ++ ("c") ++ (H) ++ (H) ++ ("ddacaaaccabcdccccdcbcbc"));
constraint
  (("abdaccdacacbaccaadbbd") ++ (H) ++ ("dadabccdbaaccdabaadbbdcbadbdaabcadbacdcccbcbc") ++ (H) ++ ("cadbcccbb") ++ (H))
    =
    (("abdaccdacacbaccaadbbd") ++ (H) ++ ("dadabccdbaaccdabaadbb") ++ (H) ++ ("badbdaabcadbacdcccbcbcdccadbcccbbdc"));
constraint
  (("aaacbabcadcb") ++ (H) ++ ("bcbbaccdbb") ++ (H) ++ ("bcb") ++ (H) ++ ("abbdacabbdbcacbbadddabbcacad") ++ (H) ++ ("bd") ++ (H) ++ ("cbbcccdadabbdbab"))
    =
    (("aaacbabca") ++ (H) ++ ("b") ++ (H) ++ ("bcbbaccdbb") ++ (H) ++ ("bcbdcabbdacabbdbcacbbadddabbcacaddcbd") ++ (H) ++ ("cbbcccdadabbdbab"));
constraint
  (("bdddbdabcadddbcbddcacdaadaaac") ++ (H) ++ ("cdabbbbbbdaddcabbbbbbabbacbbcdaccddddbd") ++ (H) ++ ("ddcbbaadb"))
    =
    (("bdddbdabcadddbcbd") ++ (H) ++ ("acdaadaaac") ++ (H) ++ ("cdabbbbbbdaddcabbbbbbabbacbbcdaccddddbddcd") ++ (H) ++ ("bbaadb"));
constraint
  (("acadabccaccdacccabcbdabbdabcaaaadbcccdbabadabbacdbcaabbbdbbaddbbdacdbcabab") ++ (H) ++ ("addaa"))
    =
    (("acadabccaccdacccabcbdabbdabcaaaadbcccdbabadabbacdbcaabbbdbbaddbbdacdbcababdcaddaa") ++ (""));
constraint
  (("aabadcccbccdddacddbaabbdbdddabbc") ++ (H) ++ ("bbdadbbabbabadcbc") ++ (H) ++ ("cb") ++ (H) ++ ("bbaacccdbcaabdbabaabacad"))
    =
    (("aabadcccbccdddacddbaabbdbdddabbc") ++ (H) ++ ("bbdadbbabbaba") ++ (H) ++ ("bcdccbdcbbaacccdbcaabdbabaabacad"));
constraint
  (("bdbbaccbaccddacdbbcbdbabacbabbabcbcddbacabcdbdbddbabadcddbbcbcbacdcababbaacbaccad") ++ (""))
    =
    (("bdbbaccbaccddacdbbcbdbabacbabbabcbcddbacabcdbdbddbabadcddbbcbcbac") ++ (H) ++ ("ababbaacbaccad"));
constraint
  (("dbbbbdbdbbddbabcbdabbdcdadabcccabccabbbaaadddbadabacdabcbccdcbaabdcdacdbdcdd") ++ (H) ++ ("cad"))
    =
    (("dbbbbdbdbbddbabcbdabb") ++ (H) ++ ("dadabcccabccabbbaaadddbadabacdabcbccdcbaab") ++ (H) ++ ("dacdb") ++ (H) ++ ("dddccad"));
constraint
  (("dbbccbcabdcababdddabcdacbdbaacbaaabddaccccbcbac") ++ (H) ++ ("aadacdcdabad") ++ (H) ++ ("adbabbccddbdbcaadd"))
    =
    (("dbbccbcab") ++ (H) ++ ("ababdddabcdacbdbaacbaaabddaccccbcbac") ++ (H) ++ ("aadacdcdabaddcadbabbccddbdbcaadd"));
constraint
  (("bbbbdabcaab") ++ (H) ++ ("b") ++ (H) ++ ("dcbacdcdbdacccaccadbcccacacccabddbbbcacdbcbdcbcabaaddbcbcbccacdcd"))
    =
    (("bbbbdabcaabdcbdc") ++ (H) ++ ("bac") ++ (H) ++ ("dbdacccaccadbcccacacccabddbbbcacdbcb") ++ (H) ++ ("bcabaaddbcbcbccacdcd"));
constraint
  (("ccda") ++ (H) ++ ("cccccdbdaa") ++ (H) ++ ("c") ++ (H) ++ ("bbcddccdbaabdacccdbaabaccddbacbbdddbdcadadddabcbbbaba") ++ (H) ++ ("cdbcd"))
    =
    (("ccda") ++ (H) ++ ("cccccdbdaadcc") ++ (H) ++ ("bbcd") ++ (H) ++ ("cdbaabdacccdbaabaccddbacbbdddb") ++ (H) ++ ("adadddabcbbbaba") ++ (H) ++ ("cdbcd"));
constraint
  (("dcabcbcdd") ++ (H) ++ ("bdbadccacb") ++ (H) ++ ("ccbacdabacda") ++ (H) ++ ("bdccdacadbdabbddabcabbacaabdacccacadbddacdac"))
    =
    (("dcabcbcdddcbdba") ++ (H) ++ ("cacb") ++ (H) ++ ("ccbacdabacdadcbdccdacadbdabbddabcabbacaabdacccacadbddacdac"));
constraint
  ((H) ++ ("bbbaadabbbabcd") ++ (H) ++ ("abacccaddddbcadaaabaaddbcbddcdbbdcadbbddadbbadabcdbdbbabdbdaadd"))
    =
    (("dcbbbaadabbbabcddcabacccaddddbcadaaabaaddbcbd") ++ (H) ++ ("dbb") ++ (H) ++ ("adbbddadbbadabcdbdbbabdbdaadd"));
constraint
  (("bcdacabbacdc") ++ (H) ++ ("baccdccdabacbaad") ++ (H) ++ ("ababcaacaadabbacca") ++ (H) ++ ("cbbcbbcbbcccbadaccccddbcdaaca"))
    =
    (("bcdacabbac") ++ (H) ++ (H) ++ ("baccdccdabacbaaddcababcaacaadabbacca") ++ (H) ++ ("cbbcbbcbbcccbadaccccddbcdaaca"));
constraint
  (("cadd") ++ (H) ++ ("dbbbbacdbadcdababcddaabadbddacbddbbaaababcccbbaacbddbbcccddbaacbdaddbbdddaa"))
    =
    (("cadd") ++ (H) ++ ("dbbbbacdbadcdababcddaabadbddacbddbbaaababcccbbaacbddbbcccddbaacbdaddbbdddaa"));
constraint
  (("cdbbbbcaccbbbdbadcbcdbcd") ++ (H) ++ ("dcababddabbbaaadcaaabdcbcadcddbbcccababacccdadddacdaacc"))
    =
    (("cdbbbbcaccbbbdbadcbcdbcd") ++ (H) ++ (H) ++ ("ababddabbbaaa") ++ (H) ++ ("aaab") ++ (H) ++ ("bcadcddbbcccababacccdadddacdaacc"));
constraint
  (("cdbcaababdacdbacbc") ++ (H) ++ ("ababacadadccdccadbbddbaa") ++ (H) ++ ("abdbdadbabcbbabababcbbcadabddabccad"))
    =
    (("cdbcaababdacdbacbc") ++ (H) ++ ("ababacada") ++ (H) ++ ("cdccadbbddbaadcabdbdadbabcbbabababcbbcadabddabccad"));
constraint
  (("caabdccbbadccdcddad") ++ (H) ++ ("dadaacbbdabbadbccbdaaacdabbaaaabdbccacaacbbabcdccbdbabbbaabb"))
    =
    (("caab") ++ (H) ++ ("cbba") ++ (H) ++ ("c") ++ (H) ++ ("ddad") ++ (H) ++ ("dadaacbbdabbadbccbdaaacdabbaaaabdbccacaacbbabcdccbdbabbbaabb"));
constraint
  (("abaaacbbaaadbada") ++ (H) ++ ("dbadbcabaabcacccbbbdacdcdadcdbcbdbbbddabbbcccbadbaabacacbdacaad"))
    =
    (("abaaacbbaaadbada") ++ (H) ++ ("dbadbcabaabcacccbbbdac") ++ (H) ++ ("dadcdbcbdbbbddabbbcccbadbaabacacbdacaad"));
constraint
  (("ddddbbadadabbdaadcccadddbcbbcbbccbbbbacbccdbcbccdaccacbaabd") ++ (H) ++ ("d") ++ (H) ++ ("dcacbcbdbccccdcbb"))
    =
    (("ddddbbadadabbdaadcccadddbcbbcbbccbbbbacbccdbcbccdaccacbaabd") ++ (H) ++ ("ddc") ++ (H) ++ ("acbcbdbcccc") ++ (H) ++ ("bb"));
constraint
  (("dbabcadaabdcdacbaabbadbcdcacdacdccdbcdcbdb") ++ (H) ++ ("caabccaadcccddd") ++ (H) ++ ("cbdbaddacabbbabc") ++ (H) ++ ("bc"))
    =
    (("dbabcadaabdcdacbaabbadbc") ++ (H) ++ ("acdac") ++ (H) ++ ("cdbcdcbdb") ++ (H) ++ ("caabccaadcccddddccbdbaddacabbbabcdcbc"));
constraint
  ((H) ++ ("a") ++ (H) ++ ("aacabdbddbbbabdaacddcadabbcadbbccdbacbbbacdbbcacddcccdbbbcacbcdaccadaacaccbd"))
    =
    (("dcadcaacabdbddbbbabdaacddcadabbcadbbccdbacbbbacdbbcacddcccdbbbcacbcdaccadaacaccbd") ++ (""));
constraint
  (("cbbaccacbbacccc") ++ (H) ++ ("cbbaadccbbbaabadbcdbcdadbaadacaccbabcbdababb") ++ (A) ++ ("ccabdbcadadbbacc"))
    =
    (("cbbaccacbbacccc") ++ (H) ++ ("cbbaa") ++ (H) ++ ("cbbbaabadbcdbcdadbaadacaccbabcbdababba") ++ (H) ++ ("accabdbcadadbbacc"));
constraint
  (("aaadcbbbadbdadadddaaacbaacdbcbacad") ++ (H) ++ ("dabbbaccbacbabbbacbdacdbbaadaacabacbddddcdcba"))
    =
    (("aaa") ++ (H) ++ ("bbbadbdadadddaaacbaacdbcbacad") ++ (H) ++ ("dabbbaccbacbabbbacbdacdbbaadaacabacbddd") ++ (H) ++ (H) ++ ("ba"));
constraint
  (("cabcc") ++ (A) ++ ("cbdddcbbadddbbacbcaccbabda") ++ (H) ++ ("cdb") ++ (H) ++ ("acadadaaaadbccddbabcadcbabadbbacdcdbcbd"))
    =
    (("cabcca") ++ (H) ++ ("acbdd") ++ (H) ++ ("bbadddbbacbcaccbabdadccdb") ++ (H) ++ ("acadadaaaadbccddbabca") ++ (H) ++ ("babadbbacdcdbcbd"));
constraint
  (("cc") ++ (H) ++ ("ccdbbcdabbbb") ++ (H) ++ ("addbdababbbadddbcdcddacdadbbbcbcddcbdadadaddcacccdaba") ++ (H) ++ ("bcbaabdc"))
    =
    (("ccdcccdbbcdabbbb") ++ (H) ++ ("addbdababbbadddbcdcddacdadbbbcbcd") ++ (H) ++ ("bdadadad") ++ (H) ++ ("acccdaba") ++ (H) ++ ("bcbaabdc"));
constraint
  (("bddaadbd") ++ (A) ++ ("dbbdabcddbcbdcbadddbc") ++ (A) ++ ("cbcadcdbaccbccbaaddbb") ++ (H) ++ ("acabbbccaacddbadbacdb"))
    =
    (("bddaadbda") ++ (H) ++ ("adbbdabcddbcb") ++ (H) ++ ("badddbca") ++ (H) ++ ("acbca") ++ (H) ++ ("dbaccbccbaaddbbdcacabbbccaacddbadbacdb"));
constraint
  (("ad") ++ (A) ++ ("dabb") ++ (H) ++ ("adabacccbddbddddabc") ++ (H) ++ ("dcbcaaaacadcdbdbdbacdcdabbcddaabdacbcbdbbdacdbab"))
    =
    (("ada") ++ (H) ++ ("adabbdcadabacccbddbddddabcdc") ++ (H) ++ ("bcaaaacadcdbdbdbac") ++ (H) ++ ("dabbcddaabdacbcbdbbdacdbab"));
constraint
  (("acccddbacabadaabcbdcdacbdddbccaacaacbbcdbdcaacaabddbcadadaaaaabcdbaacbddadacbd") ++ (H) ++ ("b"))
    =
    (("acccddbacabadaabcb") ++ (H) ++ ("dacbdddbccaacaacbbcdbdcaacaabddbcadadaaaaabcdbaacbddadacbddcb"));
constraint
  (("acb") ++ (H) ++ ("aaccdcccbaabbabcbcaccdaccacddaaabb") ++ (H) ++ ("bdbacabaccbdbbaacdbddbcabbcccbcbcddcbbcd"))
    =
    (("acbdcaaccdcccbaabbabcbcaccdaccacddaaabb") ++ (H) ++ ("bdbacabaccbdbbaacdbddbcabbcccbcbcddcbbcd"));
constraint
  (("babbbcdc") ++ (H) ++ ("bddaccacbbcdbaaadccdddbadbddd") ++ (H) ++ ("cbbdcccbdaabbabcacdbadbcaabdaccccaacbbbd"))
    =
    (("babbbcdc") ++ (H) ++ ("bddaccacbbcdbaaadccdddbadbddd") ++ (H) ++ ("cbb") ++ (H) ++ ("ccbdaabbabcacdbadbcaabdaccccaacbbbd"));
constraint
  (("dccbccacadddabcaaddcccabbbccdbdccabdadaddaababcaadaadaccbacbdbcccdadddcccbdbbbdda") ++ (""))
    =
    ((H) ++ ("cbccacadddabcaaddcccabbbccdbdccabdadaddaababcaadaadaccbacbdbcccdadd") ++ (H) ++ ("ccbdbbbdda"));
constraint
  (("bbcbdbbaaacacdcdabccbddbddcbcdacbacccbbabbcaba") ++ (H) ++ ("bdadbacdadadbcb") ++ (H) ++ ("dbadacbadbbbddaa"))
    =
    (("bbcbdbbaaacac") ++ (H) ++ ("dabccbddbd") ++ (H) ++ ("bcdacbacccbbabbcabadcbdadbacdadadbcb") ++ (H) ++ ("dbadacbadbbbddaa"));
constraint
  (("aaabaadbabdddbacdccccbbcbdcaabaddcaabbddbd") ++ (H) ++ ("cabb") ++ (H) ++ ("bcbdaccabbddacdbacacbdadcbcbacd"))
    =
    (("aaabaadbabdddbacdccccbbcb") ++ (H) ++ ("aabaddcaabbddbddccabb") ++ (H) ++ ("bcbdaccabbddacdbacacbda") ++ (H) ++ ("bcbacd"));
constraint
  (("c") ++ (H) ++ ("babcbabbcbdcaddacbbbdd") ++ (H) ++ ("abbbcbcabdbddda") ++ (H) ++ ("ddacaaaddabcacbcbdaadabadbaadcbcaccbd"))
    =
    (("c") ++ (H) ++ ("babcbabbcb") ++ (H) ++ ("addacbbbdd") ++ (H) ++ ("abbbcbcabdbdddadcddacaaaddabcacbcbdaadabadbaadcbcaccbd"));
constraint
  (("cd") ++ (H) ++ ("abddaddbddddbddaaadc") ++ (H) ++ ("bcd") ++ (H) ++ ("adddc") ++ (H) ++ ("dcbaadbcbd") ++ (H) ++ ("acddbddabbadbbccdaba") ++ (H) ++ ("cabadbcaa"))
    =
    (("cddcabddaddbddddbddaaadc") ++ (H) ++ ("bcd") ++ (H) ++ ("add") ++ (H) ++ ("dcdcbaadbcbddcacddbddabbadbbccdabadccabadbcaa"));
constraint
  (("ddddbcdbddbdadcbc") ++ (A) ++ ("abccadbbabdbadba") ++ (H) ++ ("baadbb") ++ (H) ++ ("aabdbaadabbcc") ++ (H) ++ ("acaadd") ++ (H) ++ ("cbcbccaabcd"))
    =
    (("ddddbcdbddbdadcbc") ++ (A) ++ ("abccadbbabdbadba") ++ (H) ++ ("baadbbdcaabdbaadabbccdcacaadd") ++ (H) ++ ("cbcbccaabcd"));
constraint
  (("abdca") ++ (H) ++ ("cdcadbbaadacaacacdcacddbacddbdabccccbbbddbcccabadabbabadaaccdbbabdbcccbdac"))
    =
    (("abdcadcc") ++ (H) ++ ("adbbaadacaacac") ++ (H) ++ ("acddbacddbdabccccbbbddbcccabadabbabadaaccdbbabdbcccbdac"));
constraint
  (("dbcdbcdadacbabcbacacbbaaaacbbcbdbcacdbbcbbcbcdbdabddbc") ++ (H) ++ ("cbdbcdb") ++ (A) ++ ("cacb") ++ (H) ++ ("dbdaaadd"))
    =
    (("dbcdbcdadacbabcbacacbbaaaacbbcbdbcacdbbcbbcbcdbdabddbc") ++ (H) ++ ("cbdbcdb") ++ (A) ++ ("cacbdcdbdaaadd"));
constraint
  (("aabcacbaad") ++ (H) ++ ("acbbdcabcbaaabbb") ++ (H) ++ ("cbcbcdaccacbacccbbbcabcbbcdbbbbcbbcddbbbdddcabacc") ++ (H))
    =
    (("aabcacbaaddcacbbdcabcbaaabbb") ++ (H) ++ ("cbcbcdaccacbacccbbbcabcbbcdbbbbcbbcddbbbdd") ++ (H) ++ ("abaccdc"));
constraint
  (("bbdcabbcad") ++ (H) ++ ("bcc") ++ (H) ++ ("dadcdddabbdabdabacb") ++ (H) ++ ("dacaaddcbdcdbddccdacbbbdcbdbbcbcdaadaddbdba"))
    =
    (("bb") ++ (H) ++ ("abbcaddcbcc") ++ (H) ++ ("da") ++ (H) ++ ("dddabbdabdabacbdcdacaaddcbdcdbd") ++ (H) ++ ("cdacbbbdcbdbbcbcdaadaddbdba"));
constraint
  (("bbbcbcadbcb") ++ (H) ++ ("addacacbcddaadbdccdbddadadccacccdbaacccabbadabbdcbcdccddcabbc") ++ (A) ++ ("cdd"))
    =
    (("bbbcbcadbcbdcaddacacbcddaadb") ++ (H) ++ ("cdbddada") ++ (H) ++ ("cacccdbaacccabbadabb") ++ (H) ++ ("bc") ++ (H) ++ ("cddcabbcadcacdd"));
constraint
  (("babaccbbcdbacbcbabdadbaaaaddddabccdbcdabcbbaccbacddbcdbacaccbcd") ++ (H) ++ ("cccadbddcadbacba"))
    =
    (("babaccbbcdbacbcbabdadbaaaaddddabccdbcdabcbbaccbacddbcdbacaccbcddccccadbd") ++ (H) ++ ("adbacba"));
constraint
  ((H) ++ ("caabbdcbcbcccbdcabadccbdddcabb") ++ (H) ++ ("baacbabaadbdabdabdcacdacabd") ++ (H) ++ ("c") ++ (H) ++ ("bbcabbcbbdcabba"))
    =
    ((H) ++ ("caabbdcbcbcccb") ++ (H) ++ ("abadccbdd") ++ (H) ++ ("abbdcbaacbabaadbdabdab") ++ (H) ++ ("acdacabd") ++ (H) ++ ("cdcbbcabbcbbdcabba"));
constraint
  (("ccdbbbddabbbcaabbaccab") ++ (H) ++ ("cdcabbacaccdbbddadadccbbbadcadbbab") ++ (H) ++ ("bdacdbdaacdddadaadaca"))
    =
    (("ccdbbbddabbbcaabbaccab") ++ (H) ++ ("cdcabbacaccdbbddada") ++ (H) ++ ("cbbba") ++ (H) ++ ("adbbabdcbdacdbdaacdddadaadaca"));
constraint
  (("cbccbcaccccdbdacdabcabacdcacbabbaddcbcdbbaddadbbbc") ++ (H) ++ ("dbdcacbcddbccbbcd") ++ (H) ++ ("dddabbbbca"))
    =
    (("cbccbcaccccdbdacdabcabacdcacbabbad") ++ (H) ++ ("bcdbbaddadbbbc") ++ (H) ++ ("dbdcacbcddbccbbcddcdddabbbbca"));
constraint
  (("cbdbccbaadcdcbbabcadd") ++ (H) ++ ("dacbabdadaacccccdcbcaaccddbcbcdaacd") ++ (H) ++ ("cadbbcadabadbb") ++ (H) ++ ("aaaca"))
    =
    (("cbdbccbaadc") ++ (H) ++ ("bbabcadddcdacbabdadaacccccdcbcaaccddbcbcdaacd") ++ (H) ++ ("cadbbcadabadbbdcaaaca"));
constraint
  (("cbdbccbbbccaacddbddbbdaababbabaccbdcbcccdbdbcabbcb") ++ (H) ++ ("aab") ++ (H) ++ ("abcdacda") ++ (H) ++ ("accdbdbaccccac"))
    =
    (("cbdbccbbbccaacddbddbbdaababbabaccb") ++ (H) ++ ("bcccdbdbcabbcb") ++ (H) ++ ("aab") ++ (H) ++ ("abcdacd") ++ (A) ++ ("ccdbdbaccccac"));
constraint
  (("dbccdadadaadbabccabccaadbbacabcccabdddaabacbdaccbabca") ++ (H) ++ ("bcbacbdbaaabdcdbacdbbcbcbc"))
    =
    (("dbccdadadaadbabccabccaadbbacabcccabdddaabacbdaccbabca") ++ (H) ++ ("bcbacbdbaaab") ++ (H) ++ ("dbacdbbcbcbc"));
constraint
  ((H) ++ ("cbbbccabadbaaadbcdcccbbabacccdddabddaddbccaccdbcddb") ++ (H) ++ ("a") ++ (H) ++ ("caadddddcadcbdcdadbabba"))
    =
    (("dccbbbccabadbaaadbc") ++ (H) ++ ("ccbbabacccdddabddaddbccaccdbcddbdca") ++ (H) ++ ("caadddd") ++ (H) ++ ("a") ++ (H) ++ ("b") ++ (H) ++ ("dadbabba"));
constraint
  (("ccaccdabaccbb") ++ (H) ++ ("ddbaacbbcadacababdabb") ++ (H) ++ ("dabacddabdcccabbcdbddcbbbbacbcad") ++ (H) ++ ("dbcaaddcc"))
    =
    (("ccaccdabaccbb") ++ (H) ++ ("ddbaacbbcadacababdabbdcdabacddab") ++ (H) ++ ("ccabbcdbd") ++ (H) ++ ("bbbbacbcad") ++ (H) ++ ("dbcaaddcc"));
constraint
  (("adccacdbdbdbdababaddacbdcabdabbcabaacbdcbcdbdbccbbabdbdadacaadd") ++ (H) ++ ("dcadcccbbab") ++ (H) ++ ("adb"))
    =
    (("adccacdbdbdbdababaddacbdcabdabbcabaacbdcbcdbdbccbbabdbdadacaadddc") ++ (H) ++ ("adcccbbabdcadb"));
constraint
  (("a") ++ (A) ++ ("dbadccddacadcddaaaddcaccaca") ++ (H) ++ ("bcabddbcdbacac") ++ (A) ++ ("acaadcbbc") ++ (H) ++ ("abbaddbcacdbbccdcd"))
    =
    (("aadcadbadccddaca") ++ (H) ++ ("ddaaaddcaccacadcbcabddbcdbacacadcaacaa") ++ (H) ++ ("bbcdcabbaddbcacdbbccdcd"));
constraint
  (("abaabaabdacaacbccabccbaacdbcbcbacdbcdacbadddbccbcb") ++ (H) ++ ("dbbdbabddbaaaddbccdddcacccccc"))
    =
    (("abaabaabdacaacbccabccbaacdbcbcbacdbcdacbadddbccbcb") ++ (H) ++ ("dbbdbabddbaaaddbccdd") ++ (H) ++ ("acccccc"));
constraint
  (("dbabcabadadabdbddacacabdaccb") ++ (H) ++ ("bbbccabdccccddbaddacabcdcbacdbcb") ++ (H) ++ ("acdbac") ++ (H) ++ ("dbabab") ++ (H) ++ ("a"))
    =
    (("dbabcabadadabdbddacacabdaccb") ++ (H) ++ ("bbbccabdccccddbaddacabcdcbacdbcb") ++ (H) ++ ("acdbacdcdbabab") ++ (H) ++ ("a"));
constraint
  (("aaabdcbdabbcccdacabbbacaaaddbadabcdbaaadbddbcbbbb") ++ (H) ++ ("dbdaacbccaadbdaadcbddbbcaccadd"))
    =
    (("aaab") ++ (H) ++ ("bdabbcccdacabbbacaaaddbadabcdbaaadbddbcbbbb") ++ (H) ++ ("dbdaacbccaadbdaadcbddbbcaccadd"));
constraint
  (("cbbccbbcbcabccdaabdbcddbcadaabbdbadcdcddadabccacddbdacb") ++ (H) ++ ("abcccccdddbbdda") ++ (H) ++ ("ccdacdb"))
    =
    (("cbbccbbcbcabccdaabdbcddbcadaabbdbadc") ++ (H) ++ ("ddadabccacddbdacb") ++ (H) ++ ("abcccccdddbbddadcccdacdb"));
constraint
  (("caaabcdb") ++ (H) ++ ("dbbccaccaddcdbaadaabdabbdabbbddabb") ++ (H) ++ ("aabbcaaccabbbabbabdbbbcdbbddccaaacb"))
    =
    (("caaabcdbdcdbbccaccad") ++ (H) ++ ("dbaadaabdabbdabbbddabbdcaabbcaaccabbbabbabdbbbcdbbddccaaacb"));
constraint
  (("bbcbdcbabcbccbabcbdbbcd") ++ (H) ++ ("ccacdddbbabadbadabcabbdbbacbdddbdabdadacbaccdbbcdabbcabc"))
    =
    (("bbcbdcbabcbccbabcbdbbcddcccacdddbbabadbadabcabbdbbacbdddbdabdadacbaccdbbcdabbcabc") ++ (""));
constraint
  (("dbabbabacaa") ++ (H) ++ ("dabdbababcdbcacdbbaacbabbacbcbcdbbbcbcabbbd") ++ (H) ++ ("ddbcdacdccdabab") ++ (H) ++ ("acbadb"))
    =
    (("dbabbabacaadcdabdbababcdbcacdbbaacbabbacbcbcdbbbcbcabbbddcddbcdac") ++ (H) ++ ("cdababdcacbadb"));
constraint
  (("bcbbbddcdaddacbcd") ++ (H) ++ (H) ++ ("dadacdcddccdacbccccbbbbdbdccdbdcdbabbbbacabbdbadad") ++ (H) ++ ("dcbdbb") ++ (H))
    =
    (("bcbbbddcdaddacbcddcdcdadac") ++ (H) ++ ("ddccdacbccccbbbbdbdccdbdcdbabbbbacabbdbadad") ++ (H) ++ ("dcbdbb") ++ (H));
constraint
  (("bdacbabdb") ++ (H) ++ ("adcadbdacbbdbdadddaadababdacdbddabacaddad") ++ (H) ++ ("ccacdbccdccadddcc") ++ (H) ++ ("badbcbdc"))
    =
    (("bdacbabdbdc") ++ (A) ++ ("dbdacbbdbdadddaadababdacdbddabacaddad") ++ (H) ++ ("ccacdbcc") ++ (H) ++ ("cadddccdcbadbcb") ++ (H));
constraint
  (("aaaacddbcbbdddabbcd") ++ (H) ++ (H) ++ ("bcdbbaccacbdabccdacaabcdaadcdcbabaabbdd") ++ (H) ++ ("cdadbcbdaa") ++ (H) ++ ("ccdda"))
    =
    (("aaaacddbcbbdddabbcddc") ++ (H) ++ ("bcdbbaccacbdabccdacaabcdaa") ++ (H) ++ (H) ++ ("babaabbdddccdadbcbdaadcccdda"));
constraint
  (("daadabdacaaabacdcbacacdaaccdadaaadaabcbabdadabcdddcabbccdaab") ++ (H) ++ ("abbbdbbcaacadbdcdcd"))
    =
    (("daadabdacaaabacdcbacacdaaccdadaaadaabcbabdadabcdd") ++ (H) ++ ("abbccdaabdcabbbdbbcaacadb") ++ (H) ++ (H) ++ ("d"));
constraint
  (("daadbcbbbddbaddadbadbbaabbcccbc") ++ (H) ++ ("bcbcdabaabaccbadbbccbadaaacdcadaadcdabdbccadacbc"))
    =
    (("daadbcbbbddbaddadbadbbaabbcccbcdcbcbcdabaabaccbadbbccbadaaac") ++ (H) ++ ("adaa") ++ (H) ++ ("dabdbccadacbc"));
constraint
  (("badbccdcabdbddcbdaacbcdaacaaccbdadcbdcadccdabbcacdbacbaddbabcdccabddcdca") ++ (H) ++ ("adaddab"))
    =
    (("badbcc") ++ (H) ++ ("abdbddcbdaacbcdaacaaccbda") ++ (H) ++ ("b") ++ (H) ++ ("adccdabbcacdbacbaddbabcdccabddc") ++ (H) ++ ("a") ++ (H) ++ ("adaddab"));
constraint
  (("addddbacbbbad") ++ (H) ++ ("ddaabbbdbb") ++ (H) ++ ("b") ++ (H) ++ ("dab") ++ (H) ++ ("aadaaaca") ++ (H) ++ ("cdc") ++ (H) ++ ("bcdddcccabadaccabbcdddaaabbcadb"))
    =
    (("addddbacbbbaddcddaabbbdbb") ++ (H) ++ ("bdcdab") ++ (H) ++ ("aadaaaca") ++ (H) ++ ("c") ++ (H) ++ (H) ++ ("bcdddcccabadaccabbcdddaaabbcadb"));
constraint
  (("abcdda") ++ (H) ++ ("bcadabbbdbcbcbcdbcbbbabaccbcacadbcbaadcabb") ++ (H) ++ ("dacb") ++ (H) ++ ("babdaa") ++ (H) ++ ("dbddcbbcacaaabb"))
    =
    (("abcddadcbcadabbbdbcbcbcdbcbbbabaccbcacadbcbaa") ++ (H) ++ ("abb") ++ (H) ++ ("dacbdcbabdaa") ++ (H) ++ ("dbddcbbcacaaabb"));
constraint
  (("acbaaabbcacacbad") ++ (H) ++ ("abcddbbbbdddbbaacdacdbad") ++ (H) ++ ("dddbcddbbaadaadabacadadadacddbccaadba"))
    =
    (("acbaaabbcacacbad") ++ (H) ++ ("abcddbbbbdddbbaacdacdbaddcdddbcddbbaadaadabacadadadacddbccaadba"));
constraint
  (("ddacdaddaabddccabbbcaccbcababcadbb") ++ (H) ++ ("dacadccdbbbdbbddbcadabbcadbdddaabdbadabcbbdbd"))
    =
    (("ddacdaddaabddccabbbcaccbcababcadbb") ++ (H) ++ ("dacadccdbbbdbbddbcadabbcadbdddaabdbadabcbbdbd"));
constraint
  ((H) ++ ("cbbbbdbaabbaacdccdbdcdcbdccbcdddddcdad") ++ (H) ++ ("ccdaabcdbdbddab") ++ (H) ++ (H) ++ ("abdc") ++ (H) ++ ("cacdacadbdacad"))
    =
    ((H) ++ ("cbbbbdbaabbaac") ++ (H) ++ ("cdb") ++ (H) ++ (H) ++ ("b") ++ (H) ++ ("cbcdddd") ++ (H) ++ ("daddcccdaabcdbdbddab") ++ (H) ++ ("dcabdcdccacdacadbdacad"));
constraint
  (("cdbcacababdbdcdaccbcbbddaacdcaddad") ++ (H) ++ ("cbaadbddabacadcddacdbcdc") ++ (H) ++ ("bddabaacccbabacbcac"))
    =
    (("cdbcacababdb") ++ (H) ++ ("daccbcbbddaacdcaddaddccbaadbddabaca") ++ (H) ++ ("ddacdbc") ++ (H) ++ (H) ++ ("bddabaacccbabacbcac"));
constraint
  (("baabc") ++ (H) ++ ("cbacaacdbddbabaadacbcaabacbdacacbbabbcdbaabbddba") ++ (H) ++ ("cccccdddddcbcdacbddacdab"))
    =
    (("baabc") ++ (H) ++ ("cbacaacdbddbabaadacbcaabacbdacacbbabbcdbaabbddba") ++ (H) ++ ("cccccdddd") ++ (H) ++ ("bcdacbddacdab"));
constraint
  (("cbcddbdddd") ++ (H) ++ ("bbbbaabdacacdabbcaaaacbdbddabdcbdccccaa") ++ (H) ++ ("cb") ++ (H) ++ ("adbbabcacadaaadbadbcadbb"))
    =
    (("cbcddbdddd") ++ (H) ++ ("bbbbaabdacacdabbcaaaacbdbddab") ++ (H) ++ ("bdccccaadccbdcadbbabcacadaaadbadbcadbb"));
constraint
  (("caabddbaaccb") ++ (H) ++ ("dacbbbdbbcaacdcdddaddcacabcbacbccabbacccaaaabada") ++ (H) ++ (H) ++ ("db") ++ (H) ++ (H) ++ ("cbdddaccb"))
    =
    (("caabddbaaccb") ++ (H) ++ ("dacbbbdbbcaacdcdddaddcacabcbacbccabbacccaaaabada") ++ (H) ++ (H) ++ ("dbdc") ++ (H) ++ ("cbdddaccb"));
constraint
  (("bcaabcbaaabbccbddadddccad") ++ (A) ++ ("ccccdbbbccacbbbac") ++ (H) ++ ("bcbcdbddcacbacdadcddbbcdbabddbabb"))
    =
    (("bcaabcbaaabbccbddadd") ++ (H) ++ ("cad") ++ (A) ++ ("ccccdbbbccacbbbacdcbcbcdbddcacbacda") ++ (H) ++ ("ddbbcdbabddbabb"));
constraint
  (("aadbacabdbaddbaacbacbabdabcbcca") ++ (H) ++ ("cdddabbb") ++ (H) ++ ("aacddcddddadbcdc") ++ (H) ++ ("baddabcadbcacddcdaca"))
    =
    (("aadbacabdbaddbaacbacbabdabcbccadccdddabbbdcaacd") ++ (H) ++ ("ddddadbc") ++ (H) ++ ("dcbaddabcadbcacd") ++ (H) ++ ("daca"));
constraint
  (("cbcbbacdccbcdbbaacbadacccadacadacbcadadbcbabcabdbabcdbacaaaaccc") ++ (H) ++ ("cdbdbc") ++ (H) ++ ("bccadacc"))
    =
    (("cbcbbacdccbcdbbaacbadacccadacadacbcadadbcbabcabdbabcdbacaaaacccdccdbdbcdcbccadacc") ++ (""));
constraint
  (("cadddbccbbdbcdabdadbcaadadbbcddaadabccacbaccccaaaaaacba") ++ (H) ++ ("b") ++ (H) ++ ("ababbab") ++ (H) ++ ("daab") ++ (H) ++ ("abdada"))
    =
    (("cadddbccbbdbcdabdadbcaadadbbcddaadabccacbaccccaaaaaacbadcb") ++ (H) ++ ("ababbab") ++ (H) ++ ("daab") ++ (H) ++ ("abdada"));
constraint
  (("dadadabbdabcadbcdcaadcccccdcccdccbddbcdbaac") ++ (H) ++ ("b") ++ (H) ++ ("cbabcbcadaabdacbddbdadabbdbcbadaa"))
    =
    (("dadadabbdabcadbcdcaa") ++ (H) ++ ("ccccdcccdccbddbcdbaac") ++ (H) ++ ("b") ++ (H) ++ ("cbabcbcadaabdacbddbdadabbdbcbadaa"));
constraint
  (("ac") ++ (H) ++ ("bbaadadd") ++ (H) ++ ("bbdaaabd") ++ (H) ++ ("cbddbcdcccdbaccdbccadbbcbbcddacacdabac") ++ (H) ++ ("caacdddbbbbccadab"))
    =
    (("acdcbbaadadddcbbdaaabd") ++ (H) ++ ("cbddbc") ++ (H) ++ ("ccdbaccdbccadbbcbbcddacacdabacdccaacdddbbbbccadab"));
constraint
  (("ddc") ++ (H) ++ ("dabddcbaadddbbdbcdbcdd") ++ (H) ++ ("adacbcccdaccaccdbbbaddddaddabdcdbdbcdbccccbcddbbacad"))
    =
    (("ddcdcdabddcbaadddbbdbcdbcdddcadacbcccdaccaccdbbbaddddaddabdcdbdbcdbccccbcddbbacad") ++ (""));
constraint
  (("dbbccabcdcbbacbbbcbcccbacbbdaccdbaacdcadcbcaccddabddaccacbdaabaddcbba") ++ (A) ++ ("cacbabbb"))
    =
    (("dbbccabc") ++ (H) ++ ("bbacbbbcbcccbacbbdaccdbaac") ++ (H) ++ ("a") ++ (H) ++ ("bcaccddabddaccacbdaabaddcbbaadcacacbabbb"));
constraint
  (("caaacccdbccbdbaccaadcbccdbbabbabdcbaaaaabaadacddcacababcdababbcdadddbbaabaccadaad") ++ (""))
    =
    (("caaacccdbccbdbaccaa") ++ (H) ++ ("bccdbbabbabdcbaaaaabaadacddcacababcdababbcdadddbbaabaccadaad"));
constraint
  (("aaccabcbcacacabdcacbdbcdcddabcbbbcdcbabccbdbcccadd") ++ (H) ++ ("ccbabbd") ++ (H) ++ ("daaccccaccaaac") ++ (H) ++ ("acba"))
    =
    (("aaccabcbcacacabdcacbdbcdcddabcbbbcdcbabccbdbcccadd") ++ (H) ++ ("ccbabbd") ++ (H) ++ ("daaccccaccaaacdcacba"));
constraint
  (("baddadaccbaacddcacadaadabbbdabcc") ++ (H) ++ ("cdddbacaabaccc") ++ (H) ++ ("aadadbccba") ++ (H) ++ ("cbcbcbcdcdaadacabaa"))
    =
    (("baddadaccbaacddcacadaadabbbdabccdccdddbacaabacccdcaadadbccbadccbcbcbcdcdaadacabaa") ++ (""));
constraint
  (("cabccccbbcaacddadbbadbdcdabbdd") ++ (H) ++ ("ccbcba") ++ (H) ++ ("bcaddcbbbcbcacaadbdaaaadbcbdd") ++ (H) ++ ("cdbcccadcc"))
    =
    (("cabccccbbcaacddadbbadbdcdabbdddcccbcbadcbcad") ++ (H) ++ ("bbbcbcacaadbdaaaadbcbdd") ++ (H) ++ ("cdbcccadcc"));
constraint
  (("ccbabacacbcbbabccaabdbcadbddaadc") ++ (H) ++ ("caccdbbcaaabdabc") ++ (H) ++ ("bccaccabb") ++ (H) ++ ("aaccadbabbabaddbac"))
    =
    (("ccbabacacbcbbabccaabdbcadbddaadc") ++ (H) ++ ("caccdbbcaaabdabcdcbccaccabbdcaaccadbabbabaddbac"));
constraint
  (("ddaabbdadadcd") ++ (H) ++ ("ccbbbdcdacccadbbaabaaccddaddbdabccbbdbbdacbccbcaadbcbdaddabcdbacbc"))
    =
    (("ddaabbdadadcddcccbbbdcdacccadbbaabaaccddaddbdabccbbdbbdacbccbcaadbcbdaddabcdbacbc") ++ (""));
constraint
  ((A) ++ ("acacaaaacddbdcdddbbcadbdcaccdbbbcdaaaaaaabaaacacddaaacabddbcccbbbddbcdaaaadaa") ++ (""))
    =
    (("adcaacacaaaacddbdcdddbbcadb") ++ (H) ++ ("accdbbbcdaaaaaaabaaacacddaaacabddbcccbbbddbcdaaaadaa"));
constraint
  (("b") ++ (H) ++ ("bdcd") ++ (H) ++ ("abdbabcbdaabcbb") ++ (H) ++ ("cacabbbaabdaaccbcdbccaaadacab") ++ (H) ++ ("baddadbb") ++ (H) ++ ("abbcbbbccbdabd"))
    =
    (("bdcbdcddcabdbabcbdaabcbbdccacabbbaabdaaccbcdbccaaadacabdcbaddadbbdcabbcbbbccbdabd") ++ (""));
constraint
  (("adcabbbbcdcdaaaddabadadcdaaadbddacdaccdbabbcbcbdaabccacaabaacabcacdbd") ++ (H) ++ ("dbdbbdcbcd"))
    =
    (("a") ++ (H) ++ ("abbbbcdcdaaaddabada") ++ (H) ++ ("daaadbddacdaccdbabbcbcbdaabccacaabaacabcacdbd") ++ (H) ++ ("dbdbb") ++ (H) ++ ("bcd"));
constraint
  (("adbbacdbcbbcaab") ++ (H) ++ ("acabcbdcddabababdaabdaabb") ++ (H) ++ ("bddcbbcbbaadbacdcabddadbabcca") ++ (A) ++ ("bbbb"))
    =
    (("adbbacdbcbbcaabdcacabcbdcddabababdaabdaabb") ++ (H) ++ ("bddcbbcbbaadbac") ++ (H) ++ ("abddadbabccaa") ++ (H) ++ ("abbbb"));
constraint
  (("addbacbbcdbcacccadbaccbabbbacbcbbcbbabd") ++ (H) ++ ("ddabddcdaadadddbbaccccbcdacbdbaadbadddab"))
    =
    (("addbacbbcdbcacccadbaccbabbbacbcbbcbbabddcddabddcdaadadddbbaccccbcdacbdbaadbadddab") ++ (""));
constraint
  (("badbddacbaabacdabadaacabcdcbaabdddbbdaaddbaabcbb") ++ (H) ++ ("db") ++ (H) ++ ("abaaaddbcdbdbcabbbaabcddcdd"))
    =
    (("badbddacbaabacdabadaacabcdcbaabdddbbdaaddbaabcbbdcdbdcabaaaddbcdbdbcabbbaabcddcdd") ++ (""));
constraint
  (("ccdaaaabadbabdadbdcbaaaabbabcddacbcac") ++ (H) ++ ("db") ++ (H) ++ ("dbaddddbdaabbbdbcac") ++ (H) ++ ("bddcbddbabccaabdc"))
    =
    (("ccdaaaabadbabdadb") ++ (H) ++ ("baaaabbabcddacbcacdcdbdcdbaddddbdaabbbdbcac") ++ (H) ++ ("bddcbddbabccaabdc"));
constraint
  ((H) ++ ("ddbcbacbbdaabbbcaacaababccbcbdcbcbacbcaabcaddbdabdbadbcbcaaabbab") ++ (H) ++ ("dbbabccbacbba"))
    =
    ((H) ++ ("ddbcbacbbdaabbbcaacaababccbcbdcbcbacbcaabcaddbdabdbadbcbcaaabbab") ++ (H) ++ ("dbbabccbacbba"));
constraint
  (("baadcbbddaacbdadababadbccdacbddcd") ++ (H) ++ ("dd") ++ (H) ++ ("db") ++ (H) ++ ("dadddaddbabacabcbcaccaccbbdddabbacdbbc"))
    =
    (("baadcbbddaacbdadababadbccdacbddcd") ++ (H) ++ ("dddcdb") ++ (H) ++ ("dadddaddbabacabcbcaccaccbbdddabbacdbbc"));
constraint
  (("bddcadbabcddaadaaccadbadcbbbaaaadacba") ++ (H) ++ ("cadbccbabbacdcbcabcdacaccabcdadabbdaadadab"))
    =
    (("bddcadbabcddaadaaccadba") ++ (H) ++ ("bbbaaaadacbadccadbccbabbac") ++ (H) ++ ("bcabcdacaccabcdadabbdaadadab"));
constraint
  (("daabbbcdccbbbcbdaccddaaba") ++ (H) ++ ("dddbabbcadbb") ++ (H) ++ ("caadabdccbcdcdcaacbacd") ++ (H) ++ ("dadabacc") ++ (H) ++ ("cbdadd"))
    =
    (("daabbbc") ++ (H) ++ ("cbbbcbdaccddaabadcdddbabbcadbb") ++ (H) ++ ("caadab") ++ (H) ++ ("cbc") ++ (H) ++ (H) ++ ("aacbacddcdadabaccdccbdadd"));
constraint
  (("cbaaabdcdbcacd") ++ (H) ++ ("ccd") ++ (H) ++ ("daccaaabdaadbaacaadbbabcaabaaadaabbcdbdbaabcbcca") ++ (H) ++ ("dacbdb") ++ (H) ++ ("da"))
    =
    (("cbaaab") ++ (H) ++ ("dbcacd") ++ (H) ++ ("ccd") ++ (H) ++ ("daccaaabdaadbaacaadbbabcaabaaadaabbcdbdbaabcbccadcdacbdb") ++ (H) ++ ("da"));
constraint
  (("ccccbadcddccaddbdbacaccbacccadaa") ++ (H) ++ ("bbacaadadccbdadbdbdbccbdcaacbdabbdbaadbbdbccaab"))
    =
    (("ccccbadcddccaddbdbacaccbacccadaa") ++ (H) ++ ("bbacaada") ++ (H) ++ ("cbdadbdbdbccbdcaacbdabbdbaadbbdbccaab"));
constraint
  (("ddabbbaddaaacccbacb") ++ (H) ++ ("cddaccdccdbdddbdbd") ++ (H) ++ ("daabadacbabbbad") ++ (H) ++ ("dbdcbacdbdaaadccacaacaa"))
    =
    (("ddabbbaddaaacccbacbdccddacc") ++ (H) ++ ("cdbdddbdbddcdaabadacbabbbad") ++ (H) ++ ("dbdcbacdbdaaadccacaacaa"));
constraint
  (("bdbbccbcbabddccdbaabbdcdbdcabda") ++ (H) ++ ("bddbcadcdbdcadaacacdabcdd") ++ (H) ++ ("bccdbcdbdbbaadacdcdbd"))
    =
    (("bdbbccbcbabd") ++ (H) ++ ("cdbaabbdcdbdcabdadcbddbca") ++ (H) ++ ("dbdcadaacacdabcdd") ++ (H) ++ ("bccdbcdbdbbaadacdcdbd"));
constraint
  (("dbcacbcc") ++ (H) ++ ("aaddddcbbcdbbdadacacbddddcba") ++ (H) ++ ("addbdbbadbcabccdaaadc") ++ (H) ++ ("bcdbaaacc") ++ (A) ++ ("c") ++ (H) ++ ("da"))
    =
    (("dbcacbccdcaaddddcbbcdbbdadacacbddd") ++ (H) ++ ("badcaddbdbbadbcabccdaaadc") ++ (H) ++ ("bcdbaaacca") ++ (H) ++ ("acdcda"));
constraint
  (("abcabacabaaadacaadb") ++ (H) ++ ("adaccdabaaddbaadabcbabdbbcddddcd") ++ (H) ++ ("dbacdacacabbbaabacbad") ++ (H) ++ ("b") ++ (H))
    =
    (("abcabacabaaadacaadbdcadaccdabaaddbaadabcbabdbbcddddcd") ++ (H) ++ ("dbacdacacabbbaabacbad") ++ (H) ++ ("bdc"));
constraint
  (("daaaaabbbbccabcdabaccabacbaac") ++ (H) ++ ("dababbaddadbddacbdbabcabaabbddbacbdbbdbbcdad") ++ (A) ++ ("da"))
    =
    (("daaaaabbbbccabcdabaccabacbaacdcdababbaddadbddacbdbabcabaabbddbacbdbbdbbcdad") ++ (A) ++ ("da"));
constraint
  (("bbbdadbdabbcdadbdabbacddddbccddcdbaaaaabbbbacdbbbaddddbccbbcdadaabbcb") ++ (H) ++ ("baaddadbca"))
    =
    (("bbbdadbdabbcdadbdabbacddddbccd") ++ (H) ++ ("dbaaaaabbbbacdbbbaddddbccbbcdadaabbcbdcbaaddadbca"));
constraint
  (("abbabdcb") ++ (H) ++ ("cdaabcababcaddcbbbbbbaddabdbccdcc") ++ (H) ++ ("abdcdaacaacdd") ++ (H) ++ ("acaadccbcbadcaacabcbb"))
    =
    (("abbab") ++ (H) ++ ("b") ++ (H) ++ ("cdaabcababcad") ++ (H) ++ ("bbbbbbaddabdbcc") ++ (H) ++ ("cdcabdcdaacaacdd") ++ (H) ++ ("acaadccbcba") ++ (H) ++ ("aacabcbb"));
constraint
  (("ccabbabacdcccbdababddaacbddbcabddbdbabbcadcadbacbcccacbdbaccadccaacacacbcddaaacac") ++ (""))
    =
    (("ccabbabacdcccbdababddaacbddbcabddbdbabbca") ++ (H) ++ ("adbacbcccacbdbacca") ++ (H) ++ ("caacacacbcddaaacac"));
constraint
  (("aaba") ++ (H) ++ ("dddcadccbadacbabaddaaadaadbbdacdabacdd") ++ (H) ++ ("ddbaaaccadcaacdcadcab") ++ (H) ++ ("accbccbdbadd"))
    =
    (("aabadcdd") ++ (H) ++ ("adccbadacbabaddaaadaadbbdacdabacdd") ++ (H) ++ ("ddbaaacc") ++ (A) ++ ("ac") ++ (H) ++ ("a") ++ (H) ++ ("abdcaccbccbdbadd"));
constraint
  (("bbabdb") ++ (H) ++ ("ddaddbacaacddbdddbacdbbdbdbaaaacdddbdadaabdbaaaaddbbabcabddbbbbddbcacaabc"))
    =
    (("bbabdb") ++ (H) ++ ("ddaddbacaacddbdddbacdbbdbdbaaaacdddbdadaabdbaaaaddbbabcabddbbbbddbcacaabc"));
constraint
  (("dbaacddaadaaccadabddbddcdabaa") ++ (H) ++ ("aacbccbcbdacbbcacddbccbbadaabcddbbcba") ++ (H) ++ ("babdabaccbb"))
    =
    (("dbaacddaadaaccadabddbd") ++ (H) ++ ("dabaadcaacbccbcbdacbbcacddbccbbadaabcddbbcba") ++ (H) ++ ("babdabaccbb"));
constraint
  (("dbaccbcbaadbcababcbabadabdabacdaadbbcaadaaacaba") ++ (H) ++ ("dbaccacaddba") ++ (H) ++ ("cabcbbadacacbdbb") ++ (H))
    =
    (("dbaccbcbaadbcababcbabadabdabacdaadbbcaadaaacabadcdbaccacaddbadccabcbbadacacbdbb") ++ (H));
constraint
  (("cacaacadbdbbbbbcbbccadbbcbcbccabbbccbddbdc") ++ (H) ++ ("aadadbcaabacdaadbdabccaaccaacbdccbdcc"))
    =
    (("cacaacadbdbbbbbcbbccadbbcbcbccabbbccbddb") ++ (H) ++ ("dcaadadbcaabacdaadbdabccaaccaacbdccbdcc"));
constraint
  ((H) ++ ("bbdbabdadbdccd") ++ (H) ++ ("abbdccabdbbccaadadb") ++ (H) ++ ("bbccbdbaddddbaaaddacababcaddbcccbbcbc") ++ (H) ++ (H) ++ ("b"))
    =
    (("dcbbdbabdadb") ++ (H) ++ ("cd") ++ (H) ++ ("abbdccabdbbccaadadb") ++ (H) ++ ("bbccbdbaddddbaaaddacababcaddbcccbbcbc") ++ (H) ++ ("dcb"));
constraint
  (("adbbabcaddacacddbbccbadbcdacabdbabbcbdabaabbdddad") ++ (H) ++ ("ccadabdccadaddadacabbbacbbbcac"))
    =
    (("adbbabcaddacacddbbccbadbcdacabdbabbcbdabaabbdddad") ++ (H) ++ ("ccadab") ++ (H) ++ ("cadaddadacabbbacbbbcac"));
constraint
  (("bccaaddabcbcaccbbbcdddabcaadabdabbdbcccadadaacbbdadbcadbcaabaaaabbbdadbb") ++ (H) ++ ("badbaca"))
    =
    (("bccaaddabcbcaccbbbcdddabcaadabdabbdbcccadadaacbbdadbcadbcaabaaaabbbdadbb") ++ (H) ++ ("badbaca"));
constraint
  (("ccddacbcaaaccccbcbbbbcacccbdcbcddbbabdbdaadbbc") ++ (H) ++ (H) ++ ("baacbadacbbba") ++ (H) ++ ("badcadbbdacadbac"))
    =
    (("ccddacbcaaaccccbcbbbbcacccb") ++ (H) ++ ("bcddbbabdbdaadbbcdc") ++ (H) ++ ("baacbadacbbba") ++ (H) ++ ("b") ++ (A) ++ ("dbbdacadbac"));
constraint
  (("bacddcdcdacabacdcbc") ++ (H) ++ ("dbcabadddbcaccabdadadaadbbcddad") ++ (H) ++ ("dadcdadbccabbccbacadaabacba"))
    =
    (("bacddcdcdacabacdcbcdcdbcabadddbcaccabdadadaadbbcddaddcda") ++ (H) ++ ("dadbccabbccbacadaabacba"));
constraint
  (("abcdbbbbdadbdccabcbcacc") ++ (H) ++ ("cbbabcacdabdacacdcbcddabbcb") ++ (H) ++ ("ccbaaacbabadbbbbdcdccaca") ++ (H) ++ ("d"))
    =
    (("abcdbbbbdadbdccabcbcaccdccbbabcacdabdacacdcbcddabbcbdcccbaaacbabadbbbbdcdccaca") ++ (H) ++ ("d"));
constraint
  (("acbcacadcdabdbccaab") ++ (H) ++ ("aacaadbccdddcbdcdaac") ++ (H) ++ ("dadddbabdbbdddadaddacbbcbdbdacbbcbcacd"))
    =
    (("acbcacadcdabdbccaab") ++ (H) ++ ("aacaadbccdd") ++ (H) ++ ("b") ++ (H) ++ ("daacdcdadddbabdbbdddadaddacbbcbdbdacbbcbcacd"));
constraint
  (("baabbbbadaac") ++ (H) ++ ("bacc") ++ (H) ++ ("bbabababaac") ++ (H) ++ ("ccccbcaadbcbadcbadbdbb") ++ (H) ++ ("dbadbc") ++ (A) ++ ("b") ++ (H) ++ ("dddbbcadbcb"))
    =
    (("baabbbbadaac") ++ (H) ++ ("bacc") ++ (H) ++ ("bbabababaac") ++ (H) ++ ("ccccbcaadbcbadcbadbdbbdcdbadbca") ++ (H) ++ ("abdcdddbbcadbcb"));
constraint
  (("db") ++ (H) ++ ("caccacccc") ++ (H) ++ ("ababdaabccabd") ++ (H) ++ ("dcabbbcaabacdaaddacdbdbcbccddaacbbcdabdbcddadaacdca"))
    =
    (("db") ++ (H) ++ ("caccacccc") ++ (H) ++ ("ababdaabccabd") ++ (H) ++ ("dcabbbcaabacdaaddacdbdbcbccddaacbbcdabdbcddadaac") ++ (H) ++ ("a"));
constraint
  (("bccabda") ++ (H) ++ ("dbaacccabdadadb") ++ (H) ++ ("bdadbccdbcacacbaccbacbbbcbdbcdbccbdaaabbcaadabddbab") ++ (H) ++ ("db"))
    =
    (("bccabda") ++ (H) ++ ("dbaacccabdadadbdcbdadbccdbcacacbaccbacbbbcbdbcdbccbdaaabbcaadabddbabdcdb"));
constraint
  (("daaabaccaccaacbabdcddba") ++ (H) ++ ("dbbdcdddaccbabdcabcbdcabdadbabdbdabdaaaadccabadcdbdbcbdd"))
    =
    (("daaabaccaccaacbab") ++ (H) ++ ("ddbadcdbbdcdddaccbabdcabcbdcabdadbabdbdabdaaaa") ++ (H) ++ ("caba") ++ (H) ++ ("dbdbcbdd"));
constraint
  (("cbdaccadaca") ++ (H) ++ ("bddbbbbaabbbbddaacdadabaaabacbddcdcccbdaaaddaccbabcaaccacdadabbcbdcb"))
    =
    (("cbdaccadacadcbddbbbbaabbbbddaacdadabaaabacbd") ++ (H) ++ ("dcccbdaaaddaccbabcaaccacdadabbcbdcb"));
constraint
  (("dda") ++ (H) ++ ("ddbcadcaaaca") ++ (H) ++ ("bdcacbadccbcccacddaabcbbacabbacdababcacabbdbabdddbbcda") ++ (H) ++ ("cabcbc"))
    =
    (("ddadcddbcadcaaacadcb") ++ (H) ++ ("acbadccbcccacddaabcbbacabbacdababcacabbdbabdddbbcdadccabcbc"));
constraint
  (("bcddbbbca") ++ (H) ++ ("cabbdabcccddcabbdcddbbaadadbbbdbabbabadbadcdacaacdaccadd") ++ (H) ++ ("dbbaadda") ++ (H) ++ ("ba"))
    =
    (("bcddbbbcadccabbdabcccddcabb") ++ (H) ++ ("ddbbaadadbbbdbabbabadbadcdacaacdaccadd") ++ (H) ++ ("dbbaaddadcba"));
constraint
  (("bbbacccbadcadcdbbcdadbbbdcd") ++ (H) ++ ("ddbb") ++ (H) ++ ("cdcbcbacdbbcbbbabbbcbaacbacccccdacadbbdbacaddd"))
    =
    (("bbbacccba") ++ (H) ++ ("a") ++ (H) ++ ("dbbcdadbbb") ++ (H) ++ ("ddcddbb") ++ (H) ++ ("c") ++ (H) ++ ("bcbacdbbcbbbabbbcbaacbacccccdacadbbdbacaddd"));
constraint
  (("bdddbbbccddb") ++ (H) ++ ("cbdd") ++ (A) ++ (H) ++ ("dcadcdbadaaaaacdd") ++ (H) ++ ("dac") ++ (H) ++ ("abb") ++ (H) ++ ("ddcaacabacbdbbcaddcddcddabaa"))
    =
    (("bdddbbbccddbdccbdda") ++ (H) ++ ("adc") ++ (H) ++ ("a") ++ (H) ++ ("dbadaaaaacdd") ++ (H) ++ ("dacdcabbdcd") ++ (H) ++ ("aacabacbdbbcaddcd") ++ (H) ++ ("ddabaa"));
constraint
  (("addaccdbcbbdddbbdbdabcacbabcbddbddaacdcbaccccdccbbcbdbbdcbddb") ++ (H) ++ ("cbabdbccddcacbbbcd"))
    =
    (("addaccdbcbbdddbbdbdabcacbabcbddbddaac") ++ (H) ++ ("bacccc") ++ (H) ++ ("cbbcbdbbdcbddb") ++ (H) ++ ("cbabdbccd") ++ (H) ++ ("acbbbcd"));
constraint
  (("cbccabaabbaaacdbbcdabbbccadcdcddadbacddcddaadacbdccdbaccacb") ++ (A) ++ ("bcbcbd") ++ (H) ++ ("acbadccddd"))
    =
    (("cbccabaabbaaacdbbcdabbbccadcdcddadbacddcddaadacbdccdbaccacba") ++ (H) ++ ("abcbcbd") ++ (H) ++ ("acba") ++ (H) ++ ("cddd"));
constraint
  (("ddaab") ++ (H) ++ ("adccbccdcacbddaddadddaccabbbccbddbdbbcdcccdabdbaadaddddadaaccdacbbaddaaacd"))
    =
    (("ddaab") ++ (H) ++ ("a") ++ (H) ++ ("cbccdcacbddaddadddaccabbbccbddbdbbc") ++ (H) ++ ("ccdabdbaadaddddadaaccdacbbaddaaacd"));
constraint
  (("badbdacdaaabbddcdcbccccbdbcbdbdadccaaaabbbabdbcccaacdcacbbcad") ++ (H) ++ ("abaccdbbccaabcb") ++ (H) ++ ("a"))
    =
    (("badbdacdaaabbddc") ++ (H) ++ ("bccccbdbcbdbda") ++ (H) ++ ("caaaabbbabdbcccaacdcacbbcaddcabaccdbbccaabcb") ++ (H) ++ ("a"));
constraint
  (("abbbadcc") ++ (H) ++ ("baabcdaacab") ++ (H) ++ ("d") ++ (H) ++ ("bdaaadaccabaccdbddabdddacdddaadabdacbcbadcdbcbcaacbbbdb"))
    =
    (("abbba") ++ (H) ++ ("cdcbaabcdaacabdcd") ++ (H) ++ ("bdaaadaccabaccdbddabdddacdddaadabdacbcba") ++ (H) ++ ("dbcbcaacbbbdb"));
constraint
  (("bbdabaddaaddaccaaaacbccdabadccb") ++ (H) ++ ("ccbddbdbcccbdadcdcccbcc") ++ (H) ++ ("ababbadabbdbbacaa") ++ (H) ++ ("c") ++ (H) ++ ("c"))
    =
    (("bbdabaddaaddaccaaaacbccdabadccbdcccbddbdbcccbda") ++ (H) ++ (H) ++ ("ccbccdcababbadabbdbbacaadcc") ++ (H) ++ ("c"));
constraint
  (("baaadadbbbdbccacbdacbcccaaccbaddabbbcbdaabcbdbbdaddbbdbdaabbdbadbcbbcbad") ++ (H) ++ ("aaababc"))
    =
    (("baaadadbbbdbccacbdacbcccaaccbaddabbbcbdaabcbdbbdaddbbdbdaabbdbadbcbbcbad") ++ (H) ++ ("aaababc"));
constraint
  (("cacadacacbbddacdaabbadbdaaaabacbadacabccba") ++ (H) ++ ("adcbcccbacbac") ++ (H) ++ ("acccbbdbbbdcdbdbbbdbbc"))
    =
    (("cacadacacbbddacdaabbadbdaaaabacbadacabccba") ++ (H) ++ ("a") ++ (H) ++ ("bcccbacbac") ++ (H) ++ ("acccbbdbbb") ++ (H) ++ ("dbdbbbdbbc"));
constraint
  (("cccabdabbdbdddadaabaddbdddabacaaadddcbaddabbbddadbbaca") ++ (H) ++ ("acbcabbdbabcdbcbdcbdbaddc"))
    =
    (("cccabdabbdbdddadaabaddbdddabacaaadddcbaddabbbddadbbaca") ++ (H) ++ ("acbcabbdbabcdbcb") ++ (H) ++ ("bdbad") ++ (H));
constraint
  (("bbabdbabddccaacabdddaaaaabbdcadacbbdadcddbcbccdadbadabdbdbabaccdacbcdabbacdbcbcac") ++ (""))
    =
    (("bbabdbabd") ++ (H) ++ ("caacabdddaaaaabb") ++ (H) ++ ("adacbbdadcddbcbccdadbadabdbdbabaccdacbcdabbacdbcbcac"));
solve satisfy;
