var string: C;
var string: E;
constraint
  (("dafbedecacebecaddcdabdcd") ++ (E) ++ ("bdaefeddadaafdadececbfdcfbaadabfc"))
    = ((C) ++ ("aeaabdaefadccfacebdaefeddadaafdadececbfdcfbaadabfc") ++ (""));
constraint
  (("debcdecaaaabddcbcdbfada") ++ (E) ++ ("beafacbe")) =
    (("debc") ++ (C) ++ ("ececfefffffedfcbfbfacbeafacbe"));
constraint
  (("adebfabedabedfbfbccdaadbfcdaedeecdece") ++ (E) ++ ("ddcdccbfbcebbadbccdbceceafbbedbdfdfbbfdc"))
    = (("adebfabedabe") ++ (C) ++ ("fbbfdc"));
constraint
  (("ceefcbcec") ++ (E) ++ ("cfacecdebfabeaaedfbebedecfdafeefaceaafefbcbaeadebebdeaddaadabcdaaabb"))
    =
    (("ceefcbcec") ++ (E) ++ ("cfacecdebfabeaaedfbebedecfdafeefaceaafefbcbaeadebebdeaddaadabcdaaabb"));
constraint
  (("ceabbabebbe") ++ (E) ++ ("aceefadcbcdafcacceaebafeaaeafacfabcdcccacdacbfdafbabfaaefdcfbdefdf"))
    =
    (("ceabbabebbedbdaceefadcbcdafcacceaebafeaaeafacfabcdcccacdacbfdafbabfaaefdcfbdefdf") ++ (""));
constraint
  (("cecbdbdeafdfceeeaccfeedeebdeadfbadcffcdbeafacbfeaccdeaddacdeaaffcbedafdcacfaaccc") ++ (""))
    =
    (("cecb") ++ (E) ++ ("eafdfceeeaccfeedeebdeadfbadcffcdbeafacbfeaccdeaddacdeaaffcbedafdcacfaaccc"));
constraint
  (("beacfeadecfafaedfaecfffcdffaebeebcbfdddfadadbbb") ++ (E) ++ ("aeacdccafbcdbaedbfbcdffabefaae"))
    =
    (("beacfeadecfafaedfaecfffcdffaebeebcbfdddfadadbbb") ++ (E) ++ ("aeacdccafbcdbaedbfbcdffabefaae"));
constraint
  (("adfebfaeebfbfafcafedebbeabbcbfdcffddee") ++ (E) ++ ("ddeabbefacdaeaecdcfafcbaceeefadbcbdaade"))
    =
    (("adfebfaeebfbfafcafedebbeabbcbfdcffddee") ++ (E) ++ ("ddeabbefacdaeaecdcfafcbaceeefadbcbdaade"));
constraint
  (("ecbcfaecaacecfdcfceadfafecefabedbaeebdbdbbfababbfdefdcbaceeebfeaebbabbefcaecccab") ++ (""))
    =
    (("ecbcfaecaacecfdcfceadfafecefabedbaeeb") ++ (E) ++ ("bbfababbfdefdcbaceeebfeaebbabbefcaecccab"));
constraint
  (("deceaeddcfccefbadcaafcaceccbfefffdbdfcbcbaaaddbefbbfaeecaefaaedfaccbeeccdabecffe") ++ (""))
    =
    (("deceaeddcfccefbadcaafcaceccbfefff") ++ (E) ++ ("fcbcbaaaddbefbbfaeecaefaaedfaccbeeccdabecffe"));
constraint
  (("ebcfefeacadebabfbdfdcfeccbaacfaaabafebdcacacad") ++ (E) ++ ("dbbbdaabdcdeadaddfddcbbeadbbfcb"))
    =
    (("ebcfefeacadebabfbdfdcfeccbaacfaaabafebdcacacaddbddbbbdaabdcdeadaddfddcbbeadbbfcb") ++ (""));
constraint
  (("ebdfbccb") ++ (E) ++ ("eedbbecbacdfabdcdafaacdffeecfbccceddebbfebadeaeaacecaaebbafaaaacbadbd"))
    =
    (("ebdfbccbdbdeedbbecbacdfabdcdafaacdffeecfbccceddebbfebadeaeaacecaaebbafaaaacbadbd") ++ (""));
constraint
  (("cdbfddbbdbbccfcebaeaecefedfaeebfaecddbdbebfefcabbbcbfdbbafacbaeaceaeabacdaabcadb") ++ (""))
    =
    (("cdbfddbbdbbccfcebaeaecefedfaeebfaecd") ++ (E) ++ ("bebfefcabbbcbfdbbafacbaeaceaeabacdaabcadb"));
constraint
  (("fcfeafadecddceeaafefcdfddbddbdfceecdebdcebbefcdecadaaecedebeffaacfbbfadafecfaddf") ++ (""))
    =
    (("fcfeafadecddceeaafefcdfd") ++ (E) ++ ("dbdfceecdebdcebbefcdecadaaecedebeffaacfbbfadafecfaddf"));
constraint
  (("cfbfaebcaaffdecffbcdebdccbfdadcceccccfadbecaabfaebbdecedeacce") ++ (E) ++ ("edaaaabeefedabde"))
    =
    (("cfbfaebcaaffdecffbcdebdccbfdadcceccccfadbecaabfaebbdecedeacce") ++ (E) ++ ("edaaaabeefedabde"));
constraint
  (("aafbcffbbdcddedcdaebfdfdedcfadceadddfeaaeddbeaafbdbb") ++ (E) ++ ("cdaaadbcccbdbbbbecefedfcc"))
    =
    (("aafbcffbbdcddedcdaebfdfdedcfadceadddfeaaeddbeaafbdbbdbdcdaaadbcccbdbbbbecefedfcc") ++ (""));
constraint
  (("ecbeccfdbccccbcefbedfdbafbeabfcfbdecdfdf") ++ (E) ++ ("cbecdedadfacffddbfcbffcfaeedafcbaeeff"))
    =
    (("ecbeccfdbccccbcefbedfdbafbeabfcfbdecdfdf") ++ (E) ++ ("cbecdedadfacffddbfcbffcfaeedafcbaeeff"));
constraint
  (("addbdcfdecebdcdbbeaafcfddefdfcffcfaabdfadfadcccdbebadddacbeeffaddbaaafffceabbbfe") ++ (""))
    =
    (("ad") ++ (E) ++ ("cfdecebdcdbbeaafcfddefdfcffcfaabdfadfadcccdbebadddacbeeffaddbaaafffceabbbfe"));
constraint
  (("debadbafaecdaebdfbbbebdbcdbedbfad") ++ (E) ++ ("cfbaccadeabaeeffaeacbecfceeaccbaadcdcfecedcc"))
    =
    (("debadbafaecdaebdfbbbebdbcdbedbfad") ++ (E) ++ ("cfbaccadeabaeeffaeacbecfceeaccbaadcdcfecedcc"));
constraint
  (("ccdbcecafb") ++ (E) ++ ("cadfabbcdbfbddfbccdffdfaacccdaeeacaebaedceaefeabddeacabcdbaeeaacccf"))
    =
    (("ccdbcecafb") ++ (E) ++ ("cadfabbcdbfbddfbccdffdfaacccdaeeacaebaedceaefeabddeacabcdbaeeaacccf"));
constraint
  (("aaabebacadbfdcb") ++ (E) ++ ("edbafcfaddedeeabdcdcceabfeefbbefccacffafcffabce") ++ (E) ++ ("fcbaeebdefcd"))
    =
    (("aaabebacadbfdcbdbdedbafcfaddedeeabdcdcceabfeefbbefccacffafcffabcedbdfcbaeebdefcd") ++ (""));
constraint
  (("dfddfefcdbcd") ++ (E) ++ ("faebadacfaecbaacfdacecbcfebafffbededeacefbefbfdfcdefcddaaafdcafac"))
    =
    (("dfddfefcdbcddbdfaebadacfaecbaacfdacecbcfebafffbededeacefbefbfdfcdefcddaaafdcafac") ++ (""));
constraint
  (("afbbfecceecbefeeafcabccaae") ++ (E) ++ ("dcdcafeebfcdacebbfaccddddaeafbcabdaeebdfdeabedbbdbc"))
    =
    (("afbbfecceecbefeeafcabccaaedbddcdcafeebfcdacebbfaccddddaeafbcabdaeebdfdeabedbbdbc") ++ (""));
constraint
  (("abfbcbebeaebbcebeebceafddbeabcbfeaebaccdcbefbfecdcefafecbfbcddbdffafaeabbecacffd") ++ (""))
    =
    (("abfbcbebeaebbcebeebceafddbeabcbfeaebaccdcbefbfecdcefafecbfbcd") ++ (E) ++ ("ffafaeabbecacffd"));
constraint
  (("bbeaab") ++ (E) ++ ("bfeeafafbfbefececcddfdfabaaffabfacabfeeeacfadbfeadcfddefceafaaeffecfeae"))
    =
    (("bbeaabdbdbfeeafafbfbefececcddfdfabaaffabfacabfeeeacfadbfeadcfddefceafaaeffecfeae") ++ (""));
constraint
  (("bcfefdfdaecceaceddbbbbebceabfadeaeedebeeebeeffdddeefabaaaebbecfabdfbed") ++ (E) ++ ("fdfaaec"))
    =
    (("bcfefdfdaecceaceddbbbbebceabfadeaeedebeeebeeffdddeefabaaaebbecfabdfbeddbdfdfaaec") ++ (""));
solve satisfy;
