var string: B;
var string: A;
var string: C;
constraint
  (("ccaaaaacacccbaacbaccbccaccbabcaba") ++ (A) ++ ("cbbccbaabbbbaacaaccccbcbababcbaaccaabbbccb"))
    =
    (("ccaaaaacacccbaacbaccbccaccbabcabacbbcaaacbbcacbcacacbbccbaabbbbaacaaccccbcbababcbaaccaabbbccb") ++ (""));
constraint
  (("caaabccaabaccccaca") ++ (B) ++ ("bbccaabacabacaba")) =
    (("caaabccaabaccccacaccbcacbbbba") ++ (C) ++ ("bbccaabacabacaba"));
constraint
  (("aaaababcbcaacbbccaabbbaccbbbabcc") ++ (C) ++ ("bbababbacabbaaaaaccbcccbcbbaabccbccbcbcacaaabbaaaca"))
    =
    (("aaaababcbcaacbbccaabbbaccb") ++ (A) ++ ("aaccbcccbcbbaabccbccbcbcacaaabbaaaca"));
constraint
  (("ccaa") ++ (B) ++ ("cbbaaaccaabccabbbcaaccacbcbbacababbbcaaabcbabbaaaaccbccabcbaccbbccbaabbacabccaaacb"))
    =
    (("ccaa") ++ (B) ++ ("cbbaaaccaabccabbbcaaccacbcbbacababbbcaaabcbabbaaaaccbccabcbaccbbccbaabbacabccaaacb"));
constraint
  (("acbcaabbb") ++ (B) ++ ("bbbacaaccbcaaabbabcacbccbbccabcacaccaaaacbbbbabcacabccbaabbabacaaacbabcccaaba"))
    =
    (("acbcaabbbbacacaabbbacaaccbcaaabbabcacbccbbccabcacaccaaaacbbbbabcacabccbaabbabacaaacbabcccaaba") ++ (""));
constraint
  (("ccbaacbbbaaccabbbbccbcaaacacbaaabcccbbcaabaaccabbbacabbcaaababaabccbacacaaaabbbacbccbbcbbcbba") ++ (""))
    =
    (("ccbaacbbbaaccabbbbccbcaaacacbaaabcccbbcaabaaccabbbacabbcaaababaabcc") ++ (B) ++ ("aabbbacbccbbcbbcbba"));
constraint
  (("ccbccaccbbbbbabbabaccababbcbabaabbabbccbccccbccba") ++ (B) ++ ("acbbcccacbacbcabaabbaaccaaaacaccacbba"))
    =
    (("ccbccaccbbbbbabbabaccababbcbabaabbabbccbccccbccbabacacaaacbbcccacbacbcabaabbaaccaaaacaccacbba") ++ (""));
constraint
  (("babaaccabacababcabacbbcabaacabaacbcabababaaccabcca") ++ (B) ++ ("bccbacaaacacbbcbbccabcccabaabacbbbcc"))
    =
    (("babaaccabacababcabacbbcabaacabaacbcabababaaccabccabacacaabccbacaaacacbbcbbccabcccabaabacbbbcc") ++ (""));
constraint
  (("cbaaacbcaaccbbabcbacacbaccacacbbccbcabccbabcccbaaababacbacaabacccaaabcaabbcabaccaacccbacacaac") ++ (""))
    =
    (("cbaaacbcaaccbbabcbacacbaccacacbbccbcabccbabcccbaaababacbacaabacccaaabcaabbcabaccaaccc") ++ (B) ++ ("c"));
constraint
  (("bbccbbcacabbbaacabbbcbbabbcbabaccaccbaaaaabc") ++ (B) ++ ("ccaabbbacbbaacacbacaacbcbacacccaaabaaaccba"))
    =
    (("bbccbbcacabbbaacabbbcbbabbcbabaccaccbaaaaabcbacacaaccaabbbacbbaacacbacaacbcbacacccaaabaaaccba") ++ (""));
constraint
  (("cbacccabbcbbabccbbccaabbababaaaabbbbbccbcbbaabaabcabbabbccaabaacc") ++ (B) ++ ("aabcbaabcaaaaabaacabb"))
    =
    (("cbacccabbcbbabccbbccaabbababaaaabbbbbccbcbbaabaabcabbabbccaabaaccbacacaaaabcbaabcaaaaabaacabb") ++ (""));
constraint
  (("aabcccaababaabcbbacababbaaccbacccccaccacaaccacbbab") ++ (B) ++ ("acccaccbbccaaababcbcbcacccbabaacaacc"))
    =
    (("aabcccaababaabcbbacababbaaccbacccccaccacaaccacbbabbacacaaacccaccbbccaaababcbcbcacccbabaacaacc") ++ (""));
constraint
  (("acbbaabababcccaaabbabcccbbabbabaaaaabcbaabccbccabccbabacababacccab") ++ (B) ++ ("cabbcacccabbbcbbbaba"))
    =
    (("acbbaabababcccaaabbabcccbbabbabaaaaabcbaabccbccabccbabacababacccab") ++ (B) ++ ("cabbcacccabbbcbbbaba"));
constraint
  (("bbbcbbcbababbcbacabbabccbaabccacaacbbcabbabcbcaccbcaaaccacabacccbbbbcbcbbbaaacbb") ++ (B) ++ ("aaabcb"))
    =
    (("bbbcbbcbababbcbacabbabccbaabccacaacbbcabbabcbcaccbcaaaccacabacccbbbbcbcbbbaaacbb") ++ (B) ++ ("aaabcb"));
constraint
  (("aabaacc") ++ (C) ++ ("cbbabcaaaaaabacbabbcbcacaababcaccbbbaabbbccacbaabaaacbaabacccbbababcbccabccc"))
    =
    (("aabaaccaa") ++ (B) ++ ("bcbbabcaaaaaabacbabbcbcacaababcaccbbbaabbbccacbaabaaacbaabacccbbababcbccabccc"));
constraint
  (("bcbbacacbacbcabbaa") ++ (B) ++ ("cbcabccbcaabaabacbbbaaacbcbbbbcbbcabbbbabcbaccaaaacacabccabbcababacb"))
    =
    (("bcbbacacbacbcabbaabacacaacbcabccbcaabaabacbbbaaacbcbbbbcbbcabbbbabcbaccaaaacacabccabbcababacb") ++ (""));
constraint
  (("bbcbaabc") ++ (B) ++ ("babbbbaacbcccaccaabbaacbacbcbababbabbaaaacbaccbaabbabcaccaccabaacacbcbcababcac"))
    =
    (("bbcbaabc") ++ (B) ++ ("babbbbaacbcccaccaabbaacbacbcbababbabbaaaacbaccbaabbabcaccaccabaacacbcbcababcac"));
constraint
  (("accbbbababccbbbbccccacbbcaaabccbccacaaacacccccbaabbbacacaaabaccabaabcaaaccacabaacaaacbaacbacb") ++ (""))
    =
    (("accbbbababccbbbbccccacbbcaaabccbccacaaacacccccbaabb") ++ (B) ++ ("abaccabaabcaaaccacabaacaaacbaacbacb"));
constraint
  (("ccab") ++ (B) ++ ("cbacbbbcaccbcccbbcabccbcbbcbbcbbcccacbabbbbbcbbaacaccabbccacaaccbbbbbacbabcababcbb"))
    =
    (("ccabbacacaacbacbbbcaccbcccbbcabccbcbbcbbcbbcccacbabbbbbcbbaacaccabbccacaaccbbbbbacbabcababcbb") ++ (""));
constraint
  (("cabbcccaaacccabbccabbcabacabcabbbbbabbcbcccaacabbaabbcabcbacacaabcbaabbcbccaaaccbcbccbcabcabb") ++ (""))
    =
    (("cabbcccaaacccabbccabbcabacabcabbbbbabbcbcccaacabbaabbcabc") ++ (B) ++ ("bcbaabbcbccaaaccbcbccbcabcabb"));
constraint
  (("accaaabaabbaaccbaabccccacaabbabbcccccaabcaabacbbbbabccaa") ++ (B) ++ ("aabaababacaaccabcbacbbcaccbacb"))
    =
    (("accaaabaabbaaccbaabccccacaabbabbcccccaabcaabacbbbbabccaa") ++ (B) ++ ("aabaababacaaccabcbacbbcaccbacb"));
constraint
  (("bbaaaccbaaabbcbccacccacbbbbbbcbbbabacaccbbc") ++ (B) ++ ("aaccbaabacbacbabcbbcbcaababbabbbabaabbaabcb"))
    =
    (("bbaaaccbaaabbcbccacccacbbbbbbcbbbabacaccbbcbacacaaaaccbaabacbacbabcbbcbcaababbabbbabaabbaabcb") ++ (""));
constraint
  (("aacabbcabbbaaaccacabacbcacbbccccbacabcbbcaacca") ++ (B) ++ ("baccbaaabbbbbabaaaaaabbbbaccbcbabaaccbca"))
    =
    (("aacabbcabbbaaaccacabacbcacbbccccbacabcbbcaaccabacacaabaccbaaabbbbbabaaaaaabbbbaccbcbabaaccbca") ++ (""));
constraint
  (("acccbbacbcccacccabaaabbabccaaccbbbabcbbccbacabbbbbcccbabcaacababca") ++ (B) ++ ("aaabaabbabcbaacbaacc"))
    =
    (("acccbbacbcccacccabaaabbabccaaccbbbabcbbccbacabbbbbcccbabcaacababcabacacaaaaabaabbabcbaacbaacc") ++ (""));
constraint
  (("acabaccbcbbcccacabacabbacacaabbccccaabcccbabaccacbacbbbcbacaaabcacbaaaacbcacaaacbbabacaabaccc") ++ (""))
    =
    (("acabaccbcbbcccacabacab") ++ (B) ++ ("bbccccaabcccbabaccacbacbbbcbacaaabcacbaaaacbcacaaacbbabacaabaccc"));
constraint
  (("acbbabbaba") ++ (B) ++ ("cccbbababcaabbbbbcabaaabaaabaccacbcbabcbcbcbcbcaccbcacaacbacaccaccbbcabbacbb"))
    =
    (("acbbabbaba") ++ (B) ++ ("cccbbababcaabbbbbcabaaabaaabaccacbcbabcbcbcbcbcaccbcacaacbacaccaccbbcabbacbb"));
constraint
  (("aaabcbccaccbbbcacaccaaccaabcacbaccbbbcbabbcbaabcbbbbabaacbcababaaaacbccbcc") ++ (B) ++ ("bcaaacaaacaa"))
    =
    (("aaabcbccaccbbbcacaccaaccaabcacbaccbbbcbabbcbaabcbbbbabaacbcababaaaacbccbccbacacaabcaaacaaacaa") ++ (""));
constraint
  (("abacbbccccbbccacbbbbbccbbbbbbbbccbbcbabccacc") ++ (B) ++ ("bbabcbccbcaccacbbcbcccaaabbbbacbccbacabaaa"))
    =
    (("abacbbccccbbccacbbbbbccbbbbbbbbccbbcbabccacc") ++ (B) ++ ("bbabcbccbcaccacbbcbcccaaabbbbacbccbacabaaa"));
constraint
  (("bbcccacccbbbcbacbbabcccacabbccaccbacbacbcbbabaabbacacaabcaccabcbacbabcccbaaabcbaacbacabaaabac") ++ (""))
    =
    (("bbcccacccbbbcbacbbabcccacabbccaccbacbacbcbbabaab") ++ (B) ++ ("bcaccabcbacbabcccbaaabcbaacbacabaaabac"));
constraint
  (("ccbcbabbccccb") ++ (C) ++ ("babbbcacca")) =
    (("ccbcbabbccccb") ++ (C) ++ ("babbbcacca"));
constraint
  (("bbbacccbaaaaaaacababccbcaaabbbbcaaacbcaaccaabcacabaccbbcbcbbaccaacabcbbacbcbbcbacaababcbcbaac") ++ (""))
    = (("bbbacccbaaaaaaacababccbcaaabbbbcaaacbcaacc") ++ (B) ++ ("cbcbaac"));
constraint
  ((C) ++ ("cbcbbbaccaabbbabcccbcbcbccccbacaab") ++ (C) ++ ("aaac") ++ (C) ++ ("caabbbccaabcbabacacbaaaacacacbbbccbaa") ++ (C) ++ ("ba"))
    =
    (("aaaccbcbbbaccaabbbabcccbcbcbccccbacaab") ++ (C) ++ ("aaac") ++ (C) ++ ("caabbbccaabcbabacacbaaaacacacbbbccbaaaaacba"));
constraint
  (("aacccccbcbbcbcacccbbaccbcbcaabaccaacbaacbabbccbcbbaaaaabacccbbacbca") ++ (B) ++ ("bacbcaaccbbbbaabbcbbc"))
    =
    (("aacccccbcbbcbcacccbbaccbcbcaabaccaacbaacbabbccbcbbaaaaabacccbbacbcaacaaabacbcaaccbbbbaabbcbbc") ++ (""));
constraint
  (("abcbbacbbbbbbc") ++ (C) ++ ("cabacabaababccbacaaccccabbabcbcabcacaabacbcccbbcbccccbcacbabcaaccbbcbaccbac"))
    =
    (("abcbbacbbbbbbcaaaccabacabaababccbacaaccccabbabcbcabcacaabacbcccbbcbccccbcacbabcaaccbbcbaccbac") ++ (""));
constraint
  (("c") ++ (C) ++ ("cacbbcbbabbaabccbbacccbbccccccbcaccbbbcaabcabcabc") ++ (B) ++ ("bcabbcbacccbbbcbbabbbbacbbacbbcbbb"))
    =
    (("c") ++ (C) ++ ("cacbbcbbabbaabccbbacccbbccccccbcaccbbbcaabcabcabcacaaabcabbcbacccbbbcbbabbbbacbbacbbcbbb"));
constraint
  (("aabbcbacbcbcbbccbbcbbbbbab") ++ (C) ++ ("bbcbaabcbccbbbaabcbaabacaabaacbbaabaaccbbabcbbacabbbcbcaabcabbc"))
    =
    (("aabbcbacbcbcbbccbbcbbbbbabaaacbbcbaabcbccbbbaabcbaabacaabaacbbaabaaccbbabcbbacabbbcbcaabcabbc") ++ (""));
constraint
  (("abbbbaacbbcacbbccbacbcaabbaccbbbcbbaabcbbacbababccbaabbaccaccaccaabbacbaaaabbcaaaccbbcbcbaacb") ++ (""))
    =
    (("abbbbaacbbcacbbccbacbcaabbaccbbbcbbaabcbbacbababccbaabbaccaccaccaabbacbaaaabbc") ++ (C) ++ ("cbbcbcbaacb"));
constraint
  (("accccbcbbabbaaaabccbaacbbbaaccbababbacaabccaabcabccabbcabaabaaccbcacaaabaabbbcacbabaacaaaabaa") ++ (""))
    =
    (("accccbcbbabbaaaabccbaacbbbaaccbababbacaabccaabcabccabbcabaabaaccbc") ++ (B) ++ ("baabbbcacbabaacaaaabaa"));
constraint
  (("cccbacccbacbcacaba") ++ (C) ++ ("cabcbbbcabacaaacacaccaaccbccaaaabaccbbccabaccbcaaaabaaabbcbcbaabababacb"))
    =
    (("cccbacccbacbcacaba") ++ (C) ++ ("cabcbbbcab") ++ (B) ++ ("cacaccaaccbccaaaabaccbbccabaccbcaaaabaaabbcbcbaabababacb"));
constraint
  (("babbccccbbbcaccbcbbcbabcbcbcbbaabbccbbbaaacbcabbbbbacbacaaaccaacbbccbbcacacbabcbbbbbbbabaacaa") ++ (""))
    =
    (("babbccccbbbcaccbcbbcbabcbcbcbbaabbccbbb") ++ (C) ++ ("bcabbbbbacbac") ++ (C) ++ ("caacbbccbbcacacbabcbbbbbbbabaacaa"));
constraint
  (("cbaaccababcabccbaaababacbcbacaccbcabababacaacaabbbaaabcbccaa") ++ (B) ++ ("bbababbcbbbcbaabacbbbbccabbc"))
    =
    (("cbaaccababcabccbaaababacbcbacaccbcabababacaacaabbbaaabcbcc") ++ (C) ++ ("aaabbababbcbbbcbaabacbbbbccabbc"));
constraint
  (("cbcabaacb") ++ (C) ++ ("cbaaaaccbaaaaabccc") ++ (C) ++ ("bbbcaacacbacbcacacccbaacbbcccabaabaacbacbcbcbcbababbbabbcb"))
    =
    (("cbcabaacb") ++ (C) ++ ("cba") ++ (C) ++ ("cbaaaaabcccaaacbbbcaacacbacbcacacccbaacbbcccabaabaacbacbcbcbcbababbbabbcb"));
constraint
  (("bcbbcbccaaababbaccbcacacc") ++ (C) ++ ("bbaabbaccaabccacccccacbcaacbbacccbabaccacacacccbcbcbcccacbcacbac"))
    =
    (("bcbbcbccaaababbaccbcacaccaaacbbaabbaccaabccacccccacbcaacbbacccbabaccacacacccbcbcbcccacbcacbac") ++ (""));
constraint
  (("bcabcbcbaacbccccbacbbbbccabbccabcbcaccbbcbbbcabbaccaccbcaabaabbbacbaccabbcbbbaaaabbbbbaa") ++ (C) ++ ("c"))
    =
    (("bcabcbcbaacbccccbacbbbbccabbccabcbcaccbbcbbbcabbaccaccbcaabaabbbacbaccabbcbbbaaaabbbbbaa") ++ (C) ++ ("c"));
constraint
  (("cacccbcbbbbccbccaccbbcaccaacbcbbcaacbbcbaaabbbc") ++ (C) ++ ("cacbcbbcaacabbcabbaabbaacbbacabbcccacacbcb"))
    =
    (("cacccbcbbbbccbccaccbbcaccaacbcbbcaacbbcbaaabbbcaaaccacbcbbcaacabbcabbaabbaacbbacabbcccacacbcb") ++ (""));
constraint
  (("ccbababbbcbaabaabaaccccccacabacbbccccbbbbccbaacaacccabccb") ++ (B) ++ ("bbacabccacbccbaabababbacbcbcaba"))
    =
    (("ccbababbbcbaabaabaaccccccacabacbbccccbbbbccbaacaacccabccbacaaabbacabccacbccbaabababbacbcbcaba") ++ (""));
constraint
  (("accaccbccaacabaacaacbaccaabcabcacacabbabcaabbbcbacaaaacbcacccccaababbaabbcbaabbababbaabbacbac") ++ (""))
    =
    (("accaccbccaacabaacaacbaccaabcabcacacabbabcaabbbcbaca") ++ (C) ++ ("bcacccccaababbaabbcbaabbababbaabbacbac"));
constraint
  (("ccabcbcacbababbbbabaabacacaabccbbbaacbabbaa") ++ (C) ++ ("ccbabababaacabbbaccbacacacbbbaba") ++ (C) ++ ("cacaababca"))
    =
    (("ccabcbcacbababbbbabaabacacaabccbbbaacbabbaa") ++ (C) ++ ("ccbabababaacabbbaccbacacacbbbaba") ++ (C) ++ ("cacaababca"));
constraint
  (("abaabcbcbbccabcbaccaababacbabcaaabacacbbb") ++ (C) ++ ("cbabababcbacaabccaabaabaabccccabbbcbbaccbabbbacc"))
    =
    (("abaabcbcbbccabcbaccaababacbabcaaabacacbbb") ++ (C) ++ ("cbabababcbacaabccaabaabaabccccabbbcbbaccbabbbacc"));
constraint
  (("baaabbbccaabcabbabccbcabbbccacccbabcacaabaacaa") ++ (C) ++ ("abaaabaacbbacbaabccaabbcbabacccccbcbbbbbbac"))
    =
    (("baaabbbccaabcabbabccbcabbbccacccbabcacaabaacaa") ++ (C) ++ ("abaaabaacbbacbaabccaabbcbabacccccbcbbbbbbac"));
constraint
  (("ca") ++ (C) ++ ("acbabbacbcccabbabcabcabbcabccaacabbaccabbcaaabaacbabbababcbccbcbaccabccaacacababbbaaabc"))
    =
    (("ca") ++ (C) ++ ("acbabbacbcccabbabcabcabbcabccaacabbaccabbcaaabaacbabbababcbccbcbaccabccaacacababbbaaabc"));
constraint
  (("abcabcabacbaccaaaaabcababacba") ++ (C) ++ ("cbccabaccaccccabccacabbabaabcccaacbcaabcababaaccacbbacbabcac"))
    =
    (("abcabcabacbaccaaaaabcababacbaaaaccbccabaccaccccabccacabbabaabcccaacbcaabcababaaccacbbacbabcac") ++ (""));
constraint
  (("ccabbcbcccbccccacaabbaabccaaacbcbcbcccbbcaabbbabccbcbbcaaaccaabacaabacccccbcaccbacbbbaacbcbca") ++ (""))
    =
    (("ccabbcbcccbccccacaabbaabccaaacbcbcbcccbbcaabbbabccbcbbc") ++ (C) ++ ("caabacaabacccccbcaccbacbbbaacbcbca"));
constraint
  (("bcbcbacacaccaccccbccabaaaacacbbacbacbcbbcacbcbccbcaaccbacb") ++ (B) ++ ("baacabaabbaabbabaacbcbabbabacb"))
    =
    (("bcbcbacacaccaccccbccaba") ++ (C) ++ ("acbbacbacbcbbcacbcbccbcaaccbacbacaaabaacabaabbaabbabaacbcbabbabacb"));
constraint
  (("ccaaccacbb") ++ (C) ++ ("bcacbbaabcaccbaacbcabbcacaaaaaacbaccccaacacbabbaacabbcbcaccaacbbbcacacbcaabbccb"))
    =
    (("ccaaccacbb") ++ (C) ++ ("bcacbbaabcaccbaacbcabbcacaaaaaacbaccccaacacbabbaacabbcbcaccaacbbbcacacbcaabbccb"));
constraint
  (("cababbbcccacbabcbbcca") ++ (C) ++ ("bccaacbcbccbcbccaccbabacabaccacbcbcccabcaccbabccbaaaabcabbcbcacccbab"))
    =
    (("cababbbcccacbabcbbcca") ++ (C) ++ ("bccaacbcbccbcbccaccbabacabaccacbcbcccabcaccbabccbaaaabcabbcbcacccbab"));
constraint
  (("aabacbccaaaacbbacabbbcbacbaaccbbaccacacbb") ++ (C) ++ ("bbabcaabbaaabaaacacaccaccabcabbbcbaabbbba") ++ (C) ++ ("baa"))
    =
    (("aabacbcca") ++ (C) ++ ("bbacabbbcbacbaaccbbaccacacbbaaacbbabcaabbaaab") ++ (C) ++ ("acaccaccabcabbbcbaabbbbaaaacbaa"));
constraint
  (("acbcccabacbacabaccccabbccabcaaaccaacbcabbbacbbbbcaccccbcabacbbbabcbccccbacbbabccccbcbabcbabca") ++ (""))
    =
    (("acbcccabacbacabaccccabbccabc") ++ (C) ++ ("caacbcabbbacbbbbcaccccbcabacbbbabcbccccbacbbabccccbcbabcbabca"));
constraint
  (("babbcaabaabccaabbcbbcbcbbacaacabcaabcbbaccbcbaaaaabbcbbbaabbaabaacabcaccc") ++ (C) ++ ("caababbbcbaabaca"))
    =
    (("babbcaabaabccaabbcbbcbcbbacaacabcaabcbbaccbcbaaaaabbcbbbaabbaabaacabcaccc") ++ (C) ++ ("caababbbcbaabaca"));
constraint
  (("cbca") ++ (B) ++ ("bccbabbabcbbbbbcaaaaaabcbaacbabcaaacbcbabcbbacabacbaacaacbbabacccbacbbacacccbbbbacba"))
    =
    (("cbcaacaaabccbabbabcbbbbbcaaaaaabcbaacbabcaaacbcbabcbbacabacbaacaacbbabacccbacbbacacccbbbbacba") ++ (""));
constraint
  (("cbccaabaccacaabac") ++ (C) ++ ("aabccaaaccacbbbcabaacbcbcbaccbcbcbacaacbaabaccbcbbacaccbccacbcbbbcbcacbb"))
    =
    (("cbccaabaccacaabac") ++ (C) ++ ("aabccaaaccacbbbcabaacbcbcbaccbcbcbacaacbaabaccbcbbacaccbccacbcbbbcbcacbb"));
constraint
  (("bacbacca") ++ (B) ++ ("bcaaabccbcabbacccaaccbbaaccbccacccaccaaccbaaabbbbcabccbaacacababcbbaacaccabbabaa"))
    =
    (("bacbaccaacaaabcaaabccbcabbacccaaccbbaaccbccacccaccaaccbaaabbbbcabccbaacacababcbbaacaccabbabaa") ++ (""));
constraint
  (("cbbcb") ++ (B) ++ ("acabaabccabccbbcabbaacbaccbbbcccababcabcccccbccbaabcccaaacccccacbabaccacbcaabacacaa"))
    =
    (("cbbcbacaaaacabaabccabccbbcabbaacbaccbbbcccababcabcccccbccbaabccc") ++ (C) ++ ("ccccacbabaccacbcaabacacaa"));
constraint
  (("abccaaaabcbbccbcbbcacbccaabbabaaaacccbbbccbaacabaabacbaaccbccabbcaccbacacbcaccbbcbcccaccaabcc") ++ (""))
    =
    (("abccaaaabcbbccbcbbcacbccaabbaba") ++ (C) ++ ("ccbbbccbaacabaabacbaaccbccabbcaccbacacbcaccbbcbcccaccaabcc"));
constraint
  (("ccacacabcababaaccaccbcacccccbcbbbaaccbcccccbabbccbabcbcaaaabbbccacacccabbabaccbbbcabc") ++ (C) ++ ("cbca"))
    =
    (("ccacacabcababaaccaccbcacccccbcbbbaaccbcccccbabbccbabcbcaaaabbbccacacccabbabaccbbbcabcaaaccbca") ++ (""));
constraint
  (("caababbccbbbabccccbccbb") ++ (B) ++ ("abacbaacbbcbbcac") ++ (C) ++ ("cacabccbbacaabaaaacaabbaababbcabcaccbcbccacca"))
    =
    (("caababbccbbbabccccbccbbacaaaabacbaacbbcbbcac") ++ (C) ++ ("cacabccbbacaabaaaacaabbaababbcabcaccbcbccacca"));
constraint
  (("abcbbcabcacbccbaccbaccbcaaacabcaabccbcbabaabbabbcccccbbcbbcbccabacaaacbaaaaccabcbbbbcccbbbabc") ++ (""))
    =
    (("abcbbcabcacbccbaccbaccbc") ++ (C) ++ ("abcaabccbcbabaabbabbcccccbbcbbcbccabac") ++ (C) ++ ("ba") ++ (C) ++ ("cabcbbbbcccbbbabc"));
constraint
  (("cacbacbbacbcbbbcababbc") ++ (C) ++ ("babccacbbbbbbaccaccacbbccaabbaabcaabcbacacabcabbcccbcaccbabccaaccbb"))
    =
    (("cacbacbbacbcbbbcababbcaaacbabccacbbbbbbaccaccacbbccaabbaabcaabcbacacabcabbcccbcaccbabccaaccbb") ++ (""));
constraint
  (("abc") ++ (B) ++ ("bacbbbacbbcbcacccacabaaabcacbaacbcaaccaabcbccbabcbbbbbab") ++ (C) ++ ("bbcccbbabbcacabaabbcaaabc"))
    =
    (("abcacaaabacbbbacbbcbcacccacabaaabcacbaacbcaaccaabcbccbabcbbbbbab") ++ (C) ++ ("bbcccbbabbcacabaabbcaaabc"));
constraint
  (("baccbbccaacacbcbbaaaaabbbbaacaabbcbbbababbcccaabbaabacaaabbcbcbbcbacabbcbacaabaabcaaccabcacac") ++ (""))
    =
    (("baccbbccaacacbcbbaaaaabbbbaacaabbcbbbababbcccaabbaab") ++ (B) ++ ("bbcbcbbcbacabbcbacaabaabcaaccabcacac"));
constraint
  (("aacabbcaaacaccbaabaccbaababbcbaabbabaaaabcacbbacaaaabcbbacccccaababbbbabcbcbbcabcaabbcacbbbbb") ++ (""))
    =
    (("aacabbc") ++ (C) ++ ("accbaabaccbaababbcbaabbabaaaabcacbb") ++ (B) ++ ("abcbbacccccaababbbbabcbcbbcabcaabbcacbbbbb"));
constraint
  (("cbccbcccbaabcaaabcaabbcccababbaaaabacbabbabbacccacccbacaabaacccbbaaaaacbcaacbaccaccbbbbbcabac") ++ (""))
    =
    (("cbccbcccbaabcaaabcaabbcccababbaaaabacbabbabbacccacccbacaabaacccbbaa") ++ (C) ++ ("bcaacbaccaccbbbbbcabac"));
constraint
  (("bbcccbbcbacbcbabccccaaabbbbccccbccaccacbabcbccaabbacacbbabbbbcbbcba") ++ (C) ++ ("abbccaaaabaaaaabacccab"))
    =
    (("bbcccbbcbacbcbabccccaaabbbbccccbccaccacbabcbccaabbacacbbabbbbcbbcbaaaacabbccaaaabaaaaabacccab") ++ (""));
constraint
  (("bccbc") ++ (C) ++ ("aaabaaccbbcbacabbcabacbcacaaabcbcba") ++ (C) ++ ("aacbaccabaabccaaaccacabacbacbacaababacbabcaaa"))
    =
    (("bccbc") ++ (C) ++ ("aaabaaccbbcbacabbcabacbc") ++ (B) ++ ("bcbcba") ++ (C) ++ ("aacbaccabaabccaaaccacabacbacbacaababacbabcaaa"));
constraint
  (("ab") ++ (C) ++ ("caacbababbbcabcccabccbbabbabcabcbabbaaabbcacbbaabbbbcccaacbbbcaacbcbaaabaaccabccaccbccb"))
    =
    (("ab") ++ (C) ++ ("caacbababbbcabcccabccbbabbabcabcbabbaaabbcacbbaabbbbcccaacbbbcaacbcbaaabaaccabccaccbccb"));
constraint
  (("acaabbbccabcacabacbabbacaaabbccacbbbaabccccabcbbabcaabacacabaabacabb") ++ (C) ++ ("bbacbccaabcbaaccaabcc"))
    =
    (("acaabbbccabcacabacbabb") ++ (B) ++ ("bbccacbbbaabccccabcbbabcaabacacabaabacabb") ++ (C) ++ ("bbacbccaabcbaaccaabcc"));
constraint
  (("abcaccacccaabccbbbcaccccbbbacbabcabababbbcabacccbcabbbcaccbbccacaabcbcbbbbbacabaccb") ++ (C) ++ ("bcccba"))
    =
    (("abcaccacccaabccbbbcaccccbbbacbabcabababbbcabacccbcabbbcaccbbccacaabcbcbbbbbacabaccbaaacbcccba") ++ (""));
constraint
  (("caaccabbbcbbbaabacacbbcaccbcbccccacaacacbccccaaaaaacabbbabcbaaccbcc") ++ (B) ++ ("aaabcacbaacbaaaabcbbb"))
    =
    (("caaccabbbcbbbaabacacbbcaccbcbccccacaacacbccccaaaaaacabbbabcbaaccbccacaaaaaabcacbaacbaaaabcbbb") ++ (""));
constraint
  (("bcccbbcabccbaaccbcccbb") ++ (B) ++ ("bbaacbcabaacbcbbaccaabbcccbacccbbcbaccbaababcaaaababaabbbcbaacccac"))
    =
    (("bcccbbcabccbaaccbcccbbacaaabbaacbcabaacbcbbaccaabbcccbacccbbcbaccbaababcaaaababaabbbcbaacccac") ++ (""));
constraint
  (("acbccbabaaaacbbaaabaaaaaacabbaabcbccbacabcbccaacbacbcaaccbcbaccbcccacaaccbabccccbaaabc") ++ (C) ++ ("bca"))
    =
    (("acbccbabaaaacbbaaabaaaaaacabbaabcbccbacabcbccaacbacbcaaccbcbaccbcccacaaccbabccccbaaabc") ++ (C) ++ ("bca"));
constraint
  (("aababbccbbbccabbaaacbcacbbabaacbacbaacbaccabaabbccccabccbcabababcaabccbcbbcbbccabcacccabcabca") ++ (""))
    =
    (("aababbccbbbccabb") ++ (C) ++ ("bcacbbabaacbacbaacbaccabaabbccccabccbcabababcaabccbcbbcbbccabcacccabcabca"));
constraint
  (("accabbacaccaacacccbcaaabcbbbcbbbcabbacacaaccbcaccbbbbccbbacaabacbababbacaaaabccccc") ++ (C) ++ ("cbaaabb"))
    =
    (("accabbacaccaacacccbcaaabcbbbcbbbcabbacacaaccbcaccbbbbccbbacaabacbababbacaaaabcccccaaaccbaaabb") ++ (""));
constraint
  (("c") ++ (B) ++ ("caaccbbabbbbbcabccbcbccccaaabcacacbcbcbbaabaacacbacaccacccacccabcacabbacabaabcabccaccac"))
    =
    (("cac") ++ (C) ++ ("aaccbbabbbbbcabccbcbccccaaabcacacbcbcbbaabaacacbacaccacccacccabcacabbacabaabcabccaccac"));
constraint
  (("cbabacacaccaccbcbabccacabcccabaccaabcacbaaabaaacbbabcca") ++ (C) ++ ("ccbbcaaaababcccbcaccabbabbaacbccab"))
    =
    (("cbabacacaccaccbcbabccacabcccabaccaabcacbaaab") ++ (C) ++ ("bbabccaaaacccbbcaaaababcccbcaccabbabbaacbccab"));
constraint
  (("cacccbacbababbaacacbbabbbabacaaaaabbbaaccbcbcabcbbacbabccbcbbbcbab") ++ (B) ++ ("ac") ++ (C) ++ ("cbcabaabccbbbacb"))
    =
    (("cacccbacbababbaacacbbabbbabacaaaaabbbaaccbcbcabcbbacbabccbcbbbcbabacaaa") ++ (B) ++ ("ccbcabaabccbbbacb"));
constraint
  (("abbacbbabaccaabbbbabcccbccbaacabccbcbaacaccaacbcacab") ++ (C) ++ ("bbababbabccabbaaccacbaacaab") ++ (C) ++ ("bccbcc"))
    =
    (("abbacbbabaccaabbbbabcccbccbaacabccbcbaacaccaacbcacab") ++ (C) ++ ("bbababbabccabbaaccacbaacaab") ++ (C) ++ ("bccbcc"));
constraint
  (("bccabcacbabba") ++ (B) ++ ("acaabcabbbbcabaabaabacbbacbcaacc") ++ (C) ++ ("bcbbbbcbbcabbaaabaaaabaaabaa") ++ (C) ++ ("accabaa"))
    =
    (("bccabcacbabba") ++ (B) ++ ("acaabcabbbbcabaabaabacbbacbcaaccaaacbcbbbbcbbcabbaaabaaaabaaabaa") ++ (C) ++ ("accabaa"));
constraint
  (("accaaabcccaaccbcbbacbbccbabcccccbacaccbccbaabccbccacbaca") ++ (C) ++ ("caaccbbcbcbaaabcccaaaaabbacbcaaca"))
    =
    (("accaaabcccaaccbcbbacbbccbabcccccbacaccbccbaabccbccacbacaaaaccaaccbbcbcbaaabcccaaaaabbacbcaaca") ++ (""));
constraint
  (("aacbcbabbbbccaccbcabccbabaaabacbcbbbbaaabcaacaccbbcbbacaacabbc") ++ (C) ++ ("aaccaabbcaabcbcbbacabcaaccb"))
    =
    (("aacbcbabbbbccaccbcabccbabaaabacbcbbbbaaabcaacaccbbcbbacaacabbcaaacaaccaabbcaabcbcbbacabcaaccb") ++ (""));
constraint
  (("babcbaacaacbabbaccabbabbaabccabccabcbabcccbcccacacaaacccabaccbacaacaabacabbcbcacaaccaccbbcbbc") ++ (""))
    =
    (("babcbaacaacbabbaccabbabbaabccabccabcbabcccbcccacac") ++ (C) ++ ("ccabaccbacaacaabacabbcbcacaaccaccbbcbbc"));
constraint
  ((C) ++ ("cbcab") ++ (B) ++ ("bbcbbccacbacaabcbabacacccccbacbcbabccbacaacabacaacacbbaccbcaccaaabbbbabaacbbabc"))
    =
    ((C) ++ ("cbcab") ++ (B) ++ ("bbcbbccacbacaabcbabacacccccbacbcbabccbacaacabacaacacbbaccbcaccaaabbbbabaacbbabc"));
constraint
  (("accaacaccabbacabcabbabacabac") ++ (C) ++ ("bccacbcaaaacbbbccbabbbccbaacacbabbbaccbbcabbaaccabcbbcabaccaa"))
    =
    (("accaacaccabbacabcabbabacab") ++ (B) ++ ("cbccacbcaaaacbbbccbabbbccbaacacbabbbaccbbcabbaaccabcbbcabaccaa"));
constraint
  (("bbaacacccacbab") ++ (C) ++ ("acbbcabcabaabcbcbcbccac") ++ (C) ++ ("caccacbbbcaabcbccccbbbccbcbbaacbcbaaaacabbcccccc"))
    =
    (("bbaacacccacbab") ++ (C) ++ ("acbbcabcabaabcbcbcbccacaaaccaccacbbbcaabcbccccbbbccbcbbaacbcbaaaacabbcccccc"));
constraint
  (("bccaccbbaaccbbbaabaabcbaacabbcaccbcacaacba") ++ (C) ++ ("abaabccccbcaaaaaabcbaacbccacacbabcbbacccbbabaca"))
    =
    (("bccaccbbaaccbbbaabaabcbaacabbcaccbcacaacba") ++ (C) ++ ("abaabccccbcaaaaaabcbaacbccacacbabcbbacccbbabaca"));
constraint
  (("accbbcaccababaccacccaccbbaaabbccacbc") ++ (C) ++ ("caccbccbbcaccc") ++ (C) ++ ("ccbcbbccacaaabbbbccbcabbbbccbccabcb"))
    =
    (("accbbcaccababaccacccaccbbaaabbccacbc") ++ (C) ++ ("caccbccbbcacccaaacccbcbbcc") ++ (B) ++ ("bbbbccbcabbbbccbccabcb"));
constraint
  (("bccbcabcacaababbaabbaccccaaccabaaccaacabccbaaaccbbccab") ++ (B) ++ ("caacaacccaabbaacaabbabcbbbcbacacbc"))
    =
    (("bccbcabcacaababbaabbaccccaaccabaaccaacabccb") ++ (C) ++ ("cbbccab") ++ (B) ++ ("caacaacccaabbaacaabbabcbbbcbacacbc"));
constraint
  (("cbbcaccabcaccabcaaacccbcbacab") ++ (C) ++ ("aabcaaaaa") ++ (C) ++ ("acaccbabcccbccaabbbcbaaaacbbacacaccaccabbbbbaab"))
    =
    (("cbbcaccabcaccabc") ++ (C) ++ ("ccbcbacab") ++ (C) ++ ("aabcaaaaa") ++ (C) ++ ("acaccbabcccbccaabbbcba") ++ (C) ++ ("bbacacaccaccabbbbbaab"));
constraint
  (("caabaccacbbbccbabcacb") ++ (C) ++ ("babccbcbbbbaaacacbbcaaaabcacacccacccabacbbababcaccabcaccbaaaccbbabbb"))
    =
    (("caabaccacbbbccbabcacb") ++ (C) ++ ("babccbcbbbb") ++ (C) ++ ("acbbcaaaabcacacccacccabacbbababcaccabcaccbaaaccbbabbb"));
constraint
  (("ccbcbbabbcbc") ++ (B) ++ ("bcbbccaabcacbbbacabacccaabbbbaacbabbcbbbacccaacbaaababaabcbccacbaabbaabaccaa"))
    =
    (("ccbcbbabbcbcacaaabcbbccaabcacbbbacabacccaabbbbaacbabbcbbbacccaacbaaababaabcbccacbaabbaabaccaa") ++ (""));
solve satisfy;
