var string: F;
var string: E;
var string: C;
constraint
  (("bdcbbacbbacaccddc") ++ (F) ++ ("aacadbbabbcdaaccdbacd")) =
    (("bdcbbacbbacaccddc") ++ (E) ++ ("acadbbabbcdaaccdbacd"));
constraint
  (("ccdcccbcdd") ++ (C) ++ ("b") ++ (C) ++ ("abbbaac") ++ (F) ++ ("aabababcdbdbcaabc"))
    = (("ccdcccbcdd") ++ (E) ++ ("abbbaacdbbdcadaaadbdaabababcdbdbcaabc"));
constraint
  (("aabdaaaaccadaaaadc") ++ (C) ++ ("cdcbbacccbbdabdbaabdcccbabadcddad")) =
    (("aabdaaaaccadaaaadcbddcdcbbacccbbdabdbaabdcccbabadcddad") ++ (""));
constraint
  (("abbbadacaadabddabddabcbabcbadbccbadddbbbbbcabbdacbcbdd") ++ ("")) =
    (("abbbadacaada") ++ (C) ++ ("a") ++ (C) ++ ("abcbabcbadbccbadddbbbbbcabbdacbc") ++ (C));
constraint
  (("cbcbcadbabbaacb") ++ (C) ++ ("dacbabbaaadbabdbabbddb") ++ (C) ++ ("ccabbbbccad"))
    =
    (("cbcbcadbabbaacb") ++ (C) ++ ("dacbabbaaadbabdbab") ++ (E) ++ ("ccabbbbccad"));
constraint
  (("abcdadabbcbbbddbcdaaba") ++ (C) ++ ("bdabddaaddcaddcaddcbbbdcddaaa")) =
    (("abcdadabbcbb") ++ (C) ++ ("bcdaaba") ++ (C) ++ ("bdabddaaddcaddcaddcbbbdcddaaa"));
constraint
  (("cddcbdcadcddbdadc") ++ (C) ++ ("cbbdbaccbdacdbbbaddadadadacdaabbad")) =
    (("cddcbdcadcddbdadcbddcbbdbaccbdacdbbbaddadadadacdaabbad") ++ (""));
constraint
  (("aadccdabaddabdcdbbabcaabbdcbcbadbbbdccabbddbbaadddaabc") ++ ("")) =
    (("aadccdabaddabdcdbbabcaabbdcbcbadbbbdccab") ++ (C) ++ ("bbaadddaabc"));
constraint
  (("cddccbdbabdbaabcbabacbdbddccdbaddcbddadddcd") ++ (C) ++ ("dccadbab")) =
    (("cddccbdbabdbaabcbabacbdbddccdbaddcbddadddcd") ++ (C) ++ ("dccadbab"));
constraint
  (("baadbdbbbdc") ++ (C) ++ ("cabcabbdaabdbacbabbaabbccdbabdbacccaabdb")) =
    (("baadbdbbbdc") ++ (C) ++ ("cabcabbdaabdbacbabbaabbccdbabdbacccaabdb"));
constraint
  (("dbdbacaddadcbdbaacbcdcaddbbdaadaaccbcaadbdddddadddabdc") ++ ("")) =
    (("dbdbacaddadcbdbaacbcdcaddbbdaadaaccbcaad") ++ (C) ++ ("dddadddabdc"));
constraint
  (("bdadcaccbabbbbabbaabddbcdcadbdcadcacbdbaabacdccdadbbac") ++ ("")) =
    (("bdadcaccbabbbbabbaa") ++ (C) ++ ("bcdcadbdcadcacbdbaabacdccdadbbac"));
constraint
  (("acaacdcbbccbbcbbcbbabaddd") ++ (C) ++ ("cdbadbbbaddbccbbdcdabdddac")) =
    (("acaacdcbbccbbcbbcbbabadddbddcdbadbbbaddbccbbdcda") ++ (C) ++ ("dac"));
constraint
  (("dcccdcacdacacabdabdacdcddbabaabddbbbbacaaabd") ++ (C) ++ ("dcbaaca")) =
    (("dcccdcacdacacabdabdacdcddbabaa") ++ (C) ++ ("bbbbacaaabdbdddcbaaca"));
constraint
  (("cccbdabbaadbccbdaadc") ++ (C) ++ ("dcccbaaaaabcadadbdaacadbccbadcb")) =
    (("cccbdabbaadbccbdaadcbdddcccbaaaaabcadadbdaacadbccbadcb") ++ (""));
constraint
  (("bcccbdc") ++ (C) ++ ("aacbcaccdbdaddabdbbabaacccaabbcdbdaccddaddbb")) =
    (("bcccbdc") ++ (C) ++ ("aacbcaccdbdaddabdbbabaacccaabbcdbdaccddaddbb"));
constraint
  ((C) ++ ("aaabacdaccbbbaadcdadcbccbcdbcbbaaacbccbbabbcbbcdccd") ++ ("")) =
    ((C) ++ ("aaabacdaccbbbaadcdadcbccbcdbcbbaaacbccbbabbcbbcdccd") ++ (""));
constraint
  (("bacadcbddabcabbdcddacccbadbddcbdc") ++ (C) ++ ("adcccddcdddacccaaa")) =
    (("bacadc") ++ (C) ++ ("abcabbdcddacccbad") ++ (C) ++ ("cbdc") ++ (C) ++ ("adcccddcdddacccaaa"));
constraint
  (("bac") ++ (C) ++ ("aaaadacddccbcbbcadbccaaacacabcaabbcbdadbcdacacaa")) =
    (("bacbddaaaadacddccbcbbcadbccaaacacabcaabbcbdadbcdacacaa") ++ (""));
constraint
  (("cdcbdbddbacdcdcacdaabdaaaddacbdccdaddbcaaaacabdaccacdb") ++ ("")) =
    (("cdcbd") ++ (C) ++ ("bacdcdcacdaabdaaaddacbdccdaddbcaaaacabdaccacdb"));
constraint
  (("bbbbcbcdaabcdaabddcbcaaababdbdcaacacbddabbbabaaaddbdba") ++ ("")) =
    (("bbbbcbcdaabcdaabddcbcaaababdbdcaacac") ++ (C) ++ ("abbbabaaaddbdba"));
constraint
  (("ccdcbacbdacdadcdaaabcccaadbabaaac") ++ (C) ++ ("aaaaccdaacbbcdbbbd")) =
    (("ccdcbacbdacdadcdaaabcccaadbabaaac") ++ (C) ++ ("aaaaccdaacbbcdbbbd"));
constraint
  (("ddbbbdcdbdbdcdcd") ++ (C) ++ ("adaabdcdcdccbddacbaaadcbbcaaddaacca")) =
    (("ddbbbdcdbdbdcdcdbddadaabdcdcdccbddacbaaadcbbcaaddaacca") ++ (""));
constraint
  (("bddcabccbaabbadbbbdc") ++ (C) ++ ("dabaaccacbadbcbbdcdcdbbdbcadbdd")) =
    (("bddcabccbaabbadbbbdcbdddabaaccacbadbcbbdcdcdbbdbcadbdd") ++ (""));
constraint
  (("ddcbdccbabbbddcbdbadccccbcbdbccbbccbbdcbdbcbdcbddbcbac") ++ ("")) =
    (("ddcbdccbabb") ++ (C) ++ ("cbdbadccccbcbdbccbbccbbdcbdbcbdcbddbcbac"));
constraint
  (("dadaabccaabddbdcdcbaacacccdcdabdddbddbbaacdabccdcadabd") ++ ("")) =
    (("dadaabccaabddbdcdcbaacacccdcdabddd") ++ (C) ++ ("bbaacdabccdcadabd"));
constraint
  (("ddacbbcacbabaccbbdbadbdccaaabcbddaacbaccddcbabddbcdabc") ++ ("")) =
    (("ddacbbcacbabaccbbdbadbdccaaabc") ++ (C) ++ ("aacbaccddcbabddbcdabc"));
constraint
  (("abbdadcabdbbcdbcdabdcbd") ++ (C) ++ ("acdcbbaddbccdbaadbccbccbdaca")) =
    (("abbdadcabdbbcdbcdabdcbd") ++ (C) ++ ("acdcbbaddbccdbaadbccbccbdaca"));
constraint
  (("bbbdcbddbccbbaddbbababbdbaccabddbbcbcdcabbbdabcddbaaca") ++ ("")) =
    (("bbbdcbddbccbbaddbbababbdbacca") ++ (C) ++ ("bbcbcdcabbbdabcddbaaca"));
constraint
  (("dabbdd") ++ (C) ++ ("bdabbbdac") ++ (C) ++ ("bbdaddcabbabaaaabdcbcccdbbbccbdaa"))
    =
    (("dab") ++ (C) ++ ("bddbdabbbdacbddbbdaddcabbabaaaabdcbcccdbbbccbdaa"));
constraint
  (("bdcab") ++ (C) ++ ("a") ++ (C) ++ ("babbbadaddaddaadcadcacdabbcabbadccaadcddcb"))
    = (("bdcabbddabddbabbbadaddaddaadcadcacdabbcabbadccaadcddcb") ++ (""));
constraint
  (("abbbbbadaddaddbcadcccccdacdddcdbaabcdcbcadbcdadd") ++ (C) ++ ("dab")) =
    (("abbbbbadaddaddbcadcccccdacdddcdbaabcdcbcadbcdadd") ++ (C) ++ ("dab"));
constraint
  (("bccdbdcabbadabcbdbbcdbccdc") ++ (C) ++ ("bdbdbadadcdbbdaaadacdaadd")) =
    (("bccdbdcabbadabcbdbbcdbccdc") ++ (C) ++ ("bdbdbadadcdbbdaaadacdaadd"));
constraint
  (("a") ++ (C) ++ ("abbadbcbdcaccaddcbbaabbccdbddadad") ++ (C) ++ ("abbcbabddbaaac"))
    = (("abddabbadbcbdcaccaddcbbaabbccdbddadadbddabbcbabddbaaac") ++ (""));
constraint
  (("caabcababccbcdaccdd") ++ (C) ++ ("adaacacacbaabdabdbaccacdccddddac")) =
    (("caabcababccbcdaccdd") ++ (C) ++ ("adaacacacbaabdabdbaccacdccddddac"));
constraint
  (("abcbbcbbbbcbbdcbbbaccadbbbdaabc") ++ (C) ++ ("abbdcccdcdbdaadbabcb")) =
    (("abcbbcbbbbcbbdcbbbaccadbbbdaabcbddabbdcccdcdbdaadbabcb") ++ (""));
constraint
  (("adcddabbaabbddbabcdcadaaaddb") ++ (C) ++ ("ccacdadba") ++ (C) ++ ("cdbcddccddb"))
    =
    (("adcddabbaab") ++ (C) ++ ("babcdcadaaaddbbddccacdadba") ++ (C) ++ ("cdbcddccddb"));
constraint
  (("cdcdddaabdbbddabaacacddbbacadcadacddbabadada") ++ (C) ++ ("ccacbbd")) =
    (("cdcdddaabdbbddabaacacddbbacadcadacddbabadada") ++ (C) ++ ("ccacbbd"));
constraint
  (("abbdbcbbdcdccccadaacdcbbdadccbadbdcadcdbcddabcbdcd") ++ (C) ++ ("d")) =
    (("abbdbcbbdcdccccadaacdcbbdadccbadbdcadcdbcddabcbdcdbddd") ++ (""));
constraint
  (("bbbadaccaadcdcdbaacdacba") ++ (C) ++ ("bbbdacdcadadbdaccdccaadddbc")) =
    (("bbbadaccaadcdcdbaacdacbabddbbbdacdcadadbdaccdccaadddbc") ++ (""));
constraint
  (("dcacabaccabcaabdbbcbddbccadbacccbaaddcbcdcdbaabdaaccad") ++ ("")) =
    (("dcacabaccabcaabdbbc") ++ (C) ++ ("bccadbacccbaaddcbcdcdbaabdaaccad"));
constraint
  (("cbdcaadbccaccddbdcddbcacacadcaccbdcddddccdbabdcbdabbdd") ++ ("")) =
    (("cbdcaadbccaccddbdcddbcacacadcaccbdcddddccdbabdcbdab") ++ (C));
constraint
  (("acdbadc") ++ (C) ++ ("baddcdcbadbcccbabbdccacadbbaccaddadbdcabacda")) =
    (("acdbadc") ++ (C) ++ ("baddcdcbadbcccbabbdccacadbbaccaddadbdcabacda"));
constraint
  (("addaddbcabcdabaacdb") ++ (C) ++ ("dbcdcaaadcbdbdabcbcccbbcbaacaddd")) =
    (("addaddbcabcdabaacdb") ++ (C) ++ ("dbcdcaaadcbdbdabcbcccbbcbaacaddd"));
constraint
  (("bbcabaddcbcadcacdbacabbccbdddba") ++ (C) ++ ("cddddccddcdadcdcbadc")) =
    (("bbcabaddcbcadcacdbacabbccbdddba") ++ (C) ++ ("cddddccddcdadcdcbadc"));
constraint
  (("aa") ++ (C) ++ ("ddacccdacbcddcaacabbdaadacbabcdcacbbdcdddbbbcacbb")) =
    (("aabddddacccdacbcddcaacabbdaadacbabcdcacbbdcdddbbbcacbb") ++ (""));
constraint
  (("ccadcbaaddba") ++ (C) ++ ("accdbccbdaaaabadcaddddbccaabcacbdada") ++ (C))
    =
    (("ccadcbaaddba") ++ (C) ++ ("accdbccbdaaaabadcaddddbccaabcacbdadabdd"));
constraint
  (("babaaacdccbabcaddbcdadddccbacddbcdbbdbba") ++ (C) ++ ("aadadbbbbbb")) =
    (("babaaacdccbabcaddbcdadddccbacddbcdbbdbba") ++ (C) ++ ("aadadbbbbbb"));
constraint
  (("aaccabdbdbbabdbdbbddcccb") ++ (C) ++ ("dddccbabacdabaaadacbadcbdaa")) =
    (("aaccabdbdbbabdbdb") ++ (C) ++ ("cccb") ++ (C) ++ ("dddccbabacdabaaadacbadcbdaa"));
constraint
  (("bcdbcbacbdddccaccdbbddabbdaacaadcadbbaabcccacaabbaddbc") ++ ("")) =
    (("bcdbcbac") ++ (C) ++ ("dccaccdb") ++ (C) ++ ("abbdaacaadcadbbaabcccacaabbaddbc"));
constraint
  (("adcaccdcdabc") ++ (C) ++ ("daadbaccccdaccadaaaaadbbbaacaccacdccadd")) =
    (("adcaccdcdabcbdddaadbaccccdaccadaaaaadbbbaacaccacdccadd") ++ (""));
constraint
  (("acbdddcbabbcbabacbadabbdbdabbbbaabcdcdbccbaccbbcbcabbb") ++ ("")) =
    (("ac") ++ (C) ++ ("dcbabbcbabacbadabbdbdabbbbaabcdcdbccbaccbbcbcabbb"));
constraint
  (("bbccaddddbadcaacaacdbcacaacadadb") ++ (C) ++ ("ccdbadcccbbcdbcbbda")) =
    (("bbccaddddbadcaacaacdbcacaacadadb") ++ (C) ++ ("ccdbadcccbbcdbcbbda"));
constraint
  (("cbdaddddbbacabbbabbb") ++ (C) ++ ("cbb") ++ (C) ++ ("caccadaabcbccadbaaccbbaac"))
    =
    (("cbdaddddbbacabbbabbbbddcbb") ++ (C) ++ ("caccadaabcbccadbaaccbbaac"));
constraint
  (("cdaacbaadb") ++ (C) ++ ("dcaaccabddbcbbcaddbbcdbdbdcbdbdbbaaddadbc")) =
    (("cdaacbaadb") ++ (C) ++ ("dcaaccabddbcbbcaddbbcdbdbdcbdbdbbaaddadbc"));
constraint
  (("abcaabadacdcaaadbdbadccaaabaabcccbcbcdbdbbbdddcbaabbcd") ++ ("")) =
    (("abcaabadacdcaaadbdbadccaaabaabcccbcbcdbdbb") ++ (C) ++ ("dcbaabbcd"));
constraint
  (("cbadadadba") ++ (C) ++ ("cbbbbabdadbbddcdddccbbdbcbaadadbbbcbbbbbc")) =
    (("cbadadadbabddcbbbbabdadbbddcdddccbbdbcbaadadbbbcbbbbbc") ++ (""));
constraint
  (("ccdadabdbbadac") ++ (C) ++ ("bbdbbdadddbcdddbaadbacccbdcabccccccaa")) =
    (("ccdadabdbbadac") ++ (C) ++ ("bbdbbdadddbcdddbaadbacccbdcabccccccaa"));
constraint
  (("a") ++ (C) ++ ("bcacbadbabdcbacbddadaccddcdacabbccdbcddcccbbcdabac")) =
    (("a") ++ (C) ++ ("bcacbadbabdcbac") ++ (C) ++ ("adaccddcdacabbccdbcddcccbbcdabac"));
constraint
  (("bbcacbabdbddbccbbdbbdcadaadcdacddabcaacbadcadcabdcacda") ++ ("")) =
    (("bbcacbabd") ++ (C) ++ ("bccbbdbbdcadaadcdacddabcaacbadcadcabdcacda"));
constraint
  (("aacddbbcccdddacdcddcbddaccddddbcbadaadccadbcdccaaabddb") ++ ("")) =
    (("aacddbbcccdddacdcddc") ++ (C) ++ ("accddddbcbadaadccadbcdccaaa") ++ (C) ++ ("b"));
solve satisfy;
